Repository googleapis/google-cloud-ruby, pull requests merged in 2018-09, with the labels that each got.

#2398 Remove unwanted synth transform for monitoring rubocop config
  google-cloud-monitoring/synth.py
Labels: cla: yes

#2399 Regenerate asset library using synth
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_services_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/asset_service.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/assets.rb
Labels: cla: yes

#2400 Fix typos in documentation
  google-cloud-bigquery/acceptance/bigquery/table_reference_test.rb
  google-cloud-bigquery/acceptance/bigquery/table_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
Labels: cla: yes, type: cleanup

#2401 Fix link of stackdriver documentation
  google-cloud-debugger/README.md
  google-cloud-error_reporting/README.md
  google-cloud-logging/README.md
  google-cloud-trace/README.md
Labels: api: debugger, api: error reporting, api: logging, api: trace, cla: yes, type: docs

#2411 Update to jsondoc-forwarder-0.2.0.js
  index.html
  js/vendor/jsondoc-forwarder-0.2.0.js
Labels: cla: yes, type: docs

#2414 Add Object Lifecycle Management to Storage Bucket
  google-cloud-storage/acceptance/storage/bucket_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/bucket/cors.rb
  google-cloud-storage/lib/google/cloud/storage/bucket/lifecycle.rb
  google-cloud-storage/lib/google/cloud/storage/convert.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/google/cloud/storage/bucket_test.rb
  google-cloud-storage/test/google/cloud/storage/bucket_update_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_update_test.rb
  google-cloud-storage/test/google/cloud/storage/project_test.rb
  google-cloud-storage/test/helper.rb
Labels: api: storage, cla: yes

#2412 add notice of updated gems
  .kokoro/build.bat
  .kokoro/build.sh
  .kokoro/docker/windows/Dockerfile
  Rakefile
Labels: cla: yes

#2416 fix kokoro continuous failure
  .kokoro/build.sh
Labels: cla: yes

#2418 kokoro update
  .kokoro/build.sh
  .kokoro/docker/windows/Dockerfile
  .kokoro/trampoline.sh
Labels: cla: yes, do not merge

#2420 Use Rake::Task#invoke instead of sh
  Rakefile
  gcloud/Rakefile
  google-cloud-asset/Rakefile
  google-cloud-asset/synth.py
  google-cloud-bigquery-data_transfer/Rakefile
  google-cloud-bigquery-data_transfer/synth.py
  google-cloud-bigquery/Rakefile
  google-cloud-bigtable/Rakefile
  google-cloud-container/Rakefile
  google-cloud-container/synth.py
  google-cloud-core/Rakefile
  google-cloud-dataproc/Rakefile
  google-cloud-dataproc/synth.py
  google-cloud-datastore/Rakefile
  google-cloud-debugger/Rakefile
  google-cloud-dialogflow/Rakefile
  google-cloud-dialogflow/synth.py
  google-cloud-dlp/Rakefile
  google-cloud-dns/Rakefile
  google-cloud-env/Rakefile
  google-cloud-error_reporting/Rakefile
  google-cloud-firestore/Rakefile
  google-cloud-kms/Rakefile
  google-cloud-kms/synth.py
  google-cloud-language/Rakefile
  google-cloud-language/synth.py
  google-cloud-logging/Rakefile
  google-cloud-monitoring/Rakefile
  google-cloud-os_login/Rakefile
  google-cloud-pubsub/Rakefile
  google-cloud-redis/Rakefile
  google-cloud-redis/synth.py
  google-cloud-resource_manager/Rakefile
  google-cloud-spanner/Rakefile
  google-cloud-speech/Rakefile
  google-cloud-storage/Rakefile
  google-cloud-tasks/Rakefile
  google-cloud-tasks/synth.py
  google-cloud-text_to_speech/Rakefile
  google-cloud-trace/Rakefile
  google-cloud-translate/Rakefile
  google-cloud-video_intelligence/Rakefile
  google-cloud-vision/Rakefile
  google-cloud/Rakefile
  stackdriver-core/Rakefile
  stackdriver/Rakefile
Labels: cla: yes, type: cleanup

#2427 Fix loaded_files test to pass in coverage
  google-cloud-core/test/google/cloud/loaded_files_test.rb
Labels: api: core, cla: yes, type: cleanup

#2426 Use Rake::TestTask for running tests
  gcloud/Rakefile
  google-cloud-asset/Rakefile
  google-cloud-asset/synth.py
  google-cloud-bigquery-data_transfer/Rakefile
  google-cloud-bigquery-data_transfer/synth.py
  google-cloud-bigquery/Rakefile
  google-cloud-bigtable/Rakefile
  google-cloud-container/Rakefile
  google-cloud-container/synth.py
  google-cloud-core/Rakefile
  google-cloud-dataproc/Rakefile
  google-cloud-dataproc/synth.py
  google-cloud-datastore/Rakefile
  google-cloud-debugger/Rakefile
  google-cloud-dialogflow/Rakefile
  google-cloud-dialogflow/synth.py
  google-cloud-dlp/Rakefile
  google-cloud-dns/Rakefile
  google-cloud-env/Rakefile
  google-cloud-error_reporting/Rakefile
  google-cloud-firestore/Rakefile
  google-cloud-kms/Rakefile
  google-cloud-kms/synth.py
  google-cloud-language/Rakefile
  google-cloud-language/synth.py
  google-cloud-logging/Rakefile
  google-cloud-monitoring/Rakefile
  google-cloud-os_login/Rakefile
  google-cloud-pubsub/Rakefile
  google-cloud-redis/Rakefile
  google-cloud-redis/synth.py
  google-cloud-resource_manager/Rakefile
  google-cloud-spanner/Rakefile
  google-cloud-speech/Rakefile
  google-cloud-storage/Rakefile
  google-cloud-tasks/Rakefile
  google-cloud-tasks/synth.py
  google-cloud-text_to_speech/Rakefile
  google-cloud-trace/Rakefile
  google-cloud-translate/Rakefile
  google-cloud-video_intelligence/Rakefile
  google-cloud-vision/Rakefile
  google-cloud/Rakefile
  stackdriver-core/Rakefile
  stackdriver/Rakefile
Labels: cla: yes, type: cleanup

#2428 Add missing standard types to Datastore docs
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/protobuf/struct.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/protobuf/timestamp.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/type/latlng.rb
Labels: cla: yes

#2430 Releases for 2018-19-12
  gcloud/CHANGELOG.md
  gcloud/gcloud.gemspec
  gcloud/lib/gcloud/version.rb
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/google-cloud-bigtable.gemspec
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/google-cloud-datastore.gemspec
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/google-cloud-debugger.gemspec
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
  google-cloud-dns/CHANGELOG.md
  google-cloud-dns/google-cloud-dns.gemspec
  google-cloud-dns/lib/google/cloud/dns/version.rb
  google-cloud-env/CHANGELOG.md
  google-cloud-env/google-cloud-env.gemspec
  google-cloud-env/lib/google/cloud/env/version.rb
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/google-cloud-error_reporting.gemspec
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/google-cloud-firestore.gemspec
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/google-cloud-logging.gemspec
  google-cloud-logging/lib/google/cloud/logging/version.rb
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/google-cloud-pubsub.gemspec
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
  google-cloud-resource_manager/CHANGELOG.md
  google-cloud-resource_manager/google-cloud-resource_manager.gemspec
  google-cloud-resource_manager/lib/google/cloud/resource_manager/version.rb
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/google-cloud-spanner.gemspec
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/google-cloud-storage.gemspec
  google-cloud-storage/lib/google/cloud/storage/version.rb
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/google-cloud-trace.gemspec
  google-cloud-trace/lib/google/cloud/trace/version.rb
  google-cloud-translate/CHANGELOG.md
  google-cloud-translate/google-cloud-translate.gemspec
  google-cloud-translate/lib/google/cloud/translate/version.rb
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/google-cloud-vision.gemspec
  google-cloud-vision/lib/google/cloud/vision/version.rb
  google-cloud/CHANGELOG.md
  google-cloud/google-cloud.gemspec
  google-cloud/lib/google/cloud/version.rb
  stackdriver-core/CHANGELOG.md
  stackdriver-core/lib/stackdriver/core/version.rb
  stackdriver-core/stackdriver-core.gemspec
  stackdriver/CHANGELOG.md
  stackdriver/lib/stackdriver/version.rb
  stackdriver/stackdriver.gemspec
Labels: cla: yes

#2432 Release google-cloud-core 1.2.6
  google-cloud-core/CHANGELOG.md
  google-cloud-core/google-cloud-core.gemspec
  google-cloud-core/lib/google/cloud/core/version.rb
Labels: cla: yes

#2437 Remove verbose flag from test rake tasks
  google-cloud-bigquery-data_transfer/Rakefile
  google-cloud-bigquery/Rakefile
  google-cloud-bigtable/Rakefile
  google-cloud-container/Rakefile
  google-cloud-dataproc/Rakefile
  google-cloud-datastore/Rakefile
  google-cloud-debugger/Rakefile
  google-cloud-dlp/Rakefile
  google-cloud-dns/Rakefile
  google-cloud-error_reporting/Rakefile
  google-cloud-firestore/Rakefile
  google-cloud-language/Rakefile
  google-cloud-logging/Rakefile
  google-cloud-monitoring/Rakefile
  google-cloud-pubsub/Rakefile
  google-cloud-spanner/Rakefile
  google-cloud-speech/Rakefile
  google-cloud-storage/Rakefile
  google-cloud-trace/Rakefile
  google-cloud-translate/Rakefile
  google-cloud-video_intelligence/Rakefile
  google-cloud-vision/Rakefile
Labels: cla: yes, testing, type: cleanup

#2438 Fix redis synth script
  google-cloud-redis/synth.py
Labels: cla: yes

#2433 Update google-cloud README
  google-cloud/README.md
Labels: cla: yes, type: docs

#2439 Use bigquery-public-data project for tests
  google-cloud-bigquery/acceptance/bigquery/bigquery_test.rb
  google-cloud-bigquery/acceptance/bigquery/dataset_access_test.rb
  google-cloud-bigquery/acceptance/bigquery/dataset_reference_test.rb
  google-cloud-bigquery/acceptance/bigquery/dataset_test.rb
  google-cloud-bigquery/acceptance/bigquery/view_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/query_job_test.rb
Labels: api: bigquery, cla: yes

#2441 Fix circular require warnings
  google-cloud-bigquery/lib/google-cloud-bigquery.rb
  google-cloud-bigtable/lib/google-cloud-bigtable.rb
  google-cloud-datastore/lib/google-cloud-datastore.rb
  google-cloud-debugger/lib/google-cloud-debugger.rb
  google-cloud-dns/lib/google-cloud-dns.rb
  google-cloud-error_reporting/lib/google-cloud-error_reporting.rb
  google-cloud-firestore/lib/google-cloud-firestore.rb
  google-cloud-logging/lib/google-cloud-logging.rb
  google-cloud-pubsub/lib/google-cloud-pubsub.rb
  google-cloud-resource_manager/lib/google-cloud-resource_manager.rb
  google-cloud-spanner/lib/google-cloud-spanner.rb
  google-cloud-storage/lib/google-cloud-storage.rb
  google-cloud-trace/lib/google-cloud-trace.rb
  google-cloud-translate/lib/google-cloud-translate.rb
  google-cloud-vision/lib/google-cloud-vision.rb
  google-cloud/lib/google-cloud.rb
Labels: api: core, cla: yes, type: cleanup

#2442 Fix tip-level rake test tasks
  Rakefile
Labels: cla: yes, type: cleanup

#2444 Fix bigtable's overview guide
  google-cloud-bigtable/OVERVIEW.md
Labels: cla: yes

#2440 Add labels to Pub/Sub Snapshot, Subscription and Topic
  google-cloud-pubsub/.rubocop.yml
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/project.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/snapshot.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/test/google/cloud/pubsub/project_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/subscribe_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: api: pubsub, cla: yes

#2445 Quick copy editing pass through the bigtable docs
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
Labels: cla: yes

#2447 Fix for tableadmin sample intersection gc rule
  google-cloud-bigtable/samples/tableadmin.rb
Labels: cla: yes

#2449 Pub/Sub update labels
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/snapshot.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/test/google/cloud/pubsub/snapshot_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/update_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/update_test.rb
Labels: api: pubsub, cla: yes

#2450 Fix Logger's add_trace_id method
  google-cloud-logging/lib/google/cloud/logging/logger.rb
Labels: api: debugger, api: logging, cla: yes, type: bug

#2462 Switch to codecov for coverage report
  Gemfile
  README.md
  Rakefile
Labels: cla: yes, type: cleanup

#2448 Make Logger thread-safe
  google-cloud-logging/lib/google/cloud/logging/logger.rb
  google-cloud-logging/test/google/cloud/logging/logger_test.rb
Labels: api: logging, cla: yes, type: feature request

#2467 Skip drop rows acceptance tests
  google-cloud-bigtable/acceptance/bigtable/table/drop_rows_test.rb
Labels: api: bigtable, cla: yes, testing

#2469 Fix acceptance test for bigtable drop rows
  google-cloud-bigtable/acceptance/bigtable/table/drop_rows_test.rb
Labels: cla: yes

#2464 Add array conformance tests
  google-cloud-firestore/Rakefile
  google-cloud-firestore/conformance/test-suite.binproto
  google-cloud-firestore/lib/google/cloud/firestore/field_value.rb
  google-cloud-firestore/test/google/cloud/firestore/conformance_test.rb
Labels: api: firestore, cla: yes, testing

#2471 Fix for comparing NaN values
  google-cloud-firestore/lib/google/cloud/firestore/query.rb
Labels: api: firestore, cla: yes, type: bug

#2472 Fix Codecov badge image link
  README.md
Labels: cla: yes, type: cleanup, type: docs

#2474 Fix google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/CHANGELOG.md
Labels: cla: yes

#2452 Update RELEASING.md
  RELEASING.md
Labels: cla: yes, type: docs

#2475 Use ThreadLocalVar for RequestInfo
  google-cloud-logging/google-cloud-logging.gemspec
  google-cloud-logging/lib/google/cloud/logging/logger.rb
  google-cloud-logging/test/google/cloud/logging/logger_test.rb
Labels: api: logging, cla: yes

#2487 Support Object Localization
  acceptance/data/bicycle.jpg
  google-cloud-vision/.rubocop.yml
  google-cloud-vision/acceptance/vision/vision_test.rb
  google-cloud-vision/acceptance/vision_helper.rb
  google-cloud-vision/lib/google-cloud-vision.rb
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/lib/google/cloud/vision/annotate.rb
  google-cloud-vision/lib/google/cloud/vision/annotation.rb
  google-cloud-vision/lib/google/cloud/vision/annotation/normalized_vertex.rb
  google-cloud-vision/lib/google/cloud/vision/annotation/object_localization.rb
  google-cloud-vision/lib/google/cloud/vision/image.rb
  google-cloud-vision/lib/google/cloud/vision/project.rb
  google-cloud-vision/support/doctest_helper.rb
  google-cloud-vision/test/google/cloud/vision/annotation/object_localization_test.rb
  google-cloud-vision/test/google/cloud/vision/annotation_test.rb
  google-cloud-vision/test/google/cloud/vision/image/annotate_test.rb
  google-cloud-vision/test/google/cloud/vision/project_test.rb
  google-cloud-vision/test/helper.rb
Labels: api: vision, cla: yes

#2488 Release google-cloud-vision 0.31.0
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: api: vision, cla: yes

#2483 Fix Google::Cloud::Bigtable::Row#cells documentation for return value
  google-cloud-bigtable/lib/google/cloud/bigtable/row.rb
Labels: api: bigtable, cla: yes, type: docs

#2489 Firestore conformance tests for empty map
  google-cloud-firestore/conformance/test-suite.binproto
Labels: api: firestore, cla: yes, testing

#2477 Add Bigtable Emulator support
  google-cloud-bigtable/.yardopts
  google-cloud-bigtable/EMULATOR.md
  google-cloud-bigtable/OVERVIEW.md
  google-cloud-bigtable/google-cloud-bigtable.gemspec
  google-cloud-bigtable/lib/google-cloud-bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/service.rb
  google-cloud-bigtable/test/google/cloud/bigtable_test.rb
Labels: api: bigtable, cla: yes, type: feature request

#2490 Remove focus from acceptance tests
  google-cloud-vision/acceptance/vision/vision_test.rb
Labels: api: vision, cla: yes, testing

#2154 Storage Bucket lock
  google-cloud-storage/Rakefile
  google-cloud-storage/acceptance/storage/bucket_lock_retention_policy_test.rb
  google-cloud-storage/acceptance/storage/bucket_test.rb
  google-cloud-storage/acceptance/storage_helper.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/service.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/google/cloud/storage/bucket_lock_retention_policy_test.rb
  google-cloud-storage/test/google/cloud/storage/bucket_test.rb
  google-cloud-storage/test/google/cloud/storage/file_test.rb
  google-cloud-storage/test/google/cloud/storage/file_update_test.rb
  google-cloud-storage/test/google/cloud/storage/project_test.rb
  google-cloud-storage/test/helper.rb
Labels: api: storage, cla: yes
