Repository googleapis/google-cloud-ruby, pull requests merged in 2018-08, with the labels that each got.

#2218 Remove old badges
  README.md
Labels: cla: yes, type: cleanup

#2217 Fixed String#unpack1 for ruby 2.3 #2214
  google-cloud-bigtable/lib/google/cloud/bigtable/row.rb
Labels: cla: yes

#2220 run gapic gen for bigquery-data_transfer
  google-cloud-bigquery-data_transfer/README.md
  google-cloud-bigquery-data_transfer/Rakefile
  google-cloud-bigquery-data_transfer/google-cloud-bigquery-data_transfer.gemspec
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/credentials.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/datatransfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/empty.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/overview.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/datatransfer_pb.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/datatransfer_services_pb.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/transfer_pb.rb
  google-cloud-bigquery-data_transfer/synth.py
  google-cloud-bigquery-data_transfer/test/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client_test.rb
Labels: api: bigquery data transfer, cla: yes

#2226 add acceptance test to synth.py
  google-cloud-bigquery-data_transfer/acceptance/google/cloud/bigquery/data_transfer/v1/data_transfer_service_smoke_test.rb
  google-cloud-bigquery-data_transfer/synth.py
Labels: cla: yes

#2228 Include acceptance tests in video_intelligence synth
  google-cloud-video_intelligence/README.md
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/synth.py
Labels: cla: yes

#2227 Update synth script for speech
  google-cloud-speech/.rubocop.yml
  google-cloud-speech/.yardopts
  google-cloud-speech/README.md
  google-cloud-speech/google-cloud-speech.gemspec
  google-cloud-speech/lib/google/cloud/speech/v1.rb
  google-cloud-speech/lib/google/cloud/speech/v1/credentials.rb
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/credentials.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/overview.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client.rb
  google-cloud-speech/synth.py
  google-cloud-speech/test/google/cloud/speech/v1/speech_client_test.rb
  google-cloud-speech/test/google/cloud/speech/v1p1beta1/speech_client_test.rb
Labels: cla: yes

#2229 Add synth script for redis
  google-cloud-redis/README.md
  google-cloud-redis/google-cloud-redis.gemspec
  google-cloud-redis/lib/google/cloud/redis.rb
  google-cloud-redis/lib/google/cloud/redis/credentials.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/credentials.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/overview.rb
  google-cloud-redis/synth.py
  google-cloud-redis/test/google/cloud/redis/v1beta1/cloud_redis_client_test.rb
Labels: cla: yes

#2236 Tasks synth: Fix api enable link in the readme, temporarily disable gemspec merge
  google-cloud-tasks/README.md
  google-cloud-tasks/synth.py
Labels: cla: yes

#2239 Fixes for existing synth scripts
  google-cloud-redis/synth.py
  google-cloud-speech/synth.py
  google-cloud-tasks/synth.py
  google-cloud-trace/lib/google/cloud/trace/v1/doc/overview.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/overview.rb
  google-cloud-trace/synth.py
  google-cloud-video_intelligence/synth.py
Labels: cla: yes

#2225 Update synth script for text_to_speech
  google-cloud-text_to_speech/README.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/credentials.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client.rb
  google-cloud-text_to_speech/synth.py
Labels: cla: yes

#2242 Fix Trace documentation template value
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/devtools/cloudtrace/v1/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
Labels: api: trace, cla: yes, type: docs

#2240 Create synth script for datastore
  google-cloud-datastore/lib/google/cloud/datastore/credentials.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/credentials.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/datastore.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/entity.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/query.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/protobuf/wrappers.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/overview.rb
  google-cloud-datastore/lib/google/datastore/v1/datastore_services_pb.rb
  google-cloud-datastore/synth.py
Labels: cla: yes

#2237 Create synth script for pubsub
  google-cloud-pubsub/google-cloud-pubsub.gemspec
  google-cloud-pubsub/lib/google/cloud/pubsub/credentials.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/credentials.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/iam/v1/policy.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/duration.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/empty.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/field_mask.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/timestamp.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/overview.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client_config.json
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_services_pb.rb
  google-cloud-pubsub/synth.py
Labels: cla: yes

#2243 Fix some more links in documentation and simplify synth scripts a bit
  google-cloud-os_login/lib/google/cloud/os_login.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/overview.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/overview.rb
  google-cloud-os_login/synth.py
  google-cloud-redis/lib/google/cloud/redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/overview.rb
  google-cloud-redis/synth.py
  google-cloud-speech/lib/google/cloud/speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/overview.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/overview.rb
  google-cloud-speech/synth.py
  google-cloud-tasks/lib/google/cloud/tasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/overview.rb
  google-cloud-tasks/synth.py
  google-cloud-text_to_speech/synth.py
  google-cloud-trace/synth.py
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/overview.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/overview.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/overview.rb
  google-cloud-video_intelligence/synth.py
Labels: cla: yes

#2244 Update synth script for kms and regenerate
  google-cloud-kms/README.md
  google-cloud-kms/lib/google/cloud/kms.rb
  google-cloud-kms/lib/google/cloud/kms/v1.rb
  google-cloud-kms/lib/google/cloud/kms/v1/credentials.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/overview.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/synth.py
Labels: cla: yes

#2246 Update synth script for dlp and regenerate
  google-cloud-dlp/README.md
  google-cloud-dlp/lib/google/cloud/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/credentials.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/overview.rb
  google-cloud-dlp/synth.py
Labels: cla: yes

#2245 Create synth script for error reporting and regenerate
  google-cloud-error_reporting/lib/google/cloud/error_reporting/credentials.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/credentials.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_group_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_stats_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/report_errors_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/protobuf/duration.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/overview.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_group_service_services_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_stats_service_services_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/report_errors_service_services_pb.rb
  google-cloud-error_reporting/synth.py
Labels: cla: yes

#2248 Create synth script for dialogflow and regen gapic
  google-cloud-dialogflow/README.md
  google-cloud-dialogflow/google-cloud-dialogflow.gemspec
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/credentials.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/longrunning/operations.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/empty.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/overview.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client.rb
  google-cloud-dialogflow/synth.py
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/agents_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/contexts_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/entity_types_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/intents_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/session_entity_types_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/sessions_client_test.rb
Labels: cla: yes

#2249 Create synth script for language and regen gapic
  google-cloud-language/README.md
  google-cloud-language/acceptance/google/cloud/language/v1/language_service_smoke_test.rb
  google-cloud-language/google-cloud-language.gemspec
  google-cloud-language/lib/google/cloud/language.rb
  google-cloud-language/lib/google/cloud/language/credentials.rb
  google-cloud-language/lib/google/cloud/language/v1.rb
  google-cloud-language/lib/google/cloud/language/v1/credentials.rb
  google-cloud-language/lib/google/cloud/language/v1/doc/overview.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1beta2.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/credentials.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/doc/google/cloud/language/v1beta2/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/doc/overview.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_services_pb.rb
  google-cloud-language/synth.py
  google-cloud-language/test/google/cloud/language/v1/language_service_client_test.rb
  google-cloud-language/test/google/cloud/language/v1beta2/language_service_client_test.rb
Labels: cla: yes

#2247 Add YARD HTML Documentation
  Rakefile
  rakelib/yard_builder.rb
Labels: cla: yes, type: docs

#2255 Fix synth script and rakefile for language acceptance tests
  google-cloud-language/Rakefile
  google-cloud-language/synth.py
Labels: cla: yes

#2241 [Bigtable] Get table admin api changes
  google-cloud-bigtable/acceptance/bigtable/table/read_rows_test.rb
  google-cloud-bigtable/acceptance/bigtable/table_test.rb
  google-cloud-bigtable/acceptance/bigtable_helper.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_range.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_range.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/rows_reader.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/sample_row_key.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/value_range.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance/table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/row_reader/read_rows_state_machine_acceptance_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/row_reader_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/check_and_mutate_row_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/exists_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/mutate_row_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/mutate_rows_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/read_modify_write_row_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/read_rows_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/sample_row_keys_test.rb
Labels: api: bigtable, cla: yes

#2258 Bigtable Quickstart examples
  google-cloud-bigtable/.rubocop.yml
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/samples/Gemfile
  google-cloud-bigtable/samples/README.md
  google-cloud-bigtable/samples/instances.rb
  google-cloud-bigtable/samples/quickstart.rb
  google-cloud-bigtable/samples/tableadmin.rb
Labels: cla: yes

#2250 Create synth script for spanner and regen gapic
  google-cloud-spanner/lib/google/cloud/spanner/credentials.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/credentials.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/empty.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/mutation.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/type.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/overview.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/synth.py
Labels: cla: yes

#2252 Create synth script for debugger and regen gapic
  google-cloud-debugger/lib/google/cloud/debugger/credentials.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/credentials.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/controller.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/data.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/source/v1/source_context.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/protobuf/empty.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/protobuf/timestamp.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/overview.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/controller_services_pb.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/debugger_services_pb.rb
  google-cloud-debugger/synth.py
  google-cloud-debugger/test/google/cloud/debugger/v2/controller2_client_test.rb
  google-cloud-debugger/test/google/cloud/debugger/v2/debugger2_client_test.rb
Labels: cla: yes

#2253 Create synth script for dataproc and regen gapic
  google-cloud-dataproc/.rubocop.yml
  google-cloud-dataproc/README.md
  google-cloud-dataproc/Rakefile
  google-cloud-dataproc/acceptance/google/cloud/dataproc/v1/cluster_controller_smoke_test.rb
  google-cloud-dataproc/google-cloud-dataproc.gemspec
  google-cloud-dataproc/lib/google/cloud/dataproc.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/credentials.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/longrunning/operations.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/any.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/duration.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/empty.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/field_mask.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/timestamp.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/rpc/status.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/overview.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client.rb
  google-cloud-dataproc/synth.py
  google-cloud-dataproc/test/google/cloud/dataproc/v1/cluster_controller_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1/job_controller_client_test.rb
Labels: cla: yes

#2261 Fix intermittent debugger backoff test failures
  google-cloud-debugger/test/google/cloud/debugger/backoff_test.rb
Labels: cla: yes

#2263 Update synth script for vision and regen gapic
  google-cloud-vision/lib/google/cloud/vision/v1.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/overview.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb
  google-cloud-vision/synth.py
  google-cloud-vision/test/google/cloud/vision/v1/image_annotator_client_test.rb
Labels: cla: yes

#2262 Update synth script for bigquery-datatransfer and regen gapic
  google-cloud-bigquery-data_transfer/README.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/overview.rb
  google-cloud-bigquery-data_transfer/synth.py
Labels: cla: yes

#2251 Create synth script for firestore and regen gapic
  google-cloud-firestore/lib/google/cloud/firestore/credentials.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/credentials.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/common.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/document.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/any.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/empty.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/wrappers.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/rpc/status.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/overview.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/firestore_services_pb.rb
  google-cloud-firestore/synth.py
  google-cloud-firestore/test/google/cloud/firestore/v1beta1/firestore_client_test.rb
Labels: cla: yes

#2264 update auth urls
  google-cloud-core/lib/google/cloud/credentials.rb
  google-cloud-core/test/google/cloud/credentials_test.rb
Labels: cla: yes

#2268 Create monitoring synth script and regenerate gapic
  google-cloud-monitoring/.rubocop.yml
  google-cloud-monitoring/README.md
  google-cloud-monitoring/Rakefile
  google-cloud-monitoring/google-cloud-monitoring.gemspec
  google-cloud-monitoring/lib/google/cloud/monitoring.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/credentials.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/credentials.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/monitored_resource.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/group_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/any.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/empty.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/struct.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/rpc/status.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/overview.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client.rb
  google-cloud-monitoring/lib/google/monitoring/v3/alert_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/dropped_labels_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/group_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/span_context_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_service_services_pb.rb
  google-cloud-monitoring/synth.py
  google-cloud-monitoring/test/google/cloud/monitoring/v3/alert_policy_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/group_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/metric_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/notification_channel_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/uptime_check_service_client_test.rb
Labels: cla: yes

#2267 Create logging synth script and regenerate gapic
  google-cloud-logging/google-cloud-logging.gemspec
  google-cloud-logging/lib/google/cloud/logging/credentials.rb
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/credentials.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/distribution.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/label.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/metric.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/type/http_request.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/log_entry.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_metrics.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/any.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/duration.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/empty.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/field_mask.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/struct.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/overview.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client_config.json
  google-cloud-logging/lib/google/logging/v2/log_entry_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_config_services_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_metrics_services_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_services_pb.rb
  google-cloud-logging/synth.py
Labels: cla: yes

#2269 Use CircleCI 2.0 for post-build
  .circleci/config.yml
  Rakefile
Labels: cla: yes, type: cleanup

#2270 Attempt to deflake coverage for debugger by increasing the evaluation timeout
  google-cloud-debugger/test/helper.rb
Labels: cla: yes

#2274 Fix Firestore Watch Stream Issue
  google-cloud-firestore/lib/google/cloud/firestore/watch/listener.rb
Labels: api: firestore, cla: yes

#2286 Update CSV mime type
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_load_job_local_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_load_local_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_load_job_local_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_load_local_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_reference_test.rb
Labels: api: bigquery, cla: yes, type: cleanup

#2276 Kokoro migration
  .kokoro/build.sh
  .kokoro/common.cfg
  .kokoro/docker/ruby-2.3/Dockerfile
  .kokoro/docker/ruby-2.4/Dockerfile
  .kokoro/docker/ruby-2.5/Dockerfile
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/ruby-2.3.cfg
  .kokoro/presubmit/ruby-2.4.cfg
  .kokoro/presubmit/ruby-2.5.cfg
  .kokoro/trampoline.sh
Labels: cla: yes

#2284 Fixes for release documentation
  Rakefile
  rakelib/yard_builder.rb
Labels: cla: yes, type: cleanup, type: docs

#2277 Use Pub/Sub Subscriber Error Handler
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/async_unary_pusher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
Labels: api: pubsub, cla: yes

#2273 Pub/Sub Subscriber Stream Threading
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/async_stream_pusher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/async_unary_pusher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/inventory.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
Labels: api: pubsub, cla: yes

#2279 Fix bug in AsyncUnaryPusher
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/async_unary_pusher.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/acknowledge_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/delay_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/error_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/nack_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/restart_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: api: pubsub, cla: yes, type: bug

#2288 Guard on running ThreadPool
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/async_unary_pusher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
Labels: api: pubsub, cla: yes

#2281 Fixed and updated acceptance test for read and mutations apis
  google-cloud-bigtable/acceptance/bigtable/column_family_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/check_and_mutate_row_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/mutate_rows_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/read_modify_write_row_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/read_rows_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/row_filter_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/sample_row_keys_test.rb
  google-cloud-bigtable/acceptance/bigtable/table_test.rb
  google-cloud-bigtable/acceptance/bigtable_helper.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_range.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_range.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/rows_reader.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/value_range.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/exists_test.rb
Labels: cla: yes

#2278 Refactor Subscriber Stream shutdown
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
Labels: api: pubsub, cla: yes

#2285 Add case insenitive file system check
  rakelib/yard_builder.rb
Labels: cla: yes, type: docs

#2289 Fix documentation for Vision::Project#async_batch_annotate_files
  google-cloud-vision/lib/google/cloud/vision/project.rb
Labels: api: vision, cla: yes, type: docs

#2290 Update Storage monkeypatch docs
  google-cloud-storage/lib/google/cloud/storage/service.rb
Labels: api: storage, cla: yes, type: docs

#2311 Mark OperationsClient classes private, and change synth scripts to reproduce
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/synth.py
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/synth.py
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/synth.py
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/synth.py
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/synth.py
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client.rb
  google-cloud-speech/synth.py
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/synth.py
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb
  google-cloud-vision/synth.py
Labels: cla: yes

#2317 Fix Spanner documentation links
  google-cloud-spanner/lib/google/cloud/spanner/batch_snapshot.rb
  google-cloud-spanner/lib/google/cloud/spanner/client.rb
  google-cloud-spanner/lib/google/cloud/spanner/instance.rb
  google-cloud-spanner/lib/google/cloud/spanner/project.rb
Labels: api: spanner, cla: yes, type: docs

#2330 Update YARD excludes of protobuf files
  google-cloud-datastore/.yardopts
  google-cloud-debugger/.yardopts
  google-cloud-error_reporting/.yardopts
  google-cloud-firestore/.yardopts
  google-cloud-logging/.yardopts
  google-cloud-pubsub/.yardopts
  google-cloud-spanner/.yardopts
  google-cloud-trace/.yardopts
  google-cloud-vision/.yardopts
Labels: cla: yes, type: docs

#2331 Fix Storage documentation warning
  google-cloud-storage/lib/google/cloud/storage/file.rb
Labels: api: storage, cla: yes, type: docs

#2333 Remove Container Credentials
  google-cloud-container/lib/google/cloud/container/credentials.rb
Labels: api:container, cla: yes

#2335 Updated ruby version warnings to reflect current supported versions
  google-cloud-core/lib/google/cloud.rb
Labels: cla: yes

#2345 Set Debugger evaluation_time_limit during coverage
  Rakefile
  google-cloud-debugger/test/helper.rb
Labels: api: debugger, cla: yes, testing, type: cleanup

#2348 Fix documentation build in release rake tasks
  Rakefile
Labels: cla: yes, type: cleanup, type: docs

#2341 Update partial download test
  google-cloud-storage/acceptance/storage/file_test.rb
Labels: api: storage, cla: yes, testing, type: cleanup

#2346 Set evaluation_time_limit in Evaluator tests
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator/class_c_methods_whitelist_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator/immutable_classes_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator/instance_c_methods_whitelist_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator_test.rb
Labels: api: debugger, cla: yes, testing, type: cleanup

#2351 Add array-contains operator
  google-cloud-firestore/acceptance/firestore/query_test.rb
  google-cloud-firestore/lib/google/cloud/firestore/query.rb
  google-cloud-firestore/test/google/cloud/firestore/query/where/array_contains_test.rb
  google-cloud-firestore/test/google/cloud/firestore/query/where/equal_test.rb
  google-cloud-firestore/test/google/cloud/firestore/query/where/greater_than_test.rb
  google-cloud-firestore/test/google/cloud/firestore/query/where/less_than_test.rb
Labels: api: firestore, cla: yes, type: feature request

#2349 Add Array FieldValue types
  google-cloud-firestore/acceptance/firestore/document_test.rb
  google-cloud-firestore/lib/google/cloud/firestore/client.rb
  google-cloud-firestore/lib/google/cloud/firestore/convert.rb
  google-cloud-firestore/lib/google/cloud/firestore/field_value.rb
  google-cloud-firestore/test/google/cloud/firestore/convert/is_field_value_nested_test.rb
  google-cloud-firestore/test/google/cloud/firestore/convert/remove_field_value_from_test.rb
  google-cloud-firestore/test/google/cloud/firestore/convert/writes_for_create_test.rb
  google-cloud-firestore/test/google/cloud/firestore/convert/writes_for_update_test.rb
  google-cloud-firestore/test/google/cloud/firestore/field_value_test.rb
Labels: api: firestore, cla: yes, type: feature request

#2372 Add ORC support to BigQuery
  acceptance/data/us-states.orc
  google-cloud-bigquery/acceptance/bigquery/dataset_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/convert.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/load_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_load_job_storage_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_load_storage_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/load_job_updater_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_load_job_storage_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_load_storage_test.rb
Labels: api: bigquery, cla: yes

#2373 Replace Angular site app with YARD
  _data/jsondoc_types.yaml
  index.html
  js/jsondoc-forwarder-init-0.1.0.js
  js/vendor/jsondoc-forwarder-0.1.0.js
  new.html
Labels: cla: yes, type: docs

#2300 Fix middleware documentation warning
  google-cloud-debugger/lib/google/cloud/debugger/middleware.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/middleware.rb
  google-cloud-logging/lib/google/cloud/logging/logger.rb
  google-cloud-logging/lib/google/cloud/logging/middleware.rb
  google-cloud-trace/lib/google/cloud/trace/middleware.rb
  stackdriver-core/lib/stackdriver/core/async_actor.rb
Labels: api: debugger, api: error reporting, api: logging, api: trace, cla: yes, stackdriver, type: cleanup, type: docs

#2374 Update synth scripts to remove jsondoc from rakefiles
  google-cloud-asset/synth.py
  google-cloud-bigquery-data_transfer/synth.py
  google-cloud-container/synth.py
  google-cloud-dataproc/synth.py
  google-cloud-dialogflow/synth.py
  google-cloud-kms/synth.py
  google-cloud-language/synth.py
  google-cloud-redis/synth.py
  google-cloud-tasks/synth.py
Labels: cla: yes

#2375 Remove synth references to overview.rb file that is no longer generated
  google-cloud-bigquery-data_transfer/synth.py
  google-cloud-bigtable/synth.py
  google-cloud-container/synth.py
  google-cloud-datastore/synth.py
  google-cloud-debugger/synth.py
  google-cloud-error_reporting/synth.py
  google-cloud-firestore/synth.py
  google-cloud-kms/synth.py
  google-cloud-language/synth.py
  google-cloud-logging/synth.py
  google-cloud-os_login/synth.py
  google-cloud-pubsub/synth.py
  google-cloud-redis/synth.py
  google-cloud-spanner/synth.py
  google-cloud-trace/synth.py
  google-cloud-video_intelligence/synth.py
  google-cloud-vision/synth.py
Labels: cla: yes

#2387 set acceptance tests to only run on gem change
  .kokoro/build.sh
Labels: cla: yes

#2388 configure kokoro to log inclusion of acceptance tests
  .kokoro/build.sh
  .kokoro/docker/ruby-2.3/Dockerfile
  .kokoro/docker/ruby-2.4/Dockerfile
  .kokoro/docker/ruby-2.5/Dockerfile
Labels: cla: yes

#2385 Refactor Evaluator tests into test class
  Rakefile
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator/class_c_methods_whitelist_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator/expression_test_helper.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator/immutable_classes_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator/instance_c_methods_whitelist_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator_test.rb
  google-cloud-debugger/test/helper.rb
Labels: api: debugger, cla: yes, testing

#2391 Update Storage notification tests and examples to use Project#service_account_email
  google-cloud-storage/acceptance/storage/bucket_notification_test.rb
  google-cloud-storage/acceptance/storage/bucket_requester_pays_test.rb
  google-cloud-storage/lib/google/cloud/storage.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/notification.rb
  google-cloud-storage/support/doctest_helper.rb
Labels: api: storage, cla: yes

#2389 Fix and rerun gapic generation for assets and tasks
  google-cloud-asset/README.md
  google-cloud-asset/lib/google/cloud/asset.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_services_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/assets_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/credentials.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/asset_service.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/assets.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/any.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/struct.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/rpc/status.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/overview.rb
  google-cloud-asset/synth.py
  google-cloud-asset/test/google/cloud/asset/v1beta1/asset_service_client_test.rb
  google-cloud-tasks/lib/google/cloud/tasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloudtasks_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/credentials.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/duration.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/empty.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/rpc/status.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/overview.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/queue_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/target_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/task_pb.rb
  google-cloud-tasks/synth.py
Labels: cla: yes

#2395 Don't auto-update rubocop configs from gapic
  google-cloud-asset/synth.py
  google-cloud-bigquery-data_transfer/synth.py
  google-cloud-container/synth.py
  google-cloud-dataproc/synth.py
  google-cloud-dialogflow/synth.py
  google-cloud-dlp/synth.py
  google-cloud-kms/synth.py
  google-cloud-language/synth.py
  google-cloud-monitoring/synth.py
  google-cloud-os_login/synth.py
  google-cloud-redis/synth.py
  google-cloud-speech/synth.py
  google-cloud-tasks/synth.py
  google-cloud-text_to_speech/synth.py
  google-cloud-video_intelligence/synth.py
Labels: cla: yes
