Repository googleapis/google-cloud-ruby, pull requests merged in 2019-12, with the labels that each got.

#4438 docs(stackdriver): update use_logging description
  stackdriver/INSTRUMENTATION_CONFIGURATION.md
Labels: api: logging, cla: yes, stackdriver, type: docs

#4423 fix(spanner) : add service address and port for operation client
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/synth.py
Labels: cla: yes

#4472 docs(bigtable): Update release level to GA
  README.md
  google-cloud-bigtable/README.md
  google-cloud-bigtable/lib/google/cloud/bigtable/admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2.rb
Labels: api: bigtable, cla: yes

#4473 Release google-cloud-bigtable 1.0.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
  google-cloud/google-cloud.gemspec
Labels: api: bigtable, autorelease: pending, cla: yes

#4476 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_pb.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4475 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/firestore/v1/firestore_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/query_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#4471 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/protobuf/empty.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/helpers.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client_config.json
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise_pb.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise_services_pb.rb
  google-cloud-recaptcha_enterprise/synth.metadata
  google-cloud-recaptcha_enterprise/test/google/cloud/recaptcha_enterprise/v1beta1/helpers_test.rb
  google-cloud-recaptcha_enterprise/test/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client_test.rb
Labels: cla: yes

#4470 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client_config.json
  google-cloud-container/lib/google/cloud/container/v1beta1/doc/google/container/v1beta1/cluster_service.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-container/lib/google/container/v1beta1/cluster_service_pb.rb
  google-cloud-container/lib/google/container/v1beta1/cluster_service_services_pb.rb
  google-cloud-container/synth.metadata
  google-cloud-container/test/google/cloud/container/v1beta1/cluster_manager_client_test.rb
Labels: cla: yes

#4464 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/metric.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#4462 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#4205 introduce enable_cross_project_tracing option to the faraday middleware
  google-cloud-trace/lib/google/cloud/trace/faraday_middleware.rb
  google-cloud-trace/test/google/cloud/trace/faraday_middleware_test.rb
Labels: cla: yes

#4461 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client_config.json
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/datastore.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/entity.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/query.rb
  google-cloud-datastore/lib/google/datastore/v1/datastore_pb.rb
  google-cloud-datastore/lib/google/datastore/v1/datastore_services_pb.rb
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#4482 fix(datastore): Update Service calls to run_query and commit
  google-cloud-datastore/lib/google/cloud/datastore/service.rb
  google-cloud-datastore/support/doctest_helper.rb
  google-cloud-datastore/test/google/cloud/datastore/dataset_test.rb
  google-cloud-datastore/test/google/cloud/datastore/lookup_results/find_all_test.rb
  google-cloud-datastore/test/google/cloud/datastore/query_results/all_test.rb
  google-cloud-datastore/test/google/cloud/datastore/query_results/all_with_more_test.rb
  google-cloud-datastore/test/google/cloud/datastore/query_results/all_with_offset_test.rb
  google-cloud-datastore/test/google/cloud/datastore/query_results_test.rb
  google-cloud-datastore/test/google/cloud/datastore/read_only_transaction_test.rb
  google-cloud-datastore/test/google/cloud/datastore/transaction_test.rb
Labels: api: datastore, cla: yes

#4466 feat(storage): add IAM Conditions support
  google-cloud-storage/.rubocop.yml
  google-cloud-storage/acceptance/storage/bucket_policy_test.rb
  google-cloud-storage/acceptance/storage/bucket_requester_pays_test.rb
  google-cloud-storage/acceptance/storage/bucket_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/policy.rb
  google-cloud-storage/lib/google/cloud/storage/policy/binding.rb
  google-cloud-storage/lib/google/cloud/storage/policy/bindings.rb
  google-cloud-storage/lib/google/cloud/storage/policy/condition.rb
  google-cloud-storage/lib/google/cloud/storage/service.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/google/cloud/storage/bucket_iam_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_iam_test.rb
  google-cloud-storage/test/google/cloud/storage/policy_binding_test.rb
  google-cloud-storage/test/google/cloud/storage/policy_test.rb
  google-cloud-storage/test/google/cloud/storage/policy_v1_test.rb
  google-cloud-storage/test/google/cloud/storage/policy_v3_bindings_test.rb
  google-cloud-storage/test/google/cloud/storage/policy_v3_test.rb
  google-cloud-storage/test/helper.rb
Labels: api: storage, cla: yes

#4505 Release google-cloud-storage 1.25.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4502 Release google-cloud-datastore 1.7.2
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: api: datastore, autorelease: pending, cla: yes, type: process

#4495 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client_config.json
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_services_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1/assets_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/cloud/asset/v1/asset_service.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/cloud/asset/v1/assets.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/protobuf/empty.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/protobuf/field_mask.rb
  google-cloud-asset/lib/google/cloud/asset/v1/helpers.rb
  google-cloud-asset/synth.metadata
  google-cloud-asset/test/google/cloud/asset/v1/asset_service_client_test.rb
  google-cloud-asset/test/google/cloud/asset/v1/helpers_test.rb
Labels: cla: yes

#4514 Release google-cloud-asset 0.6.0
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4512 feat(monitoring): Add support for monitoring dashboards API
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/credentials.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/dashboards_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/dashboards_service_client_config.json
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/common.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/dashboard.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/dashboards_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/layouts.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/metrics.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/scorecard.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/text.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/widget.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/xychart.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/protobuf/duration.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/protobuf/empty.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/common_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/dashboard_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/dashboards_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/dashboards_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/drilldowns_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/layouts_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/metrics_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/scorecard_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/text_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/widget_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/xychart_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_pb.rb
  google-cloud-monitoring/synth.metadata
  google-cloud-monitoring/synth.py
  google-cloud-monitoring/test/google/cloud/monitoring/dashboard/v1/dashboards_service_client_test.rb
Labels: cla: yes

#4504 Fix MonitorMixin usage on Ruby 2.7
  google-cloud-bigquery/lib/google/cloud/bigquery/table/async_inserter.rb
  google-cloud-firestore/lib/google/cloud/firestore/watch/listener.rb
  google-cloud-logging/lib/google/cloud/logging/async_writer.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher/batch.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/inventory.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/sequencer.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-speech/lib/google/cloud/speech/v1/stream.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/stream.rb
  google-cloud-trace/lib/google/cloud/trace/async_reporter.rb
Labels: cla: yes

#4489 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/firestore/admin/v1/firestore_admin.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/firestore_admin_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/field_pb.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/firestore_admin_pb.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/index_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/firestore_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/query_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#4491 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client_config.json
  google-cloud-speech/synth.metadata
Labels: cla: yes

#4516 Release google-cloud-monitoring 0.34.0
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4493 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client_config.json
  google-cloud-trace/synth.metadata
Labels: cla: yes

#4496 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/datatransfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/datatransfer_pb.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/transfer_pb.rb
  google-cloud-bigquery-data_transfer/synth.metadata
  google-cloud-bigquery-data_transfer/test/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client_test.rb
Labels: cla: yes

#4497 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4499 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_services_pb.rb
  google-cloud-language/synth.metadata
Labels: cla: yes

#4500 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/asset_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/asset.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/finding.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/organization_settings.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/security_marks.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/securitycenter_service.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/source.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/finding_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/organization_settings_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/run_asset_discovery_response_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_marks_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/securitycenter_service_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/securitycenter_service_services_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/source_pb.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#4520 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client_config.json
  google-cloud-speech/synth.metadata
Labels: cla: yes

#4492 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client_config.json
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/helpers.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client_config.json
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/helpers.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client_config.json
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/helpers.rb
  google-cloud-tasks/synth.metadata
  google-cloud-tasks/test/google/cloud/tasks/v2/cloud_tasks_client_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2/helpers_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2beta2/cloud_tasks_client_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2beta2/helpers_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2beta3/cloud_tasks_client_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2beta3/helpers_test.rb
Labels: cla: yes

#4506 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/autoscaling_policies_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/jobs_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_templates_services_pb.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4459 Release google-cloud-automl 0.5.0
  google-cloud-automl/CHANGELOG.md
  google-cloud-automl/lib/google/cloud/automl/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4469 Release stackdriver 0.16.1
  stackdriver/CHANGELOG.md
  stackdriver/lib/stackdriver/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4453 Release google-cloud-talent 0.8.2
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4484 Release google-cloud-recaptcha_enterprise 0.4.0
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4479 Release google-cloud-container 0.8.0
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4487 Release google-cloud-firestore 1.2.2
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4485 Release google-cloud-dlp 0.13.0
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4503 Release google-cloud-logging 1.9.2
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4494 Release google-cloud-speech 0.40.1
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4509 Release google-cloud-spanner 1.12.2
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4518 Release google-cloud-pubsub 1.1.3
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4519 Release google-cloud-bigquery 1.18.1
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4517 Release google-cloud-trace 0.37.0
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4521 Release google-cloud-dataproc 0.7.2
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4522 Release google-cloud 0.64.0
  google-cloud/CHANGELOG.md
  google-cloud/lib/google/cloud/version.rb
Labels: autorelease: pending, cla: yes

#4523 Release google-cloud-bigquery-data_transfer 0.5.0
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes

#4524 Release google-cloud-language 0.35.2
  google-cloud-language/CHANGELOG.md
  google-cloud-language/lib/google/cloud/language/version.rb
Labels: autorelease: pending, cla: yes

#4525 Release google-cloud-security_center 0.4.3
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes

#4526 Release google-cloud-tasks 1.3.2
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes

#4527 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/audio_config_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/context.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/duration.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4528 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/metric.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#4529 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4530 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/asset_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/asset.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/securitycenter_service.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/finding_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/organization_settings_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/run_asset_discovery_response_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client_config.json
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_marks_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/securitycenter_service_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/source_pb.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#4488 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/acceptance/error_reporting/error_reporting_test.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_group_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_stats_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/report_errors_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client_config.json
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client_config.json
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/common_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_group_service_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_group_service_services_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_stats_service_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_stats_service_services_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/report_errors_service_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/report_errors_service_services_pb.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#4531 Release google-cloud-dialogflow 0.12.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4532 Release google-cloud-security_center 0.5.0
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4533 Release google-cloud-error_reporting 0.34.1
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4534 Release google-cloud-logging 1.9.3
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#4535 Release google-cloud-monitoring 0.34.1
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes

#4541 Fixes for Core Config
  google-cloud-core/lib/google/cloud/config.rb
  google-cloud-core/test/google/cloud/config_test.rb
Labels: cla: yes

#4545 Remove AUTHENTICATION.md from google-cloud-errors gemspec
  google-cloud-errors/google-cloud-errors.gemspec
Labels: cla: yes

#4549 fix(spanner) - Fix a typo in README.md.
  README.md
Labels: cla: yes, type: docs

#4544 Add Secret Manager V1beta1 and Veneer gems
  Gemfile
  google-cloud-secret_manager-v1beta1/.gitignore
  google-cloud-secret_manager-v1beta1/.repo-metadata.json
  google-cloud-secret_manager-v1beta1/.rubocop.yml
  google-cloud-secret_manager-v1beta1/.yardopts
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/Gemfile
  google-cloud-secret_manager-v1beta1/LICENSE.md
  google-cloud-secret_manager-v1beta1/README.md
  google-cloud-secret_manager-v1beta1/Rakefile
  google-cloud-secret_manager-v1beta1/google-cloud-secret_manager-v1beta1.gemspec
  google-cloud-secret_manager-v1beta1/lib/google-cloud-secret_manager-v1beta1.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/credentials.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secrets/v1beta1/resources_pb.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secrets/v1beta1/service_pb.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secrets/v1beta1/service_services_pb.rb
  google-cloud-secret_manager-v1beta1/proto_docs/README.md
  google-cloud-secret_manager-v1beta1/proto_docs/google/api/field_behavior.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/resources.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/service.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/iam/v1/policy.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/empty.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-secret_manager-v1beta1/test/google/cloud/secret_manager/v1beta1/secret_manager_service_test.rb
  google-cloud-secret_manager/.gitignore
  google-cloud-secret_manager/.repo-metadata.json
  google-cloud-secret_manager/.rubocop.yml
  google-cloud-secret_manager/.yardopts
  google-cloud-secret_manager/AUTHENTICATION.md
  google-cloud-secret_manager/CHANGELOG.md
  google-cloud-secret_manager/Gemfile
  google-cloud-secret_manager/LICENSE
  google-cloud-secret_manager/README.md
  google-cloud-secret_manager/Rakefile
  google-cloud-secret_manager/google-cloud-secret_manager.gemspec
  google-cloud-secret_manager/lib/google-cloud-secret_manager.rb
  google-cloud-secret_manager/lib/google/cloud/secret_manager.rb
  google-cloud-secret_manager/lib/google/cloud/secret_manager/version.rb
  google-cloud-secret_manager/test/google/cloud/language/version_test.rb
  google-cloud-secret_manager/test/helper.rb
Labels: cla: yes
