Repository googleapis/google-cloud-ruby, pull requests merged in 2019-01, with the labels that each got.

#2745 Update dataproc synth script to rename WorkflowTemplate factory
  google-cloud-dataproc/synth.py
Labels: cla: yes

#2598 fix windows tests
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_insert_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_insert_test.rb
  google-cloud-core/lib/google/cloud.rb
  google-cloud-core/test/google/cloud/loaded_files_test.rb
Labels: cla: yes

#2744 Firestore Emulator Support
  google-cloud-firestore/.yardopts
  google-cloud-firestore/EMULATOR.md
  google-cloud-firestore/google-cloud-firestore.gemspec
  google-cloud-firestore/lib/google-cloud-firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/service.rb
  google-cloud-firestore/test/google/cloud/firestore_test.rb
Labels: api: firestore, cla: yes

#2750 Fix rubocop warning in firestore
  google-cloud-firestore/lib/google/cloud/firestore.rb
Labels: cla: yes

#2736 AsyncReporter buffer traces and make batch API calls
  google-cloud-trace/.rubocop.yml
  google-cloud-trace/google-cloud-trace.gemspec
  google-cloud-trace/lib/google/cloud/trace/async_reporter.rb
  google-cloud-trace/lib/google/cloud/trace/errors.rb
  google-cloud-trace/test/google/cloud/trace/async_reporter_test.rb
Labels: api: cloudtrace, cla: yes

#2738 Move ErrorReporting to use concurrent-ruby
  google-cloud-error_reporting/acceptance/error_reporting_helper.rb
  google-cloud-error_reporting/google-cloud-error_reporting.gemspec
  google-cloud-error_reporting/lib/google-cloud-error_reporting.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/async_error_reporter.rb
  google-cloud-error_reporting/test/google/cloud/error_reporting/async_error_reporter_test.rb
Labels: api: clouderrorreporting, cla: yes

#2772 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/acceptance/google/cloud/vision/v1/helpers_smoke_test.rb
  google-cloud-vision/acceptance/google/cloud/vision/v1p3beta1/helpers_smoke_test.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/longrunning/operations.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/wrappers.rb
  google-cloud-vision/lib/google/cloud/vision/v1/helpers.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/longrunning/operations.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/wrappers.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/helpers.rb
  google-cloud-vision/synth.metadata
  google-cloud-vision/test/google/cloud/vision/v1/helpers_test.rb
  google-cloud-vision/test/google/cloud/vision/v1p3beta1/helpers_test.rb
Labels: cla: yes

#2771 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/cloud/videointelligence/v1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#2770 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/wrappers.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#2769 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/doc/google/cloud/texttospeech/v1/cloud_tts.rb
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#2768 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/policy.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#2767 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/longrunning/operations.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/longrunning/operations.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#2766 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/longrunning/operations.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/longrunning/operations.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#2765 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/longrunning/operations.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-redis/synth.metadata
Labels: cla: yes

#2763 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/wrappers.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#2762 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/distribution.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/metric.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#2761 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/lib/google/cloud/language/v1/doc/google/cloud/language/v1/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/doc/google/cloud/language/v1beta2/language_service.rb
  google-cloud-language/synth.metadata
Labels: cla: yes

#2760 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/iam/v1/policy.rb
  google-cloud-kms/lib/google/cloud/kms/v1/helpers.rb
  google-cloud-kms/synth.metadata
  google-cloud-kms/test/google/cloud/kms/v1/helpers_test.rb
Labels: cla: yes

#2759 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/wrappers.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#2758 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_stats_service.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#2757 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#2756 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/longrunning/operations.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#2755 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/protobuf/wrappers.rb
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#2752 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/transfer.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#2751 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#2773 Fix test coverage task
  Gemfile
  gcloud/Gemfile
Labels: cla: yes, testing

#2764 Re-generated google-cloud-pubsub files
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/iam/v1/policy.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client_config.json
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_services_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#2737 Update googleauth to 0.7.1
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-dns/google-cloud-dns.gemspec
  google-cloud-resource_manager/google-cloud-resource_manager.gemspec
  google-cloud-storage/google-cloud-storage.gemspec
  google-cloud-translate/google-cloud-translate.gemspec
Labels: auth, cla: yes

#2776 sort methods prior to generating helper methods
  google-cloud-kms/Rakefile
  google-cloud-kms/lib/google/cloud/kms/v1/helpers.rb
  google-cloud-kms/synth/helpers_test.rb.erb
  google-cloud-kms/test/google/cloud/kms/v1/helpers_test.rb
  google-cloud-scheduler/.gitignore
  google-cloud-scheduler/Rakefile
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/helpers.rb
  google-cloud-scheduler/synth/helpers_test.rb.erb
  google-cloud-scheduler/test/google/cloud/scheduler/v1beta1/helpers_test.rb
  google-cloud-vision/Rakefile
  google-cloud-vision/acceptance/google/cloud/vision/v1/helpers_smoke_test.rb
  google-cloud-vision/acceptance/google/cloud/vision/v1p3beta1/helpers_smoke_test.rb
  google-cloud-vision/lib/google/cloud/vision/v1/helpers.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/helpers.rb
  google-cloud-vision/synth/helpers.rb.erb
  google-cloud-vision/synth/helpers_smoke_test.rb.erb
  google-cloud-vision/synth/helpers_test.rb.erb
  google-cloud-vision/test/google/cloud/vision/v1/helpers_test.rb
  google-cloud-vision/test/google/cloud/vision/v1p3beta1/helpers_test.rb
Labels: cla: yes

#2777 update error message expected in tests
  google-cloud-bigquery/acceptance/bigquery/dataset_test.rb
  google-cloud-bigquery/acceptance/bigquery/table_test.rb
  google-cloud-bigquery/acceptance/bigquery/view_test.rb
Labels: cla: yes

#2753 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/longrunning/operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/protobuf/wrappers.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#2780 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/clusters_pb.rb
  google-cloud-dataproc/synth.metadata
Labels: api: dataproc, cla: yes

#2779 Make use of Credentials#project_id
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-bigquery/lib/google/cloud/bigquery.rb
  google-cloud-bigquery/test/google/cloud/bigquery_test.rb
  google-cloud-bigtable/lib/google/cloud/bigtable.rb
  google-cloud-bigtable/test/google/cloud/bigtable_test.rb
  google-cloud-datastore/lib/google/cloud/datastore.rb
  google-cloud-datastore/test/google/cloud/datastore_test.rb
  google-cloud-debugger/lib/google/cloud/debugger.rb
  google-cloud-debugger/test/google/cloud/debugger_test.rb
  google-cloud-dns/google-cloud-dns.gemspec
  google-cloud-dns/lib/google/cloud/dns.rb
  google-cloud-dns/test/google/cloud/dns_test.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting.rb
  google-cloud-firestore/lib/google/cloud/firestore.rb
  google-cloud-firestore/test/google/cloud/firestore_test.rb
  google-cloud-logging/lib/google/cloud/logging.rb
  google-cloud-logging/test/google/cloud/logging_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub.rb
  google-cloud-pubsub/test/google/cloud/pubsub_test.rb
  google-cloud-resource_manager/google-cloud-resource_manager.gemspec
  google-cloud-spanner/lib/google/cloud/spanner.rb
  google-cloud-spanner/test/google/cloud/spanner_test.rb
  google-cloud-storage/google-cloud-storage.gemspec
  google-cloud-storage/lib/google/cloud/storage.rb
  google-cloud-storage/test/google/cloud/storage_test.rb
  google-cloud-trace/lib/google/cloud/trace.rb
  google-cloud-translate/google-cloud-translate.gemspec
  google-cloud-translate/lib/google/cloud/translate.rb
  google-cloud-translate/test/google/cloud/translate_test.rb
Labels: api: core, auth, cla: yes

#2786 Pub/Sub: Remove delay alias
  google-cloud-pubsub/lib/google/cloud/pubsub/received_message.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/received_message_test.rb
Labels: api: pubsub, cla: yes

#2787 Re-generated google-cloud-speech files
  google-cloud-speech/lib/google/cloud/speech/v1.rb
  google-cloud-speech/lib/google/cloud/speech/v1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#2784 Convert Debugger Transmitter to concurrent-ruby
  google-cloud-debugger/acceptance/debugger_helper.rb
  google-cloud-debugger/google-cloud-debugger.gemspec
  google-cloud-debugger/lib/google-cloud-debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger/breakpoint.rb
  google-cloud-debugger/lib/google/cloud/debugger/transmitter.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint_manager_test.rb
  google-cloud-debugger/test/google/cloud/debugger/transmitter_test.rb
Labels: api: clouddebugger, cla: yes

#2788 Re-generated google-cloud-text_to_speech files
  google-cloud-text_to_speech/README.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1.rb
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#2792 Re-generate google-cloud-firestore files
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/write.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/firestore_services_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/write_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#2798 Remove auto-load of minitest-reporters
  google-cloud-bigquery/Gemfile
  google-cloud-bigtable/Gemfile
  google-cloud-logging/Gemfile
  google-cloud-pubsub/Gemfile
  google-cloud-storage/Gemfile
Labels: cla: yes, type: cleanup

#2824 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/acceptance/google/cloud/vision/v1/image_annotator_smoke_test.rb
  google-cloud-vision/acceptance/google/cloud/vision/v1p3beta1/image_annotator_smoke_test.rb
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/lib/google/cloud/vision/v1.rb
  google-cloud-vision/lib/google/cloud/vision/v1/credentials.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/geometry.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/image_annotator.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/text_annotation.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/web_detection.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/longrunning/operations.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/any.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/empty.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/field_mask.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/timestamp.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/wrappers.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/rpc/status.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/type/color.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/type/latlng.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/credentials.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/geometry.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/image_annotator.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/text_annotation.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/web_detection.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/longrunning/operations.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/any.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/empty.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/field_mask.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/timestamp.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/wrappers.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/rpc/status.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/type/color.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/type/latlng.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client.rb
  google-cloud-vision/synth.metadata
  google-cloud-vision/test/google/cloud/vision/v1/image_annotator_client_test.rb
  google-cloud-vision/test/google/cloud/vision/v1/product_search_client_test.rb
  google-cloud-vision/test/google/cloud/vision/v1p3beta1/image_annotator_client_test.rb
  google-cloud-vision/test/google/cloud/vision/v1p3beta1/product_search_client_test.rb
Labels: cla: yes

#2823 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/protobuf/duration.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/cloud/videointelligence/v1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/cloud/videointelligence/v1beta2/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/protobuf/duration.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/cloud/videointelligence/v1p1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/protobuf/duration.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/cloud/videointelligence/v1p2beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/protobuf/duration.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/synth.metadata
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client_test.rb
Labels: cla: yes

#2822 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/credentials.rb
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/devtools/cloudtrace/v1/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/protobuf/empty.rb
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/protobuf/timestamp.rb
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v2/credentials.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/tracing.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/any.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/empty.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/timestamp.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/wrappers.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/rpc/status.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#2821 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/credentials.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/doc/google/cloud/texttospeech/v1/cloud_tts.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1/cloud_tts_pb.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1/cloud_tts_services_pb.rb
  google-cloud-text_to_speech/synth.metadata
  google-cloud-text_to_speech/test/google/cloud/text_to_speech/v1/text_to_speech_client_test.rb
Labels: cla: yes

#2820 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/credentials.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/duration.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/empty.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/rpc/status.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/credentials.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/duration.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/empty.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/rpc/status.rb
  google-cloud-tasks/synth.metadata
  google-cloud-tasks/test/google/cloud/tasks/v2beta2/cloud_tasks_client_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2beta3/cloud_tasks_client_test.rb
Labels: cla: yes

#2819 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/acceptance/google/cloud/speech/v1/speech_smoke_test.rb
  google-cloud-speech/acceptance/google/cloud/speech/v1p1beta1/speech_smoke_test.rb
  google-cloud-speech/lib/google/cloud/speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1.rb
  google-cloud-speech/lib/google/cloud/speech/v1/credentials.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/longrunning/operations.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/protobuf/any.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/protobuf/duration.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/rpc/status.rb
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/credentials.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/longrunning/operations.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/protobuf/any.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/protobuf/duration.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/rpc/status.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client.rb
  google-cloud-speech/synth.metadata
  google-cloud-speech/test/google/cloud/speech/v1/speech_client_test.rb
  google-cloud-speech/test/google/cloud/speech/v1p1beta1/speech_client_test.rb
Labels: cla: yes

#2818 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/credentials.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/longrunning/operations.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/protobuf/any.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/protobuf/empty.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/spanner/admin/database/v1/spanner_database_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/credentials.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/longrunning/operations.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/protobuf/any.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/protobuf/empty.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/protobuf/field_mask.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/spanner/admin/instance/v1/spanner_instance_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/credentials.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/duration.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/empty.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/struct.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/timestamp.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/keys.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/mutation.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/query_plan.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/result_set.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/transaction.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/type.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/admin/database/v1/database_admin_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/admin/instance/v1/instance_admin_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/v1/spanner_client_test.rb
Labels: cla: yes

#2817 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1/credentials.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/longrunning/operations.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/protobuf/any.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/protobuf/field_mask.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/protobuf/timestamp.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/rpc/status.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/credentials.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/cloud/redis/v1beta1/cloud_redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/protobuf/any.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/rpc/status.rb
  google-cloud-redis/synth.metadata
  google-cloud-redis/test/google/cloud/redis/v1/cloud_redis_client_test.rb
  google-cloud-redis/test/google/cloud/redis/v1beta1/cloud_redis_client_test.rb
Labels: cla: yes

#2816 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/credentials.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/cloud/oslogin/common/common.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/cloud/oslogin/v1/oslogin.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/protobuf/empty.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/protobuf/field_mask.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/credentials.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/cloud/oslogin/common/common.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/cloud/oslogin/v1beta/oslogin.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/protobuf/empty.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/protobuf/field_mask.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client.rb
  google-cloud-os_login/synth.metadata
  google-cloud-os_login/test/google/cloud/os_login/v1/os_login_service_client_test.rb
  google-cloud-os_login/test/google/cloud/os_login/v1beta/os_login_service_client_test.rb
Labels: cla: yes

#2815 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/acceptance/google/cloud/monitoring/v3/metric_service_smoke_test.rb
  google-cloud-monitoring/lib/google/cloud/monitoring.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/credentials.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/distribution.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/label.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/monitored_resource.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/common.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/group.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/group_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/mutation_record.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/any.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/duration.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/empty.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/field_mask.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/struct.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/timestamp.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/wrappers.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/rpc/status.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client.rb
  google-cloud-monitoring/synth.metadata
  google-cloud-monitoring/test/google/cloud/monitoring/v3/alert_policy_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/group_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/metric_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/notification_channel_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/uptime_check_service_client_test.rb
Labels: cla: yes

#2814 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/credentials.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/distribution.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/label.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/metric.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/type/http_request.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/log_entry.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_metrics.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/any.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/duration.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/empty.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/field_mask.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/struct.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#2813 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/acceptance/google/cloud/language/v1/language_service_smoke_test.rb
  google-cloud-language/lib/google/cloud/language.rb
  google-cloud-language/lib/google/cloud/language/v1.rb
  google-cloud-language/lib/google/cloud/language/v1/credentials.rb
  google-cloud-language/lib/google/cloud/language/v1/doc/google/cloud/language/v1/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1beta2.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/credentials.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/doc/google/cloud/language/v1beta2/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client.rb
  google-cloud-language/synth.metadata
  google-cloud-language/test/google/cloud/language/v1/language_service_client_test.rb
  google-cloud-language/test/google/cloud/language/v1beta2/language_service_client_test.rb
Labels: cla: yes

#2812 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms.rb
  google-cloud-kms/lib/google/cloud/kms/v1.rb
  google-cloud-kms/lib/google/cloud/kms/v1/credentials.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/resources.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/service.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/iam/v1/policy.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/protobuf/duration.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/protobuf/field_mask.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/protobuf/timestamp.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/synth.metadata
  google-cloud-kms/test/google/cloud/kms/v1/key_management_service_client_test.rb
Labels: cla: yes

#2811 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/credentials.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/common.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/document.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/any.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/empty.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/wrappers.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/rpc/status.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/synth.metadata
  google-cloud-firestore/test/google/cloud/firestore/v1beta1/firestore_client_test.rb
Labels: cla: yes

#2810 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/credentials.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_group_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_stats_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/report_errors_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/protobuf/duration.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#2809 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/credentials.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/any.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/duration.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/empty.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/field_mask.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/timestamp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/rpc/status.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/type/date.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/type/timeofday.rb
  google-cloud-dlp/synth.metadata
  google-cloud-dlp/test/google/cloud/dlp/v2/dlp_service_client_test.rb
Labels: cla: yes

#2808 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/credentials.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/context.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session_entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/longrunning/operations.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/any.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/empty.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/field_mask.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/struct.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/rpc/status.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/type/latlng.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client.rb
  google-cloud-dialogflow/synth.metadata
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/agents_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/contexts_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/entity_types_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/intents_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/session_entity_types_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/sessions_client_test.rb
Labels: cla: yes

#2807 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/credentials.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/controller.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/data.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/source/v1/source_context.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/protobuf/empty.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/protobuf/timestamp.rb
  google-cloud-debugger/synth.metadata
  google-cloud-debugger/test/google/cloud/debugger/v2/controller2_client_test.rb
  google-cloud-debugger/test/google/cloud/debugger/v2/debugger2_client_test.rb
Labels: cla: yes

#2806 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/credentials.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/datastore.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/entity.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/query.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/protobuf/wrappers.rb
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#2805 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/acceptance/google/cloud/dataproc/v1/cluster_controller_smoke_test.rb
  google-cloud-dataproc/acceptance/google/cloud/dataproc/v1beta2/cluster_controller_smoke_test.rb
  google-cloud-dataproc/lib/google/cloud/dataproc.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/credentials.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/longrunning/operations.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/any.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/duration.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/empty.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/field_mask.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/timestamp.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/rpc/status.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/credentials.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/longrunning/operations.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/any.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/duration.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/empty.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/field_mask.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/timestamp.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/rpc/status.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/synth.metadata
  google-cloud-dataproc/test/google/cloud/dataproc/v1/cluster_controller_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1/job_controller_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1/workflow_template_service_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1beta2/cluster_controller_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1beta2/job_controller_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1beta2/workflow_template_service_client_test.rb
Labels: cla: yes

#2804 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/acceptance/google/cloud/container/v1/cluster_manager_smoke_test.rb
  google-cloud-container/lib/google/cloud/container.rb
  google-cloud-container/lib/google/cloud/container/v1.rb
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1/credentials.rb
  google-cloud-container/lib/google/cloud/container/v1/doc/google/container/v1/cluster_service.rb
  google-cloud-container/lib/google/cloud/container/v1/doc/google/protobuf/empty.rb
  google-cloud-container/synth.metadata
  google-cloud-container/test/google/cloud/container/v1/cluster_manager_client_test.rb
Labels: cla: yes

#2803 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/credentials.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/bigtable_instance_admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/bigtable_table_admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/iam_policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/longrunning/operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/any.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/duration.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/empty.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/field_mask.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/timestamp.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/rpc/status.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/credentials.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/bigtable/v2/bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/bigtable/v2/data.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/protobuf/any.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/protobuf/wrappers.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/rpc/status.rb
  google-cloud-bigtable/synth.metadata
  google-cloud-bigtable/test/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/admin/v2/bigtable_table_admin_client_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/v2/bigtable_client_test.rb
Labels: cla: yes

#2802 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/acceptance/google/cloud/bigquery/data_transfer/v1/data_transfer_service_smoke_test.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/credentials.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/datatransfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/any.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/duration.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/empty.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/field_mask.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/struct.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/timestamp.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/rpc/status.rb
  google-cloud-bigquery-data_transfer/synth.metadata
  google-cloud-bigquery-data_transfer/test/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client_test.rb
Labels: cla: yes

#2801 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/credentials.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/asset_service.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/assets.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/any.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/struct.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/rpc/status.rb
  google-cloud-asset/synth.metadata
  google-cloud-asset/test/google/cloud/asset/v1beta1/asset_service_client_test.rb
Labels: cla: yes

#2830 Fix big query code sample in README.md
  README.md
  google-cloud-bigquery/README.md
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
Labels: api: bigquery, cla: yes

#2831 Release google-cloud-logging 1.6.0
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#2842 Fix release jobs
  .kokoro/build.sh
Labels: cla: yes

#2843 Release google-cloud-speech 0.33.0
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/google-cloud-speech.gemspec
Labels: api: speech, autorelease: pending, cla: yes

#2845 Release
  Rakefile
Labels: cla: yes

#2848 run git fetch prior to release process
  .kokoro/build.sh
Labels: cla: yes

#2846 generate initial irm library
  .kokoro/continuous/linux/irm.cfg
  .kokoro/continuous/osx/irm.cfg
  .kokoro/continuous/windows/irm.cfg
  .kokoro/nightly/linux/irm.cfg
  .kokoro/nightly/osx/irm.cfg
  .kokoro/nightly/windows/irm.cfg
  .kokoro/presubmit/linux/irm.cfg
  .kokoro/presubmit/osx/irm.cfg
  .kokoro/presubmit/windows/irm.cfg
  .kokoro/release/irm.cfg
  Rakefile
  google-cloud-irm/.gitignore
  google-cloud-irm/.rubocop.yml
  google-cloud-irm/.yardopts
  google-cloud-irm/CHANGELOG.md
  google-cloud-irm/Gemfile
  google-cloud-irm/LICENSE
  google-cloud-irm/README.md
  google-cloud-irm/Rakefile
  google-cloud-irm/google-cloud-irm.gemspec
  google-cloud-irm/lib/google/cloud/irm.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/credentials.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents_service.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/protobuf/empty.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/protobuf/field_mask.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/protobuf/timestamp.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/helpers.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client_config.json
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_pb.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_service_pb.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_service_services_pb.rb
  google-cloud-irm/synth.py
  google-cloud-irm/synth/helpers.rb.erb
  google-cloud-irm/synth/helpers_test.rb.erb
  google-cloud-irm/test/google/cloud/irm/v1alpha2/helpers_test.rb
  google-cloud-irm/test/google/cloud/irm/v1alpha2/incident_service_client_test.rb
Labels: cla: yes

#2849 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/target_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/task_pb.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#2829 Add list_collections alias
  google-cloud-firestore/lib/google/cloud/firestore/client.rb
  google-cloud-firestore/lib/google/cloud/firestore/document_reference.rb
  google-cloud-firestore/support/doctest_helper.rb
Labels: api: firestore, cla: yes, type: feature request

#2834 Add field_mask argument to get_all method
  google-cloud-firestore/acceptance/firestore/firestore_test.rb
  google-cloud-firestore/lib/google/cloud/firestore/client.rb
  google-cloud-firestore/lib/google/cloud/firestore/transaction.rb
  google-cloud-firestore/test/google/cloud/firestore/client/get_all_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/get_all_test.rb
Labels: api: firestore, cla: yes, type: feature request

#2850 Add __pycache__ to gitignore to prevent local synth from adding it
  .gitignore
Labels: cla: yes

#2853 Update Firestore Conformance
  google-cloud-firestore/conformance/test-suite.binproto
Labels: api: firestore, cla: yes, testing

#2856 Release google-cloud-core 1.3.0
  google-cloud-core/CHANGELOG.md
  google-cloud-core/lib/google/cloud/core/version.rb
Labels: api: core, autorelease: pending, cla: yes
