Repository googleapis/google-cloud-ruby, pull requests merged in 2019-02, with the labels that each got.

#2859 Release google-cloud-bigtable 0.3.0
  README.md
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/OVERVIEW.md
  google-cloud-bigtable/README.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#2860 Release google-cloud-asset 0.1.2
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/google-cloud-asset.gemspec
Labels: autorelease: pending, cla: yes

#2861 Release google-cloud-bigquery 1.11.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes

#2862 Release google-cloud-dataproc 0.3.0
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/google-cloud-dataproc.gemspec
Labels: autorelease: pending, cla: yes

#2863 Release google-cloud-datastore 1.5.0
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes

#2864 Release google-cloud-debugger 0.33.0
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#2865 Release google-cloud-dns 0.30.0
  google-cloud-dns/CHANGELOG.md
  google-cloud-dns/lib/google/cloud/dns/version.rb
Labels: autorelease: pending, cla: yes

#2858 Add RecognitionConfig#audio_channel_count attribute
  google-cloud-speech/lib/google/cloud/speech/v1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#2867 Release google-cloud-firestore 0.25.0
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#2868 Release google-cloud-monitoring 0.29.3
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/google-cloud-monitoring.gemspec
Labels: autorelease: pending, cla: yes

#2869 Release google-cloud-pubsub 0.34.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#2870 Release google-cloud-spanner 1.8.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#2871 Release google-cloud-storage 1.16.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes

#2872 Release google-cloud-tasks 0.3.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/google-cloud-tasks.gemspec
Labels: autorelease: pending, cla: yes

#2873 Release google-cloud-text_to_speech 0.2.0
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/google-cloud-text_to_speech.gemspec
Labels: autorelease: pending, cla: yes

#2874 Release google-cloud-translate 1.3.0
  google-cloud-translate/CHANGELOG.md
  google-cloud-translate/lib/google/cloud/translate/version.rb
Labels: autorelease: pending, cla: yes

#2875 Release google-cloud-speech 0.34.0
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/google-cloud-speech.gemspec
Labels: api: speech, autorelease: pending, cla: yes

#2857 update release process
  RELEASING.md
Labels: cla: yes, type: docs

#2795 Add Bucket#policy_only? and #policy_only=
  google-cloud-storage/acceptance/storage/bucket_policy_only_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/google/cloud/storage/bucket_policy_only_test.rb
  google-cloud-storage/test/helper.rb
Labels: api: storage, cla: yes

#2886 Restore manual verification of docs to RELEASING.md
  RELEASING.md
Labels: cla: yes

#2889 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cla: yes, type: cleanup

#2891 Update google-cloud-storage.gemspec
  google-cloud-storage/google-cloud-storage.gemspec
Labels: api: storage, cla: yes

#2877 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/README.md
  google-cloud-kms/lib/google/cloud/kms.rb
  google-cloud-kms/lib/google/cloud/kms/v1.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#2894 Fix test coverage task
  Gemfile
  gcloud/Gemfile
  google-cloud/Gemfile
  google-cloud/google-cloud.gemspec
Labels: cla: yes

#2892 Update concurrent-ruby dependency
  google-cloud-debugger/google-cloud-debugger.gemspec
  google-cloud-error_reporting/google-cloud-error_reporting.gemspec
  google-cloud-logging/google-cloud-logging.gemspec
  google-cloud-trace/google-cloud-trace.gemspec
Labels: api: clouddebugger, api: clouderrorreporting, api: cloudtrace, api: logging, cla: yes

#2878 fix out-date comments
  google-cloud-debugger/ext/google/cloud/debugger/debugger_c/tracer.c
Labels: api: cloudtrace, cla: yes, type: docs

#2893 Release google-cloud-storage 1.17.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: no

#2895 Release google-cloud-debugger 0.33.1
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#2896 Release google-cloud-error_reporting 0.31.1
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes

#2897 Release google-cloud-logging 1.6.1
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#2898 Release google-cloud-trace 0.34.0
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes

#2899 Release google-cloud-kms 0.3.0
  README.md
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/google-cloud-kms.gemspec
Labels: api: cloudkms, autorelease: pending, cla: yes

#2903 Fix typo
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-datastore/CHANGELOG.md
  google-cloud-debugger/CHANGELOG.md
  google-cloud-dns/CHANGELOG.md
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-firestore/CHANGELOG.md
  google-cloud-logging/CHANGELOG.md
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-spanner/CHANGELOG.md
  google-cloud-storage/CHANGELOG.md
  google-cloud-translate/CHANGELOG.md
Labels: cla: yes, type: docs

#2902 Fix proto conversion of ErrorEvent and Debuggee for Protobuf 3.7
  google-cloud-debugger/lib/google/cloud/debugger/debuggee.rb
  google-cloud-debugger/test/google/cloud/debugger/debuggee_test.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/error_event.rb
Labels: cla: yes

#2905 Release google-cloud-debugger 0.33.2
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: api: clouddebugger, autorelease: pending, cla: yes

#2904 Update RELEASING.md
  RELEASING.md
Labels: cla: yes

#2906 Remove circle and simplify release process
  .circleci/config.yml
  Rakefile
Labels: cla: yes

#2907 change scope for gemfile check
  Rakefile
Labels: cla: yes

#2909 Release google-cloud-error_reporting 0.31.2
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: api: clouderrorreporting, autorelease: pending, cla: yes

#2910 Resource Manager: Project Parent Resource
  google-cloud-resource_manager/lib/google/cloud/resource_manager/manager.rb
  google-cloud-resource_manager/lib/google/cloud/resource_manager/project.rb
  google-cloud-resource_manager/lib/google/cloud/resource_manager/project/updater.rb
  google-cloud-resource_manager/lib/google/cloud/resource_manager/resource.rb
  google-cloud-resource_manager/lib/google/cloud/resource_manager/service.rb
  google-cloud-resource_manager/support/doctest_helper.rb
  google-cloud-resource_manager/test/google/cloud/resource_manager/manager_test.rb
  google-cloud-resource_manager/test/google/cloud/resource_manager/project_test.rb
  google-cloud-resource_manager/test/google/cloud/resource_manager/resource_test.rb
  google-cloud-resource_manager/test/helper.rb
Labels: api: cloudresourcemanager, cla: yes

#2915 Release google-cloud-resource_manager 0.31.0
  google-cloud-resource_manager/CHANGELOG.md
  google-cloud-resource_manager/lib/google/cloud/resource_manager/version.rb
Labels: api: cloudresourcemanager, autorelease: pending, cla: yes

#2918 Fix typo calling configuration
  google-cloud-debugger/lib/google/cloud/debugger/transmitter.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/async_error_reporter.rb
  google-cloud-logging/lib/google/cloud/logging/async_writer.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-trace/lib/google/cloud/trace/async_reporter.rb
Labels: api: clouddebugger, api: clouderrorreporting, api: cloudtrace, api: logging, api: pubsub, cla: yes, type: bug

#2919 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client_config.json
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#2887 Add ReadOnlyTransaction#query convenience method
  google-cloud-datastore/acceptance/datastore/datastore_test.rb
  google-cloud-datastore/lib/google/cloud/datastore/read_only_transaction.rb
  google-cloud-datastore/support/doctest_helper.rb
  google-cloud-datastore/test/google/cloud/datastore/read_only_transaction_test.rb
Labels: api: datastore, cla: no, needs work

#2921 Release google-cloud-debugger 0.33.3
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#2922 Release google-cloud-error_reporting 0.31.3
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: api: clouderrorreporting, autorelease: pending, cla: yes

#2923 Release google-cloud-logging 1.6.2
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: api: logging, autorelease: pending, cla: yes

#2924 Release google-cloud-pubsub 0.34.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: api: pubsub, autorelease: pending, cla: yes

#2925 Release google-cloud-trace 0.34.1
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: api: cloudtrace, autorelease: pending, cla: yes

#2926 Release google-cloud-datastore 1.5.1
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: api: datastore, autorelease: pending, cla: yes

#2928 generate v1beta1
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/credentials.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/doc/google/cloud/texttospeech/v1beta1/cloud_tts.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client_config.json
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1beta1/cloud_tts_pb.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1beta1/cloud_tts_services_pb.rb
  google-cloud-text_to_speech/synth.metadata
  google-cloud-text_to_speech/synth.py
  google-cloud-text_to_speech/test/google/cloud/text_to_speech/v1beta1/text_to_speech_client_test.rb
Labels: api: texttospeech, cla: yes

#2929 regenerate irm
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/credentials.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/synth.metadata
  google-cloud-irm/synth.py
Labels: cla: yes

#2935 re-generate irm
  google-cloud-irm/lib/google/cloud/irm/v1alpha2.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents_service.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client_config.json
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_pb.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_service_pb.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_service_services_pb.rb
  google-cloud-irm/synth.metadata
  google-cloud-irm/test/google/cloud/irm/v1alpha2/incident_service_client_test.rb
Labels: api: irm, cla: yes

#2938 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#2937 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/any.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/lib/google/spanner/v1/spanner_pb.rb
  google-cloud-spanner/lib/google/spanner/v1/spanner_services_pb.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/v1/spanner_client_test.rb
Labels: cla: yes

#2940 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/lib/google/spanner/v1/spanner_pb.rb
  google-cloud-spanner/lib/google/spanner/v1/spanner_services_pb.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/v1/spanner_client_test.rb
Labels: cla: yes

#2939 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/README.md
  google-cloud-redis/lib/google/cloud/redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_services_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis/synth.metadata
  google-cloud-redis/test/google/cloud/redis/v1/cloud_redis_client_test.rb
Labels: cla: yes

#2934 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_services_pb.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/storage_pb.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#2931 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/resources.rb
  google-cloud-kms/lib/google/cloud/kms/v1/resources_pb.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#2941 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/target_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/task_pb.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#2943 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_services_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/asset_service.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/assets.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/rpc/status.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#2944 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/rpc/status.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#2945 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/rpc/status.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/rpc/status.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#2946 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/rpc/status.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/rpc/status.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#2947 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/datastore.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/entity.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/query.rb
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#2948 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agent_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/context_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/context.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session_entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/rpc/status.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#2949 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/rpc/status.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/type/date.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/type/timeofday.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#2950 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/report_errors_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/report_errors_service_services_pb.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#2951 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/rpc/status.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/rpc/status.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#2952 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/resources.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/service.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/lib/google/cloud/kms/v1/service_services_pb.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#2953 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/type/http_request.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#2954 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/monitored_resource.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/common.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/group.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/rpc/status.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_services_pb.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#2955 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/rpc/status.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/cloud/redis/v1beta1/cloud_redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/rpc/status.rb
  google-cloud-redis/synth.metadata
Labels: cla: yes

#2956 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/spanner/admin/database/v1/spanner_database_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/spanner/admin/instance/v1/spanner_instance_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/keys.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/mutation.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/query_plan.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/result_set.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/transaction.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/type.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/lib/google/spanner/admin/database/v1/spanner_database_admin_services_pb.rb
  google-cloud-spanner/lib/google/spanner/admin/instance/v1/spanner_instance_admin_services_pb.rb
  google-cloud-spanner/lib/google/spanner/v1/spanner_services_pb.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#2957 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/rpc/status.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/rpc/status.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#2958 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/rpc/status.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/rpc/status.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#2959 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/rpc/status.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#2960 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#2961 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/rpc/status.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/rpc/status.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#2964 Release google-cloud-video_intelligence 1.1.4
  google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/google-cloud-video_intelligence.gemspec
Labels: api: videointelligence, autorelease: pending, cla: yes

#2936 Fix label_detection helper smoke test
  google-cloud-vision/acceptance/google/cloud/vision/v1/helpers_smoke_test.rb
  google-cloud-vision/acceptance/google/cloud/vision/v1p3beta1/helpers_smoke_test.rb
  google-cloud-vision/synth/helpers_smoke_test.rb.erb
Labels: :rotating_light:, api: vision, cla: yes, testing

#2967 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_services_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#2968 Fix acceptance tests of Numeric types
  google-cloud-bigquery/acceptance/bigquery/table_test.rb
Labels: api: bigquery, cla: yes, testing
