Repository googleapis/google-cloud-ruby, pull requests merged in 2019-09, with the labels that each got.

#3995 Release google-cloud-pubsub 0.39.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#3994 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/firestore_admin_client_config.json
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client_config.json
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#3993 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/bigtable/admin/v2/bigtable_table_admin_pb.rb
  google-cloud-bigtable/lib/google/bigtable/admin/v2/bigtable_table_admin_services_pb.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client_config.json
  google-cloud-bigtable/synth.metadata
  google-cloud-bigtable/test/google/cloud/bigtable/admin/v2/bigtable_table_admin_client_test.rb
Labels: cla: yes

#3980 Release google-cloud-bigquery 1.14.1
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3981 Release google-cloud-asset 0.3.2
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3984 Release google-cloud-security_center 0.3.2
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3985 Release google-cloud-tasks 1.1.2
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3987 Release google-cloud-spanner 1.10.1
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3983 Release google-cloud-container_analysis 0.3.1
  google-cloud-container_analysis/CHANGELOG.md
  google-cloud-container_analysis/lib/google/cloud/container_analysis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3996 chore: fix link tests
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#3986 Release google-cloud-bigtable 0.6.1
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3997 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3942 Update version file location
  grafeas-client/grafeas-client.gemspec
  grafeas-client/lib/grafeas/client/version.rb
  grafeas-client/lib/grafeas/v1/grafeas_client.rb
  grafeas-client/synth.py
Labels: cla: yes, type: cleanup

#4012 feat(dns): Support overriding of service endpoint
  google-cloud-dns/lib/google-cloud-dns.rb
  google-cloud-dns/lib/google/cloud/dns.rb
  google-cloud-dns/lib/google/cloud/dns/service.rb
  google-cloud-dns/test/google/cloud/dns_test.rb
Labels: cla: yes

#4010 feat(resource_manager): Support overriding of service endpoint
  google-cloud-resource_manager/lib/google-cloud-resource_manager.rb
  google-cloud-resource_manager/lib/google/cloud/resource_manager.rb
  google-cloud-resource_manager/lib/google/cloud/resource_manager/service.rb
  google-cloud-resource_manager/test/google/cloud/resource_manager_test.rb
Labels: cla: yes

#4022 Do not interrupt Subscriber callbacks when stopping
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
Labels: api: pubsub, cla: yes, type: bug

#4021 Update Subscriber stop and wait documentation
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
Labels: api: pubsub, cla: yes, type: docs

#4026 Release google-cloud-pubsub 0.39.2
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4031 Support overriding of service endpoint
  google-cloud-translate/lib/google-cloud-translate.rb
  google-cloud-translate/lib/google/cloud/translate.rb
  google-cloud-translate/lib/google/cloud/translate/service.rb
  google-cloud-translate/test/google/cloud/translate_test.rb
Labels: api: translation, cla: yes

#4029 Support use_avro_logical_types on extract jobs
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-bigquery/lib/google/cloud/bigquery/extract_job.rb
  google-cloud-bigquery/test/google/cloud/bigquery/extract_job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_extract_job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_extract_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_extract_job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_extract_test.rb
Labels: api: bigquery, cla: yes

#4030 Add range support for Google Sheets
  google-cloud-bigquery/lib/google/cloud/bigquery/external.rb
  google-cloud-bigquery/test/google/cloud/bigquery/external_sheets_source_test.rb
Labels: api: bigquery, cla: yes

#4039 Add Model encryption
  google-cloud-bigquery/lib/google/cloud/bigquery/model.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/partial/attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/partial/update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/reference/attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/reference/update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/resource/attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/resource/update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_update_test.rb
  google-cloud-bigquery/test/helper.rb
Labels: api: bigquery, cla: yes

#4037 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/firestore/admin/v1/field.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/firestore/admin/v1/index.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/query.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/firestore_admin_pb.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/index_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/firestore_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/firestore_services_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/query_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/firestore_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/firestore_services_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/query_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#4024 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#4025 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agent_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/context_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_type_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow/synth.metadata
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/entity_types_client_test.rb
Labels: cla: yes

#4033 test only updated gems
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#4054 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_pb.rb
  google-cloud-redis/synth.metadata
  google-cloud-redis/test/google/cloud/redis/v1/cloud_redis_client_test.rb
  google-cloud-redis/test/google/cloud/redis/v1beta1/cloud_redis_client_test.rb
Labels: cla: yes

#4050 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/lib/google/cloud/vision/v1.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/image_annotator.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/text_annotation.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_service_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_service_services_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/text_annotation_pb.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#4045 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/policy.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4044 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#4043 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/policy.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#4042 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/policy.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#4041 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/policy.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4032 Update storage class examples in docs and tests
  google-cloud-storage/acceptance/storage/bucket_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/bucket/lifecycle.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/google/cloud/storage/bucket_update_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_update_test.rb
Labels: api: storage, cla: yes

#4068 Register is a Hash, not Concurrent::Map
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/timed_unary_buffer.rb
Labels: api: pubsub, cla: yes

#4067 Set lower max_bytes default
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/timed_unary_buffer.rb
Labels: api: pubsub, cla: yes

#4070 Use multi-regional locations in KMS keys
  google-cloud-bigquery/acceptance/bigquery_helper.rb
Labels: api: bigquery, cla: yes, testing

#4062 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client_config.json
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4014 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client.rb
  google-cloud-webrisk/synth.metadata
  google-cloud-webrisk/test/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client_test.rb
Labels: cla: yes

#4085 Fix Subscriber#wait! behavior.
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
Labels: api: pubsub, cla: yes

#4084 Update path to dialogflow artman config
  google-cloud-dialogflow/synth.py
Labels: cla: yes

#4088 Release google-cloud-pubsub 0.39.3
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4087 Allow wait to block for specified time
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/support/doctest_helper.rb
Labels: api: pubsub, cla: yes

#4092 Add convenience method calling both stop and wait!
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-pubsub/support/doctest_helper.rb
Labels: api: pubsub, cla: yes

#4069 Release google-cloud-storage 1.21.1
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4035 Release google-cloud-bigquery 1.15.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4098 Release google-cloud-pubsub 1.0.0
  README.md
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
  google-cloud/google-cloud.gemspec
Labels: api: pubsub, autorelease: pending, cla: yes

#4100 Release google-cloud 0.62.0
  google-cloud/CHANGELOG.md
  google-cloud/lib/google/cloud/version.rb
Labels: autorelease: pending, cla: yes

#4101 chore(talent): Update synth for talent to include updated common protos dependency
  google-cloud-talent/synth.py
Labels: cla: yes

#4061 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl/v1beta1/automl_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/image.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/service.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/image_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/service_pb.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes
