Repository googleapis/google-cloud-ruby, pull requests merged in 2019-05, with the labels that each got.

#3277 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/run_asset_discovery_response_pb.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#3279 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/README.md
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/lib/google/cloud/vision/v1.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/image_annotator.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/web_detection.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client_config.json
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_services_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client_config.json
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_service_services_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/web_detection_pb.rb
  google-cloud-vision/synth.metadata
  google-cloud-vision/test/google/cloud/vision/v1/image_annotator_client_test.rb
  google-cloud-vision/test/google/cloud/vision/v1/product_search_client_test.rb
Labels: api: vision, cla: yes

#3282 Release google-cloud 0.59.0
  google-cloud/CHANGELOG.md
Labels: autorelease: pending, cla: yes

#3274 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/audio_config_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow/synth.metadata
Labels: api: dialogflow, cla: yes

#3283 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/synth.metadata
  google-cloud-security_center/test/google/cloud/security_center/v1/security_center_client_test.rb
Labels: api: securitycenter, cla: yes

#3289 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3290 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/README.md
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/synth.metadata
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1/video_intelligence_service_client_test.rb
Labels: cla: yes

#3287 Release google-cloud-security_center 0.2.0
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/google-cloud-security_center.gemspec
Labels: autorelease: pending, cla: yes

#3291 Fix Rubocop errors in google-cloud-translate
  google-cloud-translate/google-cloud-translate.gemspec
  google-cloud-translate/lib/google/cloud/translate/credentials.rb
  google-cloud-translate/lib/google/cloud/translate/service.rb
Labels: api: translation, cla: yes, testing, type: cleanup

#3284 Fix errors in bigtable code sample
  README.md
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
Labels: api: bigtable, cla: yes, type: docs

#3292 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/type/expr.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/type/expr.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3293 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/iam_policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/type/expr.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3296 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/policy.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/type/expr.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#3297 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/type/expr.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/type/expr.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3298 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/type/expr.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/type/expr.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/type/expr.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3300 Allow floats in Google::Cloud::Trace::Utils.time_to_grpc
  google-cloud-trace/lib/google/cloud/trace/utils.rb
  google-cloud-trace/test/google/cloud/trace/utils_test.rb
Labels: api: cloudtrace, cla: yes

#3304 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client_config.json
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client_config.json
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3305 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client_config.json
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#3306 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client_config.json
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client_config.json
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client_config.json
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3307 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client_config.json
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client_config.json
  google-cloud-container/synth.metadata
Labels: cla: yes

#3308 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/job_controller_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client_config.json
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#3310 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client_config.json
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client_config.json
  google-cloud-debugger/synth.metadata
Labels: cla: yes

#3311 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client_config.json
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3312 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client_config.json
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3313 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client_config.json
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client_config.json
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client_config.json
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#3314 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client_config.json
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client_config.json
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#3315 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client_config.json
  google-cloud-irm/synth.metadata
Labels: cla: yes

#3309 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client_config.json
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#3316 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/lib/google/cloud/language/v1/language_service_client_config.json
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client_config.json
  google-cloud-language/synth.metadata
Labels: cla: yes

#3317 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client_config.json
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3318 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client_config.json
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client_config.json
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client_config.json
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client_config.json
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client_config.json
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#3319 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client_config.json
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client_config.json
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#3320 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_client_config.json
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#3321 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client_config.json
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#3322 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client_config.json
  google-cloud-redis/synth.metadata
Labels: cla: yes

#3323 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client_config.json
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#3324 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client_config.json
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3325 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client_config.json
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client_config.json
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3327 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client_config.json
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client_config.json
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client_config.json
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3328 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client_config.json
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client_config.json
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#3237 fix pubsub tests
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/acknowledge_test.rb
Labels: :rotating_light:, api: pubsub, cla: yes

#3288 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/google-cloud-pubsub.gemspec
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_services_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: api: pubsub, cla: no

#3295 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloudscheduler_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/job.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/target.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/job_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/target_pb.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3326 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client_config.json
  google-cloud-talent/synth.metadata
  google-cloud-talent/test/google/cloud/talent/v4beta1/profile_service_client_test.rb
Labels: cla: yes

#3329 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client_config.json
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client_config.json
  google-cloud-trace/synth.metadata
Labels: cla: yes

#3330 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#3331 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client_config.json
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client_config.json
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/image_annotator_client_config.json
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client_config.json
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3332 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client_config.json
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#3337 asset - remove extra space from gemspec
  google-cloud-asset/google-cloud-asset.gemspec
  google-cloud-asset/synth.metadata
  google-cloud-asset/synth.py
Labels: api: cloudasset, cla: yes

#3338 bigquery-data_transfer - add version.rb and remove Gem.loaded_specs
  google-cloud-bigquery-data_transfer/google-cloud-bigquery-data_transfer.gemspec
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
  google-cloud-bigquery-data_transfer/synth.metadata
  google-cloud-bigquery-data_transfer/synth.py
Labels: api: bigquerydatatransfer, cla: yes

#3336 Fix trace test
  google-cloud-trace/test/google/cloud/trace/utils_test.rb
Labels: api: cloudtrace, cla: yes, testing

#3346 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client_config.json
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloud_scheduler_client_config.json
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3340 bigtable - use version.rb instead of Gem.loaded_specs
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client.rb
  google-cloud-bigtable/synth.metadata
  google-cloud-bigtable/synth.py
Labels: api: bigtable, api: bigtableadmin, cla: yes

#3341 container - add version.rb and use it in place of Gem.loaded_specs
  google-cloud-container/google-cloud-container.gemspec
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/version.rb
  google-cloud-container/synth.metadata
  google-cloud-container/synth.py
Labels: api: container, cla: yes

#3343 debugger - use version.rb in place of Gem.loaded_specs
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/synth.metadata
  google-cloud-debugger/synth.py
Labels: api: clouddebugger, cla: yes

#3342 dataproc - add version.rb and use it in place of Gem.loaded_specs
  google-cloud-dataproc/google-cloud-dataproc.gemspec
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
  google-cloud-dataproc/synth.metadata
  google-cloud-dataproc/synth.py
Labels: api: dataproc, cla: yes

#3344 datastore - use version.rb in place of Gem.loaded_specs
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb
  google-cloud-datastore/synth.metadata
  google-cloud-datastore/synth.py
Labels: api: datastore, cla: yes

#3349 talent - re-add DEADLINE_EXCEEDED to retry codes
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client_config.json
  google-cloud-talent/synth.metadata
Labels: api: talent-solution, cla: yes

#3350 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client_config.json
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client_config.json
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3351 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client_config.json
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#3352 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client_config.json
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client_config.json
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client_config.json
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3353 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client_config.json
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client_config.json
  google-cloud-container/synth.metadata
Labels: cla: yes

#3354 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/job_controller_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client_config.json
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#3355 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client_config.json
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#3356 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client_config.json
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client_config.json
  google-cloud-debugger/synth.metadata
Labels: cla: yes

#3357 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client_config.json
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3358 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client_config.json
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3359 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client_config.json
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client_config.json
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client_config.json
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#3360 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client_config.json
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client_config.json
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#3361 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client_config.json
  google-cloud-irm/synth.metadata
Labels: cla: yes

#3362 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/lib/google/cloud/language/v1/language_service_client_config.json
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client_config.json
  google-cloud-language/synth.metadata
Labels: cla: yes

#3363 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client_config.json
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3364 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client_config.json
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client_config.json
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client_config.json
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client_config.json
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client_config.json
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#3365 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client_config.json
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client_config.json
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#3366 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_client_config.json
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#3367 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client_config.json
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#3368 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client_config.json
  google-cloud-redis/synth.metadata
Labels: cla: yes

#3369 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client_config.json
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloud_scheduler_client_config.json
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3339 Add mime types dependency
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-storage/google-cloud-storage.gemspec
Labels: api: bigquery, api: storage, cla: yes

#3370 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client_config.json
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#3371 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client_config.json
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3372 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client_config.json
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client_config.json
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3373 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client_config.json
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client_config.json
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client_config.json
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3374 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client_config.json
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client_config.json
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#3375 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client_config.json
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client_config.json
  google-cloud-trace/synth.metadata
Labels: cla: yes

#3379 Release google-cloud-talent 0.3.0
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/google-cloud-talent.gemspec
Labels: api: talent-solution, autorelease: pending, cla: yes

#3376 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/README.md
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/synth.metadata
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1/video_intelligence_service_client_test.rb
Labels: cla: yes

#3377 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client_config.json
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client_config.json
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/image_annotator_client_config.json
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client_config.json
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3378 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client_config.json
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#3380 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/metric.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3381 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/monitored_resource.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#3383 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/image_annotator.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3382 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloudtasks_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/queue_pb.rb
  google-cloud-tasks/synth.metadata
  google-cloud-tasks/test/google/cloud/tasks/v2beta3/cloud_tasks_client_test.rb
Labels: cla: yes

#3385 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3386 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/synth.metadata
  google-cloud-talent/test/google/cloud/talent/v4beta1/profile_service_client_test.rb
Labels: cla: yes

#3387 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloudtasks_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3345 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/type/expr.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3294 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/type/expr.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/synth.metadata
Labels: :rotating_light:, cla: yes

#3393 Resolve BigDecimal deprecation warnings
  google-cloud-pubsub/test/google/cloud/pubsub/convert/number_to_duration_test.rb
  google-cloud-spanner/test/google/cloud/spanner/convert/number_to_duration_test.rb
Labels: api: pubsub, api: spanner, cla: yes, type: cleanup

#3392 Pub/Sub: Add Topic#kms_key
  google-cloud-pubsub/lib/google/cloud/pubsub/project.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/project_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/update_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: api: pubsub, cla: yes, type: feature request

#3396 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3397 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/README.md
  google-cloud-scheduler/lib/google/cloud/scheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3398 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/README.md
  google-cloud-tasks/lib/google/cloud/tasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3395 Set Bigtable max length headers
  google-cloud-bigtable/lib/google/cloud/bigtable/service.rb
Labels: api: bigtable, cla: yes, type: bug

#3401 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3405 Release google-cloud-bigquery 1.11.1
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes

#3406 Release google-cloud-storage 1.18.2
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes

#3404 Release google-cloud-bigtable 0.4.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#3403 Release google-cloud-pubsub 0.36.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#3402 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agent_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/context_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_type_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3409 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3417 Change test fixture date-formatted String to Date in Lifecycle::Rule::Condition tests
  google-cloud-storage/test/google/cloud/storage/bucket_update_test.rb
Labels: api: storage, cla: yes, testing

#3418 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3412 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client_config.json
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3415 Release google-cloud-scheduler 1.0.0
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/google-cloud-scheduler.gemspec
  google-cloud/google-cloud.gemspec
Labels: autorelease: pending, cla: yes

#3414 Release google-cloud-tasks 1.0.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/google-cloud-tasks.gemspec
  google-cloud/google-cloud.gemspec
Labels: autorelease: pending, cla: yes

#3421 Update dataproc synth script to fix AutoscalingPolicy name collision
  google-cloud-dataproc/synth.py
Labels: cla: yes

#3423 Fix Loading data documentation link
  google-cloud-bigquery/lib/google/cloud/bigquery/load_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema/field.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
Labels: api: bigquery, cla: yes, type: docs

#3422 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/batch_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/common_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/completion_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/histogram.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/longrunning/operations.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/protobuf/any.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/rpc/status.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/filters_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/histogram_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_services_pb.rb
  google-cloud-talent/synth.metadata
  google-cloud-talent/test/google/cloud/talent/v4beta1/job_service_client_test.rb
Labels: cla: yes

#3416 Firestore Collection Group queries
  google-cloud-firestore/acceptance/firestore/query_test.rb
  google-cloud-firestore/lib/google/cloud/firestore/client.rb
  google-cloud-firestore/lib/google/cloud/firestore/collection_reference.rb
  google-cloud-firestore/lib/google/cloud/firestore/query.rb
  google-cloud-firestore/support/doctest_helper.rb
  google-cloud-firestore/test/google/cloud/firestore/client/col_group_test.rb
Labels: api: firestore, cla: yes

#3399 feat(env): Google::Cloud::Env provides additional configuration options including retries and cache control
  google-cloud-debugger/test/google/cloud/debugger/debuggee_test.rb
  google-cloud-env/lib/google/cloud/env.rb
  google-cloud-env/test/google/cloud/env_test.rb
Labels: cla: yes

#3426 build: get magictokens from FASTCONFIGPUSH
  .kokoro/release/common.cfg
Labels: cla: yes

#3428 Add Topic#persistence_regions
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/attrs_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: api: pubsub, cla: yes, type: feature request
