Repository googleapis/google-cloud-ruby, pull requests merged in 2019-08, with the labels that each got.

#3721 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3722 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/README.md
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#3727 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client_config.json
  google-cloud-monitoring/synth.metadata
  google-cloud-monitoring/test/google/cloud/monitoring/v3/notification_channel_service_client_test.rb
Labels: cla: yes

#3725 successfully fail
  Rakefile
Labels: cla: yes

#3728 verify env_vars for kokoro jobs
  Rakefile
Labels: cla: yes

#3729 add triggerable kokoro job to republish all docs
  .kokoro/build.sh
  .kokoro/release/republish.cfg
  Rakefile
Labels: cla: yes

#3730 add missing releases
  _data/releases.yaml
Labels: cla: yes

#3731 Release google-cloud-pubsub 0.38.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#3732 Use MiniMime to detect content types
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-storage/google-cloud-storage.gemspec
  google-cloud-storage/lib/google/cloud/storage/service.rb
Labels: api: bigquery, api: storage, cla: yes

#3734 fix(storage): Specify current file generation within File#download
  google-cloud-storage/acceptance/storage/file_test.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/test/google/cloud/storage/file_test.rb
  google-cloud-storage/test/google/cloud/storage/project_anonymous_test.rb
Labels: api: storage, cla: yes

#3724 add ".html" to urls ending in a capitalized word
  404.html
  index.html
  js/devsite-forwarder/.gitignore
  js/devsite-forwarder/main.js
  js/devsite-forwarder/package.json
  js/devsite-forwarder/test/main-test.js
  js/jsondoc-forwarder-init-0.1.0.js
Labels: cla: yes

#3737 Release google-cloud-bigtable 0.5.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#3739 fix kokoro:republish
  .kokoro/build.sh
Labels: cla: yes

#3740 provide default value for staging-bucket
  rakelib/gem_version_doc.rb
Labels: cla: yes

#3738 Update Data#total assertions
  google-cloud-bigquery/acceptance/bigquery/dataset_test.rb
  google-cloud-bigquery/acceptance/bigquery/location_test.rb
  google-cloud-bigquery/acceptance/bigquery/table_reference_test.rb
  google-cloud-bigquery/acceptance/bigquery/table_test.rb
Labels: api: bigquery, cla: yes, testing

#3741 chore: update to newest docuploader process
  .kokoro/release/common.cfg
  rakelib/gem_version_doc.rb
Labels: cla: yes

#3735 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3736 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/filters_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/histogram_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_pb.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3744 Add assert_data acceptance method
  google-cloud-bigquery/acceptance/bigquery/dataset_test.rb
  google-cloud-bigquery/acceptance/bigquery/location_test.rb
  google-cloud-bigquery/acceptance/bigquery/table_reference_test.rb
  google-cloud-bigquery/acceptance/bigquery/table_test.rb
  google-cloud-bigquery/acceptance/bigquery_helper.rb
Labels: api: bigquery, cla: yes, testing

#3743 Remove cache_hit? acceptance checks
  google-cloud-bigquery/acceptance/bigquery/bigquery_test.rb
  google-cloud-bigquery/acceptance/bigquery/table_test.rb
Labels: api: bigquery, cla: yes, testing

#3745 Remove acceptance timestamp checks
  google-cloud-spanner/acceptance/spanner/client/snapshot_test.rb
Labels: api: spanner, cla: yes, testing

#3742 feat(bigquery): Support overriding of service endpoint
  google-cloud-bigquery/lib/google-cloud-bigquery.rb
  google-cloud-bigquery/lib/google/cloud/bigquery.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/test/google/cloud/bigquery_test.rb
Labels: cla: yes

#3746 test(storage): Fix incorrect download object in acceptance test
  google-cloud-storage/acceptance/storage/file_encryption_test.rb
Labels: api: storage, cla: yes

#3747 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_pb.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3748 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_pb.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#3749 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/image_annotator.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/text_annotation.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/web_detection.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client_config.json
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_service_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_service_services_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1/web_detection_pb.rb
  google-cloud-vision/synth.metadata
  google-cloud-vision/test/google/cloud/vision/v1/product_search_client_test.rb
Labels: cla: yes

#3751 chore(bigtable): Fix style issues in g/c/bigtable.rb
  google-cloud-bigtable/.rubocop.yml
  google-cloud-bigtable/lib/google/cloud/bigtable.rb
Labels: cla: yes

#3765 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/iam/v1/policy.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3766 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/policy.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3767 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/policy.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#3768 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/policy.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#3769 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3770 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/policy.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3400 Add Storage::HmacKey
  google-cloud-storage/.rubocop.yml
  google-cloud-storage/acceptance/storage/project_test.rb
  google-cloud-storage/conformance/v1/proto/google/cloud/conformance/storage/v1/tests.proto
  google-cloud-storage/conformance/v1/proto/google/cloud/conformance/storage/v1/tests_pb.rb
  google-cloud-storage/conformance/v1/test_service_account.not-a-test.json
  google-cloud-storage/conformance/v1/v4_signatures.json
  google-cloud-storage/lib/google/cloud/storage/file/signer_v4.rb
  google-cloud-storage/lib/google/cloud/storage/hmac_key.rb
  google-cloud-storage/lib/google/cloud/storage/hmac_key/list.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/lib/google/cloud/storage/service.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/google/cloud/storage/file/signer_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/hmac_key_test.rb
  google-cloud-storage/test/google/cloud/storage/project_hmac_keys_test.rb
Labels: api: storage, cla: yes, do not merge

#3726 Mark old storage classes as legacy
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
Labels: api: storage, cla: yes

#3772 test(storage): Skip bucket policy only acceptance tests pending GCS fix
  google-cloud-storage/acceptance/storage/bucket_policy_only_test.rb
  google-cloud-storage/acceptance/storage/project_test.rb
Labels: api: storage, cla: yes

#3771 Release google-cloud-storage 1.20.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: api: storage, autorelease: pending, cla: yes

#3752 feat(bigtable): Support overriding of the service endpoint
  google-cloud-bigtable/lib/google-cloud-bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable.rb
  google-cloud-bigtable/test/google/cloud/bigtable_test.rb
Labels: cla: yes

#3779 test(storage): Fix acceptance bucket_test versioning assertion
  google-cloud-storage/acceptance/storage/bucket_test.rb
Labels: api: storage, cla: yes, testing

#3774 [WIP] chore: release google-cloud-vision@0.35.0
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: autorelease: pending, cla: no, type: process

#3780 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl/v1beta1/automl_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/classification_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/classification.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/column_spec.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/data_items.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/data_types.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/detection.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/image.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/io.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/model.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/model_evaluation.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/prediction_service.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/service.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/table_spec.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/tables.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/text.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_services_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/service_services_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/table_spec_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/tables_pb.rb
  google-cloud-automl/synth.metadata
  google-cloud-automl/test/google/cloud/automl/v1beta1/automl_client_test.rb
Labels: cla: yes

#3776 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_pb.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3750 GKE Metadata Server requires header "Metadata-Flavor": "Google" at METADATA_ROOT_PATH
  google-cloud-env/lib/google/cloud/env.rb
Labels: cla: yes

#3764 feat(storage): Support overriding of service endpoint
  google-cloud-storage/lib/google-cloud-storage.rb
  google-cloud-storage/lib/google/cloud/storage.rb
  google-cloud-storage/lib/google/cloud/storage/service.rb
  google-cloud-storage/test/google/cloud/storage_test.rb
Labels: api: storage, cla: yes

#3777 feat(datastore): Support overriding of service endpoint
  google-cloud-datastore/lib/google-cloud-datastore.rb
  google-cloud-datastore/lib/google/cloud/datastore.rb
  google-cloud-datastore/test/google/cloud/datastore_test.rb
Labels: api: datastore, cla: yes

#3778 feat(firestore): Support overriding of service endpoint
  google-cloud-firestore/lib/google-cloud-firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore.rb
  google-cloud-firestore/test/google/cloud/firestore_test.rb
Labels: api: firestore, cla: yes

#3782 Release google-cloud-video_intelligence 1.4.0
  google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/version.rb
Labels: api: videointelligence, autorelease: pending, cla: yes

#3783 docs: fix 404s
  AUTHENTICATION.md
  README.md
  RELEASING.md
  Rakefile
  gcloud/README.md
  google-cloud-asset/synth.py
  google-cloud-bigquery/OVERVIEW.md
  google-cloud-bigtable/samples/README.md
  google-cloud-error_reporting/INSTRUMENTATION.md
  google-cloud-error_reporting/README.md
  google-cloud-phishing_protection/synth.py
  google-cloud-recaptcha_enterprise/synth.py
  google-cloud-scheduler/synth.py
  google-cloud-spanner/OVERVIEW.md
  google-cloud-trace/INSTRUMENTATION.md
  google-cloud/README.md
  integration/README.md
Labels: cla: yes, type: docs

#3786 fix(spanner): Low-level admin clients now honor service_address and service_port
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/synth.py
Labels: cla: yes

#3788 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client_config.json
  google-cloud-kms/synth.metadata
Labels: cla: yes

#3789 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/README.md
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#3790 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/README.md
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#3791 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/README.md
  google-cloud-scheduler/lib/google/cloud/scheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3792 feat(spanner): Support overriding of service endpoint
  google-cloud-spanner/lib/google-cloud-spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/service.rb
  google-cloud-spanner/test/google/cloud/spanner_test.rb
Labels: api: spanner, cla: yes

#3793 feat(debugger): Support overriding of service endpoint
  google-cloud-debugger/lib/google-cloud-debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger/service.rb
  google-cloud-debugger/test/google/cloud/debugger_test.rb
Labels: api: clouddebugger, cla: yes

#3787 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/README.md
  google-cloud-asset/lib/google/cloud/asset.rb
  google-cloud-asset/lib/google/cloud/asset/v1.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3794 fix(storage): Fix Bucket Policy Only service bug temporarily
  google-cloud-storage/acceptance/storage/bucket_policy_only_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/test/helper.rb
Labels: cla: yes

#3796 feat(error_reporting): Support overriding of service endpoint
  google-cloud-error_reporting/lib/google-cloud-error_reporting.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/service.rb
  google-cloud-error_reporting/test/google/cloud/error_reporting_test.rb
Labels: api: clouderrorreporting, cla: yes

#3798 Release google-cloud-storage 1.21.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3800 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl/v1beta1/data_items_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/data_items.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/io.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/prediction_service.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_services_pb.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes

#3801 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3804 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3795 refactor kokoro and add release-please
  .kokoro/continuous/linux/common.cfg
  .kokoro/continuous/linux/post.cfg
  .kokoro/docker/multi-node/Dockerfile
  .kokoro/templates/post.cfg.erb
  Rakefile
  rakelib/devsite/devsite_builder.rb
  rakelib/devsite/gem_version_doc.rb
  rakelib/devsite/repo_doc_common.rb
  rakelib/devsite/repo_metadata.rb
  rakelib/devsite/yard_builder.rb
  rakelib/kokoro/command.rb
  rakelib/kokoro/kokoro.rb
  rakelib/kokoro/kokoro_builder.rb
Labels: cla: yes

#3802 feat(logging): Support overriding of service endpoint
  google-cloud-logging/lib/google-cloud-logging.rb
  google-cloud-logging/lib/google/cloud/logging.rb
  google-cloud-logging/lib/google/cloud/logging/service.rb
  google-cloud-logging/test/google/cloud/logging_test.rb
Labels: api: logging, cla: yes

#3803 feat(trace): Support overriding of service endpoint
  google-cloud-trace/lib/google-cloud-trace.rb
  google-cloud-trace/lib/google/cloud/trace.rb
  google-cloud-trace/lib/google/cloud/trace/service.rb
  google-cloud-trace/test/google/cloud/trace_test.rb
Labels: api: cloudtrace, cla: yes

#3806 feat(firestore): Add low-level admin API
  google-cloud-firestore/.rubocop.yml
  google-cloud-firestore/lib/google/cloud/firestore/admin.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/credentials.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/firestore/admin/v1/field.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/firestore/admin/v1/firestore_admin.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/firestore/admin/v1/index.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/longrunning/operations.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/protobuf/any.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/protobuf/empty.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/protobuf/field_mask.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/rpc/status.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/firestore_admin_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/firestore_admin_client_config.json
  google-cloud-firestore/lib/google/firestore/admin/v1/field_pb.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/firestore_admin_pb.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/firestore_admin_services_pb.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/index_pb.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/location_pb.rb
  google-cloud-firestore/lib/google/firestore/admin/v1/operation_pb.rb
  google-cloud-firestore/support/doctest_helper.rb
  google-cloud-firestore/synth.metadata
  google-cloud-firestore/synth.py
  google-cloud-firestore/test/google/cloud/firestore/admin/v1/firestore_admin_client_test.rb
Labels: cla: yes

#3807 chore: only run release-please on linux os
  rakelib/kokoro/command.rb
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#3808 chore: skip presubmit tests when commit message contains "[ci skip]"
  .kokoro/osx.sh
  .kokoro/trampoline.bat
  .kokoro/trampoline.sh
Labels: cla: yes

#3813 chore: configure renovate to ignore rubocop
  renovate.json
Labels: cla: yes

#3865 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloudtasks_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/queue_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/task_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloudtasks_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/queue_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/target_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/task_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloudtasks_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/queue_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/task_pb.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3810 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3937 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3901 chore: run release-please during nightly linux builds
  .kokoro/continuous/linux/common.cfg
  .kokoro/nightly/linux/common.cfg
  rakelib/kokoro/command.rb
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#3936 Release stackdriver-core 1.3.4
  stackdriver-core/CHANGELOG.md
  stackdriver-core/lib/stackdriver/core/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3935 Release stackdriver 0.15.5
  stackdriver/CHANGELOG.md
  stackdriver/lib/stackdriver/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3934 Release grafeas-client 0.2.1
  grafeas-client/CHANGELOG.md
  grafeas-client/lib/grafeas/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3933 Release google-cloud-webrisk 0.2.1
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3932 Release google-cloud-translate 1.3.1
  google-cloud-translate/CHANGELOG.md
  google-cloud-translate/lib/google/cloud/translate/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3931 Release google-cloud-trace 0.35.0
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3930 Release google-cloud-text_to_speech 0.4.1
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3929 Release google-cloud-tasks 1.1.1
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3927 Release google-cloud-speech 0.37.0
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3925 Release google-cloud-security_center 0.3.1
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3924 Release google-cloud-scheduler 1.1.1
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/lib/google/cloud/scheduler/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3923 Release google-cloud-resource_manager 0.31.1
  google-cloud-resource_manager/CHANGELOG.md
  google-cloud-resource_manager/lib/google/cloud/resource_manager/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3922 Release google-cloud-redis 0.5.1
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3921 Release google-cloud-recaptcha_enterprise 0.2.1
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3919 Release google-cloud-phishing_protection 0.2.1
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3918 Release google-cloud-os_login 0.3.1
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3917 Release google-cloud-monitoring 0.31.0
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3916 Release google-cloud-logging 1.7.0
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3915 Release google-cloud-language 0.33.1
  google-cloud-language/CHANGELOG.md
  google-cloud-language/lib/google/cloud/language/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3914 Release google-cloud-kms 1.2.1
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3913 Release google-cloud-firestore 1.1.0
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3912 Release google-cloud-error_reporting 0.32.0
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3911 Release google-cloud-env 1.2.1
  google-cloud-env/CHANGELOG.md
  google-cloud-env/lib/google/cloud/env/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3910 Release google-cloud-dns 0.30.2
  google-cloud-dns/CHANGELOG.md
  google-cloud-dns/lib/google/cloud/dns/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3909 Release google-cloud-dlp 0.11.1
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3908 Release google-cloud-dialogflow 0.6.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3907 Release google-cloud-debugger 0.34.0
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3906 Release google-cloud-datastore 1.6.0
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3905 Release google-cloud-container_analysis 0.3.0
  google-cloud-container_analysis/CHANGELOG.md
  google-cloud-container_analysis/lib/google/cloud/container_analysis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3904 Release google-cloud-bigquery-data_transfer 0.3.0
  google-cloud-bigquery-data_transfer/CHANGELOG.md
Labels: autorelease: pending, cla: yes, type: process

#3878 Release google-cloud-dataproc 0.5.1
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3877 Release google-cloud-core 1.3.1
  google-cloud-core/CHANGELOG.md
  google-cloud-core/lib/google/cloud/core/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3875 Release google-cloud-container 0.5.1
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3874 Release google-cloud-bigtable 0.6.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3872 Release google-cloud-bigquery 1.14.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3871 Release google-cloud-automl 0.2.0
  google-cloud-automl/CHANGELOG.md
  google-cloud-automl/lib/google/cloud/automl/version.rb
Labels: autorelease: pending, cla: no, type: process

#3870 Release google-cloud-asset 0.3.1
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3938 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes, do not merge

#3943 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/lib/google/spanner/v1/spanner_pb.rb
  google-cloud-spanner/lib/google/spanner/v1/spanner_services_pb.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/v1/spanner_client_test.rb
Labels: cla: yes

#3928 Release google-cloud-talent 0.5.0
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3948 Release google-cloud-pubsub 0.39.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3926 Release google-cloud-spanner 1.10.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes, type: process

#3947 Release google-cloud 0.61.0
  google-cloud/CHANGELOG.md
  google-cloud/lib/google/cloud/version.rb
Labels: autorelease: pending, cla: yes

#3946 Release gcloud 0.23.4
  gcloud/CHANGELOG.md
  gcloud/lib/gcloud/version.rb
Labels: autorelease: pending, cla: yes

#3950 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes
