Repository googleapis/google-cloud-ruby, pull requests merged in 2019-06, with the labels that each got.

#3430 feat(firestore): add commit_response to Client#transaction
  google-cloud-firestore/acceptance/firestore/transaction_test.rb
  google-cloud-firestore/lib/google/cloud/firestore/client.rb
  google-cloud-firestore/lib/google/cloud/firestore/transaction.rb
  google-cloud-firestore/test/google/cloud/firestore/client/transaction_test.rb
Labels: api: firestore, cla: yes

#3424 Release google-cloud-env 1.1.0
  google-cloud-env/CHANGELOG.md
  google-cloud-env/lib/google/cloud/env/version.rb
Labels: autorelease: pending, cla: yes

#3435 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3440 Make Pub/Sub tests more resilient
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/acknowledge_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/modify_ack_deadline_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/nack_test.rb
Labels: api: pubsub, cla: yes, testing

#3443 Disable gRPC Service Config
  google-cloud-bigtable/lib/google/cloud/bigtable/service.rb
  google-cloud-datastore/lib/google/cloud/datastore/service.rb
  google-cloud-firestore/lib/google/cloud/firestore/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
Labels: api: bigtable, api: datastore, api: firestore, api: pubsub, cla: yes

#3438 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_pb.rb
  google-cloud-video_intelligence/synth.metadata
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client_test.rb
Labels: cla: yes

#3433 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/synth.metadata
  google-cloud-language/test/google/cloud/language/v1/language_service_client_test.rb
  google-cloud-language/test/google/cloud/language/v1beta2/language_service_client_test.rb
Labels: cla: yes

#3434 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/synth.metadata
  google-cloud-os_login/test/google/cloud/os_login/v1/os_login_service_client_test.rb
  google-cloud-os_login/test/google/cloud/os_login/v1beta/os_login_service_client_test.rb
Labels: cla: yes

#3439 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/synth.metadata
  google-cloud-webrisk/test/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client_test.rb
Labels: cla: yes

#3441 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3436 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_services_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_services_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/cloud/redis/v1beta1/cloud_redis.rb
  google-cloud-redis/synth.metadata
  google-cloud-redis/test/google/cloud/redis/v1/cloud_redis_client_test.rb
  google-cloud-redis/test/google/cloud/redis/v1beta1/cloud_redis_client_test.rb
Labels: cla: yes

#3445 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/storage_pb.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3437 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/synth.metadata
  google-cloud-text_to_speech/test/google/cloud/text_to_speech/v1/text_to_speech_client_test.rb
  google-cloud-text_to_speech/test/google/cloud/text_to_speech/v1beta1/text_to_speech_client_test.rb
Labels: cla: yes

#3447 feat(firestore): add CollectionReference#list_documents
  google-cloud-firestore/acceptance/firestore/collection_test.rb
  google-cloud-firestore/lib/google/cloud/firestore/client.rb
  google-cloud-firestore/lib/google/cloud/firestore/collection_reference.rb
  google-cloud-firestore/lib/google/cloud/firestore/document_reference.rb
  google-cloud-firestore/lib/google/cloud/firestore/document_reference/list.rb
  google-cloud-firestore/lib/google/cloud/firestore/service.rb
  google-cloud-firestore/support/doctest_helper.rb
  google-cloud-firestore/test/google/cloud/firestore/collection_reference/list_documents_test.rb
Labels: api: firestore, cla: yes

#3448 Remove acceptance pagination and token checks
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
Labels: api: pubsub, cla: yes, testing

#3450 Pub/Sub: Fix bug with chaining bang methods
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/inventory.rb
Labels: api: pubsub, cla: yes, type: bug

#3449 Upgrade Pub/Sub to concurrent-ruby Promises framework
  google-cloud-pubsub/google-cloud-pubsub.gemspec
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/timed_unary_buffer.rb
Labels: api: pubsub, cla: yes, type: cleanup

#3451 Remove messages from inventory after callback
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/inventory_test.rb
Labels: api: pubsub, cla: yes, type: bug

#3444 prepare repo-metadata.json for docuploader
  gcloud/.repo-metadata.json
  google-cloud-asset/.repo-metadata.json
  google-cloud-bigquery-data_transfer/.repo-metadata.json
  google-cloud-bigquery/.repo-metadata.json
  google-cloud-bigtable/.repo-metadata.json
  google-cloud-container/.repo-metadata.json
  google-cloud-core/.repo-metadata.json
  google-cloud-dataproc/.repo-metadata.json
  google-cloud-datastore/.repo-metadata.json
  google-cloud-debugger/.repo-metadata.json
  google-cloud-dialogflow/.repo-metadata.json
  google-cloud-dlp/.repo-metadata.json
  google-cloud-dns/.repo-metadata.json
  google-cloud-env/.repo-metadata.json
  google-cloud-error_reporting/.repo-metadata.json
  google-cloud-firestore/.repo-metadata.json
  google-cloud-irm/.repo-metadata.json
  google-cloud-kms/.repo-metadata.json
  google-cloud-language/.repo-metadata.json
  google-cloud-logging/.repo-metadata.json
  google-cloud-monitoring/.repo-metadata.json
  google-cloud-os_login/.repo-metadata.json
  google-cloud-phishing_protection/.repo-metadata.json
  google-cloud-pubsub/.repo-metadata.json
  google-cloud-recaptcha_enterprise/.repo-metadata.json
  google-cloud-redis/.repo-metadata.json
  google-cloud-resource_manager/.repo-metadata.json
  google-cloud-scheduler/.repo-metadata.json
  google-cloud-security_center/.repo-metadata.json
  google-cloud-spanner/.repo-metadata.json
  google-cloud-speech/.repo-metadata.json
  google-cloud-storage/.repo-metadata.json
  google-cloud-talent/.repo-metadata.json
  google-cloud-tasks/.repo-metadata.json
  google-cloud-text_to_speech/.repo-metadata.json
  google-cloud-trace/.repo-metadata.json
  google-cloud-translate/.repo-metadata.json
  google-cloud-video_intelligence/.repo-metadata.json
  google-cloud-vision/.repo-metadata.json
  google-cloud-webrisk/.repo-metadata.json
  google-cloud/.repo-metadata.json
  stackdriver-core/.repo-metadata.json
  stackdriver/.repo-metadata.json
Labels: cla: yes

#3453 Release google-cloud-bigquery 1.11.2
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes

#3454 Release google-cloud-bigquery-data_transfer 0.2.5
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes

#3455 Release google-cloud-bigtable 0.4.1
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#3456 Release google-cloud-container 0.4.2
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes

#3457 Release google-cloud-dataproc 0.4.0
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes

#3452 Cleanup Subscriber Threading Restart
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
Labels: api: pubsub, cla: yes, type: cleanup

#3459 Release google-cloud-debugger 0.33.5
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#3461 Release google-cloud-dlp 0.10.0
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes

#3462 Release google-cloud-error_reporting 0.31.5
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes

#3463 Release google-cloud-logging 1.6.4
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes, kokoro:force-run

#3458 Release google-cloud-datastore 1.5.3
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes

#3460 Release google-cloud-dialogflow 0.4.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes

#3464 Release google-cloud-kms 1.0.2
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes, kokoro:force-run

#3465 Release google-cloud-language 0.32.2
  google-cloud-language/CHANGELOG.md
  google-cloud-language/lib/google/cloud/language/version.rb
Labels: autorelease: pending, cla: yes

#3466 Release google-cloud-monitoring 0.29.5
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes

#3467 Release google-cloud-os_login 0.2.5
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes

#3468 Release google-cloud-phishing_protection 0.1.1
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes

#3469 Release google-cloud-recaptcha_enterprise 0.1.1
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes

#3470 Release google-cloud-redis 0.4.0
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes

#3471 Release google-cloud-scheduler 1.0.1
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/lib/google/cloud/scheduler/version.rb
Labels: autorelease: pending, cla: yes

#3472 Release google-cloud-security_center 0.2.1
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes

#3473 Release google-cloud-speech 0.35.0
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes

#3474 Release google-cloud-tasks 1.0.1
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes

#3475 Release google-cloud-text_to_speech 0.3.1
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/version.rb
Labels: autorelease: pending, cla: yes

#3476 Release google-cloud-trace 0.34.3
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes

#3477 Release google-cloud-vision 0.33.1
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: autorelease: pending, cla: yes

#3478 Release google-cloud-webrisk 0.1.2
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes

#3480 Release google-cloud 0.60.0
  google-cloud/CHANGELOG.md
  google-cloud/lib/google/cloud/version.rb
Labels: autorelease: pending, cla: yes

#3481 Release google-cloud-firestore 0.26.0
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#3482 Release google-cloud-spanner 1.9.2
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#3486 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/synth.metadata
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client_test.rb
Labels: cla: yes

#3483 Release stackdriver 0.15.4
  stackdriver/CHANGELOG.md
  stackdriver/lib/stackdriver/version.rb
Labels: autorelease: pending, cla: yes

#3487 Release google-cloud-video_intelligence 1.2.0
  google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/version.rb
Labels: autorelease: pending, cla: yes

#3489 Correct Float value conversion
  google-cloud-bigquery/acceptance/bigquery/advanced_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/convert.rb
  google-cloud-bigquery/test/google/cloud/bigquery/convert_test.rb
Labels: api: bigquery, cla: yes, type: bug

#3490 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/credentials.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/resources.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/service.rb
  google-cloud-kms/lib/google/cloud/kms/v1/helpers.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client_config.json
  google-cloud-kms/lib/google/cloud/kms/v1/resources_pb.rb
  google-cloud-kms/lib/google/cloud/kms/v1/service_pb.rb
  google-cloud-kms/lib/google/cloud/kms/v1/service_services_pb.rb
  google-cloud-kms/synth.metadata
  google-cloud-kms/test/google/cloud/kms/v1/helpers_test.rb
  google-cloud-kms/test/google/cloud/kms/v1/key_management_service_client_test.rb
Labels: cla: yes

#3493 Explicitly require run_asset_discovery_response_pb in security_center
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/synth.metadata
  google-cloud-security_center/synth.py
Labels: cla: yes

#3491 Add grafeas-client library
  .kokoro/continuous/linux/grafeas-client.cfg
  .kokoro/continuous/osx/grafeas-client.cfg
  .kokoro/continuous/windows/grafeas-client.cfg
  .kokoro/nightly/linux/grafeas-client.cfg
  .kokoro/nightly/osx/grafeas-client.cfg
  .kokoro/nightly/windows/grafeas-client.cfg
  .kokoro/presubmit/linux/grafeas-client.cfg
  .kokoro/presubmit/osx/grafeas-client.cfg
  .kokoro/presubmit/windows/grafeas-client.cfg
  .kokoro/release/grafeas-client.cfg
  grafeas-client/.gitignore
  grafeas-client/.repo-metadata.json
  grafeas-client/.rubocop.yml
  grafeas-client/.yardopts
  grafeas-client/AUTHENTICATION.md
  grafeas-client/CHANGELOG.md
  grafeas-client/Gemfile
  grafeas-client/LICENSE
  grafeas-client/README.md
  grafeas-client/Rakefile
  grafeas-client/acceptance/grafeas/v1/grafeas_service_smoke_test.rb
  grafeas-client/grafeas-client.gemspec
  grafeas-client/lib/grafeas-client.rb
  grafeas-client/lib/grafeas.rb
  grafeas-client/lib/grafeas/v1.rb
  grafeas-client/lib/grafeas/v1/attestation_pb.rb
  grafeas-client/lib/grafeas/v1/build_pb.rb
  grafeas-client/lib/grafeas/v1/common_pb.rb
  grafeas-client/lib/grafeas/v1/credentials.rb
  grafeas-client/lib/grafeas/v1/cvss_pb.rb
  grafeas-client/lib/grafeas/v1/deployment_pb.rb
  grafeas-client/lib/grafeas/v1/discovery_pb.rb
  grafeas-client/lib/grafeas/v1/doc/google/protobuf/any.rb
  grafeas-client/lib/grafeas/v1/doc/google/protobuf/empty.rb
  grafeas-client/lib/grafeas/v1/doc/google/protobuf/field_mask.rb
  grafeas-client/lib/grafeas/v1/doc/google/protobuf/timestamp.rb
  grafeas-client/lib/grafeas/v1/doc/google/rpc/status.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/attestation.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/build.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/common.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/cvss.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/deployment.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/discovery.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/grafeas.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/image.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/package.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/provenance.rb
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/vulnerability.rb
  grafeas-client/lib/grafeas/v1/grafeas_client.rb
  grafeas-client/lib/grafeas/v1/grafeas_client_config.json
  grafeas-client/lib/grafeas/v1/grafeas_pb.rb
  grafeas-client/lib/grafeas/v1/grafeas_services_pb.rb
  grafeas-client/lib/grafeas/v1/image_pb.rb
  grafeas-client/lib/grafeas/v1/package_pb.rb
  grafeas-client/lib/grafeas/v1/provenance_pb.rb
  grafeas-client/lib/grafeas/v1/vulnerability_pb.rb
  grafeas-client/lib/grafeas/version.rb
  grafeas-client/synth.metadata
  grafeas-client/synth.py
  grafeas-client/test/grafeas/v1/grafeas_client_test.rb
Labels: cla: yes

#3492 Add google-cloud-container_analysis library
  .kokoro/continuous/linux/container_analysis.cfg
  .kokoro/continuous/osx/container_analysis.cfg
  .kokoro/continuous/windows/container_analysis.cfg
  .kokoro/nightly/linux/container_analysis.cfg
  .kokoro/nightly/osx/container_analysis.cfg
  .kokoro/nightly/windows/container_analysis.cfg
  .kokoro/presubmit/linux/container_analysis.cfg
  .kokoro/presubmit/osx/container_analysis.cfg
  .kokoro/presubmit/windows/container_analysis.cfg
  .kokoro/release/container_analysis.cfg
  google-cloud-container_analysis/.gitignore
  google-cloud-container_analysis/.repo-metadata.json
  google-cloud-container_analysis/.rubocop.yml
  google-cloud-container_analysis/.yardopts
  google-cloud-container_analysis/AUTHENTICATION.md
  google-cloud-container_analysis/CHANGELOG.md
  google-cloud-container_analysis/Gemfile
  google-cloud-container_analysis/LICENSE
  google-cloud-container_analysis/README.md
  google-cloud-container_analysis/Rakefile
  google-cloud-container_analysis/google-cloud-container_analysis.gemspec
  google-cloud-container_analysis/lib/google-cloud-container_analysis.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client_config.json
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/credentials.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/policy.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/type/expr.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/version.rb
  google-cloud-container_analysis/lib/google/devtools/containeranalysis/v1/containeranalysis_pb.rb
  google-cloud-container_analysis/lib/google/devtools/containeranalysis/v1/containeranalysis_services_pb.rb
  google-cloud-container_analysis/synth.metadata
  google-cloud-container_analysis/synth.py
  google-cloud-container_analysis/test/google/cloud/container_analysis/v1/container_analysis_client_test.rb
Labels: cla: yes

#3495 test(webrisk): add TargetRubyVersion: 2.2 to .rubocop.yml
  google-cloud-webrisk/.rubocop.yml
Labels: cla: yes

#3496 Fix Security Center acceptance rake task
  google-cloud-security_center/Rakefile
Labels: api: securitycenter, cla: yes, testing, type: cleanup

#3500 Release google-cloud-pubsub 0.37.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: api: pubsub, autorelease: pending, cla: yes

#3497 Release google-cloud-kms 1.1.0
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes

#3499 Fix lifecycle acceptance test
  google-cloud-storage/acceptance/storage/bucket_test.rb
Labels: api: storage, cla: yes, testing, type: cleanup

#3501 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google-cloud-container_analysis.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#3502 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/storage_pb.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3505 Fix build problems
  Gemfile
  google-cloud-container_analysis/.rubocop.yml
  google-cloud-container_analysis/lib/google-cloud-container_analysis.rb
Labels: cla: yes, type: cleanup

#3504 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/lib/google/devtools/containeranalysis/v1/containeranalysis_services_pb.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#3506 Cloud Text-to-Speech: changed mode of File.open
  README.md
Labels: api: texttospeech, cla: yes

#3508 feat(env): Support separate timeout for connecting to the metadata server vs the entire request
  google-cloud-env/lib/google/cloud/env.rb
Labels: cla: yes

#3513 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3511 Release google-cloud-env 1.2.0
  google-cloud-env/CHANGELOG.md
  google-cloud-env/lib/google/cloud/env/version.rb
Labels: autorelease: pending, cla: yes

#3514 feat(container_analysis): Make container_analysis depend on grafeas
  google-cloud-container_analysis/Gemfile
  google-cloud-container_analysis/Rakefile
  google-cloud-container_analysis/acceptance/google/cloud/container_analysis/v1/grafeas_service_smoke_test.rb
  google-cloud-container_analysis/google-cloud-container_analysis.gemspec
  google-cloud-container_analysis/lib/google/cloud/container_analysis.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/credentials.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/policy.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/type/expr.rb
  google-cloud-container_analysis/synth.metadata
  google-cloud-container_analysis/synth.py
  grafeas-client/Rakefile
Labels: cla: yes

#3517 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/postal_address.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3518 Release grafeas-client 0.1.0
  grafeas-client/CHANGELOG.md
Labels: autorelease: pending, cla: yes

#3520 Release google-cloud-container_analysis 0.1.0
  google-cloud-container_analysis/CHANGELOG.md
Labels: autorelease: pending, cla: yes

#3521 fix(pubsub): Fixed race in TimedUnaryBuffer
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/timed_unary_buffer.rb
Labels: cla: yes

#3515 chore: Add container_analysis library to main readme
  README.md
  google-cloud-container_analysis/README.md
  google-cloud-container_analysis/synth.py
Labels: cla: yes

#3524 [CHANGE ME] Re-generated grafeas-client to pick up changes in the API or client library generator.
  grafeas-client/lib/grafeas/v1/doc/grafeas/v1/vulnerability.rb
  grafeas-client/lib/grafeas/v1/vulnerability_pb.rb
  grafeas-client/synth.metadata
Labels: cla: yes

#3526 publish docs on release
  Rakefile
  rakelib/devsite_builder.rb
Labels: cla: yes

#3527 Ensure two blank lines after copyright block in container_analysis
  google-cloud-container_analysis/lib/google/cloud/container_analysis.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/credentials.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/policy.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/type/expr.rb
  google-cloud-container_analysis/synth.metadata
  google-cloud-container_analysis/synth.py
Labels: cla: yes

#3528 add rebuild_all for devsite
  Rakefile
  rakelib/devsite_builder.rb
  rakelib/gem_version_doc.rb
  rakelib/repo_doc_common.rb
  rakelib/repo_metadata.rb
Labels: cla: yes

#3533 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm/v1alpha2.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents_service.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client_config.json
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_pb.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_service_pb.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_service_services_pb.rb
  google-cloud-irm/synth.metadata
  google-cloud-irm/test/google/cloud/irm/v1alpha2/incident_service_client_test.rb
Labels: cla: yes

#3545 Release google-cloud-spanner 1.9.3
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: api: spanner, autorelease: pending, cla: yes

#3546 use distribution name for devsite url
  Rakefile
  rakelib/devsite_builder.rb
  rakelib/gem_version_doc.rb
  rakelib/repo_metadata.rb
Labels: cla: yes

#3542 chore: Make it easier to override the service host in generated libraries
  google-cloud-asset/synth.py
  google-cloud-automl/synth.py
  google-cloud-bigquery-data_transfer/synth.py
  google-cloud-bigtable/google-cloud-bigtable.gemspec
  google-cloud-bigtable/synth.py
  google-cloud-container/synth.py
  google-cloud-container_analysis/synth.py
  google-cloud-dataproc/synth.py
  google-cloud-datastore/google-cloud-datastore.gemspec
  google-cloud-datastore/synth.py
  google-cloud-debugger/google-cloud-debugger.gemspec
  google-cloud-debugger/synth.py
  google-cloud-dialogflow/synth.py
  google-cloud-dlp/synth.py
  google-cloud-error_reporting/google-cloud-error_reporting.gemspec
  google-cloud-error_reporting/synth.py
  google-cloud-firestore/google-cloud-firestore.gemspec
  google-cloud-firestore/synth.py
  google-cloud-irm/synth.py
  google-cloud-kms/synth.py
  google-cloud-language/synth.py
  google-cloud-logging/google-cloud-logging.gemspec
  google-cloud-logging/synth.py
  google-cloud-monitoring/synth.py
  google-cloud-os_login/synth.py
  google-cloud-phishing_protection/synth.py
  google-cloud-pubsub/google-cloud-pubsub.gemspec
  google-cloud-pubsub/synth.py
  google-cloud-recaptcha_enterprise/synth.py
  google-cloud-redis/synth.py
  google-cloud-scheduler/synth.py
  google-cloud-security_center/synth.py
  google-cloud-spanner/google-cloud-spanner.gemspec
  google-cloud-spanner/synth.py
  google-cloud-speech/synth.py
  google-cloud-talent/synth.py
  google-cloud-tasks/synth.py
  google-cloud-text_to_speech/synth.py
  google-cloud-trace/google-cloud-trace.gemspec
  google-cloud-trace/synth.py
  google-cloud-video_intelligence/synth.py
  google-cloud-vision/synth.py
  google-cloud-webrisk/synth.py
  grafeas-client/synth.py
Labels: cla: yes
