Repository googleapis/google-cloud-ruby, pull requests merged in 2019-07, with the labels that each got.

#3548 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/google-cloud-asset.gemspec
  google-cloud-asset/lib/google/cloud/asset.rb
  google-cloud-asset/lib/google/cloud/asset/v1.rb
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3549 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/google-cloud-automl.gemspec
  google-cloud-automl/lib/google/cloud/automl.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/automl_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_client.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes

#3550 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/google-cloud-bigquery-data_transfer.gemspec
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#3551 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3552 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/google-cloud-container.gemspec
  google-cloud-container/lib/google/cloud/container.rb
  google-cloud-container/lib/google/cloud/container/v1.rb
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1beta1.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client.rb
  google-cloud-container/synth.metadata
Labels: cla: yes

#3553 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/google-cloud-container_analysis.gemspec
  google-cloud-container_analysis/lib/google/cloud/container_analysis.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#3554 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/google-cloud-dataproc.gemspec
  google-cloud-dataproc/lib/google/cloud/dataproc.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#3555 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#3556 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/synth.metadata
Labels: cla: yes

#3558 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#3559 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#3563 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3567 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3572 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3557 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/google-cloud-dlp.gemspec
  google-cloud-dlp/lib/google/cloud/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3560 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/google-cloud-irm.gemspec
  google-cloud-irm/lib/google/cloud/irm.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/synth.metadata
Labels: cla: yes

#3561 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/google-cloud-kms.gemspec
  google-cloud-kms/lib/google/cloud/kms.rb
  google-cloud-kms/lib/google/cloud/kms/v1.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#3562 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/google-cloud-language.gemspec
  google-cloud-language/lib/google/cloud/language.rb
  google-cloud-language/lib/google/cloud/language/v1.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1beta2.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client.rb
  google-cloud-language/synth.metadata
Labels: cla: yes

#3564 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/google-cloud-monitoring.gemspec
  google-cloud-monitoring/lib/google/cloud/monitoring.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#3565 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/google-cloud-os_login.gemspec
  google-cloud-os_login/lib/google/cloud/os_login.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client.rb
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#3566 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/google-cloud-phishing_protection.gemspec
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_client.rb
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#3568 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/google-cloud-recaptcha_enterprise.gemspec
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client.rb
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#3569 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/google-cloud-redis.gemspec
  google-cloud-redis/lib/google/cloud/redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/synth.metadata
Labels: cla: yes

#3570 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/google-cloud-scheduler.gemspec
  google-cloud-scheduler/lib/google/cloud/scheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloud_scheduler_client.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3571 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/google-cloud-security_center.gemspec
  google-cloud-security_center/lib/google/cloud/security_center.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#3573 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/google-cloud-speech.gemspec
  google-cloud-speech/lib/google/cloud/speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3574 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/google-cloud-talent.gemspec
  google-cloud-talent/lib/google/cloud/talent.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/resume_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3575 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/google-cloud-tasks.gemspec
  google-cloud-tasks/lib/google/cloud/tasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3576 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/google-cloud-text_to_speech.gemspec
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client.rb
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#3577 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v2.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#3578 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/google-cloud-video_intelligence.gemspec
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#3579 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/google-cloud-vision.gemspec
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/lib/google/cloud/vision/v1.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3580 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/google-cloud-webrisk.gemspec
  google-cloud-webrisk/lib/google/cloud/webrisk.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client.rb
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#3581 [CHANGE ME] Re-generated grafeas-client to pick up changes in the API or client library generator.
  grafeas-client/grafeas-client.gemspec
  grafeas-client/lib/grafeas.rb
  grafeas-client/lib/grafeas/v1.rb
  grafeas-client/lib/grafeas/v1/grafeas_client.rb
  grafeas-client/synth.metadata
Labels: cla: yes

#3503 Add BigQuery Model API
  google-cloud-bigquery/acceptance/bigquery/model_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/convert.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/model.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/model/list.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/standard_sql.rb
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigquery/test/google/cloud/bigquery/convert_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset/model_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset/models_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/columns_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/metrics_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/partial/attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/partial/delete_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/partial/exists_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/partial/update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/reference/attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/reference/delete_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/reference/exists_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/reference/update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/resource/attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/resource/delete_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/resource/exists_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/resource/update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/standard_sql/array_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/standard_sql/struct_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/standard_sql/value_test.rb
  google-cloud-bigquery/test/helper.rb
Labels: :rotating_light:, api: bigquery, cla: yes, type: feature request

#3582 feat(video_intelligence): Use canonical module capitalization for VideoIntelligence type namespace
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/cloud/videointelligence/v1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/cloud/videointelligence/v1beta2/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/cloud/videointelligence/v1p1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/cloud/videointelligence/v1p2beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1beta1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1beta1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1beta2/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1beta2/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1p1beta1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1p1beta1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1p2beta1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1p2beta1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/synth.metadata
  google-cloud-video_intelligence/synth.py
Labels: cla: yes

#3585 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/iam_policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/options.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3588 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/iam/v1/options.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3590 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/options.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/options.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3586 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/options.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#3592 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/options.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/options.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/options.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3589 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/options.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/securitycenter_service_pb.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#3591 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/completion_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/filters_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/resume_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_pb.rb
  google-cloud-talent/synth.metadata
  google-cloud-talent/test/google/cloud/talent/v4beta1/profile_service_client_test.rb
Labels: cla: yes

#3583 feat(container_analysis): Obtain grafeas client from the container_analysis client
  README.md
  google-cloud-container_analysis/README.md
  google-cloud-container_analysis/acceptance/google/cloud/container_analysis/v1/grafeas_service_smoke_test.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/synth.metadata
  google-cloud-container_analysis/synth.py
Labels: cla: yes

#3584 tests(bigtable): add read_rows conformance tests
  google-cloud-bigtable/.rubocop.yml
  google-cloud-bigtable/conformance/v2/proto/google/cloud/conformance/bigtable/v2/tests.proto
  google-cloud-bigtable/conformance/v2/proto/google/cloud/conformance/bigtable/v2/tests_pb.rb
  google-cloud-bigtable/conformance/v2/readrows.json
  google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb
  google-cloud-bigtable/test/google/cloud/bigtable/conformance_test.rb
Labels: api: bigtable, cla: yes

#3597 Refactor conformance test
  google-cloud-bigtable/test/google/cloud/bigtable/conformance_test.rb
Labels: api: bigtable, cla: yes, testing, type: cleanup

#3594 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/resume_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3587 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/iam/v1/options.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#3599 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3600 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/resume_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3598 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/google-cloud-dialogflow.gemspec
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agent_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agent_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/audio_config_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/context_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/context_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/context.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_type_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/webhook_pb.rb
  google-cloud-dialogflow/synth.metadata
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/agents_client_test.rb
Labels: cla: yes

#3603 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/resume_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3602 docs(text_to_speech): Update code example in READMEs and synth.py
  README.md
  google-cloud-text_to_speech/README.md
  google-cloud-text_to_speech/synth.metadata
  google-cloud-text_to_speech/synth.py
Labels: api: texttospeech, cla: yes

#3644 Fix JSON deserialization
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/model/list.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset/model_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset/models_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/partial/attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/partial/exists_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/partial/update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/reference/exists_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/reference/update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/resource/exists_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/resource/update_test.rb
Labels: api: bigquery, cla: yes, testing, type: cleanup

#3636 Release grafeas-client 0.2.0
  grafeas-client/CHANGELOG.md
  grafeas-client/lib/grafeas/version.rb
Labels: autorelease: pending, cla: yes

#3605 Release google-cloud-asset 0.3.0
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes

#3607 Release google-cloud-container 0.5.0
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes

#3608 Release google-cloud-container_analysis 0.2.0
  google-cloud-container_analysis/CHANGELOG.md
  google-cloud-container_analysis/lib/google/cloud/container_analysis/version.rb
Labels: autorelease: pending, cla: yes

#3609 Release google-cloud-dataproc 0.5.0
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes

#3610 Release google-cloud-datastore 1.5.4
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes

#3611 Release google-cloud-debugger 0.33.6
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#3612 Release google-cloud-dialogflow 0.5.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes

#3613 Release google-cloud-dlp 0.11.0
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes

#3614 Release google-cloud-error_reporting 0.31.6
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes

#3615 Release google-cloud-firestore 0.26.1
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#3616 Release google-cloud-kms 1.2.0
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes

#3617 Release google-cloud-language 0.33.0
  google-cloud-language/CHANGELOG.md
  google-cloud-language/lib/google/cloud/language/version.rb
Labels: autorelease: pending, cla: yes

#3618 Release google-cloud-logging 1.6.5
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#3619 Release google-cloud-monitoring 0.30.0
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes

#3620 Release google-cloud-os_login 0.3.0
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes

#3621 Release google-cloud-phishing_protection 0.2.0
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes

#3623 Release google-cloud-recaptcha_enterprise 0.2.0
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes

#3624 Release google-cloud-redis 0.5.0
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes

#3625 Release google-cloud-scheduler 1.1.0
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/lib/google/cloud/scheduler/version.rb
Labels: autorelease: pending, cla: yes

#3626 Release google-cloud-security_center 0.3.0
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes

#3627 Release google-cloud-spanner 1.9.4
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#3628 Release google-cloud-speech 0.36.0
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes

#3630 Release google-cloud-tasks 1.1.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes

#3631 Release google-cloud-text_to_speech 0.4.0
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/version.rb
Labels: autorelease: pending, cla: yes

#3632 Release google-cloud-trace 0.34.4
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes

#3633 Release google-cloud-video_intelligence 1.3.0
  google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/version.rb
Labels: autorelease: pending, cla: yes

#3634 Release google-cloud-vision 0.34.0
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: autorelease: pending, cla: yes

#3635 Release google-cloud-webrisk 0.2.0
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes

#3639 Release google-cloud-bigtable 0.4.2
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#3640 Release google-cloud-pubsub 0.37.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#3645 Release google-cloud-talent 0.4.0
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes

#3650 Release google-cloud-bigquery 1.12.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: api: bigquery, autorelease: pending, cla: yes

#3651 fix(dns): Ensure the DNS library uses a recent underlying client with the correct endpoint
  google-cloud-dns/google-cloud-dns.gemspec
Labels: cla: yes

#3649 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/helpers.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/synth.metadata
  google-cloud-talent/test/google/cloud/talent/v4beta1/helpers_test.rb
Labels: cla: yes

#3648 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3647 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#3646 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#3303 Add Storage::Bucket#location_type
  google-cloud-storage/acceptance/storage/bucket_lock_retention_policy_test.rb
  google-cloud-storage/acceptance/storage/bucket_test.rb
  google-cloud-storage/acceptance/storage/buckets_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/test/google/cloud/storage/bucket_lock_retention_policy_test.rb
  google-cloud-storage/test/google/cloud/storage/bucket_test.rb
  google-cloud-storage/test/google/cloud/storage/bucket_update_test.rb
  google-cloud-storage/test/google/cloud/storage/project_test.rb
  google-cloud-storage/test/helper.rb
Labels: api: storage, cla: yes, do not merge

#3652 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/tables.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/tables_pb.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes

#3653 Release google-cloud-storage 1.19.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: api: storage, autorelease: pending, cla: yes

#3658 Fix for protobuf 3.9.0
  google-cloud-bigtable/lib/google/cloud/bigtable/chunk_processor.rb
  google-cloud-bigtable/test/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance_test.rb
  google-cloud-container/test/google/cloud/container/v1/cluster_manager_client_test.rb
  google-cloud-container/test/google/cloud/container/v1beta1/cluster_manager_client_test.rb
  google-cloud-datastore/lib/google/cloud/datastore/convert.rb
  google-cloud-firestore/lib/google/cloud/firestore/convert.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/partition_query_test.rb
  grafeas-client/test/grafeas/v1/grafeas_client_test.rb
Labels: api: bigtable, api: container, api: datastore, api: firestore, api: spanner, cla: yes, type: cleanup

#3659 Release google-cloud-bigtable 0.4.3
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: api: bigtable, autorelease: pending, cla: yes

#3660 Release google-cloud-datastore 1.5.5
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: api: datastore, autorelease: pending, cla: yes

#3661 Release google-cloud-firestore 0.26.2
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: api: firestore, autorelease: pending, cla: yes

#3668 chore: Update synth files so they don't revert to_h fixes
  google-cloud-bigtable/synth.py
  google-cloud-container/synth.py
  grafeas-client/synth.py
Labels: cla: yes

#3667 Release google-cloud-dns 0.30.1
  google-cloud-dns/CHANGELOG.md
  google-cloud-dns/lib/google/cloud/dns/version.rb
Labels: autorelease: pending, cla: yes

#3669 Release google-cloud-automl 0.1.0
  google-cloud-automl/CHANGELOG.md
Labels: autorelease: pending, cla: yes

#3655 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/audio_config_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3665 test: fix conformance file paths in bigtable, firestore and storage
  google-cloud-bigtable/test/google/cloud/bigtable/conformance_test.rb
  google-cloud-firestore/test/google/cloud/firestore/conformance_test.rb
  google-cloud-storage/test/google/cloud/storage/file/signer_v4_test.rb
Labels: api: bigtable, api: firestore, api: storage, cla: yes, testing

#3666 Release google-cloud-firestore 1.0.0
  README.md
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/README.md
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1.rb
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
  google-cloud-firestore/synth.metadata
  google-cloud-firestore/synth.py
  google-cloud/google-cloud.gemspec
Labels: api: firestore, autorelease: pending, cla: yes

#3673 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/synth.metadata
  google-cloud-bigtable/test/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client_test.rb
Labels: cla: yes

#3674 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/synth.metadata
  google-cloud-container/test/google/cloud/container/v1/cluster_manager_client_test.rb
  google-cloud-container/test/google/cloud/container/v1beta1/cluster_manager_client_test.rb
Labels: cla: yes

#3675 [CHANGE ME] Re-generated grafeas-client to pick up changes in the API or client library generator.
  grafeas-client/synth.metadata
  grafeas-client/test/grafeas/v1/grafeas_client_test.rb
Labels: cla: yes

#3678 Use ThreadPoolExecutor instead of CachedThreadPool
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
Labels: api: pubsub, cla: yes

#3683 Reduce thread allocations
  google-cloud-bigquery/lib/google/cloud/bigquery/table/async_inserter.rb
  google-cloud-spanner/lib/google/cloud/spanner/pool.rb
Labels: api: bigquery, api: spanner, cla: yes

#3682 Fix max threads in thread pools
  google-cloud-debugger/lib/google/cloud/debugger/transmitter.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/async_error_reporter.rb
  google-cloud-logging/lib/google/cloud/logging/async_writer.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/timed_unary_buffer.rb
  google-cloud-trace/lib/google/cloud/trace/async_reporter.rb
Labels: api: clouddebugger, api: clouderrorreporting, api: cloudtrace, api: logging, api: pubsub, cla: yes

#3687 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/securitycenter_service.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#3688 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/filters_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client_config.json
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3691 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client_config.json
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client_config.json
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client_config.json
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3690 check for broken links during post build
  .kokoro/build.sh
  .kokoro/continuous/linux/common.cfg
  .kokoro/continuous/linux/post.cfg
  .kokoro/docker/autosynth/Dockerfile
  .kokoro/docker/multi/Dockerfile
  .kokoro/docker/release/Dockerfile
  .kokoro/nightly/linux/common.cfg
  .kokoro/presubmit/linux/common.cfg
  .kokoro/release/common.cfg
  .kokoro/templates/autosynth.Dockerfile.erb
  .kokoro/templates/multi.Dockerfile.erb
  .kokoro/templates/post.cfg.erb
  .kokoro/templates/release.Dockerfile.erb
  Rakefile
Labels: cla: yes, do not merge

#3686 Allow persistence_regions to be set
  google-cloud-pubsub/lib/google/cloud/pubsub/project.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/project_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/update_test.rb
Labels: api: pubsub, cla: yes

#3702 fix syntax error
  js/jsondoc-forwarder-init-0.1.0.js
Labels: cla: yes

#3697 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset.rb
  google-cloud-asset/lib/google/cloud/asset/v1.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3698 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes

#3699 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#3700 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3707 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3706 fix kokoro:post for root users
  Rakefile
Labels: cla: yes

#3708 Add Table#require_partition_filter
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_update_test.rb
  google-cloud-bigquery/test/helper.rb
Labels: api: bigquery, cla: yes

#3709 docs(bigtable): Fix timestamp param documentation
  google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/row_filter_test.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/chain_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/interleave_filter.rb
  google-cloud-bigtable/test/google/cloud/bigtable/mutation_entry_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/row_filter_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/mutate_rows_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/read_modify_write_row_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/read_rows_test.rb
  google-cloud-bigtable/test/helper.rb
Labels: api: bigtable, cla: yes, type: docs

#3710 feat(pubsub): Service endpoint can be overridden from config
  google-cloud-pubsub/lib/google-cloud-pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub.rb
  google-cloud-pubsub/test/google/cloud/pubsub_test.rb
Labels: cla: yes

#3694 feat(bigtable): Accept nil gc_rule arguments for column_family create/update
  google-cloud-bigtable/acceptance/bigtable/column_family_test.rb
  google-cloud-bigtable/acceptance/bigtable/table_test.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/column_family_map.rb
  google-cloud-bigtable/test/google/cloud/bigtable/column_family/modifications_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/modify_column_families_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/column_family_map_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/modify_column_families_test.rb
Labels: api: bigtable, cla: yes

#3712 List jobs using min and max created_at
  google-cloud-bigquery/lib/google/cloud/bigquery/job/list.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/project.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project/jobs_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_test.rb
Labels: api: bigquery, cla: yes

#3713 Release google-cloud-bigquery 1.13.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes

#3714 Release google-cloud-spanner 1.9.5
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#3716 Release google-cloud-debugger 0.33.7
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#3717 Release google-cloud-error_reporting 0.31.7
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes

#3718 Release google-cloud-logging 1.6.6
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#3719 Release google-cloud-trace 0.34.5
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes

#3715 Release google-cloud-pubsub 0.38.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#3723 Add endpoint to constructor
  google-cloud-pubsub/lib/google/cloud/pubsub.rb
  google-cloud-pubsub/test/google/cloud/pubsub_test.rb
Labels: api: pubsub, cla: yes
