Repository googleapis/google-cloud-ruby, pull requests merged in 2019-11, with the labels that each got.

#4320 chore: Remove hacks in place for old versions of Ruby
  google-cloud-core/lib/google/cloud.rb
  google-cloud-core/lib/google/cloud/errors.rb
  google-cloud-core/test/google/cloud/errors/error_cause_test.rb
  google-cloud-debugger/lib/google/cloud/debugger/breakpoint/evaluator.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator/class_c_methods_whitelist_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator_test.rb
  google-cloud-debugger/test/google/cloud/debugger/tracer/tracer_scenarios_test.rb
  google-cloud-irm/Gemfile
  google-cloud-kms/Gemfile
Labels: cla: yes, type: cleanup

#4361 feat(bigtable)!: Raise Google::Cloud::Error from Table#mutate_row and similar methods
  google-cloud-bigtable/acceptance/bigtable/table/check_and_mutate_row_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/mutate_row_test.rb
  google-cloud-bigtable/acceptance/bigtable/table/read_modify_write_row_test.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/chunk_processor.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/rows_mutator.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/rows_reader.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/service.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/check_and_mutate_row_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/mutate_row_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/read_modify_write_row_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/read_rows_test.rb
Labels: api: bigtable, cla: yes

#4364 Release google-cloud-bigtable 0.8.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4273 feat(storage): Add support for Bucket#uniform_bucket_level_access
  google-cloud-storage/acceptance/storage/bucket_policy_only_test.rb
  google-cloud-storage/acceptance/storage/bucket_uniform_bucket_level_access_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/google/cloud/storage/bucket_policy_only_test.rb
  google-cloud-storage/test/google/cloud/storage/bucket_uniform_bucket_level_access_test.rb
  google-cloud-storage/test/helper.rb
Labels: api: storage, cla: yes

#4239 Release google-cloud-scheduler 1.2.0
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/lib/google/cloud/scheduler/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4362 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_pb.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4374 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/AUTHENTICATION.md
  google-cloud-automl/lib/google/cloud/automl/v1beta1/classification_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/classification.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/image.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/io.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/tables.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/text.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/image_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/operations_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/tables_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/text_pb.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes

#4375 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/README.md
  google-cloud-vision/acceptance/google/cloud/vision/v1/image_annotator_smoke_test.rb
  google-cloud-vision/acceptance/google/cloud/vision/v1p3beta1/image_annotator_smoke_test.rb
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/lib/google/cloud/vision/v1.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#4367 Release google-cloud-storage 1.23.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: published, cla: yes, type: process

#4366 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/target_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/task_pb.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4221 Release google-cloud-automl 0.4.0
  google-cloud-automl/CHANGELOG.md
  google-cloud-automl/lib/google/cloud/automl/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4326 Fix issue with mismatched dependencies
  google-cloud-translate/google-cloud-translate.gemspec
Labels: api: translation, cla: yes, type: bug

#4378 Add optional query parameter types
  google-cloud-bigquery/acceptance/bigquery/named_params_test.rb
  google-cloud-bigquery/acceptance/bigquery/positional_params_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/convert.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/project.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb
  google-cloud-bigquery/test/google/cloud/bigquery/convert_to_query_param_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_job_named_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_job_positional_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_named_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_positional_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_job_named_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_job_positional_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_named_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_positional_params_test.rb
Labels: api: bigquery, cla: yes, type: feature request

#4380 Add param types helper methods
  google-cloud-bigquery/lib/google/cloud/bigquery/data.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/external.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema/field.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigquery/test/google/cloud/bigquery/data_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/external_csv_source_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/external_json_source_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_reference_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_schema_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/view_attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/view_test.rb
Labels: api: bigquery, cla: yes

#4283 Release google-cloud-pubsub 1.1.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4325 Release google-cloud-talent 0.8.0
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4328 Release google-cloud-dataproc 0.7.1
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4329 Release google-cloud-asset 0.5.1
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4332 Release google-cloud-bigquery-data_transfer 0.4.1
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4333 Release google-cloud-language 0.35.1
  google-cloud-language/CHANGELOG.md
  google-cloud-language/lib/google/cloud/language/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4334 Release google-cloud-container 0.6.1
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4335 Release google-cloud-error_reporting 0.33.1
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4336 Release google-cloud-kms 1.3.1
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4337 Release google-cloud-os_login 0.5.1
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4338 Release google-cloud-dlp 0.12.1
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4357 Release google-cloud-bigquery 1.18.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4354 Release google-cloud-firestore 1.2.1
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4353 Release google-cloud-speech 0.39.1
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4352 Release google-cloud-vision 0.37.1
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4351 Release google-cloud-video_intelligence 2.0.1
  google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4350 Release google-cloud-trace 0.36.1
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4348 Release google-cloud-text_to_speech 0.5.1
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4346 Release google-cloud-recaptcha_enterprise 0.3.1
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4345 Release google-cloud-monitoring 0.33.1
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4344 Release google-cloud-security_center 0.4.1
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4342 Release google-cloud-redis 0.6.1
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4341 Release google-cloud-webrisk 0.4.1
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4340 Release google-cloud-datastore 1.7.1
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4339 Release google-cloud-debugger 0.35.1
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4368 Release grafeas 0.1.1
  grafeas/CHANGELOG.md
  grafeas/lib/grafeas/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4369 Release google-cloud-logging 1.9.1
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4372 Release google-cloud-phishing_protection 0.3.1
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4377 Release google-cloud-tasks 1.3.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4382 Release google-cloud-translate 2.1.0
  google-cloud-translate/CHANGELOG.md
  google-cloud-translate/lib/google/cloud/translate/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4371 Release google-cloud-dialogflow 0.10.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4373 Release stackdriver 0.16.0
  stackdriver/CHANGELOG.md
  stackdriver/lib/stackdriver/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4214 Release google-cloud 0.63.0
  google-cloud/CHANGELOG.md
  google-cloud/lib/google/cloud/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4217 Release gcloud 0.24.0
  gcloud/CHANGELOG.md
  gcloud/lib/gcloud/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4379 Prefix error message with the error name instead of the first line of the backtrace
  google-cloud-error_reporting/lib/google/cloud/error_reporting/error_event.rb
  google-cloud-error_reporting/test/google/cloud/error_reporting/error_event_test.rb
Labels: api: clouderrorreporting, cla: yes

#4147 Update Bucket#post_object
  google-cloud-storage/acceptance/storage/bucket_post_object_test.rb
  google-cloud-storage/lib/google/cloud/storage/file/signer_v2.rb
  google-cloud-storage/test/google/cloud/storage/bucket_post_object_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_post_object_test.rb
Labels: api: storage, cla: yes

#4383 Release google-cloud-error_reporting 0.34.0
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4385 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4384 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/audio_config_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_pb.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4275 feat(storage): Add force_copy_metadata to File#copy and #rewrite
  google-cloud-storage/acceptance/storage/file_encryption_test.rb
  google-cloud-storage/acceptance/storage/file_test.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/test/google/cloud/storage/file_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/file_test.rb
Labels: api: storage, cla: yes

#4402 Release google-cloud-storage 1.24.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4399 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/spanner/admin/database/v1/spanner_database_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/lib/google/spanner/admin/database/v1/spanner_database_admin_services_pb.rb
  google-cloud-spanner/lib/google/spanner/v1/spanner_services_pb.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/admin/database/v1/database_admin_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/admin/instance/v1/instance_admin_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/v1/spanner_client_test.rb
Labels: cla: yes

#4403 Release google-cloud-spanner 1.12.1
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#4391 Release google-cloud-talent 0.8.1
  google-cloud-talent/CHANGELOG.md
Labels: autorelease: pending, cla: yes, type: process

#4392 Release google-cloud-dialogflow 0.11.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4404 docs(bigtable): Add sample to README.md
  google-cloud-bigtable/README.md
Labels: api: bigtable, cla: yes, type: docs

#4397 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/storage_pb.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#4400 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/README.md
  google-cloud-speech/acceptance/google/cloud/speech/v1/speech_smoke_test.rb
  google-cloud-speech/acceptance/google/cloud/speech/v1p1beta1/speech_smoke_test.rb
  google-cloud-speech/lib/google/cloud/speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1.rb
  google-cloud-speech/lib/google/cloud/speech/v1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#4409 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/spanner/admin/instance/v1/spanner_instance_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/spanner/admin/instance/v1/spanner_instance_admin_pb.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#4415 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/admin/database/v1/database_admin_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/admin/instance/v1/instance_admin_client_test.rb
Labels: cla: yes

#4408 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client_config.json
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4401 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/policy.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4398 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/policy.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#4396 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/policy.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#4394 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/policy.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4393 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/iam/v1/policy.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#4395 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/README.md
  google-cloud-container/lib/google/cloud/container.rb
  google-cloud-container/lib/google/cloud/container/v1.rb
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client_config.json
  google-cloud-container/lib/google/cloud/container/v1/doc/google/container/v1/cluster_service.rb
  google-cloud-container/lib/google/cloud/container/v1/doc/google/protobuf/timestamp.rb
  google-cloud-container/lib/google/container/v1/cluster_service_pb.rb
  google-cloud-container/lib/google/container/v1/cluster_service_services_pb.rb
  google-cloud-container/synth.metadata
  google-cloud-container/test/google/cloud/container/v1/cluster_manager_client_test.rb
Labels: cla: yes

#4424 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/bigtable/v2/bigtable_pb.rb
  google-cloud-bigtable/lib/google/bigtable/v2/bigtable_services_pb.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/bigtable/v2/bigtable.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4425 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4427 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/spanner/admin/instance/v1/spanner_instance_admin.rb
  google-cloud-spanner/lib/google/spanner/admin/instance/v1/spanner_instance_admin_pb.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#4439 docs(storage): fix YARD warning in CHANGELOG.md
  google-cloud-storage/CHANGELOG.md
Labels: api: storage, cla: yes, type: docs

#4429 docs(bigtable): Fix samples and copy edit all in-line documentation
  google-cloud-bigtable/OVERVIEW.md
  google-cloud-bigtable/README.md
  google-cloud-bigtable/acceptance/bigtable/project_test.rb
  google-cloud-bigtable/lib/google-cloud-bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_range.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/gc_rule.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/cluster_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/longrunning_job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_modify_write_rule.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/routing_policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/chain_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/condition_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/interleave_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/simple_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/rows_reader.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/sample_row_key.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/cluster_state.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/value_range.rb
  google-cloud-bigtable/support/doctest_helper.rb
Labels: api: bigtable, cla: yes, testing, type: docs

#4406 Release google-cloud-talent 0.8.1
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4410 Release google-cloud-speech 0.40.0
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4416 Release google-cloud-container_analysis 0.4.2
  google-cloud-container_analysis/CHANGELOG.md
  google-cloud-container_analysis/lib/google/cloud/container_analysis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4417 Release google-cloud-asset 0.5.2
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4418 Release google-cloud-container 0.7.0
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4419 Release google-cloud-tasks 1.3.1
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4420 Release google-cloud-security_center 0.4.2
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4421 Release google-cloud-pubsub 1.1.2
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4435 Release google-cloud-dialogflow 0.11.1
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4432 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/tables.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/operations_pb.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes

#4433 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/devtools/cloudtrace/v1/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client_config.json
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/tracing.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v1/trace_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v1/trace_services_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v2/trace_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v2/tracing_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v2/tracing_services_pb.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#4441 import keys during osx builds
  .kokoro/osx.sh
Labels: cla: yes, do not merge

#4445 docs(bigtable): Add OVERVIEW guide with samples
  google-cloud-bigtable/OVERVIEW.md
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb
Labels: api: bigtable, cla: yes, type: docs

#4448 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client_config.json
  google-cloud-speech/synth.metadata
Labels: cla: yes

#4449 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/postal_address.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4450 Fix ServiceMonitoringService generated code
  google-cloud-monitoring/lib/google/monitoring/v3/service_service_services_pb.rb
  google-cloud-monitoring/synth.py
Labels: api: monitoring, cla: yes, type: cleanup

#4456 chore(spanner): Use legacy artman config for spanner
  google-cloud-spanner/synth.py
Labels: api: spanner, cla: yes

#4458 Add LRO RPCs to AutoML client
  google-cloud-automl/lib/google/cloud/automl/v1beta1/automl_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/automl_client_helpers.rb
  google-cloud-automl/synth.py
Labels: api: automl, cla: yes, type: feature request

#4457 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/admin/database/v1/database_admin_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/admin/instance/v1/instance_admin_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/v1/spanner_client_test.rb
Labels: cla: yes

#4443 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/bigtable/admin/v2/bigtable_table_admin_services_pb.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes
