Repository googleapis/google-cloud-ruby, pull requests merged in 2019-03, with the labels that each got.

#2969 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/datatransfer_services_pb.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#2970 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/jobs_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_templates_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/clusters_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/jobs_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_templates_services_pb.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#2971 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/common.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/common.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/lib/google/firestore/v1/firestore_services_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/firestore_services_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#2972 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/lib/google/cloud/language/v1/doc/google/cloud/language/v1/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_services_pb.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/doc/google/cloud/language/v1beta2/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_services_pb.rb
  google-cloud-language/synth.metadata
Labels: cla: yes

#2973 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_services_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#2974 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/task.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#2975 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/cloud/videointelligence/v1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/cloud/videointelligence/v1beta2/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/cloud/videointelligence/v1p1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/cloud/videointelligence/v1p2beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#2976 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/lib/google/cloud/vision/v1.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/text_annotation.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_service_services_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/text_annotation.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_service_services_pb.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#2962 Fetch credentials for magic github proxy
  .kokoro/release/common.cfg
Labels: cla: yes

#2984 Debugger/fix acceptance checks
  google-cloud-debugger/acceptance/debugger/debugger_test.rb
  google-cloud-debugger/acceptance/debugger_helper.rb
Labels: api: clouddebugger, cla: yes, testing

#2985 Protobuf 3.7 redux
  google-cloud-error_reporting/test/google/cloud/error_reporting/error_event_test.rb
  google-cloud-error_reporting/test/helper.rb
  google-cloud-firestore/Gemfile
  google-cloud-firestore/test/google/cloud/firestore/commit_response_test.rb
  google-cloud-logging/support/doctest_helper.rb
  google-cloud-logging/test/google/cloud/logging/entry/http_request_test.rb
  google-cloud-logging/test/google/cloud/logging/entry/operation_test.rb
  google-cloud-logging/test/google/cloud/logging/entry/severity_test.rb
  google-cloud-logging/test/google/cloud/logging/entry_test.rb
  google-cloud-logging/test/google/cloud/logging/metric_test.rb
  google-cloud-logging/test/google/cloud/logging/project/list_entries_test.rb
  google-cloud-logging/test/google/cloud/logging/project/list_logs_test.rb
  google-cloud-logging/test/google/cloud/logging/project/metrics_test.rb
  google-cloud-logging/test/google/cloud/logging/project/resource_descriptors_test.rb
  google-cloud-logging/test/google/cloud/logging/project/sinks_test.rb
  google-cloud-logging/test/google/cloud/logging/resource_descriptor_test.rb
  google-cloud-logging/test/google/cloud/logging/resource_test.rb
  google-cloud-logging/test/google/cloud/logging/sink_test.rb
  google-cloud-logging/test/helper.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/async_publisher_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/message/attributes_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/message_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/project_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/received_message_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/snapshot_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/acknowledge_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/error_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/modify_ack_deadline_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/nack_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/restart_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/acknowledge_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/attrs_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/delete_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/exists_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/lazy_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/listen_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/modify_ack_deadline_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/name_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/policy_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/pull_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/pull_wait_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/seek_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/update_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/autocreate_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/exists_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/lazy_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/name_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/policy_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/publish_async_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/publish_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/subscribe_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/subscription_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/subscriptions_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/update_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: cla: yes

#2987 Add readme sample and smoke test for kms
  google-cloud-kms/README.md
  google-cloud-kms/Rakefile
  google-cloud-kms/acceptance/google/cloud/kms/v1/smoke_test.rb
  google-cloud-kms/synth.metadata
  google-cloud-kms/synth.py
Labels: cla: yes

#2988 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloudscheduler_services_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/credentials.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/cloud/scheduler/v1beta1/cloudscheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/cloud/scheduler/v1beta1/job.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/cloud/scheduler/v1beta1/target.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/any.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/duration.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/empty.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/rpc/status.rb
  google-cloud-scheduler/synth.metadata
  google-cloud-scheduler/test/google/cloud/scheduler/v1beta1/cloud_scheduler_client_test.rb
Labels: cla: yes

#2989 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/lib/google/spanner/v1/spanner_pb.rb
  google-cloud-spanner/lib/google/spanner/v1/spanner_services_pb.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/v1/spanner_client_test.rb
Labels: cla: yes

#2990 Spanner Batch DML
  google-cloud-spanner/acceptance/spanner/client/batch_update_test.rb
  google-cloud-spanner/lib/google/cloud/spanner/batch_update.rb
  google-cloud-spanner/lib/google/cloud/spanner/errors.rb
  google-cloud-spanner/lib/google/cloud/spanner/service.rb
  google-cloud-spanner/lib/google/cloud/spanner/session.rb
  google-cloud-spanner/lib/google/cloud/spanner/transaction.rb
  google-cloud-spanner/support/doctest_helper.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/batch_update_test.rb
Labels: api: spanner, cla: yes

#2991 add google-style gem to translate library
  google-cloud-translate/.rubocop.yml
  google-cloud-translate/google-cloud-translate.gemspec
  google-cloud-translate/lib/google-cloud-translate.rb
  google-cloud-translate/lib/google/cloud/translate.rb
  google-cloud-translate/lib/google/cloud/translate/api.rb
  google-cloud-translate/lib/google/cloud/translate/service.rb
Labels: api: translation, cla: yes

#2994 Release google-cloud-spanner 1.9.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#2997 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/README.md
  google-cloud-kms/lib/google/cloud/kms.rb
  google-cloud-kms/lib/google/cloud/kms/v1.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#2995 generate container v1beta1
  google-cloud-container/acceptance/google/cloud/container/v1beta1/cluster_manager_smoke_test.rb
  google-cloud-container/lib/google/cloud/container/v1beta1.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client_config.json
  google-cloud-container/lib/google/cloud/container/v1beta1/credentials.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/doc/google/container/v1beta1/cluster_service.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/doc/google/protobuf/empty.rb
  google-cloud-container/lib/google/container/v1beta1/cluster_service_pb.rb
  google-cloud-container/lib/google/container/v1beta1/cluster_service_services_pb.rb
  google-cloud-container/synth.metadata
  google-cloud-container/synth.py
  google-cloud-container/test/google/cloud/container/v1beta1/cluster_manager_client_test.rb
Labels: api: container, cla: yes

#2998 Release google-cloud-container 0.4.0
  google-cloud-container/CHANGELOG.md
  google-cloud-container/google-cloud-container.gemspec
Labels: autorelease: pending, cla: yes

#3000 fix product documentation link
  google-cloud-talent/README.md
  google-cloud-talent/synth.metadata
  google-cloud-talent/synth.py
Labels: api: talent-solution, cla: yes

#3003 Release google-cloud-talent 0.1.0
  google-cloud-talent/CHANGELOG.md
Labels: api: talent-solution, autorelease: pending, cla: yes

#2993 generate scheduler v1 library
  google-cloud-scheduler/README.md
  google-cloud-scheduler/lib/google/cloud/scheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client_config.json
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloudscheduler_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloudscheduler_services_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/credentials.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/cloudscheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/job.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/target.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/any.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/duration.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/empty.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/field_mask.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/timestamp.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/rpc/status.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/helpers.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/job_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/target_pb.rb
  google-cloud-scheduler/synth.metadata
  google-cloud-scheduler/synth.py
  google-cloud-scheduler/test/google/cloud/scheduler/v1/cloud_scheduler_client_test.rb
  google-cloud-scheduler/test/google/cloud/scheduler/v1/helpers_test.rb
  google-cloud-translate/synth.metadata
Labels: api: cloudscheduler, cla: yes

#3001 Release google-cloud-kms 1.0.0
  README.md
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/google-cloud-kms.gemspec
  google-cloud/google-cloud.gemspec
Labels: api: cloudkms, autorelease: pending, cla: yes

#3004 Talent - add space to changelog and add root README entry
  README.md
  google-cloud-talent/CHANGELOG.md
Labels: cla: yes

#3005 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/type/latlng.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3006 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/type/date.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/type/timeofday.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3007 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/date.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/latlng.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/timeofday.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3008 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/type/color.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/type/latlng.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/type/color.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/type/latlng.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3009 Update conformance binproto
  google-cloud-firestore/conformance/test-suite.binproto
Labels: api: firestore, cla: yes, testing

#3010 Release google-cloud-scheduler 0.2.0
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/google-cloud-scheduler.gemspec
Labels: autorelease: pending, cla: yes

#3011 Release google-cloud-tasks 0.4.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/google-cloud-tasks.gemspec
Labels: api: cloudtasks, autorelease: pending, cla: yes

#3013 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/longrunning/operations.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3014 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/longrunning/operations.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/longrunning/operations.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#3015 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/longrunning/operations.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3017 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/longrunning/operations.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/longrunning/operations.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3019 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_services_pb.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3020 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#3021 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/longrunning/operations.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/longrunning/operations.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3016 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_services_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/longrunning/operations.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-redis/synth.metadata
  google-cloud-redis/test/google/cloud/redis/v1/cloud_redis_client_test.rb
Labels: cla: yes

#3024 Release google-cloud 0.58.0
  google-cloud/CHANGELOG.md
  google-cloud/lib/google/cloud/version.rb
Labels: autorelease: pending, cla: yes

#3027 Remove resource_pb require
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_pb.rb
Labels: api: redis, cla: yes

#3029 Patch debugger unit tests for Ruby 2.6
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/evaluator_test.rb
  google-cloud-debugger/test/google/cloud/debugger/tracer/tracer_scenarios_test.rb
  google-cloud-debugger/test/google/cloud/debugger/tracer/tracer_test_helper.rb
Labels: cla: yes

#3026 Switch to Ruby 2.5.4
  .kokoro/build.sh
  .kokoro/docker/ruby-multi/Dockerfile
  .kokoro/docker/ruby-release/Dockerfile
Labels: cla: yes

#3030 Remove decode_json from debugger tests
  google-cloud-debugger/acceptance/debugger_helper.rb
  google-cloud-debugger/integration/debugger_helper.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/source_location_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/stack_frame_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/status_message_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/variable_table_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/variable_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint_test.rb
  google-cloud-debugger/test/google/cloud/debugger/logpoint_test.rb
  google-cloud-debugger/test/google/cloud/debugger/snappoint_test.rb
  google-cloud-debugger/test/google/cloud/debugger/transmitter_test.rb
  google-cloud-debugger/test/helper.rb
Labels: api: clouddebugger, cla: yes, testing

#3032 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/write.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#3035 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3036 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/README.md
  google-cloud-bigquery-data_transfer/acceptance/google/cloud/bigquery/data_transfer/v1/data_transfer_service_smoke_test.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#3037 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#3038 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3039 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#3040 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/synth.metadata
Labels: cla: yes

#3041 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#3042 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3043 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/README.md
  google-cloud-monitoring/acceptance/google/cloud/monitoring/v3/metric_service_smoke_test.rb
  google-cloud-monitoring/lib/google/cloud/monitoring.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#3044 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client.rb
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#3045 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/resume_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3046 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#3047 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/README.md
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#3034 add instance aliases for class methods
  google-cloud-tasks/Rakefile
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/helpers.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/helpers.rb
  google-cloud-tasks/synth.metadata
  google-cloud-tasks/synth.py
  google-cloud-tasks/synth/helpers.rb.erb
  google-cloud-tasks/synth/helpers_test.rb.erb
  google-cloud-tasks/test/google/cloud/tasks/v2beta2/helpers_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2beta3/helpers_test.rb
Labels: cla: yes

#3049 Release google-cloud-tasks 0.5.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/google-cloud-tasks.gemspec
Labels: api: cloudtasks, autorelease: pending, cla: yes

#3050 genericize kokoro build scripts so other ruby libs can just copy them
  .kokoro/build.sh
  .kokoro/common.cfg
  .kokoro/continuous/linux/common.cfg
  .kokoro/continuous/osx/common.cfg
  .kokoro/continuous/windows/common.cfg
  .kokoro/nightly/linux/common.cfg
  .kokoro/nightly/osx/common.cfg
  .kokoro/nightly/windows/common.cfg
  .kokoro/osx.sh
  .kokoro/presubmit/linux/common.cfg
  .kokoro/presubmit/osx/common.cfg
  .kokoro/presubmit/windows/common.cfg
  .kokoro/release/common.cfg
  .kokoro/templates/osx.sh.erb
  .kokoro/windows.sh
Labels: cla: yes

#3052 Release google-cloud-asset 0.2.0
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/google-cloud-asset.gemspec
Labels: api: cloudasset, autorelease: pending, cla: yes

#3053 Disable logpoint-related integration test due to logging service issues
  google-cloud-debugger/acceptance/debugger/debugger_test.rb
Labels: cla: yes

#3025 update language docs and add entity types
  google-cloud-language/.yardopts
  google-cloud-language/README.md
  google-cloud-language/google-cloud-language.gemspec
  google-cloud-language/lib/google/cloud/language.rb
  google-cloud-language/lib/google/cloud/language/v1.rb
  google-cloud-language/lib/google/cloud/language/v1/doc/google/cloud/language/v1/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_client_config.json
  google-cloud-language/lib/google/cloud/language/v1/language_service_pb.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_services_pb.rb
  google-cloud-language/lib/google/cloud/language/v1beta2.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client.rb
  google-cloud-language/synth.metadata
  google-cloud-language/synth.py
Labels: :rotating_light:, cla: yes

#3063 generate tasks v2
  google-cloud-tasks/README.md
  google-cloud-tasks/lib/google/cloud/tasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client_config.json
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloudtasks_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/credentials.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/duration.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/empty.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/rpc/status.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/helpers.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/queue_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/target_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/task_pb.rb
  google-cloud-tasks/synth.metadata
  google-cloud-tasks/synth.py
  google-cloud-tasks/test/google/cloud/tasks/v2/cloud_tasks_client_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2/helpers_test.rb
Labels: cla: yes

#3062 Release google-cloud-language 0.32.0
  google-cloud-language/CHANGELOG.md
  google-cloud-language/google-cloud-language.gemspec
Labels: api: language, autorelease: pending, cla: yes

#3083 Release google-cloud-tasks 0.6.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/google-cloud-tasks.gemspec
Labels: api: cloudtasks, autorelease: pending, cla: yes
