Repository googleapis/google-cloud-ruby, pull requests merged in 2019-10, with the labels that each got.

#4065 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise_pb.rb
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#4072 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/policy.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4073 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/policy.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#4074 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/doc/google/cloud/phishingprotection/v1beta1/phishingprotection.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_client.rb
  google-cloud-phishing_protection/lib/google/cloud/phishingprotection/v1beta1/phishingprotection_pb.rb
  google-cloud-phishing_protection/lib/google/cloud/phishingprotection/v1beta1/phishingprotection_services_pb.rb
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#4075 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/policy.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#4076 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/.yardopts
  google-cloud-speech/README.md
  google-cloud-speech/google-cloud-speech.gemspec
  google-cloud-speech/lib/google/cloud/speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1.rb
  google-cloud-speech/lib/google/cloud/speech/v1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1/cloud_speech_services_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client.rb
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client_config.json
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/cloud_speech_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/cloud_speech_services_pb.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client_config.json
  google-cloud-speech/synth.metadata
Labels: cla: yes

#4077 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/policy.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4078 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#4104 Keep renewing lease
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/inventory.rb
Labels: api: pubsub, cla: yes, type: bug

#4111 Fix Subscriber lease timing
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/inventory.rb
Labels: api: pubsub, cla: yes, type: bug

#4063 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/v1/spanner_client_test.rb
Labels: cla: yes, do not merge

#4083 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/README.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/datatransfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/datatransfer_pb.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/transfer_pb.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#4094 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/iam/v1/policy.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#4097 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/README.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/doc/google/cloud/texttospeech/v1/cloud_tts.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client_config.json
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/doc/google/cloud/texttospeech/v1beta1/cloud_tts.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client_config.json
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1/cloud_tts_pb.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1/cloud_tts_services_pb.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1beta1/cloud_tts_pb.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1beta1/cloud_tts_services_pb.rb
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#4106 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/lib/google/cloud/language/v1beta2/doc/google/cloud/language/v1beta2/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_pb.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_services_pb.rb
  google-cloud-language/synth.metadata
Labels: cla: yes

#4108 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/google-cloud-talent.gemspec
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/batch_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/common_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/completion_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/histogram.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/filters_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_pb.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4107 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/log_entry.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_metrics.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/logging/v2/log_entry_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_config_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_config_services_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_metrics_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_metrics_services_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_services_pb.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#4112 Release google-cloud-pubsub 1.0.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4086 Release google-cloud-webrisk 0.3.0
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4105 Release google-cloud-phishing_protection 0.2.2
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4102 Release google-cloud-automl 0.3.0
  google-cloud-automl/CHANGELOG.md
  google-cloud-automl/lib/google/cloud/automl/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4058 Release google-cloud-security_center 0.3.3
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4057 Release google-cloud-tasks 1.1.3
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4034 Release google-cloud-translate 1.4.0
  google-cloud-translate/CHANGELOG.md
  google-cloud-translate/lib/google/cloud/translate/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4016 Release google-cloud-resource_manager 0.32.0
  google-cloud-resource_manager/CHANGELOG.md
  google-cloud-resource_manager/lib/google/cloud/resource_manager/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4048 Release google-cloud-dialogflow 0.7.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4015 Release google-cloud-dns 0.31.0
  google-cloud-dns/CHANGELOG.md
  google-cloud-dns/lib/google/cloud/dns/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4055 Release google-cloud-bigtable 0.6.2
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4096 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/common.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/group_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/monitoring/v3/alert_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/alert_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/alert_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/common_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/dropped_labels_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/group_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/group_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_service_services_pb.rb
  google-cloud-monitoring/synth.metadata
  google-cloud-monitoring/test/google/cloud/monitoring/v3/uptime_check_service_client_test.rb
Labels: cla: yes

#4004 Release grafeas-client 0.3.0
  grafeas-client/CHANGELOG.md
  grafeas-client/lib/grafeas/client/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4040 Update Pool#init to use BatchCreateSessions
  google-cloud-spanner/lib/google/cloud/spanner/client.rb
  google-cloud-spanner/lib/google/cloud/spanner/pool.rb
  google-cloud-spanner/lib/google/cloud/spanner/service.rb
  google-cloud-spanner/support/doctest_helper.rb
  google-cloud-spanner/test/google/cloud/spanner/pool/write_ratio_test.rb
Labels: api: spanner, cla: yes

#4115 chore: Fix tests by updating minitest version constraint
  google-cloud-core/Gemfile
  google-cloud-core/test/google/cloud/errors/wrapped_gax_test.rb
  google-cloud-debugger/Gemfile
  google-cloud-logging/Gemfile
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/synth.metadata
  google-cloud-logging/synth.py
Labels: cla: yes

#4119 chore: Delete renovate.json
  renovate.json
Labels: cla: yes

#4080 Add Dataset default_encryption
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/model.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_reference_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_reference_update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_update_test.rb
Labels: api: bigquery, cla: yes, type: feature request

#4109 Fix Ruby 2.7 compatibility in Cloud::Config#mehtod_missing
  google-cloud-core/lib/google/cloud/config.rb
Labels: cla: yes

#4132 Release google-cloud-bigquery 1.16.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4120 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/autoscaling_policies_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/clusters_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/clusters_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/autoscaling_policies.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/jobs_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/operations_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_templates_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_templates_services_pb.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4121 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/webhook_pb.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4122 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_service_services_pb.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4123 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#4053 docs(bigtable): add doctest coverage and update sample code
  google-cloud-bigtable/.rubocop.yml
  google-cloud-bigtable/Rakefile
  google-cloud-bigtable/lib/google-cloud-bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/gc_rule.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/cluster_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/chain_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/interleave_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/sample_row_key.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/service.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/column_family_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/list.rb
  google-cloud-bigtable/support/doctest_helper.rb
Labels: api: bigtable, cla: yes, type: docs

#4059 Release google-cloud-vision 0.36.0
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4003 Release google-cloud-speech 0.38.0
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4127 Release google-cloud-asset 0.3.3
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4128 Release google-cloud-bigquery-data_transfer 0.3.1
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4129 Release google-cloud-language 0.34.0
  google-cloud-language/CHANGELOG.md
  google-cloud-language/lib/google/cloud/language/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4130 Release google-cloud-monitoring 0.32.0
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4131 Release google-cloud-talent 0.6.0
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4125 chore(container_analysis): Update grafeas-client dependency to 0.3
  google-cloud-container_analysis/google-cloud-container_analysis.gemspec
Labels: cla: yes

#4126 Release google-cloud-logging 1.8.0
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4116 chore: Pin all minitest versions to 5.11.x
  Gemfile
  gcloud/Gemfile
  google-cloud-asset/Gemfile
  google-cloud-automl/Gemfile
  google-cloud-bigquery-data_transfer/Gemfile
  google-cloud-bigquery/Gemfile
  google-cloud-bigtable/Gemfile
  google-cloud-container/Gemfile
  google-cloud-container_analysis/Gemfile
  google-cloud-dataproc/Gemfile
  google-cloud-datastore/Gemfile
  google-cloud-dialogflow/Gemfile
  google-cloud-dlp/Gemfile
  google-cloud-dns/Gemfile
  google-cloud-env/Gemfile
  google-cloud-error_reporting/Gemfile
  google-cloud-firestore/Gemfile
  google-cloud-irm/Gemfile
  google-cloud-kms/Gemfile
  google-cloud-language/Gemfile
  google-cloud-monitoring/Gemfile
  google-cloud-os_login/Gemfile
  google-cloud-phishing_protection/Gemfile
  google-cloud-pubsub/Gemfile
  google-cloud-recaptcha_enterprise/Gemfile
  google-cloud-redis/Gemfile
  google-cloud-resource_manager/Gemfile
  google-cloud-scheduler/Gemfile
  google-cloud-security_center/Gemfile
  google-cloud-spanner/Gemfile
  google-cloud-speech/Gemfile
  google-cloud-storage/Gemfile
  google-cloud-talent/Gemfile
  google-cloud-tasks/Gemfile
  google-cloud-text_to_speech/Gemfile
  google-cloud-trace/Gemfile
  google-cloud-translate/Gemfile
  google-cloud-video_intelligence/Gemfile
  google-cloud-vision/Gemfile
  google-cloud-webrisk/Gemfile
  google-cloud/Gemfile
  grafeas-client/Gemfile
  stackdriver-core/Gemfile
  stackdriver/Gemfile
Labels: cla: yes

#4071 test(spanner): acceptance tests for multi-use #3705
  google-cloud-spanner/acceptance/spanner/client/snapshot_test.rb
Labels: api: spanner, cla: yes

#4153 Release google-cloud-spanner 1.11.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: api: spanner, autorelease: pending, cla: yes

#4154 chore(container_analysis): Ensure container-analysis always depends on updated grafeas
  google-cloud-container_analysis/synth.py
Labels: cla: yes

#4056 Release google-cloud-container_analysis 0.3.2
  google-cloud-container_analysis/CHANGELOG.md
  google-cloud-container_analysis/lib/google/cloud/container_analysis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4145 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client_config.json
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4156 style(bigtable): Update doc comment header style
  google-cloud-bigtable/lib/google-cloud-bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/chunk_processor.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_range.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/convert.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/errors.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/gc_rule.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/cluster_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/longrunning_job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_modify_write_rule.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/chain_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/condition_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/interleave_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/simple_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_range.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/rows_mutator.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/rows_reader.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/sample_row_key.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/service.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/cluster_state.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/column_family_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/value_range.rb
Labels: api: bigtable, cla: yes

#4158 Update inspect strings
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber_test.rb
Labels: api: pubsub, cla: yes, type: cleanup

#4161 feat!(bigtable): Update Table#column_families to return frozen ColumnFamilyMap
  google-cloud-bigtable/acceptance/bigtable/column_family_test.rb
  google-cloud-bigtable/acceptance/bigtable/table_test.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/column_family_map.rb
  google-cloud-bigtable/samples/tableadmin.rb
  google-cloud-bigtable/support/doctest_helper.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance/create_table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance/table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/create_table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/modify_column_families_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/modify_column_families_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table_test.rb
Labels: api: bigtable, cla: yes

#4162 fix(error_reporting): Middleware reuses existing default reporter
  google-cloud-error_reporting/acceptance/error_reporting/error_reporting_test.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/middleware.rb
  google-cloud-error_reporting/test/google/cloud/error_reporting/middleware_test.rb
  google-cloud-error_reporting/test/google/cloud/error_reporting_test.rb
Labels: cla: yes

#4168 chore: fix config builder
  rakelib/kokoro/kokoro_builder.rb
Labels: cla: yes

#4159 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client_config.json
  google-cloud-redis/synth.metadata
  google-cloud-redis/test/google/cloud/redis/v1/cloud_redis_client_test.rb
  google-cloud-redis/test/google/cloud/redis/v1beta1/cloud_redis_client_test.rb
Labels: cla: yes

#4163 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4164 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/.yardopts
  google-cloud-os_login/README.md
  google-cloud-os_login/google-cloud-os_login.gemspec
  google-cloud-os_login/lib/google/cloud/os_login.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/credentials.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/cloud/oslogin/common/common.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/cloud/oslogin/v1/oslogin.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/cloud/oslogin/common/common.rb
  google-cloud-os_login/lib/google/cloud/oslogin/common/common_pb.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1/oslogin_pb.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1/oslogin_services_pb.rb
  google-cloud-os_login/synth.metadata
  google-cloud-os_login/test/google/cloud/os_login/v1/os_login_service_client_test.rb
  google-cloud-os_login/test/google/cloud/os_login/v1beta/os_login_service_client_test.rb
Labels: cla: yes

#4165 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4166 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/doc/google/cloud/webrisk/v1beta1/webrisk.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/webrisk_pb.rb
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#4157 Fix Subscriber staying paused after releasing messages
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
Labels: api: pubsub, cla: yes, type: bug

#4175 Release google-cloud-pubsub 1.0.2
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4169 Release google-cloud-error_reporting 0.32.1
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4170 Remove v1beta1
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/cloud/videointelligence/v1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1beta1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1beta1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/synth.py
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client_test.rb
Labels: api: videointelligence, cla: yes, type: feature request

#4173 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_pb.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#4172 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/query.rb
  google-cloud-firestore/lib/google/firestore/v1/query_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/query_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#4180 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1/assets_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/cloud/asset/v1/asset_service.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#4181 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client_config.json
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client_config.json
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/controller.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/debugger.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/controller_pb.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/controller_services_pb.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/data_pb.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/debugger_pb.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/debugger_services_pb.rb
  google-cloud-debugger/synth.metadata
Labels: cla: yes

#4182 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/common.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_pb.rb
  google-cloud-monitoring/synth.metadata
  google-cloud-monitoring/test/google/cloud/monitoring/v3/uptime_check_service_client_test.rb
Labels: cla: yes

#4183 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloudscheduler_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/cloudscheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/target.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/job_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/target_pb.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4191 Update kokoro configs to support current Ruby versions
  .kokoro/docker/autosynth/Dockerfile
  .kokoro/docker/multi/Dockerfile
  .kokoro/docker/release/Dockerfile
  .kokoro/osx.sh
  .kokoro/templates/autosynth.Dockerfile.erb
  .kokoro/templates/multi.Dockerfile.erb
  .kokoro/templates/osx.sh.erb
  .kokoro/templates/release.Dockerfile.erb
  .kokoro/templates/trampoline.sh.erb
  .kokoro/trampoline.sh
  Rakefile
Labels: cla: yes

#4143 Release google-cloud-core 1.3.2
  google-cloud-core/CHANGELOG.md
  google-cloud-core/lib/google/cloud/core/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4148 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/autoscaling_policies_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/autoscaling_policies_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/clusters_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/clusters_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/autoscaling_policies.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/jobs_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/operations_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_templates_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_templates_services_pb.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4174 Release google-cloud-redis 0.5.2
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4140 Release google-cloud-dialogflow 0.8.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4176 Release google-cloud-webrisk 0.3.1
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4178 Release google-cloud-os_login 0.4.0
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4185 Release google-cloud-talent 0.6.1
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4186 Release google-cloud-asset 0.4.0
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4184 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/README.md
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client_config.json
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_pb.rb
  google-cloud-video_intelligence/synth.metadata
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1/video_intelligence_service_client_test.rb
Labels: cla: yes

#4190 Update Authentication Guide
  google-cloud-automl/AUTHENTICATION.md
  google-cloud-automl/synth.py
  google-cloud-dataproc/AUTHENTICATION.md
  google-cloud-dataproc/synth.py
  google-cloud-dialogflow/AUTHENTICATION.md
  google-cloud-dialogflow/synth.py
  google-cloud-monitoring/AUTHENTICATION.md
  google-cloud-monitoring/synth.py
  google-cloud-talent/AUTHENTICATION.md
  google-cloud-talent/synth.py
  google-cloud-vision/AUTHENTICATION.md
  google-cloud-vision/synth.py
Labels: api: automl, api: dataproc, api: dialogflow, api: monitoring, api: talent-solution, api: vision, cla: yes, type: docs

#4193 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client_config.json
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client_config.json
  google-cloud-debugger/synth.metadata
  google-cloud-debugger/test/google/cloud/debugger/v2/controller2_client_test.rb
  google-cloud-debugger/test/google/cloud/debugger/v2/debugger2_client_test.rb
Labels: cla: yes

#4197 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/clusters_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/clusters_pb.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4195 Release google-cloud-scheduler 1.1.2
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/lib/google/cloud/scheduler/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4196 Release google-cloud-dataproc 0.6.0
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4255 Update code style for Ruby 2.4
  Gemfile
  gcloud/.rubocop.yml
  gcloud/Gemfile
  gcloud/Rakefile
  gcloud/gcloud.gemspec
  google-cloud-core/.rubocop.yml
  google-cloud-core/Rakefile
  google-cloud-core/google-cloud-core.gemspec
  google-cloud-core/lib/google/cloud.rb
  google-cloud-core/lib/google/cloud/config.rb
  google-cloud-core/lib/google/cloud/credentials.rb
  google-cloud-core/lib/google/cloud/errors.rb
  google-cloud-debugger/google-cloud-debugger.gemspec
  google-cloud-env/.rubocop.yml
  google-cloud-env/Rakefile
  google-cloud-env/google-cloud-env.gemspec
  google-cloud-env/lib/google/cloud/env.rb
  google-cloud-error_reporting/google-cloud-error_reporting.gemspec
  google-cloud-error_reporting/test/google/cloud/error_reporting/middleware_test.rb
  google-cloud-logging/google-cloud-logging.gemspec
  google-cloud-trace/google-cloud-trace.gemspec
  google-cloud/.rubocop.yml
  google-cloud/Gemfile
  google-cloud/Rakefile
  google-cloud/google-cloud.gemspec
  stackdriver-core/.rubocop.yml
  stackdriver-core/Rakefile
  stackdriver-core/lib/stackdriver/core/async_actor.rb
  stackdriver-core/lib/stackdriver/core/trace_context.rb
  stackdriver-core/stackdriver-core.gemspec
  stackdriver/.rubocop.yml
  stackdriver/Rakefile
  stackdriver/stackdriver.gemspec
Labels: cla: yes

#4208 fix!(bigtable): Add MutationOperations::Response and Bigtable::Status
  google-cloud-bigtable/acceptance/bigtable/table/mutate_rows_test.rb
  google-cloud-bigtable/acceptance/bigtable/table_test.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/status.rb
  google-cloud-bigtable/support/doctest_helper.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/mutate_rows_test.rb
Labels: api: bigtable, cla: yes

#4201 feat(bigtable): Add Bigtable::RoutingPolicy
  google-cloud-bigtable/acceptance/bigtable/app_profile_test.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/routing_policy.rb
  google-cloud-bigtable/support/doctest_helper.rb
  google-cloud-bigtable/test/google/cloud/bigtable/app_profile/delete_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/app_profile/save_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/app_profile_test.rb
  google-cloud-bigtable/test/helper.rb
Labels: api: bigtable, cla: yes

#4194 Update ColumnFamilyMap, remove modify_column_families and ColumnFamily lifecycle methods
  google-cloud-bigtable/.rubocop.yml
  google-cloud-bigtable/acceptance/bigtable/column_family_test.rb
  google-cloud-bigtable/acceptance/bigtable/table_test.rb
  google-cloud-bigtable/acceptance/bigtable_helper.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/gc_rule.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/column_family_map.rb
  google-cloud-bigtable/support/doctest_helper.rb
  google-cloud-bigtable/test/google/cloud/bigtable/column_family/modifications_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/column_family_map_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/column_family_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/gc_rule_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance/create_table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance/table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/create_table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/modify_column_families_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/column_families_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/column_family_map_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/modify_column_families_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table_test.rb
  google-cloud-bigtable/test/helper.rb
Labels: api: bigtable, cla: yes

#4204 chore: document kokoro process
  KOKORO.md
Labels: cla: yes

#4256 Update Bigtable for new style rules
  google-cloud-bigtable/.rubocop.yml
  google-cloud-bigtable/Rakefile
  google-cloud-bigtable/google-cloud-bigtable.gemspec
  google-cloud-bigtable/lib/google-cloud-bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/app_profile/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/chunk_processor.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_family_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/column_range.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/convert.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/errors.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/gc_rule.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/cluster_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/job.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/list.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/project.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_modify_write_rule.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/routing_policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/chain_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/condition_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/interleave_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/row_filter/simple_filter.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/rows_mutator.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/rows_reader.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/sample_row_key.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/service.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/status.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/cluster_state.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/list.rb
Labels: api: bigtable, cla: yes, type: cleanup

#4262 Fix GcRule#max_age precision
  google-cloud-bigtable/lib/google/cloud/bigtable/gc_rule.rb
  google-cloud-bigtable/test/google/cloud/bigtable/gc_rule_test.rb
Labels: api: bigtable, cla: yes, type: bug

#4263 feat(env): Recognize App Engine Standard and Knative
  google-cloud-env/lib/google/cloud/env.rb
  google-cloud-env/test/google/cloud/env_test.rb
Labels: cla: yes

#4247 Release google-cloud-bigtable 0.7.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4265 chore(grafeas-client): Add .repo-metadata
  grafeas-client/.repo-metadata.json
Labels: cla: yes

#3685 Add Ordering Keys
  google-cloud-pubsub/OVERVIEW.md
  google-cloud-pubsub/acceptance/pubsub/async_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher/batch.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/convert.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/errors.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/message.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/publish_result.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/received_message.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/inventory.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/sequencer.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/conformance/ordered_messages.json
  google-cloud-pubsub/test/google/cloud/pubsub/async_publisher/batch_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/async_publisher/message_ordering_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/async_publisher_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/message_ordering_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/ordered_messages_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/publish_async_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/subscribe_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: api: pubsub, cla: yes

#4266 Update code style for Ruby 2.4
  google-cloud-pubsub/.rubocop.yml
  google-cloud-pubsub/Rakefile
  google-cloud-pubsub/google-cloud-pubsub.gemspec
  google-cloud-pubsub/lib/google-cloud-pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/batch_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/convert.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/project.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/snapshot/list.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/timed_unary_buffer.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription/list.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic/list.rb
Labels: api: pubsub, cla: yes, type: cleanup

#4257 Update BigQuery for new style rules
  google-cloud-bigquery/.rubocop.yml
  google-cloud-bigquery/Rakefile
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-bigquery/lib/google-cloud-bigquery.rb
  google-cloud-bigquery/lib/google/cloud/bigquery.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/convert.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/copy_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/credentials.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/data.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset/access.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset/list.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/external.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/extract_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/insert_response.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/job/list.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/load_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/model.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/model/list.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/project.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/project/list.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema/field.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table/async_inserter.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table/list.rb
Labels: api: bigquery, cla: yes, type: cleanup

#4267 chore: update docs:publish_tag so that the only the gem to be publish…
  rakelib/devsite/devsite_builder.rb
Labels: cla: yes

#4250 Release google-cloud-pubsub 1.1.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: api: pubsub, autorelease: pending, cla: yes, type: process

#4225 Release google-cloud-env 1.3.0
  google-cloud-env/CHANGELOG.md
  google-cloud-env/lib/google/cloud/env/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4219 Release google-cloud-core 1.4.0
  google-cloud-core/CHANGELOG.md
  google-cloud-core/lib/google/cloud/core/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4274 chore: Set bump-minor-pre-major behavior for release-please
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#4261 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client_config.json
  google-cloud-os_login/synth.metadata
  google-cloud-os_login/test/google/cloud/os_login/v1/os_login_service_client_test.rb
Labels: cla: yes

#4268 Release stackdriver-core 1.4.0
  stackdriver-core/CHANGELOG.md
  stackdriver-core/lib/stackdriver/core/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4276 Release grafeas 0.1.0
  grafeas/CHANGELOG.md
Labels: autorelease: pending, cla: yes, type: process

#4277 docs: Update the list of GCP environments for automatic authentication
  AUTHENTICATION.md
  README.md
  gcloud/AUTHENTICATION.md
  google-cloud-bigquery/AUTHENTICATION.md
  google-cloud-bigquery/OVERVIEW.md
  google-cloud-bigquery/README.md
  google-cloud-bigtable/AUTHENTICATION.md
  google-cloud-bigtable/README.md
  google-cloud-core/AUTHENTICATION.md
  google-cloud-datastore/AUTHENTICATION.md
  google-cloud-datastore/OVERVIEW.md
  google-cloud-datastore/README.md
  google-cloud-debugger/AUTHENTICATION.md
  google-cloud-dns/AUTHENTICATION.md
  google-cloud-dns/OVERVIEW.md
  google-cloud-dns/README.md
  google-cloud-error_reporting/AUTHENTICATION.md
  google-cloud-error_reporting/OVERVIEW.md
  google-cloud-firestore/AUTHENTICATION.md
  google-cloud-firestore/OVERVIEW.md
  google-cloud-logging/AUTHENTICATION.md
  google-cloud-logging/OVERVIEW.md
  google-cloud-logging/README.md
  google-cloud-pubsub/AUTHENTICATION.md
  google-cloud-pubsub/OVERVIEW.md
  google-cloud-pubsub/README.md
  google-cloud-resource_manager/AUTHENTICATION.md
  google-cloud-resource_manager/OVERVIEW.md
  google-cloud-spanner/AUTHENTICATION.md
  google-cloud-spanner/OVERVIEW.md
  google-cloud-spanner/README.md
  google-cloud-storage/AUTHENTICATION.md
  google-cloud-storage/OVERVIEW.md
  google-cloud-storage/README.md
  google-cloud-trace/AUTHENTICATION.md
  google-cloud-translate/AUTHENTICATION.md
  google-cloud/AUTHENTICATION.md
Labels: cla: yes, type: docs

#4258 Add Translate V3 client
  google-cloud-translate/.gitignore
  google-cloud-translate/.rubocop.yml
  google-cloud-translate/AUTHENTICATION.md
  google-cloud-translate/LICENSE
  google-cloud-translate/OVERVIEW.md
  google-cloud-translate/Rakefile
  google-cloud-translate/acceptance/translate/translate_test.rb
  google-cloud-translate/acceptance/translate_helper.rb
  google-cloud-translate/google-cloud-translate.gemspec
  google-cloud-translate/lib/google-cloud-translate.rb
  google-cloud-translate/lib/google/cloud/translate.rb
  google-cloud-translate/lib/google/cloud/translate/api.rb
  google-cloud-translate/lib/google/cloud/translate/credentials.rb
  google-cloud-translate/lib/google/cloud/translate/detection.rb
  google-cloud-translate/lib/google/cloud/translate/language.rb
  google-cloud-translate/lib/google/cloud/translate/service.rb
  google-cloud-translate/lib/google/cloud/translate/translation.rb
  google-cloud-translate/lib/google/cloud/translate/v2.rb
  google-cloud-translate/lib/google/cloud/translate/v2/api.rb
  google-cloud-translate/lib/google/cloud/translate/v2/credentials.rb
  google-cloud-translate/lib/google/cloud/translate/v2/detection.rb
  google-cloud-translate/lib/google/cloud/translate/v2/language.rb
  google-cloud-translate/lib/google/cloud/translate/v2/service.rb
  google-cloud-translate/lib/google/cloud/translate/v2/translation.rb
  google-cloud-translate/lib/google/cloud/translate/v3.rb
  google-cloud-translate/lib/google/cloud/translate/v3/credentials.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/cloud/translate/v3/translation_service.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/longrunning/operations.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/protobuf/any.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/protobuf/timestamp.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/rpc/status.rb
  google-cloud-translate/lib/google/cloud/translate/v3/translation_service_client.rb
  google-cloud-translate/lib/google/cloud/translate/v3/translation_service_client_config.json
  google-cloud-translate/lib/google/cloud/translate/v3/translation_service_pb.rb
  google-cloud-translate/lib/google/cloud/translate/v3/translation_service_services_pb.rb
  google-cloud-translate/support/doctest_helper.rb
  google-cloud-translate/synth.metadata
  google-cloud-translate/synth.py
  google-cloud-translate/test/google/cloud/translate/v2/detect_test.rb
  google-cloud-translate/test/google/cloud/translate/v2/languages_test.rb
  google-cloud-translate/test/google/cloud/translate/v2/service_test.rb
  google-cloud-translate/test/google/cloud/translate/v2/translate_test.rb
  google-cloud-translate/test/google/cloud/translate/v3/translation_service_client_test.rb
  google-cloud-translate/test/google/cloud/translate_test.rb
  google-cloud-translate/test/helper.rb
Labels: api: translation, cla: yes

#4287 [CHANGE ME] Re-generated google-cloud-translate to pick up changes in the API or client library generator.
  google-cloud-translate/synth.metadata
  google-cloud-translate/test/google/cloud/translate/v3/translation_service_client_test.rb
Labels: cla: yes

#4284 Update default endpoint for google-cloud-storage
  google-cloud-storage/lib/google-cloud-storage.rb
  google-cloud-storage/test/google/cloud/storage_test.rb
Labels: api: storage, cla: yes

#4286 Release google-cloud-translate 2.0.0
  google-cloud-translate/CHANGELOG.md
  google-cloud-translate/google-cloud-translate.gemspec
  google-cloud-translate/lib/google/cloud/translate/version.rb
  google-cloud/google-cloud.gemspec
Labels: autorelease: pending, cla: yes, type: process

#4279 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/cloud/oslogin/v1/oslogin.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/cloud/oslogin/v1beta/oslogin.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1/oslogin_pb.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1/oslogin_services_pb.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1beta/oslogin_pb.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1beta/oslogin_services_pb.rb
  google-cloud-os_login/synth.metadata
  google-cloud-os_login/test/google/cloud/os_login/v1/os_login_service_client_test.rb
  google-cloud-os_login/test/google/cloud/os_login/v1beta/os_login_service_client_test.rb
Labels: cla: yes

#4288 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/synth.metadata
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client_test.rb
Labels: cla: yes

#4278 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/audio_config_pb.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4252 Release google-cloud-storage 1.22.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4292 chore(scheduler): Reinstate project_path helper in synth
  google-cloud-scheduler/synth.py
Labels: api: cloudscheduler, cla: yes

#4293 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/AUTHENTICATION.md
  google-cloud-asset/synth.metadata
Labels: cla: yes

#4294 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/AUTHENTICATION.md
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#4295 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/AUTHENTICATION.md
  google-cloud-container/synth.metadata
Labels: cla: yes

#4296 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/AUTHENTICATION.md
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#4297 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/AUTHENTICATION.md
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4298 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/AUTHENTICATION.md
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4299 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/AUTHENTICATION.md
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#4300 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/AUTHENTICATION.md
  google-cloud-irm/synth.metadata
Labels: cla: yes

#4301 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/AUTHENTICATION.md
  google-cloud-kms/synth.metadata
Labels: cla: yes

#4302 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/AUTHENTICATION.md
  google-cloud-language/synth.metadata
Labels: cla: yes

#4303 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/AUTHENTICATION.md
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4304 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/AUTHENTICATION.md
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#4305 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/AUTHENTICATION.md
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#4306 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/AUTHENTICATION.md
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#4307 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/AUTHENTICATION.md
  google-cloud-redis/synth.metadata
Labels: cla: yes

#4308 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/AUTHENTICATION.md
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#4309 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/AUTHENTICATION.md
  google-cloud-speech/synth.metadata
Labels: cla: yes

#4310 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/AUTHENTICATION.md
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4311 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/AUTHENTICATION.md
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4312 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/AUTHENTICATION.md
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#4313 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/AUTHENTICATION.md
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#4314 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/AUTHENTICATION.md
  google-cloud-vision/synth.metadata
Labels: cla: yes

#4315 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/AUTHENTICATION.md
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#4316 [CHANGE ME] Re-generated grafeas to pick up changes in the API or client library generator.
  grafeas/AUTHENTICATION.md
  grafeas/synth.metadata
Labels: cla: yes

#4209 Release google-cloud-asset 0.5.0
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4210 Release google-cloud-bigquery-data_transfer 0.4.0
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4211 Release google-cloud-container 0.6.0
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4233 Release google-cloud-os_login 0.5.0
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes, do not merge, type: process
