Repository googleapis/google-cloud-ruby, pull requests merged in 2019-04, with the labels that each got.

#3054 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/common.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/common.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/lib/google/firestore/v1/common_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/document_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/firestore_services_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/query_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/write_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/common_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/document_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/firestore_services_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/query_pb.rb
  google-cloud-firestore/lib/google/firestore/v1beta1/write_pb.rb
  google-cloud-firestore/synth.metadata
Labels: :rotating_light:, cla: yes

#3065 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3066 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client.rb
  google-cloud-container/synth.metadata
Labels: cla: yes

#3067 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#3068 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#3069 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/synth.metadata
Labels: cla: yes

#3070 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3071 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3072 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#3073 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/synth.metadata
Labels: cla: yes

#3074 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3075 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#3076 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client.rb
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#3077 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloud_scheduler_client.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3078 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3079 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#3080 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3085 Add Pub/Sub reload
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/reload_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/lazy_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/reload_test.rb
Labels: api: pubsub, cla: yes

#3089 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#3086 Add Subscription#expires_in
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/attrs_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/update_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: api: pubsub, cla: yes

#3055 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: :rotating_light:, cla: yes

#3095 run trampoline from gfile_dir
  .kokoro/trampoline.bat
  .kokoro/trampoline_windows.py
Labels: cla: yes

#3094 generate webrisk v1beta1
  .kokoro/continuous/linux/webrisk.cfg
  .kokoro/continuous/osx/webrisk.cfg
  .kokoro/continuous/windows/webrisk.cfg
  .kokoro/nightly/linux/webrisk.cfg
  .kokoro/nightly/osx/webrisk.cfg
  .kokoro/nightly/windows/webrisk.cfg
  .kokoro/presubmit/linux/webrisk.cfg
  .kokoro/presubmit/osx/webrisk.cfg
  .kokoro/presubmit/windows/webrisk.cfg
  .kokoro/release/webrisk.cfg
  Gemfile
  google-cloud-webrisk/.gitignore
  google-cloud-webrisk/.rubocop.yml
  google-cloud-webrisk/.yardopts
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/Gemfile
  google-cloud-webrisk/LICENSE
  google-cloud-webrisk/README.md
  google-cloud-webrisk/Rakefile
  google-cloud-webrisk/google-cloud-webrisk.gemspec
  google-cloud-webrisk/lib/google/cloud/webrisk.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/credentials.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/doc/google/cloud/webrisk/v1beta1/webrisk.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client_config.json
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/webrisk_pb.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/webrisk_services_pb.rb
  google-cloud-webrisk/synth.metadata
  google-cloud-webrisk/synth.py
  google-cloud-webrisk/test/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client_test.rb
Labels: api: webrisk, cla: yes

#3031 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/google-cloud-redis.gemspec
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_pb.rb
  google-cloud-redis/synth.metadata
Labels: :rotating_light:, cla: yes

#3087 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/README.md
  google-cloud-dialogflow/google-cloud-dialogflow.gemspec
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agent_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agent_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/audio_config_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/context_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/context_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/credentials.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/context.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session_entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_type_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/webhook_pb.rb
  google-cloud-dialogflow/synth.metadata
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/sessions_client_test.rb
Labels: cla: yes

#3088 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/google-cloud-dlp.gemspec
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_services_pb.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/storage_pb.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3093 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3096 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/google-cloud-scheduler.gemspec
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloudscheduler_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloudscheduler_services_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/cloud/scheduler/v1beta1/cloudscheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/cloud/scheduler/v1beta1/job.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/cloud/scheduler/v1beta1/target.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/job_pb.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/target_pb.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3097 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/google-cloud-tasks.gemspec
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloudtasks_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloudtasks_services_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/queue_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/target_pb.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/task_pb.rb
  google-cloud-tasks/synth.metadata
  google-cloud-tasks/test/google/cloud/tasks/v2beta3/cloud_tasks_client_test.rb
Labels: cla: yes

#3092 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/google-cloud-language.gemspec
  google-cloud-language/lib/google/cloud/language/v1/doc/google/cloud/language/v1/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_pb.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_services_pb.rb
  google-cloud-language/synth.metadata
Labels: cla: yes

#3100 checkout pr instead of commit for presubmits
  .kokoro/build.bat
Labels: cla: yes

#3057 Add support for Storage V4 signed URLs
  google-cloud-storage/acceptance/storage/file_test.rb
  google-cloud-storage/acceptance/storage/signed_url_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/file/signer_v2.rb
  google-cloud-storage/lib/google/cloud/storage/file/signer_v4.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/data/signer_v4_test_account.json
  google-cloud-storage/test/data/signer_v4_test_data.json
  google-cloud-storage/test/google/cloud/storage/bucket_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/bucket_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/file/signer_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/file_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/file_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/file_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/file_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/project_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/project_signed_url_v4_test.rb
Labels: :rotating_light:, api: storage, cla: yes

#3098 Release google-cloud-webrisk 0.1.0
  google-cloud-webrisk/CHANGELOG.md
Labels: api: webrisk, autorelease: pending, cla: yes

#3109 Update SignerV2
  google-cloud-storage/acceptance/storage/signed_url_test.rb
  google-cloud-storage/google-cloud-storage.gemspec
  google-cloud-storage/lib/google/cloud/storage/file/signer_v2.rb
  google-cloud-storage/lib/google/cloud/storage/file/signer_v4.rb
  google-cloud-storage/test/google/cloud/storage/bucket_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/file_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/file_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/project_signed_url_v2_test.rb
Labels: api: storage, cla: yes

#3107 Release google-cloud-dlp 0.9.0
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/google-cloud-dlp.gemspec
Labels: api: dlp, autorelease: pending, cla: yes

#3101 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/synth.metadata
  google-cloud-dialogflow/synth.py
Labels: cla: yes

#3102 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/synth.metadata
  google-cloud-dlp/synth.py
Labels: cla: yes

#3103 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/synth.metadata
  google-cloud-language/synth.py
Labels: cla: yes

#3110 Release google-cloud-storage 1.18.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: api: storage, autorelease: pending, cla: yes

#3105 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/synth.metadata
  google-cloud-scheduler/synth.py
Labels: cla: yes

#3106 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/synth.metadata
  google-cloud-tasks/synth.py
Labels: cla: yes

#3112 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#3111 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/common_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/completion_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/histogram.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/filters_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/histogram_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3115 Update signed_url version docs formatting
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
Labels: api: storage, cla: yes, type: docs

#3118 Release google-cloud-scheduler 0.3.0
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/google-cloud-scheduler.gemspec
Labels: api: cloudscheduler, autorelease: pending, cla: yes

#3119 Release google-cloud-tasks 0.7.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/google-cloud-tasks.gemspec
Labels: api: cloudtasks, autorelease: pending, cla: yes

#3091 Add Subscription#push_config
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription/push_config.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/attrs_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/update_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: :rotating_light:, api: pubsub, cla: yes

#3104 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_services_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/cloud/redis/v1beta1/cloud_redis.rb
  google-cloud-redis/synth.metadata
  google-cloud-redis/synth.py
  google-cloud-redis/test/google/cloud/redis/v1beta1/cloud_redis_client_test.rb
Labels: :rotating_light:, cla: yes

#3121 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client_config.json
  google-cloud-kms/synth.metadata
Labels: cla: yes

#3120 check response body after pushing gem
  Rakefile
Labels: cla: yes

#3123 Lower addressable dependency
  google-cloud-storage/google-cloud-storage.gemspec
Labels: cla: yes

#3124 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#3130 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/any.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/field_mask.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/timestamp.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/protobuf/any.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3131 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/any.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/field_mask.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/timestamp.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/any.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/field_mask.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/timestamp.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#3132 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/protobuf/timestamp.rb
  google-cloud-debugger/synth.metadata
Labels: cla: yes

#3133 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/any.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/field_mask.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3135 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#3136 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/protobuf/any.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/protobuf/timestamp.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/any.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#3137 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/protobuf/field_mask.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/protobuf/timestamp.rb
  google-cloud-irm/synth.metadata
Labels: cla: yes

#3138 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/protobuf/field_mask.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/protobuf/timestamp.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#3139 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/any.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/field_mask.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3140 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/any.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/field_mask.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/timestamp.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#3141 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/protobuf/field_mask.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/protobuf/field_mask.rb
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#3142 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/field_mask.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/timestamp.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3143 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/protobuf/any.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/protobuf/field_mask.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/protobuf/timestamp.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/protobuf/any.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-redis/synth.metadata
Labels: cla: yes

#3144 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/any.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/field_mask.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/timestamp.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/any.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3145 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/protobuf/any.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/protobuf/any.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/protobuf/field_mask.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/any.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/timestamp.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3147 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/protobuf/field_mask.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/protobuf/timestamp.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3148 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3150 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#3151 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/any.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/field_mask.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/timestamp.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/any.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/field_mask.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/timestamp.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3128 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/protobuf/any.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/protobuf/timestamp.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/any.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3129 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/any.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/field_mask.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/timestamp.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#3134 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/any.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/field_mask.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/timestamp.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3149 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/protobuf/timestamp.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/any.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/timestamp.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#3146 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/protobuf/any.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/protobuf/any.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3152 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#3126 generate phishing protection library
  Gemfile
  google-cloud-phishing_protection/.gitignore
  google-cloud-phishing_protection/.rubocop.yml
  google-cloud-phishing_protection/.yardopts
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/Gemfile
  google-cloud-phishing_protection/LICENSE
  google-cloud-phishing_protection/README.md
  google-cloud-phishing_protection/Rakefile
  google-cloud-phishing_protection/google-cloud-phishing_protection.gemspec
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/credentials.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/doc/google/cloud/phishingprotection/v1beta1/phishingprotection.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/helpers.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_client.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_client_config.json
  google-cloud-phishing_protection/lib/google/cloud/phishingprotection/v1beta1/phishingprotection_pb.rb
  google-cloud-phishing_protection/lib/google/cloud/phishingprotection/v1beta1/phishingprotection_services_pb.rb
  google-cloud-phishing_protection/synth.metadata
  google-cloud-phishing_protection/synth.py
  google-cloud-phishing_protection/synth/helpers.rb.erb
  google-cloud-phishing_protection/synth/helpers_test.rb.erb
  google-cloud-phishing_protection/test/google/cloud/phishing_protection/v1beta1/helpers_test.rb
  google-cloud-phishing_protection/test/google/cloud/phishing_protection/v1beta1/phishing_protection_client_test.rb
Labels: cla: yes

#3127 generate recaptcha enterprise library
  Gemfile
  google-cloud-recaptcha_enterprise/.gitignore
  google-cloud-recaptcha_enterprise/.rubocop.yml
  google-cloud-recaptcha_enterprise/.yardopts
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/Gemfile
  google-cloud-recaptcha_enterprise/LICENSE
  google-cloud-recaptcha_enterprise/README.md
  google-cloud-recaptcha_enterprise/Rakefile
  google-cloud-recaptcha_enterprise/google-cloud-recaptcha_enterprise.gemspec
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/credentials.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/helpers.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client_config.json
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise_pb.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise_services_pb.rb
  google-cloud-recaptcha_enterprise/synth.metadata
  google-cloud-recaptcha_enterprise/synth.py
  google-cloud-recaptcha_enterprise/synth/helpers.rb.erb
  google-cloud-recaptcha_enterprise/synth/helpers_test.rb.erb
  google-cloud-recaptcha_enterprise/test/google/cloud/recaptcha_enterprise/v1beta1/helpers_test.rb
  google-cloud-recaptcha_enterprise/test/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client_test.rb
Labels: cla: yes

#3153 remove public_suffix pin and bump rake version
  google-cloud-asset/Gemfile
  google-cloud-irm/Gemfile
  google-cloud-kms/Gemfile
  google-cloud-scheduler/Gemfile
  google-cloud-talent/Gemfile
  google-cloud-webrisk/Gemfile
Labels: cla: yes

#3155 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#3168 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client.rb
  google-cloud-vision/synth.metadata
  google-cloud-vision/test/google/cloud/vision/v1/product_search_client_test.rb
Labels: cla: yes

#3156 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3157 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3158 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#3159 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/synth.metadata
Labels: cla: yes

#3160 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#3161 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#3162 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client.rb
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#3163 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client.rb
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#3164 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/synth.metadata
Labels: cla: yes

#3165 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloud_scheduler_client.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3166 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#3167 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3169 Initial codegen for securitycenter
  google-cloud-security_center/.gitignore
  google-cloud-security_center/.rubocop.yml
  google-cloud-security_center/.yardopts
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/Gemfile
  google-cloud-security_center/LICENSE
  google-cloud-security_center/README.md
  google-cloud-security_center/Rakefile
  google-cloud-security_center/google-cloud-security_center.gemspec
  google-cloud-security_center/lib/google/cloud/security_center.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/asset_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/credentials.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/asset.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/finding.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/organization_settings.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/security_marks.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/securitycenter_service.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/source.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/policy.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/longrunning/operations.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/any.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/duration.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/field_mask.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/struct.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/timestamp.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/rpc/status.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/finding_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/helpers.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/organization_settings_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client_config.json
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_marks_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/securitycenter_service_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/securitycenter_service_services_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/source_pb.rb
  google-cloud-security_center/synth.metadata
  google-cloud-security_center/synth.py
  google-cloud-security_center/synth/helpers.rb.erb
  google-cloud-security_center/synth/helpers_test.rb.erb
  google-cloud-security_center/test/google/cloud/security_center/v1/helpers_test.rb
  google-cloud-security_center/test/google/cloud/security_center/v1/security_center_client_test.rb
Labels: cla: yes

#3203 Manually update AUTHENTICATION.md in veneer gems
  google-cloud-bigtable/.repo-metadata.json
  google-cloud-bigtable/AUTHENTICATION.md
  google-cloud-bigtable/synth.py
  google-cloud-datastore/.repo-metadata.json
  google-cloud-datastore/AUTHENTICATION.md
  google-cloud-datastore/synth.py
  google-cloud-debugger/.repo-metadata.json
  google-cloud-debugger/AUTHENTICATION.md
  google-cloud-debugger/synth.py
  google-cloud-error_reporting/.repo-metadata.json
  google-cloud-error_reporting/AUTHENTICATION.md
  google-cloud-error_reporting/synth.py
  google-cloud-firestore/.repo-metadata.json
  google-cloud-firestore/AUTHENTICATION.md
  google-cloud-firestore/synth.py
  google-cloud-logging/.repo-metadata.json
  google-cloud-logging/AUTHENTICATION.md
  google-cloud-logging/synth.py
  google-cloud-pubsub/.repo-metadata.json
  google-cloud-pubsub/AUTHENTICATION.md
  google-cloud-pubsub/synth.py
  google-cloud-spanner/.repo-metadata.json
  google-cloud-spanner/AUTHENTICATION.md
  google-cloud-spanner/synth.py
  google-cloud-trace/.repo-metadata.json
  google-cloud-trace/AUTHENTICATION.md
  google-cloud-trace/synth.py
Labels: cla: yes

#3205 Add kokoro configs for security_center
  .kokoro/continuous/linux/phishing_protection.cfg
  .kokoro/continuous/linux/recaptcha_enterprise.cfg
  .kokoro/continuous/linux/security_center.cfg
  .kokoro/continuous/osx/phishing_protection.cfg
  .kokoro/continuous/osx/recaptcha_enterprise.cfg
  .kokoro/continuous/osx/security_center.cfg
  .kokoro/continuous/windows/phishing_protection.cfg
  .kokoro/continuous/windows/recaptcha_enterprise.cfg
  .kokoro/continuous/windows/security_center.cfg
  .kokoro/nightly/linux/phishing_protection.cfg
  .kokoro/nightly/linux/recaptcha_enterprise.cfg
  .kokoro/nightly/linux/security_center.cfg
  .kokoro/nightly/osx/phishing_protection.cfg
  .kokoro/nightly/osx/recaptcha_enterprise.cfg
  .kokoro/nightly/osx/security_center.cfg
  .kokoro/nightly/windows/phishing_protection.cfg
  .kokoro/nightly/windows/recaptcha_enterprise.cfg
  .kokoro/nightly/windows/security_center.cfg
  .kokoro/presubmit/linux/phishing_protection.cfg
  .kokoro/presubmit/linux/recaptcha_enterprise.cfg
  .kokoro/presubmit/linux/security_center.cfg
  .kokoro/presubmit/osx/phishing_protection.cfg
  .kokoro/presubmit/osx/recaptcha_enterprise.cfg
  .kokoro/presubmit/osx/security_center.cfg
  .kokoro/presubmit/windows/phishing_protection.cfg
  .kokoro/presubmit/windows/recaptcha_enterprise.cfg
  .kokoro/presubmit/windows/security_center.cfg
  .kokoro/release/phishing_protection.cfg
  .kokoro/release/recaptcha_enterprise.cfg
  .kokoro/release/security_center.cfg
Labels: cla: yes

#3202 Update synth.py to add AUTHENTICATION.md to file lists in *.gemspec and .yardopts
  google-cloud-asset/synth.py
  google-cloud-bigquery-data_transfer/synth.py
  google-cloud-container/synth.py
  google-cloud-dataproc/synth.py
  google-cloud-dialogflow/synth.py
  google-cloud-dlp/synth.py
  google-cloud-irm/synth.py
  google-cloud-kms/synth.py
  google-cloud-language/synth.py
  google-cloud-monitoring/synth.py
  google-cloud-os_login/synth.py
  google-cloud-phishing_protection/synth.py
  google-cloud-recaptcha_enterprise/synth.py
  google-cloud-redis/synth.py
  google-cloud-scheduler/synth.py
  google-cloud-speech/synth.py
  google-cloud-talent/synth.py
  google-cloud-tasks/synth.py
  google-cloud-text_to_speech/.repo-metadata.json
  google-cloud-text_to_speech/synth.py
  google-cloud-video_intelligence/synth.py
  google-cloud-vision/synth.py
  google-cloud-webrisk/synth.py
Labels: cla: yes

#3207 Add security_center to toplevel Gemfile and readme
  Gemfile
  README.md
Labels: cla: yes

#3232 Release google-cloud-pubsub 0.35.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#3208 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/.yardopts
  google-cloud-asset/AUTHENTICATION.md
  google-cloud-asset/google-cloud-asset.gemspec
  google-cloud-asset/synth.metadata
Labels: cla: yes

#3209 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/.yardopts
  google-cloud-bigquery-data_transfer/AUTHENTICATION.md
  google-cloud-bigquery-data_transfer/google-cloud-bigquery-data_transfer.gemspec
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#3210 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/.yardopts
  google-cloud-container/AUTHENTICATION.md
  google-cloud-container/google-cloud-container.gemspec
  google-cloud-container/synth.metadata
Labels: cla: yes

#3211 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/.yardopts
  google-cloud-dataproc/AUTHENTICATION.md
  google-cloud-dataproc/google-cloud-dataproc.gemspec
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#3212 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/.yardopts
  google-cloud-dialogflow/AUTHENTICATION.md
  google-cloud-dialogflow/google-cloud-dialogflow.gemspec
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#3213 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/.yardopts
  google-cloud-dlp/AUTHENTICATION.md
  google-cloud-dlp/google-cloud-dlp.gemspec
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#3214 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/.yardopts
  google-cloud-irm/AUTHENTICATION.md
  google-cloud-irm/google-cloud-irm.gemspec
  google-cloud-irm/synth.metadata
Labels: cla: yes

#3215 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/.yardopts
  google-cloud-kms/AUTHENTICATION.md
  google-cloud-kms/google-cloud-kms.gemspec
  google-cloud-kms/synth.metadata
Labels: cla: yes

#3216 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/.yardopts
  google-cloud-language/AUTHENTICATION.md
  google-cloud-language/google-cloud-language.gemspec
  google-cloud-language/synth.metadata
Labels: cla: yes

#3217 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3218 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/.yardopts
  google-cloud-monitoring/AUTHENTICATION.md
  google-cloud-monitoring/google-cloud-monitoring.gemspec
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/distribution.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/monitored_resource.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#3219 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/.yardopts
  google-cloud-os_login/AUTHENTICATION.md
  google-cloud-os_login/google-cloud-os_login.gemspec
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#3220 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/.yardopts
  google-cloud-phishing_protection/AUTHENTICATION.md
  google-cloud-phishing_protection/google-cloud-phishing_protection.gemspec
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#3221 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/.yardopts
  google-cloud-recaptcha_enterprise/AUTHENTICATION.md
  google-cloud-recaptcha_enterprise/google-cloud-recaptcha_enterprise.gemspec
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#3222 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/.yardopts
  google-cloud-redis/AUTHENTICATION.md
  google-cloud-redis/google-cloud-redis.gemspec
  google-cloud-redis/synth.metadata
Labels: cla: yes

#3224 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/.yardopts
  google-cloud-speech/AUTHENTICATION.md
  google-cloud-speech/google-cloud-speech.gemspec
  google-cloud-speech/synth.metadata
Labels: cla: yes

#3225 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/.yardopts
  google-cloud-talent/AUTHENTICATION.md
  google-cloud-talent/google-cloud-talent.gemspec
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/helpers.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/synth.metadata
  google-cloud-talent/test/google/cloud/talent/v4beta1/company_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/helpers_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/job_service_client_test.rb
Labels: cla: yes

#3226 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/.yardopts
  google-cloud-tasks/AUTHENTICATION.md
  google-cloud-tasks/google-cloud-tasks.gemspec
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#3227 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/.yardopts
  google-cloud-text_to_speech/AUTHENTICATION.md
  google-cloud-text_to_speech/google-cloud-text_to_speech.gemspec
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#3228 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/.yardopts
  google-cloud-video_intelligence/AUTHENTICATION.md
  google-cloud-video_intelligence/google-cloud-video_intelligence.gemspec
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#3229 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/.yardopts
  google-cloud-vision/AUTHENTICATION.md
  google-cloud-vision/google-cloud-vision.gemspec
  google-cloud-vision/synth.metadata
Labels: cla: yes

#3230 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/.yardopts
  google-cloud-webrisk/AUTHENTICATION.md
  google-cloud-webrisk/google-cloud-webrisk.gemspec
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#3223 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/.yardopts
  google-cloud-scheduler/AUTHENTICATION.md
  google-cloud-scheduler/google-cloud-scheduler.gemspec
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#3231 Update Storage Bucket Policy Only documentation
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
Labels: api: storage, cla: yes

#3206 Release google-cloud-recaptcha_enterprise 0.1.0
  README.md
  gcloud/.rubocop.yml
  gcloud/Gemfile
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud/.rubocop.yml
  google-cloud/Gemfile
  google-cloud/google-cloud.gemspec
Labels: api: recaptchaenterprise, autorelease: pending, cla: yes

#3204 Release google-cloud-phishing_protection 0.1.0
  README.md
  gcloud/Gemfile
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud/Gemfile
  google-cloud/google-cloud.gemspec
Labels: api: phishingprotection, autorelease: pending, cla: yes

#3234 Add security_center to google-cloud and gcloud gems
  gcloud/Gemfile
  google-cloud/Gemfile
  google-cloud/google-cloud.gemspec
Labels: cla: yes

#3233 Release google-cloud-security_center 0.1.0
  google-cloud-security_center/CHANGELOG.md
Labels: api: securitycenter, autorelease: pending, cla: yes

#3236 Update google-cloud-security_center synth.py
  google-cloud-security_center/.repo-metadata.json
  google-cloud-security_center/synth.py
Labels: api: securitycenter, cla: yes

#3238 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#3239 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#3240 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#3242 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#3241 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/.yardopts
  google-cloud-security_center/AUTHENTICATION.md
  google-cloud-security_center/google-cloud-security_center.gemspec
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#3244 Release google-cloud-asset 0.2.1
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/google-cloud-asset.gemspec
Labels: autorelease: pending, cla: yes

#3246 Release google-cloud-bigquery-data_transfer 0.2.4
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/google-cloud-bigquery-data_transfer.gemspec
Labels: autorelease: pending, cla: yes

#3247 Release google-cloud-bigtable 0.3.1
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#3248 Release google-cloud-container 0.4.1
  google-cloud-container/CHANGELOG.md
  google-cloud-container/google-cloud-container.gemspec
Labels: autorelease: pending, cla: yes

#3249 Release google-cloud-dataproc 0.3.1
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/google-cloud-dataproc.gemspec
Labels: autorelease: pending, cla: yes

#3250 Release google-cloud-datastore 1.5.2
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes

#3251 Release google-cloud-debugger 0.33.4
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#3252 Release google-cloud-dialogflow 0.3.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/google-cloud-dialogflow.gemspec
Labels: autorelease: pending, cla: yes

#3254 Release google-cloud-error_reporting 0.31.4
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes

#3255 Release google-cloud-firestore 0.25.1
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#3256 Release google-cloud-kms 1.0.1
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/google-cloud-kms.gemspec
Labels: autorelease: pending, cla: yes

#3257 Release google-cloud-language 0.32.1
  google-cloud-language/CHANGELOG.md
  google-cloud-language/google-cloud-language.gemspec
Labels: autorelease: pending, cla: yes

#3258 Release google-cloud-logging 1.6.3
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#3262 Release google-cloud-scheduler 0.3.1
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/google-cloud-scheduler.gemspec
Labels: autorelease: pending, cla: yes

#3263 Release google-cloud-security_center 0.1.1
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/google-cloud-security_center.gemspec
Labels: autorelease: pending, cla: yes

#3273 Release google-cloud 0.59.0
  google-cloud/CHANGELOG.md
  google-cloud/lib/google/cloud/version.rb
Labels: autorelease: pending, cla: yes
