Repository googleapis/google-cloud-ruby, pull requests merged in 2020-05, with the labels that each got.

#5804 chore(bigquery-data_transfer): Add samples from ruby-docs-samples
  google-cloud-bigquery-data_transfer/Gemfile
  google-cloud-bigquery-data_transfer/google-cloud-bigquery-data_transfer.gemspec
  google-cloud-bigquery-data_transfer/samples/.rubocop.yml
  google-cloud-bigquery-data_transfer/samples/Gemfile
  google-cloud-bigquery-data_transfer/samples/README.md
  google-cloud-bigquery-data_transfer/samples/Rakefile
  google-cloud-bigquery-data_transfer/samples/acceptance/helper.rb
  google-cloud-bigquery-data_transfer/samples/acceptance/quickstart_test.rb
  google-cloud-bigquery-data_transfer/samples/quickstart.rb
Labels: api: bigquerydatatransfer, cla: yes

#5812 speech: move samples from ruby-docs-samples
  google-cloud-speech/.rubocop.yml
  google-cloud-speech/samples/Gemfile
  google-cloud-speech/samples/README.md
  google-cloud-speech/samples/Rakefile
  google-cloud-speech/samples/acceptance/helper.rb
  google-cloud-speech/samples/acceptance/quickstart_test.rb
  google-cloud-speech/samples/acceptance/speech_samples_test.rb
  google-cloud-speech/samples/quickstart.rb
  google-cloud-speech/samples/resources/Google_Gnome.wav
  google-cloud-speech/samples/resources/brooklyn_bridge.raw
  google-cloud-speech/samples/resources/commercial_mono.wav
  google-cloud-speech/samples/resources/multi.wav
  google-cloud-speech/samples/speech_samples.rb
Labels: cla: yes

#5811 chore(security_center): Move samples from the ruby-docs-samples repo
  google-cloud-security_center/samples/Gemfile
  google-cloud-security_center/samples/Rakefile
  google-cloud-security_center/samples/acceptance/helper.rb
  google-cloud-security_center/samples/acceptance/notification_test.rb
  google-cloud-security_center/samples/notification.rb
Labels: cla: yes

#5816 docs(speech): Fix example streaming call in the migration guide
  google-cloud-speech/MIGRATING.md
Labels: cla: yes

#5843 chore: Re-enable release-please
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#5842 [CHANGE ME] Re-generated google-cloud-web_risk to pick up changes in the API or client library generator.
  google-cloud-web_risk/Gemfile
  google-cloud-web_risk/google-cloud-web_risk.gemspec
  google-cloud-web_risk/synth.metadata
Labels: cla: yes

#5841 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/Gemfile
  google-cloud-vision/google-cloud-vision.gemspec
  google-cloud-vision/synth.metadata
Labels: cla: yes

#5840 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/Gemfile
  google-cloud-video_intelligence/google-cloud-video_intelligence.gemspec
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#5839 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/Gemfile
  google-cloud-talent/google-cloud-talent.gemspec
  google-cloud-talent/synth.metadata
Labels: cla: yes

#5838 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/.rubocop.yml
  google-cloud-speech/Gemfile
  google-cloud-speech/google-cloud-speech.gemspec
  google-cloud-speech/synth.metadata
Labels: cla: yes

#5837 [CHANGE ME] Re-generated google-cloud-service_directory to pick up changes in the API or client library generator.
  google-cloud-service_directory/Gemfile
  google-cloud-service_directory/google-cloud-service_directory.gemspec
  google-cloud-service_directory/synth.metadata
Labels: cla: yes

#5836 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/Gemfile
  google-cloud-security_center/google-cloud-security_center.gemspec
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#5835 [CHANGE ME] Re-generated google-cloud-secret_manager to pick up changes in the API or client library generator.
  google-cloud-secret_manager/Gemfile
  google-cloud-secret_manager/google-cloud-secret_manager.gemspec
  google-cloud-secret_manager/synth.metadata
Labels: cla: yes, context: none

#5834 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/Gemfile
  google-cloud-redis/google-cloud-redis.gemspec
  google-cloud-redis/synth.metadata
Labels: cla: yes

#5833 [CHANGE ME] Re-generated google-cloud-recommender to pick up changes in the API or client library generator.
  google-cloud-recommender/Gemfile
  google-cloud-recommender/google-cloud-recommender.gemspec
  google-cloud-recommender/synth.metadata
Labels: cla: yes

#5832 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/Gemfile
  google-cloud-recaptcha_enterprise/google-cloud-recaptcha_enterprise.gemspec
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#5822 [CHANGE ME] Re-generated google-cloud-bigquery-storage to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage/Gemfile
  google-cloud-bigquery-storage/google-cloud-bigquery-storage.gemspec
  google-cloud-bigquery-storage/synth.metadata
Labels: cla: yes

#5831 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/Gemfile
  google-cloud-language/google-cloud-language.gemspec
  google-cloud-language/synth.metadata
Labels: cla: yes

#5830 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/Gemfile
  google-cloud-kms/google-cloud-kms.gemspec
  google-cloud-kms/synth.metadata
Labels: cla: yes

#5829 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/Gemfile
  google-cloud-dlp/google-cloud-dlp.gemspec
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#5828 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/Gemfile
  google-cloud-dialogflow/google-cloud-dialogflow.gemspec
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5827 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes

#5826 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/Gemfile
  google-cloud-dataproc/google-cloud-dataproc.gemspec
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#5825 [CHANGE ME] Re-generated google-cloud-data_catalog to pick up changes in the API or client library generator.
  google-cloud-data_catalog/Gemfile
  google-cloud-data_catalog/google-cloud-data_catalog.gemspec
  google-cloud-data_catalog/synth.metadata
Labels: cla: yes

#5824 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/Gemfile
  google-cloud-container/google-cloud-container.gemspec
  google-cloud-container/synth.metadata
Labels: cla: yes

#5823 [CHANGE ME] Re-generated google-cloud-billing to pick up changes in the API or client library generator.
  google-cloud-billing/Gemfile
  google-cloud-billing/google-cloud-billing.gemspec
  google-cloud-billing/synth.metadata
Labels: cla: yes

#5821 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/Gemfile
  google-cloud-automl/google-cloud-automl.gemspec
  google-cloud-automl/synth.metadata
Labels: cla: yes

#5820 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/Gemfile
  google-cloud-asset/google-cloud-asset.gemspec
  google-cloud-asset/synth.metadata
Labels: cla: yes, context: none

#5819 [CHANGE ME] Re-generated google-cloud-access_approval to pick up changes in the API or client library generator.
  google-cloud-access_approval/Gemfile
  google-cloud-access_approval/google-cloud-access_approval.gemspec
  google-cloud-access_approval/synth.metadata
Labels: cla: yes

#5815 chore(text-to-speech): Move samples from the ruby-docs-samples repo
  google-cloud-text_to_speech/samples/Gemfile
  google-cloud-text_to_speech/samples/README.md
  google-cloud-text_to_speech/samples/Rakefile
  google-cloud-text_to_speech/samples/acceptance/list_voices_test.rb
  google-cloud-text_to_speech/samples/acceptance/quickstart_test.rb
  google-cloud-text_to_speech/samples/acceptance/synthesize_file_test.rb
  google-cloud-text_to_speech/samples/acceptance/synthesize_text_test.rb
  google-cloud-text_to_speech/samples/list_voices.rb
  google-cloud-text_to_speech/samples/quickstart.rb
  google-cloud-text_to_speech/samples/resources/hello.ssml
  google-cloud-text_to_speech/samples/resources/hello.txt
  google-cloud-text_to_speech/samples/synthesize_file.rb
  google-cloud-text_to_speech/samples/synthesize_text.rb
Labels: cla: yes

#5844 Release google-cloud-access_approval 0.2.1
  google-cloud-access_approval/CHANGELOG.md
  google-cloud-access_approval/lib/google/cloud/access_approval/version.rb
Labels: autorelease: pending, cla: yes

#5818 chore(dlp): Move samples from the ruby-docs-samples repo
  google-cloud-dlp/samples/Gemfile
  google-cloud-dlp/samples/README.md
  google-cloud-dlp/samples/Rakefile
  google-cloud-dlp/samples/acceptance/data/test.txt
  google-cloud-dlp/samples/acceptance/quickstart_test.rb
  google-cloud-dlp/samples/acceptance/sample_test.rb
  google-cloud-dlp/samples/quickstart.rb
  google-cloud-dlp/samples/sample.rb
Labels: cla: yes

#5848 chore: Delay local_docs_test until May 11
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#5900 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/entity.rb
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#5897 Release google-cloud-vision-v1 0.1.5
  google-cloud-vision-v1/CHANGELOG.md
  google-cloud-vision-v1/lib/google/cloud/vision/v1/version.rb
Labels: autorelease: pending, cla: yes

#5896 Release google-cloud-vision-v1p3beta1 0.1.5
  google-cloud-vision-v1p3beta1/CHANGELOG.md
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/version.rb
Labels: autorelease: pending, cla: yes

#5895 Release google-cloud-speech-v1p1beta1 0.2.1
  google-cloud-speech-v1p1beta1/CHANGELOG.md
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5894 Release google-cloud-dialogflow-v2 0.5.1
  google-cloud-dialogflow-v2/CHANGELOG.md
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/version.rb
Labels: autorelease: pending, cla: yes

#5893 Release google-cloud-talent-v4beta1 0.1.1
  google-cloud-talent-v4beta1/CHANGELOG.md
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/version.rb
Labels: autorelease: pending, cla: yes

#5892 Release google-cloud-redis-v1 0.1.1
  google-cloud-redis-v1/CHANGELOG.md
  google-cloud-redis-v1/lib/google/cloud/redis/v1/version.rb
Labels: autorelease: pending, cla: yes

#5891 Release google-cloud-dlp-v2 0.1.1
  google-cloud-dlp-v2/CHANGELOG.md
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/version.rb
Labels: autorelease: pending, cla: yes

#5890 Release google-cloud-video_intelligence-v1p1beta1 0.1.1
  google-cloud-video_intelligence-v1p1beta1/CHANGELOG.md
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5888 Release google-cloud-video_intelligence-v1beta2 0.1.1
  google-cloud-video_intelligence-v1beta2/CHANGELOG.md
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/video_intelligence/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#5885 Release google-cloud-video_intelligence-v1 0.1.1
  google-cloud-video_intelligence-v1/CHANGELOG.md
  google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/version.rb
Labels: autorelease: pending, cla: yes

#5810 add talent samples
  google-cloud-talent/samples/.rubocop.yml
  google-cloud-talent/samples/Gemfile
  google-cloud-talent/samples/Rakefile
  google-cloud-talent/samples/acceptance/helper.rb
  google-cloud-talent/samples/acceptance/talent_test.rb
  google-cloud-talent/samples/autocomplete_job_title.rb
  google-cloud-talent/samples/batch_create_jobs.rb
  google-cloud-talent/samples/batch_delete_job.rb
  google-cloud-talent/samples/batch_update_jobs.rb
  google-cloud-talent/samples/commute_search.rb
  google-cloud-talent/samples/create_client_event.rb
  google-cloud-talent/samples/create_company.rb
  google-cloud-talent/samples/create_job.rb
  google-cloud-talent/samples/create_job_custom_attributes.rb
  google-cloud-talent/samples/create_tenant.rb
  google-cloud-talent/samples/custom_ranking_search.rb
  google-cloud-talent/samples/delete_company.rb
  google-cloud-talent/samples/delete_job.rb
  google-cloud-talent/samples/delete_tenant.rb
  google-cloud-talent/samples/get_company.rb
  google-cloud-talent/samples/get_job.rb
  google-cloud-talent/samples/get_tenant.rb
  google-cloud-talent/samples/histogram_search.rb
  google-cloud-talent/samples/list_companies.rb
  google-cloud-talent/samples/list_jobs.rb
  google-cloud-talent/samples/list_tenants.rb
Labels: cla: yes

#5809 docs(redis): Fix copy-paste error in the migration guide
  google-cloud-redis/MIGRATING.md
Labels: cla: yes

#5813 chore(dialogflow): Move samples from the ruby-docs-samples repo
  google-cloud-dialogflow/samples/Gemfile
  google-cloud-dialogflow/samples/README.md
  google-cloud-dialogflow/samples/Rakefile
  google-cloud-dialogflow/samples/acceptance/context_management_test.rb
  google-cloud-dialogflow/samples/acceptance/detect_intent_audio_test.rb
  google-cloud-dialogflow/samples/acceptance/detect_intent_stream_test.rb
  google-cloud-dialogflow/samples/acceptance/detect_intent_texts_test.rb
  google-cloud-dialogflow/samples/acceptance/entity_management_test.rb
  google-cloud-dialogflow/samples/acceptance/entity_type_management_test.rb
  google-cloud-dialogflow/samples/acceptance/helper.rb
  google-cloud-dialogflow/samples/acceptance/intent_management_test.rb
  google-cloud-dialogflow/samples/acceptance/session_entity_type_management_test.rb
  google-cloud-dialogflow/samples/context_management.rb
  google-cloud-dialogflow/samples/detect_intent_audio.rb
  google-cloud-dialogflow/samples/detect_intent_stream.rb
  google-cloud-dialogflow/samples/detect_intent_texts.rb
  google-cloud-dialogflow/samples/entity_management.rb
  google-cloud-dialogflow/samples/entity_type_management.rb
  google-cloud-dialogflow/samples/intent_management.rb
  google-cloud-dialogflow/samples/resources/230pm.wav
  google-cloud-dialogflow/samples/resources/RoomReservation.zip
  google-cloud-dialogflow/samples/resources/book_a_room.wav
  google-cloud-dialogflow/samples/resources/half_an_hour.wav
  google-cloud-dialogflow/samples/resources/mountain_view.wav
  google-cloud-dialogflow/samples/resources/today.wav
  google-cloud-dialogflow/samples/resources/two_people.wav
  google-cloud-dialogflow/samples/session_entity_type_management.rb
Labels: cla: yes

#5882 Release google-cloud-speech-v1 0.1.4
  google-cloud-speech-v1/CHANGELOG.md
  google-cloud-speech-v1/lib/google/cloud/speech/v1/version.rb
Labels: autorelease: pending, cla: yes

#5901 Release google-cloud-speech 1.0.0
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes

#5886 Release google-cloud-secret_manager-v1 0.3.1
  google-cloud-secret_manager-v1/CHANGELOG.md
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/version.rb
Labels: autorelease: pending, cla: yes

#5883 Release google-cloud-secret_manager-v1beta1 0.5.1
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5881 Release google-cloud-kms-v1 0.1.1
  google-cloud-kms-v1/CHANGELOG.md
  google-cloud-kms-v1/lib/google/cloud/kms/v1/version.rb
Labels: autorelease: pending, cla: yes

#5880 Release google-cloud-security_center-v1p1beta1 0.1.1
  google-cloud-security_center-v1p1beta1/CHANGELOG.md
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5879 Release google-cloud-dataproc-v1 0.1.1
  google-cloud-dataproc-v1/CHANGELOG.md
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/version.rb
Labels: autorelease: pending, cla: yes

#5877 Release google-cloud-data_catalog-v1 0.3.1
  google-cloud-data_catalog-v1/CHANGELOG.md
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/version.rb
Labels: autorelease: pending, cla: yes

#5876 Release google-cloud-security_center-v1 0.1.1
  google-cloud-security_center-v1/CHANGELOG.md
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/version.rb
Labels: autorelease: pending, cla: yes

#5875 Release google-cloud-video_intelligence-v1p2beta1 0.1.1
  google-cloud-video_intelligence-v1p2beta1/CHANGELOG.md
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/video_intelligence/v1p2beta1/version.rb
Labels: autorelease: pending, cla: yes

#5884 Release google-cloud-logging 1.10.5
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending

#5817 docs(dialogflow): Add section on streaming methods to the migration guide
  google-cloud-dialogflow/MIGRATING.md
Labels: cla: yes

#5874 Release google-cloud-web_risk-v1 0.1.1
  google-cloud-web_risk-v1/CHANGELOG.md
  google-cloud-web_risk-v1/lib/google/cloud/web_risk/v1/version.rb
Labels: autorelease: pending, cla: yes

#5873 Release google-cloud-web_risk-v1beta1 0.1.1
  google-cloud-web_risk-v1beta1/CHANGELOG.md
  google-cloud-web_risk-v1beta1/lib/google/cloud/web_risk/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5871 Release google-cloud-language-v1beta2 0.1.5
  google-cloud-language-v1beta2/CHANGELOG.md
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#5872 Release google-cloud-billing-v1 0.4.1
  google-cloud-billing-v1/CHANGELOG.md
  google-cloud-billing-v1/lib/google/cloud/billing/v1/version.rb
Labels: autorelease: pending, cla: yes

#5870 Release google-cloud-service_directory-v1beta1 0.3.1
  google-cloud-service_directory-v1beta1/CHANGELOG.md
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5868 Release google-cloud-dataproc-v1beta2 0.1.1
  google-cloud-dataproc-v1beta2/CHANGELOG.md
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#5867 Release google-cloud-recaptcha_enterprise-v1beta1 0.1.1
  google-cloud-recaptcha_enterprise-v1beta1/CHANGELOG.md
  google-cloud-recaptcha_enterprise-v1beta1/lib/google/cloud/recaptcha_enterprise/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5865 Release google-cloud-recommender-v1 0.3.3
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
Labels: autorelease: pending, cla: yes

#5864 Release google-cloud-redis-v1beta1 0.1.1
  google-cloud-redis-v1beta1/CHANGELOG.md
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5861 Release google-cloud-language-v1 0.1.4
  google-cloud-language-v1/CHANGELOG.md
  google-cloud-language-v1/lib/google/cloud/language/v1/version.rb
Labels: autorelease: pending, cla: yes

#5860 Release google-cloud-recaptcha_enterprise-v1 0.1.1
  google-cloud-recaptcha_enterprise-v1/CHANGELOG.md
  google-cloud-recaptcha_enterprise-v1/lib/google/cloud/recaptcha_enterprise/v1/version.rb
Labels: autorelease: pending, cla: yes

#5858 Release google-cloud-bigquery-data_transfer-v1 0.1.1
  google-cloud-bigquery-data_transfer-v1/CHANGELOG.md
  google-cloud-bigquery-data_transfer-v1/lib/google/cloud/bigquery/data_transfer/v1/version.rb
Labels: autorelease: pending, cla: yes

#5859 Release google-cloud-automl-v1beta1 0.1.1
  google-cloud-automl-v1beta1/CHANGELOG.md
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5856 Release google-cloud-automl-v1 0.1.1
  google-cloud-automl-v1/CHANGELOG.md
  google-cloud-automl-v1/lib/google/cloud/automl/v1/version.rb
Labels: autorelease: pending, cla: yes

#5855 Release google-cloud-asset-v1beta1 0.1.4
  google-cloud-asset-v1beta1/CHANGELOG.md
  google-cloud-asset-v1beta1/lib/google/cloud/asset/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5851 Release google-cloud-asset-v1 0.2.3
  google-cloud-asset-v1/CHANGELOG.md
  google-cloud-asset-v1/lib/google/cloud/asset/v1/version.rb
Labels: autorelease: pending, cla: yes

#5853 Release google-cloud-access_approval-v1 0.1.3
  google-cloud-access_approval-v1/CHANGELOG.md
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/version.rb
Labels: autorelease: pending, cla: yes

#5852 Release google-cloud-bigquery-storage-v1 0.1.4
  google-cloud-bigquery-storage-v1/CHANGELOG.md
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/version.rb
Labels: autorelease: pending, cla: yes

#5869 Release google-cloud-secret_manager 0.4.1
  google-cloud-secret_manager/CHANGELOG.md
  google-cloud-secret_manager/lib/google/cloud/secret_manager/version.rb
Labels: autorelease: pending, cla: yes

#5866 Release google-cloud-service_directory 0.2.1
  google-cloud-service_directory/CHANGELOG.md
  google-cloud-service_directory/lib/google/cloud/service_directory/version.rb
Labels: autorelease: pending, cla: yes

#5863 Release google-cloud-language 1.1.1
  google-cloud-language/CHANGELOG.md
  google-cloud-language/lib/google/cloud/language/version.rb
Labels: autorelease: pending, cla: yes

#5862 Release google-cloud-recommender 0.2.1
  google-cloud-recommender/CHANGELOG.md
  google-cloud-recommender/lib/google/cloud/recommender/version.rb
Labels: autorelease: pending, cla: yes

#5850 Release google-cloud-billing 0.2.1
  google-cloud-billing/CHANGELOG.md
  google-cloud-billing/lib/google/cloud/billing/version.rb
Labels: autorelease: pending, cla: yes

#5849 Release google-cloud-bigquery-storage 0.2.1
  google-cloud-bigquery-storage/CHANGELOG.md
  google-cloud-bigquery-storage/lib/google/cloud/bigquery/storage/version.rb
Labels: autorelease: pending, cla: yes

#5857 Release google-cloud-data_catalog 0.2.1
  google-cloud-data_catalog/CHANGELOG.md
  google-cloud-data_catalog/lib/google/cloud/data_catalog/version.rb
Labels: autorelease: pending, cla: yes

#5847 chore(datastore): Add samples from ruby-docs-samples
  google-cloud-datastore/Rakefile
  google-cloud-datastore/samples/.rubocop.yml
  google-cloud-datastore/samples/Gemfile
  google-cloud-datastore/samples/README.md
  google-cloud-datastore/samples/Rakefile
  google-cloud-datastore/samples/acceptance/helper.rb
  google-cloud-datastore/samples/acceptance/quickstart_test.rb
  google-cloud-datastore/samples/acceptance/sample_test.rb
  google-cloud-datastore/samples/acceptance/tasks_test.rb
  google-cloud-datastore/samples/index.yaml
  google-cloud-datastore/samples/quickstart.rb
  google-cloud-datastore/samples/sample.rb
  google-cloud-datastore/samples/tasks.rb
Labels: api: datastore, cla: yes

#5854 Release google-cloud-asset 1.0.2
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes

#5902 Release google-cloud-container-v1beta1 0.1.0
  google-cloud-container-v1beta1/CHANGELOG.md
  google-cloud-container-v1beta1/lib/google/cloud/container/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5903 Release google-cloud-container-v1 0.1.0
  google-cloud-container-v1/CHANGELOG.md
  google-cloud-container-v1/lib/google/cloud/container/v1/version.rb
Labels: autorelease: pending, cla: yes

#5904 Release google-cloud-os_login-v1 0.1.0
  google-cloud-os_login-v1/CHANGELOG.md
  google-cloud-os_login-v1/lib/google/cloud/os_login/v1/version.rb
Labels: autorelease: pending, cla: yes

#5905 Release google-cloud-os_login-v1beta 0.1.0
  google-cloud-os_login-v1beta/CHANGELOG.md
  google-cloud-os_login-v1beta/lib/google/cloud/os_login/v1beta/version.rb
Labels: autorelease: pending, cla: yes

#5906 Release google-cloud-text_to_speech-v1 0.1.0
  google-cloud-text_to_speech-v1/CHANGELOG.md
  google-cloud-text_to_speech-v1/lib/google/cloud/text_to_speech/v1/version.rb
Labels: autorelease: pending, cla: yes

#5907 Release google-cloud-text_to_speech-v1beta1 0.1.0
  google-cloud-text_to_speech-v1beta1/CHANGELOG.md
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/text_to_speech/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5908 Release google-cloud-scheduler-v1 0.1.0
  google-cloud-scheduler-v1/CHANGELOG.md
  google-cloud-scheduler-v1/lib/google/cloud/scheduler/v1/version.rb
Labels: autorelease: pending, cla: yes

#5909 Release google-cloud-scheduler-v1beta1 0.1.0
  google-cloud-scheduler-v1beta1/CHANGELOG.md
  google-cloud-scheduler-v1beta1/lib/google/cloud/scheduler/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5910 Release google-cloud-tasks-v2 0.1.0
  google-cloud-tasks-v2/CHANGELOG.md
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/version.rb
Labels: autorelease: pending, cla: yes

#5911 Release google-cloud-tasks-v2beta2 0.1.0
  google-cloud-tasks-v2beta2/CHANGELOG.md
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/version.rb
Labels: autorelease: pending, cla: yes

#5912 Release google-cloud-tasks-v2beta3 0.1.0
  google-cloud-tasks-v2beta3/CHANGELOG.md
  google-cloud-tasks-v2beta3/lib/google/cloud/tasks/v2beta3/version.rb
Labels: autorelease: pending, cla: yes

#5916 Create CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#5913 [CHANGE ME] Re-generated google-cloud-monitoring-v3 to pick up changes in the API or client library generator.
  google-cloud-monitoring-v3/lib/google/monitoring/v3/alert_pb.rb
  google-cloud-monitoring-v3/proto_docs/google/monitoring/v3/alert.rb
  google-cloud-monitoring-v3/synth.metadata
Labels: cla: yes

#5899 Release google-cloud-storage 1.26.1
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes

#5917 Release google-cloud-dialogflow 1.0.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes

#5918 Release google-cloud-bigquery-data_transfer 1.0.0
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes

#5920 Release google-cloud-text_to_speech 1.0.0
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/version.rb
Labels: autorelease: pending, cla: yes

#5898 Release google-cloud-pubsub 1.6.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#5921 Release google-cloud-security_center 1.0.0
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes

#5922 Release google-cloud-dataproc 1.0.0
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes

#5923 Release google-cloud-container 1.0.0
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes

#5930 [google-cloud-secret_manager-v1beta1] Update documentation
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secrets/v1beta1/service_services_pb.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/service.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes, context: full

#5927 test(redis): Add basic smoke test
  google-cloud-redis/acceptance/redis_smoke_test.rb
Labels: cla: yes

#5931 Release google-cloud-os_login 1.0.0
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes

#5932 Release google-cloud-web_risk 1.0.0
  google-cloud-web_risk/CHANGELOG.md
  google-cloud-web_risk/lib/google/cloud/web_risk/version.rb
Labels: autorelease: pending, cla: yes

#5934 Release google-cloud-redis 1.0.0
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes

#5933 Release google-cloud-recaptcha_enterprise 1.0.0
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes

#5935 Release google-cloud-secret_manager-v1beta1 0.5.2
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5926 feat(webrisk): Deprecate google-cloud-webrisk
  google-cloud-webrisk/README.md
  google-cloud-webrisk/google-cloud-webrisk.gemspec
  google-cloud-webrisk/lib/google/cloud/webrisk.rb
  google-cloud-webrisk/synth.metadata
  google-cloud-webrisk/synth.py
Labels: cla: yes

#5940 fix(trace): V2 constructor is broken
  google-cloud-trace/lib/google/cloud/trace/v2.rb
Labels: api: cloudtrace, cla: yes

#5938 Release google-cloud-webrisk 0.6.0
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes

#5943 Release google-cloud-trace 0.38.1
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes

#5941 [google-cloud-data_catalog-v1] chore: enable gapicv2 for datacatalog/v1beta1 API
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/data_catalog/client.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/datacatalog.rb
  google-cloud-data_catalog-v1/synth.metadata
Labels: cla: yes, context: full

#5942 [google-cloud-spanner] fix: update backup RPC timeouts from 30secs to 10mins
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json
  google-cloud-spanner/synth.metadata
Labels: cla: yes, context: full

#5925 feat(pubsub): Set client-scoped UUID in initial StreamingPullRequest#client_id
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/acknowledge_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/inventory_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/modify_ack_deadline_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/nack_test.rb
Labels: api: pubsub, cla: yes

#5937 fix(spanner): run system test against emulator skip not supported tests by emulator
  google-cloud-spanner/acceptance/spanner/backup_operations_test.rb
  google-cloud-spanner/acceptance/spanner/backup_test.rb
  google-cloud-spanner/acceptance/spanner/batch_client/execute_partition_test.rb
  google-cloud-spanner/acceptance/spanner/client/batch_update_test.rb
  google-cloud-spanner/acceptance/spanner/client/large_data_test.rb
  google-cloud-spanner/acceptance/spanner/client/params/struct_test.rb
  google-cloud-spanner/acceptance/spanner/client/pdml_test.rb
  google-cloud-spanner/acceptance/spanner/client/single_use_test.rb
  google-cloud-spanner/acceptance/spanner/client/snapshot_test.rb
  google-cloud-spanner/acceptance/spanner/client/transaction_test.rb
  google-cloud-spanner/acceptance/spanner/database_operations_test.rb
  google-cloud-spanner/acceptance/spanner/database_test.rb
  google-cloud-spanner/acceptance/spanner/instance_test.rb
  google-cloud-spanner/acceptance/spanner_helper.rb
Labels: api: spanner, cla: yes

#5949 fix(spanner): update to not require key file when running against the emulator.
  google-cloud-spanner/Rakefile
Labels: api: spanner, cla: yes

#5948 [google-cloud-pubsub] Removing the experimental tag from dead letter policy related fields.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes, context: full

#5947 [google-cloud-dlp-v2] Release new file type enums and new MetadataLocation proto.
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/dlp_service/client.rb
  google-cloud-dlp-v2/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp-v2/lib/google/privacy/dlp/v2/storage_pb.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp-v2/synth.metadata
Labels: cla: yes, context: full

#5954 [google-cloud-secret_manager-v1] Update documentation
  google-cloud-secret_manager-v1/lib/google/cloud/secretmanager/v1/service_services_pb.rb
  google-cloud-secret_manager-v1/proto_docs/google/cloud/secretmanager/v1/resources.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes, context: full

#5951 Fix Ruby 2.7 warn
  google-cloud-firestore/lib/google/cloud/firestore/service.rb
Labels: cla: yes

#5953 chore(firestore): Mark Firestore lower-level v1beta1 client as deprecated
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/synth.metadata
  google-cloud-firestore/synth.py
Labels: api: firestore

#5959 [google-cloud-dlp-v2] Cloud DLP - fix routing for gRPC clients by embedding location into parent instead of having it's own parameter. API still remain global only, but prepares for the addition of regional support.
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/dlp_service/client.rb
  google-cloud-dlp-v2/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp-v2/synth.metadata
  google-cloud-dlp-v2/test/google/cloud/dlp/v2/dlp_service_test.rb
Labels: cla: yes, context: full

#5957 bigquery(docs): Update documentation for udfs param
  google-cloud-bigquery/Rakefile
  google-cloud-bigquery/acceptance/bigquery/bigquery_test.rb
  google-cloud-bigquery/acceptance/bigquery_helper.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/project.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
Labels: api: bigquery, cla: yes

#5956 Release google-cloud-firestore 1.4.2
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#5955 Release google-cloud-dlp-v2 0.2.0
  google-cloud-dlp-v2/CHANGELOG.md
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/version.rb
Labels: autorelease: pending, cla: yes

#5960 chore: Kick 404 enforcement out again
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#5961 chore(monitoring-v3): Hack synth file to remove dead links in docs for an obsolete proto
  google-cloud-monitoring-v3/synth.py
Labels: cla: yes

#5958 Add samples for Cloud Scheduler
  google-cloud-scheduler/samples/.rubocop.yml
  google-cloud-scheduler/samples/Gemfile
  google-cloud-scheduler/samples/README.md
  google-cloud-scheduler/samples/Rakefile
  google-cloud-scheduler/samples/acceptance/sample_server_test.rb
  google-cloud-scheduler/samples/acceptance/scheduler_test.rb
  google-cloud-scheduler/samples/app.rb
  google-cloud-scheduler/samples/app.yaml
  google-cloud-scheduler/samples/create_job.rb
  google-cloud-scheduler/samples/delete_job.rb
Labels: cla: yes

#5814 Update samples for Cloud Tasks
  google-cloud-tasks/samples/Gemfile
  google-cloud-tasks/samples/README.md
  google-cloud-tasks/samples/Rakefile
  google-cloud-tasks/samples/create_http_task.rb
  google-cloud-tasks/samples/test/task_test.rb
Labels: cla: yes

#5965 chore(bigquery): Add samples from ruby-docs-samples
  google-cloud-bigquery/Rakefile
  google-cloud-bigquery/samples/simple_app/.rubocop.yml
  google-cloud-bigquery/samples/simple_app/Gemfile
  google-cloud-bigquery/samples/simple_app/README.md
  google-cloud-bigquery/samples/simple_app/Rakefile
  google-cloud-bigquery/samples/simple_app/acceptance/stackoverflow_test.rb
  google-cloud-bigquery/samples/simple_app/stackoverflow.rb
  google-cloud-bigquery/samples/snippets/.rubocop.yml
  google-cloud-bigquery/samples/snippets/Gemfile
  google-cloud-bigquery/samples/snippets/README.md
  google-cloud-bigquery/samples/snippets/Rakefile
  google-cloud-bigquery/samples/snippets/acceptance/browse_table_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/create_dataset_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/create_table_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/delete_dataset_and_contents_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/delete_dataset_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/delete_table_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/extract_table_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/helper.rb
  google-cloud-bigquery/samples/snippets/acceptance/list_datasets_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/list_tables_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/load_from_file_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/load_table_gcs_csv_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/load_table_gcs_json_autodetect_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/load_table_gcs_json_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/load_table_gcs_json_truncate_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/load_table_gcs_orc_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/load_table_gcs_orc_truncate_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/query_test.rb
  google-cloud-bigquery/samples/snippets/acceptance/table_insert_rows_test.rb
  google-cloud-bigquery/samples/snippets/browse_table.rb
  google-cloud-bigquery/samples/snippets/create_dataset.rb
  google-cloud-bigquery/samples/snippets/create_table.rb
  google-cloud-bigquery/samples/snippets/delete_dataset.rb
  google-cloud-bigquery/samples/snippets/delete_dataset_and_contents.rb
  google-cloud-bigquery/samples/snippets/delete_table.rb
  google-cloud-bigquery/samples/snippets/extract_table.rb
  google-cloud-bigquery/samples/snippets/list_datasets.rb
  google-cloud-bigquery/samples/snippets/list_tables.rb
  google-cloud-bigquery/samples/snippets/load_from_file.rb
  google-cloud-bigquery/samples/snippets/load_table_gcs_csv.rb
  google-cloud-bigquery/samples/snippets/load_table_gcs_json.rb
  google-cloud-bigquery/samples/snippets/load_table_gcs_json_autodetect.rb
  google-cloud-bigquery/samples/snippets/load_table_gcs_json_truncate.rb
  google-cloud-bigquery/samples/snippets/load_table_gcs_orc.rb
  google-cloud-bigquery/samples/snippets/load_table_gcs_orc_truncate.rb
  google-cloud-bigquery/samples/snippets/query.rb
  google-cloud-bigquery/samples/snippets/resources/people.csv
  google-cloud-bigquery/samples/snippets/table_insert_rows.rb
Labels: api: bigquery, cla: yes

#5968 [CHANGE ME] Re-generated google-cloud-monitoring-v3 to pick up changes in the API or client library generator.
  google-cloud-monitoring-v3/proto_docs/google/monitoring/v3/common.rb
  google-cloud-monitoring-v3/synth.metadata
Labels: cla: yes, context: none

#5967 [google-cloud-asset-v1] cloudasset: add SearchAllResources and SearchAllIamPolicies RPCs
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_services_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/assets_pb.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/asset_service.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/assets.rb
  google-cloud-asset-v1/synth.metadata
  google-cloud-asset-v1/test/google/cloud/asset/v1/asset_service_test.rb
Labels: cla: yes, context: full

#5969 docs(os_login): Fix a typo in the migration guide
  google-cloud-os_login/MIGRATING.md
Labels: cla: yes

#5966 feat: Extract google-cloud-translate-v2 from google-cloud-translate
  .kokoro/continuous/linux/translate-v2.cfg
  .kokoro/continuous/osx/translate-v2.cfg
  .kokoro/continuous/windows/translate-v2.cfg
  .kokoro/nightly/linux/translate-v2.cfg
  .kokoro/nightly/osx/translate-v2.cfg
  .kokoro/nightly/windows/translate-v2.cfg
  .kokoro/release/translate-v2.cfg
  Gemfile
  google-cloud-translate-v2/.gitignore
  google-cloud-translate-v2/.repo-metadata.json
  google-cloud-translate-v2/.rubocop.yml
  google-cloud-translate-v2/.yardopts
  google-cloud-translate-v2/AUTHENTICATION.md
  google-cloud-translate-v2/CHANGELOG.md
  google-cloud-translate-v2/Gemfile
  google-cloud-translate-v2/LICENSE.md
  google-cloud-translate-v2/README.md
  google-cloud-translate-v2/Rakefile
  google-cloud-translate-v2/acceptance/translate/translate_test.rb
  google-cloud-translate-v2/acceptance/translate_helper.rb
  google-cloud-translate-v2/google-cloud-translate-v2.gemspec
  google-cloud-translate-v2/lib/google-cloud-translate-v2.rb
  google-cloud-translate-v2/lib/google/cloud/translate/v2.rb
  google-cloud-translate-v2/lib/google/cloud/translate/v2/api.rb
  google-cloud-translate-v2/lib/google/cloud/translate/v2/credentials.rb
  google-cloud-translate-v2/lib/google/cloud/translate/v2/detection.rb
  google-cloud-translate-v2/lib/google/cloud/translate/v2/language.rb
  google-cloud-translate-v2/lib/google/cloud/translate/v2/service.rb
  google-cloud-translate-v2/lib/google/cloud/translate/v2/translation.rb
  google-cloud-translate-v2/lib/google/cloud/translate/v2/version.rb
  google-cloud-translate-v2/support/doctest_helper.rb
  google-cloud-translate-v2/test/google/cloud/translate/v2/detect_test.rb
  google-cloud-translate-v2/test/google/cloud/translate/v2/languages_test.rb
  google-cloud-translate-v2/test/google/cloud/translate/v2/service_test.rb
  google-cloud-translate-v2/test/google/cloud/translate/v2/translate_test.rb
  google-cloud-translate-v2/test/google/cloud/translate/v2_test.rb
  google-cloud-translate-v2/test/helper.rb
Labels: cla: yes

#5962 fix(dlp): Update dependency on dlp-v2 to 0.2
  google-cloud-dlp/google-cloud-dlp.gemspec
  google-cloud-dlp/synth.py
Labels: cla: yes

#5970 Release google-cloud-asset-v1 0.3.0
  google-cloud-asset-v1/CHANGELOG.md
  google-cloud-asset-v1/lib/google/cloud/asset/v1/version.rb
Labels: autorelease: pending, cla: yes

#5971 Release google-cloud-os_login 1.0.1
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes

#5974 Release google-cloud-dlp 1.0.0
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes

#5889 Release google-cloud-tasks 2.0.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes

#5887 Release google-cloud-scheduler 2.0.0
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/lib/google/cloud/scheduler/version.rb
Labels: autorelease: pending, cla: yes

#5977 fix: Pin protobuf on old rubies
  .kokoro/build.sh
  Gemfile
  gcloud/Gemfile
  google-cloud-bigquery/Gemfile
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigtable/Gemfile
  google-cloud-bigtable/support/doctest_helper.rb
  google-cloud-container_analysis/Gemfile
  google-cloud-core/Gemfile
  google-cloud-datastore/Gemfile
  google-cloud-datastore/support/doctest_helper.rb
  google-cloud-debugger/Gemfile
  google-cloud-debugger/support/doctest_helper.rb
  google-cloud-dns/Gemfile
  google-cloud-dns/support/doctest_helper.rb
  google-cloud-env/Gemfile
  google-cloud-error_reporting/Gemfile
  google-cloud-error_reporting/support/doctest_helper.rb
  google-cloud-errors/Gemfile
  google-cloud-firestore/Gemfile
  google-cloud-firestore/support/doctest_helper.rb
  google-cloud-logging/Gemfile
  google-cloud-logging/support/doctest_helper.rb
  google-cloud-phishing_protection/Gemfile
  google-cloud-pubsub/Gemfile
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-resource_manager/Gemfile
  google-cloud-resource_manager/support/doctest_helper.rb
  google-cloud-spanner/Gemfile
  google-cloud-spanner/support/doctest_helper.rb
  google-cloud-storage/Gemfile
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-trace/Gemfile
  google-cloud-trace/support/doctest_helper.rb
  google-cloud/Gemfile
  grafeas-client/Gemfile
  grafeas/Gemfile
  stackdriver-core/Gemfile
  stackdriver/Gemfile
Labels: cla: yes

#5986 [google-cloud-translate] fix: restore GAPIC v2 retry configs
  google-cloud-translate/lib/google/cloud/translate/v3/translation_service_client.rb
  google-cloud-translate/lib/google/cloud/translate/v3/translation_service_client_config.json
  google-cloud-translate/synth.metadata
  google-cloud-translate/test/google/cloud/translate/v3/translation_service_client_test.rb
Labels: cla: yes, context: full

#5985 [google-cloud-trace] fix: restore GAPIC v2 retry configs
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client_config.json
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client_config.json
  google-cloud-trace/synth.metadata
Labels: cla: yes, context: full
