Repository googleapis/google-cloud-ruby, pull requests merged in 2020-04, with the labels that each got.

#5223 [CHANGE ME] Re-generated google-cloud-access_approval-v1 to pick up changes in the API or client library generator.
  google-cloud-access_approval-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-access_approval-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-access_approval-v1/synth.metadata
Labels: cla: yes

#5261 [CHANGE ME] Re-generated grafeas to pick up changes in the API or client library generator.
  grafeas/AUTHENTICATION.md
  grafeas/synth.metadata
Labels: cla: yes

#5260 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/AUTHENTICATION.md
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#5259 [CHANGE ME] Re-generated google-cloud-vision-v1p3beta1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1p3beta1/proto_docs/google/protobuf/any.rb
  google-cloud-vision-v1p3beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-vision-v1p3beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-vision-v1p3beta1/synth.metadata
Labels: cla: yes

#5258 [CHANGE ME] Re-generated google-cloud-vision-v1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1/proto_docs/google/protobuf/any.rb
  google-cloud-vision-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-vision-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-vision-v1/synth.metadata
Labels: cla: yes

#5257 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/AUTHENTICATION.md
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#5256 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/AUTHENTICATION.md
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#5255 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/AUTHENTICATION.md
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#5253 [CHANGE ME] Re-generated google-cloud-speech-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1p1beta1/proto_docs/google/protobuf/any.rb
  google-cloud-speech-v1p1beta1/proto_docs/google/protobuf/duration.rb
  google-cloud-speech-v1p1beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-speech-v1p1beta1/synth.metadata
Labels: cla: yes

#5252 [CHANGE ME] Re-generated google-cloud-speech-v1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1/proto_docs/google/protobuf/any.rb
  google-cloud-speech-v1/proto_docs/google/protobuf/duration.rb
  google-cloud-speech-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-speech-v1/synth.metadata
Labels: cla: yes

#5251 [CHANGE ME] Re-generated google-cloud-service_directory-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-service_directory-v1beta1/synth.metadata
Labels: cla: yes

#5250 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/AUTHENTICATION.md
  google-cloud-security_center/lib/google/cloud/security_center/v1/helpers.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/helpers.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/security_center_client.rb
  google-cloud-security_center/synth.metadata
  google-cloud-security_center/test/google/cloud/security_center/v1/helpers_test.rb
  google-cloud-security_center/test/google/cloud/security_center/v1p1beta1/helpers_test.rb
Labels: cla: yes

#5249 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/service.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#5247 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/AUTHENTICATION.md
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#5246 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/AUTHENTICATION.md
  google-cloud-redis/synth.metadata
Labels: cla: yes

#5245 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/proto_docs/google/protobuf/duration.rb
  google-cloud-recommender-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes

#5244 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/AUTHENTICATION.md
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#5243 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#5242 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/AUTHENTICATION.md
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#5241 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/AUTHENTICATION.md
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#5240 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/AUTHENTICATION.md
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#5239 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#5238 [CHANGE ME] Re-generated google-cloud-language-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-language-v1beta2/proto_docs/google/protobuf/timestamp.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes

#5237 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/AUTHENTICATION.md
  google-cloud-kms/synth.metadata
Labels: cla: yes

#5236 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/AUTHENTICATION.md
  google-cloud-irm/synth.metadata
Labels: cla: yes

#5235 [CHANGE ME] Re-generated google-cloud-iot-v1 to pick up changes in the API or client library generator.
  google-cloud-iot-v1/proto_docs/google/protobuf/any.rb
  google-cloud-iot-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-iot-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-iot-v1/synth.metadata
Labels: cla: yes

#5233 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/proto_docs/google/protobuf/any.rb
  google-cloud-dialogflow-v2/proto_docs/google/protobuf/duration.rb
  google-cloud-dialogflow-v2/proto_docs/google/protobuf/field_mask.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes

#5230 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/AUTHENTICATION.md
  google-cloud-container/synth.metadata
Labels: cla: yes

#5229 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-billing-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#5228 [CHANGE ME] Re-generated google-cloud-bigquery-storage-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-bigquery-storage-v1/synth.metadata
Labels: cla: yes

#5227 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/AUTHENTICATION.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/datatransfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/datatransfer_pb.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/datatransfer_services_pb.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#5226 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/AUTHENTICATION.md
  google-cloud-automl/synth.metadata
Labels: cla: yes

#5225 [CHANGE ME] Re-generated google-cloud-asset-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1beta1/proto_docs/google/protobuf/any.rb
  google-cloud-asset-v1beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-asset-v1beta1/synth.metadata
Labels: cla: yes

#5224 [CHANGE ME] Re-generated google-cloud-asset-v1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_services_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/assets_pb.rb
  google-cloud-asset-v1/lib/google/identity/accesscontextmanager/type/device_resources_pb.rb
  google-cloud-asset-v1/lib/google/identity/accesscontextmanager/v1/access_level_pb.rb
  google-cloud-asset-v1/lib/google/identity/accesscontextmanager/v1/access_policy_pb.rb
  google-cloud-asset-v1/lib/google/identity/accesscontextmanager/v1/service_perimeter_pb.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/asset_service.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/assets.rb
  google-cloud-asset-v1/proto_docs/google/identity/accesscontextmanager/type/device_resources.rb
  google-cloud-asset-v1/proto_docs/google/identity/accesscontextmanager/v1/access_level.rb
  google-cloud-asset-v1/proto_docs/google/identity/accesscontextmanager/v1/access_policy.rb
  google-cloud-asset-v1/proto_docs/google/identity/accesscontextmanager/v1/service_perimeter.rb
  google-cloud-asset-v1/proto_docs/google/protobuf/any.rb
  google-cloud-asset-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-asset-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-asset-v1/proto_docs/google/type/expr.rb
  google-cloud-asset-v1/synth.metadata
Labels: cla: yes

#5303 chore(secret_manager-v1): Disable context-aware-commits for now
  google-cloud-secret_manager-v1/synth.py
Labels: cla: yes

#5302 Release google-cloud-video_intelligence 2.1.1
  google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/version.rb
Labels: autorelease: pending, cla: yes

#5301 Release google-cloud-dialogflow-v2 0.2.2
  google-cloud-dialogflow-v2/CHANGELOG.md
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/version.rb
Labels: autorelease: pending, cla: yes

#5300 Release google-cloud-vision-v1p3beta1 0.1.1
  google-cloud-vision-v1p3beta1/CHANGELOG.md
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/version.rb
Labels: autorelease: pending, cla: yes

#5299 Release google-cloud-vision-v1 0.1.1
  google-cloud-vision-v1/CHANGELOG.md
  google-cloud-vision-v1/lib/google/cloud/vision/v1/version.rb
Labels: autorelease: pending, cla: yes

#5298 Release google-cloud-logging 1.10.2
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#5297 Release google-cloud-security_center 0.10.0
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes

#5296 Release google-cloud-tasks 1.5.1
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes

#5295 Release google-cloud-text_to_speech 0.6.1
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/version.rb
Labels: autorelease: pending, cla: yes

#5294 Release google-cloud-scheduler 1.3.1
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/lib/google/cloud/scheduler/version.rb
Labels: autorelease: pending, cla: yes

#5293 Release google-cloud-secret_manager-v1beta1 0.4.1
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5292 Release google-cloud-language-v1beta2 0.1.2
  google-cloud-language-v1beta2/CHANGELOG.md
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#5291 Release google-cloud-service_directory-v1beta1 0.2.1
  google-cloud-service_directory-v1beta1/CHANGELOG.md
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5290 Release google-cloud-webrisk 0.5.1
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes

#5289 Release google-cloud-os_login 0.6.1
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes

#5288 Release google-cloud-speech-v1 0.1.1
  google-cloud-speech-v1/CHANGELOG.md
  google-cloud-speech-v1/lib/google/cloud/speech/v1/version.rb
Labels: autorelease: pending, cla: yes

#5287 Release google-cloud-speech-v1p1beta1 0.1.1
  google-cloud-speech-v1p1beta1/CHANGELOG.md
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5286 Release google-cloud-recommender-v1 0.3.1
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
Labels: autorelease: pending, cla: yes

#5285 Release google-cloud-kms 1.5.1
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes

#5284 Release grafeas 0.3.1
  grafeas/CHANGELOG.md
  grafeas/lib/grafeas/version.rb
Labels: autorelease: pending, cla: yes

#5283 Release google-cloud-bigquery-storage-v1 0.1.1
  google-cloud-bigquery-storage-v1/CHANGELOG.md
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/version.rb
Labels: autorelease: pending, cla: yes

#5282 Release google-cloud-container 0.10.1
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes

#5281 Release google-cloud-bigquery-data_transfer 0.8.0
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes

#5280 Release google-cloud-billing-v1 0.3.1
  google-cloud-billing-v1/CHANGELOG.md
  google-cloud-billing-v1/lib/google/cloud/billing/v1/version.rb
Labels: autorelease: pending, cla: yes

#5279 Release google-cloud-automl 0.7.1
  google-cloud-automl/CHANGELOG.md
  google-cloud-automl/lib/google/cloud/automl/version.rb
Labels: autorelease: pending, cla: yes

#5278 Release google-cloud-asset-v1beta1 0.1.1
  google-cloud-asset-v1beta1/CHANGELOG.md
  google-cloud-asset-v1beta1/lib/google/cloud/asset/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5277 Release google-cloud-asset-v1 0.2.0
  google-cloud-asset-v1/CHANGELOG.md
  google-cloud-asset-v1/lib/google/cloud/asset/v1/version.rb
Labels: autorelease: pending, cla: yes

#5276 Release google-cloud-access_approval-v1 0.1.1
  google-cloud-access_approval-v1/CHANGELOG.md
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/version.rb
Labels: autorelease: pending, cla: yes

#5222 Release google-cloud-monitoring 0.37.1
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes

#5221 Release google-cloud-resource_manager 0.33.2
  google-cloud-resource_manager/CHANGELOG.md
  google-cloud-resource_manager/lib/google/cloud/resource_manager/version.rb
Labels: autorelease: pending, cla: yes

#5198 Release google-cloud-phishing_protection 0.4.1
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes

#5197 Release google-cloud-recaptcha_enterprise 0.5.1
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes

#5196 Release google-cloud-redis 0.8.2
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes

#5314 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client_config.json
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#5313 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/README.md
  google-cloud-monitoring/lib/google/cloud/monitoring.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/common.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client_config.json
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#5305 feat: Initial microsynth of DataCatalog V1
  .kokoro/continuous/linux/data_catalog-v1.cfg
  .kokoro/continuous/osx/data_catalog-v1.cfg
  .kokoro/continuous/windows/data_catalog-v1.cfg
  .kokoro/nightly/linux/data_catalog-v1.cfg
  .kokoro/nightly/osx/data_catalog-v1.cfg
  .kokoro/nightly/windows/data_catalog-v1.cfg
  .kokoro/release/data_catalog-v1.cfg
  Gemfile
  google-cloud-data_catalog-v1/.gitignore
  google-cloud-data_catalog-v1/.repo-metadata.json
  google-cloud-data_catalog-v1/.rubocop.yml
  google-cloud-data_catalog-v1/.yardopts
  google-cloud-data_catalog-v1/AUTHENTICATION.md
  google-cloud-data_catalog-v1/CHANGELOG.md
  google-cloud-data_catalog-v1/Gemfile
  google-cloud-data_catalog-v1/LICENSE.md
  google-cloud-data_catalog-v1/README.md
  google-cloud-data_catalog-v1/Rakefile
  google-cloud-data_catalog-v1/google-cloud-data_catalog-v1.gemspec
  google-cloud-data_catalog-v1/lib/google-cloud-data_catalog-v1.rb
  google-cloud-data_catalog-v1/lib/google/cloud/common_resources_pb.rb
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1.rb
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/data_catalog.rb
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/data_catalog/client.rb
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/data_catalog/credentials.rb
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/data_catalog/paths.rb
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/version.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/common_pb.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/datacatalog_pb.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/datacatalog_services_pb.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/gcs_fileset_spec_pb.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/schema_pb.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/search_pb.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/table_spec_pb.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/tags_pb.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/timestamps_pb.rb
  google-cloud-data_catalog-v1/proto_docs/README.md
  google-cloud-data_catalog-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-data_catalog-v1/proto_docs/google/api/resource.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/common.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/datacatalog.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/gcs_fileset_spec.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/schema.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/search.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/table_spec.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/tags.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/timestamps.rb
  google-cloud-data_catalog-v1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-data_catalog-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-data_catalog-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-data_catalog-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-data_catalog-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-data_catalog-v1/synth.metadata
  google-cloud-data_catalog-v1/synth.py
  google-cloud-data_catalog-v1/test/google/cloud/data_catalog/v1/data_catalog_test.rb
Labels: cla: yes

#5308 feat: Initial microsynth of Redis V1
  .kokoro/continuous/linux/redis-v1.cfg
  .kokoro/continuous/osx/redis-v1.cfg
  .kokoro/continuous/windows/redis-v1.cfg
  .kokoro/nightly/linux/redis-v1.cfg
  .kokoro/nightly/osx/redis-v1.cfg
  .kokoro/nightly/windows/redis-v1.cfg
  .kokoro/release/redis-v1.cfg
  Gemfile
  google-cloud-redis-v1/.gitignore
  google-cloud-redis-v1/.repo-metadata.json
  google-cloud-redis-v1/.rubocop.yml
  google-cloud-redis-v1/.yardopts
  google-cloud-redis-v1/AUTHENTICATION.md
  google-cloud-redis-v1/CHANGELOG.md
  google-cloud-redis-v1/Gemfile
  google-cloud-redis-v1/LICENSE.md
  google-cloud-redis-v1/README.md
  google-cloud-redis-v1/Rakefile
  google-cloud-redis-v1/google-cloud-redis-v1.gemspec
  google-cloud-redis-v1/lib/google-cloud-redis-v1.rb
  google-cloud-redis-v1/lib/google/cloud/common_resources_pb.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/client.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/credentials.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/operations.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/paths.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis_pb.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis_services_pb.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/version.rb
  google-cloud-redis-v1/proto_docs/README.md
  google-cloud-redis-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-redis-v1/proto_docs/google/api/resource.rb
  google-cloud-redis-v1/proto_docs/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis-v1/proto_docs/google/longrunning/operations.rb
  google-cloud-redis-v1/proto_docs/google/protobuf/any.rb
  google-cloud-redis-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-redis-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-redis-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-redis-v1/proto_docs/google/rpc/status.rb
  google-cloud-redis-v1/synth.metadata
  google-cloud-redis-v1/synth.py
  google-cloud-redis-v1/test/google/cloud/redis/v1/cloud_redis_operations_test.rb
  google-cloud-redis-v1/test/google/cloud/redis/v1/cloud_redis_test.rb
Labels: cla: yes

#5309 feat: Initial microsynth of Redis V1beta1
  .kokoro/continuous/linux/redis-v1beta1.cfg
  .kokoro/continuous/osx/redis-v1beta1.cfg
  .kokoro/continuous/windows/redis-v1beta1.cfg
  .kokoro/nightly/linux/redis-v1beta1.cfg
  .kokoro/nightly/osx/redis-v1beta1.cfg
  .kokoro/nightly/windows/redis-v1beta1.cfg
  .kokoro/release/redis-v1beta1.cfg
  Gemfile
  google-cloud-redis-v1beta1/.gitignore
  google-cloud-redis-v1beta1/.repo-metadata.json
  google-cloud-redis-v1beta1/.rubocop.yml
  google-cloud-redis-v1beta1/.yardopts
  google-cloud-redis-v1beta1/AUTHENTICATION.md
  google-cloud-redis-v1beta1/CHANGELOG.md
  google-cloud-redis-v1beta1/Gemfile
  google-cloud-redis-v1beta1/LICENSE.md
  google-cloud-redis-v1beta1/README.md
  google-cloud-redis-v1beta1/Rakefile
  google-cloud-redis-v1beta1/google-cloud-redis-v1beta1.gemspec
  google-cloud-redis-v1beta1/lib/google-cloud-redis-v1beta1.rb
  google-cloud-redis-v1beta1/lib/google/cloud/common_resources_pb.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/client.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/credentials.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/operations.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/paths.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis_pb.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis_services_pb.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/version.rb
  google-cloud-redis-v1beta1/proto_docs/README.md
  google-cloud-redis-v1beta1/proto_docs/google/api/field_behavior.rb
  google-cloud-redis-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-redis-v1beta1/proto_docs/google/cloud/redis/v1beta1/cloud_redis.rb
  google-cloud-redis-v1beta1/proto_docs/google/longrunning/operations.rb
  google-cloud-redis-v1beta1/proto_docs/google/protobuf/any.rb
  google-cloud-redis-v1beta1/proto_docs/google/protobuf/empty.rb
  google-cloud-redis-v1beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-redis-v1beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-redis-v1beta1/proto_docs/google/rpc/status.rb
  google-cloud-redis-v1beta1/synth.metadata
  google-cloud-redis-v1beta1/synth.py
  google-cloud-redis-v1beta1/test/google/cloud/redis/v1beta1/cloud_redis_operations_test.rb
  google-cloud-redis-v1beta1/test/google/cloud/redis/v1beta1/cloud_redis_test.rb
Labels: cla: yes

#5317 feat: Initial wrapper synth of DataCatalog
  .kokoro/continuous/linux/data_catalog.cfg
  .kokoro/continuous/osx/data_catalog.cfg
  .kokoro/continuous/windows/data_catalog.cfg
  .kokoro/nightly/linux/data_catalog.cfg
  .kokoro/nightly/osx/data_catalog.cfg
  .kokoro/nightly/windows/data_catalog.cfg
  .kokoro/release/data_catalog.cfg
  .kokoro/samples_latest/linux/data_catalog.cfg
  .kokoro/samples_latest/osx/data_catalog.cfg
  .kokoro/samples_latest/windows/data_catalog.cfg
  .kokoro/samples_master/linux/data_catalog.cfg
  .kokoro/samples_master/osx/data_catalog.cfg
  .kokoro/samples_master/windows/data_catalog.cfg
  Gemfile
  google-cloud-data_catalog/.gitignore
  google-cloud-data_catalog/.repo-metadata.json
  google-cloud-data_catalog/.rubocop.yml
  google-cloud-data_catalog/.yardopts
  google-cloud-data_catalog/AUTHENTICATION.md
  google-cloud-data_catalog/CHANGELOG.md
  google-cloud-data_catalog/Gemfile
  google-cloud-data_catalog/LICENSE.md
  google-cloud-data_catalog/README.md
  google-cloud-data_catalog/Rakefile
  google-cloud-data_catalog/google-cloud-data_catalog.gemspec
  google-cloud-data_catalog/lib/google-cloud-data_catalog.rb
  google-cloud-data_catalog/lib/google/cloud/data_catalog.rb
  google-cloud-data_catalog/lib/google/cloud/data_catalog/version.rb
  google-cloud-data_catalog/synth.metadata
  google-cloud-data_catalog/synth.py
  google-cloud-data_catalog/test/google/cloud/data_catalog/client_test.rb
  google-cloud-data_catalog/test/google/cloud/data_catalog/version_test.rb
  google-cloud-data_catalog/test/helper.rb
Labels: cla: yes

#5312 chore(container_analysis): restore path helpers for gapic v2 generation
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/helpers.rb
  google-cloud-container_analysis/synth.py
Labels: cla: yes

#4866 Storage v4 POST Policy
  google-cloud-storage/acceptance/storage/bucket_generate_signed_post_policy_v4_test.rb
  google-cloud-storage/acceptance/storage/bucket_post_object_v2_test.rb
  google-cloud-storage/acceptance/storage/signed_url_v2_test.rb
  google-cloud-storage/acceptance/storage/signed_url_v4_test.rb
  google-cloud-storage/conformance/README.md
  google-cloud-storage/conformance/v1/proto/google/cloud/conformance/storage/v1/tests.proto
  google-cloud-storage/conformance/v1/proto/google/cloud/conformance/storage/v1/tests_pb.rb
  google-cloud-storage/conformance/v1/v4_signatures.json
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/file/signer_v4.rb
  google-cloud-storage/lib/google/cloud/storage/post_object.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/data/signer_v4_test_account.json
  google-cloud-storage/test/data/signer_v4_test_data.json
  google-cloud-storage/test/google/cloud/storage/file/signer_v4/escape_characters_test.rb
  google-cloud-storage/test/google/cloud/storage/file/signer_v4/post_object_conformance_test.rb
  google-cloud-storage/test/google/cloud/storage/file/signer_v4/signed_url_conformance_test.rb
Labels: api: storage, cla: yes

#5318 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/AUTHENTICATION.md
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client_config.json
  google-cloud-container_analysis/synth.metadata
  google-cloud-container_analysis/test/google/cloud/container_analysis/v1/container_analysis_client_test.rb
Labels: cla: yes

#5319 [CHANGE ME] Re-generated google-cloud-dataproc-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller/operations.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/jobs_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/jobs_services_pb.rb
  google-cloud-dataproc-v1beta2/proto_docs/google/cloud/dataproc/v1beta2/jobs.rb
  google-cloud-dataproc-v1beta2/synth.metadata
  google-cloud-dataproc-v1beta2/test/google/cloud/dataproc/v1beta2/job_controller_operations_test.rb
  google-cloud-dataproc-v1beta2/test/google/cloud/dataproc/v1beta2/job_controller_test.rb
Labels: cla: yes

#5320 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/contexts/paths.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/paths.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/paths.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_types/paths.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/sessions/paths.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/context.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/webhook.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes

#5321 [CHANGE ME] Re-generated google-cloud-language-v1 to pick up changes in the API or client library generator.
  google-cloud-language-v1/proto_docs/google/cloud/language/v1/language_service.rb
  google-cloud-language-v1/synth.metadata
Labels: cla: yes

#5322 [CHANGE ME] Re-generated google-cloud-language-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-language-v1beta2/proto_docs/google/cloud/language/v1beta2/language_service.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes

#5323 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/log_entry.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/logging/v2/logging_config_services_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_services_pb.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#5326 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#5328 [CHANGE ME] Re-generated google-cloud-secret_manager-v1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1/proto_docs/google/cloud/secretmanager/v1/service.rb
  google-cloud-secret_manager-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-secret_manager-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes

#5329 [CHANGE ME] Re-generated google-cloud-vision-v1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1/proto_docs/google/cloud/vision/v1/image_annotator.rb
  google-cloud-vision-v1/synth.metadata
Labels: cla: yes

#5330 [CHANGE ME] Re-generated google-cloud-vision-v1p3beta1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1p3beta1/proto_docs/google/cloud/vision/v1p3beta1/image_annotator.rb
  google-cloud-vision-v1p3beta1/synth.metadata
Labels: cla: yes

#5336 Release google-cloud-secret_manager-v1 0.2.1
  google-cloud-secret_manager-v1/CHANGELOG.md
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/version.rb
Labels: autorelease: pending, cla: yes

#5332 chore: restore namespace compatibility for OsLogin, PhishingProtection, and RecaptchaEnterprise
  google-cloud-os_login/synth.py
  google-cloud-phishing_protection/synth.py
  google-cloud-recaptcha_enterprise/synth.py
Labels: cla: yes

#5338 Release google-cloud-dialogflow-v2 0.3.0
  google-cloud-dialogflow-v2/CHANGELOG.md
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/version.rb
Labels: autorelease: pending, cla: yes

#4825 Release google-cloud-storage 1.26.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: api: storage, autorelease: pending, cla: yes

#5344 Release google-cloud-data_catalog-v1 0.1.0
  google-cloud-data_catalog-v1/CHANGELOG.md
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/version.rb
Labels: autorelease: pending, cla: yes

#5345 Release google-cloud-data_catalog 0.1.0
  google-cloud-data_catalog/CHANGELOG.md
  google-cloud-data_catalog/lib/google/cloud/data_catalog/version.rb
Labels: autorelease: pending, cla: yes

#5378 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/Rakefile
  google-cloud-vision/synth.metadata
Labels: cla: yes

#5377 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/Rakefile
  google-cloud-speech/synth.metadata
Labels: cla: yes

#5376 [CHANGE ME] Re-generated google-cloud-service_directory to pick up changes in the API or client library generator.
  google-cloud-service_directory/Rakefile
  google-cloud-service_directory/synth.metadata
Labels: cla: yes

#5372 [CHANGE ME] Re-generated google-cloud-secret_manager to pick up changes in the API or client library generator.
  google-cloud-secret_manager/Rakefile
  google-cloud-secret_manager/synth.metadata
Labels: cla: yes

#5369 [CHANGE ME] Re-generated google-cloud-recommender to pick up changes in the API or client library generator.
  google-cloud-recommender/Rakefile
  google-cloud-recommender/synth.metadata
Labels: cla: yes

#5362 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/Rakefile
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#5359 [CHANGE ME] Re-generated google-cloud-data_catalog to pick up changes in the API or client library generator.
  google-cloud-data_catalog/Rakefile
  google-cloud-data_catalog/synth.metadata
Labels: cla: yes

#5357 [CHANGE ME] Re-generated google-cloud-billing to pick up changes in the API or client library generator.
  google-cloud-billing/Rakefile
  google-cloud-billing/synth.metadata
Labels: cla: yes

#5355 [CHANGE ME] Re-generated google-cloud-bigquery-storage to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage/Rakefile
  google-cloud-bigquery-storage/synth.metadata
Labels: cla: yes

#5380 chore: remove presubmits for samples on osx
  .kokoro/osx.sh
  .kokoro/samples_presubmit/osx/access_approval.cfg
  .kokoro/samples_presubmit/osx/asset.cfg
  .kokoro/samples_presubmit/osx/automl.cfg
  .kokoro/samples_presubmit/osx/bigquery-data_transfer.cfg
  .kokoro/samples_presubmit/osx/bigquery-storage.cfg
  .kokoro/samples_presubmit/osx/bigquery.cfg
  .kokoro/samples_presubmit/osx/bigtable.cfg
  .kokoro/samples_presubmit/osx/billing.cfg
  .kokoro/samples_presubmit/osx/common.cfg
  .kokoro/samples_presubmit/osx/container.cfg
  .kokoro/samples_presubmit/osx/container_analysis.cfg
  .kokoro/samples_presubmit/osx/core.cfg
  .kokoro/samples_presubmit/osx/data_catalog.cfg
  .kokoro/samples_presubmit/osx/dataproc.cfg
  .kokoro/samples_presubmit/osx/datastore.cfg
  .kokoro/samples_presubmit/osx/debugger.cfg
  .kokoro/samples_presubmit/osx/dialogflow.cfg
  .kokoro/samples_presubmit/osx/dlp.cfg
  .kokoro/samples_presubmit/osx/dns.cfg
  .kokoro/samples_presubmit/osx/env.cfg
  .kokoro/samples_presubmit/osx/error_reporting.cfg
  .kokoro/samples_presubmit/osx/errors.cfg
  .kokoro/samples_presubmit/osx/firestore.cfg
  .kokoro/samples_presubmit/osx/gcloud.cfg
  .kokoro/samples_presubmit/osx/google-cloud.cfg
  .kokoro/samples_presubmit/osx/grafeas-client.cfg
  .kokoro/samples_presubmit/osx/grafeas.cfg
  .kokoro/samples_presubmit/osx/irm.cfg
  .kokoro/samples_presubmit/osx/kms.cfg
  .kokoro/samples_presubmit/osx/language.cfg
  .kokoro/samples_presubmit/osx/logging.cfg
  .kokoro/samples_presubmit/osx/monitoring.cfg
  .kokoro/samples_presubmit/osx/os_login.cfg
  .kokoro/samples_presubmit/osx/phishing_protection.cfg
  .kokoro/samples_presubmit/osx/pubsub.cfg
  .kokoro/samples_presubmit/osx/recaptcha_enterprise.cfg
  .kokoro/samples_presubmit/osx/recommender.cfg
  .kokoro/samples_presubmit/osx/redis.cfg
  .kokoro/samples_presubmit/osx/resource_manager.cfg
  .kokoro/samples_presubmit/osx/scheduler.cfg
  .kokoro/samples_presubmit/osx/secret_manager.cfg
  .kokoro/samples_presubmit/osx/security_center.cfg
  .kokoro/samples_presubmit/osx/service_directory.cfg
  .kokoro/samples_presubmit/osx/spanner.cfg
  .kokoro/samples_presubmit/osx/speech.cfg
  .kokoro/samples_presubmit/osx/stackdriver-core.cfg
  .kokoro/samples_presubmit/osx/stackdriver.cfg
  .kokoro/samples_presubmit/osx/storage.cfg
  .kokoro/samples_presubmit/osx/talent.cfg
  .kokoro/samples_presubmit/osx/tasks.cfg
  .kokoro/samples_presubmit/osx/text_to_speech.cfg
  .kokoro/samples_presubmit/osx/trace.cfg
  .kokoro/samples_presubmit/osx/translate.cfg
  .kokoro/samples_presubmit/osx/video_intelligence.cfg
  .kokoro/samples_presubmit/osx/vision.cfg
  .kokoro/samples_presubmit/osx/webrisk.cfg
  rakelib/kokoro/kokoro_builder.rb
Labels: cla: yes

#5354 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/Rakefile
  google-cloud-asset/synth.metadata
Labels: cla: yes

#5351 [CHANGE ME] Re-generated google-cloud-access_approval to pick up changes in the API or client library generator.
  google-cloud-access_approval/Rakefile
  google-cloud-access_approval/synth.metadata
Labels: cla: yes

#5364 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/resources.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/service.rb
  google-cloud-kms/lib/google/cloud/kms/v1/resources_pb.rb
  google-cloud-kms/lib/google/cloud/kms/v1/service_pb.rb
  google-cloud-kms/lib/google/cloud/kms/v1/service_services_pb.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#5367 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/doc/google/cloud/phishingprotection/v1beta1/phishingprotection.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_client.rb
  google-cloud-phishing_protection/lib/google/cloud/phishingprotection/v1beta1/phishingprotection_pb.rb
  google-cloud-phishing_protection/lib/google/cloud/phishingprotection/v1beta1/phishingprotection_services_pb.rb
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#5368 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise_pb.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise_services_pb.rb
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#5366 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/cloud/oslogin/common/common.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/cloud/oslogin/v1/oslogin.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/cloud/oslogin/common.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/cloud/oslogin/common/common.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/cloud/oslogin/v1beta/oslogin.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/oslogin/common/common_pb.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1/oslogin_pb.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1/oslogin_services_pb.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1beta/oslogin_pb.rb
  google-cloud-os_login/lib/google/cloud/oslogin/v1beta/oslogin_services_pb.rb
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#5352 [CHANGE ME] Re-generated google-cloud-asset-v1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-asset-v1/synth.metadata
Labels: cla: yes

#5353 [CHANGE ME] Re-generated google-cloud-asset-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1beta1/proto_docs/google/iam/v1/policy.rb
  google-cloud-asset-v1beta1/proto_docs/google/type/expr.rb
  google-cloud-asset-v1beta1/synth.metadata
Labels: cla: yes

#5343 chore: fix kokoro samples permissions issue
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#5382 chore: Restore namespace compatibility for WebRisk, Container, and Bigquery-DataTransfer
  google-cloud-bigquery-data_transfer/synth.py
  google-cloud-container/synth.py
  google-cloud-webrisk/synth.py
Labels: cla: yes

#5396 chore: delay broken link checker another week
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#5361 [CHANGE ME] Re-generated google-cloud-dataproc-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/cluster_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/clusters_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/clusters_services_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/jobs_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/shared_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_template_service/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_templates_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_templates_services_pb.rb
  google-cloud-dataproc-v1beta2/proto_docs/google/cloud/dataproc/v1beta2/clusters.rb
  google-cloud-dataproc-v1beta2/proto_docs/google/cloud/dataproc/v1beta2/jobs.rb
  google-cloud-dataproc-v1beta2/proto_docs/google/cloud/dataproc/v1beta2/shared.rb
  google-cloud-dataproc-v1beta2/proto_docs/google/cloud/dataproc/v1beta2/workflow_templates.rb
  google-cloud-dataproc-v1beta2/synth.metadata
Labels: cla: yes

#5360 [CHANGE ME] Re-generated google-cloud-dataproc-v1 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/autoscaling_policy_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/clusters_services_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/operations.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/jobs_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/jobs_services_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/shared_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_templates_pb.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/autoscaling_policies.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/shared.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/workflow_templates.rb
  google-cloud-dataproc-v1/synth.metadata
  google-cloud-dataproc-v1/test/google/cloud/dataproc/v1/job_controller_operations_test.rb
  google-cloud-dataproc-v1/test/google/cloud/dataproc/v1/job_controller_test.rb
Labels: cla: yes

#5387 Release google-cloud-os_login 0.7.0
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes

#5388 Release google-cloud-phishing_protection 0.5.0
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes

#5389 Release google-cloud-recaptcha_enterprise 0.6.0
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes

#5390 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/datasource.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/datatransfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/datatransfer_pb.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/datatransfer_services_pb.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/datatransfer/v1/transfer_pb.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#5391 [CHANGE ME] Re-generated google-cloud-bigquery-storage-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage-v1/proto_docs/google/cloud/bigquery/storage/v1/arrow.rb
  google-cloud-bigquery-storage-v1/synth.metadata
Labels: cla: yes

#5392 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/lib/google/container/v1/cluster_service_pb.rb
  google-cloud-container/lib/google/container/v1/cluster_service_services_pb.rb
  google-cloud-container/lib/google/container/v1beta1/cluster_service_pb.rb
  google-cloud-container/lib/google/container/v1beta1/cluster_service_services_pb.rb
  google-cloud-container/synth.metadata
Labels: cla: yes

#5394 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/webrisk_pb.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/webrisk_services_pb.rb
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#5395 [CHANGE ME] Re-generated grafeas to pick up changes in the API or client library generator.
  grafeas/lib/grafeas/v1/grafeas_client.rb
  grafeas/lib/grafeas/v1/grafeas_client_config.json
  grafeas/synth.metadata
  grafeas/test/grafeas/v1/grafeas_client_test.rb
Labels: cla: yes

#5381 Release google-cloud-kms 1.6.0
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes

#5397 chore: run samples presubmits against master gem versions
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#5401 chore(secret_manager-v1): reenable context-aware-commits
  google-cloud-secret_manager-v1/synth.py
Labels: cla: yes

#5406 test(pubsub): Add acceptance test for endpoint (host)
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
Labels: api: pubsub, cla: yes

#5383 chore: add asset samples
  .kokoro/build.bat
  google-cloud-asset/samples/Gemfile
  google-cloud-asset/samples/Rakefile
  google-cloud-asset/samples/acceptance/helper.rb
  google-cloud-asset/samples/acceptance/quickstart_test.rb
  google-cloud-asset/samples/quickstart.rb
Labels: cla: yes, do not merge

#5402 Release google-cloud-bigquery-storage-v1 0.1.2
  google-cloud-bigquery-storage-v1/CHANGELOG.md
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/version.rb
Labels: autorelease: pending, cla: yes

#5403 Release google-cloud-bigquery-data_transfer 0.9.0
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes

#5399 docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc-v1/synth.metadata
Labels: cla: yes

#5398 docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1/doc/google/container/v1/cluster_service.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/doc/google/container/v1beta1/cluster_service.rb
  google-cloud-container/lib/google/container/v1/cluster_service_services_pb.rb
  google-cloud-container/lib/google/container/v1beta1/cluster_service_services_pb.rb
  google-cloud-container/synth.metadata
Labels: cla: yes

#5400 docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-dataproc-v1beta2/proto_docs/google/cloud/dataproc/v1beta2/clusters.rb
  google-cloud-dataproc-v1beta2/synth.metadata
Labels: cla: yes

#5407 chore: restore namespace compatibility for Monitoring and TextToSpeech
  google-cloud-monitoring/synth.py
  google-cloud-text_to_speech/synth.py
Labels: cla: yes

#5408 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1/doc/google/container/v1/cluster_service.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/doc/google/container/v1beta1/cluster_service.rb
  google-cloud-container/synth.metadata
Labels: cla: yes

#5409 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/common_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/dashboard_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/dashboards_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/dashboards_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/drilldowns_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/layouts_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/metrics_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/scorecard_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/text_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/widget_pb.rb
  google-cloud-monitoring/lib/google/monitoring/dashboard/v1/xychart_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/alert_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/alert_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/alert_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/common_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/dropped_labels_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/group_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/group_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/group_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/mutation_record_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/service_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/service_service_services_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/span_context_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_service_services_pb.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#5410 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/doc/google/cloud/texttospeech/v1/cloud_tts.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/doc/google/cloud/texttospeech/v1beta1/cloud_tts.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1/cloud_tts_pb.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1/cloud_tts_services_pb.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1beta1/cloud_tts_pb.rb
  google-cloud-text_to_speech/lib/google/cloud/texttospeech/v1beta1/cloud_tts_services_pb.rb
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#5405 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/firestore_admin_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/firestore_admin_client_config.json
  google-cloud-firestore/lib/google/cloud/firestore/service.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client_config.json
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client_config.json
  google-cloud-firestore/support/doctest_helper.rb
  google-cloud-firestore/synth.metadata
  google-cloud-firestore/test/google/cloud/firestore/admin/v1/firestore_admin_client_test.rb
  google-cloud-firestore/test/google/cloud/firestore/batch/create_test.rb
  google-cloud-firestore/test/google/cloud/firestore/batch/delete_test.rb
  google-cloud-firestore/test/google/cloud/firestore/batch/set_test.rb
  google-cloud-firestore/test/google/cloud/firestore/batch/update_test.rb
  google-cloud-firestore/test/google/cloud/firestore/batch/values_test.rb
  google-cloud-firestore/test/google/cloud/firestore/client/batch_test.rb
  google-cloud-firestore/test/google/cloud/firestore/client/get_all_test.rb
  google-cloud-firestore/test/google/cloud/firestore/client/transaction_test.rb
  google-cloud-firestore/test/google/cloud/firestore/collection_reference/add_test.rb
  google-cloud-firestore/test/google/cloud/firestore/conformance_test.rb
  google-cloud-firestore/test/google/cloud/firestore/document_reference/create_test.rb
  google-cloud-firestore/test/google/cloud/firestore/document_reference/delete_test.rb
  google-cloud-firestore/test/google/cloud/firestore/document_reference/get_test.rb
  google-cloud-firestore/test/google/cloud/firestore/document_reference/set_test.rb
  google-cloud-firestore/test/google/cloud/firestore/document_reference/update_test.rb
  google-cloud-firestore/test/google/cloud/firestore/document_reference/values_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/closed/get_all_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/create_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/delete_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/empty/get_all_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/empty/get_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/get_all_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/get_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/set_test.rb
  google-cloud-firestore/test/google/cloud/firestore/transaction/update_test.rb
  google-cloud-firestore/test/google/cloud/firestore/v1/firestore_client_test.rb
  google-cloud-firestore/test/google/cloud/firestore/v1beta1/firestore_client_test.rb
Labels: api: firestore, cla: yes, do not merge

#5404 Release google-cloud-container 0.11.0
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes

#5411 Release google-cloud-text_to_speech 0.7.0
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/version.rb
Labels: autorelease: pending, cla: yes

#5426 [CHANGE ME] Re-generated google-cloud-access_approval to pick up changes in the API or client library generator.
  google-cloud-access_approval/README.md
  google-cloud-access_approval/lib/google-cloud-access_approval.rb
  google-cloud-access_approval/lib/google/cloud/access_approval.rb
  google-cloud-access_approval/synth.metadata
Labels: cla: yes

#5429 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/README.md
  google-cloud-asset/lib/google-cloud-asset.rb
  google-cloud-asset/lib/google/cloud/asset.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#5434 [CHANGE ME] Re-generated google-cloud-bigquery-storage to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage/README.md
  google-cloud-bigquery-storage/lib/google-cloud-bigquery-storage.rb
  google-cloud-bigquery-storage/lib/google/cloud/bigquery/storage.rb
  google-cloud-bigquery-storage/synth.metadata
Labels: cla: yes

#5467 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/README.md
  google-cloud-vision/lib/google-cloud-vision.rb
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#5464 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/AUTHENTICATION.md
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/synth.metadata
  google-cloud-talent/test/google/cloud/talent/v4beta1/company_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/job_service_client_test.rb
Labels: cla: yes

#5463 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/README.md
  google-cloud-speech/lib/google-cloud-speech.rb
  google-cloud-speech/lib/google/cloud/speech.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#5460 [CHANGE ME] Re-generated google-cloud-service_directory to pick up changes in the API or client library generator.
  google-cloud-service_directory/README.md
  google-cloud-service_directory/lib/google-cloud-service_directory.rb
  google-cloud-service_directory/lib/google/cloud/service_directory.rb
  google-cloud-service_directory/synth.metadata
Labels: cla: yes

#5458 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/README.md
  google-cloud-security_center/lib/google-cloud-security_center.rb
  google-cloud-security_center/lib/google/cloud/security_center.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#5455 [CHANGE ME] Re-generated google-cloud-secret_manager to pick up changes in the API or client library generator.
  google-cloud-secret_manager/README.md
  google-cloud-secret_manager/lib/google-cloud-secret_manager.rb
  google-cloud-secret_manager/lib/google/cloud/secret_manager.rb
  google-cloud-secret_manager/synth.metadata
Labels: cla: yes

#5452 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/README.md
  google-cloud-redis/lib/google-cloud-redis.rb
  google-cloud-redis/lib/google/cloud/redis.rb
  google-cloud-redis/synth.metadata
Labels: cla: yes

#5449 [CHANGE ME] Re-generated google-cloud-recommender to pick up changes in the API or client library generator.
  google-cloud-recommender/README.md
  google-cloud-recommender/lib/google-cloud-recommender.rb
  google-cloud-recommender/lib/google/cloud/recommender.rb
  google-cloud-recommender/synth.metadata
Labels: cla: yes
