Repository googleapis/google-cloud-ruby, pull requests merged in 2020-11, with the labels that each got.

#8080 feat: Initial generation of google-cloud-workflows-executions-v1beta
  .kokoro/continuous/linux/workflows-executions-v1beta.cfg
  .kokoro/continuous/osx/workflows-executions-v1beta.cfg
  .kokoro/continuous/windows/workflows-executions-v1beta.cfg
  .kokoro/nightly/linux/workflows-executions-v1beta.cfg
  .kokoro/nightly/osx/workflows-executions-v1beta.cfg
  .kokoro/nightly/windows/workflows-executions-v1beta.cfg
  .kokoro/release/workflows-executions-v1beta.cfg
  Gemfile
  google-cloud-workflows-executions-v1beta/.gitignore
  google-cloud-workflows-executions-v1beta/.repo-metadata.json
  google-cloud-workflows-executions-v1beta/.rubocop.yml
  google-cloud-workflows-executions-v1beta/.yardopts
  google-cloud-workflows-executions-v1beta/AUTHENTICATION.md
  google-cloud-workflows-executions-v1beta/CHANGELOG.md
  google-cloud-workflows-executions-v1beta/Gemfile
  google-cloud-workflows-executions-v1beta/LICENSE.md
  google-cloud-workflows-executions-v1beta/README.md
  google-cloud-workflows-executions-v1beta/Rakefile
  google-cloud-workflows-executions-v1beta/google-cloud-workflows-executions-v1beta.gemspec
  google-cloud-workflows-executions-v1beta/lib/google-cloud-workflows-executions-v1beta.rb
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta.rb
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/executions.rb
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/executions/client.rb
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/executions/credentials.rb
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/executions/paths.rb
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/executions_pb.rb
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/executions_services_pb.rb
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/version.rb
  google-cloud-workflows-executions-v1beta/proto_docs/README.md
  google-cloud-workflows-executions-v1beta/proto_docs/google/api/field_behavior.rb
  google-cloud-workflows-executions-v1beta/proto_docs/google/api/resource.rb
  google-cloud-workflows-executions-v1beta/proto_docs/google/cloud/workflows/executions/v1beta/executions.rb
  google-cloud-workflows-executions-v1beta/proto_docs/google/protobuf/timestamp.rb
  google-cloud-workflows-executions-v1beta/synth.metadata
  google-cloud-workflows-executions-v1beta/synth.py
  google-cloud-workflows-executions-v1beta/test/google/cloud/workflows/executions/v1beta/executions_paths_test.rb
  google-cloud-workflows-executions-v1beta/test/google/cloud/workflows/executions/v1beta/executions_test.rb
  google-cloud-workflows-executions-v1beta/test/helper.rb
Labels: cla: yes

#8083 Release google-cloud-workflows-executions-v1beta 0.1.0
  google-cloud-workflows-executions-v1beta/CHANGELOG.md
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/version.rb
Labels: autorelease: pending, cla: yes

#8065 Release google-analytics-admin-v1alpha 0.2.1
  google-analytics-admin-v1alpha/CHANGELOG.md
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/version.rb
Labels: autorelease: pending, cla: yes

#8077 Release google-cloud-billing-budgets-v1beta1 0.3.0
  google-cloud-billing-budgets-v1beta1/CHANGELOG.md
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#8081 Release google-cloud-asset-v1 0.8.0
  google-cloud-asset-v1/CHANGELOG.md
  google-cloud-asset-v1/lib/google/cloud/asset/v1/version.rb
Labels: autorelease: pending, cla: yes

#8087 chore: start tracking obsolete files
  google-cloud-workflows-executions-v1beta/synth.metadata
Labels: cla: yes, context: full

#8090 Release google-cloud-workflows 0.2.0
  google-cloud-workflows/CHANGELOG.md
  google-cloud-workflows/lib/google/cloud/workflows/version.rb
Labels: autorelease: pending, cla: yes

#8086 [google-analytics-data-v1alpha] docs: App+Web properties renamed to GA4
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/client.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_services_pb.rb
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/analytics_data_api.rb
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/data.rb
  google-analytics-data-v1alpha/synth.metadata
Labels: cla: yes, context: full

#8093 chore: start tracking obsolete files
  google-cloud-workflows/synth.metadata
Labels: cla: yes, context: full

#8085 chore(bigquery): Fix expectations in samples list_datasets_test
  google-cloud-bigquery/samples/snippets/acceptance/list_datasets_test.rb
Labels: api: bigquery, cla: yes

#8094 Release google-analytics-data-v1alpha 0.3.1
  google-analytics-data-v1alpha/CHANGELOG.md
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/version.rb
Labels: autorelease: pending, cla: yes

#8091 feat: Initial generation of google-cloud-media_translation-v1beta1
  .kokoro/continuous/linux/media_translation-v1beta1.cfg
  .kokoro/continuous/osx/media_translation-v1beta1.cfg
  .kokoro/continuous/windows/media_translation-v1beta1.cfg
  .kokoro/nightly/linux/media_translation-v1beta1.cfg
  .kokoro/nightly/osx/media_translation-v1beta1.cfg
  .kokoro/nightly/windows/media_translation-v1beta1.cfg
  .kokoro/release/media_translation-v1beta1.cfg
  Gemfile
  google-cloud-media_translation-v1beta1/.gitignore
  google-cloud-media_translation-v1beta1/.repo-metadata.json
  google-cloud-media_translation-v1beta1/.rubocop.yml
  google-cloud-media_translation-v1beta1/.yardopts
  google-cloud-media_translation-v1beta1/AUTHENTICATION.md
  google-cloud-media_translation-v1beta1/CHANGELOG.md
  google-cloud-media_translation-v1beta1/Gemfile
  google-cloud-media_translation-v1beta1/LICENSE.md
  google-cloud-media_translation-v1beta1/README.md
  google-cloud-media_translation-v1beta1/Rakefile
  google-cloud-media_translation-v1beta1/google-cloud-media_translation-v1beta1.gemspec
  google-cloud-media_translation-v1beta1/lib/google-cloud-media_translation-v1beta1.rb
  google-cloud-media_translation-v1beta1/lib/google/cloud/media_translation/v1beta1.rb
  google-cloud-media_translation-v1beta1/lib/google/cloud/media_translation/v1beta1/speech_translation_service.rb
  google-cloud-media_translation-v1beta1/lib/google/cloud/media_translation/v1beta1/speech_translation_service/client.rb
  google-cloud-media_translation-v1beta1/lib/google/cloud/media_translation/v1beta1/speech_translation_service/credentials.rb
  google-cloud-media_translation-v1beta1/lib/google/cloud/media_translation/v1beta1/version.rb
  google-cloud-media_translation-v1beta1/lib/google/cloud/mediatranslation/v1beta1/media_translation_pb.rb
  google-cloud-media_translation-v1beta1/lib/google/cloud/mediatranslation/v1beta1/media_translation_services_pb.rb
  google-cloud-media_translation-v1beta1/proto_docs/README.md
  google-cloud-media_translation-v1beta1/proto_docs/google/api/field_behavior.rb
  google-cloud-media_translation-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-media_translation-v1beta1/proto_docs/google/cloud/mediatranslation/v1beta1/media_translation.rb
  google-cloud-media_translation-v1beta1/proto_docs/google/protobuf/any.rb
  google-cloud-media_translation-v1beta1/proto_docs/google/rpc/status.rb
  google-cloud-media_translation-v1beta1/synth.metadata
  google-cloud-media_translation-v1beta1/synth.py
  google-cloud-media_translation-v1beta1/test/google/cloud/media_translation/v1beta1/speech_translation_service_test.rb
  google-cloud-media_translation-v1beta1/test/helper.rb
Labels: cla: yes

#8089 feat(bigquery): Add routine (UDF) to Dataset::Access
  google-cloud-bigquery/acceptance/bigquery/dataset_access_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset/access.rb
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_access_test.rb
Labels: api: bigquery, cla: yes

#8099 [google-analytics-data-v1alpha] feat: added RunRealtimeReport method that returns a customized report of realtime event data for a GA4 property docs: minor documentation updates
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/client.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_pb.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_services_pb.rb
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/analytics_data_api.rb
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/data.rb
  google-analytics-data-v1alpha/synth.metadata
  google-analytics-data-v1alpha/test/google/analytics/data/v1alpha/analytics_data_test.rb
Labels: cla: yes, context: full

#8100 chore: start tracking obsolete files
  google-cloud-media_translation-v1beta1/synth.metadata
Labels: cla: yes, context: full

#8101 chore: start tracking obsolete files
  google-cloud-recommendation_engine-v1beta1/synth.metadata
Labels: cla: yes, context: full

#8096 feat: Initial generation of google-cloud-web_security_scanner-v1beta
  .kokoro/continuous/linux/web_security_scanner-v1beta.cfg
  .kokoro/continuous/osx/web_security_scanner-v1beta.cfg
  .kokoro/continuous/windows/web_security_scanner-v1beta.cfg
  .kokoro/nightly/linux/web_security_scanner-v1beta.cfg
  .kokoro/nightly/osx/web_security_scanner-v1beta.cfg
  .kokoro/nightly/windows/web_security_scanner-v1beta.cfg
  .kokoro/release/web_security_scanner-v1beta.cfg
  Gemfile
  google-cloud-web_security_scanner-v1beta/.gitignore
  google-cloud-web_security_scanner-v1beta/.repo-metadata.json
  google-cloud-web_security_scanner-v1beta/.rubocop.yml
  google-cloud-web_security_scanner-v1beta/.yardopts
  google-cloud-web_security_scanner-v1beta/AUTHENTICATION.md
  google-cloud-web_security_scanner-v1beta/CHANGELOG.md
  google-cloud-web_security_scanner-v1beta/Gemfile
  google-cloud-web_security_scanner-v1beta/LICENSE.md
  google-cloud-web_security_scanner-v1beta/README.md
  google-cloud-web_security_scanner-v1beta/Rakefile
  google-cloud-web_security_scanner-v1beta/google-cloud-web_security_scanner-v1beta.gemspec
  google-cloud-web_security_scanner-v1beta/lib/google-cloud-web_security_scanner-v1beta.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/web_security_scanner/v1beta.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/web_security_scanner/v1beta/version.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/web_security_scanner/v1beta/web_security_scanner.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/web_security_scanner/v1beta/web_security_scanner/client.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/web_security_scanner/v1beta/web_security_scanner/credentials.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/web_security_scanner/v1beta/web_security_scanner/paths.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/crawled_url_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/finding_addon_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/finding_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/finding_type_stats_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/scan_config_error_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/scan_config_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/scan_run_error_trace_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/scan_run_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/scan_run_warning_trace_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/web_security_scanner_pb.rb
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/websecurityscanner/v1beta/web_security_scanner_services_pb.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/README.md
  google-cloud-web_security_scanner-v1beta/proto_docs/google/api/field_behavior.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/api/resource.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/crawled_url.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/finding.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/finding_addon.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/finding_type_stats.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/scan_config.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/scan_config_error.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/scan_run.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/scan_run_error_trace.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/scan_run_warning_trace.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/cloud/websecurityscanner/v1beta/web_security_scanner.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/protobuf/empty.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/protobuf/field_mask.rb
  google-cloud-web_security_scanner-v1beta/proto_docs/google/protobuf/timestamp.rb
  google-cloud-web_security_scanner-v1beta/synth.metadata
  google-cloud-web_security_scanner-v1beta/synth.py
  google-cloud-web_security_scanner-v1beta/test/google/cloud/web_security_scanner/v1beta/web_security_scanner_paths_test.rb
  google-cloud-web_security_scanner-v1beta/test/google/cloud/web_security_scanner/v1beta/web_security_scanner_test.rb
  google-cloud-web_security_scanner-v1beta/test/helper.rb
Labels: cla: yes

#8102 Release google-analytics-data-v1alpha 0.4.0
  google-analytics-data-v1alpha/CHANGELOG.md
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/version.rb
Labels: autorelease: pending, cla: yes

#8095 feat: Initial generation of google-cloud-web_security_scanner-v1
  .kokoro/continuous/linux/web_security_scanner-v1.cfg
  .kokoro/continuous/osx/web_security_scanner-v1.cfg
  .kokoro/continuous/windows/web_security_scanner-v1.cfg
  .kokoro/nightly/linux/web_security_scanner-v1.cfg
  .kokoro/nightly/osx/web_security_scanner-v1.cfg
  .kokoro/nightly/windows/web_security_scanner-v1.cfg
  .kokoro/release/web_security_scanner-v1.cfg
  Gemfile
  google-cloud-web_security_scanner-v1/.gitignore
  google-cloud-web_security_scanner-v1/.repo-metadata.json
  google-cloud-web_security_scanner-v1/.rubocop.yml
  google-cloud-web_security_scanner-v1/.yardopts
  google-cloud-web_security_scanner-v1/AUTHENTICATION.md
  google-cloud-web_security_scanner-v1/CHANGELOG.md
  google-cloud-web_security_scanner-v1/Gemfile
  google-cloud-web_security_scanner-v1/LICENSE.md
  google-cloud-web_security_scanner-v1/README.md
  google-cloud-web_security_scanner-v1/Rakefile
  google-cloud-web_security_scanner-v1/google-cloud-web_security_scanner-v1.gemspec
  google-cloud-web_security_scanner-v1/lib/google-cloud-web_security_scanner-v1.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/web_security_scanner/v1.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/web_security_scanner/v1/version.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/web_security_scanner/v1/web_security_scanner.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/web_security_scanner/v1/web_security_scanner/client.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/web_security_scanner/v1/web_security_scanner/credentials.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/crawled_url_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/finding_addon_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/finding_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/finding_type_stats_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/scan_config_error_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/scan_config_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/scan_run_error_trace_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/scan_run_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/scan_run_warning_trace_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/web_security_scanner_pb.rb
  google-cloud-web_security_scanner-v1/lib/google/cloud/websecurityscanner/v1/web_security_scanner_services_pb.rb
  google-cloud-web_security_scanner-v1/proto_docs/README.md
  google-cloud-web_security_scanner-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/api/resource.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/crawled_url.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/finding.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/finding_addon.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/finding_type_stats.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/scan_config.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/scan_config_error.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/scan_run.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/scan_run_error_trace.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/scan_run_warning_trace.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/cloud/websecurityscanner/v1/web_security_scanner.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-web_security_scanner-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-web_security_scanner-v1/synth.metadata
  google-cloud-web_security_scanner-v1/synth.py
  google-cloud-web_security_scanner-v1/test/google/cloud/web_security_scanner/v1/web_security_scanner_test.rb
  google-cloud-web_security_scanner-v1/test/helper.rb
Labels: cla: yes

#8108 chore: start tracking obsolete files
  google-cloud-artifact_registry-v1beta2/synth.metadata
Labels: cla: yes, context: full

#8109 chore: start tracking obsolete files
  google-cloud-web_security_scanner-v1/synth.metadata
Labels: cla: yes, context: full

#8110 chore: start tracking obsolete files
  google-cloud-web_security_scanner-v1beta/synth.metadata
Labels: cla: yes, context: full

#8107 [google-analytics-admin-v1alpha] fix: 'requests' field of CreateUserLink, UpdateUserLink, DeleteUserLink methods is now required docs: minor documentation updates
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service/client.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/resources_pb.rb
  google-analytics-admin-v1alpha/proto_docs/google/analytics/admin/v1alpha/analytics_admin.rb
  google-analytics-admin-v1alpha/proto_docs/google/analytics/admin/v1alpha/resources.rb
  google-analytics-admin-v1alpha/synth.metadata
Labels: cla: yes, context: full

#8103 feat: Initial generation of google-iam-v1beta
  .kokoro/continuous/linux/google-iam-v1beta.cfg
  .kokoro/continuous/osx/google-iam-v1beta.cfg
  .kokoro/continuous/windows/google-iam-v1beta.cfg
  .kokoro/nightly/linux/google-iam-v1beta.cfg
  .kokoro/nightly/osx/google-iam-v1beta.cfg
  .kokoro/nightly/windows/google-iam-v1beta.cfg
  .kokoro/release/google-iam-v1beta.cfg
  Gemfile
  google-iam-v1beta/.gitignore
  google-iam-v1beta/.repo-metadata.json
  google-iam-v1beta/.rubocop.yml
  google-iam-v1beta/.yardopts
  google-iam-v1beta/AUTHENTICATION.md
  google-iam-v1beta/CHANGELOG.md
  google-iam-v1beta/Gemfile
  google-iam-v1beta/LICENSE.md
  google-iam-v1beta/README.md
  google-iam-v1beta/Rakefile
  google-iam-v1beta/google-iam-v1beta.gemspec
  google-iam-v1beta/lib/google-iam-v1beta.rb
  google-iam-v1beta/lib/google/iam/v1beta.rb
  google-iam-v1beta/lib/google/iam/v1beta/version.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pool_pb.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pool_services_pb.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/client.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/credentials.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/operations.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/paths.rb
  google-iam-v1beta/proto_docs/README.md
  google-iam-v1beta/proto_docs/google/api/field_behavior.rb
  google-iam-v1beta/proto_docs/google/api/resource.rb
  google-iam-v1beta/proto_docs/google/iam/v1beta/workload_identity_pool.rb
  google-iam-v1beta/proto_docs/google/longrunning/operations.rb
  google-iam-v1beta/proto_docs/google/protobuf/any.rb
  google-iam-v1beta/proto_docs/google/protobuf/empty.rb
  google-iam-v1beta/proto_docs/google/protobuf/field_mask.rb
  google-iam-v1beta/proto_docs/google/rpc/status.rb
  google-iam-v1beta/synth.metadata
  google-iam-v1beta/synth.py
  google-iam-v1beta/test/google/iam/v1beta/workload_identity_pools_operations_test.rb
  google-iam-v1beta/test/google/iam/v1beta/workload_identity_pools_paths_test.rb
  google-iam-v1beta/test/google/iam/v1beta/workload_identity_pools_test.rb
  google-iam-v1beta/test/helper.rb
Labels: cla: yes

#8104 feat: Initial generation of google-cloud-binary_authorization-v1beta1
  .kokoro/continuous/linux/binary_authorization-v1beta1.cfg
  .kokoro/continuous/osx/binary_authorization-v1beta1.cfg
  .kokoro/continuous/windows/binary_authorization-v1beta1.cfg
  .kokoro/nightly/linux/binary_authorization-v1beta1.cfg
  .kokoro/nightly/osx/binary_authorization-v1beta1.cfg
  .kokoro/nightly/windows/binary_authorization-v1beta1.cfg
  .kokoro/release/binary_authorization-v1beta1.cfg
  Gemfile
  google-cloud-binary_authorization-v1beta1/.gitignore
  google-cloud-binary_authorization-v1beta1/.repo-metadata.json
  google-cloud-binary_authorization-v1beta1/.rubocop.yml
  google-cloud-binary_authorization-v1beta1/.yardopts
  google-cloud-binary_authorization-v1beta1/AUTHENTICATION.md
  google-cloud-binary_authorization-v1beta1/CHANGELOG.md
  google-cloud-binary_authorization-v1beta1/Gemfile
  google-cloud-binary_authorization-v1beta1/LICENSE.md
  google-cloud-binary_authorization-v1beta1/README.md
  google-cloud-binary_authorization-v1beta1/Rakefile
  google-cloud-binary_authorization-v1beta1/google-cloud-binary_authorization-v1beta1.gemspec
  google-cloud-binary_authorization-v1beta1/lib/google-cloud-binary_authorization-v1beta1.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binary_authorization/v1beta1.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binary_authorization/v1beta1/binauthz_management_service.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binary_authorization/v1beta1/binauthz_management_service/client.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binary_authorization/v1beta1/binauthz_management_service/credentials.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binary_authorization/v1beta1/binauthz_management_service/paths.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binary_authorization/v1beta1/version.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binaryauthorization/v1beta1/resources_pb.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binaryauthorization/v1beta1/service_pb.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binaryauthorization/v1beta1/service_services_pb.rb
  google-cloud-binary_authorization-v1beta1/proto_docs/README.md
  google-cloud-binary_authorization-v1beta1/proto_docs/google/api/field_behavior.rb
  google-cloud-binary_authorization-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-binary_authorization-v1beta1/proto_docs/google/cloud/binaryauthorization/v1beta1/resources.rb
  google-cloud-binary_authorization-v1beta1/proto_docs/google/cloud/binaryauthorization/v1beta1/service.rb
  google-cloud-binary_authorization-v1beta1/proto_docs/google/protobuf/empty.rb
  google-cloud-binary_authorization-v1beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-binary_authorization-v1beta1/synth.metadata
  google-cloud-binary_authorization-v1beta1/synth.py
  google-cloud-binary_authorization-v1beta1/test/google/cloud/binary_authorization/v1beta1/binauthz_management_service_paths_test.rb
  google-cloud-binary_authorization-v1beta1/test/google/cloud/binary_authorization/v1beta1/binauthz_management_service_test.rb
  google-cloud-binary_authorization-v1beta1/test/helper.rb
Labels: cla: yes

#8105 feat: Initial generation of google-cloud-service_control-v1
  .kokoro/continuous/linux/service_control-v1.cfg
  .kokoro/continuous/osx/service_control-v1.cfg
  .kokoro/continuous/windows/service_control-v1.cfg
  .kokoro/nightly/linux/service_control-v1.cfg
  .kokoro/nightly/osx/service_control-v1.cfg
  .kokoro/nightly/windows/service_control-v1.cfg
  .kokoro/release/service_control-v1.cfg
  Gemfile
  google-cloud-service_control-v1/.gitignore
  google-cloud-service_control-v1/.repo-metadata.json
  google-cloud-service_control-v1/.rubocop.yml
  google-cloud-service_control-v1/.yardopts
  google-cloud-service_control-v1/AUTHENTICATION.md
  google-cloud-service_control-v1/CHANGELOG.md
  google-cloud-service_control-v1/Gemfile
  google-cloud-service_control-v1/LICENSE.md
  google-cloud-service_control-v1/README.md
  google-cloud-service_control-v1/Rakefile
  google-cloud-service_control-v1/google-cloud-service_control-v1.gemspec
  google-cloud-service_control-v1/lib/google-cloud-service_control-v1.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/check_error_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/distribution_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/http_request_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/log_entry_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/metric_value_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/operation_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/quota_controller_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/quota_controller_services_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/service_controller_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/service_controller_services_pb.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/quota_controller.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/quota_controller/client.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/quota_controller/credentials.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/service_controller.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/service_controller/client.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/service_controller/credentials.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/version.rb
  google-cloud-service_control-v1/proto_docs/README.md
  google-cloud-service_control-v1/proto_docs/google/api/resource.rb
  google-cloud-service_control-v1/proto_docs/google/api/servicecontrol/v1/check_error.rb
  google-cloud-service_control-v1/proto_docs/google/api/servicecontrol/v1/distribution.rb
  google-cloud-service_control-v1/proto_docs/google/api/servicecontrol/v1/http_request.rb
  google-cloud-service_control-v1/proto_docs/google/api/servicecontrol/v1/log_entry.rb
  google-cloud-service_control-v1/proto_docs/google/api/servicecontrol/v1/metric_value.rb
  google-cloud-service_control-v1/proto_docs/google/api/servicecontrol/v1/operation.rb
  google-cloud-service_control-v1/proto_docs/google/api/servicecontrol/v1/quota_controller.rb
  google-cloud-service_control-v1/proto_docs/google/api/servicecontrol/v1/service_controller.rb
  google-cloud-service_control-v1/proto_docs/google/logging/type/log_severity.rb
  google-cloud-service_control-v1/proto_docs/google/protobuf/any.rb
  google-cloud-service_control-v1/proto_docs/google/protobuf/duration.rb
  google-cloud-service_control-v1/proto_docs/google/protobuf/struct.rb
  google-cloud-service_control-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-service_control-v1/proto_docs/google/rpc/status.rb
  google-cloud-service_control-v1/synth.metadata
  google-cloud-service_control-v1/synth.py
  google-cloud-service_control-v1/test/google/cloud/service_control/v1/quota_controller_test.rb
  google-cloud-service_control-v1/test/google/cloud/service_control/v1/service_controller_test.rb
  google-cloud-service_control-v1/test/helper.rb
Labels: cla: yes

#8106 feat: Initial generation of google-cloud-document_ai-v1beta3
  .kokoro/continuous/linux/document_ai-v1beta3.cfg
  .kokoro/continuous/osx/document_ai-v1beta3.cfg
  .kokoro/continuous/windows/document_ai-v1beta3.cfg
  .kokoro/nightly/linux/document_ai-v1beta3.cfg
  .kokoro/nightly/osx/document_ai-v1beta3.cfg
  .kokoro/nightly/windows/document_ai-v1beta3.cfg
  .kokoro/release/document_ai-v1beta3.cfg
  Gemfile
  google-cloud-document_ai-v1beta3/.gitignore
  google-cloud-document_ai-v1beta3/.repo-metadata.json
  google-cloud-document_ai-v1beta3/.rubocop.yml
  google-cloud-document_ai-v1beta3/.yardopts
  google-cloud-document_ai-v1beta3/AUTHENTICATION.md
  google-cloud-document_ai-v1beta3/CHANGELOG.md
  google-cloud-document_ai-v1beta3/Gemfile
  google-cloud-document_ai-v1beta3/LICENSE.md
  google-cloud-document_ai-v1beta3/README.md
  google-cloud-document_ai-v1beta3/Rakefile
  google-cloud-document_ai-v1beta3/google-cloud-document_ai-v1beta3.gemspec
  google-cloud-document_ai-v1beta3/lib/google-cloud-document_ai-v1beta3.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service/client.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service/credentials.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service/operations.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service/paths.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/version.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/documentai/v1beta3/document_pb.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/documentai/v1beta3/document_processor_service_pb.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/documentai/v1beta3/document_processor_service_services_pb.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/documentai/v1beta3/geometry_pb.rb
  google-cloud-document_ai-v1beta3/proto_docs/README.md
  google-cloud-document_ai-v1beta3/proto_docs/google/api/field_behavior.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/api/resource.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/cloud/documentai/v1beta3/document.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/cloud/documentai/v1beta3/document_processor_service.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/cloud/documentai/v1beta3/geometry.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/longrunning/operations.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/protobuf/any.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/protobuf/duration.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/protobuf/empty.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/protobuf/field_mask.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/protobuf/timestamp.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/protobuf/wrappers.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/rpc/status.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/type/color.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/type/date.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/type/datetime.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/type/money.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/type/postal_address.rb
  google-cloud-document_ai-v1beta3/synth.metadata
  google-cloud-document_ai-v1beta3/synth.py
  google-cloud-document_ai-v1beta3/test/google/cloud/document_ai/v1beta3/document_processor_service_operations_test.rb
  google-cloud-document_ai-v1beta3/test/google/cloud/document_ai/v1beta3/document_processor_service_paths_test.rb
  google-cloud-document_ai-v1beta3/test/google/cloud/document_ai/v1beta3/document_processor_service_test.rb
  google-cloud-document_ai-v1beta3/test/helper.rb
Labels: cla: yes

#8112 chore: start tracking obsolete files
  google-iam-v1beta/synth.metadata
Labels: cla: yes, context: full

#8115 chore: start tracking obsolete files
  google-cloud-binary_authorization-v1beta1/synth.metadata
Labels: cla: yes, context: full

#8116 chore: start tracking obsolete files
  google-cloud-data_labeling-v1beta1/synth.metadata
Labels: cla: yes, context: full

#8117 chore: start tracking obsolete files
  google-cloud-document_ai-v1beta3/synth.metadata
Labels: cla: yes, context: full

#8118 chore: start tracking obsolete files
  google-cloud-service_control-v1/synth.metadata
Labels: cla: yes, context: full

#8111 Release google-analytics-admin-v1alpha 0.2.2
  google-analytics-admin-v1alpha/CHANGELOG.md
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/version.rb
Labels: autorelease: pending, cla: yes

#8120 Release google-iam-v1beta 0.1.0
  google-iam-v1beta/CHANGELOG.md
  google-iam-v1beta/lib/google/iam/v1beta/version.rb
Labels: autorelease: pending, cla: yes

#6462 feat(pubsub): Add Subscription#remove_dead_letter_policy
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/update_test.rb
Labels: api: pubsub, cla: yes

#8079 feat(bigtable): Add Backup-level IAM Policy support
  google-cloud-bigtable/acceptance/bigtable/backup_test.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/backup.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/service.rb
  google-cloud-bigtable/support/doctest_helper.rb
  google-cloud-bigtable/test/google/cloud/bigtable/backup/iam_policy_test.rb
Labels: api: bigtable, cla: yes

#8082 feat(bigquery): Add support for Table ACLS (IAM Policy)
  google-cloud-bigquery/acceptance/bigquery/table_policy_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/policy.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigquery/test/google/cloud/bigquery/policy_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_policy_test.rb
  google-cloud-bigquery/test/helper.rb
Labels: api: bigquery, cla: yes

#8124 chore: release google-cloud-pubsub 2.2.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#8125 chore: release google-cloud-bigtable 2.2.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#8133 Ignore bundler-related directory
  .gitignore
Labels: cla: yes

#8128 feat: Enable server side flow control by default with the option to turn it off
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/inventory.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/acknowledge_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/inventory_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/listen_test.rb
Labels: api: pubsub, cla: yes, type: feature request

#8097 chore: release google-cloud-bigquery 1.25.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: api: bigquery, autorelease: pending, cla: yes

#8143 [google-cloud-assured_workloads-v1beta1] feat: updated google.cloud.assuredworkloads.v1beta1.AssuredWorkloadsService service
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assuredworkloads/v1beta1/assuredworkloads_v1beta1_pb.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/cloud/assuredworkloads/v1beta1/assuredworkloads_v1beta1.rb
  google-cloud-assured_workloads-v1beta1/synth.metadata
Labels: cla: yes, context: full

#8141 [google-cloud-logging-v2] feat: Makes remaining LogBucket and LogViews methods public
  google-cloud-logging-v2/lib/google/cloud/logging/v2/config_service/client.rb
  google-cloud-logging-v2/lib/google/cloud/logging/v2/config_service/paths.rb
  google-cloud-logging-v2/lib/google/logging/v2/logging_config_pb.rb
  google-cloud-logging-v2/lib/google/logging/v2/logging_config_services_pb.rb
  google-cloud-logging-v2/proto_docs/google/logging/type/http_request.rb
  google-cloud-logging-v2/proto_docs/google/logging/v2/logging_config.rb
  google-cloud-logging-v2/proto_docs/google/logging/v2/logging_metrics.rb
  google-cloud-logging-v2/synth.metadata
  google-cloud-logging-v2/test/google/cloud/logging/v2/config_service_paths_test.rb
  google-cloud-logging-v2/test/google/cloud/logging/v2/config_service_test.rb
Labels: cla: yes, context: full

#8136 [google-cloud-artifact_registry-v1beta2] fix!: remove unimplemented ListDockerImages method.
  google-cloud-artifact_registry-v1beta2/lib/google/cloud/artifact_registry/v1beta2/artifact_registry/client.rb
  google-cloud-artifact_registry-v1beta2/lib/google/cloud/artifact_registry/v1beta2/artifact_registry/paths.rb
  google-cloud-artifact_registry-v1beta2/lib/google/devtools/artifactregistry/v1beta2/artifact_pb.rb
  google-cloud-artifact_registry-v1beta2/lib/google/devtools/artifactregistry/v1beta2/service_pb.rb
  google-cloud-artifact_registry-v1beta2/lib/google/devtools/artifactregistry/v1beta2/service_services_pb.rb
  google-cloud-artifact_registry-v1beta2/proto_docs/google/devtools/artifactregistry/v1beta2/artifact.rb
  google-cloud-artifact_registry-v1beta2/synth.metadata
  google-cloud-artifact_registry-v1beta2/test/google/cloud/artifact_registry/v1beta2/artifact_registry_paths_test.rb
  google-cloud-artifact_registry-v1beta2/test/google/cloud/artifact_registry/v1beta2/artifact_registry_test.rb
Labels: cla: yes, context: full

#8131 [google-cloud-recommendation_engine-v1beta1] fix!: Apply namespace/package options to RecommendationEngine resources proto.
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendationengine/v1beta1/recommendationengine_resources_pb.rb
  google-cloud-recommendation_engine-v1beta1/synth.metadata
Labels: cla: yes, context: full

#8130 [google-cloud-os_config-v1] feat: Added PatchRollout feature to PatchDeployments feat: Added Inventory proto definitions for VM Manager Inventory.
  google-cloud-os_config-v1/lib/google/cloud/os_config/v1/os_config_service/client.rb
  google-cloud-os_config-v1/lib/google/cloud/osconfig/v1/inventory_pb.rb
  google-cloud-os_config-v1/lib/google/cloud/osconfig/v1/osconfig_common_pb.rb
  google-cloud-os_config-v1/lib/google/cloud/osconfig/v1/patch_deployments_pb.rb
  google-cloud-os_config-v1/lib/google/cloud/osconfig/v1/patch_jobs_pb.rb
  google-cloud-os_config-v1/proto_docs/google/cloud/osconfig/v1/inventory.rb
  google-cloud-os_config-v1/proto_docs/google/cloud/osconfig/v1/osconfig_common.rb
  google-cloud-os_config-v1/proto_docs/google/cloud/osconfig/v1/patch_deployments.rb
  google-cloud-os_config-v1/proto_docs/google/cloud/osconfig/v1/patch_jobs.rb
  google-cloud-os_config-v1/synth.metadata
  google-cloud-os_config-v1/test/google/cloud/os_config/v1/os_config_service_test.rb
Labels: cla: yes, context: full

#8121 feat: Initial generation of google-cloud-artifact_registry wrapper
  .kokoro/continuous/linux/artifact_registry.cfg
  .kokoro/continuous/osx/artifact_registry.cfg
  .kokoro/continuous/windows/artifact_registry.cfg
  .kokoro/nightly/linux/artifact_registry.cfg
  .kokoro/nightly/osx/artifact_registry.cfg
  .kokoro/nightly/windows/artifact_registry.cfg
  .kokoro/release/artifact_registry.cfg
  .kokoro/samples_latest/linux/artifact_registry.cfg
  .kokoro/samples_latest/osx/artifact_registry.cfg
  .kokoro/samples_latest/windows/artifact_registry.cfg
  Gemfile
  google-cloud-artifact_registry/.gitignore
  google-cloud-artifact_registry/.repo-metadata.json
  google-cloud-artifact_registry/.rubocop.yml
  google-cloud-artifact_registry/.yardopts
  google-cloud-artifact_registry/AUTHENTICATION.md
  google-cloud-artifact_registry/CHANGELOG.md
  google-cloud-artifact_registry/Gemfile
  google-cloud-artifact_registry/LICENSE.md
  google-cloud-artifact_registry/README.md
  google-cloud-artifact_registry/Rakefile
  google-cloud-artifact_registry/google-cloud-artifact_registry.gemspec
  google-cloud-artifact_registry/lib/google-cloud-artifact_registry.rb
  google-cloud-artifact_registry/lib/google/cloud/artifact_registry.rb
  google-cloud-artifact_registry/lib/google/cloud/artifact_registry/version.rb
  google-cloud-artifact_registry/synth.metadata
  google-cloud-artifact_registry/synth.py
  google-cloud-artifact_registry/test/google/cloud/artifact_registry/client_test.rb
  google-cloud-artifact_registry/test/google/cloud/artifact_registry/version_test.rb
  google-cloud-artifact_registry/test/helper.rb
Labels: cla: yes

#8122 [google-cloud-billing-budgets-v1beta1] docs: Reworded comments for the new credit types filter
  google-cloud-billing-budgets-v1beta1/proto_docs/google/cloud/billing/budgets/v1beta1/budget_model.rb
  google-cloud-billing-budgets-v1beta1/synth.metadata
Labels: cla: yes, context: full

#8127 [google-cloud-data_labeling-v1beta1] docs: Provide a descriptive comment for DataLabelingService
  google-cloud-data_labeling-v1beta1/lib/google/cloud/data_labeling/v1beta1/data_labeling_service.rb
  google-cloud-data_labeling-v1beta1/lib/google/cloud/data_labeling/v1beta1/data_labeling_service/client.rb
  google-cloud-data_labeling-v1beta1/lib/google/cloud/datalabeling/v1beta1/data_labeling_service_services_pb.rb
  google-cloud-data_labeling-v1beta1/synth.metadata
Labels: cla: yes, context: full

#8129 [google-analytics-data-v1alpha] fix!: GetUniversalMetadata method removed from the API, GetMetadata method should be used instead feat: reporting requests now support date ranges longer than one year docs: minor documentation updates
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/client.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_pb.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_services_pb.rb
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/analytics_data_api.rb
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/data.rb
  google-analytics-data-v1alpha/synth.metadata
  google-analytics-data-v1alpha/test/google/analytics/data/v1alpha/analytics_data_test.rb
Labels: cla: yes, context: full

#8123 chore: start tracking obsolete files
  google-cloud-service_management-v1/synth.metadata
Labels: cla: yes, context: full

#8144 docs(pubsub): Remove EXPERIMENTAL label from RetryPolicy docs
  google-cloud-pubsub/lib/google/cloud/pubsub/retry_policy.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
Labels: api: pubsub, cla: yes, type: docs

#8140 chore: release google-cloud-pubsub 2.3.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#8153 chore: release google-cloud-firestore 2.4.0
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#8158 chore: start tracking obsolete files
  google-cloud-artifact_registry/synth.metadata
Labels: cla: yes, context: full

#8151 chore: release google-cloud-assured_workloads-v1beta1 0.2.0
  google-cloud-assured_workloads-v1beta1/CHANGELOG.md
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#8152 chore: release google-analytics-data-v1alpha 0.5.0
  google-analytics-data-v1alpha/CHANGELOG.md
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/version.rb
Labels: autorelease: pending, cla: yes

#8155 chore: release google-cloud-billing-budgets-v1beta1 0.3.1
  google-cloud-billing-budgets-v1beta1/CHANGELOG.md
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#8156 chore: release google-cloud-os_config-v1 0.2.0
  google-cloud-os_config-v1/CHANGELOG.md
  google-cloud-os_config-v1/lib/google/cloud/os_config/v1/version.rb
Labels: autorelease: pending, cla: yes

#8157 chore: release google-cloud-logging-v2 0.2.0
  google-cloud-logging-v2/CHANGELOG.md
  google-cloud-logging-v2/lib/google/cloud/logging/v2/version.rb
Labels: autorelease: pending, cla: yes

#8165 [google-cloud-container-v1] feat: sync v1 GKE API fix: deprecate SetLocations; use UpdateCluster refactor: provide name alias for GetOperation (as method signature annotation) feat: support for GetJSONWebKeys feat: support for Workload Identity feat:
  google-cloud-container-v1/lib/google/cloud/container/v1/cluster_manager/client.rb
  google-cloud-container-v1/lib/google/container/v1/cluster_service_pb.rb
  google-cloud-container-v1/lib/google/container/v1/cluster_service_services_pb.rb
  google-cloud-container-v1/proto_docs/google/container/v1/cluster_service.rb
  google-cloud-container-v1/synth.metadata
  google-cloud-container-v1/test/google/cloud/container/v1/cluster_manager_test.rb
Labels: cla: yes, context: full

#8171 [google-cloud-logging-v2] feat: add the Tailing API to get a live stream of the tail end of filtered logs
  google-cloud-logging-v2/lib/google/cloud/logging/v2/logging_service/client.rb
  google-cloud-logging-v2/lib/google/logging/v2/logging_pb.rb
  google-cloud-logging-v2/lib/google/logging/v2/logging_services_pb.rb
  google-cloud-logging-v2/proto_docs/google/logging/v2/logging.rb
  google-cloud-logging-v2/synth.metadata
  google-cloud-logging-v2/test/google/cloud/logging/v2/logging_service_test.rb
Labels: cla: yes, context: full

#8175 feat(stackdriver): Update dependencies to post-microgenerator versions
  stackdriver/stackdriver.gemspec
Labels: cla: yes
