Repository googleapis/google-cloud-ruby, pull requests merged in 2020-07, with the labels that each got.

#6925 feat: Initial microgen of spanner V1
  .kokoro/continuous/linux/spanner-v1.cfg
  .kokoro/continuous/osx/spanner-v1.cfg
  .kokoro/continuous/windows/spanner-v1.cfg
  .kokoro/nightly/linux/spanner-v1.cfg
  .kokoro/nightly/osx/spanner-v1.cfg
  .kokoro/nightly/windows/spanner-v1.cfg
  .kokoro/release/spanner-v1.cfg
  Gemfile
  google-cloud-spanner-v1/.gitignore
  google-cloud-spanner-v1/.repo-metadata.json
  google-cloud-spanner-v1/.rubocop.yml
  google-cloud-spanner-v1/.yardopts
  google-cloud-spanner-v1/AUTHENTICATION.md
  google-cloud-spanner-v1/CHANGELOG.md
  google-cloud-spanner-v1/Gemfile
  google-cloud-spanner-v1/LICENSE.md
  google-cloud-spanner-v1/README.md
  google-cloud-spanner-v1/Rakefile
  google-cloud-spanner-v1/google-cloud-spanner-v1.gemspec
  google-cloud-spanner-v1/lib/google-cloud-spanner-v1.rb
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1.rb
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/spanner.rb
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/spanner/client.rb
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/spanner/credentials.rb
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/spanner/paths.rb
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/version.rb
  google-cloud-spanner-v1/lib/google/spanner/v1/keys_pb.rb
  google-cloud-spanner-v1/lib/google/spanner/v1/mutation_pb.rb
  google-cloud-spanner-v1/lib/google/spanner/v1/query_plan_pb.rb
  google-cloud-spanner-v1/lib/google/spanner/v1/result_set_pb.rb
  google-cloud-spanner-v1/lib/google/spanner/v1/spanner_pb.rb
  google-cloud-spanner-v1/lib/google/spanner/v1/spanner_services_pb.rb
  google-cloud-spanner-v1/lib/google/spanner/v1/transaction_pb.rb
  google-cloud-spanner-v1/lib/google/spanner/v1/type_pb.rb
  google-cloud-spanner-v1/proto_docs/README.md
  google-cloud-spanner-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-spanner-v1/proto_docs/google/api/resource.rb
  google-cloud-spanner-v1/proto_docs/google/protobuf/any.rb
  google-cloud-spanner-v1/proto_docs/google/protobuf/duration.rb
  google-cloud-spanner-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-spanner-v1/proto_docs/google/protobuf/struct.rb
  google-cloud-spanner-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-spanner-v1/proto_docs/google/rpc/status.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/keys.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/mutation.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/query_plan.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/result_set.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/spanner.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/transaction.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/type.rb
  google-cloud-spanner-v1/synth.metadata
  google-cloud-spanner-v1/synth.py
  google-cloud-spanner-v1/test/google/cloud/spanner/v1/spanner_paths_test.rb
  google-cloud-spanner-v1/test/google/cloud/spanner/v1/spanner_test.rb
  google-cloud-spanner-v1/test/helper.rb
Labels: cla: yes

#6926 feat: Initial microgen of Spanner Database Admin V1
  .kokoro/continuous/linux/spanner-admin-database-v1.cfg
  .kokoro/continuous/osx/spanner-admin-database-v1.cfg
  .kokoro/continuous/windows/spanner-admin-database-v1.cfg
  .kokoro/nightly/linux/spanner-admin-database-v1.cfg
  .kokoro/nightly/osx/spanner-admin-database-v1.cfg
  .kokoro/nightly/windows/spanner-admin-database-v1.cfg
  .kokoro/release/spanner-admin-database-v1.cfg
  Gemfile
  google-cloud-spanner-admin-database-v1/.gitignore
  google-cloud-spanner-admin-database-v1/.repo-metadata.json
  google-cloud-spanner-admin-database-v1/.rubocop.yml
  google-cloud-spanner-admin-database-v1/.yardopts
  google-cloud-spanner-admin-database-v1/AUTHENTICATION.md
  google-cloud-spanner-admin-database-v1/CHANGELOG.md
  google-cloud-spanner-admin-database-v1/Gemfile
  google-cloud-spanner-admin-database-v1/LICENSE.md
  google-cloud-spanner-admin-database-v1/README.md
  google-cloud-spanner-admin-database-v1/Rakefile
  google-cloud-spanner-admin-database-v1/google-cloud-spanner-admin-database-v1.gemspec
  google-cloud-spanner-admin-database-v1/lib/google-cloud-spanner-admin-database-v1.rb
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1.rb
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin.rb
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/client.rb
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/credentials.rb
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/operations.rb
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/paths.rb
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/version.rb
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/backup_pb.rb
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/common_pb.rb
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/spanner_database_admin_pb.rb
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/spanner_database_admin_services_pb.rb
  google-cloud-spanner-admin-database-v1/proto_docs/README.md
  google-cloud-spanner-admin-database-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/api/resource.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/iam/v1/options.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/longrunning/operations.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/protobuf/any.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/rpc/status.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/spanner/admin/database/v1/backup.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/spanner/admin/database/v1/common.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/spanner/admin/database/v1/spanner_database_admin.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/type/expr.rb
  google-cloud-spanner-admin-database-v1/synth.metadata
  google-cloud-spanner-admin-database-v1/synth.py
  google-cloud-spanner-admin-database-v1/test/google/cloud/spanner/admin/database/v1/database_admin_operations_test.rb
  google-cloud-spanner-admin-database-v1/test/google/cloud/spanner/admin/database/v1/database_admin_paths_test.rb
  google-cloud-spanner-admin-database-v1/test/google/cloud/spanner/admin/database/v1/database_admin_test.rb
  google-cloud-spanner-admin-database-v1/test/helper.rb
Labels: cla: yes

#6927 feat: Initial microgen of Spanner Instance Admin V1
  .kokoro/continuous/linux/spanner-admin-instance-v1.cfg
  .kokoro/continuous/osx/spanner-admin-instance-v1.cfg
  .kokoro/continuous/windows/spanner-admin-instance-v1.cfg
  .kokoro/nightly/linux/spanner-admin-instance-v1.cfg
  .kokoro/nightly/osx/spanner-admin-instance-v1.cfg
  .kokoro/nightly/windows/spanner-admin-instance-v1.cfg
  .kokoro/release/spanner-admin-instance-v1.cfg
  Gemfile
  google-cloud-spanner-admin-instance-v1/.gitignore
  google-cloud-spanner-admin-instance-v1/.repo-metadata.json
  google-cloud-spanner-admin-instance-v1/.rubocop.yml
  google-cloud-spanner-admin-instance-v1/.yardopts
  google-cloud-spanner-admin-instance-v1/AUTHENTICATION.md
  google-cloud-spanner-admin-instance-v1/CHANGELOG.md
  google-cloud-spanner-admin-instance-v1/Gemfile
  google-cloud-spanner-admin-instance-v1/LICENSE.md
  google-cloud-spanner-admin-instance-v1/README.md
  google-cloud-spanner-admin-instance-v1/Rakefile
  google-cloud-spanner-admin-instance-v1/google-cloud-spanner-admin-instance-v1.gemspec
  google-cloud-spanner-admin-instance-v1/lib/google-cloud-spanner-admin-instance-v1.rb
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1.rb
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin.rb
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/client.rb
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/credentials.rb
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/operations.rb
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/paths.rb
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/version.rb
  google-cloud-spanner-admin-instance-v1/lib/google/spanner/admin/instance/v1/spanner_instance_admin_pb.rb
  google-cloud-spanner-admin-instance-v1/lib/google/spanner/admin/instance/v1/spanner_instance_admin_services_pb.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/README.md
  google-cloud-spanner-admin-instance-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/api/resource.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/iam/v1/options.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/longrunning/operations.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/protobuf/any.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/rpc/status.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/spanner/admin/instance/v1/spanner_instance_admin.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/type/expr.rb
  google-cloud-spanner-admin-instance-v1/synth.metadata
  google-cloud-spanner-admin-instance-v1/synth.py
  google-cloud-spanner-admin-instance-v1/test/google/cloud/spanner/admin/instance/v1/instance_admin_operations_test.rb
  google-cloud-spanner-admin-instance-v1/test/google/cloud/spanner/admin/instance/v1/instance_admin_paths_test.rb
  google-cloud-spanner-admin-instance-v1/test/google/cloud/spanner/admin/instance/v1/instance_admin_test.rb
  google-cloud-spanner-admin-instance-v1/test/helper.rb
Labels: cla: yes

#7000 Release google-cloud-spanner-v1 0.1.0
  google-cloud-spanner-v1/CHANGELOG.md
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/version.rb
Labels: autorelease: pending, cla: yes

#7001 Release google-cloud-spanner-admin-database-v1 0.1.0
  google-cloud-spanner-admin-database-v1/CHANGELOG.md
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/version.rb
Labels: autorelease: pending, cla: yes

#7002 Release google-cloud-spanner-admin-instance-v1 0.1.0
  google-cloud-spanner-admin-instance-v1/CHANGELOG.md
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/version.rb
Labels: autorelease: pending, cla: yes

#7004 fix: Don't check links to the current library's reference docs URL
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#7003 fix(debugger): Fix segfaults on Ruby 2.7
  google-cloud-debugger/ext/google/cloud/debugger/debugger_c/tracer.c
  google-cloud-debugger/lib/google/cloud/debugger/breakpoint/evaluator.rb
Labels: cla: yes

#7008 Release google-cloud-debugger 0.36.3
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending

#7015 [google-cloud-trace] feat: added support for span kind
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v1/trace_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v1/trace_services_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v2/trace_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v2/tracing_services_pb.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes, context: full

#7014 [google-cloud-trace-v2] feat: added support for span kind
  google-cloud-trace-v2/lib/google/cloud/trace/v2/trace_service/client.rb
  google-cloud-trace-v2/lib/google/devtools/cloudtrace/v2/trace_pb.rb
  google-cloud-trace-v2/lib/google/devtools/cloudtrace/v2/tracing_services_pb.rb
  google-cloud-trace-v2/proto_docs/google/devtools/cloudtrace/v2/trace.rb
  google-cloud-trace-v2/synth.metadata
  google-cloud-trace-v2/test/google/cloud/trace/v2/trace_service_test.rb
Labels: cla: yes, context: full

#7013 [google-cloud-trace-v1] feat: added support for span kind
  google-cloud-trace-v1/lib/google/devtools/cloudtrace/v1/trace_pb.rb
  google-cloud-trace-v1/lib/google/devtools/cloudtrace/v1/trace_services_pb.rb
  google-cloud-trace-v1/synth.metadata
Labels: cla: yes, context: full

#7007 [google-cloud-redis-v1] redis: v1 add UpgradeInstance request
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/client.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis_pb.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis_services_pb.rb
  google-cloud-redis-v1/proto_docs/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis-v1/synth.metadata
  google-cloud-redis-v1/test/google/cloud/redis/v1/cloud_redis_test.rb
Labels: cla: yes, context: full

#7005 [google-cloud-recommender-v1] feat: adds methods for interacting with insights
  google-cloud-recommender-v1/README.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/insight_pb.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommendation_pb.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/paths.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender_service_pb.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender_service_services_pb.rb
  google-cloud-recommender-v1/proto_docs/google/cloud/recommender/v1/insight.rb
  google-cloud-recommender-v1/proto_docs/google/cloud/recommender/v1/recommendation.rb
  google-cloud-recommender-v1/proto_docs/google/cloud/recommender/v1/recommender_service.rb
  google-cloud-recommender-v1/synth.metadata
  google-cloud-recommender-v1/test/google/cloud/recommender/v1/recommender_paths_test.rb
  google-cloud-recommender-v1/test/google/cloud/recommender/v1/recommender_test.rb
Labels: cla: yes, context: full

#7006 [google-cloud-recommender] feat: adds methods for interacting with insights
  google-cloud-recommender/lib/google/cloud/recommender.rb
  google-cloud-recommender/synth.metadata
Labels: cla: yes, context: full

#7016 Release google-cloud-trace 0.39.0
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes

#7017 Release google-cloud-trace-v1 0.1.0
  google-cloud-trace-v1/CHANGELOG.md
  google-cloud-trace-v1/lib/google/cloud/trace/v1/version.rb
Labels: autorelease: pending, cla: yes

#7018 Release google-cloud-trace-v2 0.1.0
  google-cloud-trace-v2/CHANGELOG.md
  google-cloud-trace-v2/lib/google/cloud/trace/v2/version.rb
Labels: autorelease: pending, cla: yes

#7019 Release google-cloud-logging-v2 0.1.0
  google-cloud-logging-v2/CHANGELOG.md
  google-cloud-logging-v2/lib/google/cloud/logging/v2/version.rb
Labels: autorelease: pending, cla: yes

#7020 Release google-cloud-debugger-v2 0.1.0
  google-cloud-debugger-v2/CHANGELOG.md
  google-cloud-debugger-v2/lib/google/cloud/debugger/v2/version.rb
Labels: autorelease: pending, cla: yes

#7021 Release google-cloud-error_reporting-v1beta1 0.1.0
  google-cloud-error_reporting-v1beta1/CHANGELOG.md
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7023 [google-cloud-logging-v2] feat: Update Logging API protos.
  google-cloud-logging-v2/lib/google/cloud/logging/v2/config_service/client.rb
  google-cloud-logging-v2/lib/google/cloud/logging/v2/logging_service/client.rb
  google-cloud-logging-v2/lib/google/cloud/logging/v2/metrics_service/client.rb
  google-cloud-logging-v2/lib/google/logging/v2/logging_config_services_pb.rb
  google-cloud-logging-v2/lib/google/logging/v2/logging_pb.rb
  google-cloud-logging-v2/lib/google/logging/v2/logging_services_pb.rb
  google-cloud-logging-v2/proto_docs/google/logging/v2/log_entry.rb
  google-cloud-logging-v2/proto_docs/google/logging/v2/logging.rb
  google-cloud-logging-v2/proto_docs/google/logging/v2/logging_config.rb
  google-cloud-logging-v2/proto_docs/google/logging/v2/logging_metrics.rb
  google-cloud-logging-v2/synth.metadata
Labels: cla: yes, context: full

#7026 fix(spanner): update batch and batch, partitioned query, staleness options tests for emulator
  google-cloud-spanner/acceptance/spanner/batch_client/execute_partition_test.rb
  google-cloud-spanner/acceptance/spanner/client/batch_update_test.rb
  google-cloud-spanner/acceptance/spanner/client/params/struct_test.rb
  google-cloud-spanner/acceptance/spanner/client/single_use_test.rb
  google-cloud-spanner/acceptance/spanner/client/snapshot_test.rb
  google-cloud-spanner/acceptance/spanner/client/transaction_test.rb
Labels: api: spanner, cla: yes

#6923 [google-cloud-firestore] firestore: add BatchWrite to service config
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/query.rb
  google-cloud-firestore/lib/google/firestore/v1/query_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes, context: full

#7029 test(pubsub): Fix acceptance test assertion
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
Labels: api: pubsub, cla: yes

#6996 feat: Generate google-cloud-build wrapper
  .kokoro/continuous/linux/build.cfg
  .kokoro/continuous/osx/build.cfg
  .kokoro/continuous/windows/build.cfg
  .kokoro/nightly/linux/build.cfg
  .kokoro/nightly/osx/build.cfg
  .kokoro/nightly/windows/build.cfg
  .kokoro/release/build.cfg
  .kokoro/samples_latest/linux/build.cfg
  .kokoro/samples_latest/osx/build.cfg
  .kokoro/samples_latest/windows/build.cfg
  Gemfile
  google-cloud-build/.gitignore
  google-cloud-build/.repo-metadata.json
  google-cloud-build/.rubocop.yml
  google-cloud-build/.yardopts
  google-cloud-build/AUTHENTICATION.md
  google-cloud-build/CHANGELOG.md
  google-cloud-build/Gemfile
  google-cloud-build/LICENSE.md
  google-cloud-build/README.md
  google-cloud-build/Rakefile
  google-cloud-build/google-cloud-build.gemspec
  google-cloud-build/lib/google-cloud-build.rb
  google-cloud-build/lib/google/cloud/build.rb
  google-cloud-build/lib/google/cloud/build/version.rb
  google-cloud-build/synth.metadata
  google-cloud-build/synth.py
  google-cloud-build/test/google/cloud/build/client_test.rb
  google-cloud-build/test/google/cloud/build/version_test.rb
  google-cloud-build/test/helper.rb
Labels: cla: yes

#7022 fix(env): Project ID should honor GOOGLE_CLOUD_PROJECT
  google-cloud-env/lib/google/cloud/env.rb
Labels: cla: yes

#7027 [google-cloud-dlp-v2] Feature: Add CSV and TSV to file types. Fixes: Cleaned up resource_reference annotations for correct semantics and improved client library generation Fixes: BucketingConfig.replacement_value marked as required
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/dlp_service/client.rb
  google-cloud-dlp-v2/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp-v2/lib/google/privacy/dlp/v2/storage_pb.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp-v2/synth.metadata
Labels: cla: yes, context: full

#7030 Release google-cloud-env 1.3.3
  google-cloud-env/CHANGELOG.md
  google-cloud-env/lib/google/cloud/env/version.rb
Labels: autorelease: pending, cla: yes

#7025 Release google-cloud-logging-v2 0.1.1
  google-cloud-logging-v2/CHANGELOG.md
  google-cloud-logging-v2/lib/google/cloud/logging/v2/version.rb
Labels: autorelease: pending, cla: yes

#7031 Release google-cloud-dlp-v2 0.4.0
  google-cloud-dlp-v2/CHANGELOG.md
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/version.rb
Labels: autorelease: pending, cla: yes

#7033 Release google-cloud-build 0.1.0
  google-cloud-build/CHANGELOG.md
  google-cloud-build/lib/google/cloud/build/version.rb
Labels: autorelease: pending, cla: yes

#7034 chore: Initial microgen of PubSub V1
  .kokoro/continuous/linux/pubsub-v1.cfg
  .kokoro/continuous/osx/pubsub-v1.cfg
  .kokoro/continuous/windows/pubsub-v1.cfg
  .kokoro/nightly/linux/pubsub-v1.cfg
  .kokoro/nightly/osx/pubsub-v1.cfg
  .kokoro/nightly/windows/pubsub-v1.cfg
  .kokoro/release/pubsub-v1.cfg
  Gemfile
  google-cloud-pubsub-v1/.gitignore
  google-cloud-pubsub-v1/.repo-metadata.json
  google-cloud-pubsub-v1/.rubocop.yml
  google-cloud-pubsub-v1/.yardopts
  google-cloud-pubsub-v1/AUTHENTICATION.md
  google-cloud-pubsub-v1/CHANGELOG.md
  google-cloud-pubsub-v1/Gemfile
  google-cloud-pubsub-v1/LICENSE.md
  google-cloud-pubsub-v1/README.md
  google-cloud-pubsub-v1/Rakefile
  google-cloud-pubsub-v1/google-cloud-pubsub-v1.gemspec
  google-cloud-pubsub-v1/lib/google-cloud-pubsub-v1.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/credentials.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/paths.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber/credentials.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber/paths.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/version.rb
  google-cloud-pubsub-v1/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub-v1/lib/google/pubsub/v1/pubsub_services_pb.rb
  google-cloud-pubsub-v1/proto_docs/README.md
  google-cloud-pubsub-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-pubsub-v1/proto_docs/google/api/resource.rb
  google-cloud-pubsub-v1/proto_docs/google/protobuf/duration.rb
  google-cloud-pubsub-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-pubsub-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-pubsub-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-pubsub-v1/proto_docs/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub-v1/synth.metadata
  google-cloud-pubsub-v1/synth.py
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/publisher_paths_test.rb
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/publisher_test.rb
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/subscriber_paths_test.rb
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/subscriber_test.rb
  google-cloud-pubsub-v1/test/helper.rb
Labels: api: pubsub, cla: yes

#7039 [google-cloud-spanner-v1] feat: Spanner NUMERIC type
  google-cloud-spanner-v1/lib/google/spanner/v1/type_pb.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/type.rb
  google-cloud-spanner-v1/synth.metadata
Labels: cla: yes, context: full

#7037 [google-cloud-security_center-v1] fix: correct securitycenter grpc_service_configs
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/security_center/client.rb
  google-cloud-security_center-v1/synth.metadata
Labels: cla: yes, context: full

#7038 [google-cloud-security_center-v1p1beta1] fix: correct securitycenter grpc_service_configs
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/security_center/client.rb
  google-cloud-security_center-v1p1beta1/synth.metadata
Labels: cla: yes, context: full

#7044 chore: Fix nightly job error that was causing release-please not to run
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#7041 chore: Workaround for grpc/grpc#23490 in OSLogin synth files
  google-cloud-os_login-v1/synth.py
  google-cloud-os_login-v1beta/synth.py
Labels: cla: yes

#7032 [google-cloud-firestore] firestore: add BatchWrite to gapic yaml
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client_config.json
  google-cloud-firestore/synth.metadata
  google-cloud-firestore/test/google/cloud/firestore/v1/firestore_client_test.rb
Labels: cla: yes, context: full

#7042 Release google-cloud-spanner-v1 0.2.0
  google-cloud-spanner-v1/CHANGELOG.md
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/version.rb
Labels: autorelease: pending, cla: yes

#7043 Release google-cloud-security_center-v1p1beta1 0.3.2
  google-cloud-security_center-v1p1beta1/CHANGELOG.md
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7048 Release google-cloud-security_center-v1 0.3.2
  google-cloud-security_center-v1/CHANGELOG.md
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/version.rb
Labels: autorelease: pending, cla: yes

#7046 Release google-cloud-recommender-v1 0.5.0
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
Labels: autorelease: pending, cla: yes

#7047 Release google-cloud-redis-v1 0.3.0
  google-cloud-redis-v1/CHANGELOG.md
  google-cloud-redis-v1/lib/google/cloud/redis/v1/version.rb
Labels: autorelease: pending, cla: yes

#7054 Add publisher/helpers.rb and subscriber/helpers.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/helpers.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber/helpers.rb
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/publisher/helpers_test.rb
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/subscriber/helpers_test.rb
Labels: api: pubsub, cla: yes

#7049 [google-cloud-build-v1] fix: add missing cloudbuild RPCs to retry config
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/client.rb
  google-cloud-build-v1/synth.metadata
Labels: cla: yes, context: full

#7009 feat(debugger)!: Use new generated client classes
  google-cloud-debugger/.rubocop.yml
  google-cloud-debugger/AUTHENTICATION.md
  google-cloud-debugger/Gemfile
  google-cloud-debugger/OVERVIEW.md
  google-cloud-debugger/Rakefile
  google-cloud-debugger/acceptance/debugger/debugger_test.rb
  google-cloud-debugger/acceptance/debugger_helper.rb
  google-cloud-debugger/google-cloud-debugger.gemspec
  google-cloud-debugger/integration/common_debugger_test.rb
  google-cloud-debugger/integration/debugger_helper.rb
  google-cloud-debugger/lib/google-cloud-debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger/breakpoint.rb
  google-cloud-debugger/lib/google/cloud/debugger/breakpoint/source_location.rb
  google-cloud-debugger/lib/google/cloud/debugger/breakpoint/stack_frame.rb
  google-cloud-debugger/lib/google/cloud/debugger/breakpoint/status_message.rb
  google-cloud-debugger/lib/google/cloud/debugger/breakpoint/variable.rb
  google-cloud-debugger/lib/google/cloud/debugger/credentials.rb
  google-cloud-debugger/lib/google/cloud/debugger/debuggee.rb
  google-cloud-debugger/lib/google/cloud/debugger/service.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client_config.json
  google-cloud-debugger/lib/google/cloud/debugger/v2/credentials.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client_config.json
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/controller.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/data.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/source/v1/source_context.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/protobuf/empty.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/protobuf/timestamp.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/controller_pb.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/controller_services_pb.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/data_pb.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/debugger_pb.rb
  google-cloud-debugger/lib/google/devtools/clouddebugger/v2/debugger_services_pb.rb
  google-cloud-debugger/lib/google/devtools/source/v1/source_context_pb.rb
  google-cloud-debugger/support/doctest_helper.rb
  google-cloud-debugger/synth.metadata
  google-cloud-debugger/synth.py
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/source_location_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/stack_frame_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/status_message_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/variable_table_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint/variable_test.rb
  google-cloud-debugger/test/google/cloud/debugger/breakpoint_test.rb
  google-cloud-debugger/test/google/cloud/debugger/debuggee_test.rb
  google-cloud-debugger/test/google/cloud/debugger/logpoint_test.rb
  google-cloud-debugger/test/google/cloud/debugger/snappoint_test.rb
  google-cloud-debugger/test/google/cloud/debugger/transmitter_test.rb
  google-cloud-debugger/test/google/cloud/debugger/v2/controller2_client_test.rb
  google-cloud-debugger/test/google/cloud/debugger/v2/debugger2_client_test.rb
  google-cloud-debugger/test/google/cloud/debugger_test.rb
Labels: cla: yes

#6999 feat(error_reporting)!: Use new generated client classes
  google-cloud-error_reporting/.rubocop.yml
  google-cloud-error_reporting/AUTHENTICATION.md
  google-cloud-error_reporting/Gemfile
  google-cloud-error_reporting/Rakefile
  google-cloud-error_reporting/acceptance/error_reporting/error_reporting_test.rb
  google-cloud-error_reporting/acceptance/error_reporting_helper.rb
  google-cloud-error_reporting/google-cloud-error_reporting.gemspec
  google-cloud-error_reporting/lib/google-cloud-error_reporting.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/credentials.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/error_event.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/credentials.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_group_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_stats_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/report_errors_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/protobuf/duration.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client_config.json
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client_config.json
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client_config.json
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/common_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_group_service_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_group_service_services_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_stats_service_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/error_stats_service_services_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/report_errors_service_pb.rb
  google-cloud-error_reporting/lib/google/devtools/clouderrorreporting/v1beta1/report_errors_service_services_pb.rb
  google-cloud-error_reporting/support/doctest_helper.rb
  google-cloud-error_reporting/synth.metadata
  google-cloud-error_reporting/synth.py
  google-cloud-error_reporting/test/google-cloud-error_reporting_test.rb
  google-cloud-error_reporting/test/google/cloud/error_reporting/error_event_test.rb
  google-cloud-error_reporting/test/google/cloud/error_reporting_test.rb
Labels: cla: yes

#6995 Release google-cloud-bigquery 1.21.2
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes

#7053 Release google-cloud-bigtable 1.3.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#6997 Release google-cloud-pubsub 1.9.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#7055 Release google-cloud-build-v1 0.1.1
  google-cloud-build-v1/CHANGELOG.md
  google-cloud-build-v1/lib/google/cloud/build/v1/version.rb
Labels: autorelease: pending, cla: yes

#7063 Release google-cloud-error_reporting 0.40.0
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes

#7058 Release google-cloud-logging 2.0.0
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#7064 Release google-cloud-logging 2.0.0
  google-cloud-logging/CHANGELOG.md
  stackdriver/stackdriver.gemspec
Labels: autorelease: pending, cla: yes

#7065 Release google-cloud-debugger 0.40.0
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#7067 [google-cloud-build-v1] fix: inline markup spans must be separated from the surrounding text by non-word characters
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/client.rb
  google-cloud-build-v1/lib/google/devtools/cloudbuild/v1/cloudbuild_services_pb.rb
  google-cloud-build-v1/proto_docs/google/devtools/cloudbuild/v1/cloudbuild.rb
  google-cloud-build-v1/synth.metadata
Labels: cla: yes, context: full

#7060 [google-cloud-spanner-admin-database-v1] fix(spanner): update UpdateBackup to be retryable
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/client.rb
  google-cloud-spanner-admin-database-v1/synth.metadata
Labels: cla: yes, context: full

#7069 chore: Initial microgen of Datastore V1
  .kokoro/continuous/linux/datastore-v1.cfg
  .kokoro/continuous/osx/datastore-v1.cfg
  .kokoro/continuous/windows/datastore-v1.cfg
  .kokoro/nightly/linux/datastore-v1.cfg
  .kokoro/nightly/osx/datastore-v1.cfg
  .kokoro/nightly/windows/datastore-v1.cfg
  .kokoro/release/datastore-v1.cfg
  Gemfile
  google-cloud-datastore-v1/.gitignore
  google-cloud-datastore-v1/.repo-metadata.json
  google-cloud-datastore-v1/.rubocop.yml
  google-cloud-datastore-v1/.yardopts
  google-cloud-datastore-v1/AUTHENTICATION.md
  google-cloud-datastore-v1/CHANGELOG.md
  google-cloud-datastore-v1/Gemfile
  google-cloud-datastore-v1/LICENSE.md
  google-cloud-datastore-v1/README.md
  google-cloud-datastore-v1/Rakefile
  google-cloud-datastore-v1/google-cloud-datastore-v1.gemspec
  google-cloud-datastore-v1/lib/google-cloud-datastore-v1.rb
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1.rb
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1/datastore.rb
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1/datastore/client.rb
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1/datastore/credentials.rb
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1/version.rb
  google-cloud-datastore-v1/lib/google/datastore/v1/datastore_pb.rb
  google-cloud-datastore-v1/lib/google/datastore/v1/datastore_services_pb.rb
  google-cloud-datastore-v1/lib/google/datastore/v1/entity_pb.rb
  google-cloud-datastore-v1/lib/google/datastore/v1/query_pb.rb
  google-cloud-datastore-v1/proto_docs/README.md
  google-cloud-datastore-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-datastore-v1/proto_docs/google/api/resource.rb
  google-cloud-datastore-v1/proto_docs/google/datastore/v1/datastore.rb
  google-cloud-datastore-v1/proto_docs/google/datastore/v1/entity.rb
  google-cloud-datastore-v1/proto_docs/google/datastore/v1/query.rb
  google-cloud-datastore-v1/proto_docs/google/protobuf/struct.rb
  google-cloud-datastore-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-datastore-v1/proto_docs/google/protobuf/wrappers.rb
  google-cloud-datastore-v1/proto_docs/google/type/latlng.rb
  google-cloud-datastore-v1/synth.metadata
  google-cloud-datastore-v1/synth.py
  google-cloud-datastore-v1/test/google/cloud/datastore/v1/datastore_test.rb
  google-cloud-datastore-v1/test/helper.rb
Labels: api: datastore, cla: yes

#6493 feat(pubsub): Add Subscription#detach and #detached?
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
  google-cloud-pubsub/acceptance/pubsub_helper.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/attrs_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/detach_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: api: pubsub, cla: yes

#7072 chore: Initial microgen of Firestore Admin V1
  .kokoro/continuous/linux/firestore-admin-v1.cfg
  .kokoro/continuous/osx/firestore-admin-v1.cfg
  .kokoro/continuous/windows/firestore-admin-v1.cfg
  .kokoro/nightly/linux/firestore-admin-v1.cfg
  .kokoro/nightly/osx/firestore-admin-v1.cfg
  .kokoro/nightly/windows/firestore-admin-v1.cfg
  .kokoro/release/firestore-admin-v1.cfg
  Gemfile
  google-cloud-firestore-admin-v1/.gitignore
  google-cloud-firestore-admin-v1/.repo-metadata.json
  google-cloud-firestore-admin-v1/.rubocop.yml
  google-cloud-firestore-admin-v1/.yardopts
  google-cloud-firestore-admin-v1/AUTHENTICATION.md
  google-cloud-firestore-admin-v1/CHANGELOG.md
  google-cloud-firestore-admin-v1/Gemfile
  google-cloud-firestore-admin-v1/LICENSE.md
  google-cloud-firestore-admin-v1/README.md
  google-cloud-firestore-admin-v1/Rakefile
  google-cloud-firestore-admin-v1/google-cloud-firestore-admin-v1.gemspec
  google-cloud-firestore-admin-v1/lib/google-cloud-firestore-admin-v1.rb
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1.rb
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin.rb
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin/client.rb
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin/credentials.rb
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin/operations.rb
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin/paths.rb
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/version.rb
  google-cloud-firestore-admin-v1/lib/google/firestore/admin/v1/field_pb.rb
  google-cloud-firestore-admin-v1/lib/google/firestore/admin/v1/firestore_admin_pb.rb
  google-cloud-firestore-admin-v1/lib/google/firestore/admin/v1/firestore_admin_services_pb.rb
  google-cloud-firestore-admin-v1/lib/google/firestore/admin/v1/index_pb.rb
  google-cloud-firestore-admin-v1/lib/google/firestore/admin/v1/location_pb.rb
  google-cloud-firestore-admin-v1/lib/google/firestore/admin/v1/operation_pb.rb
  google-cloud-firestore-admin-v1/proto_docs/README.md
  google-cloud-firestore-admin-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-firestore-admin-v1/proto_docs/google/api/resource.rb
  google-cloud-firestore-admin-v1/proto_docs/google/firestore/admin/v1/field.rb
  google-cloud-firestore-admin-v1/proto_docs/google/firestore/admin/v1/firestore_admin.rb
  google-cloud-firestore-admin-v1/proto_docs/google/firestore/admin/v1/index.rb
  google-cloud-firestore-admin-v1/proto_docs/google/firestore/admin/v1/location.rb
  google-cloud-firestore-admin-v1/proto_docs/google/firestore/admin/v1/operation.rb
  google-cloud-firestore-admin-v1/proto_docs/google/longrunning/operations.rb
  google-cloud-firestore-admin-v1/proto_docs/google/protobuf/any.rb
  google-cloud-firestore-admin-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-firestore-admin-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-firestore-admin-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-firestore-admin-v1/proto_docs/google/rpc/status.rb
  google-cloud-firestore-admin-v1/proto_docs/google/type/latlng.rb
  google-cloud-firestore-admin-v1/synth.metadata
  google-cloud-firestore-admin-v1/synth.py
  google-cloud-firestore-admin-v1/test/google/cloud/firestore/admin/v1/firestore_admin_operations_test.rb
  google-cloud-firestore-admin-v1/test/google/cloud/firestore/admin/v1/firestore_admin_paths_test.rb
  google-cloud-firestore-admin-v1/test/google/cloud/firestore/admin/v1/firestore_admin_test.rb
  google-cloud-firestore-admin-v1/test/helper.rb
Labels: api: firestore, cla: yes

#7073 chore: remove nonexistent file from billing-v1's synth
  google-cloud-billing-v1/synth.py
Labels: cla: yes

#7075 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/synth.metadata
  google-cloud-billing-v1/test/google/cloud/billing/v1/cloud_billing_test.rb
  google-cloud-billing-v1/test/google/cloud/billing/v1/cloud_catalog_test.rb
Labels: cla: yes, context: partial

#7071 chore: Initial microgen of Firestore V1
  .kokoro/continuous/linux/firestore-v1.cfg
  .kokoro/continuous/osx/firestore-v1.cfg
  .kokoro/continuous/windows/firestore-v1.cfg
  .kokoro/nightly/linux/firestore-v1.cfg
  .kokoro/nightly/osx/firestore-v1.cfg
  .kokoro/nightly/windows/firestore-v1.cfg
  .kokoro/release/firestore-v1.cfg
  Gemfile
  google-cloud-firestore-v1/.gitignore
  google-cloud-firestore-v1/.repo-metadata.json
  google-cloud-firestore-v1/.rubocop.yml
  google-cloud-firestore-v1/.yardopts
  google-cloud-firestore-v1/AUTHENTICATION.md
  google-cloud-firestore-v1/CHANGELOG.md
  google-cloud-firestore-v1/Gemfile
  google-cloud-firestore-v1/LICENSE.md
  google-cloud-firestore-v1/README.md
  google-cloud-firestore-v1/Rakefile
  google-cloud-firestore-v1/google-cloud-firestore-v1.gemspec
  google-cloud-firestore-v1/lib/google-cloud-firestore-v1.rb
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1.rb
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore.rb
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore/client.rb
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore/credentials.rb
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/version.rb
  google-cloud-firestore-v1/lib/google/firestore/v1/common_pb.rb
  google-cloud-firestore-v1/lib/google/firestore/v1/document_pb.rb
  google-cloud-firestore-v1/lib/google/firestore/v1/firestore_pb.rb
  google-cloud-firestore-v1/lib/google/firestore/v1/firestore_services_pb.rb
  google-cloud-firestore-v1/lib/google/firestore/v1/query_pb.rb
  google-cloud-firestore-v1/lib/google/firestore/v1/write_pb.rb
  google-cloud-firestore-v1/proto_docs/README.md
  google-cloud-firestore-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-firestore-v1/proto_docs/google/api/resource.rb
  google-cloud-firestore-v1/proto_docs/google/firestore/v1/common.rb
  google-cloud-firestore-v1/proto_docs/google/firestore/v1/document.rb
  google-cloud-firestore-v1/proto_docs/google/firestore/v1/firestore.rb
  google-cloud-firestore-v1/proto_docs/google/firestore/v1/query.rb
  google-cloud-firestore-v1/proto_docs/google/firestore/v1/write.rb
  google-cloud-firestore-v1/proto_docs/google/protobuf/any.rb
  google-cloud-firestore-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-firestore-v1/proto_docs/google/protobuf/struct.rb
  google-cloud-firestore-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-firestore-v1/proto_docs/google/protobuf/wrappers.rb
  google-cloud-firestore-v1/proto_docs/google/rpc/status.rb
  google-cloud-firestore-v1/proto_docs/google/type/latlng.rb
  google-cloud-firestore-v1/synth.metadata
  google-cloud-firestore-v1/synth.py
  google-cloud-firestore-v1/test/google/cloud/firestore/v1/firestore_test.rb
  google-cloud-firestore-v1/test/helper.rb
Labels: api: firestore, cla: yes

#7076 fix(spanner-admin): Make the spanner env prefixes consistent
  google-cloud-spanner-admin-database-v1/AUTHENTICATION.md
  google-cloud-spanner-admin-database-v1/Rakefile
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/credentials.rb
  google-cloud-spanner-admin-database-v1/synth.metadata
  google-cloud-spanner-admin-database-v1/synth.py
  google-cloud-spanner-admin-instance-v1/AUTHENTICATION.md
  google-cloud-spanner-admin-instance-v1/Rakefile
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/credentials.rb
  google-cloud-spanner-admin-instance-v1/synth.metadata
  google-cloud-spanner-admin-instance-v1/synth.py
Labels: cla: yes

#7078 chore: Initial microgen of Bigtable V2
  .kokoro/continuous/linux/bigtable-v2.cfg
  .kokoro/continuous/osx/bigtable-v2.cfg
  .kokoro/continuous/windows/bigtable-v2.cfg
  .kokoro/nightly/linux/bigtable-v2.cfg
  .kokoro/nightly/osx/bigtable-v2.cfg
  .kokoro/nightly/windows/bigtable-v2.cfg
  .kokoro/release/bigtable-v2.cfg
  Gemfile
  google-cloud-bigtable-v2/.gitignore
  google-cloud-bigtable-v2/.repo-metadata.json
  google-cloud-bigtable-v2/.rubocop.yml
  google-cloud-bigtable-v2/.yardopts
  google-cloud-bigtable-v2/AUTHENTICATION.md
  google-cloud-bigtable-v2/CHANGELOG.md
  google-cloud-bigtable-v2/Gemfile
  google-cloud-bigtable-v2/LICENSE.md
  google-cloud-bigtable-v2/README.md
  google-cloud-bigtable-v2/Rakefile
  google-cloud-bigtable-v2/google-cloud-bigtable-v2.gemspec
  google-cloud-bigtable-v2/lib/google-cloud-bigtable-v2.rb
  google-cloud-bigtable-v2/lib/google/bigtable/v2/bigtable_pb.rb
  google-cloud-bigtable-v2/lib/google/bigtable/v2/bigtable_services_pb.rb
  google-cloud-bigtable-v2/lib/google/bigtable/v2/data_pb.rb
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2.rb
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/bigtable.rb
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/bigtable/client.rb
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/bigtable/credentials.rb
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/bigtable/paths.rb
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/version.rb
  google-cloud-bigtable-v2/proto_docs/README.md
  google-cloud-bigtable-v2/proto_docs/google/api/field_behavior.rb
  google-cloud-bigtable-v2/proto_docs/google/api/resource.rb
  google-cloud-bigtable-v2/proto_docs/google/bigtable/v2/bigtable.rb
  google-cloud-bigtable-v2/proto_docs/google/bigtable/v2/data.rb
  google-cloud-bigtable-v2/proto_docs/google/protobuf/any.rb
  google-cloud-bigtable-v2/proto_docs/google/protobuf/wrappers.rb
  google-cloud-bigtable-v2/proto_docs/google/rpc/status.rb
  google-cloud-bigtable-v2/synth.metadata
  google-cloud-bigtable-v2/synth.py
  google-cloud-bigtable-v2/test/google/cloud/bigtable/v2/bigtable_paths_test.rb
  google-cloud-bigtable-v2/test/google/cloud/bigtable/v2/bigtable_test.rb
  google-cloud-bigtable-v2/test/helper.rb
Labels: api: bigtable, cla: yes

#7070 Release google-cloud-spanner-admin-database-v1 0.1.1
  google-cloud-spanner-admin-database-v1/CHANGELOG.md
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/version.rb
Labels: autorelease: pending, cla: yes

#7077 Release google-cloud-spanner-admin-instance-v1 0.1.1
  google-cloud-spanner-admin-instance-v1/CHANGELOG.md
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/version.rb
Labels: autorelease: pending, cla: yes

#7074 feat(trace)!: Use new generated client classes
  google-cloud-trace/.rubocop.yml
  google-cloud-trace/AUTHENTICATION.md
  google-cloud-trace/Gemfile
  google-cloud-trace/Rakefile
  google-cloud-trace/google-cloud-trace.gemspec
  google-cloud-trace/lib/google-cloud-trace.rb
  google-cloud-trace/lib/google/cloud/trace.rb
  google-cloud-trace/lib/google/cloud/trace/credentials.rb
  google-cloud-trace/lib/google/cloud/trace/result_set.rb
  google-cloud-trace/lib/google/cloud/trace/service.rb
  google-cloud-trace/lib/google/cloud/trace/span.rb
  google-cloud-trace/lib/google/cloud/trace/trace_record.rb
  google-cloud-trace/lib/google/cloud/trace/v1.rb
  google-cloud-trace/lib/google/cloud/trace/v1/credentials.rb
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/devtools/cloudtrace/v1/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/protobuf/empty.rb
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/protobuf/timestamp.rb
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client_config.json
  google-cloud-trace/lib/google/cloud/trace/v2.rb
  google-cloud-trace/lib/google/cloud/trace/v2/credentials.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/tracing.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/any.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/empty.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/timestamp.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/wrappers.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/rpc/status.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client_config.json
  google-cloud-trace/lib/google/devtools/cloudtrace/v1/trace_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v1/trace_services_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v2/trace_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v2/tracing_pb.rb
  google-cloud-trace/lib/google/devtools/cloudtrace/v2/tracing_services_pb.rb
  google-cloud-trace/support/doctest_helper.rb
  google-cloud-trace/synth.metadata
  google-cloud-trace/synth.py
  google-cloud-trace/test/google/cloud/trace/middleware_test.rb
  google-cloud-trace/test/google/cloud/trace/project_test.rb
  google-cloud-trace/test/google/cloud/trace/trace_record_test.rb
  google-cloud-trace/test/google/cloud/trace_test.rb
  google-cloud-trace/test/helper.rb
Labels: cla: yes

#7082 Release google-cloud-pubsub 1.10.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#7081 Release google-cloud-trace 0.40.0
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes

#7080 Release google-cloud-spanner 2.0.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#7101 [google-cloud-text_to_speech-v1beta1] feat: Support MULAW audio encoding feat: Support MP3_64_KBPS audio encoding feat: Support timepointing via SSML <mark> tag
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/text_to_speech/v1beta1/text_to_speech/client.rb
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/texttospeech/v1beta1/cloud_tts_pb.rb
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/texttospeech/v1beta1/cloud_tts_services_pb.rb
  google-cloud-text_to_speech-v1beta1/proto_docs/google/cloud/texttospeech/v1beta1/cloud_tts.rb
  google-cloud-text_to_speech-v1beta1/synth.metadata
  google-cloud-text_to_speech-v1beta1/test/google/cloud/text_to_speech/v1beta1/text_to_speech_test.rb
Labels: cla: yes, context: full

#7091 feat: storage support signing with IAMCredentials SignBlob API
  google-cloud-storage/acceptance/storage/bucket_generate_signed_post_policy_v4_test.rb
  google-cloud-storage/acceptance/storage/bucket_post_object_v2_test.rb
  google-cloud-storage/acceptance/storage/signed_url_v2_test.rb
  google-cloud-storage/acceptance/storage/signed_url_v4_test.rb
  google-cloud-storage/acceptance/storage_helper.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/file/signer_v2.rb
  google-cloud-storage/lib/google/cloud/storage/file/signer_v4.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/support/doctest_helper.rb
  google-cloud-storage/test/google/cloud/storage/bucket_post_object_test.rb
  google-cloud-storage/test/google/cloud/storage/bucket_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/bucket_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/file_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/file_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_post_object_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/file_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/file_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/project_signed_url_v2_test.rb
  google-cloud-storage/test/google/cloud/storage/project_signed_url_v4_test.rb
Labels: api: storage, cla: yes, type: feature request

#7102 docs: Update Security Command Center UpdateNotificationConfig sample,…
  google-cloud-security_center/samples/notification.rb
Labels: cla: yes

#7093 [google-cloud-dialogflow] docs: more detailed docs on APIs such as Environment, Intents, Sessions.
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes, context: full

#7092 [google-cloud-dialogflow-v2] docs: more detailed docs on APIs such as Environment, Intents, Sessions.
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/context_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/contexts.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/contexts/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_type_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environment_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environments.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environments/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intent_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_type_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_types.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/sessions.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/sessions/client.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/context.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/environment.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/session_entity_type.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes, context: full

#7106 Release google-cloud-storage 1.27.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes

#7108 feat(bigtable-admin-v2): Add IAMPolicy::Client
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/iam_policy.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/iam_policy/client.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/iam_policy/credentials.rb
  google-cloud-bigtable-admin-v2/lib/google/iam/v1/iam_policy_services_pb.rb
  google-cloud-bigtable-admin-v2/synth.metadata
  google-cloud-bigtable-admin-v2/synth.py
  google-cloud-bigtable-admin-v2/test/google/cloud/bigtable/admin/v2/iam_policy_test.rb
Labels: api: bigtable, cla: yes

#7110 chore(bigtable-v2): Add helpers.rb
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/bigtable/helpers.rb
  google-cloud-bigtable-v2/test/google/cloud/bigtable/v2/bigtable/helpers_test.rb
Labels: api: bigtable, cla: yes

#7111 chore(bigtable-admin-v2): Remove IAMPolicy::Client
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/iam_policy.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/iam_policy/client.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/iam_policy/credentials.rb
  google-cloud-bigtable-admin-v2/lib/google/iam/v1/iam_policy_services_pb.rb
  google-cloud-bigtable-admin-v2/synth.metadata
  google-cloud-bigtable-admin-v2/synth.py
  google-cloud-bigtable-admin-v2/test/google/cloud/bigtable/admin/v2/iam_policy_test.rb
Labels: api: bigtableadmin, cla: yes

#7114 [google-cloud-translate-v3] fix: corrects spelling of build dependency adds backticks in docstring to smooth doc generation
  google-cloud-translate-v3/proto_docs/google/cloud/translate/v3/translation_service.rb
  google-cloud-translate-v3/synth.metadata
Labels: cla: yes, context: full

#7112 [google-cloud-dataproc-v1] feat: Additional fields for the `ClusterConfig` and `InstanceGroupConfig` messages.
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/clusters_pb.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/autoscaling_policies.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/shared.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/workflow_templates.rb
  google-cloud-dataproc-v1/synth.metadata
Labels: cla: yes, context: full

#7107 [google-cloud-dialogflow-v2] feat: added support for custom content types docs: clarified wording around quota usage
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes, context: full
