Repository googleapis/google-cloud-ruby, pull requests merged in 2020-06, with the labels that each got.

#5691 Release google-cloud-kms 2.0.0
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes

#6294 chore(monitoring): Move samples from ruby-docs-samples
  google-cloud-monitoring/samples/Gemfile
  google-cloud-monitoring/samples/README.md
  google-cloud-monitoring/samples/Rakefile
  google-cloud-monitoring/samples/acceptance/helper.rb
  google-cloud-monitoring/samples/acceptance/metrics_test.rb
  google-cloud-monitoring/samples/acceptance/quickstart_test.rb
  google-cloud-monitoring/samples/acceptance/uptime_check_test.rb
  google-cloud-monitoring/samples/metrics.rb
  google-cloud-monitoring/samples/quickstart.rb
  google-cloud-monitoring/samples/uptime_check.rb
Labels: cla: yes

#6302 Release google-cloud-phishing_protection 0.10.0
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes

#6299 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes, context: full

#6306 Release google-cloud-talent 0.20.0
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes

#6307 Release google-cloud-monitoring 1.0.0
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes

#6308 Release google-cloud-vision 1.0.0
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: autorelease: pending, cla: yes

#6300 Add ruby 2.7.1 and update bundler 2.1.4
  .kokoro/docker/autosynth/Dockerfile
  .kokoro/docker/multi/Dockerfile
  .kokoro/docker/release/Dockerfile
  .kokoro/osx.sh
  .kokoro/templates/autosynth.Dockerfile.erb
  .kokoro/templates/multi.Dockerfile.erb
  .kokoro/templates/release.Dockerfile.erb
  .kokoro/trampoline.sh
  Rakefile
  google-cloud-spanner/google-cloud-spanner.gemspec
Labels: cla: yes

#6315 chore: Kick linkinator can till after the fixit 2 weeks
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#6310 feat: Initial microgen of google-cloud-container_analysis-v1
  .kokoro/continuous/linux/container_analysis-v1.cfg
  .kokoro/continuous/osx/container_analysis-v1.cfg
  .kokoro/continuous/windows/container_analysis-v1.cfg
  .kokoro/nightly/linux/container_analysis-v1.cfg
  .kokoro/nightly/osx/container_analysis-v1.cfg
  .kokoro/nightly/windows/container_analysis-v1.cfg
  .kokoro/release/container_analysis-v1.cfg
  Gemfile
  google-cloud-container_analysis-v1/.gitignore
  google-cloud-container_analysis-v1/.repo-metadata.json
  google-cloud-container_analysis-v1/.rubocop.yml
  google-cloud-container_analysis-v1/.yardopts
  google-cloud-container_analysis-v1/AUTHENTICATION.md
  google-cloud-container_analysis-v1/CHANGELOG.md
  google-cloud-container_analysis-v1/Gemfile
  google-cloud-container_analysis-v1/LICENSE.md
  google-cloud-container_analysis-v1/README.md
  google-cloud-container_analysis-v1/Rakefile
  google-cloud-container_analysis-v1/google-cloud-container_analysis-v1.gemspec
  google-cloud-container_analysis-v1/lib/google-cloud-container_analysis-v1.rb
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1.rb
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/container_analysis.rb
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/container_analysis/client.rb
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/container_analysis/credentials.rb
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/container_analysis/helpers.rb
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/version.rb
  google-cloud-container_analysis-v1/lib/google/devtools/containeranalysis/v1/containeranalysis_pb.rb
  google-cloud-container_analysis-v1/lib/google/devtools/containeranalysis/v1/containeranalysis_services_pb.rb
  google-cloud-container_analysis-v1/proto_docs/README.md
  google-cloud-container_analysis-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-container_analysis-v1/proto_docs/google/api/resource.rb
  google-cloud-container_analysis-v1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-container_analysis-v1/proto_docs/google/iam/v1/options.rb
  google-cloud-container_analysis-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-container_analysis-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-container_analysis-v1/proto_docs/google/type/expr.rb
  google-cloud-container_analysis-v1/synth.metadata
  google-cloud-container_analysis-v1/synth.py
  google-cloud-container_analysis-v1/test/google/cloud/container_analysis/v1/container_analysis_test.rb
  google-cloud-container_analysis-v1/test/google/cloud/container_analysis/v1/grafeas_client_test.rb
  google-cloud-container_analysis-v1/test/helper.rb
Labels: cla: yes

#6401 [CHANGE ME] Re-generated google-cloud-web_risk to pick up changes in the API or client library generator.
  google-cloud-web_risk/.rubocop.yml
  google-cloud-web_risk/Gemfile
  google-cloud-web_risk/synth.metadata
Labels: cla: yes, context: none

#6398 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/Gemfile
  google-cloud-vision/synth.metadata
Labels: cla: yes, context: none

#6395 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/.rubocop.yml
  google-cloud-video_intelligence/Gemfile
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes, context: none

#6390 [CHANGE ME] Re-generated google-cloud-translate to pick up changes in the API or client library generator.
  google-cloud-translate/.rubocop.yml
  google-cloud-translate/Gemfile
  google-cloud-translate/synth.metadata
Labels: cla: yes, context: none

#6388 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/.rubocop.yml
  google-cloud-text_to_speech/Gemfile
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes, context: none

#6385 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/.rubocop.yml
  google-cloud-tasks/Gemfile
  google-cloud-tasks/synth.metadata
Labels: cla: yes, context: none

#6381 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/.rubocop.yml
  google-cloud-talent/Gemfile
  google-cloud-talent/synth.metadata
Labels: cla: yes, context: none

#6379 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/.rubocop.yml
  google-cloud-speech/Gemfile
  google-cloud-speech/synth.metadata
Labels: cla: yes, context: none

#6376 [CHANGE ME] Re-generated google-cloud-service_directory to pick up changes in the API or client library generator.
  google-cloud-service_directory/.rubocop.yml
  google-cloud-service_directory/Gemfile
  google-cloud-service_directory/synth.metadata
Labels: cla: yes, context: none

#6374 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/.rubocop.yml
  google-cloud-security_center/Gemfile
  google-cloud-security_center/synth.metadata
Labels: cla: yes, context: none

#6371 [CHANGE ME] Re-generated google-cloud-secret_manager to pick up changes in the API or client library generator.
  google-cloud-secret_manager/.rubocop.yml
  google-cloud-secret_manager/Gemfile
  google-cloud-secret_manager/synth.metadata
Labels: cla: yes, context: none

#6368 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/.rubocop.yml
  google-cloud-scheduler/Gemfile
  google-cloud-scheduler/synth.metadata
Labels: cla: yes, context: none

#6365 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/.rubocop.yml
  google-cloud-redis/Gemfile
  google-cloud-redis/synth.metadata
Labels: cla: yes, context: none

#6362 [CHANGE ME] Re-generated google-cloud-recommender to pick up changes in the API or client library generator.
  google-cloud-recommender/.rubocop.yml
  google-cloud-recommender/Gemfile
  google-cloud-recommender/synth.metadata
Labels: cla: yes, context: none

#6360 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/.rubocop.yml
  google-cloud-recaptcha_enterprise/Gemfile
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes, context: none

#6357 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/.rubocop.yml
  google-cloud-phishing_protection/Gemfile
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes, context: none

#6355 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/.rubocop.yml
  google-cloud-os_login/Gemfile
  google-cloud-os_login/synth.metadata
Labels: cla: yes, context: none

#6352 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/.rubocop.yml
  google-cloud-monitoring/Gemfile
  google-cloud-monitoring/synth.metadata
Labels: cla: yes, context: none

#6348 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/.rubocop.yml
  google-cloud-language/Gemfile
  google-cloud-language/synth.metadata
Labels: cla: yes, context: none

#6345 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/.rubocop.yml
  google-cloud-kms/Gemfile
  google-cloud-kms/synth.metadata
Labels: cla: yes, context: none

#6341 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/.rubocop.yml
  google-cloud-dlp/Gemfile
  google-cloud-dlp/synth.metadata
Labels: cla: yes, context: none

#6339 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/.rubocop.yml
  google-cloud-dialogflow/Gemfile
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes, context: none

#6337 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/.rubocop.yml
  google-cloud-dataproc/Gemfile
  google-cloud-dataproc/synth.metadata
Labels: cla: yes, context: none

#6334 [CHANGE ME] Re-generated google-cloud-data_catalog to pick up changes in the API or client library generator.
  google-cloud-data_catalog/.rubocop.yml
  google-cloud-data_catalog/Gemfile
  google-cloud-data_catalog/synth.metadata
Labels: cla: yes, context: none

#6332 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/.rubocop.yml
  google-cloud-container/Gemfile
  google-cloud-container/google-cloud-container.gemspec
  google-cloud-container/synth.metadata
Labels: cla: yes, context: none

#6329 [CHANGE ME] Re-generated google-cloud-billing to pick up changes in the API or client library generator.
  google-cloud-billing/.rubocop.yml
  google-cloud-billing/Gemfile
  google-cloud-billing/google-cloud-billing.gemspec
  google-cloud-billing/synth.metadata
Labels: cla: yes, context: none

#6327 [CHANGE ME] Re-generated google-cloud-bigquery-storage to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage/.rubocop.yml
  google-cloud-bigquery-storage/Gemfile
  google-cloud-bigquery-storage/google-cloud-bigquery-storage.gemspec
  google-cloud-bigquery-storage/synth.metadata
Labels: cla: yes, context: none

#6325 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/.rubocop.yml
  google-cloud-bigquery-data_transfer/Gemfile
  google-cloud-bigquery-data_transfer/google-cloud-bigquery-data_transfer.gemspec
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes, context: none

#6323 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/.rubocop.yml
  google-cloud-automl/Gemfile
  google-cloud-automl/google-cloud-automl.gemspec
  google-cloud-automl/synth.metadata
Labels: cla: yes, context: none

#6320 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/.rubocop.yml
  google-cloud-asset/Gemfile
  google-cloud-asset/google-cloud-asset.gemspec
  google-cloud-asset/synth.metadata
Labels: cla: yes, context: none

#6317 [CHANGE ME] Re-generated google-cloud-access_approval to pick up changes in the API or client library generator.
  google-cloud-access_approval/.rubocop.yml
  google-cloud-access_approval/Gemfile
  google-cloud-access_approval/google-cloud-access_approval.gemspec
  google-cloud-access_approval/synth.metadata
Labels: cla: yes, context: none

#6400 [CHANGE ME] Re-generated google-cloud-web_risk-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1beta1/lib/google/cloud/web_risk/v1beta1/web_risk_service/client.rb
  google-cloud-web_risk-v1beta1/synth.metadata
Labels: cla: yes, context: none

#6399 [CHANGE ME] Re-generated google-cloud-web_risk-v1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1/lib/google/cloud/web_risk/v1/web_risk_service/client.rb
  google-cloud-web_risk-v1/synth.metadata
Labels: cla: yes, context: none

#6342 [google-cloud-firestore] firestore: add BatchWrite
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client_config.json
  google-cloud-firestore/lib/google/firestore/v1/firestore_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/firestore_services_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/query_pb.rb
  google-cloud-firestore/synth.metadata
  google-cloud-firestore/test/google/cloud/firestore/v1/firestore_client_test.rb
Labels: cla: yes, context: full

#6397 [CHANGE ME] Re-generated google-cloud-vision-v1p3beta1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/image_annotator/client.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/image_annotator/operations.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/product_search/client.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/product_search/operations.rb
  google-cloud-vision-v1p3beta1/synth.metadata
Labels: cla: yes, context: none

#6396 [CHANGE ME] Re-generated google-cloud-vision-v1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search/operations.rb
  google-cloud-vision-v1/synth.metadata
Labels: cla: yes, context: none

#6394 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p2beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1p2beta1/synth.metadata
Labels: cla: yes, context: none

#6393 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#6392 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1beta2/synth.metadata
Labels: cla: yes, context: none

#6391 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1/synth.metadata
Labels: cla: yes, context: none

#6389 [CHANGE ME] Re-generated google-cloud-translate-v3 to pick up changes in the API or client library generator.
  google-cloud-translate-v3/lib/google/cloud/translate/v3/translation_service/client.rb
  google-cloud-translate-v3/lib/google/cloud/translate/v3/translation_service/operations.rb
  google-cloud-translate-v3/synth.metadata
Labels: cla: yes, context: none

#6387 [google-cloud-text_to_speech-v1beta1] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/text_to_speech/v1beta1/text_to_speech/client.rb
  google-cloud-text_to_speech-v1beta1/proto_docs/google/cloud/texttospeech/v1beta1/cloud_tts.rb
  google-cloud-text_to_speech-v1beta1/synth.metadata
Labels: cla: yes, context: partial

#6386 [google-cloud-text_to_speech-v1] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-text_to_speech-v1/lib/google/cloud/text_to_speech/v1/text_to_speech/client.rb
  google-cloud-text_to_speech-v1/proto_docs/google/cloud/texttospeech/v1/cloud_tts.rb
  google-cloud-text_to_speech-v1/synth.metadata
Labels: cla: yes, context: partial

#6384 [CHANGE ME] Re-generated google-cloud-tasks-v2beta3 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta3/lib/google/cloud/tasks/v2beta3/cloud_tasks/client.rb
  google-cloud-tasks-v2beta3/synth.metadata
Labels: cla: yes, context: none

#6383 [CHANGE ME] Re-generated google-cloud-tasks-v2beta2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/cloud_tasks/client.rb
  google-cloud-tasks-v2beta2/synth.metadata
Labels: cla: yes, context: none

#6382 [CHANGE ME] Re-generated google-cloud-tasks-v2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/cloud_tasks/client.rb
  google-cloud-tasks-v2/synth.metadata
Labels: cla: yes, context: none

#6380 [CHANGE ME] Re-generated google-cloud-talent-v4beta1 to pick up changes in the API or client library generator.
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/application_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/company_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/completion/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/event_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/job_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/job_service/operations.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/profile_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/tenant_service/client.rb
  google-cloud-talent-v4beta1/synth.metadata
Labels: cla: yes, context: none

#6378 [CHANGE ME] Re-generated google-cloud-speech-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/speech/client.rb
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/speech/operations.rb
  google-cloud-speech-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#6377 [CHANGE ME] Re-generated google-cloud-speech-v1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1/lib/google/cloud/speech/v1/speech/client.rb
  google-cloud-speech-v1/lib/google/cloud/speech/v1/speech/operations.rb
  google-cloud-speech-v1/synth.metadata
Labels: cla: yes, context: none

#6375 [CHANGE ME] Re-generated google-cloud-service_directory-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/lookup_service/client.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service/client.rb
  google-cloud-service_directory-v1beta1/synth.metadata
Labels: cla: yes, context: none

#6373 [CHANGE ME] Re-generated google-cloud-security_center-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/security_center/client.rb
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/security_center/operations.rb
  google-cloud-security_center-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#6313 chore: Pin ubuntu to bionic in docker images
  .kokoro/docker/autosynth/Dockerfile
  .kokoro/docker/release/Dockerfile
  .kokoro/osx.sh
  .kokoro/templates/autosynth.Dockerfile.erb
  .kokoro/templates/release.Dockerfile.erb
Labels: cla: yes

#6369 [CHANGE ME] Re-generated google-cloud-secret_manager-v1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes, context: none

#6367 [CHANGE ME] Re-generated google-cloud-scheduler-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1beta1/lib/google/cloud/scheduler/v1beta1/cloud_scheduler/client.rb
  google-cloud-scheduler-v1beta1/synth.metadata
Labels: cla: yes, context: none

#6366 [CHANGE ME] Re-generated google-cloud-scheduler-v1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1/lib/google/cloud/scheduler/v1/cloud_scheduler/client.rb
  google-cloud-scheduler-v1/synth.metadata
Labels: cla: yes, context: none

#6364 [google-cloud-redis-v1beta1] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/client.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/operations.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis_services_pb.rb
  google-cloud-redis-v1beta1/proto_docs/google/cloud/redis/v1beta1/cloud_redis.rb
  google-cloud-redis-v1beta1/synth.metadata
Labels: cla: yes, context: partial

#6363 [google-cloud-redis-v1] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/client.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/operations.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis_services_pb.rb
  google-cloud-redis-v1/proto_docs/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis-v1/synth.metadata
Labels: cla: yes, context: partial

#6361 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes, context: none

#6359 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise-v1beta1/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_service/client.rb
  google-cloud-recaptcha_enterprise-v1beta1/synth.metadata
Labels: cla: yes, context: none

#6358 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise-v1 to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise-v1/lib/google/cloud/recaptcha_enterprise/v1/recaptcha_enterprise_service/client.rb
  google-cloud-recaptcha_enterprise-v1/synth.metadata
Labels: cla: yes, context: none

#6354 [CHANGE ME] Re-generated google-cloud-os_login-v1beta to pick up changes in the API or client library generator.
  google-cloud-os_login-v1beta/lib/google/cloud/os_login/v1beta/os_login_service/client.rb
  google-cloud-os_login-v1beta/synth.metadata
Labels: cla: yes, context: none

#6351 [CHANGE ME] Re-generated google-cloud-monitoring-v3 to pick up changes in the API or client library generator.
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/alert_policy_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/group_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/metric_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/notification_channel_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/service_monitoring_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/uptime_check_service/client.rb
  google-cloud-monitoring-v3/synth.metadata
Labels: cla: yes, context: none

#6349 [CHANGE ME] Re-generated google-cloud-memcache-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/cloud_memcache/client.rb
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/cloud_memcache/operations.rb
  google-cloud-memcache-v1beta2/synth.metadata
Labels: cla: yes, context: none

#6347 [CHANGE ME] Re-generated google-cloud-language-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes, context: none

#6346 [CHANGE ME] Re-generated google-cloud-language-v1 to pick up changes in the API or client library generator.
  google-cloud-language-v1/lib/google/cloud/language/v1/language_service/client.rb
  google-cloud-language-v1/synth.metadata
Labels: cla: yes, context: none

#6343 [CHANGE ME] Re-generated google-cloud-iot-v1 to pick up changes in the API or client library generator.
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager/client.rb
  google-cloud-iot-v1/synth.metadata
Labels: cla: yes, context: none

#6340 [CHANGE ME] Re-generated google-cloud-dlp-v2 to pick up changes in the API or client library generator.
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/dlp_service/client.rb
  google-cloud-dlp-v2/synth.metadata
Labels: cla: yes, context: none

#6338 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/contexts/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environments/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/sessions/client.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes, context: none

#6336 [CHANGE ME] Re-generated google-cloud-dataproc-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/cluster_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/cluster_controller/operations.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller/operations.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_template_service/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_template_service/operations.rb
  google-cloud-dataproc-v1beta2/synth.metadata
Labels: cla: yes, context: none

#6335 [CHANGE ME] Re-generated google-cloud-dataproc-v1 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/autoscaling_policy_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/operations.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/operations.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_template_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_template_service/operations.rb
  google-cloud-dataproc-v1/synth.metadata
Labels: cla: yes, context: none

#6333 [CHANGE ME] Re-generated google-cloud-data_catalog-v1 to pick up changes in the API or client library generator.
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/data_catalog/client.rb
  google-cloud-data_catalog-v1/synth.metadata
Labels: cla: yes, context: none

#6330 [CHANGE ME] Re-generated google-cloud-container-v1 to pick up changes in the API or client library generator.
  google-cloud-container-v1/lib/google/cloud/container/v1/cluster_manager/client.rb
  google-cloud-container-v1/synth.metadata
Labels: cla: yes, context: none

#6328 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/client.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes, context: none

#6326 [CHANGE ME] Re-generated google-cloud-bigquery-storage-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/big_query_read/client.rb
  google-cloud-bigquery-storage-v1/synth.metadata
Labels: cla: yes, context: none

#6324 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer-v1/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service/client.rb
  google-cloud-bigquery-data_transfer-v1/synth.metadata
Labels: cla: yes, context: none

#6322 [CHANGE ME] Re-generated google-cloud-automl-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/automl/client.rb
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/automl/operations.rb
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/prediction_service/client.rb
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/prediction_service/operations.rb
  google-cloud-automl-v1beta1/synth.metadata
Labels: cla: yes, context: none

#6321 [CHANGE ME] Re-generated google-cloud-automl-v1 to pick up changes in the API or client library generator.
  google-cloud-automl-v1/lib/google/cloud/automl/v1/automl/client.rb
  google-cloud-automl-v1/lib/google/cloud/automl/v1/automl/operations.rb
  google-cloud-automl-v1/lib/google/cloud/automl/v1/prediction_service/client.rb
  google-cloud-automl-v1/lib/google/cloud/automl/v1/prediction_service/operations.rb
  google-cloud-automl-v1/synth.metadata
Labels: cla: yes, context: none

#6319 [CHANGE ME] Re-generated google-cloud-asset-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1beta1/lib/google/cloud/asset/v1beta1/asset_service/client.rb
  google-cloud-asset-v1beta1/lib/google/cloud/asset/v1beta1/asset_service/operations.rb
  google-cloud-asset-v1beta1/synth.metadata
Labels: cla: yes, context: none

#6318 [CHANGE ME] Re-generated google-cloud-asset-v1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/operations.rb
  google-cloud-asset-v1/synth.metadata
Labels: cla: yes, context: none

#6316 [CHANGE ME] Re-generated google-cloud-access_approval-v1 to pick up changes in the API or client library generator.
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/access_approval/client.rb
  google-cloud-access_approval-v1/synth.metadata
Labels: cla: yes, context: none

#6403 Release grafeas-v1 0.1.0
  grafeas-v1/CHANGELOG.md
  grafeas-v1/lib/grafeas/v1/version.rb
Labels: autorelease: pending, cla: yes

#6404 Release google-cloud-container_analysis-v1 0.1.0
  google-cloud-container_analysis-v1/CHANGELOG.md
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/version.rb
Labels: autorelease: pending, cla: yes

#6457 [google-cloud-dataproc-v1] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc-v1/synth.metadata
Labels: cla: yes, context: full

#6459 [google-cloud-dlp-v2] docs: fix several broken links in the docs.
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp-v2/synth.metadata
Labels: cla: yes, context: full

#6458 [google-cloud-dataproc-v1beta2] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-dataproc-v1beta2/proto_docs/google/cloud/dataproc/v1beta2/jobs.rb
  google-cloud-dataproc-v1beta2/synth.metadata
Labels: cla: yes, context: full

#6464 [google-cloud-container-v1] docs: fix a broken link in the docs.
  google-cloud-container-v1/proto_docs/google/container/v1/cluster_service.rb
  google-cloud-container-v1/synth.metadata
Labels: cla: yes, context: full

#6465 [google-cloud-container-v1beta1] docs: fix a broken link in the docs.
  google-cloud-container-v1beta1/proto_docs/google/container/v1beta1/cluster_service.rb
  google-cloud-container-v1beta1/synth.metadata
Labels: cla: yes, context: full

#6466 [google-cloud-data_catalog-v1] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/gcs_fileset_spec.rb
  google-cloud-data_catalog-v1/synth.metadata
Labels: cla: yes, context: full

#6469 [google-cloud-error_reporting] docs: fix several broken links in the docs.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_group_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes, context: full

#6470 [google-cloud-kms-v1] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-kms-v1/proto_docs/google/cloud/kms/v1/resources.rb
  google-cloud-kms-v1/synth.metadata
Labels: cla: yes, context: full

#6471 [google-cloud-monitoring-dashboard-v1] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-monitoring-dashboard-v1/proto_docs/google/monitoring/dashboard/v1/common.rb
  google-cloud-monitoring-dashboard-v1/proto_docs/google/monitoring/dashboard/v1/metrics.rb
  google-cloud-monitoring-dashboard-v1/synth.metadata
Labels: cla: yes, context: full

#6472 [google-cloud-monitoring-v3] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-monitoring-v3/proto_docs/google/monitoring/v3/common.rb
  google-cloud-monitoring-v3/synth.metadata
Labels: cla: yes, context: full

#6474 [google-cloud-talent-v4beta1] docs: Remove a broken link from the documentation.
  google-cloud-talent-v4beta1/proto_docs/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent-v4beta1/synth.metadata
Labels: cla: yes, context: full

#6455 Release google-cloud-vision-v1 0.2.2
  google-cloud-vision-v1/CHANGELOG.md
  google-cloud-vision-v1/lib/google/cloud/vision/v1/version.rb
Labels: autorelease: pending, cla: yes

#6453 Release google-cloud-security_center-v1p1beta1 0.2.2
  google-cloud-security_center-v1p1beta1/CHANGELOG.md
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6452 Release google-cloud-security_center-v1 0.2.2
  google-cloud-security_center-v1/CHANGELOG.md
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/version.rb
Labels: autorelease: pending, cla: yes

#6450 Release google-cloud-redis-v1 0.2.2
  google-cloud-redis-v1/CHANGELOG.md
  google-cloud-redis-v1/lib/google/cloud/redis/v1/version.rb
Labels: autorelease: pending, cla: yes

#6449 Release google-cloud-video_intelligence-v1p2beta1 0.2.2
  google-cloud-video_intelligence-v1p2beta1/CHANGELOG.md
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/video_intelligence/v1p2beta1/version.rb
Labels: autorelease: pending, cla: yes

#6448 Release google-cloud-tasks-v2 0.2.2
  google-cloud-tasks-v2/CHANGELOG.md
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/version.rb
Labels: autorelease: pending, cla: yes

#6447 Release google-cloud-translate-v3 0.1.1
  google-cloud-translate-v3/CHANGELOG.md
  google-cloud-translate-v3/lib/google/cloud/translate/v3/version.rb
Labels: autorelease: pending, cla: yes

#6446 Release google-cloud-text_to_speech-v1beta1 0.2.2
  google-cloud-text_to_speech-v1beta1/CHANGELOG.md
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/text_to_speech/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6445 Release google-cloud-vision-v1p3beta1 0.2.2
  google-cloud-vision-v1p3beta1/CHANGELOG.md
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/version.rb
Labels: autorelease: pending, cla: yes

#6444 Release google-cloud-tasks-v2beta3 0.2.2
  google-cloud-tasks-v2beta3/CHANGELOG.md
  google-cloud-tasks-v2beta3/lib/google/cloud/tasks/v2beta3/version.rb
Labels: autorelease: pending, cla: yes

#6443 Release google-cloud-speech-v1p1beta1 0.3.2
  google-cloud-speech-v1p1beta1/CHANGELOG.md
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6442 Release google-cloud-os_login-v1beta 0.2.2
  google-cloud-os_login-v1beta/CHANGELOG.md
  google-cloud-os_login-v1beta/lib/google/cloud/os_login/v1beta/version.rb
Labels: autorelease: pending, cla: yes

#6441 Release google-cloud-video_intelligence-v1 0.2.2
  google-cloud-video_intelligence-v1/CHANGELOG.md
  google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/version.rb
Labels: autorelease: pending, cla: yes

#6440 Release google-cloud-phishing_protection-v1beta1 0.1.1
  google-cloud-phishing_protection-v1beta1/CHANGELOG.md
  google-cloud-phishing_protection-v1beta1/lib/google/cloud/phishing_protection/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6439 Release google-cloud-secret_manager-v1 0.4.2
  google-cloud-secret_manager-v1/CHANGELOG.md
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/version.rb
Labels: autorelease: pending, cla: yes

#6438 Release google-cloud-speech-v1 0.2.2
  google-cloud-speech-v1/CHANGELOG.md
  google-cloud-speech-v1/lib/google/cloud/speech/v1/version.rb
Labels: autorelease: pending, cla: yes

#6437 Release google-cloud-scheduler-v1beta1 0.2.2
  google-cloud-scheduler-v1beta1/CHANGELOG.md
  google-cloud-scheduler-v1beta1/lib/google/cloud/scheduler/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6435 Release google-cloud-video_intelligence-v1p1beta1 0.2.2
  google-cloud-video_intelligence-v1p1beta1/CHANGELOG.md
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6436 Release google-cloud-recaptcha_enterprise-v1 0.2.2
  google-cloud-recaptcha_enterprise-v1/CHANGELOG.md
  google-cloud-recaptcha_enterprise-v1/lib/google/cloud/recaptcha_enterprise/v1/version.rb
Labels: autorelease: pending, cla: yes

#6434 Release google-cloud-dataproc-v1 0.2.2
  google-cloud-dataproc-v1/CHANGELOG.md
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/version.rb
Labels: autorelease: pending, cla: yes

#6433 Release google-cloud-language-v1beta2 0.2.2
  google-cloud-language-v1beta2/CHANGELOG.md
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#6432 Release google-cloud-recommender-v1 0.4.2
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
Labels: autorelease: pending, cla: yes

#6430 Release google-cloud-web_risk-v1 0.2.2
  google-cloud-web_risk-v1/CHANGELOG.md
  google-cloud-web_risk-v1/lib/google/cloud/web_risk/v1/version.rb
Labels: autorelease: pending, cla: yes

#6429 Release google-cloud-service_directory-v1beta1 0.4.2
  google-cloud-service_directory-v1beta1/CHANGELOG.md
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6428 Release google-cloud-redis-v1beta1 0.2.2
  google-cloud-redis-v1beta1/CHANGELOG.md
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6426 Release google-cloud-tasks-v2beta2 0.2.2
  google-cloud-tasks-v2beta2/CHANGELOG.md
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/version.rb
Labels: autorelease: pending, cla: yes

#6425 Release google-cloud-recaptcha_enterprise-v1beta1 0.2.2
  google-cloud-recaptcha_enterprise-v1beta1/CHANGELOG.md
  google-cloud-recaptcha_enterprise-v1beta1/lib/google/cloud/recaptcha_enterprise/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6424 Release google-cloud-secret_manager-v1beta1 0.6.2
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6423 Release google-cloud-video_intelligence-v1beta2 0.2.2
  google-cloud-video_intelligence-v1beta2/CHANGELOG.md
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/video_intelligence/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#6421 Release google-cloud-os_login-v1 0.2.2
  google-cloud-os_login-v1/CHANGELOG.md
  google-cloud-os_login-v1/lib/google/cloud/os_login/v1/version.rb
Labels: autorelease: pending, cla: yes

#6420 Release google-cloud-text_to_speech-v1 0.2.2
  google-cloud-text_to_speech-v1/CHANGELOG.md
  google-cloud-text_to_speech-v1/lib/google/cloud/text_to_speech/v1/version.rb
Labels: autorelease: pending, cla: yes

#6405 Release google-cloud-scheduler-v1 0.2.2
  google-cloud-scheduler-v1/CHANGELOG.md
  google-cloud-scheduler-v1/lib/google/cloud/scheduler/v1/version.rb
Labels: autorelease: pending, cla: yes

#6402 Release google-cloud-web_risk-v1beta1 0.2.2
  google-cloud-web_risk-v1beta1/CHANGELOG.md
  google-cloud-web_risk-v1beta1/lib/google/cloud/web_risk/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6409 Release google-cloud-language-v1 0.2.2
  google-cloud-language-v1/CHANGELOG.md
  google-cloud-language-v1/lib/google/cloud/language/v1/version.rb
Labels: autorelease: pending, cla: yes

#6419 Release google-cloud-dialogflow-v2 0.6.2
  google-cloud-dialogflow-v2/CHANGELOG.md
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/version.rb
Labels: autorelease: pending, cla: yes

#6418 Release google-cloud-dataproc-v1beta2 0.2.2
  google-cloud-dataproc-v1beta2/CHANGELOG.md
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#6417 Release google-cloud-automl-v1beta1 0.2.3
  google-cloud-automl-v1beta1/CHANGELOG.md
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6413 Release google-cloud-asset-v1 0.4.3
  google-cloud-asset-v1/CHANGELOG.md
  google-cloud-asset-v1/lib/google/cloud/asset/v1/version.rb
Labels: autorelease: pending, cla: yes

#6407 Release google-cloud-access_approval-v1 0.2.2
  google-cloud-access_approval-v1/CHANGELOG.md
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/version.rb
Labels: autorelease: pending, cla: yes

#6408 Release google-cloud-billing-v1 0.5.2
  google-cloud-billing-v1/CHANGELOG.md
  google-cloud-billing-v1/lib/google/cloud/billing/v1/version.rb
Labels: autorelease: pending, cla: yes

#6410 Release google-cloud-asset-v1beta1 0.2.2
  google-cloud-asset-v1beta1/CHANGELOG.md
  google-cloud-asset-v1beta1/lib/google/cloud/asset/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#6411 Release google-cloud-bigquery-storage-v1 0.2.2
  google-cloud-bigquery-storage-v1/CHANGELOG.md
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/version.rb
Labels: autorelease: pending, cla: yes

#6412 Release google-cloud-bigquery-data_transfer-v1 0.2.2
  google-cloud-bigquery-data_transfer-v1/CHANGELOG.md
  google-cloud-bigquery-data_transfer-v1/lib/google/cloud/bigquery/data_transfer/v1/version.rb
Labels: autorelease: pending, cla: yes

#6476 [google-cloud-container-v1] docs: Fixed broken links in the reference documentation
  google-cloud-container-v1/proto_docs/google/container/v1/cluster_service.rb
  google-cloud-container-v1/synth.metadata
Labels: cla: yes, context: full

#6477 [google-cloud-container-v1beta1] docs: Fixed broken links in the reference documentation
  google-cloud-container-v1beta1/proto_docs/google/container/v1beta1/cluster_service.rb
  google-cloud-container-v1beta1/synth.metadata
Labels: cla: yes, context: full

#6467 [google-cloud-dialogflow-v2] docs: cleaned docs for the Agents service and resource.
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agent_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/client.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes, context: full

#6468 [google-cloud-dialogflow] docs: cleaned docs for the Agents service and resource.
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes, context: full
