Repository googleapis/google-cloud-ruby, pull requests merged in 2020-02, with the labels that each got.

#4759 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/image_annotator.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/image_annotator_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/image_annotator_services_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_service_pb.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_service_services_pb.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#4763 fix(docs): List all projects example
  google-cloud-resource_manager/README.md
Labels: cla: yes

#4758 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/autoscaling_policy_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/autoscaling_policy_service_client_config.json
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/autoscaling_policies.rb
  google-cloud-dataproc/synth.metadata
  google-cloud-dataproc/test/google/cloud/dataproc/v1/autoscaling_policy_service_client_test.rb
Labels: cla: yes

#4767 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4766 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/proto_docs/google/api/resource.rb
  google-cloud-billing-v1/proto_docs/google/cloud/billing/v1/cloud_billing.rb
  google-cloud-billing-v1/proto_docs/google/cloud/billing/v1/cloud_catalog.rb
  google-cloud-billing-v1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-billing-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-billing-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#4768 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/resources.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/service.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/iam/v1/policy.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#4746 Release google-cloud-video_intelligence 2.0.3
  google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4752 Release google-cloud-asset 0.7.0
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4756 Release google-cloud-monitoring 0.35.0
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4757 Release google-cloud-pubsub 1.2.2
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4760 Release google-cloud-vision 0.37.3
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4764 Release google-cloud-resource_manager 0.33.1
  google-cloud-resource_manager/CHANGELOG.md
  google-cloud-resource_manager/lib/google/cloud/resource_manager/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4769 Release google-cloud-dialogflow 0.12.2
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4765 Release google-cloud-dataproc 0.8.0
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4771 docs(secret_manager): change a few readme references from language to secret-manager
  google-cloud-secret_manager/README.md
Labels: cla: yes

#4772 chore: Add billing veneer library
  Gemfile
  google-cloud-billing/.gitignore
  google-cloud-billing/.repo-metadata.json
  google-cloud-billing/.rubocop.yml
  google-cloud-billing/.yardopts
  google-cloud-billing/AUTHENTICATION.md
  google-cloud-billing/CHANGELOG.md
  google-cloud-billing/Gemfile
  google-cloud-billing/LICENSE
  google-cloud-billing/README.md
  google-cloud-billing/Rakefile
  google-cloud-billing/google-cloud-billing.gemspec
  google-cloud-billing/lib/google-cloud-billing.rb
  google-cloud-billing/lib/google/cloud/billing.rb
  google-cloud-billing/lib/google/cloud/billing/version.rb
  google-cloud-billing/test/google/cloud/billing/version_test.rb
  google-cloud-billing/test/helper.rb
Labels: cla: yes

#4778 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4776 chore(asset): add orgpolicy protos to the library
  google-cloud-asset/lib/google/cloud/orgpolicy/v1/doc/google/cloud/orgpolicy/v1/orgpolicy.rb
  google-cloud-asset/lib/google/cloud/orgpolicy/v1/orgpolicy_pb.rb
  google-cloud-asset/synth.metadata
  google-cloud-asset/synth.py
Labels: api: cloudasset, cla: yes

#4777 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing_pb.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog_pb.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#4779 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secrets/v1beta1/resources_pb.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secrets/v1beta1/service_pb.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#4780 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client_config.json
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4734 [Recommender][Synth] Synth.py for the google-cloud-recommender and th…
  Gemfile
  google-cloud-recommender-v1/.gitignore
  google-cloud-recommender-v1/.repo-metadata.json
  google-cloud-recommender-v1/.rubocop.yml
  google-cloud-recommender-v1/.yardopts
  google-cloud-recommender-v1/AUTHENTICATION.md
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/Gemfile
  google-cloud-recommender-v1/LICENSE.md
  google-cloud-recommender-v1/README.md
  google-cloud-recommender-v1/Rakefile
  google-cloud-recommender-v1/google-cloud-recommender-v1.gemspec
  google-cloud-recommender-v1/lib/google-cloud-recommender-v1.rb
  google-cloud-recommender-v1/lib/google/cloud/common_resources_pb.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommendation_pb.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/credentials.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/paths.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender_service_pb.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender_service_services_pb.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
  google-cloud-recommender-v1/proto_docs/README.md
  google-cloud-recommender-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-recommender-v1/proto_docs/google/api/resource.rb
  google-cloud-recommender-v1/proto_docs/google/cloud/recommender/v1/recommendation.rb
  google-cloud-recommender-v1/proto_docs/google/cloud/recommender/v1/recommender_service.rb
  google-cloud-recommender-v1/proto_docs/google/protobuf/duration.rb
  google-cloud-recommender-v1/proto_docs/google/protobuf/struct.rb
  google-cloud-recommender-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-recommender-v1/proto_docs/google/type/money.rb
  google-cloud-recommender-v1/synth.metadata
  google-cloud-recommender-v1/synth.py
  google-cloud-recommender-v1/test/google/cloud/recommender/v1/recommender_test.rb
Labels: cla: yes

#4785 chore: Add recommender veneer library
  Gemfile
  google-cloud-recommender/.gitignore
  google-cloud-recommender/.repo-metadata.json
  google-cloud-recommender/.rubocop.yml
  google-cloud-recommender/.yardopts
  google-cloud-recommender/AUTHENTICATION.md
  google-cloud-recommender/CHANGELOG.md
  google-cloud-recommender/Gemfile
  google-cloud-recommender/LICENSE
  google-cloud-recommender/README.md
  google-cloud-recommender/Rakefile
  google-cloud-recommender/google-cloud-recommender.gemspec
  google-cloud-recommender/lib/google-cloud-recommender.rb
  google-cloud-recommender/lib/google/cloud/recommender.rb
  google-cloud-recommender/lib/google/cloud/recommender/version.rb
  google-cloud-recommender/test/google/cloud/recommender/version_test.rb
  google-cloud-recommender/test/helper.rb
Labels: cla: yes

#4786 chore: add kokoro configs for billing and recommender
  .kokoro/continuous/linux/billing-v1.cfg
  .kokoro/continuous/linux/billing.cfg
  .kokoro/continuous/linux/recommender-v1.cfg
  .kokoro/continuous/linux/recommender.cfg
  .kokoro/continuous/osx/billing-v1.cfg
  .kokoro/continuous/osx/billing.cfg
  .kokoro/continuous/osx/recommender-v1.cfg
  .kokoro/continuous/osx/recommender.cfg
  .kokoro/continuous/windows/billing-v1.cfg
  .kokoro/continuous/windows/billing.cfg
  .kokoro/continuous/windows/recommender-v1.cfg
  .kokoro/continuous/windows/recommender.cfg
  .kokoro/nightly/linux/billing-v1.cfg
  .kokoro/nightly/linux/billing.cfg
  .kokoro/nightly/linux/recommender-v1.cfg
  .kokoro/nightly/linux/recommender.cfg
  .kokoro/nightly/osx/billing-v1.cfg
  .kokoro/nightly/osx/billing.cfg
  .kokoro/nightly/osx/recommender-v1.cfg
  .kokoro/nightly/osx/recommender.cfg
  .kokoro/nightly/windows/billing-v1.cfg
  .kokoro/nightly/windows/billing.cfg
  .kokoro/nightly/windows/recommender-v1.cfg
  .kokoro/nightly/windows/recommender.cfg
  .kokoro/release/billing-v1.cfg
  .kokoro/release/billing.cfg
  .kokoro/release/recommender-v1.cfg
  .kokoro/release/recommender.cfg
Labels: cla: yes

#4773 Release google-cloud-secret_manager 0.2.1
  google-cloud-secret_manager/CHANGELOG.md
  google-cloud-secret_manager/lib/google/cloud/secret_manager/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4784 Release google-cloud-tasks 1.3.5
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4783 Release google-cloud-dialogflow 0.12.3
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4747 Release google-cloud-secret_manager-v1beta1 0.2.1
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4774 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_services_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client_config.json
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_services_pb.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/cloud/redis/v1beta1/cloud_redis.rb
  google-cloud-redis/synth.metadata
  google-cloud-redis/test/google/cloud/redis/v1beta1/cloud_redis_client_test.rb
Labels: cla: yes

#4791 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/synth.metadata
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/intents_client_test.rb
Labels: cla: yes

#4706 Add support for Pub/Sub Dead Letter Queues
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
  google-cloud-pubsub/acceptance/pubsub_helper.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/received_message.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/received_message_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/inventory_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/attrs_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/update_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/subscribe_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: api: pubsub, cla: yes

#4794 chore(asset): move orgpolicy docs to the correct location
  google-cloud-asset/synth.py
Labels: cla: yes

#4788 test(spanner): fix tests to avoid repeated updates to stubbed method calls.
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/execute_partition_test.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/execute_partition_update_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/execute_query_resume_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/execute_query_single_use_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/fields_for_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/reset_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/snapshot_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/transaction_retry_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/transaction_rollback_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/transaction_test.rb
  google-cloud-spanner/test/google/cloud/spanner/pool/keepalive_or_release_test.rb
  google-cloud-spanner/test/google/cloud/spanner/session/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/session/keepalive_test.rb
  google-cloud-spanner/test/google/cloud/spanner/snapshot/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/batch_update_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/execute_update_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/fields_for_test.rb
  google-cloud-spanner/test/google/cloud/spanner_test.rb
  google-cloud-spanner/test/helper.rb
Labels: cla: yes

#4798 feat(security_center): add support for v1p1beta1
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/asset_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/credentials.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/cloud/securitycenter/v1p1beta1/asset.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/cloud/securitycenter/v1p1beta1/finding.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/cloud/securitycenter/v1p1beta1/notification_config.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/cloud/securitycenter/v1p1beta1/organization_settings.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/cloud/securitycenter/v1p1beta1/security_marks.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/cloud/securitycenter/v1p1beta1/securitycenter_service.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/cloud/securitycenter/v1p1beta1/source.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/iam/v1/iam_policy.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/iam/v1/options.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/iam/v1/policy.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/longrunning/operations.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/protobuf/any.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/protobuf/duration.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/protobuf/empty.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/protobuf/struct.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/rpc/status.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/doc/google/type/expr.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/finding_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/helpers.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/notification_config_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/notification_message_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/organization_settings_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/run_asset_discovery_response_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/security_center_client_config.json
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/security_marks_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/securitycenter_service_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/securitycenter_service_services_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/source_pb.rb
  google-cloud-security_center/synth.metadata
  google-cloud-security_center/synth.py
  google-cloud-security_center/test/google/cloud/security_center/v1p1beta1/helpers_test.rb
  google-cloud-security_center/test/google/cloud/security_center/v1p1beta1/security_center_client_test.rb
Labels: cla: yes

#4799 fix(billing): default to the correct billing service version
  google-cloud-billing/lib/google/cloud/billing.rb
  google-cloud-billing/lib/google/cloud/billing/version.rb
  google-cloud-billing/test/google/cloud/billing/client_test.rb
Labels: cla: yes

#4800 fix(recommender): create the correct type of object
  google-cloud-recommender/lib/google/cloud/recommender.rb
  google-cloud-recommender/test/google/cloud/recommender/client_test.rb
Labels: cla: yes

#4801 test(secret_manager): add basic test for factory methods
  google-cloud-secret_manager/test/google/cloud/secret_manager/client_test.rb
Labels: cla: yes

#4787 Release google-cloud-redis 0.7.0
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4792 Release google-cloud-dialogflow 0.13.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4806 Release google-cloud-security_center 0.6.0
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4789 Release google-cloud-bigtable 1.1.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4793 Release google-cloud-pubsub 1.3.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4803 Release google-cloud-recommender-v1 0.1.0
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
Labels: autorelease: pending, cla: yes

#4802 Release google-cloud-billing-v1 0.1.0
  google-cloud-billing-v1/CHANGELOG.md
  google-cloud-billing-v1/lib/google/cloud/billing/v1/version.rb
Labels: autorelease: pending, cla: yes

#4805 Release google-cloud-recommender 0.1.0
  google-cloud-recommender/CHANGELOG.md
  google-cloud-recommender/lib/google/cloud/recommender/version.rb
Labels: autorelease: pending, cla: yes

#4804 Release google-cloud-billing 0.1.0
  google-cloud-billing/CHANGELOG.md
  google-cloud-billing/lib/google/cloud/billing/version.rb
Labels: autorelease: pending, cla: yes

#4796 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/log_entry.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_metrics.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/lib/google/logging/v2/log_entry_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_config_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_config_services_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_metrics_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_services_pb.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#4809 Release google-cloud-bigquery 1.19.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4762 feat(spanner): allow custom lib name and version for telemetry purpose
  google-cloud-spanner/lib/google-cloud-spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/service.rb
  google-cloud-spanner/test/google/cloud/spanner_test.rb
Labels: api: spanner, cla: yes

#4807 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/bigtable/admin/v2/bigtable_instance_admin_pb.rb
  google-cloud-bigtable/lib/google/bigtable/admin/v2/bigtable_instance_admin_services_pb.rb
  google-cloud-bigtable/lib/google/bigtable/admin/v2/bigtable_table_admin_pb.rb
  google-cloud-bigtable/lib/google/bigtable/admin/v2/bigtable_table_admin_services_pb.rb
  google-cloud-bigtable/lib/google/bigtable/admin/v2/instance_pb.rb
  google-cloud-bigtable/lib/google/bigtable/admin/v2/table_pb.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client_config.json
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client_config.json
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/bigtable_instance_admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/bigtable_table_admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/table.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4811 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/logging/v2/logging_pb.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#4815 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/README.md
  google-cloud-bigquery-data_transfer/acceptance/google/cloud/bigquery/data_transfer/v1/data_transfer_service_smoke_test.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client_config.json
  google-cloud-bigquery-data_transfer/synth.metadata
  google-cloud-bigquery-data_transfer/test/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client_test.rb
Labels: cla: yes

#4816 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/synth.metadata
  google-cloud-redis/test/google/cloud/redis/v1/cloud_redis_client_test.rb
  google-cloud-redis/test/google/cloud/redis/v1beta1/cloud_redis_client_test.rb
Labels: cla: yes

#4818 Release google-cloud-redis 0.7.1
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes

#4817 Release google-cloud-bigquery-data_transfer 0.6.0
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes

#4808 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/README.md
  google-cloud-container/acceptance/google/cloud/container/v1/cluster_manager_smoke_test.rb
  google-cloud-container/lib/google/cloud/container.rb
  google-cloud-container/lib/google/cloud/container/v1.rb
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1/doc/google/container/v1/cluster_service.rb
  google-cloud-container/synth.metadata
  google-cloud-container/test/google/cloud/container/v1/cluster_manager_client_test.rb
Labels: cla: yes

#4820 Pubsub async fix
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
Labels: api: pubsub, cla: yes

#4797 GCS SigV4 updates
  google-cloud-storage/.rubocop.yml
  google-cloud-storage/conformance/v1/proto/google/cloud/conformance/storage/v1/tests.proto
  google-cloud-storage/conformance/v1/proto/google/cloud/conformance/storage/v1/tests_pb.rb
  google-cloud-storage/conformance/v1/v4_signatures.json
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/file/signer_v4.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/test/google/cloud/storage/bucket_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/file/signer_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/file_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/file_signed_url_v4_test.rb
  google-cloud-storage/test/google/cloud/storage/project_signed_url_v4_test.rb
Labels: api: storage, cla: yes

#4827 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/group_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_services_pb.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4828 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client_config.json
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4814 Release google-cloud-spanner 1.14.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#4824 Release google-cloud-container 0.9.0
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes

#4831 Release google-cloud-monitoring 0.35.1
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes

#4826 Release google-cloud-pubsub 1.3.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#4819 docs(logging): Fix doc links to Cmek methods in lower-level client
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/synth.metadata
  google-cloud-logging/synth.py
Labels: api: logging, cla: yes

#4840 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/.repo-metadata.json
  google-cloud-billing-v1/.rubocop.yml
  google-cloud-billing-v1/README.md
  google-cloud-billing-v1/google-cloud-billing-v1.gemspec
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/client.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#4842 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/.repo-metadata.json
  google-cloud-recommender-v1/.rubocop.yml
  google-cloud-recommender-v1/README.md
  google-cloud-recommender-v1/google-cloud-recommender-v1.gemspec
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes

#4843 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/.repo-metadata.json
  google-cloud-secret_manager-v1beta1/.rubocop.yml
  google-cloud-secret_manager-v1beta1/README.md
  google-cloud-secret_manager-v1beta1/google-cloud-secret_manager-v1beta1.gemspec
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#4852 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/autoscaling_policies_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/clusters_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/clusters_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/jobs_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/jobs_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_templates_services_pb.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4854 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/spanner/admin/instance/v1/spanner_instance_admin.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#4855 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/queue_pb.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4853 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/helpers.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client_config.json
  google-cloud-security_center/synth.metadata
  google-cloud-security_center/test/google/cloud/security_center/v1/helpers_test.rb
  google-cloud-security_center/test/google/cloud/security_center/v1/security_center_client_test.rb
Labels: cla: yes

#4837 Release google-cloud-logging 1.9.5
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#4845 Release google-cloud-billing-v1 0.1.1
  google-cloud-billing-v1/CHANGELOG.md
  google-cloud-billing-v1/lib/google/cloud/billing/v1/version.rb
Labels: autorelease: pending, cla: yes

#4846 Release google-cloud-secret_manager-v1beta1 0.2.2
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#4851 Release google-cloud-recommender-v1 0.1.1
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
Labels: autorelease: pending, cla: yes

#4856 Release google-cloud-dataproc 0.9.0
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes

#4857 Release google-cloud-tasks 1.4.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes

#4859 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/autoscaling_policies_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/clusters_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/clusters_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/jobs_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/jobs_services_pb.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_templates_services_pb.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4849 chore: fix synth of a few more libraries to remove release levels
  google-cloud-bigtable/synth.py
  google-cloud-irm/synth.py
  grafeas/synth.py
Labels: cla: yes

#4823 feat(firestore): Add IN and ARRAY_CONTAINS_ANY query operators
  google-cloud-firestore/acceptance/firestore/query_test.rb
  google-cloud-firestore/lib/google/cloud/firestore/query.rb
  google-cloud-firestore/test/google/cloud/firestore/query/where/array_contains_any_test.rb
  google-cloud-firestore/test/google/cloud/firestore/query/where/in_test.rb
Labels: api: firestore, cla: yes

#4833 feat(bigquery): Add Range Partitioning
  google-cloud-bigquery/acceptance/bigquery/bigquery_test.rb
  google-cloud-bigquery/acceptance/bigquery/dataset_test.rb
  google-cloud-bigquery/acceptance/bigquery/query_destination_test.rb
  google-cloud-bigquery/acceptance/bigquery/table_reference_test.rb
  google-cloud-bigquery/acceptance/bigquery/table_test.rb
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/load_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_load_job_schema_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_reference_test.rb
Labels: api: bigquery, cla: yes

#4868 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/google-cloud-billing-v1.gemspec
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#4869 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/clusters_services_pb.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4870 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/synth.metadata
  google-cloud-irm/test/google/cloud/irm/v1alpha2/helpers_test.rb
Labels: cla: yes

#4871 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/synth.metadata
  google-cloud-kms/test/google/cloud/kms/v1/helpers_test.rb
Labels: cla: yes

#4872 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/synth.metadata
  google-cloud-phishing_protection/test/google/cloud/phishing_protection/v1beta1/helpers_test.rb
Labels: cla: yes

#4873 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_services_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4874 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/synth.metadata
  google-cloud-recaptcha_enterprise/test/google/cloud/recaptcha_enterprise/v1beta1/helpers_test.rb
Labels: cla: yes

#4875 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/google-cloud-recommender-v1.gemspec
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes

#4876 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/synth.metadata
  google-cloud-scheduler/test/google/cloud/scheduler/v1/helpers_test.rb
  google-cloud-scheduler/test/google/cloud/scheduler/v1beta1/helpers_test.rb
Labels: cla: yes

#4877 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/google-cloud-secret_manager-v1beta1.gemspec
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#4883 chore: add some missing simplecov requires to synth templates
  google-cloud-asset/synth/helpers_test.rb.erb
  google-cloud-asset/test/google/cloud/asset/v1/helpers_test.rb
  google-cloud-asset/test/google/cloud/asset/v1beta1/helpers_test.rb
  google-cloud-irm/synth/helpers_test.rb.erb
  google-cloud-irm/test/google/cloud/irm/v1alpha2/helpers_test.rb
  google-cloud-kms/synth/helpers_test.rb.erb
  google-cloud-kms/test/google/cloud/kms/v1/helpers_test.rb
  google-cloud-phishing_protection/synth/helpers_test.rb.erb
  google-cloud-phishing_protection/test/google/cloud/phishing_protection/v1beta1/helpers_test.rb
  google-cloud-recaptcha_enterprise/synth/helpers_test.rb.erb
  google-cloud-recaptcha_enterprise/test/google/cloud/recaptcha_enterprise/v1beta1/helpers_test.rb
  google-cloud-scheduler/synth/helpers_test.rb.erb
  google-cloud-scheduler/test/google/cloud/scheduler/v1/helpers_test.rb
  google-cloud-scheduler/test/google/cloud/scheduler/v1beta1/helpers_test.rb
  google-cloud-security_center/synth/helpers_test.rb.erb
  google-cloud-talent/synth/helpers_test.rb.erb
  google-cloud-vision/synth/helpers_smoke_test.rb.erb
  google-cloud-vision/synth/helpers_test.rb.erb
Labels: cla: yes

#4888 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/spanner/admin/database/v1/spanner_database_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/spanner/admin/instance/v1/spanner_instance_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/mutation.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/lib/google/spanner/admin/database/v1/spanner_database_admin_services_pb.rb
  google-cloud-spanner/lib/google/spanner/admin/instance/v1/spanner_instance_admin_services_pb.rb
  google-cloud-spanner/lib/google/spanner/v1/spanner_pb.rb
  google-cloud-spanner/lib/google/spanner/v1/spanner_services_pb.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#4887 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client_config.json
  google-cloud-security_center/synth.metadata
  google-cloud-security_center/test/google/cloud/security_center/v1/security_center_client_test.rb
Labels: cla: yes

#4886 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client_config.json
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4885 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/write.rb
  google-cloud-firestore/lib/google/firestore/v1/firestore_services_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/query_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/write_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#4890 chore: one more simplecov template fix
  google-cloud-tasks/synth/helpers_test.rb.erb
Labels: cla: yes

#4891 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agent_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agent_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client_config.json
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/context_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/validation_result.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intent_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/validation_result_pb.rb
  google-cloud-dialogflow/synth.metadata
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/agents_client_test.rb
Labels: cla: yes
