Repository googleapis/google-cloud-ruby, pull requests merged in 2020-08, with the labels that each got.

#7123 [google-cloud-build-v1] Synchronize new proto/yaml changes.
  google-cloud-build-v1/proto_docs/google/devtools/cloudbuild/v1/cloudbuild.rb
  google-cloud-build-v1/synth.metadata
Labels: cla: yes, context: full

#7094 Release google-cloud-pubsub-v1 0.1.0
  google-cloud-pubsub-v1/CHANGELOG.md
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/version.rb
Labels: autorelease: pending, cla: yes

#7095 Release google-cloud-datastore-v1 0.1.0
  google-cloud-datastore-v1/CHANGELOG.md
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1/version.rb
Labels: autorelease: pending, cla: yes

#7098 Release google-cloud-bigtable-v2 0.1.0
  google-cloud-bigtable-v2/CHANGELOG.md
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/version.rb
Labels: autorelease: pending, cla: yes

#7099 Release google-cloud-bigtable-admin-v2 0.1.0
  google-cloud-bigtable-admin-v2/CHANGELOG.md
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/version.rb
Labels: autorelease: pending, cla: yes

#7096 Release google-cloud-firestore-v1 0.1.0
  google-cloud-firestore-v1/CHANGELOG.md
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/version.rb
Labels: autorelease: pending, cla: yes

#7097 Release google-cloud-firestore-admin-v1 0.1.0
  google-cloud-firestore-admin-v1/CHANGELOG.md
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/version.rb
Labels: autorelease: pending, cla: yes

#7113 [google-cloud-pubsub-v1] Remove experimental warning for ordering keys properties.
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber/client.rb
  google-cloud-pubsub-v1/lib/google/pubsub/v1/pubsub_services_pb.rb
  google-cloud-pubsub-v1/proto_docs/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub-v1/synth.metadata
Labels: cla: yes, context: full

#7090 feat(datastore)!: Use new generated client classes
  google-cloud-datastore/.rubocop.yml
  google-cloud-datastore/AUTHENTICATION.md
  google-cloud-datastore/Gemfile
  google-cloud-datastore/Rakefile
  google-cloud-datastore/google-cloud-datastore.gemspec
  google-cloud-datastore/lib/google-cloud-datastore.rb
  google-cloud-datastore/lib/google/cloud/datastore.rb
  google-cloud-datastore/lib/google/cloud/datastore/commit.rb
  google-cloud-datastore/lib/google/cloud/datastore/convert.rb
  google-cloud-datastore/lib/google/cloud/datastore/credentials.rb
  google-cloud-datastore/lib/google/cloud/datastore/entity.rb
  google-cloud-datastore/lib/google/cloud/datastore/gql_query.rb
  google-cloud-datastore/lib/google/cloud/datastore/key.rb
  google-cloud-datastore/lib/google/cloud/datastore/properties.rb
  google-cloud-datastore/lib/google/cloud/datastore/query.rb
  google-cloud-datastore/lib/google/cloud/datastore/service.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/credentials.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client_config.json
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/datastore.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/entity.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/query.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/protobuf/struct.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/protobuf/timestamp.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/protobuf/wrappers.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/type/latlng.rb
  google-cloud-datastore/lib/google/datastore/v1/datastore_pb.rb
  google-cloud-datastore/lib/google/datastore/v1/datastore_services_pb.rb
  google-cloud-datastore/lib/google/datastore/v1/entity_pb.rb
  google-cloud-datastore/lib/google/datastore/v1/query_pb.rb
  google-cloud-datastore/support/doctest_helper.rb
  google-cloud-datastore/synth.metadata
  google-cloud-datastore/synth.py
  google-cloud-datastore/test/google/cloud/datastore/dataset_test.rb
  google-cloud-datastore/test/google/cloud/datastore/entity_exclude_test.rb
  google-cloud-datastore/test/google/cloud/datastore/entity_test.rb
  google-cloud-datastore/test/google/cloud/datastore/gql_query_test.rb
  google-cloud-datastore/test/google/cloud/datastore/key_test.rb
  google-cloud-datastore/test/google/cloud/datastore/lookup_results/find_all_test.rb
  google-cloud-datastore/test/google/cloud/datastore/properties_test.rb
  google-cloud-datastore/test/google/cloud/datastore/query_results/all_test.rb
  google-cloud-datastore/test/google/cloud/datastore/query_results/all_with_more_test.rb
  google-cloud-datastore/test/google/cloud/datastore/query_results/all_with_offset_test.rb
  google-cloud-datastore/test/google/cloud/datastore/query_results_test.rb
  google-cloud-datastore/test/google/cloud/datastore/read_only_transaction_test.rb
  google-cloud-datastore/test/google/cloud/datastore/transaction_test.rb
  google-cloud-datastore/test/google/cloud/datastore_test.rb
  google-cloud-datastore/test/helper.rb
Labels: api: datastore, cla: yes

#7100 feat(spanner): support custom setting of timeout and retry
  google-cloud-spanner/lib/google/cloud/spanner/batch_snapshot.rb
  google-cloud-spanner/lib/google/cloud/spanner/client.rb
  google-cloud-spanner/lib/google/cloud/spanner/results.rb
  google-cloud-spanner/lib/google/cloud/spanner/service.rb
  google-cloud-spanner/lib/google/cloud/spanner/session.rb
  google-cloud-spanner/lib/google/cloud/spanner/snapshot.rb
  google-cloud-spanner/lib/google/cloud/spanner/transaction.rb
  google-cloud-spanner/support/doctest_helper.rb
  google-cloud-spanner/test/google/cloud/spanner/backup/delete_test.rb
  google-cloud-spanner/test/google/cloud/spanner/backup/expire_time_test.rb
  google-cloud-spanner/test/google/cloud/spanner/backup/referencing_databases_test.rb
  google-cloud-spanner/test/google/cloud/spanner/backup/restore_test.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/execute_partition_test.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/partition_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/partition_read_test.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/read_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/admin_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/commit_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/execute_partition_update_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/read_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/snapshot_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/transaction_test.rb
  google-cloud-spanner/test/google/cloud/spanner/database/backup_test.rb
  google-cloud-spanner/test/google/cloud/spanner/database/create_backup_test.rb
  google-cloud-spanner/test/google/cloud/spanner/database/database_operations_test.rb
  google-cloud-spanner/test/google/cloud/spanner/database/ddl_test.rb
  google-cloud-spanner/test/google/cloud/spanner/database/drop_test.rb
  google-cloud-spanner/test/google/cloud/spanner/database/iam_test.rb
  google-cloud-spanner/test/google/cloud/spanner/database/update_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/backup_operations_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/backup_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/backups_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/config_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/create_database_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/database_operations_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/database_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/databases_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/delete_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/iam_test.rb
  google-cloud-spanner/test/google/cloud/spanner/instance/save_test.rb
  google-cloud-spanner/test/google/cloud/spanner/project/create_database_test.rb
  google-cloud-spanner/test/google/cloud/spanner/project/create_instance_test.rb
  google-cloud-spanner/test/google/cloud/spanner/project/database_test.rb
  google-cloud-spanner/test/google/cloud/spanner/project/databases_test.rb
  google-cloud-spanner/test/google/cloud/spanner/project/instance_config_test.rb
  google-cloud-spanner/test/google/cloud/spanner/project/instance_configs_test.rb
  google-cloud-spanner/test/google/cloud/spanner/project/instance_test.rb
  google-cloud-spanner/test/google/cloud/spanner/project/instances_test.rb
  google-cloud-spanner/test/google/cloud/spanner/snapshot/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/snapshot/read_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/batch_update_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/execute_update_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/read_test.rb
Labels: api: spanner, cla: yes

#7124 test(spanner): unskip tests and update GA workflow for emulator
  .github/workflows/spanner-integration-tests-against-emulator.yaml
  .github/workflows/system-tests-against-emulator.sh
  .github/workflows/system-tests-against-emulator.yaml
  google-cloud-spanner/acceptance/spanner/client/batch_update_test.rb
  google-cloud-spanner/emulator_test.sh
Labels: api: spanner, cla: yes

#7131 fix(bigtable): Include correct project in resource prefix headers
  google-cloud-bigtable/acceptance/bigtable/service_test.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/service.rb
Labels: api: bigtable, cla: yes

#7134 [google-cloud-access_approval-v1] replace html with markdown for accessapproval.proto
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/access_approval/client.rb
  google-cloud-access_approval-v1/proto_docs/google/cloud/accessapproval/v1/accessapproval.rb
  google-cloud-access_approval-v1/synth.metadata
Labels: cla: yes, context: full

#7139 [google-cloud-dataproc-v1] docs: change relative URLs to absolute URLs to fix broken links.
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/autoscaling_policies.rb
  google-cloud-dataproc-v1/synth.metadata
Labels: cla: yes, context: full

#7118 chore(access_approval-v1): Set up new grpc service config
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/access_approval/client.rb
  google-cloud-access_approval-v1/synth.metadata
  google-cloud-access_approval-v1/synth.py
Labels: cla: yes

#7120 chore: Initial microgen of analytics admin v1alpha
  .kokoro/continuous/linux/google-analytics-admin-v1alpha.cfg
  .kokoro/continuous/osx/google-analytics-admin-v1alpha.cfg
  .kokoro/continuous/windows/google-analytics-admin-v1alpha.cfg
  .kokoro/nightly/linux/google-analytics-admin-v1alpha.cfg
  .kokoro/nightly/osx/google-analytics-admin-v1alpha.cfg
  .kokoro/nightly/windows/google-analytics-admin-v1alpha.cfg
  .kokoro/release/google-analytics-admin-v1alpha.cfg
  Gemfile
  google-analytics-admin-v1alpha/.gitignore
  google-analytics-admin-v1alpha/.repo-metadata.json
  google-analytics-admin-v1alpha/.rubocop.yml
  google-analytics-admin-v1alpha/.yardopts
  google-analytics-admin-v1alpha/AUTHENTICATION.md
  google-analytics-admin-v1alpha/CHANGELOG.md
  google-analytics-admin-v1alpha/Gemfile
  google-analytics-admin-v1alpha/LICENSE.md
  google-analytics-admin-v1alpha/README.md
  google-analytics-admin-v1alpha/Rakefile
  google-analytics-admin-v1alpha/google-analytics-admin-v1alpha.gemspec
  google-analytics-admin-v1alpha/lib/google-analytics-admin-v1alpha.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_pb.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service/client.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service/credentials.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service/paths.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_services_pb.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/resources_pb.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/version.rb
  google-analytics-admin-v1alpha/proto_docs/README.md
  google-analytics-admin-v1alpha/proto_docs/google/analytics/admin/v1alpha/analytics_admin.rb
  google-analytics-admin-v1alpha/proto_docs/google/analytics/admin/v1alpha/resources.rb
  google-analytics-admin-v1alpha/proto_docs/google/api/field_behavior.rb
  google-analytics-admin-v1alpha/proto_docs/google/api/resource.rb
  google-analytics-admin-v1alpha/proto_docs/google/protobuf/empty.rb
  google-analytics-admin-v1alpha/proto_docs/google/protobuf/field_mask.rb
  google-analytics-admin-v1alpha/proto_docs/google/protobuf/timestamp.rb
  google-analytics-admin-v1alpha/proto_docs/google/protobuf/wrappers.rb
  google-analytics-admin-v1alpha/synth.metadata
  google-analytics-admin-v1alpha/synth.py
  google-analytics-admin-v1alpha/test/google/analytics/admin/v1alpha/analytics_admin_service_paths_test.rb
  google-analytics-admin-v1alpha/test/google/analytics/admin/v1alpha/analytics_admin_service_test.rb
  google-analytics-admin-v1alpha/test/helper.rb
Labels: cla: yes

#7209 feat: Initial microgen of Datastore Admin V1
  .kokoro/continuous/linux/datastore-admin-v1.cfg
  .kokoro/continuous/osx/datastore-admin-v1.cfg
  .kokoro/continuous/windows/datastore-admin-v1.cfg
  .kokoro/nightly/linux/datastore-admin-v1.cfg
  .kokoro/nightly/osx/datastore-admin-v1.cfg
  .kokoro/nightly/windows/datastore-admin-v1.cfg
  .kokoro/release/datastore-admin-v1.cfg
  Gemfile
  google-cloud-datastore-admin-v1/.gitignore
  google-cloud-datastore-admin-v1/.repo-metadata.json
  google-cloud-datastore-admin-v1/.rubocop.yml
  google-cloud-datastore-admin-v1/.yardopts
  google-cloud-datastore-admin-v1/AUTHENTICATION.md
  google-cloud-datastore-admin-v1/CHANGELOG.md
  google-cloud-datastore-admin-v1/Gemfile
  google-cloud-datastore-admin-v1/LICENSE.md
  google-cloud-datastore-admin-v1/README.md
  google-cloud-datastore-admin-v1/Rakefile
  google-cloud-datastore-admin-v1/google-cloud-datastore-admin-v1.gemspec
  google-cloud-datastore-admin-v1/lib/google-cloud-datastore-admin-v1.rb
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1.rb
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/datastore_admin.rb
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/datastore_admin/client.rb
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/datastore_admin/credentials.rb
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/datastore_admin/operations.rb
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/version.rb
  google-cloud-datastore-admin-v1/lib/google/datastore/admin/v1/datastore_admin_pb.rb
  google-cloud-datastore-admin-v1/lib/google/datastore/admin/v1/datastore_admin_services_pb.rb
  google-cloud-datastore-admin-v1/lib/google/datastore/admin/v1/index_pb.rb
  google-cloud-datastore-admin-v1/proto_docs/README.md
  google-cloud-datastore-admin-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-datastore-admin-v1/proto_docs/google/api/resource.rb
  google-cloud-datastore-admin-v1/proto_docs/google/datastore/admin/v1/datastore_admin.rb
  google-cloud-datastore-admin-v1/proto_docs/google/datastore/admin/v1/index.rb
  google-cloud-datastore-admin-v1/proto_docs/google/longrunning/operations.rb
  google-cloud-datastore-admin-v1/proto_docs/google/protobuf/any.rb
  google-cloud-datastore-admin-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-datastore-admin-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-datastore-admin-v1/proto_docs/google/rpc/status.rb
  google-cloud-datastore-admin-v1/synth.metadata
  google-cloud-datastore-admin-v1/synth.py
  google-cloud-datastore-admin-v1/test/google/cloud/datastore/admin/v1/datastore_admin_operations_test.rb
  google-cloud-datastore-admin-v1/test/google/cloud/datastore/admin/v1/datastore_admin_test.rb
  google-cloud-datastore-admin-v1/test/helper.rb
Labels: api: datastore, cla: yes

#7175 [CHANGE ME] Re-generated google-cloud-pubsub-v1 to pick up changes in the API or client library generator.
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber/client.rb
  google-cloud-pubsub-v1/lib/google/iam/v1/iam_policy_services_pb.rb
  google-cloud-pubsub-v1/synth.metadata
Labels: cla: yes, context: none

#7163 [CHANGE ME] Re-generated google-cloud-firestore-v1 to pick up changes in the API or client library generator.
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore/client.rb
  google-cloud-firestore-v1/synth.metadata
Labels: cla: yes, context: none

#7162 [CHANGE ME] Re-generated google-cloud-firestore-admin-v1 to pick up changes in the API or client library generator.
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin/client.rb
  google-cloud-firestore-admin-v1/synth.metadata
Labels: cla: yes, context: none

#7157 [CHANGE ME] Re-generated google-cloud-datastore-v1 to pick up changes in the API or client library generator.
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1/datastore/client.rb
  google-cloud-datastore-v1/synth.metadata
Labels: cla: yes, context: none

#7207 [CHANGE ME] Re-generated google-cloud-web_risk-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1beta1/lib/google/cloud/web_risk/v1beta1/web_risk_service/client.rb
  google-cloud-web_risk-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7206 [CHANGE ME] Re-generated google-cloud-web_risk-v1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1/lib/google/cloud/web_risk/v1/web_risk_service/client.rb
  google-cloud-web_risk-v1/synth.metadata
Labels: cla: yes, context: none

#7149 [CHANGE ME] Re-generated google-cloud-bigtable-v2 to pick up changes in the API or client library generator.
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/bigtable/client.rb
  google-cloud-bigtable-v2/synth.metadata
Labels: cla: yes, context: none

#7148 [CHANGE ME] Re-generated google-cloud-bigtable-admin-v2 to pick up changes in the API or client library generator.
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin/client.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin/client.rb
  google-cloud-bigtable-admin-v2/synth.metadata
Labels: cla: yes, context: none

#7147 [CHANGE ME] Re-generated google-cloud-bigquery-storage-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/big_query_read/client.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/storage_services_pb.rb
  google-cloud-bigquery-storage-v1/synth.metadata
Labels: cla: yes, context: none

#7205 [CHANGE ME] Re-generated google-cloud-vision-v1p3beta1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/image_annotator/client.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/image_annotator_services_pb.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/product_search/client.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/product_search_service_services_pb.rb
  google-cloud-vision-v1p3beta1/synth.metadata
Labels: cla: yes, context: none

#7204 [CHANGE ME] Re-generated google-cloud-vision-v1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator_services_pb.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search_service_services_pb.rb
  google-cloud-vision-v1/synth.metadata
Labels: cla: yes, context: none

#7203 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p2beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1p2beta1/synth.metadata
Labels: cla: yes, context: none

#7202 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#7201 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1beta2/synth.metadata
Labels: cla: yes, context: none

#7200 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1/synth.metadata
Labels: cla: yes, context: none

#7199 [CHANGE ME] Re-generated google-cloud-translate-v3 to pick up changes in the API or client library generator.
  google-cloud-translate-v3/lib/google/cloud/translate/v3/translation_service/client.rb
  google-cloud-translate-v3/synth.metadata
Labels: cla: yes, context: none

#7198 [CHANGE ME] Re-generated google-cloud-trace-v2 to pick up changes in the API or client library generator.
  google-cloud-trace-v2/lib/google/cloud/trace/v2/trace_service/client.rb
  google-cloud-trace-v2/synth.metadata
Labels: cla: yes, context: none

#7197 [CHANGE ME] Re-generated google-cloud-trace-v1 to pick up changes in the API or client library generator.
  google-cloud-trace-v1/lib/google/cloud/trace/v1/trace_service/client.rb
  google-cloud-trace-v1/synth.metadata
Labels: cla: yes, context: none

#7196 [CHANGE ME] Re-generated google-cloud-text_to_speech-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/text_to_speech/v1beta1/text_to_speech/client.rb
  google-cloud-text_to_speech-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7195 [CHANGE ME] Re-generated google-cloud-text_to_speech-v1 to pick up changes in the API or client library generator.
  google-cloud-text_to_speech-v1/lib/google/cloud/text_to_speech/v1/text_to_speech/client.rb
  google-cloud-text_to_speech-v1/synth.metadata
Labels: cla: yes, context: none

#7194 [CHANGE ME] Re-generated google-cloud-tasks-v2beta3 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta3/lib/google/cloud/tasks/v2beta3/cloud_tasks/client.rb
  google-cloud-tasks-v2beta3/lib/google/cloud/tasks/v2beta3/cloudtasks_services_pb.rb
  google-cloud-tasks-v2beta3/synth.metadata
Labels: cla: yes, context: none

#7193 [CHANGE ME] Re-generated google-cloud-tasks-v2beta2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/cloud_tasks/client.rb
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/cloudtasks_services_pb.rb
  google-cloud-tasks-v2beta2/synth.metadata
Labels: cla: yes, context: none

#7192 [CHANGE ME] Re-generated google-cloud-tasks-v2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/cloud_tasks/client.rb
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/cloudtasks_services_pb.rb
  google-cloud-tasks-v2/synth.metadata
Labels: cla: yes, context: none

#7191 [CHANGE ME] Re-generated google-cloud-talent-v4beta1 to pick up changes in the API or client library generator.
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/application_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/application_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/company_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/company_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/completion/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/completion_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/event_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/job_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/job_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/profile_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/profile_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/tenant_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/tenant_service_services_pb.rb
  google-cloud-talent-v4beta1/synth.metadata
Labels: cla: yes, context: none

#7190 [CHANGE ME] Re-generated google-cloud-speech-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/cloud_speech_services_pb.rb
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/speech/client.rb
  google-cloud-speech-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#7189 [CHANGE ME] Re-generated google-cloud-speech-v1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1/lib/google/cloud/speech/v1/cloud_speech_services_pb.rb
  google-cloud-speech-v1/lib/google/cloud/speech/v1/speech/client.rb
  google-cloud-speech-v1/synth.metadata
Labels: cla: yes, context: none

#7188 [CHANGE ME] Re-generated google-cloud-spanner-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/spanner/client.rb
  google-cloud-spanner-v1/synth.metadata
Labels: cla: yes, context: none

#7187 [CHANGE ME] Re-generated google-cloud-spanner-admin-instance-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/client.rb
  google-cloud-spanner-admin-instance-v1/synth.metadata
Labels: cla: yes, context: none

#7186 [CHANGE ME] Re-generated google-cloud-spanner-admin-database-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/client.rb
  google-cloud-spanner-admin-database-v1/synth.metadata
Labels: cla: yes, context: none

#7185 [CHANGE ME] Re-generated google-cloud-service_directory-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/lookup_service/client.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service/client.rb
  google-cloud-service_directory-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7184 [CHANGE ME] Re-generated google-cloud-security_center-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/security_center/client.rb
  google-cloud-security_center-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#7183 [CHANGE ME] Re-generated google-cloud-security_center-v1 to pick up changes in the API or client library generator.
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/security_center/client.rb
  google-cloud-security_center-v1/synth.metadata
Labels: cla: yes, context: none

#7182 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7181 [CHANGE ME] Re-generated google-cloud-secret_manager-v1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes, context: none

#7180 [CHANGE ME] Re-generated google-cloud-scheduler-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1beta1/lib/google/cloud/scheduler/v1beta1/cloud_scheduler/client.rb
  google-cloud-scheduler-v1beta1/lib/google/cloud/scheduler/v1beta1/cloudscheduler_services_pb.rb
  google-cloud-scheduler-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7179 [CHANGE ME] Re-generated google-cloud-scheduler-v1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1/lib/google/cloud/scheduler/v1/cloud_scheduler/client.rb
  google-cloud-scheduler-v1/lib/google/cloud/scheduler/v1/cloudscheduler_services_pb.rb
  google-cloud-scheduler-v1/synth.metadata
Labels: cla: yes, context: none

#7178 [CHANGE ME] Re-generated google-cloud-redis-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis_services_pb.rb
  google-cloud-redis-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7177 [CHANGE ME] Re-generated google-cloud-redis-v1 to pick up changes in the API or client library generator.
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis_services_pb.rb
  google-cloud-redis-v1/synth.metadata
Labels: cla: yes, context: none

#7176 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender_service_services_pb.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes, context: none

#7174 [CHANGE ME] Re-generated google-cloud-os_login-v1beta to pick up changes in the API or client library generator.
  google-cloud-os_login-v1beta/lib/google/cloud/os_login/v1beta/os_login_service/client.rb
  google-cloud-os_login-v1beta/synth.metadata
Labels: cla: yes, context: none

#7173 [CHANGE ME] Re-generated google-cloud-os_login-v1 to pick up changes in the API or client library generator.
  google-cloud-os_login-v1/lib/google/cloud/os_login/v1/os_login_service/client.rb
  google-cloud-os_login-v1/synth.metadata
Labels: cla: yes, context: none

#7172 [CHANGE ME] Re-generated google-cloud-os_config-v1 to pick up changes in the API or client library generator.
  google-cloud-os_config-v1/lib/google/cloud/os_config/v1/os_config_service/client.rb
  google-cloud-os_config-v1/synth.metadata
Labels: cla: yes, context: none

#7171 [CHANGE ME] Re-generated google-cloud-monitoring-v3 to pick up changes in the API or client library generator.
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/alert_policy_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/group_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/metric_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/notification_channel_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/service_monitoring_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/uptime_check_service/client.rb
  google-cloud-monitoring-v3/synth.metadata
Labels: cla: yes, context: none

#7170 [CHANGE ME] Re-generated google-cloud-monitoring-dashboard-v1 to pick up changes in the API or client library generator.
  google-cloud-monitoring-dashboard-v1/lib/google/cloud/monitoring/dashboard/v1/dashboards_service/client.rb
  google-cloud-monitoring-dashboard-v1/synth.metadata
Labels: cla: yes, context: none

#7169 [CHANGE ME] Re-generated google-cloud-memcache-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/cloud_memcache_services_pb.rb
  google-cloud-memcache-v1beta2/synth.metadata
Labels: cla: yes, context: none

#7168 [CHANGE ME] Re-generated google-cloud-logging-v2 to pick up changes in the API or client library generator.
  google-cloud-logging-v2/lib/google/cloud/logging/v2/config_service/client.rb
  google-cloud-logging-v2/lib/google/cloud/logging/v2/logging_service/client.rb
  google-cloud-logging-v2/lib/google/cloud/logging/v2/metrics_service/client.rb
  google-cloud-logging-v2/synth.metadata
Labels: cla: yes, context: none

#7167 [CHANGE ME] Re-generated google-cloud-language-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/language_service_services_pb.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes, context: none

#7166 [CHANGE ME] Re-generated google-cloud-language-v1 to pick up changes in the API or client library generator.
  google-cloud-language-v1/lib/google/cloud/language/v1/language_service/client.rb
  google-cloud-language-v1/lib/google/cloud/language/v1/language_service_services_pb.rb
  google-cloud-language-v1/synth.metadata
Labels: cla: yes, context: none

#7165 [CHANGE ME] Re-generated google-cloud-kms-v1 to pick up changes in the API or client library generator.
  google-cloud-kms-v1/lib/google/cloud/kms/v1/key_management_service/client.rb
  google-cloud-kms-v1/lib/google/cloud/kms/v1/service_services_pb.rb
  google-cloud-kms-v1/lib/google/iam/v1/iam_policy_services_pb.rb
  google-cloud-kms-v1/synth.metadata
Labels: cla: yes, context: none

#7164 [CHANGE ME] Re-generated google-cloud-iot-v1 to pick up changes in the API or client library generator.
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager/client.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager_services_pb.rb
  google-cloud-iot-v1/synth.metadata
Labels: cla: yes, context: none

#7161 [CHANGE ME] Re-generated google-cloud-error_reporting-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/error_group_service/client.rb
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/error_stats_service/client.rb
  google-cloud-error_reporting-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7160 [CHANGE ME] Re-generated google-cloud-dlp-v2 to pick up changes in the API or client library generator.
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/dlp_service/client.rb
  google-cloud-dlp-v2/synth.metadata
Labels: cla: yes, context: none

#7159 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agent_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/context_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/contexts/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_type_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environment_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environments/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intent_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_type_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/sessions/client.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes, context: none

#7158 [CHANGE ME] Re-generated google-cloud-debugger-v2 to pick up changes in the API or client library generator.
  google-cloud-debugger-v2/lib/google/cloud/debugger/v2/controller/client.rb
  google-cloud-debugger-v2/lib/google/cloud/debugger/v2/debugger/client.rb
  google-cloud-debugger-v2/synth.metadata
Labels: cla: yes, context: none

#7156 [CHANGE ME] Re-generated google-cloud-dataproc-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/autoscaling_policies_services_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/cluster_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/clusters_services_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/jobs_services_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_template_service/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_templates_services_pb.rb
  google-cloud-dataproc-v1beta2/synth.metadata
Labels: cla: yes, context: none

#7155 [CHANGE ME] Re-generated google-cloud-dataproc-v1 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/autoscaling_policies_services_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/autoscaling_policy_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/clusters_services_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/jobs_services_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_template_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_templates_services_pb.rb
  google-cloud-dataproc-v1/synth.metadata
Labels: cla: yes, context: none

#7154 [CHANGE ME] Re-generated google-cloud-data_catalog-v1 to pick up changes in the API or client library generator.
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/data_catalog/client.rb
  google-cloud-data_catalog-v1/synth.metadata
Labels: cla: yes, context: none

#7153 [CHANGE ME] Re-generated google-cloud-container-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-container-v1beta1/lib/google/cloud/container/v1beta1/cluster_manager/client.rb
  google-cloud-container-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7152 [CHANGE ME] Re-generated google-cloud-container-v1 to pick up changes in the API or client library generator.
  google-cloud-container-v1/lib/google/cloud/container/v1/cluster_manager/client.rb
  google-cloud-container-v1/synth.metadata
Labels: cla: yes, context: none

#7151 [CHANGE ME] Re-generated google-cloud-build-v1 to pick up changes in the API or client library generator.
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/client.rb
  google-cloud-build-v1/synth.metadata
Labels: cla: yes, context: none

#7150 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing_services_pb.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog_services_pb.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes, context: none

#7146 [CHANGE ME] Re-generated google-cloud-bigquery-reservation-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-reservation-v1/lib/google/cloud/bigquery/reservation/v1/reservation_service/client.rb
  google-cloud-bigquery-reservation-v1/lib/google/cloud/bigquery/reservation/v1/reservation_services_pb.rb
  google-cloud-bigquery-reservation-v1/synth.metadata
Labels: cla: yes, context: none

#7145 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer-v1/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service/client.rb
  google-cloud-bigquery-data_transfer-v1/synth.metadata
Labels: cla: yes, context: none

#7144 [CHANGE ME] Re-generated google-cloud-bigquery-connection-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-connection-v1/lib/google/cloud/bigquery/connection/v1/connection_service/client.rb
  google-cloud-bigquery-connection-v1/lib/google/cloud/bigquery/connection/v1/connection_services_pb.rb
  google-cloud-bigquery-connection-v1/synth.metadata
Labels: cla: yes, context: none

#7143 [CHANGE ME] Re-generated google-cloud-automl-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/automl/client.rb
  google-cloud-automl-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7142 [CHANGE ME] Re-generated google-cloud-automl-v1 to pick up changes in the API or client library generator.
  google-cloud-automl-v1/lib/google/cloud/automl/v1/automl/client.rb
  google-cloud-automl-v1/synth.metadata
Labels: cla: yes, context: none

#7141 [CHANGE ME] Re-generated google-cloud-asset-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1beta1/lib/google/cloud/asset/v1beta1/asset_service/client.rb
  google-cloud-asset-v1beta1/lib/google/cloud/asset/v1beta1/asset_service_services_pb.rb
  google-cloud-asset-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7140 [CHANGE ME] Re-generated google-cloud-asset-v1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_services_pb.rb
  google-cloud-asset-v1/synth.metadata
Labels: cla: yes, context: none

#7138 fix(pubsub): Change client config metadata hash keys to symbols
  google-cloud-pubsub/acceptance/pubsub/service_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
Labels: api: pubsub, cla: yes

#7136 fix(datastore): Change client config metadata hash keys to symbols
  google-cloud-datastore/acceptance/datastore/datastore_test.rb
  google-cloud-datastore/acceptance/datastore/service_test.rb
  google-cloud-datastore/lib/google/cloud/datastore/service.rb
Labels: api: datastore, cla: yes

#7137 fix(firestore): Change client config metadata hash keys to symbols
  google-cloud-firestore/acceptance/firestore/service_test.rb
  google-cloud-firestore/lib/google/cloud/firestore/service.rb
Labels: api: firestore, cla: yes

#7135 test(pubsub): Increase deadline for acceptance test for ordered keys
  google-cloud-pubsub/acceptance/pubsub/async_test.rb
Labels: api: pubsub, cla: yes

#7213 fix(grafeas-v1): Fix retry logic by checking the correct numeric error codes
  grafeas-v1/lib/grafeas/v1/grafeas/client.rb
  grafeas-v1/lib/grafeas/v1/grafeas_services_pb.rb
  grafeas-v1/synth.metadata
  grafeas-v1/synth.py
Labels: cla: yes

#7214 chore: Remove os_login synth hacks that are no longer needed
  google-cloud-os_login-v1/synth.py
  google-cloud-os_login-v1beta/synth.py
Labels: cla: yes

#7247 Release google-cloud-dialogflow-v2 0.6.5
  google-cloud-dialogflow-v2/CHANGELOG.md
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/version.rb
Labels: cla: yes

#7246 Release google-cloud-language-v1beta2 0.2.4
  google-cloud-language-v1beta2/CHANGELOG.md
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#7245 Release google-cloud-spanner-admin-instance-v1 0.1.2
  google-cloud-spanner-admin-instance-v1/CHANGELOG.md
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/version.rb
Labels: autorelease: pending, cla: yes

#7244 Release google-cloud-os_config-v1 0.1.3
  google-cloud-os_config-v1/CHANGELOG.md
  google-cloud-os_config-v1/lib/google/cloud/os_config/v1/version.rb
Labels: autorelease: pending, cla: yes

#7243 Release google-cloud-logging-v2 0.1.2
  google-cloud-logging-v2/CHANGELOG.md
  google-cloud-logging-v2/lib/google/cloud/logging/v2/version.rb
Labels: autorelease: pending, cla: yes

#7242 Release google-cloud-redis-v1 0.3.1
  google-cloud-redis-v1/CHANGELOG.md
  google-cloud-redis-v1/lib/google/cloud/redis/v1/version.rb
Labels: autorelease: pending, cla: yes

#7241 Release google-cloud-recommender-v1 0.5.1
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
Labels: autorelease: pending, cla: yes

#7240 Release google-cloud-scheduler-v1beta1 0.2.4
  google-cloud-scheduler-v1beta1/CHANGELOG.md
  google-cloud-scheduler-v1beta1/lib/google/cloud/scheduler/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7239 Release google-cloud-monitoring-dashboard-v1 0.2.2
  google-cloud-monitoring-dashboard-v1/CHANGELOG.md
  google-cloud-monitoring-dashboard-v1/lib/google/cloud/monitoring/dashboard/v1/version.rb
Labels: autorelease: pending, cla: yes

#7238 Release google-cloud-redis-v1beta1 0.2.4
  google-cloud-redis-v1beta1/CHANGELOG.md
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7234 Release google-cloud-firestore-v1 0.1.1
  google-cloud-firestore-v1/CHANGELOG.md
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/version.rb
Labels: autorelease: pending, cla: yes

#7233 Release google-cloud-bigtable-admin-v2 0.1.1
  google-cloud-bigtable-admin-v2/CHANGELOG.md
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/version.rb
Labels: autorelease: pending, cla: yes

#7227 Release google-cloud-bigtable-v2 0.1.1
  google-cloud-bigtable-v2/CHANGELOG.md
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/version.rb
Labels: autorelease: pending, cla: yes

#7226 Release google-cloud-datastore-v1 0.1.1
  google-cloud-datastore-v1/CHANGELOG.md
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1/version.rb
Labels: autorelease: pending, cla: yes

#7237 Release google-cloud-firestore-admin-v1 0.1.1
  google-cloud-firestore-admin-v1/CHANGELOG.md
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/version.rb
Labels: autorelease: pending, cla: yes

#7236 Release google-cloud-memcache-v1beta2 0.1.2
  google-cloud-memcache-v1beta2/CHANGELOG.md
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#7235 Release google-cloud-language-v1 0.2.4
  google-cloud-language-v1/CHANGELOG.md
  google-cloud-language-v1/lib/google/cloud/language/v1/version.rb
Labels: autorelease: pending, cla: yes

#7232 Release google-cloud-error_reporting-v1beta1 0.1.1
  google-cloud-error_reporting-v1beta1/CHANGELOG.md
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7231 Release google-cloud-container-v1beta1 0.2.4
  google-cloud-container-v1beta1/CHANGELOG.md
  google-cloud-container-v1beta1/lib/google/cloud/container/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7230 Release google-cloud-data_catalog-v1 0.4.4
  google-cloud-data_catalog-v1/CHANGELOG.md
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/version.rb
Labels: autorelease: pending, cla: yes

#7229 Release google-cloud-automl-v1beta1 0.2.5
  google-cloud-automl-v1beta1/CHANGELOG.md
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7228 Release google-cloud-debugger-v2 0.1.1
  google-cloud-debugger-v2/CHANGELOG.md
  google-cloud-debugger-v2/lib/google/cloud/debugger/v2/version.rb
Labels: autorelease: pending, cla: yes

#7225 Release google-cloud-container-v1 0.2.4
  google-cloud-container-v1/CHANGELOG.md
  google-cloud-container-v1/lib/google/cloud/container/v1/version.rb
Labels: autorelease: pending, cla: yes

#7224 Release google-cloud-bigquery-reservation-v1 0.1.1
  google-cloud-bigquery-reservation-v1/CHANGELOG.md
  google-cloud-bigquery-reservation-v1/lib/google/cloud/bigquery/reservation/v1/version.rb
Labels: autorelease: pending, cla: yes

#7126 Release google-cloud-pubsub-v1 0.1.1
  google-cloud-pubsub-v1/CHANGELOG.md
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/version.rb
Labels: autorelease: pending, cla: yes

#7121 Release google-cloud-dataproc-v1 0.3.0
  google-cloud-dataproc-v1/CHANGELOG.md
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/version.rb
Labels: autorelease: pending, cla: yes

#7125 Release google-cloud-build-v1 0.1.2
  google-cloud-build-v1/CHANGELOG.md
  google-cloud-build-v1/lib/google/cloud/build/v1/version.rb
Labels: autorelease: pending, cla: yes

#7223 Release google-cloud-bigquery-storage-v1 0.2.4
  google-cloud-bigquery-storage-v1/CHANGELOG.md
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/version.rb
Labels: autorelease: pending, cla: yes

#7128 Release google-cloud-pubsub 2.0.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#7133 Release google-cloud-bigtable 2.0.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#7132 Release google-cloud-datastore 2.0.0
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes

#7129 Release google-cloud-firestore 2.0.0
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#7222 Release google-cloud-billing-v1 0.5.4
  google-cloud-billing-v1/CHANGELOG.md
  google-cloud-billing-v1/lib/google/cloud/billing/v1/version.rb
Labels: autorelease: pending, cla: yes

#7221 Release google-cloud-bigquery-data_transfer-v1 0.2.4
  google-cloud-bigquery-data_transfer-v1/CHANGELOG.md
  google-cloud-bigquery-data_transfer-v1/lib/google/cloud/bigquery/data_transfer/v1/version.rb
Labels: autorelease: pending, cla: yes

#7220 Release google-cloud-automl-v1 0.2.5
  google-cloud-automl-v1/CHANGELOG.md
  google-cloud-automl-v1/lib/google/cloud/automl/v1/version.rb
Labels: autorelease: pending, cla: yes

#7219 Release google-cloud-asset-v1beta1 0.2.4
  google-cloud-asset-v1beta1/CHANGELOG.md
  google-cloud-asset-v1beta1/lib/google/cloud/asset/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7218 Release google-cloud-bigquery-connection-v1 0.1.1
  google-cloud-bigquery-connection-v1/CHANGELOG.md
  google-cloud-bigquery-connection-v1/lib/google/cloud/bigquery/connection/v1/version.rb
Labels: autorelease: pending, cla: yes

#7217 Release google-cloud-os_login-v1 0.2.4
  google-cloud-os_login-v1/CHANGELOG.md
  google-cloud-os_login-v1/lib/google/cloud/os_login/v1/version.rb
Labels: autorelease: pending, cla: yes

#7216 Release google-cloud-os_login-v1beta 0.2.4
  google-cloud-os_login-v1beta/CHANGELOG.md
  google-cloud-os_login-v1beta/lib/google/cloud/os_login/v1beta/version.rb
Labels: autorelease: pending, cla: yes

#7215 Release grafeas-v1 0.1.1
  grafeas-v1/CHANGELOG.md
  grafeas-v1/lib/grafeas/v1/version.rb
Labels: autorelease: pending, cla: yes

#7212 Release google-cloud-asset-v1 0.5.2
  google-cloud-asset-v1/CHANGELOG.md
  google-cloud-asset-v1/lib/google/cloud/asset/v1/version.rb
Labels: autorelease: pending, cla: yes

#7211 Release google-cloud-iot-v1 0.1.2
  google-cloud-iot-v1/CHANGELOG.md
  google-cloud-iot-v1/lib/google/cloud/iot/v1/version.rb
Labels: autorelease: pending, cla: yes

#7210 Release google-cloud-access_approval-v1 0.2.4
  google-cloud-access_approval-v1/CHANGELOG.md
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/version.rb
Labels: autorelease: pending, cla: yes

#7130 Release google-cloud-spanner 2.1.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#7249 Release google-cloud-datastore-admin-v1 0.1.0
  google-cloud-datastore-admin-v1/CHANGELOG.md
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/version.rb
Labels: api: datastore, autorelease: pending, cla: yes

#7250 Release google-analytics-admin-v1alpha 0.1.0
  google-analytics-admin-v1alpha/CHANGELOG.md
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/version.rb
Labels: autorelease: pending, cla: yes

#7251 Release google-cloud-gaming-v1 0.1.0
  google-cloud-gaming-v1/CHANGELOG.md
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/version.rb
Labels: autorelease: pending, cla: yes

#7103 Release google-cloud-text_to_speech-v1beta1 0.3.0
  google-cloud-text_to_speech-v1beta1/CHANGELOG.md
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/text_to_speech/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7117 Release google-cloud-translate-v3 0.1.3
  google-cloud-translate-v3/CHANGELOG.md
  google-cloud-translate-v3/lib/google/cloud/translate/v3/version.rb
Labels: autorelease: pending, cla: yes

#7253 Release google-cloud-trace-v1 0.1.1
  google-cloud-trace-v1/CHANGELOG.md
  google-cloud-trace-v1/lib/google/cloud/trace/v1/version.rb
Labels: autorelease: pending, cla: yes

#7254 Release google-cloud-kms-v1 0.2.3
  google-cloud-kms-v1/CHANGELOG.md
  google-cloud-kms-v1/lib/google/cloud/kms/v1/version.rb
Labels: autorelease: pending, cla: yes

#7281 Release google-cloud-monitoring-v3 0.1.3
  google-cloud-monitoring-v3/CHANGELOG.md
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/version.rb
Labels: autorelease: pending, cla: yes

#7280 Release google-cloud-vision-v1p3beta1 0.2.4
  google-cloud-vision-v1p3beta1/CHANGELOG.md
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/version.rb
Labels: autorelease: pending, cla: yes

#7279 Release google-cloud-vision-v1 0.2.4
  google-cloud-vision-v1/CHANGELOG.md
  google-cloud-vision-v1/lib/google/cloud/vision/v1/version.rb
Labels: autorelease: pending, cla: yes

#7278 Release google-cloud-spanner-v1 0.2.1
  google-cloud-spanner-v1/CHANGELOG.md
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/version.rb
Labels: autorelease: pending, cla: yes

#7277 Release google-cloud-scheduler-v1 0.2.4
  google-cloud-scheduler-v1/CHANGELOG.md
  google-cloud-scheduler-v1/lib/google/cloud/scheduler/v1/version.rb
Labels: autorelease: pending, cla: yes

#7276 Release google-cloud-video_intelligence-v1p1beta1 0.2.4
  google-cloud-video_intelligence-v1p1beta1/CHANGELOG.md
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7275 Release google-cloud-tasks-v2 0.2.4
  google-cloud-tasks-v2/CHANGELOG.md
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/version.rb
Labels: autorelease: pending, cla: yes

#7274 Release google-cloud-tasks-v2beta2 0.2.4
  google-cloud-tasks-v2beta2/CHANGELOG.md
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/version.rb
Labels: autorelease: pending, cla: yes
