Repository googleapis/google-cloud-ruby, pull requests merged in 2020-09, with the labels that each got.

#7451 feat(bigquery): Add support for ML model export
  google-cloud-bigquery/acceptance/bigquery/bigquery_test.rb
  google-cloud-bigquery/acceptance/bigquery/model_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/convert.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/copy_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/extract_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/load_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/model.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/project.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigquery/test/google/cloud/bigquery/extract_job_model_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/extract_job_table_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/reference/extract_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/model/resource/extract_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_extract_job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_extract_test.rb
  google-cloud-bigquery/test/helper.rb
Labels: api: bigquery, cla: yes

#7592 fix(spanner): retry or resume eos and rst_stream errors
  google-cloud-spanner/.gitignore
  google-cloud-spanner/lib/google/cloud/spanner/results.rb
  google-cloud-spanner/test/google/cloud/spanner/client/execute_query_resume_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/read_resume_buffer_bound_test.rb
  google-cloud-spanner/test/helper.rb
Labels: api: spanner, cla: yes

#7611 chore: Disable updating release PRs because creds are broken
  .kokoro/build.sh
Labels: cla: yes

#7608 [google-cloud-asset-v1] feat: add AnalyzeIamPolicy and ExportIamPolicyAnalysis RPCs
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_services_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/assets_pb.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/asset_service.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/assets.rb
  google-cloud-asset-v1/synth.metadata
  google-cloud-asset-v1/test/google/cloud/asset/v1/asset_service_test.rb
Labels: cla: yes, context: full

#7607 Release google-cloud-asset-v1 0.6.0
  google-cloud-asset-v1/CHANGELOG.md
  google-cloud-asset-v1/lib/google/cloud/asset/v1/version.rb
Labels: autorelease: pending, cla: yes

#7617 chore: Undo failed release PRs
  google-cloud-firestore-v1/CHANGELOG.md
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/version.rb
  google-cloud-kms-v1/CHANGELOG.md
  google-cloud-kms-v1/lib/google/cloud/kms/v1/version.rb
  google-cloud-security_center-v1/CHANGELOG.md
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/version.rb
  google-cloud-security_center-v1p1beta1/CHANGELOG.md
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/version.rb
Labels: cla: yes

#7615 feat: add custom time to file metadata sample
  google-cloud-storage/samples/acceptance/files_test.rb
  google-cloud-storage/samples/files.rb
Labels: api: storage, cla: yes, type: docs

#7618 Release google-cloud-firestore-v1 0.2.0
  google-cloud-firestore-v1/CHANGELOG.md
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/version.rb
Labels: autorelease: pending, cla: yes

#7619 Release google-cloud-kms-v1 0.3.0
  google-cloud-kms-v1/CHANGELOG.md
  google-cloud-kms-v1/lib/google/cloud/kms/v1/version.rb
Labels: autorelease: pending, cla: yes

#7620 Release google-cloud-security_center-v1 0.3.5
  google-cloud-security_center-v1/CHANGELOG.md
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/version.rb
Labels: autorelease: pending, cla: yes

#7621 Release google-cloud-security_center-v1p1beta1 0.4.0
  google-cloud-security_center-v1p1beta1/CHANGELOG.md
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7105 Release google-cloud-security_center 1.1.2
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes

#6491 feat(spanner): add numeric support
  google-cloud-spanner/acceptance/spanner/client/types/numeric_test.rb
  google-cloud-spanner/acceptance/spanner_helper.rb
  google-cloud-spanner/lib/google/cloud/spanner/convert.rb
  google-cloud-spanner/test/google/cloud/spanner/convert/grpc_value_to_object_test.rb
  google-cloud-spanner/test/google/cloud/spanner/convert/to_query_params_test.rb
Labels: api: spanner, cla: yes, do not merge

#7614 [google-cloud-dlp-v2] docs: expand parent field format, and BigQuery sampling options. Also describing which transformations are allowed for ReidentifyContent API calls, and the custom alphabet allowed for format-preserving encryption (FPE).
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/dlp_service/client.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp-v2/synth.metadata
Labels: cla: yes, context: full

#7625 [google-cloud-secret_manager-v1beta1] docs: remove redundant proto comment in v1beta1
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secrets/v1beta1/service_services_pb.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes, context: full

#7624 [google-cloud-secret_manager-v1] Remove redundant secretmanager v1 proto comment
  google-cloud-secret_manager-v1/lib/google/cloud/secretmanager/v1/service_services_pb.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes, context: full

#7582 optimization in git clone using --depth
  .kokoro/docker/autosynth/Dockerfile
  .kokoro/docker/multi/Dockerfile
  .kokoro/docker/release/Dockerfile
  .kokoro/templates/autosynth.Dockerfile.erb
  .kokoro/templates/multi.Dockerfile.erb
  .kokoro/templates/release.Dockerfile.erb
Labels: cla: yes

#7584 optimization debian package manager tweaks
  .kokoro/docker/autosynth/Dockerfile
  .kokoro/docker/multi-node/Dockerfile
  .kokoro/docker/multi/Dockerfile
  .kokoro/docker/release/Dockerfile
  .kokoro/templates/autosynth.Dockerfile.erb
  .kokoro/templates/multi.Dockerfile.erb
  .kokoro/templates/release.Dockerfile.erb
  Vagrantfile
  integration/rails4_app/Dockerfile.example
  integration/rails5_app/Dockerfile.example
  integration/sinatra2_app/Dockerfile.example
Labels: cla: yes

#7609 Release google-cloud-bigquery 1.22.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes

#7635 [google-cloud-asset-v1] fix!: remove AnalyzeIamPolicy and ExportIamPolicyAnalysis RPCs
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_services_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/assets_pb.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/asset_service.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/assets.rb
  google-cloud-asset-v1/synth.metadata
  google-cloud-asset-v1/test/google/cloud/asset/v1/asset_service_test.rb
Labels: cla: yes, context: full

#7606 Release google-cloud-firestore 2.1.0
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#7636 [google-cloud-secret_manager-v1] Update secretmanager.googleapis.com v1 protos
  google-cloud-secret_manager-v1/lib/google/cloud/secretmanager/v1/resources_pb.rb
  google-cloud-secret_manager-v1/proto_docs/google/cloud/secretmanager/v1/resources.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes, context: full

#7632 Release google-cloud-dlp-v2 0.4.3
  google-cloud-dlp-v2/CHANGELOG.md
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/version.rb
Labels: autorelease: pending, cla: yes

#7638 Release google-cloud-asset-v1 0.6.1
  google-cloud-asset-v1/CHANGELOG.md
  google-cloud-asset-v1/lib/google/cloud/asset/v1/version.rb
Labels: autorelease: pending, cla: yes

#7639 Release google-cloud-secret_manager-v1 0.5.0
  google-cloud-secret_manager-v1/CHANGELOG.md
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/version.rb
Labels: autorelease: pending, cla: yes

#7640 Release google-cloud-policy_troubleshooter-v1 0.1.0
  google-cloud-policy_troubleshooter-v1/CHANGELOG.md
  google-cloud-policy_troubleshooter-v1/lib/google/cloud/policy_troubleshooter/v1/version.rb
Labels: autorelease: pending, cla: yes

#7641 Release google-cloud-functions-v1 0.1.0
  google-cloud-functions-v1/CHANGELOG.md
  google-cloud-functions-v1/lib/google/cloud/functions/v1/version.rb
Labels: autorelease: pending, cla: yes

#7642 Release google-cloud-billing-budgets-v1beta1 0.1.0
  google-cloud-billing-budgets-v1beta1/CHANGELOG.md
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7643 Release google-cloud-notebooks-v1beta1 0.1.0
  google-cloud-notebooks-v1beta1/CHANGELOG.md
  google-cloud-notebooks-v1beta1/lib/google/cloud/notebooks/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7600 PubSub: Pass push config in create subscription method
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription/push_config.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/push_config_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic_test.rb
  google-cloud-pubsub/test/helper.rb
Labels: api: pubsub, cla: yes, type: feature request

#7613 chore(datastore-admin-v1): Add samples
  google-cloud-datastore-admin-v1/Rakefile
  google-cloud-datastore-admin-v1/samples/.rubocop.yml
  google-cloud-datastore-admin-v1/samples/Gemfile
  google-cloud-datastore-admin-v1/samples/README.md
  google-cloud-datastore-admin-v1/samples/Rakefile
  google-cloud-datastore-admin-v1/samples/acceptance/helper.rb
  google-cloud-datastore-admin-v1/samples/acceptance/snippets_test.rb
  google-cloud-datastore-admin-v1/samples/index.yaml
  google-cloud-datastore-admin-v1/samples/snippets.rb
  google-cloud-datastore/Rakefile
  google-cloud-datastore/samples/acceptance/sample_test.rb
Labels: api: datastore, cla: yes, type: docs

#7604 Pubsub docs improvement
  google-cloud-pubsub/OVERVIEW.md
  google-cloud-pubsub/README.md
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/message.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/project.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/received_message.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/async_publisher/message_ordering_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/async_publisher_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/ordered_messages_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/publish_async_test.rb
Labels: api: pubsub, cla: yes, type: docs

#7654 [google-cloud-dialogflow-v2] docs: wording updates for tiers.
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/webhook.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes, context: full

#7645 [CHANGE ME] Re-generated google-cloud-build-v1 to pick up changes in the API or client library generator.
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build.rb
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/client.rb
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/paths.rb
  google-cloud-build-v1/lib/google/devtools/cloudbuild/v1/cloudbuild_pb.rb
  google-cloud-build-v1/proto_docs/google/devtools/cloudbuild/v1/cloudbuild.rb
  google-cloud-build-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-build-v1/synth.metadata
  google-cloud-build-v1/test/google/cloud/build/v1/cloud_build_paths_test.rb
  google-cloud-build-v1/test/google/cloud/build/v1/cloud_build_test.rb
Labels: cla: yes, context: full

#7658 chore: update CODEOWNERS file
  .github/CODEOWNERS
Labels: cla: yes

#7659 chore: Use testing-infra-docker images and remove the ones in this repo
  .kokoro/docker/autosynth/Dockerfile
  .kokoro/docker/multi-node/Dockerfile
  .kokoro/docker/multi/Dockerfile
  .kokoro/docker/release/Dockerfile
  .kokoro/docker/windows/Dockerfile
  .kokoro/templates/autosynth.Dockerfile.erb
  .kokoro/templates/multi.Dockerfile.erb
  .kokoro/templates/release.Dockerfile.erb
  KOKORO.md
  Rakefile
  rakelib/kokoro/kokoro.rb
  rakelib/kokoro/kokoro_builder.rb
Labels: cla: yes

#7656 feat(storage): quota_project can be set via library configuration
  google-cloud-storage/lib/google-cloud-storage.rb
  google-cloud-storage/lib/google/cloud/storage.rb
  google-cloud-storage/lib/google/cloud/storage/service.rb
  google-cloud-storage/test/google/cloud/storage_test.rb
Labels: api: storage, cla: yes

#7633 feat(translate-v2): quota_project can be set via library configuration
  google-cloud-translate-v2/lib/google/cloud/translate/v2/service.rb
Labels: cla: yes

#7601 chore(firestore): Add snapshot query cursor sample
  google-cloud-firestore/samples/acceptance/paginate_data_test.rb
  google-cloud-firestore/samples/paginate_data.rb
Labels: api: firestore, cla: yes, type: docs

#7629 feat(resource_manager): quota_project can be set via library configuration
  google-cloud-resource_manager/lib/google-cloud-resource_manager.rb
  google-cloud-resource_manager/lib/google/cloud/resource_manager.rb
  google-cloud-resource_manager/lib/google/cloud/resource_manager/service.rb
  google-cloud-resource_manager/test/google/cloud/resource_manager_test.rb
Labels: cla: yes

#7628 feat(dns): quota_project can be set via library configuration
  google-cloud-dns/lib/google-cloud-dns.rb
  google-cloud-dns/lib/google/cloud/dns.rb
  google-cloud-dns/lib/google/cloud/dns/service.rb
  google-cloud-dns/test/google/cloud/dns_test.rb
Labels: api: dns, cla: yes

#7627 feat(bigquery): quota_project can be set via library configuration
  google-cloud-bigquery/lib/google-cloud-bigquery.rb
  google-cloud-bigquery/lib/google/cloud/bigquery.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/test/google/cloud/bigquery_test.rb
Labels: api: bigquery, cla: yes

#7630 feat: quota_project can be set via library configuration
  google-cloud-bigtable/lib/google-cloud-bigtable.rb
  google-cloud-datastore/lib/google-cloud-datastore.rb
  google-cloud-debugger/lib/google-cloud-debugger.rb
  google-cloud-error_reporting/lib/google-cloud-error_reporting.rb
  google-cloud-firestore/lib/google-cloud-firestore.rb
  google-cloud-logging/lib/google-cloud-logging.rb
  google-cloud-pubsub/lib/google-cloud-pubsub.rb
  google-cloud-spanner/lib/google-cloud-spanner.rb
Labels: cla: yes

#7663 chore: update CODEOWNERS for bigtable
  .github/CODEOWNERS
Labels: cla: yes

#7661 [google-cloud-billing-budgets-v1beta1] feat: Added support for field to disable default budget alerts to IAM recipients. fix: Pub/Sub fields in AllUpdatesRule are now optional. fix: Added cloud-billing OAuth scope.
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/budget_model_pb.rb
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/budget_service/credentials.rb
  google-cloud-billing-budgets-v1beta1/proto_docs/google/cloud/billing/budgets/v1beta1/budget_model.rb
  google-cloud-billing-budgets-v1beta1/synth.metadata
Labels: cla: yes, context: full

#7631 Release google-cloud-spanner 2.2.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#7662 chore(pubsub): Minor follow-up changes to addition of push_config param in Topic#subscribe
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription/push_config.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/support/doctest_helper.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/push_config_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic_test.rb
Labels: api: pubsub, cla: yes, type: cleanup

#7680 [google-cloud-asset-v1] feat: added support for per type and partition export for Cloud Asset API
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_pb.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/asset_service.rb
  google-cloud-asset-v1/synth.metadata
Labels: cla: yes, context: full

#7678 Release google-cloud-dns 0.33.0
  google-cloud-dns/CHANGELOG.md
  google-cloud-dns/lib/google/cloud/dns/version.rb
Labels: autorelease: pending, cla: yes

#7677 Release google-cloud-translate-v2 0.2.0
  google-cloud-translate-v2/CHANGELOG.md
  google-cloud-translate-v2/lib/google/cloud/translate/v2/version.rb
Labels: autorelease: pending, cla: yes

#7676 Release google-cloud-resource_manager 0.34.0
  google-cloud-resource_manager/CHANGELOG.md
  google-cloud-resource_manager/lib/google/cloud/resource_manager/version.rb
Labels: autorelease: pending, cla: yes

#7671 Release google-cloud-billing-budgets-v1beta1 0.2.0
  google-cloud-billing-budgets-v1beta1/CHANGELOG.md
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7669 Release google-cloud-error_reporting 0.41.0
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes

#7668 Release google-cloud-logging 2.1.0
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#7665 Release google-cloud-debugger 0.41.0
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#7657 Release google-cloud-build-v1 0.2.0
  google-cloud-build-v1/CHANGELOG.md
  google-cloud-build-v1/lib/google/cloud/build/v1/version.rb
Labels: autorelease: pending, cla: yes

#7673 chore: Generate initial google-cloud-assured_workloads-v1beta1 gapic
  .kokoro/continuous/linux/assured_workloads-v1beta1.cfg
  .kokoro/continuous/osx/assured_workloads-v1beta1.cfg
  .kokoro/continuous/windows/assured_workloads-v1beta1.cfg
  .kokoro/nightly/linux/assured_workloads-v1beta1.cfg
  .kokoro/nightly/osx/assured_workloads-v1beta1.cfg
  .kokoro/nightly/windows/assured_workloads-v1beta1.cfg
  .kokoro/release/assured_workloads-v1beta1.cfg
  Gemfile
  google-cloud-assured_workloads-v1beta1/.gitignore
  google-cloud-assured_workloads-v1beta1/.repo-metadata.json
  google-cloud-assured_workloads-v1beta1/.rubocop.yml
  google-cloud-assured_workloads-v1beta1/.yardopts
  google-cloud-assured_workloads-v1beta1/AUTHENTICATION.md
  google-cloud-assured_workloads-v1beta1/CHANGELOG.md
  google-cloud-assured_workloads-v1beta1/Gemfile
  google-cloud-assured_workloads-v1beta1/LICENSE.md
  google-cloud-assured_workloads-v1beta1/README.md
  google-cloud-assured_workloads-v1beta1/Rakefile
  google-cloud-assured_workloads-v1beta1/google-cloud-assured_workloads-v1beta1.gemspec
  google-cloud-assured_workloads-v1beta1/lib/google-cloud-assured_workloads-v1beta1.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/assured_workloads_service.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/assured_workloads_service/client.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/assured_workloads_service/credentials.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/assured_workloads_service/operations.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/assured_workloads_service/paths.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/version.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assuredworkloads/v1beta1/assuredworkloads_v1beta1_pb.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assuredworkloads/v1beta1/assuredworkloads_v1beta1_services_pb.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/README.md
  google-cloud-assured_workloads-v1beta1/proto_docs/google/api/field_behavior.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/cloud/assuredworkloads/v1beta1/assuredworkloads_v1beta1.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/longrunning/operations.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/protobuf/any.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/protobuf/duration.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/protobuf/empty.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-assured_workloads-v1beta1/proto_docs/google/rpc/status.rb
  google-cloud-assured_workloads-v1beta1/synth.metadata
  google-cloud-assured_workloads-v1beta1/synth.py
  google-cloud-assured_workloads-v1beta1/test/google/cloud/assured_workloads/v1beta1/assured_workloads_service_operations_test.rb
  google-cloud-assured_workloads-v1beta1/test/google/cloud/assured_workloads/v1beta1/assured_workloads_service_paths_test.rb
  google-cloud-assured_workloads-v1beta1/test/google/cloud/assured_workloads/v1beta1/assured_workloads_service_test.rb
  google-cloud-assured_workloads-v1beta1/test/helper.rb
Labels: cla: yes

#7672 chore: Generate initial google-analytics-data-v1alpha gapic
  .kokoro/continuous/linux/google-analytics-data-v1alpha.cfg
  .kokoro/continuous/osx/google-analytics-data-v1alpha.cfg
  .kokoro/continuous/windows/google-analytics-data-v1alpha.cfg
  .kokoro/nightly/linux/google-analytics-data-v1alpha.cfg
  .kokoro/nightly/osx/google-analytics-data-v1alpha.cfg
  .kokoro/nightly/windows/google-analytics-data-v1alpha.cfg
  .kokoro/release/google-analytics-data-v1alpha.cfg
  Gemfile
  google-analytics-data-v1alpha/.gitignore
  google-analytics-data-v1alpha/.repo-metadata.json
  google-analytics-data-v1alpha/.rubocop.yml
  google-analytics-data-v1alpha/.yardopts
  google-analytics-data-v1alpha/AUTHENTICATION.md
  google-analytics-data-v1alpha/CHANGELOG.md
  google-analytics-data-v1alpha/Gemfile
  google-analytics-data-v1alpha/LICENSE.md
  google-analytics-data-v1alpha/README.md
  google-analytics-data-v1alpha/Rakefile
  google-analytics-data-v1alpha/google-analytics-data-v1alpha.gemspec
  google-analytics-data-v1alpha/lib/google-analytics-data-v1alpha.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/client.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/credentials.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/paths.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_pb.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_services_pb.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/data_pb.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/version.rb
  google-analytics-data-v1alpha/proto_docs/README.md
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/analytics_data_api.rb
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/data.rb
  google-analytics-data-v1alpha/proto_docs/google/api/field_behavior.rb
  google-analytics-data-v1alpha/proto_docs/google/api/resource.rb
  google-analytics-data-v1alpha/synth.metadata
  google-analytics-data-v1alpha/synth.py
  google-analytics-data-v1alpha/test/google/analytics/data/v1alpha/analytics_data_paths_test.rb
  google-analytics-data-v1alpha/test/google/analytics/data/v1alpha/analytics_data_test.rb
  google-analytics-data-v1alpha/test/helper.rb
Labels: cla: yes

#7646 Release google-cloud-pubsub 2.1.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#7666 Release google-cloud-datastore 2.1.0
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes

#7803 [CHANGE ME] Re-generated grafeas to pick up changes in the API or client library generator.
  grafeas/.rubocop.yml
  grafeas/synth.metadata
Labels: cla: yes, context: none

#7801 [CHANGE ME] Re-generated google-cloud-web_risk to pick up changes in the API or client library generator.
  google-cloud-web_risk/.rubocop.yml
  google-cloud-web_risk/synth.metadata
Labels: cla: yes, context: none

#7798 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/.rubocop.yml
  google-cloud-vision/synth.metadata
Labels: cla: yes, context: none

#7795 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/.rubocop.yml
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes, context: none

#7790 [CHANGE ME] Re-generated google-cloud-translate to pick up changes in the API or client library generator.
  google-cloud-translate/.rubocop.yml
  google-cloud-translate/synth.metadata
Labels: cla: yes, context: none

#7786 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/.rubocop.yml
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes, context: none

#7783 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/.rubocop.yml
  google-cloud-tasks/synth.metadata
Labels: cla: yes, context: none

#7779 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/.rubocop.yml
  google-cloud-talent/synth.metadata
Labels: cla: yes, context: none

#7776 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/.rubocop.yml
  google-cloud-speech/synth.metadata
Labels: cla: yes, context: none

#7770 [CHANGE ME] Re-generated google-cloud-service_directory to pick up changes in the API or client library generator.
  google-cloud-service_directory/.rubocop.yml
  google-cloud-service_directory/synth.metadata
Labels: cla: yes, context: none

#7768 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/.rubocop.yml
  google-cloud-security_center/synth.metadata
Labels: cla: yes, context: none

#7765 [CHANGE ME] Re-generated google-cloud-secret_manager to pick up changes in the API or client library generator.
  google-cloud-secret_manager/.rubocop.yml
  google-cloud-secret_manager/synth.metadata
Labels: cla: yes, context: none

#7762 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/.rubocop.yml
  google-cloud-scheduler/synth.metadata
Labels: cla: yes, context: none

#7759 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/.rubocop.yml
  google-cloud-redis/synth.metadata
Labels: cla: yes, context: none

#7756 [CHANGE ME] Re-generated google-cloud-recommender to pick up changes in the API or client library generator.
  google-cloud-recommender/.rubocop.yml
  google-cloud-recommender/synth.metadata
Labels: cla: yes, context: none

#7754 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/.rubocop.yml
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes, context: none

#7749 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/.rubocop.yml
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes, context: none

#7747 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/.rubocop.yml
  google-cloud-os_login/synth.metadata
Labels: cla: yes, context: none

#7744 [CHANGE ME] Re-generated google-cloud-os_config to pick up changes in the API or client library generator.
  google-cloud-os_config/.rubocop.yml
  google-cloud-os_config/synth.metadata
Labels: cla: yes, context: none

#7741 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/.rubocop.yml
  google-cloud-monitoring/synth.metadata
Labels: cla: yes, context: none

#7738 [CHANGE ME] Re-generated google-cloud-memcache to pick up changes in the API or client library generator.
  google-cloud-memcache/.rubocop.yml
  google-cloud-memcache/synth.metadata
Labels: cla: yes, context: none

#7735 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/.rubocop.yml
  google-cloud-language/synth.metadata
Labels: cla: yes, context: none

#7732 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/.rubocop.yml
  google-cloud-kms/synth.metadata
Labels: cla: yes, context: none

#7730 [CHANGE ME] Re-generated google-cloud-iot to pick up changes in the API or client library generator.
  google-cloud-iot/.rubocop.yml
  google-cloud-iot/synth.metadata
Labels: cla: yes, context: none

#7728 [CHANGE ME] Re-generated google-cloud-gaming to pick up changes in the API or client library generator.
  google-cloud-gaming/.rubocop.yml
  google-cloud-gaming/synth.metadata
Labels: cla: yes, context: none

#7722 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/.rubocop.yml
  google-cloud-dlp/synth.metadata
Labels: cla: yes, context: none

#7720 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/.rubocop.yml
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes, context: none

#7715 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/.rubocop.yml
  google-cloud-dataproc/synth.metadata
Labels: cla: yes, context: none

#7712 [CHANGE ME] Re-generated google-cloud-data_catalog to pick up changes in the API or client library generator.
  google-cloud-data_catalog/.rubocop.yml
  google-cloud-data_catalog/synth.metadata
Labels: cla: yes, context: none

#7710 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/.rubocop.yml
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes, context: none

#7708 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/.rubocop.yml
  google-cloud-container/synth.metadata
Labels: cla: yes, context: none

#7705 [CHANGE ME] Re-generated google-cloud-build to pick up changes in the API or client library generator.
  google-cloud-build/.rubocop.yml
  google-cloud-build/synth.metadata
Labels: cla: yes, context: none

#7703 [CHANGE ME] Re-generated google-cloud-billing to pick up changes in the API or client library generator.
  google-cloud-billing/.rubocop.yml
  google-cloud-billing/synth.metadata
Labels: cla: yes, context: none

#7698 [CHANGE ME] Re-generated google-cloud-bigquery-storage to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage/.rubocop.yml
  google-cloud-bigquery-storage/synth.metadata
Labels: cla: yes, context: none

#7695 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/.rubocop.yml
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes, context: none

#7692 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/.rubocop.yml
  google-cloud-automl/synth.metadata
Labels: cla: yes, context: none

#7688 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/.rubocop.yml
  google-cloud-asset/synth.metadata
Labels: cla: yes, context: none

#7685 [CHANGE ME] Re-generated google-cloud-access_approval to pick up changes in the API or client library generator.
  google-cloud-access_approval/.rubocop.yml
  google-cloud-access_approval/synth.metadata
Labels: cla: yes, context: none

#7802 [CHANGE ME] Re-generated grafeas-v1 to pick up changes in the API or client library generator.
  grafeas-v1/.rubocop.yml
  grafeas-v1/Rakefile
  grafeas-v1/proto_docs/google/api/resource.rb
  grafeas-v1/synth.metadata
Labels: cla: yes, context: none

#7800 [CHANGE ME] Re-generated google-cloud-web_risk-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1beta1/.rubocop.yml
  google-cloud-web_risk-v1beta1/Rakefile
  google-cloud-web_risk-v1beta1/lib/google/cloud/webrisk/v1beta1/webrisk_services_pb.rb
  google-cloud-web_risk-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-web_risk-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7799 [CHANGE ME] Re-generated google-cloud-web_risk-v1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1/.rubocop.yml
  google-cloud-web_risk-v1/Rakefile
  google-cloud-web_risk-v1/lib/google/cloud/webrisk/v1/webrisk_services_pb.rb
  google-cloud-web_risk-v1/proto_docs/google/api/resource.rb
  google-cloud-web_risk-v1/synth.metadata
Labels: cla: yes, context: none

#7797 [CHANGE ME] Re-generated google-cloud-vision-v1p3beta1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1p3beta1/.rubocop.yml
  google-cloud-vision-v1p3beta1/Rakefile
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/image_annotator_services_pb.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/product_search_service_services_pb.rb
  google-cloud-vision-v1p3beta1/proto_docs/google/api/resource.rb
  google-cloud-vision-v1p3beta1/synth.metadata
Labels: cla: yes, context: none

#7796 [CHANGE ME] Re-generated google-cloud-vision-v1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1/.rubocop.yml
  google-cloud-vision-v1/Rakefile
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator_services_pb.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search_service_services_pb.rb
  google-cloud-vision-v1/proto_docs/google/api/resource.rb
  google-cloud-vision-v1/synth.metadata
Labels: cla: yes, context: none

#7794 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p2beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p2beta1/.rubocop.yml
  google-cloud-video_intelligence-v1p2beta1/Rakefile
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/videointelligence/v1p2beta1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence-v1p2beta1/proto_docs/google/api/resource.rb
  google-cloud-video_intelligence-v1p2beta1/synth.metadata
Labels: cla: yes, context: none

#7793 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p1beta1/.rubocop.yml
  google-cloud-video_intelligence-v1p1beta1/Rakefile
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/videointelligence/v1p1beta1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence-v1p1beta1/proto_docs/google/api/resource.rb
  google-cloud-video_intelligence-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#7792 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1beta2/.rubocop.yml
  google-cloud-video_intelligence-v1beta2/Rakefile
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/videointelligence/v1beta2/video_intelligence_services_pb.rb
  google-cloud-video_intelligence-v1beta2/proto_docs/google/api/resource.rb
  google-cloud-video_intelligence-v1beta2/synth.metadata
Labels: cla: yes, context: none

#7791 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1/.rubocop.yml
  google-cloud-video_intelligence-v1/Rakefile
  google-cloud-video_intelligence-v1/lib/google/cloud/videointelligence/v1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence-v1/proto_docs/google/api/resource.rb
  google-cloud-video_intelligence-v1/synth.metadata
Labels: cla: yes, context: none

#7789 [CHANGE ME] Re-generated google-cloud-translate-v3 to pick up changes in the API or client library generator.
  google-cloud-translate-v3/.rubocop.yml
  google-cloud-translate-v3/Rakefile
  google-cloud-translate-v3/lib/google/cloud/translate/v3/translation_service_services_pb.rb
  google-cloud-translate-v3/proto_docs/google/api/resource.rb
  google-cloud-translate-v3/synth.metadata
Labels: cla: yes, context: none

#7788 [CHANGE ME] Re-generated google-cloud-trace-v2 to pick up changes in the API or client library generator.
  google-cloud-trace-v2/.rubocop.yml
  google-cloud-trace-v2/Rakefile
  google-cloud-trace-v2/lib/google/devtools/cloudtrace/v2/tracing_services_pb.rb
  google-cloud-trace-v2/proto_docs/google/api/resource.rb
  google-cloud-trace-v2/synth.metadata
Labels: cla: yes, context: none

#7787 [CHANGE ME] Re-generated google-cloud-trace-v1 to pick up changes in the API or client library generator.
  google-cloud-trace-v1/.rubocop.yml
  google-cloud-trace-v1/Rakefile
  google-cloud-trace-v1/lib/google/devtools/cloudtrace/v1/trace_services_pb.rb
  google-cloud-trace-v1/proto_docs/google/api/resource.rb
  google-cloud-trace-v1/synth.metadata
Labels: cla: yes, context: none

#7785 [CHANGE ME] Re-generated google-cloud-text_to_speech-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-text_to_speech-v1beta1/.rubocop.yml
  google-cloud-text_to_speech-v1beta1/Rakefile
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/texttospeech/v1beta1/cloud_tts_services_pb.rb
  google-cloud-text_to_speech-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-text_to_speech-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7784 [CHANGE ME] Re-generated google-cloud-text_to_speech-v1 to pick up changes in the API or client library generator.
  google-cloud-text_to_speech-v1/.rubocop.yml
  google-cloud-text_to_speech-v1/Rakefile
  google-cloud-text_to_speech-v1/lib/google/cloud/texttospeech/v1/cloud_tts_services_pb.rb
  google-cloud-text_to_speech-v1/proto_docs/google/api/resource.rb
  google-cloud-text_to_speech-v1/synth.metadata
Labels: cla: yes, context: none

#7782 [CHANGE ME] Re-generated google-cloud-tasks-v2beta3 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta3/.rubocop.yml
  google-cloud-tasks-v2beta3/Rakefile
  google-cloud-tasks-v2beta3/lib/google/cloud/tasks/v2beta3/cloudtasks_services_pb.rb
  google-cloud-tasks-v2beta3/proto_docs/google/api/resource.rb
  google-cloud-tasks-v2beta3/synth.metadata
Labels: cla: yes, context: none

#7781 [CHANGE ME] Re-generated google-cloud-tasks-v2beta2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta2/.rubocop.yml
  google-cloud-tasks-v2beta2/Rakefile
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/cloudtasks_services_pb.rb
  google-cloud-tasks-v2beta2/proto_docs/google/api/resource.rb
  google-cloud-tasks-v2beta2/synth.metadata
Labels: cla: yes, context: none

#7780 [CHANGE ME] Re-generated google-cloud-tasks-v2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2/.rubocop.yml
  google-cloud-tasks-v2/Rakefile
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/cloudtasks_services_pb.rb
  google-cloud-tasks-v2/proto_docs/google/api/resource.rb
  google-cloud-tasks-v2/synth.metadata
Labels: cla: yes, context: none

#7778 [CHANGE ME] Re-generated google-cloud-talent-v4beta1 to pick up changes in the API or client library generator.
  google-cloud-talent-v4beta1/.rubocop.yml
  google-cloud-talent-v4beta1/Rakefile
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/application_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/company_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/completion_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/event_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/job_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/profile_service_services_pb.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/tenant_service_services_pb.rb
  google-cloud-talent-v4beta1/proto_docs/google/api/resource.rb
  google-cloud-talent-v4beta1/synth.metadata
Labels: cla: yes, context: none

#7777 [CHANGE ME] Re-generated google-cloud-talent-v4 to pick up changes in the API or client library generator.
  google-cloud-talent-v4/.rubocop.yml
  google-cloud-talent-v4/Rakefile
  google-cloud-talent-v4/lib/google/cloud/talent/v4/company_service_services_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/completion_service_services_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/event_service_services_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/job_service_services_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/tenant_service_services_pb.rb
  google-cloud-talent-v4/proto_docs/google/api/resource.rb
  google-cloud-talent-v4/synth.metadata
Labels: cla: yes, context: none

#7775 [CHANGE ME] Re-generated google-cloud-speech-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1p1beta1/.rubocop.yml
  google-cloud-speech-v1p1beta1/Rakefile
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/cloud_speech_services_pb.rb
  google-cloud-speech-v1p1beta1/proto_docs/google/api/resource.rb
  google-cloud-speech-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#7774 [CHANGE ME] Re-generated google-cloud-speech-v1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1/.rubocop.yml
  google-cloud-speech-v1/Rakefile
  google-cloud-speech-v1/lib/google/cloud/speech/v1/cloud_speech_services_pb.rb
  google-cloud-speech-v1/proto_docs/google/api/resource.rb
  google-cloud-speech-v1/synth.metadata
Labels: cla: yes, context: none

#7773 [CHANGE ME] Re-generated google-cloud-spanner-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-v1/.rubocop.yml
  google-cloud-spanner-v1/Rakefile
  google-cloud-spanner-v1/lib/google/spanner/v1/spanner_services_pb.rb
  google-cloud-spanner-v1/proto_docs/google/api/resource.rb
  google-cloud-spanner-v1/synth.metadata
Labels: cla: yes, context: none

#7772 [CHANGE ME] Re-generated google-cloud-spanner-admin-instance-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-admin-instance-v1/.rubocop.yml
  google-cloud-spanner-admin-instance-v1/Rakefile
  google-cloud-spanner-admin-instance-v1/lib/google/spanner/admin/instance/v1/spanner_instance_admin_services_pb.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/api/resource.rb
  google-cloud-spanner-admin-instance-v1/synth.metadata
Labels: cla: yes, context: none

#7771 [CHANGE ME] Re-generated google-cloud-spanner-admin-database-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-admin-database-v1/.rubocop.yml
  google-cloud-spanner-admin-database-v1/Rakefile
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/spanner_database_admin_services_pb.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/api/resource.rb
  google-cloud-spanner-admin-database-v1/synth.metadata
Labels: cla: yes, context: none

#7769 [CHANGE ME] Re-generated google-cloud-service_directory-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1beta1/.rubocop.yml
  google-cloud-service_directory-v1beta1/Rakefile
  google-cloud-service_directory-v1beta1/lib/google/cloud/servicedirectory/v1beta1/lookup_service_services_pb.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/servicedirectory/v1beta1/registration_service_services_pb.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-service_directory-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7767 [CHANGE ME] Re-generated google-cloud-security_center-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-security_center-v1p1beta1/.rubocop.yml
  google-cloud-security_center-v1p1beta1/Rakefile
  google-cloud-security_center-v1p1beta1/lib/google/cloud/securitycenter/v1p1beta1/securitycenter_service_services_pb.rb
  google-cloud-security_center-v1p1beta1/proto_docs/google/api/resource.rb
  google-cloud-security_center-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#7766 [CHANGE ME] Re-generated google-cloud-security_center-v1 to pick up changes in the API or client library generator.
  google-cloud-security_center-v1/.rubocop.yml
  google-cloud-security_center-v1/Rakefile
  google-cloud-security_center-v1/lib/google/cloud/securitycenter/v1/securitycenter_service_services_pb.rb
  google-cloud-security_center-v1/proto_docs/google/api/resource.rb
  google-cloud-security_center-v1/synth.metadata
Labels: cla: yes, context: none

#7764 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/.rubocop.yml
  google-cloud-secret_manager-v1beta1/Rakefile
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secrets/v1beta1/service_services_pb.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7763 [CHANGE ME] Re-generated google-cloud-secret_manager-v1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1/.rubocop.yml
  google-cloud-secret_manager-v1/Rakefile
  google-cloud-secret_manager-v1/lib/google/cloud/secretmanager/v1/service_services_pb.rb
  google-cloud-secret_manager-v1/proto_docs/google/api/resource.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes, context: none

#7761 [CHANGE ME] Re-generated google-cloud-scheduler-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1beta1/.rubocop.yml
  google-cloud-scheduler-v1beta1/Rakefile
  google-cloud-scheduler-v1beta1/lib/google/cloud/scheduler/v1beta1/cloudscheduler_services_pb.rb
  google-cloud-scheduler-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-scheduler-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7760 [CHANGE ME] Re-generated google-cloud-scheduler-v1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1/.rubocop.yml
  google-cloud-scheduler-v1/Rakefile
  google-cloud-scheduler-v1/lib/google/cloud/scheduler/v1/cloudscheduler_services_pb.rb
  google-cloud-scheduler-v1/proto_docs/google/api/resource.rb
  google-cloud-scheduler-v1/synth.metadata
Labels: cla: yes, context: none

#7758 [CHANGE ME] Re-generated google-cloud-redis-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-redis-v1beta1/.rubocop.yml
  google-cloud-redis-v1beta1/Rakefile
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis_services_pb.rb
  google-cloud-redis-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-redis-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7757 [CHANGE ME] Re-generated google-cloud-redis-v1 to pick up changes in the API or client library generator.
  google-cloud-redis-v1/.rubocop.yml
  google-cloud-redis-v1/Rakefile
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis_services_pb.rb
  google-cloud-redis-v1/proto_docs/google/api/resource.rb
  google-cloud-redis-v1/synth.metadata
Labels: cla: yes, context: none

#7755 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/.rubocop.yml
  google-cloud-recommender-v1/Rakefile
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender_service_services_pb.rb
  google-cloud-recommender-v1/proto_docs/google/api/resource.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes, context: none

#7753 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise-v1beta1/.rubocop.yml
  google-cloud-recaptcha_enterprise-v1beta1/Rakefile
  google-cloud-recaptcha_enterprise-v1beta1/lib/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise_services_pb.rb
  google-cloud-recaptcha_enterprise-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-recaptcha_enterprise-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7752 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise-v1 to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise-v1/.rubocop.yml
  google-cloud-recaptcha_enterprise-v1/Rakefile
  google-cloud-recaptcha_enterprise-v1/lib/google/cloud/recaptchaenterprise/v1/recaptchaenterprise_services_pb.rb
  google-cloud-recaptcha_enterprise-v1/proto_docs/google/api/resource.rb
  google-cloud-recaptcha_enterprise-v1/synth.metadata
Labels: cla: yes, context: none

#7751 [CHANGE ME] Re-generated google-cloud-pubsub-v1 to pick up changes in the API or client library generator.
  google-cloud-pubsub-v1/.rubocop.yml
  google-cloud-pubsub-v1/Rakefile
  google-cloud-pubsub-v1/lib/google/iam/v1/iam_policy_services_pb.rb
  google-cloud-pubsub-v1/lib/google/pubsub/v1/pubsub_services_pb.rb
  google-cloud-pubsub-v1/proto_docs/google/api/resource.rb
  google-cloud-pubsub-v1/synth.metadata
Labels: cla: yes, context: none

#7750 [CHANGE ME] Re-generated google-cloud-policy_troubleshooter-v1 to pick up changes in the API or client library generator.
  google-cloud-policy_troubleshooter-v1/.rubocop.yml
  google-cloud-policy_troubleshooter-v1/Rakefile
  google-cloud-policy_troubleshooter-v1/lib/google/cloud/policytroubleshooter/v1/checker_services_pb.rb
  google-cloud-policy_troubleshooter-v1/proto_docs/google/api/resource.rb
  google-cloud-policy_troubleshooter-v1/synth.metadata
Labels: cla: yes, context: none

#7748 [CHANGE ME] Re-generated google-cloud-phishing_protection-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-phishing_protection-v1beta1/.rubocop.yml
  google-cloud-phishing_protection-v1beta1/Rakefile
  google-cloud-phishing_protection-v1beta1/lib/google/cloud/phishingprotection/v1beta1/phishingprotection_services_pb.rb
  google-cloud-phishing_protection-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-phishing_protection-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7746 [CHANGE ME] Re-generated google-cloud-os_login-v1beta to pick up changes in the API or client library generator.
  google-cloud-os_login-v1beta/.rubocop.yml
  google-cloud-os_login-v1beta/Rakefile
  google-cloud-os_login-v1beta/lib/google/cloud/oslogin/v1beta/oslogin_services_pb.rb
  google-cloud-os_login-v1beta/proto_docs/google/api/resource.rb
  google-cloud-os_login-v1beta/synth.metadata
Labels: cla: yes, context: none

#7745 [CHANGE ME] Re-generated google-cloud-os_login-v1 to pick up changes in the API or client library generator.
  google-cloud-os_login-v1/.rubocop.yml
  google-cloud-os_login-v1/Rakefile
  google-cloud-os_login-v1/lib/google/cloud/oslogin/v1/oslogin_services_pb.rb
  google-cloud-os_login-v1/proto_docs/google/api/resource.rb
  google-cloud-os_login-v1/synth.metadata
Labels: cla: yes, context: none

#7743 [CHANGE ME] Re-generated google-cloud-os_config-v1 to pick up changes in the API or client library generator.
  google-cloud-os_config-v1/.rubocop.yml
  google-cloud-os_config-v1/Rakefile
  google-cloud-os_config-v1/lib/google/cloud/osconfig/v1/osconfig_service_services_pb.rb
  google-cloud-os_config-v1/proto_docs/google/api/resource.rb
  google-cloud-os_config-v1/synth.metadata
Labels: cla: yes, context: none

#7742 [CHANGE ME] Re-generated google-cloud-notebooks-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-notebooks-v1beta1/.rubocop.yml
  google-cloud-notebooks-v1beta1/Rakefile
  google-cloud-notebooks-v1beta1/lib/google/cloud/notebooks/v1beta1/service_services_pb.rb
  google-cloud-notebooks-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-notebooks-v1beta1/synth.metadata
Labels: cla: yes, context: none

#7740 [CHANGE ME] Re-generated google-cloud-monitoring-v3 to pick up changes in the API or client library generator.
  google-cloud-monitoring-v3/.rubocop.yml
  google-cloud-monitoring-v3/Rakefile
  google-cloud-monitoring-v3/lib/google/monitoring/v3/alert_service_services_pb.rb
  google-cloud-monitoring-v3/lib/google/monitoring/v3/group_service_services_pb.rb
  google-cloud-monitoring-v3/lib/google/monitoring/v3/metric_service_services_pb.rb
  google-cloud-monitoring-v3/lib/google/monitoring/v3/notification_service_services_pb.rb
  google-cloud-monitoring-v3/lib/google/monitoring/v3/service_service_services_pb.rb
  google-cloud-monitoring-v3/lib/google/monitoring/v3/uptime_service_services_pb.rb
  google-cloud-monitoring-v3/proto_docs/google/api/resource.rb
  google-cloud-monitoring-v3/synth.metadata
Labels: cla: yes, context: none

#7739 [CHANGE ME] Re-generated google-cloud-monitoring-dashboard-v1 to pick up changes in the API or client library generator.
  google-cloud-monitoring-dashboard-v1/.rubocop.yml
  google-cloud-monitoring-dashboard-v1/Rakefile
  google-cloud-monitoring-dashboard-v1/lib/google/monitoring/dashboard/v1/dashboards_service_services_pb.rb
  google-cloud-monitoring-dashboard-v1/proto_docs/google/api/resource.rb
  google-cloud-monitoring-dashboard-v1/synth.metadata
Labels: cla: yes, context: none

#7737 [CHANGE ME] Re-generated google-cloud-memcache-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-memcache-v1beta2/.rubocop.yml
  google-cloud-memcache-v1beta2/Rakefile
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/cloud_memcache_services_pb.rb
  google-cloud-memcache-v1beta2/proto_docs/google/api/resource.rb
  google-cloud-memcache-v1beta2/synth.metadata
Labels: cla: yes, context: none

#7736 [CHANGE ME] Re-generated google-cloud-logging-v2 to pick up changes in the API or client library generator.
  google-cloud-logging-v2/.rubocop.yml
  google-cloud-logging-v2/Rakefile
  google-cloud-logging-v2/lib/google/logging/v2/logging_config_services_pb.rb
  google-cloud-logging-v2/lib/google/logging/v2/logging_metrics_services_pb.rb
  google-cloud-logging-v2/lib/google/logging/v2/logging_services_pb.rb
  google-cloud-logging-v2/proto_docs/google/api/resource.rb
  google-cloud-logging-v2/synth.metadata
Labels: cla: yes, context: none

#7734 [CHANGE ME] Re-generated google-cloud-language-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-language-v1beta2/.rubocop.yml
  google-cloud-language-v1beta2/Rakefile
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/language_service_services_pb.rb
  google-cloud-language-v1beta2/proto_docs/google/api/resource.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes, context: none

#7733 [CHANGE ME] Re-generated google-cloud-language-v1 to pick up changes in the API or client library generator.
  google-cloud-language-v1/.rubocop.yml
  google-cloud-language-v1/Rakefile
  google-cloud-language-v1/lib/google/cloud/language/v1/language_service_services_pb.rb
  google-cloud-language-v1/proto_docs/google/api/resource.rb
  google-cloud-language-v1/synth.metadata
Labels: cla: yes, context: none

#7731 [CHANGE ME] Re-generated google-cloud-kms-v1 to pick up changes in the API or client library generator.
  google-cloud-kms-v1/.rubocop.yml
  google-cloud-kms-v1/Rakefile
  google-cloud-kms-v1/lib/google/cloud/kms/v1/service_services_pb.rb
  google-cloud-kms-v1/lib/google/iam/v1/iam_policy_services_pb.rb
  google-cloud-kms-v1/proto_docs/google/api/resource.rb
  google-cloud-kms-v1/synth.metadata
Labels: cla: yes, context: none

#7729 [CHANGE ME] Re-generated google-cloud-iot-v1 to pick up changes in the API or client library generator.
  google-cloud-iot-v1/.rubocop.yml
  google-cloud-iot-v1/Rakefile
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager_services_pb.rb
  google-cloud-iot-v1/proto_docs/google/api/resource.rb
  google-cloud-iot-v1/synth.metadata
Labels: cla: yes, context: none

#7727 [CHANGE ME] Re-generated google-cloud-gaming-v1 to pick up changes in the API or client library generator.
  google-cloud-gaming-v1/.rubocop.yml
  google-cloud-gaming-v1/Rakefile
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_clusters_service_services_pb.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_configs_service_services_pb.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_deployments_service_services_pb.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/realms_service_services_pb.rb
  google-cloud-gaming-v1/proto_docs/google/api/resource.rb
  google-cloud-gaming-v1/synth.metadata
Labels: cla: yes, context: none
