Repository googleapis/google-cloud-ruby, pull requests merged in 2020-10, with the labels that each got.

#7852 chore(firestore): update region tag to be consistent with other languages
  google-cloud-firestore/samples/query_data.rb
Labels: api: firestore, cla: yes

#7851 docs(storage): Update customer-supplied encryption key docs and examples
  google-cloud-storage/lib/google/cloud/storage/file.rb
Labels: api: storage, cla: yes, type: docs

#7855 [google-cloud-talent-v4] feat: Remove commute methods from Job Search v4 API
  google-cloud-talent-v4/lib/google/cloud/talent/v4/common_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/company_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/company_service/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/completion/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/completion_service_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/event_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/event_service/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/filters_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/job_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/tenant_pb.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/tenant_service/client.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/common.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/company.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/company_service.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/completion_service.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/event.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/event_service.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/filters.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/histogram.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/job.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/tenant.rb
  google-cloud-talent-v4/proto_docs/google/cloud/talent/v4/tenant_service.rb
  google-cloud-talent-v4/synth.metadata
Labels: cla: yes, context: full

#7860 fix(storage): Fix encoding of space characters in file names in signed_url v4
  google-cloud-storage/acceptance/storage/bucket_test.rb
  google-cloud-storage/acceptance/storage/signed_url_v2_test.rb
  google-cloud-storage/acceptance/storage/signed_url_v4_test.rb
  google-cloud-storage/lib/google/cloud/storage/file/signer_v4.rb
Labels: api: storage, cla: yes

#7849 Release google-cloud-storage 1.29.1
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes

#7859 Release google-cloud-talent-v4 0.2.0
  google-cloud-talent-v4/CHANGELOG.md
  google-cloud-talent-v4/lib/google/cloud/talent/v4/version.rb
Labels: autorelease: pending, cla: yes

#7862 chore: Move link checker into separate CI job
  .github/workflows/link-checker.yml
  Rakefile
  rakelib/kokoro/kokoro.rb
Labels: cla: yes

#7863 feat(env): Honor GCE_METADATA_HOST environment variable
  google-cloud-env/lib/google/cloud/env.rb
  google-cloud-env/test/google/cloud/env_test.rb
Labels: cla: yes

#7864 [google-analytics-data-v1alpha] feat!: GetMetadata method renamed to GetUniversalMetdata docs: documentation updates
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/client.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/paths.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_pb.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_services_pb.rb
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/analytics_data_api.rb
  google-analytics-data-v1alpha/proto_docs/google/analytics/data/v1alpha/data.rb
  google-analytics-data-v1alpha/proto_docs/google/api/resource.rb
  google-analytics-data-v1alpha/synth.metadata
  google-analytics-data-v1alpha/test/google/analytics/data/v1alpha/analytics_data_paths_test.rb
  google-analytics-data-v1alpha/test/google/analytics/data/v1alpha/analytics_data_test.rb
Labels: cla: yes, context: full

#7938 [google-cloud-automl-v1beta1] feat: Added text extraction health care option in create model.
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/text_pb.rb
  google-cloud-automl-v1beta1/proto_docs/google/cloud/automl/v1beta1/io.rb
  google-cloud-automl-v1beta1/proto_docs/google/cloud/automl/v1beta1/text.rb
  google-cloud-automl-v1beta1/synth.metadata
Labels: cla: yes, context: full

#7868 [google-cloud-language-v1beta2] feat: Fix proto comments for language API inorder for docs parsing to work correctly.
  google-cloud-language-v1beta2/proto_docs/google/cloud/language/v1beta2/language_service.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes, context: full

#7867 [google-cloud-language-v1] feat: Fix proto comments for language API inorder for docs parsing to work correctly.
  google-cloud-language-v1/proto_docs/google/cloud/language/v1/language_service.rb
  google-cloud-language-v1/synth.metadata
Labels: cla: yes, context: full

#7866 [google-cloud-firestore-v1] fix(firestore/v1): give PartitionQuery retry/timeout config
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore/client.rb
  google-cloud-firestore-v1/synth.metadata
Labels: api: firestore, cla: yes, context: full

#7858 [google-cloud-bigquery-connection-v1] feat: add aws connection support
  google-cloud-bigquery-connection-v1/lib/google/cloud/bigquery/connection/v1/connection_pb.rb
  google-cloud-bigquery-connection-v1/proto_docs/google/cloud/bigquery/connection/v1/connection.rb
  google-cloud-bigquery-connection-v1/synth.metadata
Labels: cla: yes, context: full

#7940 Release google-cloud-env 1.4.0
  google-cloud-env/CHANGELOG.md
  google-cloud-env/lib/google/cloud/env/version.rb
Labels: autorelease: pending, cla: yes

#7941 [google-cloud-dialogflow-v2] docs: fixed link from SentimentAnalysisResult
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes, context: full

#7947 [google-cloud-dlp-v2] Fix: retrieve job config for risk analysis jobs. Docs: clarify timespan config for BigQuery and Datastore.
  google-cloud-dlp-v2/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp-v2/proto_docs/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp-v2/synth.metadata
Labels: cla: yes, context: full

#7960 [google-analytics-admin-v1alpha] feat!: added ListAccountSummaries method
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_pb.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service/client.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_services_pb.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/resources_pb.rb
  google-analytics-admin-v1alpha/proto_docs/google/analytics/admin/v1alpha/analytics_admin.rb
  google-analytics-admin-v1alpha/proto_docs/google/analytics/admin/v1alpha/resources.rb
  google-analytics-admin-v1alpha/synth.metadata
  google-analytics-admin-v1alpha/test/google/analytics/admin/v1alpha/analytics_admin_service_test.rb
Labels: cla: yes, context: full

#7952 Release google-cloud-dlp-v2 0.5.0
  google-cloud-dlp-v2/CHANGELOG.md
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/version.rb
Labels: autorelease: pending, cla: yes

#7955 Release google-cloud-bigquery-connection-v1 0.2.0
  google-cloud-bigquery-connection-v1/CHANGELOG.md
  google-cloud-bigquery-connection-v1/lib/google/cloud/bigquery/connection/v1/version.rb
Labels: autorelease: pending, cla: yes

#7956 Release google-cloud-automl-v1beta1 0.3.0
  google-cloud-automl-v1beta1/CHANGELOG.md
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7957 Release google-cloud-firestore-v1 0.2.1
  google-cloud-firestore-v1/CHANGELOG.md
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/version.rb
Labels: autorelease: pending, cla: yes

#7958 Release google-cloud-language-v1beta2 0.2.6
  google-cloud-language-v1beta2/CHANGELOG.md
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#7959 Release google-cloud-language-v1 0.2.6
  google-cloud-language-v1/CHANGELOG.md
  google-cloud-language-v1/lib/google/cloud/language/v1/version.rb
Labels: autorelease: pending, cla: yes

#7962 Release google-analytics-admin-v1alpha 0.2.0
  google-analytics-admin-v1alpha/CHANGELOG.md
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/version.rb
Labels: autorelease: pending, cla: yes

#7942 Release google-analytics-data-v1alpha 0.2.0
  google-analytics-data-v1alpha/CHANGELOG.md
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/version.rb
Labels: autorelease: pending, cla: yes

#7953 chore: Fix ContainerAnalysis synth scripts to handle proto special cases
  google-cloud-container_analysis-v1/synth.py
  google-cloud-container_analysis/synth.py
Labels: cla: yes

#7948 feat(talent)!: Default to version V4 of the service
  google-cloud-talent/AUTHENTICATION.md
  google-cloud-talent/Gemfile
  google-cloud-talent/README.md
  google-cloud-talent/Rakefile
  google-cloud-talent/google-cloud-talent.gemspec
  google-cloud-talent/lib/google/cloud/talent.rb
  google-cloud-talent/samples/Gemfile
  google-cloud-talent/samples/acceptance/helper.rb
  google-cloud-talent/samples/acceptance/talent_test.rb
  google-cloud-talent/samples/autocomplete_job_title.rb
  google-cloud-talent/samples/batch_create_jobs.rb
  google-cloud-talent/samples/batch_delete_jobs.rb
  google-cloud-talent/samples/batch_update_jobs.rb
  google-cloud-talent/samples/commute_search.rb
  google-cloud-talent/samples/create_client_event.rb
  google-cloud-talent/samples/create_company.rb
  google-cloud-talent/samples/create_job.rb
  google-cloud-talent/samples/create_job_custom_attributes.rb
  google-cloud-talent/samples/custom_ranking_search.rb
  google-cloud-talent/samples/delete_company.rb
  google-cloud-talent/samples/delete_job.rb
  google-cloud-talent/samples/get_company.rb
  google-cloud-talent/samples/get_job.rb
  google-cloud-talent/samples/histogram_search.rb
  google-cloud-talent/samples/list_companies.rb
  google-cloud-talent/samples/list_jobs.rb
  google-cloud-talent/synth.metadata
  google-cloud-talent/synth.py
  google-cloud-talent/test/google/cloud/talent/client_test.rb
Labels: cla: yes

#7965 [CHANGE ME] Re-generated google-cloud-container_analysis-v1 to pick up changes in the API or client library generator.
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/container_analysis.rb
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/container_analysis/client.rb
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/container_analysis/paths.rb
  google-cloud-container_analysis-v1/lib/google/devtools/containeranalysis/v1/containeranalysis_pb.rb
  google-cloud-container_analysis-v1/lib/google/devtools/containeranalysis/v1/containeranalysis_services_pb.rb
  google-cloud-container_analysis-v1/proto_docs/google/devtools/containeranalysis/v1/containeranalysis.rb
  google-cloud-container_analysis-v1/proto_docs/grafeas/v1/common.rb
  google-cloud-container_analysis-v1/proto_docs/grafeas/v1/cvss.rb
  google-cloud-container_analysis-v1/proto_docs/grafeas/v1/package.rb
  google-cloud-container_analysis-v1/proto_docs/grafeas/v1/vulnerability.rb
  google-cloud-container_analysis-v1/synth.metadata
  google-cloud-container_analysis-v1/test/google/cloud/container_analysis/v1/container_analysis_paths_test.rb
  google-cloud-container_analysis-v1/test/google/cloud/container_analysis/v1/container_analysis_test.rb
Labels: cla: yes, context: partial

#7967 chore: Normalize Setup instructions in samples READMEs
  google-cloud-dialogflow/samples/README.md
  google-cloud-firestore/samples/README.md
  google-cloud-language/samples/README.md
  google-cloud-monitoring/samples/README.md
  google-cloud-speech/samples/README.md
  google-cloud-text_to_speech/samples/README.md
  google-cloud-translate/samples/README.md
  google-cloud-video_intelligence/samples/README.md
  google-cloud-vision/samples/README.md
Labels: cla: yes

#8040 chore: start tracking obsolete files
  google-cloud-security-private_ca-v1beta1/synth.metadata
Labels: cla: yes, context: full

#7970 feat: Initial generation of google-cloud-security-private_ca wrapper
  .kokoro/continuous/linux/security-private_ca.cfg
  .kokoro/continuous/osx/security-private_ca.cfg
  .kokoro/continuous/windows/security-private_ca.cfg
  .kokoro/nightly/linux/security-private_ca.cfg
  .kokoro/nightly/osx/security-private_ca.cfg
  .kokoro/nightly/windows/security-private_ca.cfg
  .kokoro/osx.sh
  .kokoro/release/security-private_ca.cfg
  .kokoro/samples_latest/linux/security-private_ca.cfg
  .kokoro/samples_latest/osx/security-private_ca.cfg
  .kokoro/samples_latest/windows/security-private_ca.cfg
  .kokoro/samples_presubmit/linux/ruby_2.7.2.cfg
  .kokoro/trampoline.sh
  Gemfile
  google-cloud-security-private_ca/.gitignore
  google-cloud-security-private_ca/.repo-metadata.json
  google-cloud-security-private_ca/.rubocop.yml
  google-cloud-security-private_ca/.yardopts
  google-cloud-security-private_ca/AUTHENTICATION.md
  google-cloud-security-private_ca/CHANGELOG.md
  google-cloud-security-private_ca/Gemfile
  google-cloud-security-private_ca/LICENSE.md
  google-cloud-security-private_ca/README.md
  google-cloud-security-private_ca/Rakefile
  google-cloud-security-private_ca/google-cloud-security-private_ca.gemspec
  google-cloud-security-private_ca/lib/google-cloud-security-private_ca.rb
  google-cloud-security-private_ca/lib/google/cloud/security/private_ca.rb
  google-cloud-security-private_ca/lib/google/cloud/security/private_ca/version.rb
  google-cloud-security-private_ca/synth.metadata
  google-cloud-security-private_ca/synth.py
  google-cloud-security-private_ca/test/google/cloud/security/private_ca/client_test.rb
  google-cloud-security-private_ca/test/google/cloud/security/private_ca/version_test.rb
  google-cloud-security-private_ca/test/helper.rb
Labels: cla: yes

#7968 Release google-cloud-security-private_ca-v1beta1 0.1.0
  google-cloud-security-private_ca-v1beta1/CHANGELOG.md
  google-cloud-security-private_ca-v1beta1/lib/google/cloud/security/private_ca/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#7966 Release google-cloud-container_analysis-v1 0.2.0
  google-cloud-container_analysis-v1/CHANGELOG.md
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/version.rb
Labels: autorelease: pending, cla: yes

#7969 Release google-cloud-talent 1.0.0
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes

#8043 chore: start tracking obsolete files
  google-cloud-security-private_ca/synth.metadata
Labels: cla: yes, context: full

#8044 Release google-cloud-security-private_ca 0.1.0
  google-cloud-security-private_ca/CHANGELOG.md
  google-cloud-security-private_ca/lib/google/cloud/security/private_ca/version.rb
Labels: autorelease: pending, cla: yes

#8045 docs(bigquery): Update supported types for time partition type
  google-cloud-bigquery/lib/google/cloud/bigquery/load_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
Labels: api: bigquery, cla: yes, type: feature request

#8048 #8047 update sample to illustrate AR style urls
  google-cloud-container_analysis/samples/sample.rb
Labels: cla: yes, samples

#8042 [google-cloud-firestore-v1] fix: retry PartitionQuery for INTERNAL and DEADLINE_EXCEEDED
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore/client.rb
  google-cloud-firestore-v1/synth.metadata
Labels: cla: yes, context: full

#8051 docs(pubsub): Update deprecated attribute name limit to max_outstanding_messages
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/test/google/cloud/pubsub/async_publisher_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber_test.rb
Labels: cla: yes

#8052 Release google-analytics-data-v1alpha 0.3.0
  google-analytics-data-v1alpha/CHANGELOG.md
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/version.rb
Labels: autorelease: pending, cla: yes

#8053 Release google-cloud-firestore-v1 0.2.2
  google-cloud-firestore-v1/CHANGELOG.md
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/version.rb
Labels: autorelease: pending, cla: yes

#8054 Release google-cloud-pubsub 2.1.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#8050 fix(bigquery): Ensure dense encoding of JSON responses
  google-cloud-bigquery/google-cloud-bigquery.gemspec
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/test/google/cloud/bigquery/service_test.rb
Labels: api: bigquery, cla: yes, do not merge

#8061 feat: Initial generation of google-cloud-workflows-v1beta
  .kokoro/continuous/linux/workflows-v1beta.cfg
  .kokoro/continuous/osx/workflows-v1beta.cfg
  .kokoro/continuous/windows/workflows-v1beta.cfg
  .kokoro/nightly/linux/workflows-v1beta.cfg
  .kokoro/nightly/osx/workflows-v1beta.cfg
  .kokoro/nightly/windows/workflows-v1beta.cfg
  .kokoro/release/workflows-v1beta.cfg
  Gemfile
  google-cloud-workflows-v1beta/.gitignore
  google-cloud-workflows-v1beta/.repo-metadata.json
  google-cloud-workflows-v1beta/.rubocop.yml
  google-cloud-workflows-v1beta/.yardopts
  google-cloud-workflows-v1beta/AUTHENTICATION.md
  google-cloud-workflows-v1beta/CHANGELOG.md
  google-cloud-workflows-v1beta/Gemfile
  google-cloud-workflows-v1beta/LICENSE.md
  google-cloud-workflows-v1beta/README.md
  google-cloud-workflows-v1beta/Rakefile
  google-cloud-workflows-v1beta/google-cloud-workflows-v1beta.gemspec
  google-cloud-workflows-v1beta/lib/google-cloud-workflows-v1beta.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/version.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows/client.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows/credentials.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows/operations.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows/paths.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows_pb.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows_services_pb.rb
  google-cloud-workflows-v1beta/proto_docs/README.md
  google-cloud-workflows-v1beta/proto_docs/google/api/field_behavior.rb
  google-cloud-workflows-v1beta/proto_docs/google/api/resource.rb
  google-cloud-workflows-v1beta/proto_docs/google/cloud/workflows/v1beta/workflows.rb
  google-cloud-workflows-v1beta/proto_docs/google/longrunning/operations.rb
  google-cloud-workflows-v1beta/proto_docs/google/protobuf/any.rb
  google-cloud-workflows-v1beta/proto_docs/google/protobuf/empty.rb
  google-cloud-workflows-v1beta/proto_docs/google/protobuf/field_mask.rb
  google-cloud-workflows-v1beta/proto_docs/google/protobuf/timestamp.rb
  google-cloud-workflows-v1beta/proto_docs/google/rpc/status.rb
  google-cloud-workflows-v1beta/synth.metadata
  google-cloud-workflows-v1beta/synth.py
  google-cloud-workflows-v1beta/test/google/cloud/workflows/v1beta/workflows_operations_test.rb
  google-cloud-workflows-v1beta/test/google/cloud/workflows/v1beta/workflows_paths_test.rb
  google-cloud-workflows-v1beta/test/google/cloud/workflows/v1beta/workflows_test.rb
  google-cloud-workflows-v1beta/test/helper.rb
Labels: cla: yes

#8064 [google-cloud-recommender-v1] fix: updating the v1 retry params name for ListInsights, GetInsight, and MarkInsightAccepted.
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes, context: full

#8056 [google-analytics-admin-v1alpha] docs: renamed App + Web to Google Analytics 4 (GA4) in public documentation
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service/client.rb
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_services_pb.rb
  google-analytics-admin-v1alpha/proto_docs/google/analytics/admin/v1alpha/resources.rb
  google-analytics-admin-v1alpha/synth.metadata
Labels: cla: yes, context: full

#8062 feat: Initial generation of google-cloud-workflows wrapper
  .kokoro/continuous/linux/workflows.cfg
  .kokoro/continuous/osx/workflows.cfg
  .kokoro/continuous/windows/workflows.cfg
  .kokoro/nightly/linux/workflows.cfg
  .kokoro/nightly/osx/workflows.cfg
  .kokoro/nightly/windows/workflows.cfg
  .kokoro/release/workflows.cfg
  .kokoro/samples_latest/linux/workflows.cfg
  .kokoro/samples_latest/osx/workflows.cfg
  .kokoro/samples_latest/windows/workflows.cfg
  Gemfile
  google-cloud-workflows/.gitignore
  google-cloud-workflows/.repo-metadata.json
  google-cloud-workflows/.rubocop.yml
  google-cloud-workflows/.yardopts
  google-cloud-workflows/AUTHENTICATION.md
  google-cloud-workflows/CHANGELOG.md
  google-cloud-workflows/Gemfile
  google-cloud-workflows/LICENSE.md
  google-cloud-workflows/README.md
  google-cloud-workflows/Rakefile
  google-cloud-workflows/google-cloud-workflows.gemspec
  google-cloud-workflows/lib/google-cloud-workflows.rb
  google-cloud-workflows/lib/google/cloud/workflows.rb
  google-cloud-workflows/lib/google/cloud/workflows/version.rb
  google-cloud-workflows/synth.metadata
  google-cloud-workflows/synth.py
  google-cloud-workflows/test/google/cloud/workflows/client_test.rb
  google-cloud-workflows/test/google/cloud/workflows/version_test.rb
  google-cloud-workflows/test/helper.rb
Labels: cla: yes

#8055 feat(bigquery): Add iamMember to Dataset::Access
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset/access.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_access_test.rb
Labels: api: bigquery, cla: yes

#8070 chore: start tracking obsolete files
  google-cloud-workflows-v1beta/synth.metadata
Labels: cla: yes, context: full

#8071 chore: start tracking obsolete files
  google-cloud-workflows/synth.metadata
Labels: cla: yes, context: full

#8069 [google-cloud-billing-budgets-v1beta1] feat: Add support for credit type filter field.
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/budget_model_pb.rb
  google-cloud-billing-budgets-v1beta1/proto_docs/google/cloud/billing/budgets/v1beta1/budget_model.rb
  google-cloud-billing-budgets-v1beta1/synth.metadata
Labels: cla: yes, context: full

#8073 Release google-cloud-workflows-v1beta 0.1.0
  google-cloud-workflows-v1beta/CHANGELOG.md
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/version.rb
Labels: autorelease: pending, cla: yes

#8074 Release google-cloud-workflows 0.1.0
  google-cloud-workflows/CHANGELOG.md
  google-cloud-workflows/lib/google/cloud/workflows/version.rb
Labels: autorelease: pending, cla: yes

#8068 [google-cloud-bigtable-admin-v2] feat:Update BigtableTableAdmin GetIamPolicy to include the additional binding for Backup. feat:Change DeleteAppProfileRequest.ignore_warnings to REQUIRED.
  google-cloud-bigtable-admin-v2/lib/google/bigtable/admin/v2/bigtable_instance_admin_services_pb.rb
  google-cloud-bigtable-admin-v2/lib/google/bigtable/admin/v2/bigtable_table_admin_pb.rb
  google-cloud-bigtable-admin-v2/lib/google/bigtable/admin/v2/bigtable_table_admin_services_pb.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin/client.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin/client.rb
  google-cloud-bigtable-admin-v2/proto_docs/google/bigtable/admin/v2/bigtable_instance_admin.rb
  google-cloud-bigtable-admin-v2/proto_docs/google/bigtable/admin/v2/bigtable_table_admin.rb
  google-cloud-bigtable-admin-v2/synth.metadata
Labels: cla: yes, context: full

#8075 Release google-cloud-bigtable-admin-v2 0.2.0
  google-cloud-bigtable-admin-v2/CHANGELOG.md
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/version.rb
Labels: autorelease: pending, cla: yes

#8066 Release google-cloud-bigquery 1.24.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes

#8067 Release google-cloud-recommender-v1 0.5.3
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
Labels: autorelease: pending, cla: yes

#8078 [google-cloud-asset-v1] feat: add AnalyzeIamPolicy and AnalyzeIamPolicyLongrunning RPCs
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_services_pb.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/assets_pb.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/asset_service.rb
  google-cloud-asset-v1/proto_docs/google/cloud/asset/v1/assets.rb
  google-cloud-asset-v1/synth.metadata
  google-cloud-asset-v1/test/google/cloud/asset/v1/asset_service_test.rb
Labels: cla: yes, context: full
