Repository googleapis/google-cloud-ruby, pull requests merged in 2020-03, with the labels that each got.

#4863 fix(translate): support faraday 1.x
  google-cloud-translate/google-cloud-translate.gemspec
Labels: cla: yes

#4862 fix(env): support faraday 1.x
  google-cloud-env/google-cloud-env.gemspec
Labels: cla: yes

#4860 Release google-cloud-dataproc 0.9.1
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes

#4895 Release google-cloud-env 1.3.1
  google-cloud-env/CHANGELOG.md
  google-cloud-env/lib/google/cloud/env/version.rb
Labels: autorelease: pending, cla: yes

#4894 Release google-cloud-translate 2.1.2
  google-cloud-translate/CHANGELOG.md
  google-cloud-translate/lib/google/cloud/translate/version.rb
Labels: autorelease: pending, cla: yes

#4892 Release google-cloud-dialogflow 0.14.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes

#4865 Release google-cloud-security_center 0.7.0
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes

#4861 Release google-cloud-firestore 1.3.0
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#4898 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl/v1beta1/annotation_spec_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/automl_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/classification_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/column_spec_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/data_items_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/dataset_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/annotation_spec.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/classification.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/data_items.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/image.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/prediction_service.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/service.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/tables.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/text.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/image_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/model_evaluation_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/model_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/operations_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_services_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/service_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/service_services_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/table_spec_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/tables_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/text_pb.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/translation_pb.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes

#4899 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/orgpolicy/v1/doc/google/cloud/orgpolicy/v1/orgpolicy.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#4900 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/client.rb
  google-cloud-billing-v1/proto_docs/google/api/resource.rb
  google-cloud-billing-v1/proto_docs/google/cloud/billing/v1/cloud_catalog.rb
  google-cloud-billing-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#4901 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/proto_docs/google/api/resource.rb
  google-cloud-recommender-v1/proto_docs/google/cloud/recommender/v1/recommendation.rb
  google-cloud-recommender-v1/proto_docs/google/protobuf/struct.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes

#4902 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/resources.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/iam/v1/policy.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#4903 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/asset_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/notification_config.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/securitycenter_service.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/empty.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/finding_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/helpers.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/notification_config_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/notification_message_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/organization_settings_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/run_asset_discovery_response_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client_config.json
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_marks_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/securitycenter_service_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/securitycenter_service_services_pb.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/source_pb.rb
  google-cloud-security_center/synth.metadata
  google-cloud-security_center/test/google/cloud/security_center/v1/helpers_test.rb
  google-cloud-security_center/test/google/cloud/security_center/v1/security_center_client_test.rb
Labels: cla: yes

#4897 Bump Rake version to prepare Ruby 3 keyword arguments support
  Gemfile
  gcloud/Gemfile
  google-cloud-bigquery-data_transfer/Gemfile
  google-cloud-bigquery/Gemfile
  google-cloud-bigtable/Gemfile
  google-cloud-billing/Gemfile
  google-cloud-container/Gemfile
  google-cloud-core/Gemfile
  google-cloud-dataproc/Gemfile
  google-cloud-datastore/Gemfile
  google-cloud-debugger/Gemfile
  google-cloud-dialogflow/Gemfile
  google-cloud-dlp/Gemfile
  google-cloud-dns/Gemfile
  google-cloud-env/Gemfile
  google-cloud-error_reporting/Gemfile
  google-cloud-errors/Gemfile
  google-cloud-firestore/Gemfile
  google-cloud-language/Gemfile
  google-cloud-logging/Gemfile
  google-cloud-monitoring/Gemfile
  google-cloud-os_login/Gemfile
  google-cloud-pubsub/Gemfile
  google-cloud-recommender/Gemfile
  google-cloud-redis/Gemfile
  google-cloud-resource_manager/Gemfile
  google-cloud-secret_manager/Gemfile
  google-cloud-security_center/Gemfile
  google-cloud-spanner/Gemfile
  google-cloud-speech/Gemfile
  google-cloud-storage/Gemfile
  google-cloud-tasks/Gemfile
  google-cloud-text_to_speech/Gemfile
  google-cloud-trace/Gemfile
  google-cloud-translate/Gemfile
  google-cloud-video_intelligence/Gemfile
  google-cloud-vision/Gemfile
  google-cloud/Gemfile
  stackdriver-core/Gemfile
  stackdriver/Gemfile
Labels: cla: yes

#4904 Release google-cloud-automl 0.6.0
  google-cloud-automl/CHANGELOG.md
  google-cloud-automl/lib/google/cloud/automl/version.rb
Labels: autorelease: pending, cla: yes

#4905 Release google-cloud-secret_manager-v1beta1 0.2.3
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#4906 Release google-cloud-security_center 0.8.0
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes

#4911 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4917 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/cloud/videointelligence/v1beta2/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/cloud/videointelligence/v1p1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/cloud/videointelligence/v1p2beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#4921 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/client.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#4922 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes

#4923 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#4920 feat(pubsub): Rename Subscriber methods and alias deprecated originals
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/listen_test.rb
Labels: api: pubsub, cla: yes

#4924 docs: several fixes to docs of umbrella veneers for microgenerated clients
  google-cloud-billing/.gitignore
  google-cloud-billing/.repo-metadata.json
  google-cloud-billing/AUTHENTICATION.md
  google-cloud-billing/lib/google-cloud-billing.rb
  google-cloud-recommender/.gitignore
  google-cloud-recommender/.repo-metadata.json
  google-cloud-recommender/AUTHENTICATION.md
  google-cloud-recommender/lib/google-cloud-recommender.rb
  google-cloud-secret_manager/.gitignore
  google-cloud-secret_manager/.repo-metadata.json
  google-cloud-secret_manager/AUTHENTICATION.md
  google-cloud-secret_manager/lib/google-cloud-secret_manager.rb
Labels: cla: yes

#4932 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#4933 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl/v1beta1/automl_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_client.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes

#4934 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#4935 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4937 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client.rb
  google-cloud-container/synth.metadata
Labels: cla: yes

#4938 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes

#4939 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/autoscaling_policy_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4940 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#4941 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/synth.metadata
Labels: cla: yes

#4942 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4943 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#4944 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#4945 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/firestore_admin_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#4946 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/synth.metadata
Labels: cla: yes

#4947 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#4948 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/lib/google/cloud/language/v1/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client.rb
  google-cloud-language/synth.metadata
Labels: cla: yes

#4949 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/dashboards_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/service_monitoring_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4950 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client.rb
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#4951 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_client.rb
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes

#4952 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4953 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client.rb
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes

#4955 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/synth.metadata
Labels: cla: yes

#4956 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloud_scheduler_client.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4958 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1p1beta1/security_center_client.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#4959 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#4960 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#4961 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4962 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4963 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client.rb
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes

#4964 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#4965 [CHANGE ME] Re-generated google-cloud-translate to pick up changes in the API or client library generator.
  google-cloud-translate/lib/google/cloud/translate/v3/translation_service_client.rb
  google-cloud-translate/synth.metadata
Labels: cla: yes

#4966 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#4967 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#4968 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client.rb
  google-cloud-webrisk/synth.metadata
Labels: cla: yes

#4969 [CHANGE ME] Re-generated grafeas to pick up changes in the API or client library generator.
  grafeas/lib/grafeas/v1/grafeas_client.rb
  grafeas/synth.metadata
Labels: cla: yes

#5005 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/completion_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_services_pb.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4984 Release google-cloud-language 0.36.0
  google-cloud-language/CHANGELOG.md
  google-cloud-language/lib/google/cloud/language/version.rb
Labels: autorelease: pending, cla: yes

#4930 chore: add grpc service configs to microgen library synth scripts
  google-cloud-billing-v1/synth.py
  google-cloud-recommender-v1/synth.py
  google-cloud-secret_manager-v1beta1/synth.py
Labels: cla: yes

#4864 Release google-cloud-bigquery 1.20.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes

#4918 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/sink.rb
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/log_entry.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_metrics.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client_config.json
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client_config.json
  google-cloud-logging/lib/google/logging/v2/log_entry_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_config_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_config_services_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_pb.rb
  google-cloud-logging/support/doctest_helper.rb
  google-cloud-logging/synth.metadata
  google-cloud-logging/test/google/cloud/logging/sink_test.rb
  google-cloud-logging/test/helper.rb
Labels: cla: yes

#4925 Release google-cloud-pubsub 1.4.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#4971 Release google-cloud-asset 0.8.0
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes

#4973 Release grafeas 0.3.0
  grafeas/CHANGELOG.md
  grafeas/lib/grafeas/version.rb
Labels: autorelease: pending, cla: yes

#4977 Release google-cloud-redis 0.8.0
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes

#4978 Release google-cloud-dataproc 0.10.0
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes

#4979 Release google-cloud-scheduler 1.3.0
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/lib/google/cloud/scheduler/version.rb
Labels: autorelease: pending, cla: yes

#4980 Release google-cloud-kms 1.5.0
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes

#4981 Release google-cloud-container 0.10.0
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes

#4982 Release google-cloud-recaptcha_enterprise 0.5.0
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes

#4983 Release google-cloud-security_center 0.9.0
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes

#4985 Release google-cloud-bigquery-data_transfer 0.7.0
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes

#4986 Release google-cloud-error_reporting 0.35.0
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes

#4987 Release google-cloud-os_login 0.6.0
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes

#4988 Release google-cloud-dlp 0.14.0
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes

#4989 Release google-cloud-webrisk 0.5.0
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes

#4990 Release google-cloud-phishing_protection 0.4.0
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes

#4991 Release google-cloud-dialogflow 0.15.0
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes

#4992 Release google-cloud-monitoring 0.36.0
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes

#4993 Release google-cloud-trace 0.38.0
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes

#4994 Release google-cloud-text_to_speech 0.6.0
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/version.rb
Labels: autorelease: pending, cla: yes

#4995 Release google-cloud-automl 0.7.0
  google-cloud-automl/CHANGELOG.md
  google-cloud-automl/lib/google/cloud/automl/version.rb
Labels: autorelease: pending, cla: yes

#4996 Release google-cloud-debugger 0.36.0
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#4997 Release google-cloud-translate 2.2.0
  google-cloud-translate/CHANGELOG.md
  google-cloud-translate/lib/google/cloud/translate/version.rb
Labels: autorelease: pending, cla: yes

#4998 Release google-cloud-datastore 1.8.0
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes

#4999 Release google-cloud-vision 0.38.0
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: autorelease: pending, cla: yes

#5000 Release google-cloud-speech 0.41.0
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes

#5002 Release google-cloud-bigtable 1.2.0
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#5003 Release google-cloud-firestore 1.4.0
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#4972 Release google-cloud-talent 0.9.0
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes

#4976 Release google-cloud-tasks 1.5.0
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes

#5001 Release google-cloud-video_intelligence 2.1.0
  google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/version.rb
Labels: autorelease: pending, cla: yes

#4884 Support Ruby 2.8 keyword arguments for google-cloud-storage
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/file/list.rb
  google-cloud-storage/lib/google/cloud/storage/policy/binding.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/lib/google/cloud/storage/service.rb
  google-cloud-storage/test/google/cloud/storage/bucket_encryption_test.rb
  google-cloud-storage/test/google/cloud/storage/bucket_test.rb
  google-cloud-storage/test/google/cloud/storage/lazy/bucket_test.rb
  google-cloud-storage/test/google/cloud/storage/project_test.rb
Labels: api: storage, cla: yes

#5006 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/google-cloud-billing-v1.gemspec
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/client.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#5009 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/google-cloud-recommender-v1.gemspec
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes

#5010 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/google-cloud-secret_manager-v1beta1.gemspec
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#5007 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#5008 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client_config.json
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4974 feat: initial microsynth of secret_manager v1
  .kokoro/continuous/linux/secret_manager-v1.cfg
  .kokoro/continuous/osx/secret_manager-v1.cfg
  .kokoro/continuous/windows/secret_manager-v1.cfg
  .kokoro/nightly/linux/secret_manager-v1.cfg
  .kokoro/nightly/osx/secret_manager-v1.cfg
  .kokoro/nightly/windows/secret_manager-v1.cfg
  .kokoro/release/secret_manager-v1.cfg
  Gemfile
  google-cloud-secret_manager-v1/.gitignore
  google-cloud-secret_manager-v1/.repo-metadata.json
  google-cloud-secret_manager-v1/.rubocop.yml
  google-cloud-secret_manager-v1/.yardopts
  google-cloud-secret_manager-v1/AUTHENTICATION.md
  google-cloud-secret_manager-v1/CHANGELOG.md
  google-cloud-secret_manager-v1/Gemfile
  google-cloud-secret_manager-v1/LICENSE.md
  google-cloud-secret_manager-v1/README.md
  google-cloud-secret_manager-v1/Rakefile
  google-cloud-secret_manager-v1/google-cloud-secret_manager-v1.gemspec
  google-cloud-secret_manager-v1/lib/google-cloud-secret_manager-v1.rb
  google-cloud-secret_manager-v1/lib/google/cloud/common_resources_pb.rb
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1.rb
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service.rb
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service/credentials.rb
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service/paths.rb
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/version.rb
  google-cloud-secret_manager-v1/lib/google/cloud/secretmanager/v1/resources_pb.rb
  google-cloud-secret_manager-v1/lib/google/cloud/secretmanager/v1/service_pb.rb
  google-cloud-secret_manager-v1/lib/google/cloud/secretmanager/v1/service_services_pb.rb
  google-cloud-secret_manager-v1/proto_docs/README.md
  google-cloud-secret_manager-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-secret_manager-v1/proto_docs/google/api/resource.rb
  google-cloud-secret_manager-v1/proto_docs/google/cloud/secretmanager/v1/resources.rb
  google-cloud-secret_manager-v1/proto_docs/google/cloud/secretmanager/v1/service.rb
  google-cloud-secret_manager-v1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-secret_manager-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-secret_manager-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-secret_manager-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-secret_manager-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-secret_manager-v1/synth.metadata
  google-cloud-secret_manager-v1/synth.py
  google-cloud-secret_manager-v1/test/google/cloud/secret_manager/v1/secret_manager_service_test.rb
Labels: cla: yes

#4975 feat: initial microsynth of service_directory v1beta1
  .kokoro/continuous/linux/service_directory-v1beta1.cfg
  .kokoro/continuous/osx/service_directory-v1beta1.cfg
  .kokoro/continuous/windows/service_directory-v1beta1.cfg
  .kokoro/nightly/linux/service_directory-v1beta1.cfg
  .kokoro/nightly/osx/service_directory-v1beta1.cfg
  .kokoro/nightly/windows/service_directory-v1beta1.cfg
  .kokoro/release/service_directory-v1beta1.cfg
  Gemfile
  google-cloud-service_directory-v1beta1/.gitignore
  google-cloud-service_directory-v1beta1/.repo-metadata.json
  google-cloud-service_directory-v1beta1/.rubocop.yml
  google-cloud-service_directory-v1beta1/.yardopts
  google-cloud-service_directory-v1beta1/AUTHENTICATION.md
  google-cloud-service_directory-v1beta1/CHANGELOG.md
  google-cloud-service_directory-v1beta1/Gemfile
  google-cloud-service_directory-v1beta1/LICENSE.md
  google-cloud-service_directory-v1beta1/README.md
  google-cloud-service_directory-v1beta1/Rakefile
  google-cloud-service_directory-v1beta1/google-cloud-service_directory-v1beta1.gemspec
  google-cloud-service_directory-v1beta1/lib/google-cloud-service_directory-v1beta1.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/common_resources_pb.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/lookup_service.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/lookup_service/client.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/lookup_service/credentials.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/lookup_service/paths.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service/client.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service/credentials.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service/paths.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/version.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/servicedirectory/v1beta1/endpoint_pb.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/servicedirectory/v1beta1/lookup_service_pb.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/servicedirectory/v1beta1/lookup_service_services_pb.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/servicedirectory/v1beta1/namespace_pb.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/servicedirectory/v1beta1/registration_service_pb.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/servicedirectory/v1beta1/registration_service_services_pb.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/servicedirectory/v1beta1/service_pb.rb
  google-cloud-service_directory-v1beta1/proto_docs/README.md
  google-cloud-service_directory-v1beta1/proto_docs/google/api/field_behavior.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/endpoint.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/lookup_service.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/namespace.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/registration_service.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/service.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/iam/v1/policy.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/protobuf/empty.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-service_directory-v1beta1/synth.metadata
  google-cloud-service_directory-v1beta1/synth.py
  google-cloud-service_directory-v1beta1/test/google/cloud/service_directory/v1beta1/lookup_service_test.rb
  google-cloud-service_directory-v1beta1/test/google/cloud/service_directory/v1beta1/registration_service_test.rb
Labels: cla: yes

#5011 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/protobuf/field_mask.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/protobuf/timestamp.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/spanner/admin/database/v1/backup.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/spanner/admin/database/v1/spanner_database_admin.rb
  google-cloud-spanner/lib/google/spanner/admin/database/v1/backup_pb.rb
  google-cloud-spanner/lib/google/spanner/admin/database/v1/common_pb.rb
  google-cloud-spanner/lib/google/spanner/admin/database/v1/spanner_database_admin_pb.rb
  google-cloud-spanner/lib/google/spanner/admin/database/v1/spanner_database_admin_services_pb.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/admin/database/v1/database_admin_client_test.rb
Labels: cla: yes

#5012 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/helpers.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client_config.json
  google-cloud-talent/synth.metadata
  google-cloud-talent/test/google/cloud/talent/v4beta1/application_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/company_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/completion_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/event_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/helpers_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/job_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/profile_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/tenant_service_client_test.rb
Labels: cla: yes

#4907 feat(spanner): support query options
  google-cloud-spanner/acceptance/spanner/batch_client/execute_partition_test.rb
  google-cloud-spanner/acceptance/spanner/client/execute_test.rb
  google-cloud-spanner/acceptance/spanner/client/pdml_test.rb
  google-cloud-spanner/acceptance/spanner/client/snapshot_test.rb
  google-cloud-spanner/acceptance/spanner/client/transaction_test.rb
  google-cloud-spanner/lib/google-cloud-spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/batch_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/batch_snapshot.rb
  google-cloud-spanner/lib/google/cloud/spanner/client.rb
  google-cloud-spanner/lib/google/cloud/spanner/project.rb
  google-cloud-spanner/lib/google/cloud/spanner/results.rb
  google-cloud-spanner/lib/google/cloud/spanner/service.rb
  google-cloud-spanner/lib/google/cloud/spanner/session.rb
  google-cloud-spanner/lib/google/cloud/spanner/snapshot.rb
  google-cloud-spanner/lib/google/cloud/spanner/transaction.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/execute_partition_test.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/batch_snapshot/partition_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/execute_partition_update_test.rb
  google-cloud-spanner/test/google/cloud/spanner/client/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/session/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/snapshot/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/execute_query_test.rb
  google-cloud-spanner/test/google/cloud/spanner/transaction/execute_update_test.rb
  google-cloud-spanner/test/google/cloud/spanner_test.rb
  google-cloud-spanner/test/helper.rb
Labels: api: spanner, cla: yes

#5023 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/.gitignore
  google-cloud-secret_manager-v1beta1/AUTHENTICATION.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/api/resource.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/resources.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/iam/v1/policy.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/empty.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#5022 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/.gitignore
  google-cloud-recommender-v1/AUTHENTICATION.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/proto_docs/google/api/resource.rb
  google-cloud-recommender-v1/proto_docs/google/cloud/recommender/v1/recommendation.rb
  google-cloud-recommender-v1/proto_docs/google/cloud/recommender/v1/recommender_service.rb
  google-cloud-recommender-v1/proto_docs/google/protobuf/duration.rb
  google-cloud-recommender-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes

#5021 [CHANGE ME] Re-generated google-cloud-language-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-language-v1beta2/.gitignore
  google-cloud-language-v1beta2/AUTHENTICATION.md
  google-cloud-language-v1beta2/proto_docs/google/api/resource.rb
  google-cloud-language-v1beta2/proto_docs/google/protobuf/timestamp.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes

#5020 [CHANGE ME] Re-generated google-cloud-language-v1 to pick up changes in the API or client library generator.
  google-cloud-language-v1/.gitignore
  google-cloud-language-v1/AUTHENTICATION.md
  google-cloud-language-v1/proto_docs/google/api/resource.rb
  google-cloud-language-v1/synth.metadata
Labels: cla: yes

#5019 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/.gitignore
  google-cloud-billing-v1/AUTHENTICATION.md
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/proto_docs/google/api/resource.rb
  google-cloud-billing-v1/proto_docs/google/cloud/billing/v1/cloud_billing.rb
  google-cloud-billing-v1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-billing-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-billing-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-billing-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#5018 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/orgpolicy/v1/doc/google/cloud/orgpolicy/v1/orgpolicy.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#5028 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/orgpolicy/v1/doc/google/cloud/orgpolicy/v1/orgpolicy.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#5030 [CHANGE ME] Re-generated google-cloud-service_directory-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service/client.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/registration_service.rb
  google-cloud-service_directory-v1beta1/synth.metadata
Labels: cla: yes

#5014 feat: create wrapper library for service_directory
  .kokoro/continuous/linux/service_directory.cfg
  .kokoro/continuous/osx/service_directory.cfg
  .kokoro/continuous/windows/service_directory.cfg
  .kokoro/nightly/linux/service_directory.cfg
  .kokoro/nightly/osx/service_directory.cfg
  .kokoro/nightly/windows/service_directory.cfg
  .kokoro/release/service_directory.cfg
  Gemfile
  google-cloud-service_directory/.gitignore
  google-cloud-service_directory/.repo-metadata.json
  google-cloud-service_directory/.rubocop.yml
  google-cloud-service_directory/.yardopts
  google-cloud-service_directory/AUTHENTICATION.md
  google-cloud-service_directory/CHANGELOG.md
  google-cloud-service_directory/Gemfile
  google-cloud-service_directory/LICENSE
  google-cloud-service_directory/README.md
  google-cloud-service_directory/Rakefile
  google-cloud-service_directory/google-cloud-service_directory.gemspec
  google-cloud-service_directory/lib/google-cloud-service_directory.rb
  google-cloud-service_directory/lib/google/cloud/service_directory.rb
  google-cloud-service_directory/lib/google/cloud/service_directory/version.rb
  google-cloud-service_directory/test/google/cloud/service_directory/client_test.rb
  google-cloud-service_directory/test/google/cloud/service_directory/version_test.rb
  google-cloud-service_directory/test/helper.rb
Labels: cla: yes

#5027 chore: update osx template to match current script
  .kokoro/templates/osx.sh.erb
Labels: cla: yes

#4858 feat: [IOT][MicroSynth] Add IOT client
  Gemfile
  google-cloud-iot-v1/.gitignore
  google-cloud-iot-v1/.repo-metadata.json
  google-cloud-iot-v1/.rubocop.yml
  google-cloud-iot-v1/.yardopts
  google-cloud-iot-v1/AUTHENTICATION.md
  google-cloud-iot-v1/CHANGELOG.md
  google-cloud-iot-v1/Gemfile
  google-cloud-iot-v1/LICENSE.md
  google-cloud-iot-v1/README.md
  google-cloud-iot-v1/Rakefile
  google-cloud-iot-v1/google-cloud-iot-v1.gemspec
  google-cloud-iot-v1/lib/google-cloud-iot-v1.rb
  google-cloud-iot-v1/lib/google/cloud/common_resources_pb.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager/client.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager/credentials.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager/paths.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager_pb.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager_services_pb.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1/resources_pb.rb
  google-cloud-iot-v1/lib/google/cloud/iot/v1/version.rb
  google-cloud-iot-v1/proto_docs/README.md
  google-cloud-iot-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-iot-v1/proto_docs/google/api/resource.rb
  google-cloud-iot-v1/proto_docs/google/cloud/iot/v1/device_manager.rb
  google-cloud-iot-v1/proto_docs/google/cloud/iot/v1/resources.rb
  google-cloud-iot-v1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-iot-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-iot-v1/proto_docs/google/protobuf/any.rb
  google-cloud-iot-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-iot-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-iot-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-iot-v1/proto_docs/google/rpc/status.rb
  google-cloud-iot-v1/synth.metadata
  google-cloud-iot-v1/synth.py
  google-cloud-iot-v1/test/google/cloud/iot/v1/device_manager_test.rb
Labels: cla: yes

#4832 feat: [AccessApproval][MicroSynth] Add AccessApproval client
  Gemfile
  google-cloud-access_approval-v1/.gitignore
  google-cloud-access_approval-v1/.repo-metadata.json
  google-cloud-access_approval-v1/.rubocop.yml
  google-cloud-access_approval-v1/.yardopts
  google-cloud-access_approval-v1/AUTHENTICATION.md
  google-cloud-access_approval-v1/CHANGELOG.md
  google-cloud-access_approval-v1/Gemfile
  google-cloud-access_approval-v1/LICENSE.md
  google-cloud-access_approval-v1/README.md
  google-cloud-access_approval-v1/Rakefile
  google-cloud-access_approval-v1/google-cloud-access_approval-v1.gemspec
  google-cloud-access_approval-v1/lib/google-cloud-access_approval-v1.rb
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1.rb
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/access_approval.rb
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/access_approval/client.rb
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/access_approval/credentials.rb
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/version.rb
  google-cloud-access_approval-v1/lib/google/cloud/accessapproval/v1/accessapproval_pb.rb
  google-cloud-access_approval-v1/lib/google/cloud/accessapproval/v1/accessapproval_services_pb.rb
  google-cloud-access_approval-v1/lib/google/cloud/common_resources_pb.rb
  google-cloud-access_approval-v1/proto_docs/README.md
  google-cloud-access_approval-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-access_approval-v1/proto_docs/google/api/resource.rb
  google-cloud-access_approval-v1/proto_docs/google/cloud/accessapproval/v1/accessapproval.rb
  google-cloud-access_approval-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-access_approval-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-access_approval-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-access_approval-v1/synth.metadata
  google-cloud-access_approval-v1/synth.py
  google-cloud-access_approval-v1/test/google/cloud/access_approval/v1/access_approval_test.rb
Labels: cla: yes

#5017 Release google-cloud-spanner 1.15.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes

#5024 add language samples
  google-cloud-language/.rubocop.yml
  google-cloud-language/Rakefile
  google-cloud-language/samples/Gemfile
  google-cloud-language/samples/README.md
  google-cloud-language/samples/Rakefile
  google-cloud-language/samples/acceptance/helper.rb
  google-cloud-language/samples/acceptance/language_samples_test.rb
  google-cloud-language/samples/acceptance/quickstart_test.rb
  google-cloud-language/samples/language_samples.rb
  google-cloud-language/samples/quickstart.rb
Labels: cla: yes

#5013 Release google-cloud-logging 1.10.0
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes

#5015 Release google-cloud-talent 0.10.0
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes

#5026 Release google-cloud-asset 0.8.1
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes

#5036 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client_config.json
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_services_pb.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/storage_pb.rb
  google-cloud-dlp/synth.metadata
  google-cloud-dlp/test/google/cloud/dlp/v2/dlp_service_client_test.rb
Labels: cla: yes

#5042 [CHANGE ME] Re-generated google-cloud-access_approval-v1 to pick up changes in the API or client library generator.
  google-cloud-access_approval-v1/google-cloud-access_approval-v1.gemspec
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/access_approval/client.rb
  google-cloud-access_approval-v1/synth.metadata
Labels: cla: yes

#5052 [CHANGE ME] Re-generated google-cloud-service_directory-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1beta1/google-cloud-service_directory-v1beta1.gemspec
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/lookup_service/client.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service/client.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/endpoint.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/lookup_service.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/namespace.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/registration_service.rb
  google-cloud-service_directory-v1beta1/proto_docs/google/cloud/servicedirectory/v1beta1/service.rb
  google-cloud-service_directory-v1beta1/synth.metadata
Labels: cla: yes

#5051 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/google-cloud-secret_manager-v1beta1.gemspec
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/resources.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/cloud/secrets/v1beta1/service.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#5050 [CHANGE ME] Re-generated google-cloud-secret_manager-v1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1/google-cloud-secret_manager-v1.gemspec
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1/proto_docs/google/cloud/secretmanager/v1/resources.rb
  google-cloud-secret_manager-v1/proto_docs/google/cloud/secretmanager/v1/service.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes

#5049 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/google-cloud-recommender-v1.gemspec
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes

#5047 [CHANGE ME] Re-generated google-cloud-language-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-language-v1beta2/google-cloud-language-v1beta2.gemspec
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
  google-cloud-language-v1beta2/proto_docs/google/cloud/language/v1beta2/language_service.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes

#5046 [CHANGE ME] Re-generated google-cloud-language-v1 to pick up changes in the API or client library generator.
  google-cloud-language-v1/google-cloud-language-v1.gemspec
  google-cloud-language-v1/lib/google/cloud/language/v1/language_service/client.rb
  google-cloud-language-v1/proto_docs/google/cloud/language/v1/language_service.rb
  google-cloud-language-v1/synth.metadata
Labels: cla: yes

#5045 [CHANGE ME] Re-generated google-cloud-iot-v1 to pick up changes in the API or client library generator.
  google-cloud-iot-v1/google-cloud-iot-v1.gemspec
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager/client.rb
  google-cloud-iot-v1/proto_docs/google/rpc/status.rb
  google-cloud-iot-v1/synth.metadata
Labels: cla: yes

#5044 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/google-cloud-dialogflow-v2.gemspec
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/contexts/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/sessions/client.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/context.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/session_entity_type.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/webhook.rb
  google-cloud-dialogflow-v2/proto_docs/google/longrunning/operations.rb
  google-cloud-dialogflow-v2/proto_docs/google/rpc/status.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes

#5043 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/google-cloud-billing-v1.gemspec
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/client.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#5048 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client_config.json
  google-cloud-logging/lib/google/logging/v2/logging_config_services_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_metrics_services_pb.rb
  google-cloud-logging/lib/google/logging/v2/logging_services_pb.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#5041 add analyze_entity_sentiment snippets
  google-cloud-language/samples/acceptance/language_samples_test.rb
  google-cloud-language/samples/language_samples.rb
Labels: cla: yes

#5039 Release google-cloud-dialogflow-v2 0.1.0
  google-cloud-dialogflow-v2/CHANGELOG.md
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/version.rb
Labels: autorelease: pending, cla: yes

#5038 Release google-cloud-language-v1beta2 0.1.0
  google-cloud-language-v1beta2/CHANGELOG.md
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#5037 Release google-cloud-language-v1 0.1.0
  google-cloud-language-v1/CHANGELOG.md
  google-cloud-language-v1/lib/google/cloud/language/v1/version.rb
Labels: autorelease: pending, cla: yes

#5035 Release google-cloud-service_directory-v1beta1 0.1.0
  google-cloud-service_directory-v1beta1/CHANGELOG.md
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5034 Release google-cloud-secret_manager-v1 0.1.0
  google-cloud-secret_manager-v1/CHANGELOG.md
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/version.rb
Labels: autorelease: pending, cla: yes

#5040 Release google-cloud-dlp 0.15.0
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes

#5054 Release google-cloud-secret_manager-v1beta1 0.3.0
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#5058 Release google-cloud-billing-v1 0.2.0
  google-cloud-billing-v1/CHANGELOG.md
  google-cloud-billing-v1/lib/google/cloud/billing/v1/version.rb
Labels: autorelease: pending, cla: yes

#5059 Release google-cloud-recommender-v1 0.2.0
  google-cloud-recommender-v1/CHANGELOG.md
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/version.rb
Labels: autorelease: pending, cla: yes

#5029 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4795 feat: initial microsynth of bigquery-storage-v1
  Gemfile
  google-cloud-bigquery-storage-v1/.gitignore
  google-cloud-bigquery-storage-v1/.repo-metadata.json
  google-cloud-bigquery-storage-v1/.rubocop.yml
  google-cloud-bigquery-storage-v1/.yardopts
  google-cloud-bigquery-storage-v1/AUTHENTICATION.md
  google-cloud-bigquery-storage-v1/CHANGELOG.md
  google-cloud-bigquery-storage-v1/Gemfile
  google-cloud-bigquery-storage-v1/LICENSE.md
  google-cloud-bigquery-storage-v1/README.md
  google-cloud-bigquery-storage-v1/Rakefile
  google-cloud-bigquery-storage-v1/google-cloud-bigquery-storage-v1.gemspec
  google-cloud-bigquery-storage-v1/lib/google-cloud-bigquery-storage-v1.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/arrow_pb.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/avro_pb.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/big_query_read.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/big_query_read/client.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/big_query_read/credentials.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/big_query_read/paths.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/storage_pb.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/storage_services_pb.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/stream_pb.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/version.rb
  google-cloud-bigquery-storage-v1/lib/google/cloud/common_resources_pb.rb
  google-cloud-bigquery-storage-v1/proto_docs/README.md
  google-cloud-bigquery-storage-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-bigquery-storage-v1/proto_docs/google/api/resource.rb
  google-cloud-bigquery-storage-v1/proto_docs/google/cloud/bigquery/storage/v1/arrow.rb
  google-cloud-bigquery-storage-v1/proto_docs/google/cloud/bigquery/storage/v1/avro.rb
  google-cloud-bigquery-storage-v1/proto_docs/google/cloud/bigquery/storage/v1/storage.rb
  google-cloud-bigquery-storage-v1/proto_docs/google/cloud/bigquery/storage/v1/stream.rb
  google-cloud-bigquery-storage-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-bigquery-storage-v1/synth.metadata
  google-cloud-bigquery-storage-v1/synth.py
  google-cloud-bigquery-storage-v1/test/google/cloud/bigquery/storage/v1/big_query_read_test.rb
Labels: cla: yes

#5060 chore: add kokoro configuration for access_approval-v1, bigquery-stor…
  .kokoro/continuous/linux/access_approval-v1.cfg
  .kokoro/continuous/linux/bigquery-storage-v1.cfg
  .kokoro/continuous/linux/iot-v1.cfg
  .kokoro/continuous/osx/access_approval-v1.cfg
  .kokoro/continuous/osx/bigquery-storage-v1.cfg
  .kokoro/continuous/osx/iot-v1.cfg
  .kokoro/continuous/windows/access_approval-v1.cfg
  .kokoro/continuous/windows/bigquery-storage-v1.cfg
  .kokoro/continuous/windows/iot-v1.cfg
  .kokoro/nightly/linux/access_approval-v1.cfg
  .kokoro/nightly/linux/bigquery-storage-v1.cfg
  .kokoro/nightly/linux/iot-v1.cfg
  .kokoro/nightly/osx/access_approval-v1.cfg
  .kokoro/nightly/osx/bigquery-storage-v1.cfg
  .kokoro/nightly/osx/iot-v1.cfg
  .kokoro/nightly/windows/access_approval-v1.cfg
  .kokoro/nightly/windows/bigquery-storage-v1.cfg
  .kokoro/nightly/windows/iot-v1.cfg
  .kokoro/release/access_approval-v1.cfg
  .kokoro/release/bigquery-storage-v1.cfg
  .kokoro/release/iot-v1.cfg
Labels: cla: yes, type: process

#5016 feat(secret_manager): use v1 of the service by default
  google-cloud-secret_manager/AUTHENTICATION.md
  google-cloud-secret_manager/Gemfile
  google-cloud-secret_manager/README.md
  google-cloud-secret_manager/google-cloud-secret_manager.gemspec
  google-cloud-secret_manager/lib/google/cloud/secret_manager.rb
  google-cloud-secret_manager/test/google/cloud/secret_manager/client_test.rb
Labels: cla: yes
