Repository googleapis/google-cloud-ruby, pull requests merged in 2020-01, with the labels that each got.

#4543 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/firestore/v1/firestore_services_pb.rb
  google-cloud-firestore/lib/google/firestore/v1/write_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#4319 docs(storage): Add ARCHIVE storage class
  google-cloud-storage/acceptance/storage/file_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/bucket/lifecycle.rb
  google-cloud-storage/lib/google/cloud/storage/convert.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
  google-cloud-storage/test/google/cloud/storage/file_update_test.rb
Labels: api: storage, cla: yes, type: docs

#4551 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/write.rb
  google-cloud-firestore/lib/google/firestore/v1/write_pb.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#4555 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms.rb
  google-cloud-kms/lib/google/cloud/kms/v1.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/resources.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/service.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/lib/google/cloud/kms/v1/resources_pb.rb
  google-cloud-kms/lib/google/cloud/kms/v1/service_pb.rb
  google-cloud-kms/lib/google/cloud/kms/v1/service_services_pb.rb
  google-cloud-kms/synth.metadata
Labels: cla: yes

#4559 chore: Add kokoro configs for secret manager
  .kokoro/continuous/linux/secret_manager-v1beta1.cfg
  .kokoro/continuous/linux/secret_manager.cfg
  .kokoro/continuous/osx/secret_manager-v1beta1.cfg
  .kokoro/continuous/osx/secret_manager.cfg
  .kokoro/continuous/windows/secret_manager-v1beta1.cfg
  .kokoro/continuous/windows/secret_manager.cfg
  .kokoro/nightly/linux/secret_manager-v1beta1.cfg
  .kokoro/nightly/linux/secret_manager.cfg
  .kokoro/nightly/osx/secret_manager-v1beta1.cfg
  .kokoro/nightly/osx/secret_manager.cfg
  .kokoro/nightly/windows/secret_manager-v1beta1.cfg
  .kokoro/nightly/windows/secret_manager.cfg
  .kokoro/release/secret_manager-v1beta1.cfg
  .kokoro/release/secret_manager.cfg
Labels: cla: yes

#4560 Release google-cloud-storage 1.25.1
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes

#4558 Release google-cloud-kms 1.4.0
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4546 feat(spanner): Add the support for SPANNER_EMULATOR_HOST.
  google-cloud-spanner/lib/google-cloud-spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner.rb
  google-cloud-spanner/test/google/cloud/spanner_test.rb
Labels: cla: yes

#4552 test(spanner) - Add benchwrapper
  google-cloud-spanner/benchmark/benchwrapper/README.md
  google-cloud-spanner/benchmark/benchwrapper/benchwrapper.rb
  google-cloud-spanner/benchmark/benchwrapper/benchwrapper_test_client.rb
  google-cloud-spanner/benchmark/benchwrapper/spanner.proto
  google-cloud-spanner/benchmark/benchwrapper/spanner_pb.rb
  google-cloud-spanner/benchmark/benchwrapper/spanner_services_pb.rb
  google-cloud-spanner/google-cloud-spanner.gemspec
Labels: cla: yes

#4561 fix(firestore): Use client instead of service in DocumentReference::List
  google-cloud-firestore/acceptance/firestore/collection_test.rb
  google-cloud-firestore/lib/google/cloud/firestore/client.rb
  google-cloud-firestore/lib/google/cloud/firestore/document_reference/list.rb
Labels: api: firestore, cla: yes

#4563 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/README.md
  google-cloud-os_login/lib/google/cloud/os_login.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1.rb
  google-cloud-os_login/synth.metadata
Labels: cla: yes

#4562 Release google-cloud-spanner 1.13.0
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4480 Allow row inserts to skip insert_id generation
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/service.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table/async_inserter.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_insert_async_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_insert_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_insert_test.rb
Labels: api: bigquery, cla: yes, type: feature request

#4564 Release google-cloud-firestore 1.2.3
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#4413 Update AsyncPublisher configuration defaults
  google-cloud-pubsub/lib/google/cloud/pubsub/async_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/project.rb
Labels: api: pubsub, cla: yes

#4414 Add Subscriber inventory settings
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/inventory.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber/stream.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber/inventory_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscriber_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/subscription/listen_test.rb
Labels: api: pubsub, cla: yes

#4566 Release google-cloud-os_login 0.5.2
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4565 Release google-cloud-pubsub 1.2.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4572 chore(errors): Fix copyright date for new library
  google-cloud-errors/lib/google-cloud-errors.rb
  google-cloud-errors/lib/google/cloud/errors.rb
  google-cloud-errors/lib/google/cloud/errors/version.rb
  google-cloud-errors/test/google/cloud/errors/error_cause_test.rb
  google-cloud-errors/test/google/cloud/errors/gapi_errors_test.rb
  google-cloud-errors/test/google/cloud/errors/grpc_errors_test.rb
  google-cloud-errors/test/google/cloud/errors/wrapped_gapi_test.rb
  google-cloud-errors/test/google/cloud/errors/wrapped_gax_test.rb
  google-cloud-errors/test/google/cloud/errors/wrapped_grpc_test.rb
  google-cloud-errors/test/helper.rb
Labels: cla: yes

#4571 Release google-cloud-errors 1.0.0
  google-cloud-errors/CHANGELOG.md
Labels: autorelease: pending, cla: yes

#4568 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client_config.json
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4573 Release google-cloud-core 1.5.0
  google-cloud-core/CHANGELOG.md
  google-cloud-core/lib/google/cloud/core/version.rb
Labels: autorelease: pending, cla: yes

#4576 Release google-cloud-secret_manager-v1beta1 0.1.0
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
  google-cloud-secret_manager/google-cloud-secret_manager.gemspec
  google-cloud-secret_manager/lib/google/cloud/secret_manager/version.rb
Labels: autorelease: pending, cla: yes

#4577 Release google-cloud-secret_manager 0.1.0
  google-cloud-secret_manager/CHANGELOG.md
  google-cloud-secret_manager/lib/google/cloud/secret_manager/version.rb
Labels: autorelease: pending, cla: yes

#4569 [CHANGE ME] Re-generated grafeas to pick up changes in the API or client library generator.
  grafeas/lib/grafeas/v1/common_pb.rb
  grafeas/lib/grafeas/v1/discovery_pb.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/common.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/discovery.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/grafeas.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/upgrade.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/vulnerability.rb
  grafeas/lib/grafeas/v1/grafeas_pb.rb
  grafeas/lib/grafeas/v1/upgrade_pb.rb
  grafeas/lib/grafeas/v1/vulnerability_pb.rb
  grafeas/synth.metadata
Labels: cla: yes

#4567 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client_config.json
  google-cloud-container_analysis/lib/google/devtools/containeranalysis/v1/containeranalysis_pb.rb
  google-cloud-container_analysis/synth.metadata
  google-cloud-container_analysis/test/google/cloud/container_analysis/v1/container_analysis_client_test.rb
Labels: cla: yes

#4583 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client_config.json
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client_config.json
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4579 Release google-cloud-container_analysis 0.5.0
  google-cloud-container_analysis/CHANGELOG.md
  google-cloud-container_analysis/lib/google/cloud/container_analysis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4581 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client_config.json
  google-cloud-container_analysis/synth.metadata
  google-cloud-container_analysis/test/google/cloud/container_analysis/v1/container_analysis_client_test.rb
Labels: cla: yes

#4580 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/bigtable/v2/bigtable.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4582 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/privacy/dlp/v2/dlp_pb.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#4574 Release google-cloud-tasks 1.3.3
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4578 Release grafeas 0.2.0
  grafeas/CHANGELOG.md
  grafeas/lib/grafeas/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4616 Release google-cloud-bigtable 1.0.1
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4617 Release google-cloud-dlp 0.13.1
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4618 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset.rb
  google-cloud-asset/lib/google/cloud/asset/v1.rb
  google-cloud-asset/lib/google/cloud/asset/v1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1/credentials.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/cloud/asset/v1/asset_service.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/cloud/asset/v1/assets.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/longrunning/operations.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/protobuf/any.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/protobuf/empty.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/protobuf/field_mask.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/protobuf/struct.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/protobuf/timestamp.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/rpc/status.rb
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/type/expr.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/credentials.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/asset_service.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/assets.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/iam/v1/policy.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/any.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/struct.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/rpc/status.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/type/expr.rb
  google-cloud-asset/synth.metadata
  google-cloud-asset/test/google/cloud/asset/v1/asset_service_client_test.rb
  google-cloud-asset/test/google/cloud/asset/v1beta1/asset_service_client_test.rb
Labels: cla: yes

#4619 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/automl_client.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/credentials.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/annotation_payload.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/annotation_spec.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/classification.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/column_spec.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/data_items.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/data_stats.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/data_types.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/dataset.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/detection.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/geometry.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/image.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/io.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/model.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/model_evaluation.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/prediction_service.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/ranges.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/regression.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/service.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/table_spec.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/tables.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/temporal.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/text.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/text_extraction.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/text_segment.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/text_sentiment.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/translation.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/cloud/automl/v1beta1/video.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/protobuf/any.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/protobuf/duration.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/protobuf/struct.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/rpc/status.rb
  google-cloud-automl/lib/google/cloud/automl/v1beta1/prediction_service_client.rb
  google-cloud-automl/synth.metadata
  google-cloud-automl/test/google/cloud/automl/v1beta1/automl_client_test.rb
  google-cloud-automl/test/google/cloud/automl/v1beta1/prediction_service_client_test.rb
Labels: cla: yes

#4620 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/acceptance/google/cloud/bigquery/data_transfer/v1/data_transfer_service_smoke_test.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/credentials.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/datatransfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/cloud/bigquery/datatransfer/v1/transfer.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/any.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/duration.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/empty.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/field_mask.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/struct.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/protobuf/timestamp.rb
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/rpc/status.rb
  google-cloud-bigquery-data_transfer/synth.metadata
  google-cloud-bigquery-data_transfer/test/google/cloud/bigquery/data_transfer/v1/data_transfer_service_client_test.rb
Labels: cla: yes

#4622 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/acceptance/google/cloud/container/v1/cluster_manager_smoke_test.rb
  google-cloud-container/acceptance/google/cloud/container/v1beta1/cluster_manager_smoke_test.rb
  google-cloud-container/lib/google/cloud/container.rb
  google-cloud-container/lib/google/cloud/container/v1.rb
  google-cloud-container/lib/google/cloud/container/v1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1/credentials.rb
  google-cloud-container/lib/google/cloud/container/v1/doc/google/container/v1/cluster_service.rb
  google-cloud-container/lib/google/cloud/container/v1/doc/google/protobuf/empty.rb
  google-cloud-container/lib/google/cloud/container/v1/doc/google/protobuf/timestamp.rb
  google-cloud-container/lib/google/cloud/container/v1beta1.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/cluster_manager_client.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/credentials.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/doc/google/container/v1beta1/cluster_service.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/doc/google/protobuf/empty.rb
  google-cloud-container/lib/google/cloud/container/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-container/synth.metadata
  google-cloud-container/test/google/cloud/container/v1/cluster_manager_client_test.rb
  google-cloud-container/test/google/cloud/container/v1beta1/cluster_manager_client_test.rb
Labels: cla: yes

#4623 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/lib/google/cloud/container_analysis.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/container_analysis_client.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/credentials.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/options.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/iam/v1/policy.rb
  google-cloud-container_analysis/lib/google/cloud/container_analysis/v1/doc/google/type/expr.rb
  google-cloud-container_analysis/synth.metadata
  google-cloud-container_analysis/test/google/cloud/container_analysis/v1/container_analysis_client_test.rb
Labels: cla: yes

#4624 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/acceptance/google/cloud/dataproc/v1/cluster_controller_smoke_test.rb
  google-cloud-dataproc/acceptance/google/cloud/dataproc/v1beta2/cluster_controller_smoke_test.rb
  google-cloud-dataproc/lib/google/cloud/dataproc.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/credentials.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/autoscaling_policies.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/cloud/dataproc/v1/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/longrunning/operations.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/any.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/duration.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/empty.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/field_mask.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/protobuf/timestamp.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/rpc/status.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/workflow_template_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/cluster_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/credentials.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/autoscaling_policies.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/clusters.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/jobs.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/cloud/dataproc/v1beta2/workflow_templates.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/longrunning/operations.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/any.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/duration.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/empty.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/field_mask.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/protobuf/timestamp.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/rpc/status.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/job_controller_client.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/workflow_template_service_client.rb
  google-cloud-dataproc/synth.metadata
  google-cloud-dataproc/test/google/cloud/dataproc/v1/cluster_controller_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1/job_controller_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1/workflow_template_service_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1beta2/autoscaling_policy_service_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1beta2/cluster_controller_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1beta2/job_controller_client_test.rb
  google-cloud-dataproc/test/google/cloud/dataproc/v1beta2/workflow_template_service_client_test.rb
Labels: cla: yes

#4625 [CHANGE ME] Re-generated google-cloud-datastore to pick up changes in the API or client library generator.
  google-cloud-datastore/lib/google/cloud/datastore/v1/credentials.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/datastore_client.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/datastore.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/entity.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/datastore/v1/query.rb
  google-cloud-datastore/lib/google/cloud/datastore/v1/doc/google/protobuf/wrappers.rb
  google-cloud-datastore/synth.metadata
Labels: cla: yes

#4626 [CHANGE ME] Re-generated google-cloud-debugger to pick up changes in the API or client library generator.
  google-cloud-debugger/lib/google/cloud/debugger/v2.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/controller2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/credentials.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/debugger2_client.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/controller.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/data.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/clouddebugger/v2/debugger.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/devtools/source/v1/source_context.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/protobuf/empty.rb
  google-cloud-debugger/lib/google/cloud/debugger/v2/doc/google/protobuf/timestamp.rb
  google-cloud-debugger/synth.metadata
  google-cloud-debugger/test/google/cloud/debugger/v2/controller2_client_test.rb
  google-cloud-debugger/test/google/cloud/debugger/v2/debugger2_client_test.rb
Labels: cla: yes

#4627 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/agents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/contexts_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/credentials.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/audio_config.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/context.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session_entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/longrunning/operations.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/any.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/duration.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/empty.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/field_mask.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/protobuf/struct.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/rpc/status.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/type/latlng.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/intents_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/session_entity_types_client.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/sessions_client.rb
  google-cloud-dialogflow/synth.metadata
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/agents_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/contexts_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/entity_types_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/intents_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/session_entity_types_client_test.rb
  google-cloud-dialogflow/test/google/cloud/dialogflow/v2/sessions_client_test.rb
Labels: cla: yes

#4628 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/credentials.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/dlp_service_client.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/dlp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/privacy/dlp/v2/storage.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/any.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/duration.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/empty.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/field_mask.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/protobuf/timestamp.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/rpc/status.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/type/date.rb
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/type/timeofday.rb
  google-cloud-dlp/synth.metadata
  google-cloud-dlp/test/google/cloud/dlp/v2/dlp_service_client_test.rb
Labels: cla: yes

#4629 [CHANGE ME] Re-generated google-cloud-error_reporting to pick up changes in the API or client library generator.
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/credentials.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/common.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_group_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/error_stats_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/devtools/clouderrorreporting/v1beta1/report_errors_service.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/protobuf/duration.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_group_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/error_stats_service_client.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/v1beta1/report_errors_service_client.rb
  google-cloud-error_reporting/synth.metadata
Labels: cla: yes

#4630 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/admin.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/credentials.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/firestore/admin/v1/field.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/firestore/admin/v1/firestore_admin.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/firestore/admin/v1/index.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/longrunning/operations.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/protobuf/any.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/protobuf/empty.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/protobuf/field_mask.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/rpc/status.rb
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/firestore_admin_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/credentials.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/common.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/document.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/firestore/v1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/protobuf/any.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/protobuf/empty.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/protobuf/timestamp.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/protobuf/wrappers.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/rpc/status.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/firestore_client.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/credentials.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/common.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/document.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/firestore.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/query.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/firestore/v1beta1/write.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/any.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/empty.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/protobuf/wrappers.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/rpc/status.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/firestore_client.rb
  google-cloud-firestore/synth.metadata
  google-cloud-firestore/test/google/cloud/firestore/admin/v1/firestore_admin_client_test.rb
  google-cloud-firestore/test/google/cloud/firestore/v1/firestore_client_test.rb
  google-cloud-firestore/test/google/cloud/firestore/v1beta1/firestore_client_test.rb
Labels: cla: yes

#4631 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/credentials.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents_service.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/protobuf/empty.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/protobuf/field_mask.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/protobuf/timestamp.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/synth.metadata
  google-cloud-irm/test/google/cloud/irm/v1alpha2/incident_service_client_test.rb
Labels: cla: yes

#4621 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/credentials.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/bigtable_instance_admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/bigtable_table_admin.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/bigtable/admin/v2/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/iam_policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/options.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/iam/v1/policy.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/longrunning/operations.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/any.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/duration.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/empty.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/field_mask.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/protobuf/timestamp.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/rpc/status.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/type/expr.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/bigtable_client.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/credentials.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/bigtable/v2/bigtable.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/bigtable/v2/data.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/protobuf/any.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/protobuf/wrappers.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/rpc/status.rb
  google-cloud-bigtable/synth.metadata
  google-cloud-bigtable/test/google/cloud/bigtable/admin/v2/bigtable_instance_admin_client_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/admin/v2/bigtable_table_admin_client_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/v2/bigtable_client_test.rb
Labels: cla: yes

#4632 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/lib/google/cloud/kms.rb
  google-cloud-kms/lib/google/cloud/kms/v1.rb
  google-cloud-kms/lib/google/cloud/kms/v1/credentials.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/resources.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/cloud/kms/v1/service.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/iam/v1/options.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/iam/v1/policy.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/protobuf/duration.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/protobuf/field_mask.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/protobuf/timestamp.rb
  google-cloud-kms/lib/google/cloud/kms/v1/doc/google/type/expr.rb
  google-cloud-kms/lib/google/cloud/kms/v1/key_management_service_client.rb
  google-cloud-kms/synth.metadata
  google-cloud-kms/test/google/cloud/kms/v1/key_management_service_client_test.rb
Labels: cla: yes

#4633 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/lib/google/cloud/language.rb
  google-cloud-language/lib/google/cloud/language/v1.rb
  google-cloud-language/lib/google/cloud/language/v1/credentials.rb
  google-cloud-language/lib/google/cloud/language/v1/doc/google/cloud/language/v1/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1/language_service_client.rb
  google-cloud-language/lib/google/cloud/language/v1beta2.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/credentials.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/doc/google/cloud/language/v1beta2/language_service.rb
  google-cloud-language/lib/google/cloud/language/v1beta2/language_service_client.rb
  google-cloud-language/synth.metadata
  google-cloud-language/test/google/cloud/language/v1/language_service_client_test.rb
  google-cloud-language/test/google/cloud/language/v1beta2/language_service_client_test.rb
Labels: cla: yes

#4634 [CHANGE ME] Re-generated google-cloud-logging to pick up changes in the API or client library generator.
  google-cloud-logging/lib/google/cloud/logging/v2/config_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/credentials.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/distribution.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/label.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/metric.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/api/monitored_resource.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/type/http_request.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/log_entry.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_config.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/logging/v2/logging_metrics.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/any.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/duration.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/empty.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/field_mask.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/struct.rb
  google-cloud-logging/lib/google/cloud/logging/v2/doc/google/protobuf/timestamp.rb
  google-cloud-logging/lib/google/cloud/logging/v2/logging_service_v2_client.rb
  google-cloud-logging/lib/google/cloud/logging/v2/metrics_service_v2_client.rb
  google-cloud-logging/synth.metadata
Labels: cla: yes

#4635 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/acceptance/google/cloud/monitoring/v3/metric_service_smoke_test.rb
  google-cloud-monitoring/lib/google/cloud/monitoring.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/credentials.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/dashboards_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/common.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/dashboard.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/dashboards_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/layouts.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/metrics.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/scorecard.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/text.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/widget.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/monitoring/dashboard/v1/xychart.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/protobuf/duration.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/dashboard/v1/doc/google/protobuf/empty.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/credentials.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/distribution.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/label.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/api/monitored_resource.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/common.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/group.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/group_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/mutation_record.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/service_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/any.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/duration.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/empty.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/field_mask.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/struct.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/timestamp.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/protobuf/wrappers.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/rpc/status.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/service_monitoring_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client.rb
  google-cloud-monitoring/synth.metadata
  google-cloud-monitoring/test/google/cloud/monitoring/dashboard/v1/dashboards_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/alert_policy_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/group_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/metric_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/notification_channel_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/service_monitoring_service_client_test.rb
  google-cloud-monitoring/test/google/cloud/monitoring/v3/uptime_check_service_client_test.rb
Labels: cla: yes

#4636 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/lib/google/cloud/os_login.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/credentials.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/cloud/oslogin/common/common.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/cloud/oslogin/v1/oslogin.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/protobuf/empty.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/doc/google/protobuf/field_mask.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1/os_login_service_client.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/credentials.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/cloud/oslogin/common/common.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/cloud/oslogin/v1beta/oslogin.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/protobuf/empty.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/doc/google/protobuf/field_mask.rb
  google-cloud-os_login/lib/google/cloud/os_login/v1beta/os_login_service_client.rb
  google-cloud-os_login/synth.metadata
  google-cloud-os_login/test/google/cloud/os_login/v1/os_login_service_client_test.rb
  google-cloud-os_login/test/google/cloud/os_login/v1beta/os_login_service_client_test.rb
Labels: cla: yes

#4637 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/credentials.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/doc/google/cloud/phishingprotection/v1beta1/phishingprotection.rb
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_client.rb
  google-cloud-phishing_protection/synth.metadata
  google-cloud-phishing_protection/test/google/cloud/phishing_protection/v1beta1/phishing_protection_client_test.rb
Labels: cla: yes

#4638 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/credentials.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/iam/v1/options.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/iam/v1/policy.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/duration.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/empty.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/field_mask.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/protobuf/timestamp.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/type/expr.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/publisher_client.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes

#4639 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/credentials.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/cloud/recaptchaenterprise/v1beta1/recaptchaenterprise.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/protobuf/empty.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client.rb
  google-cloud-recaptcha_enterprise/synth.metadata
  google-cloud-recaptcha_enterprise/test/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_client_test.rb
Labels: cla: yes

#4640 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1.rb
  google-cloud-redis/lib/google/cloud/redis/v1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1/credentials.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/cloud/redis/v1/cloud_redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/longrunning/operations.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/protobuf/any.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/protobuf/field_mask.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/protobuf/timestamp.rb
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/rpc/status.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/cloud_redis_client.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/credentials.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/cloud/redis/v1beta1/cloud_redis.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/longrunning/operations.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/protobuf/any.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/rpc/status.rb
  google-cloud-redis/synth.metadata
  google-cloud-redis/test/google/cloud/redis/v1/cloud_redis_client_test.rb
  google-cloud-redis/test/google/cloud/redis/v1beta1/cloud_redis_client_test.rb
Labels: cla: yes

#4641 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/credentials.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/cloudscheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/job.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/cloud/scheduler/v1/target.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/any.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/duration.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/empty.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/field_mask.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/protobuf/timestamp.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/rpc/status.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/cloud_scheduler_client.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/credentials.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/cloud/scheduler/v1beta1/cloudscheduler.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/cloud/scheduler/v1beta1/job.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/cloud/scheduler/v1beta1/target.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/any.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/duration.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/empty.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/field_mask.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/rpc/status.rb
  google-cloud-scheduler/synth.metadata
  google-cloud-scheduler/test/google/cloud/scheduler/v1/cloud_scheduler_client_test.rb
  google-cloud-scheduler/test/google/cloud/scheduler/v1beta1/cloud_scheduler_client_test.rb
Labels: cla: yes

#4642 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/credentials.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/asset.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/finding.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/organization_settings.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/security_marks.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/securitycenter_service.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/cloud/securitycenter/v1/source.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/options.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/iam/v1/policy.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/longrunning/operations.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/any.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/duration.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/field_mask.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/struct.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/protobuf/timestamp.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/rpc/status.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/type/expr.rb
  google-cloud-security_center/lib/google/cloud/security_center/v1/security_center_client.rb
  google-cloud-security_center/synth.metadata
  google-cloud-security_center/test/google/cloud/security_center/v1/security_center_client_test.rb
Labels: cla: yes

#4643 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/credentials.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/options.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/longrunning/operations.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/protobuf/any.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/protobuf/empty.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/spanner/admin/database/v1/spanner_database_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/type/expr.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/credentials.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/iam_policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/options.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/iam/v1/policy.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/longrunning/operations.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/protobuf/any.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/protobuf/empty.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/protobuf/field_mask.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/spanner/admin/instance/v1/spanner_instance_admin.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/type/expr.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/instance_admin_client.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/credentials.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/any.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/duration.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/empty.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/struct.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/protobuf/timestamp.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/keys.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/mutation.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/query_plan.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/result_set.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/spanner.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/transaction.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/spanner/v1/type.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client.rb
  google-cloud-spanner/synth.metadata
  google-cloud-spanner/test/google/cloud/spanner/admin/database/v1/database_admin_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/admin/instance/v1/instance_admin_client_test.rb
  google-cloud-spanner/test/google/cloud/spanner/v1/spanner_client_test.rb
Labels: cla: yes

#4644 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/acceptance/google/cloud/speech/v1/speech_smoke_test.rb
  google-cloud-speech/acceptance/google/cloud/speech/v1p1beta1/speech_smoke_test.rb
  google-cloud-speech/lib/google/cloud/speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1.rb
  google-cloud-speech/lib/google/cloud/speech/v1/credentials.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/longrunning/operations.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/protobuf/any.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/protobuf/duration.rb
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/rpc/status.rb
  google-cloud-speech/lib/google/cloud/speech/v1/speech_client.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/credentials.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/longrunning/operations.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/protobuf/any.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/protobuf/duration.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/rpc/status.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/speech_client.rb
  google-cloud-speech/synth.metadata
  google-cloud-speech/test/google/cloud/speech/v1/speech_client_test.rb
  google-cloud-speech/test/google/cloud/speech/v1p1beta1/speech_client_test.rb
Labels: cla: yes

#4645 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/credentials.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/completion_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/histogram.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/longrunning/operations.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/protobuf/any.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/protobuf/duration.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/protobuf/empty.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/protobuf/field_mask.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/protobuf/timestamp.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/protobuf/wrappers.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/rpc/status.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/date.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/latlng.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/money.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/postal_address.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/type/timeofday.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client.rb
  google-cloud-talent/synth.metadata
  google-cloud-talent/test/google/cloud/talent/v4beta1/application_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/company_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/completion_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/event_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/job_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/profile_service_client_test.rb
  google-cloud-talent/test/google/cloud/talent/v4beta1/tenant_service_client_test.rb
Labels: cla: yes

#4646 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/credentials.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/cloud/tasks/v2/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/options.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/duration.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/empty.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/rpc/status.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/type/expr.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/credentials.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/cloud/tasks/v2beta2/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/options.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/duration.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/empty.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/rpc/status.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/type/expr.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/cloud_tasks_client.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/credentials.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/cloudtasks.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/queue.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/target.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/cloud/tasks/v2beta3/task.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/iam_policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/options.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/iam/v1/policy.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/any.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/duration.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/empty.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/field_mask.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/protobuf/timestamp.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/rpc/status.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/type/expr.rb
  google-cloud-tasks/synth.metadata
  google-cloud-tasks/test/google/cloud/tasks/v2/cloud_tasks_client_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2beta2/cloud_tasks_client_test.rb
  google-cloud-tasks/test/google/cloud/tasks/v2beta3/cloud_tasks_client_test.rb
Labels: cla: yes

#4647 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/credentials.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/doc/google/cloud/texttospeech/v1/cloud_tts.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1/text_to_speech_client.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/credentials.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/doc/google/cloud/texttospeech/v1beta1/cloud_tts.rb
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/v1beta1/text_to_speech_client.rb
  google-cloud-text_to_speech/synth.metadata
  google-cloud-text_to_speech/test/google/cloud/text_to_speech/v1/text_to_speech_client_test.rb
  google-cloud-text_to_speech/test/google/cloud/text_to_speech/v1beta1/text_to_speech_client_test.rb
Labels: cla: yes

#4648 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v1/credentials.rb
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/devtools/cloudtrace/v1/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/protobuf/empty.rb
  google-cloud-trace/lib/google/cloud/trace/v1/doc/google/protobuf/timestamp.rb
  google-cloud-trace/lib/google/cloud/trace/v1/trace_service_client.rb
  google-cloud-trace/lib/google/cloud/trace/v2/credentials.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/trace.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/devtools/cloudtrace/v2/tracing.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/any.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/empty.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/timestamp.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/protobuf/wrappers.rb
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/rpc/status.rb
  google-cloud-trace/lib/google/cloud/trace/v2/trace_service_client.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#4649 [CHANGE ME] Re-generated google-cloud-translate to pick up changes in the API or client library generator.
  google-cloud-translate/lib/google/cloud/translate/v3.rb
  google-cloud-translate/lib/google/cloud/translate/v3/credentials.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/cloud/translate/v3/translation_service.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/longrunning/operations.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/protobuf/any.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/protobuf/timestamp.rb
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/rpc/status.rb
  google-cloud-translate/lib/google/cloud/translate/v3/translation_service_client.rb
  google-cloud-translate/synth.metadata
  google-cloud-translate/test/google/cloud/translate/v3/translation_service_client_test.rb
Labels: cla: yes

#4650 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/acceptance/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_smoke_test.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/cloud/videointelligence/v1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/protobuf/duration.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/cloud/videointelligence/v1beta2/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/protobuf/duration.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/cloud/videointelligence/v1p1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/protobuf/duration.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/credentials.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/cloud/videointelligence/v1p2beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/longrunning/operations.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/protobuf/any.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/protobuf/duration.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/synth.metadata
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client_test.rb
  google-cloud-video_intelligence/test/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client_test.rb
Labels: cla: yes

#4651 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/acceptance/google/cloud/vision/v1/image_annotator_smoke_test.rb
  google-cloud-vision/acceptance/google/cloud/vision/v1p3beta1/image_annotator_smoke_test.rb
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/lib/google/cloud/vision/v1.rb
  google-cloud-vision/lib/google/cloud/vision/v1/credentials.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/geometry.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/image_annotator.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/text_annotation.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/cloud/vision/v1/web_detection.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/longrunning/operations.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/any.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/empty.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/field_mask.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/timestamp.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/protobuf/wrappers.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/rpc/status.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/type/color.rb
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/type/latlng.rb
  google-cloud-vision/lib/google/cloud/vision/v1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1/product_search_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/credentials.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/geometry.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/image_annotator.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/product_search.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/product_search_service.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/text_annotation.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/cloud/vision/v1p3beta1/web_detection.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/longrunning/operations.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/any.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/empty.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/field_mask.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/timestamp.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/protobuf/wrappers.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/rpc/status.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/type/color.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/type/latlng.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/image_annotator_client.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/product_search_client.rb
  google-cloud-vision/synth.metadata
  google-cloud-vision/test/google/cloud/vision/v1/image_annotator_client_test.rb
  google-cloud-vision/test/google/cloud/vision/v1/product_search_client_test.rb
  google-cloud-vision/test/google/cloud/vision/v1p3beta1/image_annotator_client_test.rb
  google-cloud-vision/test/google/cloud/vision/v1p3beta1/product_search_client_test.rb
Labels: cla: yes

#4652 [CHANGE ME] Re-generated google-cloud-webrisk to pick up changes in the API or client library generator.
  google-cloud-webrisk/lib/google/cloud/webrisk.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/credentials.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/doc/google/cloud/webrisk/v1beta1/webrisk.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/doc/google/protobuf/timestamp.rb
  google-cloud-webrisk/lib/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client.rb
  google-cloud-webrisk/synth.metadata
  google-cloud-webrisk/test/google/cloud/webrisk/v1beta1/web_risk_service_v1_beta1_client_test.rb
Labels: cla: yes

#4653 [CHANGE ME] Re-generated grafeas to pick up changes in the API or client library generator.
  grafeas/lib/grafeas.rb
  grafeas/lib/grafeas/v1.rb
  grafeas/lib/grafeas/v1/credentials.rb
  grafeas/lib/grafeas/v1/doc/google/protobuf/any.rb
  grafeas/lib/grafeas/v1/doc/google/protobuf/empty.rb
  grafeas/lib/grafeas/v1/doc/google/protobuf/field_mask.rb
  grafeas/lib/grafeas/v1/doc/google/protobuf/timestamp.rb
  grafeas/lib/grafeas/v1/doc/google/rpc/status.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/attestation.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/build.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/common.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/cvss.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/deployment.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/discovery.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/grafeas.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/image.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/package.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/provenance.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/upgrade.rb
  grafeas/lib/grafeas/v1/doc/grafeas/v1/vulnerability.rb
  grafeas/lib/grafeas/v1/grafeas_client.rb
  grafeas/synth.metadata
  grafeas/test/grafeas/v1/grafeas_client_test.rb
Labels: cla: yes

#4692 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/securitycenter_service_pb.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#4691 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/agent.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/cloud/dialogflow/v2/session_entity_type.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_type_services_pb.rb
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/entity_types_client.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4693 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client_config.json
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client_config.json
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4658 docs(secret_manager): Clarify library status and provide some additional links
  google-cloud-secret_manager/README.md
  google-cloud-secret_manager/lib/google/cloud/secret_manager.rb
Labels: cla: yes

#4661 Secret Manager resource path helpers
  google-cloud-secret_manager-v1beta1/lib/google/cloud/common_resources_pb.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/paths.rb
Labels: cla: yes

#4700 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/application_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/common_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/company_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/completion_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/application_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/common.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/company_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/completion_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/event_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/filters.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/histogram.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/job_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/profile_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/cloud/talent/v4beta1/tenant_service.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/event_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/filters_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/job_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/profile_service_services_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_pb.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_client.rb
  google-cloud-talent/lib/google/cloud/talent/v4beta1/tenant_service_pb.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4660 docs(spanner): fix incorrect doc links in CONTRIBUTING.md.
  google-cloud-spanner/CONTRIBUTING.md
Labels: cla: yes

#4698 Release google-cloud-secret_manager-v1beta1 0.2.0
  google-cloud-secret_manager-v1beta1/CHANGELOG.md
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4702 feat(secret_manager): Use update to secret_manager-v1beta1 that provides resource path helpers
  google-cloud-secret_manager/google-cloud-secret_manager.gemspec
Labels: cla: yes

#4703 Release google-cloud-secret_manager 0.2.0
  google-cloud-secret_manager/CHANGELOG.md
  google-cloud-secret_manager/lib/google/cloud/secret_manager/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4704 fix(spanner): fix the issue that emulator needs an insecure grpc channel
  google-cloud-spanner/lib/google/cloud/spanner/service.rb
Labels: cla: yes, type: bug

#4710 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/lib/google/cloud/automl/v1beta1/doc/google/rpc/status.rb
  google-cloud-automl/synth.metadata
Labels: cla: yes

#4711 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/v1/doc/google/rpc/status.rb
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes

#4712 [CHANGE ME] Re-generated google-cloud-bigtable to pick up changes in the API or client library generator.
  google-cloud-bigtable/lib/google/cloud/bigtable/admin/v2/doc/google/rpc/status.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/v2/doc/google/rpc/status.rb
  google-cloud-bigtable/synth.metadata
Labels: cla: yes

#4713 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/lib/google/cloud/dataproc/v1/doc/google/rpc/status.rb
  google-cloud-dataproc/lib/google/cloud/dataproc/v1beta2/doc/google/rpc/status.rb
  google-cloud-dataproc/synth.metadata
Labels: cla: yes

#4714 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/lib/google/cloud/dialogflow/v2/doc/google/rpc/status.rb
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes

#4715 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/lib/google/cloud/dlp/v2/doc/google/rpc/status.rb
  google-cloud-dlp/synth.metadata
Labels: cla: yes

#4716 [CHANGE ME] Re-generated google-cloud-firestore to pick up changes in the API or client library generator.
  google-cloud-firestore/lib/google/cloud/firestore/admin/v1/doc/google/rpc/status.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1/doc/google/rpc/status.rb
  google-cloud-firestore/lib/google/cloud/firestore/v1beta1/doc/google/rpc/status.rb
  google-cloud-firestore/synth.metadata
Labels: cla: yes

#4717 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/rpc/status.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4718 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis/v1/doc/google/rpc/status.rb
  google-cloud-redis/lib/google/cloud/redis/v1beta1/doc/google/rpc/status.rb
  google-cloud-redis/synth.metadata
Labels: cla: yes

#4719 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler/v1/doc/google/rpc/status.rb
  google-cloud-scheduler/lib/google/cloud/scheduler/v1beta1/doc/google/rpc/status.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes

#4720 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center/v1/doc/google/rpc/status.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes

#4721 [CHANGE ME] Re-generated google-cloud-spanner to pick up changes in the API or client library generator.
  google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance/v1/doc/google/rpc/status.rb
  google-cloud-spanner/lib/google/cloud/spanner/v1/doc/google/rpc/status.rb
  google-cloud-spanner/synth.metadata
Labels: cla: yes

#4722 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech/v1/doc/google/rpc/status.rb
  google-cloud-speech/lib/google/cloud/speech/v1p1beta1/doc/google/rpc/status.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes

#4723 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent/v4beta1/doc/google/rpc/status.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes

#4724 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks/v2/doc/google/rpc/status.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta2/doc/google/rpc/status.rb
  google-cloud-tasks/lib/google/cloud/tasks/v2beta3/doc/google/rpc/status.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes

#4725 [CHANGE ME] Re-generated google-cloud-trace to pick up changes in the API or client library generator.
  google-cloud-trace/lib/google/cloud/trace/v2/doc/google/rpc/status.rb
  google-cloud-trace/synth.metadata
Labels: cla: yes

#4726 [CHANGE ME] Re-generated google-cloud-translate to pick up changes in the API or client library generator.
  google-cloud-translate/lib/google/cloud/translate/v3/doc/google/rpc/status.rb
  google-cloud-translate/synth.metadata
Labels: cla: yes

#4727 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/rpc/status.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#4728 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision/v1/doc/google/rpc/status.rb
  google-cloud-vision/lib/google/cloud/vision/v1p3beta1/doc/google/rpc/status.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes

#4729 [CHANGE ME] Re-generated grafeas to pick up changes in the API or client library generator.
  grafeas/lib/grafeas/v1/doc/google/rpc/status.rb
  grafeas/synth.metadata
Labels: cla: yes

#4709 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1/doc/google/rpc/status.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/rpc/status.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#4655 Release google-cloud-automl 0.5.1
  google-cloud-automl/CHANGELOG.md
  google-cloud-automl/lib/google/cloud/automl/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4705 feat(spanner): Add support for client's sessions pool reset
  google-cloud-spanner/acceptance/spanner/client/reset_test.rb
  google-cloud-spanner/lib/google/cloud/spanner/client.rb
  google-cloud-spanner/lib/google/cloud/spanner/pool.rb
  google-cloud-spanner/test/google/cloud/spanner/client/reset_test.rb
Labels: api: spanner, cla: yes

#4656 Release google-cloud-speech 0.40.2
  google-cloud-speech/CHANGELOG.md
  google-cloud-speech/lib/google/cloud/speech/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4663 Release google-cloud-asset 0.6.1
  google-cloud-asset/CHANGELOG.md
  google-cloud-asset/lib/google/cloud/asset/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4666 Release google-cloud-bigquery-data_transfer 0.5.1
  google-cloud-bigquery-data_transfer/CHANGELOG.md
  google-cloud-bigquery-data_transfer/lib/google/cloud/bigquery/data_transfer/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4664 Release google-cloud-monitoring 0.34.2
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4657 Release grafeas 0.2.1
  grafeas/CHANGELOG.md
  grafeas/lib/grafeas/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4665 Release google-cloud-tasks 1.3.4
  google-cloud-tasks/CHANGELOG.md
  google-cloud-tasks/lib/google/cloud/tasks/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4667 Release google-cloud-dlp 0.13.2
  google-cloud-dlp/CHANGELOG.md
  google-cloud-dlp/lib/google/cloud/dlp/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4668 Release google-cloud-dialogflow 0.12.1
  google-cloud-dialogflow/CHANGELOG.md
  google-cloud-dialogflow/lib/google/cloud/dialogflow/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4674 Release google-cloud-scheduler 1.2.1
  google-cloud-scheduler/CHANGELOG.md
  google-cloud-scheduler/lib/google/cloud/scheduler/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4677 Release google-cloud-translate 2.1.1
  google-cloud-translate/CHANGELOG.md
  google-cloud-translate/lib/google/cloud/translate/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4679 Release google-cloud-security_center 0.5.1
  google-cloud-security_center/CHANGELOG.md
  google-cloud-security_center/lib/google/cloud/security_center/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4681 Release google-cloud-talent 0.8.3
  google-cloud-talent/CHANGELOG.md
  google-cloud-talent/lib/google/cloud/talent/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4682 Release google-cloud-redis 0.6.2
  google-cloud-redis/CHANGELOG.md
  google-cloud-redis/lib/google/cloud/redis/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4684 Release google-cloud-bigtable 1.0.2
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4686 Release google-cloud-vision 0.37.2
  google-cloud-vision/CHANGELOG.md
  google-cloud-vision/lib/google/cloud/vision/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4687 Release google-cloud-video_intelligence 2.0.2
  google-cloud-video_intelligence/CHANGELOG.md
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4689 Release google-cloud-spanner 1.13.1
  google-cloud-spanner/CHANGELOG.md
  google-cloud-spanner/lib/google/cloud/spanner/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4690 Release google-cloud-firestore 1.2.4
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4699 Release google-cloud-dataproc 0.7.3
  google-cloud-dataproc/CHANGELOG.md
  google-cloud-dataproc/lib/google/cloud/dataproc/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4731 Release google-cloud-trace 0.37.1
  google-cloud-trace/CHANGELOG.md
  google-cloud-trace/lib/google/cloud/trace/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4662 Release google-cloud-container 0.8.1
  google-cloud-container/CHANGELOG.md
  google-cloud-container/lib/google/cloud/container/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4669 Release google-cloud-phishing_protection 0.3.2
  google-cloud-phishing_protection/CHANGELOG.md
  google-cloud-phishing_protection/lib/google/cloud/phishing_protection/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4670 Release google-cloud-datastore 1.7.3
  google-cloud-datastore/CHANGELOG.md
  google-cloud-datastore/lib/google/cloud/datastore/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4671 Release google-cloud-language 0.35.3
  google-cloud-language/CHANGELOG.md
  google-cloud-language/lib/google/cloud/language/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4672 Release google-cloud-text_to_speech 0.5.2
  google-cloud-text_to_speech/CHANGELOG.md
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4673 Release google-cloud-recaptcha_enterprise 0.4.1
  google-cloud-recaptcha_enterprise/CHANGELOG.md
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4675 Release google-cloud-kms 1.4.1
  google-cloud-kms/CHANGELOG.md
  google-cloud-kms/lib/google/cloud/kms/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4676 Release google-cloud-webrisk 0.4.2
  google-cloud-webrisk/CHANGELOG.md
  google-cloud-webrisk/lib/google/cloud/webrisk/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4678 Release google-cloud-logging 1.9.4
  google-cloud-logging/CHANGELOG.md
  google-cloud-logging/lib/google/cloud/logging/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4680 Release google-cloud-os_login 0.5.3
  google-cloud-os_login/CHANGELOG.md
  google-cloud-os_login/lib/google/cloud/os_login/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4683 Release google-cloud-error_reporting 0.34.2
  google-cloud-error_reporting/CHANGELOG.md
  google-cloud-error_reporting/lib/google/cloud/error_reporting/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4685 Release google-cloud-debugger 0.35.2
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4688 Release google-cloud-pubsub 1.2.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes, type: process

#4732 chore(secret_manager-v1beta1): add synth script
  google-cloud-secret_manager-v1beta1/synth.py
Labels: cla: yes

#4740 [CHANGE ME] Re-generated google-cloud-irm to pick up changes in the API or client library generator.
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/doc/google/cloud/irm/v1alpha2/incidents_service.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/helpers.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incident_service_client_config.json
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_pb.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_service_pb.rb
  google-cloud-irm/lib/google/cloud/irm/v1alpha2/incidents_service_services_pb.rb
  google-cloud-irm/synth.metadata
  google-cloud-irm/test/google/cloud/irm/v1alpha2/helpers_test.rb
  google-cloud-irm/test/google/cloud/irm/v1alpha2/incident_service_client_test.rb
Labels: cla: yes

#4733 Add google-cloud-billing-v1
  Gemfile
  google-cloud-billing-v1/.gitignore
  google-cloud-billing-v1/.repo-metadata.json
  google-cloud-billing-v1/.rubocop.yml
  google-cloud-billing-v1/.yardopts
  google-cloud-billing-v1/AUTHENTICATION.md
  google-cloud-billing-v1/CHANGELOG.md
  google-cloud-billing-v1/Gemfile
  google-cloud-billing-v1/LICENSE.md
  google-cloud-billing-v1/README.md
  google-cloud-billing-v1/Rakefile
  google-cloud-billing-v1/google-cloud-billing-v1.gemspec
  google-cloud-billing-v1/lib/google-cloud-billing-v1.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/credentials.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/paths.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing_pb.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing_services_pb.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/credentials.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/paths.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog_pb.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog_services_pb.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/version.rb
  google-cloud-billing-v1/lib/google/cloud/common_resources_pb.rb
  google-cloud-billing-v1/proto_docs/README.md
  google-cloud-billing-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-billing-v1/proto_docs/google/api/resource.rb
  google-cloud-billing-v1/proto_docs/google/cloud/billing/v1/cloud_billing.rb
  google-cloud-billing-v1/proto_docs/google/cloud/billing/v1/cloud_catalog.rb
  google-cloud-billing-v1/proto_docs/google/iam/v1/iam_policy.rb
  google-cloud-billing-v1/proto_docs/google/iam/v1/policy.rb
  google-cloud-billing-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-billing-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-billing-v1/proto_docs/google/type/money.rb
  google-cloud-billing-v1/synth.metadata
  google-cloud-billing-v1/synth.py
  google-cloud-billing-v1/test/google/cloud/billing/v1/cloud_billing_test.rb
  google-cloud-billing-v1/test/google/cloud/billing/v1/cloud_catalog_test.rb
Labels: cla: yes

#4744 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/doc/google/cloud/videointelligence/v1beta2/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/doc/google/cloud/videointelligence/v1p2beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1beta2/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1beta2/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1p2beta1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1p2beta1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#4743 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-secret_manager-v1beta1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#4750 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/doc/google/cloud/videointelligence/v1p1beta1/video_intelligence.rb
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service_client.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1p1beta1/video_intelligence_pb.rb
  google-cloud-video_intelligence/lib/google/cloud/videointelligence/v1p1beta1/video_intelligence_services_pb.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes

#4751 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_client.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/asset_service_services_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/assets_pb.rb
  google-cloud-asset/lib/google/cloud/asset/v1beta1/doc/google/cloud/asset/v1beta1/asset_service.rb
  google-cloud-asset/synth.metadata
Labels: cla: yes

#4753 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/alert_policy_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/alert_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/common.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/group_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/metric_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/notification_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/service_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/doc/google/monitoring/v3/uptime_service.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/group_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/metric_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/notification_channel_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/service_monitoring_service_client.rb
  google-cloud-monitoring/lib/google/cloud/monitoring/v3/uptime_check_service_client.rb
  google-cloud-monitoring/lib/google/monitoring/v3/alert_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/alert_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/group_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/group_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/metric_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/notification_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/service_service_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_pb.rb
  google-cloud-monitoring/lib/google/monitoring/v3/uptime_service_pb.rb
  google-cloud-monitoring/synth.metadata
Labels: cla: yes

#4754 [CHANGE ME] Re-generated google-cloud-pubsub to pick up changes in the API or client library generator.
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/doc/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/v1/subscriber_client.rb
  google-cloud-pubsub/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub/synth.metadata
Labels: cla: yes
