Repository googleapis/google-cloud-ruby, pull requests merged in 2021-04, with the labels that each got.

#11097 chore: release google-cloud-pubsub 2.5.0
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#11098 chore: release google-cloud-bigtable 2.4.1
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#11099 [google-cloud-recommendation_engine-v1beta1] docs: place paths in code spans chore: update python package name to `google-cloud-recomendations-ai`
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/catalog_service/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/prediction_api_key_registry/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/prediction_service/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/user_event_service/client.rb
  google-cloud-recommendation_engine-v1beta1/proto_docs/google/cloud/recommendationengine/v1beta1/catalog_service.rb
  google-cloud-recommendation_engine-v1beta1/proto_docs/google/cloud/recommendationengine/v1beta1/import.rb
  google-cloud-recommendation_engine-v1beta1/proto_docs/google/cloud/recommendationengine/v1beta1/prediction_apikey_registry_service.rb
  google-cloud-recommendation_engine-v1beta1/proto_docs/google/cloud/recommendationengine/v1beta1/prediction_service.rb
  google-cloud-recommendation_engine-v1beta1/proto_docs/google/cloud/recommendationengine/v1beta1/user_event_service.rb
  google-cloud-recommendation_engine-v1beta1/synth.metadata
Labels: cla: yes, context: full

#11103 chore(memcache-v1beta2): Undo version 0.1.3 changelog
  google-cloud-memcache-v1beta2/CHANGELOG.md
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/version.rb
Labels: cla: yes

#11102 chore: release google-cloud-debugger 0.42.0
  google-cloud-debugger/CHANGELOG.md
  google-cloud-debugger/lib/google/cloud/debugger/version.rb
Labels: autorelease: pending, cla: yes

#11101 chore: release google-cloud-domains-v1beta1 0.2.0
  google-cloud-domains-v1beta1/CHANGELOG.md
  google-cloud-domains-v1beta1/lib/google/cloud/domains/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#10909 chore: removed unsupported samples
  google-cloud-video_intelligence/samples/Gemfile
  google-cloud-video_intelligence/samples/README.md
  google-cloud-video_intelligence/samples/Rakefile
  google-cloud-video_intelligence/samples/acceptance/quickstart_test.rb
  google-cloud-video_intelligence/samples/acceptance/video_samples_test.rb
  google-cloud-video_intelligence/samples/quickstart.rb
  google-cloud-video_intelligence/samples/video_samples.rb
  google-cloud-video_intelligence/samples/video_samples_helper.rb
Labels: cla: yes, samples

#10899 chore: removed unsupported samples
  google-cloud-vision/samples/Gemfile
  google-cloud-vision/samples/README.md
  google-cloud-vision/samples/Rakefile
  google-cloud-vision/samples/acceptance/async_batch_annotate_images_test.rb
  google-cloud-vision/samples/acceptance/batch_annotate_files_gcs_test.rb
  google-cloud-vision/samples/acceptance/batch_annotate_files_test.rb
  google-cloud-vision/samples/acceptance/detect_crop_hints_test.rb
  google-cloud-vision/samples/acceptance/detect_document_text_test.rb
  google-cloud-vision/samples/acceptance/detect_faces_test.rb
  google-cloud-vision/samples/acceptance/detect_image_properties_test.rb
  google-cloud-vision/samples/acceptance/detect_labels_test.rb
  google-cloud-vision/samples/acceptance/detect_landmarks_test.rb
  google-cloud-vision/samples/acceptance/detect_logos_test.rb
  google-cloud-vision/samples/acceptance/detect_pdf_test.rb
  google-cloud-vision/samples/acceptance/detect_safe_search_test.rb
  google-cloud-vision/samples/acceptance/detect_text_test.rb
  google-cloud-vision/samples/acceptance/detect_web_test.rb
  google-cloud-vision/samples/acceptance/draw_box_around_faces_test.rb
  google-cloud-vision/samples/acceptance/helper.rb
  google-cloud-vision/samples/acceptance/localize_objects_test.rb
  google-cloud-vision/samples/acceptance/quickstart_test.rb
  google-cloud-vision/samples/async_batch_annotate_images.rb
  google-cloud-vision/samples/batch_annotate_files.rb
  google-cloud-vision/samples/batch_annotate_files_gcs.rb
  google-cloud-vision/samples/detect_crop_hints.rb
  google-cloud-vision/samples/detect_document_text.rb
  google-cloud-vision/samples/detect_faces.rb
  google-cloud-vision/samples/detect_image_properties.rb
  google-cloud-vision/samples/detect_labels.rb
  google-cloud-vision/samples/detect_landmarks.rb
  google-cloud-vision/samples/detect_logos.rb
  google-cloud-vision/samples/detect_pdf.rb
  google-cloud-vision/samples/detect_safe_search.rb
  google-cloud-vision/samples/detect_text.rb
  google-cloud-vision/samples/detect_web.rb
  google-cloud-vision/samples/draw_box_around_faces.rb
  google-cloud-vision/samples/localize_objects.rb
  google-cloud-vision/samples/quickstart.rb
  google-cloud-vision/samples/resources/IMAGE_SOURCES
  google-cloud-vision/samples/resources/cat.jpg
  google-cloud-vision/samples/resources/eiffel_tower.jpg
  google-cloud-vision/samples/resources/face_no_surprise.png
  google-cloud-vision/samples/resources/face_surprise.jpg
  google-cloud-vision/samples/resources/kafka.pdf
  google-cloud-vision/samples/resources/logos.png
  google-cloud-vision/samples/resources/otter_crossing.jpg
  google-cloud-vision/samples/resources/palace_of_fine_arts.jpg
  google-cloud-vision/samples/resources/pdf_ocr.pdf
  google-cloud-vision/samples/resources/puppies.jpg
  google-cloud-vision/samples/resources/wakeupcat.jpg
  google-cloud-vision/samples/set_endpoint.rb
Labels: cla: yes, samples

#11106 chore(managed_identities): Fix typo in synth script
  google-cloud-managed_identities/synth.py
Labels: cla: yes

#11054 [google-cloud-data_catalog] feat: Policy Tag Manager v1 API service feat: new RenameTagTemplateFieldEnumValue API feat: adding fully_qualified_name in lookup and search feat: added DATAPROC_METASTORE integrated system along with new entry types: DATA
  google-cloud-data_catalog/google-cloud-data_catalog.gemspec
  google-cloud-data_catalog/lib/google/cloud/data_catalog.rb
  google-cloud-data_catalog/synth.metadata
  google-cloud-data_catalog/synth.py
  google-cloud-data_catalog/test/google/cloud/data_catalog/client_test.rb
Labels: cla: yes, context: full

#11109 [google-cloud-service_management-v1] build: update links for service-management, update package name for appengine-admin
  google-cloud-service_management-v1/lib/google/api/servicemanagement/v1/servicemanager_services_pb.rb
  google-cloud-service_management-v1/lib/google/cloud/service_management/v1/service_manager.rb
  google-cloud-service_management-v1/lib/google/cloud/service_management/v1/service_manager/client.rb
  google-cloud-service_management-v1/proto_docs/google/api/servicemanagement/v1/servicemanager.rb
  google-cloud-service_management-v1/synth.metadata
Labels: cla: yes, context: full

#11110 [google-cloud-service_management] build: update links for service-management, update package name for appengine-admin
  google-cloud-service_management/lib/google/cloud/service_management.rb
  google-cloud-service_management/synth.metadata
Labels: cla: yes, context: full

#10917 chore: release google-cloud-spanner-v1 0.6.0
  google-cloud-spanner-v1/CHANGELOG.md
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/version.rb
Labels: autorelease: pending, cla: yes

#10918 chore: release google-cloud-monitoring-v3 0.4.0
  google-cloud-monitoring-v3/CHANGELOG.md
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/version.rb
Labels: autorelease: pending, cla: yes

#10928 chore: release google-cloud-build-v1 0.5.0
  google-cloud-build-v1/CHANGELOG.md
  google-cloud-build-v1/lib/google/cloud/build/v1/version.rb
Labels: autorelease: pending, cla: yes

#11090 chore: release google-cloud-bigquery-storage-v1 0.5.0
  google-cloud-bigquery-storage-v1/CHANGELOG.md
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/version.rb
Labels: autorelease: pending, cla: yes

#11092 chore: release google-cloud-spanner-admin-instance-v1 0.3.1
  google-cloud-spanner-admin-instance-v1/CHANGELOG.md
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/version.rb
Labels: autorelease: pending, cla: yes

#11093 chore: release google-cloud-spanner-admin-database-v1 0.5.1
  google-cloud-spanner-admin-database-v1/CHANGELOG.md
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/version.rb
Labels: autorelease: pending, cla: yes

#11095 chore: release google-cloud-service_control 0.2.1
  google-cloud-service_control/CHANGELOG.md
  google-cloud-service_control/lib/google/cloud/service_control/version.rb
Labels: autorelease: pending, cla: yes

#11094 chore: release google-cloud-secret_manager-v1 0.9.0
  google-cloud-secret_manager-v1/CHANGELOG.md
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/version.rb
Labels: autorelease: pending, cla: yes

#11096 chore: release google-cloud-text_to_speech-v1beta1 0.6.0
  google-cloud-text_to_speech-v1beta1/CHANGELOG.md
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/text_to_speech/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#11107 chore: release google-cloud-memcache-v1beta2 0.2.0
  google-cloud-memcache-v1beta2/CHANGELOG.md
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/version.rb
Labels: autorelease: pending, cla: yes

#11108 chore: release google-cloud-recommendation_engine-v1beta1 0.3.1
  google-cloud-recommendation_engine-v1beta1/CHANGELOG.md
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/version.rb
Labels: autorelease: pending, cla: yes

#11112 chore(dialogflow-v2): Undo version 0.6.5 changelog
  google-cloud-dialogflow-v2/CHANGELOG.md
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/version.rb
Labels: cla: yes

#11113 chore: release google-cloud-data_catalog 1.2.0
  google-cloud-data_catalog/CHANGELOG.md
  google-cloud-data_catalog/lib/google/cloud/data_catalog/version.rb
Labels: autorelease: pending, cla: yes

#10919 chore: release google-cloud-service_management-v1 0.3.1
  google-cloud-service_management-v1/CHANGELOG.md
  google-cloud-service_management-v1/lib/google/cloud/service_management/v1/version.rb
Labels: autorelease: pending, cla: yes

#11116 chore: release google-cloud-service_management 1.0.1
  google-cloud-service_management/CHANGELOG.md
  google-cloud-service_management/lib/google/cloud/service_management/version.rb
Labels: autorelease: pending, cla: yes

#10925 chore: release google-cloud-monitoring 1.2.0
  google-cloud-monitoring/CHANGELOG.md
  google-cloud-monitoring/google-cloud-monitoring.gemspec
  google-cloud-monitoring/lib/google/cloud/monitoring/version.rb
  google-cloud-monitoring/synth.py
Labels: autorelease: pending, cla: yes

#11115 chore: release google-cloud-dialogflow-v2 0.7.0
  google-cloud-dialogflow-v2/CHANGELOG.md
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/version.rb
Labels: autorelease: pending, cla: yes

#11118 chore: Set up CI jobs in GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/link-checker.yml
  .github/workflows/pr-labels.yml
  .gitignore
  .toys/.toys.rb
  .toys/ci.rb
Labels: cla: yes

#11127 chore: Fixes to pr-labels job
  .github/workflows/pr-labels.yml
Labels: cla: yes

#11128 chore: Another pr-labels fix
  .github/workflows/pr-labels.yml
Labels: cla: yes

#11129 chore: Try yoshi approver token for pr-labels job
  .github/workflows/pr-labels.yml
Labels: cla: yes

#11131 chore: ci-run kicks off tests from merge ref
  .github/workflows/pr-labels.yml
  .toys/ci.rb
Labels: cla: yes

#11132 chore: Fix typo in ci script
  .toys/ci.rb
Labels: cla: yes

#11133 chore: Another fix for ref-based CI
  .toys/ci.rb
Labels: cla: yes

#11123 chore: add link_transformer class and associated tests to find and transform Github-style md links into YARD links in release script
  Gemfile
  Rakefile
  rakelib/link_transformer.rb
  test/link_transformer_test.rb
  test/test_helper.rb
Labels: cla: yes

#11135 chore: change broken YARD-links to github friendly md links in handwritten libraries
  google-cloud-bigquery/AUTHENTICATION.md
  google-cloud-bigquery/CONTRIBUTING.md
  google-cloud-bigtable/AUTHENTICATION.md
  google-cloud-bigtable/CONTRIBUTING.md
  google-cloud-bigtable/OVERVIEW.md
  google-cloud-compute-v1/README.md
  google-cloud-core/CONTRIBUTING.md
  google-cloud-datastore/AUTHENTICATION.md
  google-cloud-datastore/CONTRIBUTING.md
  google-cloud-datastore/OVERVIEW.md
  google-cloud-debugger/AUTHENTICATION.md
  google-cloud-debugger/CONTRIBUTING.md
  google-cloud-debugger/OVERVIEW.md
  google-cloud-dns/AUTHENTICATION.md
  google-cloud-dns/CONTRIBUTING.md
  google-cloud-dns/OVERVIEW.md
  google-cloud-env/CONTRIBUTING.md
  google-cloud-error_reporting/AUTHENTICATION.md
  google-cloud-error_reporting/CONTRIBUTING.md
  google-cloud-error_reporting/OVERVIEW.md
  google-cloud-errors/CONTRIBUTING.md
  google-cloud-firestore/AUTHENTICATION.md
  google-cloud-firestore/CONTRIBUTING.md
  google-cloud-firestore/OVERVIEW.md
  google-cloud-logging/AUTHENTICATION.md
  google-cloud-logging/CONTRIBUTING.md
  google-cloud-logging/OVERVIEW.md
  google-cloud-pubsub/AUTHENTICATION.md
  google-cloud-pubsub/CONTRIBUTING.md
  google-cloud-pubsub/OVERVIEW.md
  google-cloud-resource_manager/AUTHENTICATION.md
  google-cloud-resource_manager/CONTRIBUTING.md
  google-cloud-resource_manager/OVERVIEW.md
  google-cloud-spanner/AUTHENTICATION.md
  google-cloud-spanner/CONTRIBUTING.md
  google-cloud-spanner/OVERVIEW.md
  google-cloud-storage/AUTHENTICATION.md
  google-cloud-storage/CONTRIBUTING.md
  google-cloud-storage/OVERVIEW.md
  google-cloud-trace/AUTHENTICATION.md
  google-cloud-trace/CONTRIBUTING.md
  google-cloud-trace/OVERVIEW.md
  google-cloud-translate-v2/README.md
  google-cloud/CONTRIBUTING.md
Labels: cla: yes

#11119 [google-cloud-binary_authorization-v1beta1] fix: add Java options to Binaryauthorization protos
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binary_authorization/v1beta1/binauthz_management_service/client.rb
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binaryauthorization/v1beta1/service_services_pb.rb
  google-cloud-binary_authorization-v1beta1/proto_docs/google/cloud/binaryauthorization/v1beta1/service.rb
  google-cloud-binary_authorization-v1beta1/synth.metadata
Labels: cla: yes, context: full

#11122 [google-cloud-firestore-v1] fix: retry RESOURCE_EXHAUSTED errors docs: various documentation improvements
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore/client.rb
  google-cloud-firestore-v1/proto_docs/google/firestore/v1/write.rb
  google-cloud-firestore-v1/synth.metadata
Labels: cla: yes, context: full

#11120 [google-cloud-channel-v1] docs: Update documentation comments to match tone and style with the rest of Cloud documentation. Adding customer level pubsub events for primary domain verification and primary domain change. Enabled support for boolean as
  google-cloud-channel-v1/lib/google/cloud/channel/v1/cloud_channel_service.rb
  google-cloud-channel-v1/lib/google/cloud/channel/v1/cloud_channel_service/client.rb
  google-cloud-channel-v1/lib/google/cloud/channel/v1/common_pb.rb
  google-cloud-channel-v1/lib/google/cloud/channel/v1/entitlements_pb.rb
  google-cloud-channel-v1/lib/google/cloud/channel/v1/service_services_pb.rb
  google-cloud-channel-v1/lib/google/cloud/channel/v1/subscriber_event_pb.rb
  google-cloud-channel-v1/proto_docs/google/cloud/channel/v1/common.rb
  google-cloud-channel-v1/proto_docs/google/cloud/channel/v1/entitlements.rb
  google-cloud-channel-v1/proto_docs/google/cloud/channel/v1/service.rb
  google-cloud-channel-v1/proto_docs/google/cloud/channel/v1/subscriber_event.rb
  google-cloud-channel-v1/synth.metadata
Labels: cla: yes, context: full

#11121 [google-cloud-channel] docs: Update documentation comments to match tone and style with the rest of Cloud documentation. Adding customer level pubsub events for primary domain verification and primary domain change. Enabled support for boolean as an
  google-cloud-channel/lib/google/cloud/channel.rb
  google-cloud-channel/synth.metadata
Labels: cla: yes, context: full

#11136 chore(firestore): Add new region tags to samples
  google-cloud-firestore/samples/acceptance/delete_data_test.rb
  google-cloud-firestore/samples/acceptance/get_data_test.rb
  google-cloud-firestore/samples/acceptance/order_limit_data_test.rb
  google-cloud-firestore/samples/acceptance/paginate_data_test.rb
  google-cloud-firestore/samples/acceptance/query_data_test.rb
  google-cloud-firestore/samples/acceptance/transactions_and_batched_writes_test.rb
  google-cloud-firestore/samples/add_data.rb
  google-cloud-firestore/samples/data_model.rb
  google-cloud-firestore/samples/delete_data.rb
  google-cloud-firestore/samples/distributed_counters.rb
  google-cloud-firestore/samples/get_data.rb
  google-cloud-firestore/samples/order_limit_data.rb
  google-cloud-firestore/samples/paginate_data.rb
  google-cloud-firestore/samples/query_data.rb
  google-cloud-firestore/samples/query_watch.rb
  google-cloud-firestore/samples/quickstart.rb
  google-cloud-firestore/samples/transactions_and_batched_writes.rb
Labels: api: firestore, cla: yes, samples

#11142 chore: Disable CI runs on unsupported Ruby versions
  .toys/ci.rb
  google-cloud-debugger-v2/synth.py
  google-cloud-debugger/README.md
Labels: cla: yes

#11125 [google-cloud-speech-v1p1beta1] feat: Support for spoken punctuation and spoken emojis.
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/cloud_speech_pb.rb
  google-cloud-speech-v1p1beta1/proto_docs/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech-v1p1beta1/proto_docs/google/protobuf/wrappers.rb
  google-cloud-speech-v1p1beta1/synth.metadata
Labels: cla: yes, context: full

#10926 chore: removed unsupported samples
  google-cloud-language/samples/Gemfile
  google-cloud-language/samples/README.md
  google-cloud-language/samples/Rakefile
  google-cloud-language/samples/acceptance/helper.rb
  google-cloud-language/samples/acceptance/language_samples_test.rb
  google-cloud-language/samples/acceptance/quickstart_test.rb
  google-cloud-language/samples/language_samples.rb
  google-cloud-language/samples/quickstart.rb
Labels: cla: yes, samples

#10897 chore (speech): removed unsupported samples
  google-cloud-speech/samples/Gemfile
  google-cloud-speech/samples/README.md
  google-cloud-speech/samples/Rakefile
  google-cloud-speech/samples/acceptance/helper.rb
  google-cloud-speech/samples/acceptance/quickstart_test.rb
  google-cloud-speech/samples/acceptance/speech_samples_test.rb
  google-cloud-speech/samples/quickstart.rb
  google-cloud-speech/samples/resources/Google_Gnome.wav
  google-cloud-speech/samples/resources/brooklyn_bridge.raw
  google-cloud-speech/samples/resources/commercial_mono.wav
  google-cloud-speech/samples/resources/multi.wav
Labels: automerge, cla: yes, samples

#11130 feat(pubsub): Add ordering_key to Topic#publish
  google-cloud-pubsub/acceptance/pubsub/pubsub_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/batch_publisher.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  google-cloud-pubsub/samples/acceptance/subscriptions_test.rb
  google-cloud-pubsub/test/google/cloud/pubsub/topic/message_ordering_test.rb
Labels: api: pubsub, cla: yes

#11144 chore: Support running ci tool on all gems
  .toys/ci.rb
  google-cloud-error_reporting/lib/google/cloud/error_reporting/middleware.rb
  google-cloud-logging/lib/google/cloud/logging/middleware.rb
Labels: cla: yes

#11137 fix(bigquery): Fix Table#time_partitioning_expiration=
  google-cloud-bigquery/acceptance/bigquery/table_reference_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_update_test.rb
Labels: api: bigquery, cla: yes

#11147 chore(firestore): Update style in firestore_transaction samples
  google-cloud-firestore/samples/transactions_and_batched_writes.rb
Labels: api: firestore, cla: yes, samples

#11126 docs(pubsub): Update Subscription#pull docs and samples to recommend return_immediately: false
  google-cloud-pubsub/OVERVIEW.md
  google-cloud-pubsub/acceptance/pubsub_helper.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/samples/acceptance/topics_test.rb
  google-cloud-pubsub/samples/subscriptions.rb
Labels: api: pubsub, cla: yes, samples

#11140 chore: Remove google-cloud-env directory since it has been moved to a separate repo
  .kokoro/continuous/linux/env.cfg
  .kokoro/continuous/osx/env.cfg
  .kokoro/continuous/windows/env.cfg
  .kokoro/nightly/linux/env.cfg
  .kokoro/nightly/osx/env.cfg
  .kokoro/nightly/windows/env.cfg
  .kokoro/release/env.cfg
  .kokoro/samples_latest/linux/env.cfg
  .kokoro/samples_latest/osx/env.cfg
  .kokoro/samples_latest/windows/env.cfg
  RELEASING.md
  google-cloud-bigquery/Gemfile
  google-cloud-bigtable/Gemfile
  google-cloud-core/Gemfile
  google-cloud-datastore/Gemfile
  google-cloud-debugger/Gemfile
  google-cloud-dns/Gemfile
  google-cloud-env/.autotest
  google-cloud-env/.gitignore
  google-cloud-env/.repo-metadata.json
  google-cloud-env/.rubocop.yml
  google-cloud-env/.yardopts
  google-cloud-env/CHANGELOG.md
  google-cloud-env/CODE_OF_CONDUCT.md
  google-cloud-env/CONTRIBUTING.md
  google-cloud-env/Gemfile
  google-cloud-env/LICENSE
  google-cloud-env/README.md
  google-cloud-env/Rakefile
  google-cloud-env/google-cloud-env.gemspec
  google-cloud-env/lib/google-cloud-env.rb
  google-cloud-env/lib/google/cloud/env.rb
  google-cloud-env/lib/google/cloud/env/version.rb
  google-cloud-env/test/google/cloud/env_test.rb
  google-cloud-env/test/helper.rb
  google-cloud-error_reporting/Gemfile
  google-cloud-firestore/Gemfile
  google-cloud-logging/Gemfile
  google-cloud-pubsub/Gemfile
  google-cloud-resource_manager/Gemfile
  google-cloud-spanner/Gemfile
  google-cloud-storage/Gemfile
  google-cloud-trace/Gemfile
  google-cloud-translate-v2/Gemfile
  integration/rails4_app/Gemfile
  integration/rails5_app/Gemfile
  integration/sinatra2_app/Gemfile
  stackdriver-core/Gemfile
  stackdriver/Gemfile
Labels: cla: yes

#11145 chore: Fix release-please tool to handle libraries with no existing releases
  .toys/ci.rb
  .toys/release-please.rb
Labels: cla: yes

#11134 [google-cloud-dataproc-v1] feat: update the Dataproc V1 API client library
  google-cloud-dataproc-v1/gapic_metadata.json
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/paths.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/clusters_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/clusters_services_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/jobs_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/shared_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_template_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_template_service/paths.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_templates_pb.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_templates_services_pb.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/clusters.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/jobs.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/shared.rb
  google-cloud-dataproc-v1/proto_docs/google/cloud/dataproc/v1/workflow_templates.rb
  google-cloud-dataproc-v1/synth.metadata
  google-cloud-dataproc-v1/test/google/cloud/dataproc/v1/cluster_controller_paths_test.rb
  google-cloud-dataproc-v1/test/google/cloud/dataproc/v1/cluster_controller_test.rb
  google-cloud-dataproc-v1/test/google/cloud/dataproc/v1/workflow_template_service_paths_test.rb
Labels: cla: yes, context: full

#11153 docs(pubsub): The immediate: false option is recommended to avoid adverse impacts on the performance of pull operations
  google-cloud-pubsub/OVERVIEW.md
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
Labels: api: pubsub, cla: yes

#11154 chore: Try to get presubmit changed file detection to use the actual expected merge base
  .toys/ci.rb
Labels: cla: yes

#11148 chore: add default assignee for Spanner issues
  .github/blunderbuss.yml
Labels: cla: yes

#11157 chore: Open actions-based release-please PRs from a fork
  .github/workflows/release-please.yml
  .toys/release-please.rb
Labels: cla: yes

#11149 [google-cloud-build-v1] feat: Add fields for Pub/Sub triggers
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/paths.rb
  google-cloud-build-v1/lib/google/devtools/cloudbuild/v1/cloudbuild_pb.rb
  google-cloud-build-v1/proto_docs/google/devtools/cloudbuild/v1/cloudbuild.rb
  google-cloud-build-v1/synth.metadata
  google-cloud-build-v1/test/google/cloud/build/v1/cloud_build_paths_test.rb
Labels: cla: yes, context: full

#11165 chore: Label new release-please PRs for autorelease
  .github/workflows/release-please-label.yml
Labels: cla: yes

#11167 chore: Fix release-please labeler check
  .github/workflows/release-please-label.yml
Labels: cla: yes

#11170 chore: Use pull_request_target for labeling job
  .github/workflows/release-please-label.yml
Labels: cla: yes

#11179 chore: Another release-please label fix
  .github/workflows/release-please-label.yml
Labels: cla: yes

#11194 fix(firestore): Add GRPC::Unknown to retryable errors in Watch::Listener
  google-cloud-firestore/lib/google/cloud/firestore/watch/listener.rb
  google-cloud-firestore/test/google/cloud/firestore/collection_reference/listen_restart_test.rb
  google-cloud-firestore/test/google/cloud/firestore/document_reference/listen_restart_test.rb
Labels: api: firestore, cla: yes

#11190 chore: update the Compute dependency to include the fixed gapic-common
  google-cloud-compute-v1/google-cloud-compute-v1.gemspec
Labels: cla: yes

#10888 feat(bigtable): Add CMEK support
  google-cloud-bigtable/.rubocop.yml
  google-cloud-bigtable/acceptance/bigtable/backup_test.rb
  google-cloud-bigtable/acceptance/bigtable/cluster_test.rb
  google-cloud-bigtable/acceptance/bigtable/encryption_test.rb
  google-cloud-bigtable/acceptance/bigtable/project_test.rb
  google-cloud-bigtable/acceptance/bigtable/table_test.rb
  google-cloud-bigtable/acceptance/bigtable_helper.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/backup.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/cluster.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/encryption_info.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/instance/cluster_map.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/table/cluster_state.rb
  google-cloud-bigtable/samples/acceptance/helper.rb
  google-cloud-bigtable/support/doctest_helper.rb
  google-cloud-bigtable/test/google/cloud/bigtable/backup_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/cluster_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/encryption_info_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance/cluster_map_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance/cluster_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance/create_table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/instance/table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/create_instance_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/create_table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/project/table_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/column_families_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/delete_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/drop_row_range_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table/replication_test.rb
  google-cloud-bigtable/test/google/cloud/bigtable/table_test.rb
  google-cloud-bigtable/test/helper.rb
Labels: api: bigtable, cla: yes

#10878 feat(bigquery): Add support for BIGNUMERIC data type
  google-cloud-bigquery/.rubocop.yml
  google-cloud-bigquery/OVERVIEW.md
  google-cloud-bigquery/acceptance/bigquery/advanced_test.rb
  google-cloud-bigquery/acceptance/bigquery/dataset_reference_test.rb
  google-cloud-bigquery/acceptance/bigquery/dataset_test.rb
  google-cloud-bigquery/acceptance/bigquery/legacy_query_test.rb
  google-cloud-bigquery/acceptance/bigquery/named_params_test.rb
  google-cloud-bigquery/acceptance/bigquery/positional_params_test.rb
  google-cloud-bigquery/acceptance/bigquery/standard_query_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/convert.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/load_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/project.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema/field.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/standard_sql.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table/async_inserter.rb
  google-cloud-bigquery/test/google/cloud/bigquery/convert_to_query_param_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/data_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_insert_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_load_job_schema_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_job_named_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_job_positional_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_named_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_positional_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/external_csv_source_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/external_json_source_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/load_job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_job_named_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_job_positional_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_named_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_positional_params_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/schema_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/standard_sql/array_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/standard_sql/struct_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/standard_sql/value_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_insert_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_schema_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/view_attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/view_test.rb
  google-cloud-bigquery/test/helper.rb
Labels: api: bigquery, cla: yes

#11191 chore: Update kokoro release job
  .kokoro/populate-secrets.sh
  .kokoro/release.cfg
  .kokoro/release.sh
  .kokoro/trampoline_v2.sh
  .toys/kokoro/.lib/releaser.rb
  .toys/kokoro/release.rb
  .toys/release-please.rb
  .trampolinerc
Labels: cla: yes

#11151 [google-cloud-spanner-v1] feat(spanner): add `progress` field to `UpdateDatabaseDdlMetadata`
  google-cloud-spanner-v1/lib/google/spanner/v1/commit_response_pb.rb
  google-cloud-spanner-v1/lib/google/spanner/v1/spanner_pb.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/commit_response.rb
  google-cloud-spanner-v1/proto_docs/google/spanner/v1/spanner.rb
  google-cloud-spanner-v1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#11150 [google-cloud-spanner-admin-database-v1] feat(spanner): add `progress` field to `UpdateDatabaseDdlMetadata`
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/client.rb
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/backup_pb.rb
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/common_pb.rb
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/spanner_database_admin_pb.rb
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/spanner_database_admin_services_pb.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/spanner/admin/database/v1/backup.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/spanner/admin/database/v1/common.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/spanner/admin/database/v1/spanner_database_admin.rb
  google-cloud-spanner-admin-database-v1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#11188 [google-cloud-data_catalog-v1] docs: reformat comments in PolicyTagManager definition
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/policy_tag_manager/client.rb
  google-cloud-data_catalog-v1/lib/google/cloud/datacatalog/v1/policytagmanager_services_pb.rb
  google-cloud-data_catalog-v1/proto_docs/google/cloud/datacatalog/v1/policytagmanager.rb
  google-cloud-data_catalog-v1/synth.metadata
Labels: cla: yes, context: full

#11192 [google-cloud-billing-budgets-v1beta1] feat: Added support for configurable budget time period. fix: Updated some documentation links.
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/budget_model_pb.rb
  google-cloud-billing-budgets-v1beta1/proto_docs/google/cloud/billing/budgets/v1beta1/budget_model.rb
  google-cloud-billing-budgets-v1beta1/proto_docs/google/type/date.rb
  google-cloud-billing-budgets-v1beta1/synth.metadata
Labels: cla: yes, context: full

#11208 chore: add sync repo settings config
  .github/sync-repo-settings.yaml
Labels: cla: yes

#11212 chore: Fix trampolinerc
  .trampolinerc
Labels: cla: yes

#11213 chore: Make integration entrypoint executable
  .kokoro/integration.sh
Labels: cla: yes

#11214 chore: Fixes for nightly job
  .github/sync-repo-settings.yaml
  .toys/ci.rb
  google-cloud-error_reporting/Rakefile
  google-cloud-logging/Rakefile
Labels: cla: yes

#11215 chore: Configure renovate
  .github/renovate.json
Labels: cla: yes

#11220 chore: Tweaks to CI
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yml
  .toys/ci.rb
  google-cloud-bigtable-v2/test/google/cloud/bigtable/v2/bigtable/helpers_test.rb
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/publisher/helpers_test.rb
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/subscriber/helpers_test.rb
Labels: cla: yes

#11221 chore: Backfill samples rake tasks in some of our handwritten gems
  gcloud/.rubocop.yml
  gcloud/Rakefile
  google-cloud-core/.rubocop.yml
  google-cloud-core/Rakefile
  google-cloud-debugger/Rakefile
  google-cloud-dns/Rakefile
  google-cloud-errors/.rubocop.yml
  google-cloud-errors/Rakefile
  google-cloud-resource_manager/Rakefile
  google-cloud-spanner/Rakefile
  google-cloud-trace/Rakefile
  google-cloud-translate-v2/Rakefile
  google-cloud/.rubocop.yml
  google-cloud/Rakefile
  stackdriver-core/.rubocop.yml
  stackdriver-core/Rakefile
  stackdriver/.rubocop.yml
  stackdriver/Rakefile
Labels: cla: yes, samples

#11210 chore: add rubocop config file at the root and add root rubocop rake task
  .rubocop_root.yml
  Gemfile
  Rakefile
  rakelib/link_transformer.rb
  test/link_transformer_test.rb
Labels: cla: yes

#11206 fix(pubsub): Add final flush of pending requests to Subscriber#wait!
  google-cloud-pubsub/acceptance/pubsub/async_test.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/subscriber.rb
Labels: api: pubsub, cla: yes

#11225 feat(bigquery): Add support for mutable clustering configuration
  google-cloud-bigquery/acceptance/bigquery/table_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/load_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_reference_update_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_update_test.rb
Labels: api: bigquery, cla: yes

#11209 [google-cloud-document_ai-v1beta3] feat: add confidence field to the PageAnchor.PageRef in document.proto.
  google-cloud-document_ai-v1beta3/lib/google/cloud/documentai/v1beta3/document_pb.rb
  google-cloud-document_ai-v1beta3/proto_docs/google/cloud/documentai/v1beta3/document.rb
  google-cloud-document_ai-v1beta3/synth.metadata
Labels: cla: yes, context: full

#11231 [CHANGE ME] Re-generated google-cloud-monitoring-dashboard-v1 to pick up changes in the API or client library generator.
  google-cloud-monitoring-dashboard-v1/lib/google/cloud/monitoring/dashboard/v1/dashboards_service/client.rb
  google-cloud-monitoring-dashboard-v1/lib/google/monitoring/dashboard/v1/dashboards_service_services_pb.rb
  google-cloud-monitoring-dashboard-v1/proto_docs/google/monitoring/dashboard/v1/metrics.rb
  google-cloud-monitoring-dashboard-v1/proto_docs/google/monitoring/dashboard/v1/xychart.rb
  google-cloud-monitoring-dashboard-v1/synth.metadata
Labels: cla: yes, context: full

#11232 [google-cloud-speech-v1p1beta1] feat: add webm opus support.
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/cloud_speech_pb.rb
  google-cloud-speech-v1p1beta1/proto_docs/google/cloud/speech/v1p1beta1/cloud_speech.rb
  google-cloud-speech-v1p1beta1/synth.metadata
Labels: cla: yes, context: full

#11227 tests(text_to_speech): Create a simple smoke test
  google-cloud-text_to_speech/acceptance/helper.rb
  google-cloud-text_to_speech/acceptance/tts_smoke_test.rb
Labels: cla: yes

#11228 tests(translate): Create a simple smoke test for Translate V3
  google-cloud-translate/acceptance/translate/translate_test.rb
  google-cloud-translate/acceptance/translate_v2_helper.rb
  google-cloud-translate/acceptance/translate_v2_smoke_test.rb
  google-cloud-translate/acceptance/translate_v3_helper.rb
  google-cloud-translate/acceptance/translate_v3_smoke_test.rb
Labels: api: translate, cla: yes

#11229 tests(dialogflow): Create a simple smoke test
  google-cloud-dialogflow/acceptance/dialogflow_smoke_test.rb
  google-cloud-dialogflow/acceptance/helper.rb
Labels: api: dialogflow, cla: yes

#11230 tests(talent): Create a simple smoke test
  google-cloud-talent/acceptance/helper.rb
  google-cloud-talent/acceptance/talent_smoke_test.rb
Labels: cla: yes

#10903 chore (dialogflow): removed unsupported samples
  google-cloud-dialogflow/samples/Gemfile
  google-cloud-dialogflow/samples/README.md
  google-cloud-dialogflow/samples/Rakefile
  google-cloud-dialogflow/samples/acceptance/context_management_test.rb
  google-cloud-dialogflow/samples/acceptance/detect_intent_audio_test.rb
  google-cloud-dialogflow/samples/acceptance/detect_intent_stream_test.rb
  google-cloud-dialogflow/samples/acceptance/detect_intent_texts_test.rb
  google-cloud-dialogflow/samples/acceptance/entity_management_test.rb
  google-cloud-dialogflow/samples/acceptance/entity_type_management_test.rb
  google-cloud-dialogflow/samples/acceptance/helper.rb
  google-cloud-dialogflow/samples/acceptance/intent_management_test.rb
  google-cloud-dialogflow/samples/acceptance/session_entity_type_management_test.rb
  google-cloud-dialogflow/samples/context_management.rb
  google-cloud-dialogflow/samples/detect_intent_audio.rb
  google-cloud-dialogflow/samples/detect_intent_stream.rb
  google-cloud-dialogflow/samples/detect_intent_texts.rb
  google-cloud-dialogflow/samples/entity_management.rb
  google-cloud-dialogflow/samples/entity_type_management.rb
  google-cloud-dialogflow/samples/intent_management.rb
  google-cloud-dialogflow/samples/resources/230pm.wav
  google-cloud-dialogflow/samples/resources/RoomReservation.zip
  google-cloud-dialogflow/samples/resources/book_a_room.wav
  google-cloud-dialogflow/samples/resources/half_an_hour.wav
  google-cloud-dialogflow/samples/resources/mountain_view.wav
  google-cloud-dialogflow/samples/resources/today.wav
  google-cloud-dialogflow/samples/resources/two_people.wav
  google-cloud-dialogflow/samples/session_entity_type_management.rb
Labels: cla: yes, samples

#10908 chore (translate): removed unsupported samples
  google-cloud-translate/samples/Gemfile
  google-cloud-translate/samples/README.md
  google-cloud-translate/samples/Rakefile
  google-cloud-translate/samples/v2/acceptance/helper.rb
  google-cloud-translate/samples/v2/acceptance/translate_detect_language_test.rb
  google-cloud-translate/samples/v2/acceptance/translate_list_codes_test.rb
  google-cloud-translate/samples/v2/acceptance/translate_list_language_names_test.rb
  google-cloud-translate/samples/v2/acceptance/translate_text_with_model_test.rb
  google-cloud-translate/samples/v2/acceptance/translate_translate_text_test.rb
  google-cloud-translate/samples/v2/translate_detect_language.rb
  google-cloud-translate/samples/v2/translate_list_codes.rb
  google-cloud-translate/samples/v2/translate_list_language_names.rb
  google-cloud-translate/samples/v2/translate_text_with_model.rb
  google-cloud-translate/samples/v2/translate_translate_text.rb
  google-cloud-translate/samples/v3/acceptance/batch_translate_text_test.rb
  google-cloud-translate/samples/v3/acceptance/batch_translate_text_with_glossary_and_model_test.rb
  google-cloud-translate/samples/v3/acceptance/batch_translate_text_with_glossary_test.rb
  google-cloud-translate/samples/v3/acceptance/batch_translate_text_with_model_test.rb
  google-cloud-translate/samples/v3/acceptance/create_glossary_test.rb
  google-cloud-translate/samples/v3/acceptance/delete_glossary_test.rb
  google-cloud-translate/samples/v3/acceptance/detect_language_test.rb
  google-cloud-translate/samples/v3/acceptance/get_glossary_test.rb
  google-cloud-translate/samples/v3/acceptance/get_supported_languages_for_target_test.rb
  google-cloud-translate/samples/v3/acceptance/get_supported_languages_test.rb
  google-cloud-translate/samples/v3/acceptance/helper.rb
  google-cloud-translate/samples/v3/acceptance/list_glossary_test.rb
  google-cloud-translate/samples/v3/acceptance/translate_text_test.rb
  google-cloud-translate/samples/v3/acceptance/translate_text_with_glossary_and_model_test.rb
  google-cloud-translate/samples/v3/acceptance/translate_text_with_glossary_test.rb
  google-cloud-translate/samples/v3/acceptance/translate_text_with_model_test.rb
  google-cloud-translate/samples/v3/batch_translate_text.rb
  google-cloud-translate/samples/v3/batch_translate_text_with_glossary.rb
  google-cloud-translate/samples/v3/batch_translate_text_with_glossary_and_model.rb
  google-cloud-translate/samples/v3/batch_translate_text_with_model.rb
  google-cloud-translate/samples/v3/create_glossary.rb
  google-cloud-translate/samples/v3/delete_glossary.rb
  google-cloud-translate/samples/v3/detect_language.rb
  google-cloud-translate/samples/v3/get_glossary.rb
  google-cloud-translate/samples/v3/get_supported_languages.rb
  google-cloud-translate/samples/v3/get_supported_languages_for_target.rb
  google-cloud-translate/samples/v3/list_glossary.rb
  google-cloud-translate/samples/v3/translate_text.rb
  google-cloud-translate/samples/v3/translate_text_with_glossary.rb
  google-cloud-translate/samples/v3/translate_text_with_glossary_and_model.rb
  google-cloud-translate/samples/v3/translate_text_with_model.rb
Labels: cla: yes, samples

#10910 chore (TTS): removed unsupported samples
  google-cloud-text_to_speech/samples/Gemfile
  google-cloud-text_to_speech/samples/README.md
  google-cloud-text_to_speech/samples/Rakefile
  google-cloud-text_to_speech/samples/acceptance/list_voices_test.rb
  google-cloud-text_to_speech/samples/acceptance/quickstart_test.rb
  google-cloud-text_to_speech/samples/acceptance/synthesize_file_test.rb
  google-cloud-text_to_speech/samples/acceptance/synthesize_text_test.rb
  google-cloud-text_to_speech/samples/list_voices.rb
  google-cloud-text_to_speech/samples/quickstart.rb
  google-cloud-text_to_speech/samples/resources/hello.ssml
  google-cloud-text_to_speech/samples/resources/hello.txt
  google-cloud-text_to_speech/samples/synthesize_file.rb
  google-cloud-text_to_speech/samples/synthesize_text.rb
Labels: cla: yes, samples

#11084 chore: removed unsupported samples [talent solution]
  google-cloud-talent/samples/.rubocop.yml
  google-cloud-talent/samples/Gemfile
  google-cloud-talent/samples/Rakefile
  google-cloud-talent/samples/acceptance/helper.rb
  google-cloud-talent/samples/acceptance/talent_test.rb
  google-cloud-talent/samples/autocomplete_job_title.rb
  google-cloud-talent/samples/batch_create_jobs.rb
  google-cloud-talent/samples/batch_delete_jobs.rb
  google-cloud-talent/samples/batch_update_jobs.rb
  google-cloud-talent/samples/commute_search.rb
  google-cloud-talent/samples/create_client_event.rb
  google-cloud-talent/samples/create_company.rb
  google-cloud-talent/samples/create_job.rb
  google-cloud-talent/samples/create_job_custom_attributes.rb
  google-cloud-talent/samples/create_tenant.rb
  google-cloud-talent/samples/custom_ranking_search.rb
  google-cloud-talent/samples/delete_company.rb
  google-cloud-talent/samples/delete_job.rb
  google-cloud-talent/samples/delete_tenant.rb
  google-cloud-talent/samples/get_company.rb
  google-cloud-talent/samples/get_job.rb
  google-cloud-talent/samples/get_tenant.rb
  google-cloud-talent/samples/histogram_search.rb
  google-cloud-talent/samples/list_companies.rb
  google-cloud-talent/samples/list_jobs.rb
  google-cloud-talent/samples/list_tenants.rb
Labels: cla: yes, samples

#11235 chore: Document the new CI system and configs
  .toys/ci.rb
  CI.md
Labels: cla: yes

#11243 docs(storage): Update IAMCredentialsService#sign_service_account_blob examples
  google-cloud-storage/acceptance/storage/bucket_generate_signed_post_policy_v4_test.rb
  google-cloud-storage/acceptance/storage/bucket_post_object_v2_test.rb
  google-cloud-storage/acceptance/storage/signed_url_v2_test.rb
  google-cloud-storage/acceptance/storage/signed_url_v4_test.rb
  google-cloud-storage/lib/google/cloud/storage/bucket.rb
  google-cloud-storage/lib/google/cloud/storage/file.rb
  google-cloud-storage/lib/google/cloud/storage/project.rb
Labels: api: storage, cla: yes
