Repository googleapis/google-cloud-ruby, pull requests merged in 2021-11, with the labels that each got.

#14495 chore: Various updates to Cloud RAD yaml generation
  .toys/cloud-rad.rb
  Gemfile
  google-cloud-pubsub/.yardopts-cloudrad
  google-cloud-pubsub/Gemfile
  google-cloud-pubsub/Rakefile
  google-cloud-pubsub/lib/google/cloud/pubsub/subscription.rb
  google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb
  template/default/fulldoc/yaml/setup.rb
  template/default/layout/yaml/format.rb
  template/default/layout/yaml/method.rb
  template/default/layout/yaml/setup.rb
  template/default/toc/yaml/setup.rb
Labels: cla: yes

#15687 chore: Migrate monitoring and workflows wrappers to owlbot
  .toys/owlbot.rb
  google-cloud-monitoring/.OwlBot.yaml
  google-cloud-monitoring/.owlbot-manifest.json
  google-cloud-monitoring/.owlbot.rb
  google-cloud-monitoring/synth.metadata
  google-cloud-monitoring/synth.py
  google-cloud-workflows/.OwlBot.yaml
  google-cloud-workflows/.owlbot-manifest.json
  google-cloud-workflows/.owlbot.rb
  google-cloud-workflows/.repo-metadata.json
  google-cloud-workflows/README.md
  google-cloud-workflows/google-cloud-workflows.gemspec
  google-cloud-workflows/synth.metadata
  google-cloud-workflows/synth.py
Labels: cla: yes

#15696 chore: Remove owlbot migrate script and fix owlbot script for non-piper case
  .github/workflows/owlbot-migrate.yml
  .toys/.data/owlbot-config-template.erb
  .toys/owlbot-migrate.rb
  .toys/owlbot.rb
Labels: cla: yes

#16033 chore: Rework and simplify new library script now that synth is gone
  .github/workflows/new-library.yml
  .toys/.data/owlbot-config-template.erb
  .toys/.data/owlbot-script-template.erb
  .toys/.data/synth-gapic-template.erb
  .toys/.data/synth-wrapper-template.erb
  .toys/gen-client.rb
  .toys/new-library.rb
  .toys/owlbot.rb
Labels: cla: yes

#16039 chore(compute-v1): Switch from autosynth to owlbot
  google-cloud-compute-v1/.OwlBot.yaml
  google-cloud-compute-v1/.owlbot.rb
  google-cloud-compute-v1/synth.metadata
Labels: cla: yes

#14481 chore(firestore): Update CONTRIBUTING.md
  google-cloud-firestore/CONTRIBUTING.md
Labels: cla: yes, api: firestore

#16052 chore: Various updates to cloudrad
  template/default/fulldoc/yaml/setup.rb
  template/default/layout/yaml/_method.erb
  template/default/layout/yaml/_object.erb
  template/default/layout/yaml/format.rb
  template/default/layout/yaml/method.rb
Labels: cla: yes

#16056 chore: Handle aliases and attributes better in CloudRAD
  template/default/layout/yaml/_method.erb
  template/default/layout/yaml/method.rb
Labels: cla: yes

#16060 chore: Switch cloud-rad build script and templates to ruby-common-tools repo
  .toys/cloud-rad.rb
  .toys/release.rb
Labels: cla: yes

#15699 feat(bigquery): Add session support
  google-cloud-bigquery/.rubocop.yml
  google-cloud-bigquery/acceptance/bigquery/advanced_test.rb
  google-cloud-bigquery/acceptance/bigquery/dataset_reference_test.rb
  google-cloud-bigquery/acceptance/bigquery/dataset_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/project.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb
  google-cloud-bigquery/support/doctest_helper.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_query_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/project_query_test.rb
  google-cloud-bigquery/test/helper.rb
Labels: cla: yes, api: bigquery

#16087 chore: Support staging multiple libraries via toys-cloud-rad
  .toys/cloud-rad.rb
  .toys/release.rb
Labels: cla: yes

#14482 Add storage transfer service quickstart
  google-cloud-storage_transfer/samples/Gemfile
  google-cloud-storage_transfer/samples/Rakefile
  google-cloud-storage_transfer/samples/acceptance/helper.rb
  google-cloud-storage_transfer/samples/acceptance/quickstart_test.rb
  google-cloud-storage_transfer/samples/quickstart.rb
Labels: cla: yes

#16086 samples(storage): update region tags for samples
  google-cloud-storage/samples/acls.rb
Labels: cla: yes, api: storage, samples

#16092 chore: Support running tests and producing a combined pull request from owlbot
  .github/workflows/owlbot.yml
  .toys/owlbot.rb
Labels: cla: yes

#16091 samples(storage): remove old unused tags
  google-cloud-storage/samples/acls.rb
Labels: cla: yes, api: storage, samples

#13456 feat(spanner): wrapper to create generated admin database client.
  google-cloud-spanner/acceptance/spanner/database_client_test.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/database.rb
  google-cloud-spanner/test/google/cloud/spanner/admin/database/client_config_test.rb
  google-cloud-spanner/test/google/cloud/spanner/database/client_test.rb
Labels: cla: yes, api: spanner

#16080 feat(spanner): add admin instance wrapper
  google-cloud-spanner/acceptance/instance_client_test.rb
  google-cloud-spanner/lib/google/cloud/spanner/admin/instance.rb
  google-cloud-spanner/test/google/cloud/spanner/admin/instance/client_config_test.rb
  google-cloud-spanner/test/google/cloud/spanner/admin/instance/client_test.rb
Labels: cla: yes, api: spanner

#16050 chore(firestore): Add samples/CONTRIBUTING.md
  google-cloud-firestore/samples/CONTRIBUTING.md
Labels: cla: yes, api: firestore, samples

#16095 fix(storage): Changing the test email id.
  google-cloud-storage/acceptance/storage/bucket_acl_test.rb
  google-cloud-storage/acceptance/storage/bucket_default_acl_test.rb
  google-cloud-storage/acceptance/storage/bucket_requester_pays_test.rb
  google-cloud-storage/acceptance/storage/bucket_uniform_bucket_level_access_test.rb
  google-cloud-storage/acceptance/storage/file_acl_test.rb
  google-cloud-storage/samples/acceptance/acls_test.rb
Labels: cla: yes, api: storage

#16090 samples(storage): add sample to print bucket notification
  google-cloud-storage/samples/Gemfile
  google-cloud-storage/samples/acceptance/helper.rb
  google-cloud-storage/samples/acceptance/notification_test.rb
  google-cloud-storage/samples/storage_print_pubsub_bucket_notification.rb
Labels: cla: yes, api: storage, samples

#16100 chore: Support backfilling cloud rad
  .kokoro/backfill-rad.cfg
  .kokoro/backfill-rad.sh
  .toys/rad/backfill.rb
Labels: cla: yes

#16102 chore(rad): Use a different environment variable name for rad backfill input
  .kokoro/backfill-rad.sh
  .trampolinerc
Labels: cla: yes

#16103 chore(rad): Fix permissions of the backfill entrypoint
  .kokoro/backfill-rad.sh
Labels: cla: yes

#16104 chore(rad): Fix for older git versions
  .toys/rad/backfill.rb
Labels: cla: yes
