Repository googleapis/google-cloud-ruby, pull requests merged in 2021-01, with the labels that each got.

#8414 chore: release google-cloud-pubsub-v1 0.2.0
  google-cloud-pubsub-v1/CHANGELOG.md
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/version.rb
Labels: autorelease: pending, cla: yes

#8416 feat(spanner): optionalize `credentials` when using cloud spanner emulator host
  google-cloud-spanner/lib/google/cloud/spanner.rb
  google-cloud-spanner/test/google/cloud/spanner_test.rb
Labels: api: spanner, cla: yes

#8412 chore: release google-cloud-firestore 2.4.1
  google-cloud-firestore/CHANGELOG.md
  google-cloud-firestore/lib/google/cloud/firestore/version.rb
Labels: autorelease: pending, cla: yes

#8408 make column family cf1 name consistent in the documentation
  google-cloud-bigtable/OVERVIEW.md
  google-cloud-bigtable/README.md
  google-cloud-bigtable/lib/google/cloud/bigtable/instance.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_entry.rb
  google-cloud-bigtable/lib/google/cloud/bigtable/mutation_operations.rb
Labels: api: bigtable, cla: yes

#8583 [google-analytics-admin-v1alpha] chore: put markdown table in a codeblock
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service/client.rb
  google-analytics-admin-v1alpha/proto_docs/google/analytics/admin/v1alpha/analytics_admin.rb
  google-analytics-admin-v1alpha/synth.metadata
Labels: cla: yes, context: full

#8588 feat(bigquery): Replace google-api-client with google-apis-bigquery_v2
  google-cloud-bigquery/google-cloud-bigquery.gemspec
Labels: api: bigquery, cla: yes

#8586 feat(storage): Replace google-api-client with specific client gems
  google-cloud-storage/google-cloud-storage.gemspec
Labels: api: storage, cla: yes

#8590 feat(dns): Replace google-api-client with google-apis-dns_v1
  google-cloud-dns/google-cloud-dns.gemspec
Labels: api: dns, cla: yes

#8591 feat(resource_manager): Replace google-api-client with google-apis-cloudresourcemanager_v1
  google-cloud-resource_manager/google-cloud-resource_manager.gemspec
Labels: api: cloudresourcemanager, cla: yes

#8592 chore: Replace google-api-client with google-apis-core in google-cloud-errors
  google-cloud-core/Gemfile
  google-cloud-errors/Gemfile
Labels: cla: yes

#8173 fix(bigtable-v2): Update keepalive configuration
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/bigtable/helpers.rb
  google-cloud-bigtable-v2/test/google/cloud/bigtable/v2/bigtable/helpers_test.rb
Labels: api: bigtable, cla: yes

#8597 feat: Initial generation of google-cloud-retail
  .kokoro/continuous/linux/retail.cfg
  .kokoro/continuous/osx/retail.cfg
  .kokoro/continuous/windows/retail.cfg
  .kokoro/nightly/linux/retail.cfg
  .kokoro/nightly/osx/retail.cfg
  .kokoro/nightly/windows/retail.cfg
  .kokoro/release/retail.cfg
  .kokoro/samples_latest/linux/retail.cfg
  .kokoro/samples_latest/osx/retail.cfg
  .kokoro/samples_latest/windows/retail.cfg
  google-cloud-retail/.gitignore
  google-cloud-retail/.repo-metadata.json
  google-cloud-retail/.rubocop.yml
  google-cloud-retail/.yardopts
  google-cloud-retail/AUTHENTICATION.md
  google-cloud-retail/CHANGELOG.md
  google-cloud-retail/Gemfile
  google-cloud-retail/LICENSE.md
  google-cloud-retail/README.md
  google-cloud-retail/Rakefile
  google-cloud-retail/google-cloud-retail.gemspec
  google-cloud-retail/lib/google-cloud-retail.rb
  google-cloud-retail/lib/google/cloud/retail.rb
  google-cloud-retail/lib/google/cloud/retail/version.rb
  google-cloud-retail/synth.metadata
  google-cloud-retail/synth.py
  google-cloud-retail/test/google/cloud/retail/client_test.rb
  google-cloud-retail/test/google/cloud/retail/version_test.rb
  google-cloud-retail/test/helper.rb
Labels: cla: yes

#8596 feat: Initial generation of google-cloud-channel
  .kokoro/continuous/linux/channel.cfg
  .kokoro/continuous/osx/channel.cfg
  .kokoro/continuous/windows/channel.cfg
  .kokoro/nightly/linux/channel.cfg
  .kokoro/nightly/osx/channel.cfg
  .kokoro/nightly/windows/channel.cfg
  .kokoro/release/channel.cfg
  .kokoro/samples_latest/linux/channel.cfg
  .kokoro/samples_latest/osx/channel.cfg
  .kokoro/samples_latest/windows/channel.cfg
  google-cloud-channel/.gitignore
  google-cloud-channel/.repo-metadata.json
  google-cloud-channel/.rubocop.yml
  google-cloud-channel/.yardopts
  google-cloud-channel/AUTHENTICATION.md
  google-cloud-channel/CHANGELOG.md
  google-cloud-channel/Gemfile
  google-cloud-channel/LICENSE.md
  google-cloud-channel/README.md
  google-cloud-channel/Rakefile
  google-cloud-channel/google-cloud-channel.gemspec
  google-cloud-channel/lib/google-cloud-channel.rb
  google-cloud-channel/lib/google/cloud/channel.rb
  google-cloud-channel/lib/google/cloud/channel/version.rb
  google-cloud-channel/synth.metadata
  google-cloud-channel/synth.py
  google-cloud-channel/test/google/cloud/channel/client_test.rb
  google-cloud-channel/test/google/cloud/channel/version_test.rb
  google-cloud-channel/test/helper.rb
Labels: cla: yes

#8599 chore: start tracking obsolete files
  google-cloud-channel-v1/synth.metadata
Labels: cla: yes, context: full

#8602 chore: start tracking obsolete files
  google-cloud-retail/synth.metadata
Labels: cla: yes, context: full

#8601 chore: start tracking obsolete files
  google-cloud-retail-v2/synth.metadata
Labels: cla: yes, context: full

#8600 chore: start tracking obsolete files
  google-cloud-channel/synth.metadata
Labels: cla: yes, context: full

#8604 Release google-cloud-channel-v1 0.1.0
  google-cloud-channel-v1/CHANGELOG.md
  google-cloud-channel-v1/lib/google/cloud/channel/v1/version.rb
Labels: autorelease: pending, cla: yes

#8603 Release google-cloud-retail-v2 0.1.0
  google-cloud-retail-v2/CHANGELOG.md
  google-cloud-retail-v2/lib/google/cloud/retail/v2/version.rb
Labels: autorelease: pending, cla: yes

#8607 Release google-cloud-retail 0.1.0
  google-cloud-retail/CHANGELOG.md
  google-cloud-retail/lib/google/cloud/retail/version.rb
Labels: autorelease: pending, cla: yes

#8606 Release google-cloud-channel 0.1.0
  google-cloud-channel/CHANGELOG.md
  google-cloud-channel/lib/google/cloud/channel/version.rb
Labels: autorelease: pending, cla: yes

#8605 chore: removed .class to fix NoSuchMethod exceptio error
  google-cloud-dialogflow/samples/intent_management.rb
Labels: cla: yes

#8609 chore: Update api name for cloud channel in synth scripts
  google-cloud-channel-v1/synth.py
  google-cloud-channel/synth.py
Labels: cla: yes

#8594 chore: release google-cloud-dns 0.34.0
  google-cloud-dns/CHANGELOG.md
  google-cloud-dns/lib/google/cloud/dns/version.rb
Labels: autorelease: pending, cla: yes

#8593 chore: release google-cloud-resource_manager 0.35.0
  google-cloud-resource_manager/CHANGELOG.md
  google-cloud-resource_manager/lib/google/cloud/resource_manager/version.rb
Labels: autorelease: pending, cla: yes

#8598 chore: release google-cloud-bigtable-v2 0.1.3
  google-cloud-bigtable-v2/CHANGELOG.md
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/version.rb
Labels: autorelease: pending, cla: yes

#8409 chore: release google-cloud-pubsub 2.3.1
  google-cloud-pubsub/CHANGELOG.md
  google-cloud-pubsub/lib/google/cloud/pubsub/version.rb
Labels: autorelease: pending, cla: yes

#8587 chore: release google-cloud-bigquery 1.26.0
  google-cloud-bigquery/CHANGELOG.md
  google-cloud-bigquery/lib/google/cloud/bigquery/version.rb
Labels: autorelease: pending, cla: yes

#8595 chore: release google-cloud-storage 1.30.0
  google-cloud-storage/CHANGELOG.md
  google-cloud-storage/lib/google/cloud/storage/version.rb
Labels: autorelease: pending, cla: yes

#8585 chore: release google-cloud-bigtable 2.2.1
  google-cloud-bigtable/CHANGELOG.md
  google-cloud-bigtable/lib/google/cloud/bigtable/version.rb
Labels: autorelease: pending, cla: yes

#8769 [CHANGE ME] Re-generated grafeas-v1 to pick up changes in the API or client library generator.
  grafeas-v1/lib/grafeas/v1/grafeas/client.rb
  grafeas-v1/synth.metadata
Labels: cla: yes, context: none

#8768 [CHANGE ME] Re-generated google-iam-v1beta to pick up changes in the API or client library generator.
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/client.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/operations.rb
  google-iam-v1beta/synth.metadata
Labels: cla: yes, context: none

#8767 [CHANGE ME] Re-generated google-iam-credentials-v1 to pick up changes in the API or client library generator.
  google-iam-credentials-v1/lib/google/iam/credentials/v1/iam_credentials/client.rb
  google-iam-credentials-v1/synth.metadata
Labels: cla: yes, context: none

#8765 [CHANGE ME] Re-generated google-cloud-workflows-v1beta to pick up changes in the API or client library generator.
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows/client.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows/operations.rb
  google-cloud-workflows-v1beta/synth.metadata
Labels: cla: yes, context: none

#8764 [CHANGE ME] Re-generated google-cloud-workflows-executions-v1beta to pick up changes in the API or client library generator.
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/executions/client.rb
  google-cloud-workflows-executions-v1beta/synth.metadata
Labels: cla: yes, context: none

#8762 [CHANGE ME] Re-generated google-cloud-web_security_scanner-v1beta to pick up changes in the API or client library generator.
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/web_security_scanner/v1beta/web_security_scanner/client.rb
  google-cloud-web_security_scanner-v1beta/synth.metadata
Labels: cla: yes, context: none

#8761 [CHANGE ME] Re-generated google-cloud-web_security_scanner-v1 to pick up changes in the API or client library generator.
  google-cloud-web_security_scanner-v1/lib/google/cloud/web_security_scanner/v1/web_security_scanner/client.rb
  google-cloud-web_security_scanner-v1/synth.metadata
Labels: cla: yes, context: none

#8759 [CHANGE ME] Re-generated google-cloud-web_risk-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1beta1/lib/google/cloud/web_risk/v1beta1/web_risk_service/client.rb
  google-cloud-web_risk-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8758 [CHANGE ME] Re-generated google-cloud-web_risk-v1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1/lib/google/cloud/web_risk/v1/web_risk_service/client.rb
  google-cloud-web_risk-v1/synth.metadata
Labels: cla: yes, context: none

#8756 [CHANGE ME] Re-generated google-cloud-vision-v1p3beta1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/image_annotator/client.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/image_annotator/operations.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/product_search/client.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/product_search/operations.rb
  google-cloud-vision-v1p3beta1/synth.metadata
Labels: cla: yes, context: none

#8755 [CHANGE ME] Re-generated google-cloud-vision-v1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search/operations.rb
  google-cloud-vision-v1/synth.metadata
Labels: context: none

#8753 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p2beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1p2beta1/synth.metadata
Labels: cla: yes, context: none

#8752 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#8751 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1beta2/synth.metadata
Labels: cla: yes, context: none

#8750 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1/synth.metadata
Labels: cla: yes, context: none

#8748 [CHANGE ME] Re-generated google-cloud-translate-v3 to pick up changes in the API or client library generator.
  google-cloud-translate-v3/lib/google/cloud/translate/v3/translation_service/client.rb
  google-cloud-translate-v3/lib/google/cloud/translate/v3/translation_service/operations.rb
  google-cloud-translate-v3/synth.metadata
Labels: cla: yes, context: none

#8747 [CHANGE ME] Re-generated google-cloud-trace-v2 to pick up changes in the API or client library generator.
  google-cloud-trace-v2/lib/google/cloud/trace/v2/trace_service/client.rb
  google-cloud-trace-v2/synth.metadata
Labels: cla: yes, context: none

#8746 [CHANGE ME] Re-generated google-cloud-trace-v1 to pick up changes in the API or client library generator.
  google-cloud-trace-v1/lib/google/cloud/trace/v1/trace_service/client.rb
  google-cloud-trace-v1/synth.metadata
Labels: cla: yes, context: none

#8744 [CHANGE ME] Re-generated google-cloud-text_to_speech-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/text_to_speech/v1beta1/text_to_speech/client.rb
  google-cloud-text_to_speech-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8743 [CHANGE ME] Re-generated google-cloud-text_to_speech-v1 to pick up changes in the API or client library generator.
  google-cloud-text_to_speech-v1/lib/google/cloud/text_to_speech/v1/text_to_speech/client.rb
  google-cloud-text_to_speech-v1/synth.metadata
Labels: cla: yes, context: none

#8741 [CHANGE ME] Re-generated google-cloud-tasks-v2beta3 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta3/lib/google/cloud/tasks/v2beta3/cloud_tasks/client.rb
  google-cloud-tasks-v2beta3/synth.metadata
Labels: cla: yes, context: none

#8740 [CHANGE ME] Re-generated google-cloud-tasks-v2beta2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/cloud_tasks/client.rb
  google-cloud-tasks-v2beta2/synth.metadata
Labels: cla: yes, context: none

#8739 [CHANGE ME] Re-generated google-cloud-tasks-v2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/cloud_tasks/client.rb
  google-cloud-tasks-v2/synth.metadata
Labels: cla: yes, context: none

#8737 [CHANGE ME] Re-generated google-cloud-talent-v4beta1 to pick up changes in the API or client library generator.
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/application_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/company_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/completion/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/event_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/job_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/job_service/operations.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/profile_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/tenant_service/client.rb
  google-cloud-talent-v4beta1/synth.metadata
Labels: cla: yes, context: none

#8736 [CHANGE ME] Re-generated google-cloud-talent-v4 to pick up changes in the API or client library generator.
  google-cloud-talent-v4/lib/google/cloud/talent/v4/company_service/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/completion/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/event_service/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/job_service/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/job_service/operations.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/tenant_service/client.rb
  google-cloud-talent-v4/synth.metadata
Labels: cla: yes, context: none

#8734 [CHANGE ME] Re-generated google-cloud-speech-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/speech/client.rb
  google-cloud-speech-v1p1beta1/lib/google/cloud/speech/v1p1beta1/speech/operations.rb
  google-cloud-speech-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#8733 [CHANGE ME] Re-generated google-cloud-speech-v1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1/lib/google/cloud/speech/v1/speech/client.rb
  google-cloud-speech-v1/lib/google/cloud/speech/v1/speech/operations.rb
  google-cloud-speech-v1/synth.metadata
Labels: cla: yes, context: none

#8732 [CHANGE ME] Re-generated google-cloud-spanner-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/spanner/client.rb
  google-cloud-spanner-v1/synth.metadata
Labels: cla: yes, context: none

#8731 [CHANGE ME] Re-generated google-cloud-spanner-admin-instance-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/client.rb
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/operations.rb
  google-cloud-spanner-admin-instance-v1/synth.metadata
Labels: cla: yes, context: none

#8730 [CHANGE ME] Re-generated google-cloud-spanner-admin-database-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/client.rb
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/operations.rb
  google-cloud-spanner-admin-database-v1/synth.metadata
Labels: cla: yes, context: none

#8728 [CHANGE ME] Re-generated google-cloud-service_management-v1 to pick up changes in the API or client library generator.
  google-cloud-service_management-v1/lib/google/cloud/service_management/v1/service_manager/client.rb
  google-cloud-service_management-v1/lib/google/cloud/service_management/v1/service_manager/operations.rb
  google-cloud-service_management-v1/synth.metadata
Labels: cla: yes, context: none

#8726 [CHANGE ME] Re-generated google-cloud-service_directory-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/lookup_service/client.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service/client.rb
  google-cloud-service_directory-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8725 [CHANGE ME] Re-generated google-cloud-service_directory-v1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1/lib/google/cloud/service_directory/v1/lookup_service/client.rb
  google-cloud-service_directory-v1/lib/google/cloud/service_directory/v1/registration_service/client.rb
  google-cloud-service_directory-v1/synth.metadata
Labels: cla: yes, context: none

#8723 [CHANGE ME] Re-generated google-cloud-service_control-v1 to pick up changes in the API or client library generator.
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/quota_controller/client.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/service_controller/client.rb
  google-cloud-service_control-v1/synth.metadata
Labels: cla: yes, context: none

#8721 [CHANGE ME] Re-generated google-cloud-security_center-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/security_center/client.rb
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/security_center/operations.rb
  google-cloud-security_center-v1p1beta1/synth.metadata
Labels: cla: yes, context: none

#8720 [CHANGE ME] Re-generated google-cloud-security_center-v1 to pick up changes in the API or client library generator.
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/security_center/client.rb
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/security_center/operations.rb
  google-cloud-security_center-v1/synth.metadata
Labels: cla: yes, context: none

#8718 [CHANGE ME] Re-generated google-cloud-security-private_ca-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-security-private_ca-v1beta1/lib/google/cloud/security/private_ca/v1beta1/certificate_authority_service/client.rb
  google-cloud-security-private_ca-v1beta1/lib/google/cloud/security/private_ca/v1beta1/certificate_authority_service/operations.rb
  google-cloud-security-private_ca-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8716 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8715 [CHANGE ME] Re-generated google-cloud-secret_manager-v1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes, context: none

#8713 [CHANGE ME] Re-generated google-cloud-scheduler-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1beta1/lib/google/cloud/scheduler/v1beta1/cloud_scheduler/client.rb
  google-cloud-scheduler-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8712 [CHANGE ME] Re-generated google-cloud-scheduler-v1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1/lib/google/cloud/scheduler/v1/cloud_scheduler/client.rb
  google-cloud-scheduler-v1/synth.metadata
Labels: cla: yes, context: none

#8710 [CHANGE ME] Re-generated google-cloud-retail-v2 to pick up changes in the API or client library generator.
  google-cloud-retail-v2/lib/google/cloud/retail/v2/catalog_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/prediction_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/product_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/product_service/operations.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/user_event_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/user_event_service/operations.rb
  google-cloud-retail-v2/synth.metadata
Labels: cla: yes, context: none

#8708 [CHANGE ME] Re-generated google-cloud-redis-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/client.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/operations.rb
  google-cloud-redis-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8707 [CHANGE ME] Re-generated google-cloud-redis-v1 to pick up changes in the API or client library generator.
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/client.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/operations.rb
  google-cloud-redis-v1/synth.metadata
Labels: cla: yes, context: none

#8705 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes, context: none

#8703 [CHANGE ME] Re-generated google-cloud-recommendation_engine-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/catalog_service/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/catalog_service/operations.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/prediction_api_key_registry/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/prediction_service/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/user_event_service/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/user_event_service/operations.rb
  google-cloud-recommendation_engine-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8701 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise-v1beta1/lib/google/cloud/recaptcha_enterprise/v1beta1/recaptcha_enterprise_service/client.rb
  google-cloud-recaptcha_enterprise-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8700 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise-v1 to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise-v1/lib/google/cloud/recaptcha_enterprise/v1/recaptcha_enterprise_service/client.rb
  google-cloud-recaptcha_enterprise-v1/synth.metadata
Labels: cla: yes, context: none

#8699 [CHANGE ME] Re-generated google-cloud-pubsub-v1 to pick up changes in the API or client library generator.
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/iam_policy/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/schema_service/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber/client.rb
  google-cloud-pubsub-v1/synth.metadata
Labels: cla: yes, context: none

#8697 [CHANGE ME] Re-generated google-cloud-policy_troubleshooter-v1 to pick up changes in the API or client library generator.
  google-cloud-policy_troubleshooter-v1/lib/google/cloud/policy_troubleshooter/v1/iam_checker/client.rb
  google-cloud-policy_troubleshooter-v1/synth.metadata
Labels: cla: yes, context: none

#8695 [CHANGE ME] Re-generated google-cloud-phishing_protection-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-phishing_protection-v1beta1/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_service/client.rb
  google-cloud-phishing_protection-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8693 [CHANGE ME] Re-generated google-cloud-os_login-v1beta to pick up changes in the API or client library generator.
  google-cloud-os_login-v1beta/lib/google/cloud/os_login/v1beta/os_login_service/client.rb
  google-cloud-os_login-v1beta/synth.metadata
Labels: cla: yes, context: none

#8692 [CHANGE ME] Re-generated google-cloud-os_login-v1 to pick up changes in the API or client library generator.
  google-cloud-os_login-v1/lib/google/cloud/os_login/v1/os_login_service/client.rb
  google-cloud-os_login-v1/synth.metadata
Labels: cla: yes, context: none

#8690 [CHANGE ME] Re-generated google-cloud-os_config-v1 to pick up changes in the API or client library generator.
  google-cloud-os_config-v1/lib/google/cloud/os_config/v1/os_config_service/client.rb
  google-cloud-os_config-v1/synth.metadata
Labels: cla: yes, context: none

#8688 [CHANGE ME] Re-generated google-cloud-notebooks-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-notebooks-v1beta1/lib/google/cloud/notebooks/v1beta1/notebook_service/client.rb
  google-cloud-notebooks-v1beta1/lib/google/cloud/notebooks/v1beta1/notebook_service/operations.rb
  google-cloud-notebooks-v1beta1/synth.metadata
Labels: cla: yes, context: partial

#8686 [CHANGE ME] Re-generated google-cloud-monitoring-v3 to pick up changes in the API or client library generator.
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/alert_policy_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/group_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/metric_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/notification_channel_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/service_monitoring_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/uptime_check_service/client.rb
  google-cloud-monitoring-v3/synth.metadata
Labels: cla: yes, context: none

#8685 [CHANGE ME] Re-generated google-cloud-monitoring-dashboard-v1 to pick up changes in the API or client library generator.
  google-cloud-monitoring-dashboard-v1/lib/google/cloud/monitoring/dashboard/v1/dashboards_service/client.rb
  google-cloud-monitoring-dashboard-v1/synth.metadata
Labels: cla: yes, context: none

#8683 [CHANGE ME] Re-generated google-cloud-memcache-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/cloud_memcache/client.rb
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/cloud_memcache/operations.rb
  google-cloud-memcache-v1beta2/synth.metadata
Labels: cla: yes, context: none

#8681 [CHANGE ME] Re-generated google-cloud-media_translation-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-media_translation-v1beta1/lib/google/cloud/media_translation/v1beta1/speech_translation_service/client.rb
  google-cloud-media_translation-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8679 [CHANGE ME] Re-generated google-cloud-managed_identities-v1 to pick up changes in the API or client library generator.
  google-cloud-managed_identities-v1/lib/google/cloud/managed_identities/v1/managed_identities_service/client.rb
  google-cloud-managed_identities-v1/lib/google/cloud/managed_identities/v1/managed_identities_service/operations.rb
  google-cloud-managed_identities-v1/synth.metadata
Labels: cla: yes, context: none

#8678 [CHANGE ME] Re-generated google-cloud-logging-v2 to pick up changes in the API or client library generator.
  google-cloud-logging-v2/lib/google/cloud/logging/v2/config_service/client.rb
  google-cloud-logging-v2/lib/google/cloud/logging/v2/logging_service/client.rb
  google-cloud-logging-v2/lib/google/cloud/logging/v2/metrics_service/client.rb
  google-cloud-logging-v2/synth.metadata
Labels: cla: yes, context: none

#8676 [CHANGE ME] Re-generated google-cloud-language-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes, context: none

#8675 [CHANGE ME] Re-generated google-cloud-language-v1 to pick up changes in the API or client library generator.
  google-cloud-language-v1/lib/google/cloud/language/v1/language_service/client.rb
  google-cloud-language-v1/synth.metadata
Labels: cla: yes, context: none

#8673 [CHANGE ME] Re-generated google-cloud-kms-v1 to pick up changes in the API or client library generator.
  google-cloud-kms-v1/lib/google/cloud/kms/v1/iam_policy/client.rb
  google-cloud-kms-v1/lib/google/cloud/kms/v1/key_management_service/client.rb
  google-cloud-kms-v1/synth.metadata
Labels: cla: yes, context: none

#8671 [CHANGE ME] Re-generated google-cloud-iot-v1 to pick up changes in the API or client library generator.
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager/client.rb
  google-cloud-iot-v1/synth.metadata
Labels: cla: yes, context: none

#8669 [CHANGE ME] Re-generated google-cloud-gaming-v1 to pick up changes in the API or client library generator.
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_clusters_service/client.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_clusters_service/operations.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_configs_service/client.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_configs_service/operations.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_deployments_service/client.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_deployments_service/operations.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/realms_service/client.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/realms_service/operations.rb
  google-cloud-gaming-v1/synth.metadata
Labels: cla: yes, context: none

#8667 [CHANGE ME] Re-generated google-cloud-functions-v1 to pick up changes in the API or client library generator.
  google-cloud-functions-v1/lib/google/cloud/functions/v1/cloud_functions_service/client.rb
  google-cloud-functions-v1/lib/google/cloud/functions/v1/cloud_functions_service/operations.rb
  google-cloud-functions-v1/synth.metadata
Labels: cla: yes, context: none

#8666 [CHANGE ME] Re-generated google-cloud-firestore-v1 to pick up changes in the API or client library generator.
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore/client.rb
  google-cloud-firestore-v1/synth.metadata
Labels: cla: yes, context: partial

#8665 [CHANGE ME] Re-generated google-cloud-firestore-admin-v1 to pick up changes in the API or client library generator.
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin/client.rb
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin/operations.rb
  google-cloud-firestore-admin-v1/synth.metadata
Labels: cla: yes, context: none

#8664 [CHANGE ME] Re-generated google-cloud-error_reporting-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/error_group_service/client.rb
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/error_stats_service/client.rb
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/report_errors_service/client.rb
  google-cloud-error_reporting-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8662 [CHANGE ME] Re-generated google-cloud-document_ai-v1beta3 to pick up changes in the API or client library generator.
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service/client.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service/operations.rb
  google-cloud-document_ai-v1beta3/synth.metadata
Labels: cla: yes, context: none

#8660 [CHANGE ME] Re-generated google-cloud-dlp-v2 to pick up changes in the API or client library generator.
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/dlp_service/client.rb
  google-cloud-dlp-v2/synth.metadata
Labels: cla: yes, context: none

#8658 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/contexts/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environments/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/sessions/client.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes, context: none

#8657 [CHANGE ME] Re-generated google-cloud-debugger-v2 to pick up changes in the API or client library generator.
  google-cloud-debugger-v2/lib/google/cloud/debugger/v2/controller/client.rb
  google-cloud-debugger-v2/lib/google/cloud/debugger/v2/debugger/client.rb
  google-cloud-debugger-v2/synth.metadata
Labels: cla: yes, context: none

#8656 [CHANGE ME] Re-generated google-cloud-datastore-v1 to pick up changes in the API or client library generator.
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1/datastore/client.rb
  google-cloud-datastore-v1/synth.metadata
Labels: cla: yes, context: none

#8655 [CHANGE ME] Re-generated google-cloud-datastore-admin-v1 to pick up changes in the API or client library generator.
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/datastore_admin/client.rb
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/datastore_admin/operations.rb
  google-cloud-datastore-admin-v1/synth.metadata
Labels: cla: yes, context: none

#8653 [CHANGE ME] Re-generated google-cloud-dataproc-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/cluster_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/cluster_controller/operations.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller/operations.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_template_service/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_template_service/operations.rb
  google-cloud-dataproc-v1beta2/synth.metadata
Labels: cla: yes, context: none

#8652 [CHANGE ME] Re-generated google-cloud-dataproc-v1 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/autoscaling_policy_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/operations.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/operations.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_template_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_template_service/operations.rb
  google-cloud-dataproc-v1/synth.metadata
Labels: cla: yes, context: none

#8650 [CHANGE ME] Re-generated google-cloud-data_labeling-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-data_labeling-v1beta1/lib/google/cloud/data_labeling/v1beta1/data_labeling_service/client.rb
  google-cloud-data_labeling-v1beta1/lib/google/cloud/data_labeling/v1beta1/data_labeling_service/operations.rb
  google-cloud-data_labeling-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8648 [CHANGE ME] Re-generated google-cloud-data_catalog-v1 to pick up changes in the API or client library generator.
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/data_catalog/client.rb
  google-cloud-data_catalog-v1/synth.metadata
Labels: cla: yes, context: none

#8646 [CHANGE ME] Re-generated google-cloud-container_analysis-v1 to pick up changes in the API or client library generator.
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/container_analysis/client.rb
  google-cloud-container_analysis-v1/synth.metadata
Labels: cla: yes, context: none

#8644 [CHANGE ME] Re-generated google-cloud-container-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-container-v1beta1/lib/google/cloud/container/v1beta1/cluster_manager/client.rb
  google-cloud-container-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8643 [CHANGE ME] Re-generated google-cloud-container-v1 to pick up changes in the API or client library generator.
  google-cloud-container-v1/lib/google/cloud/container/v1/cluster_manager/client.rb
  google-cloud-container-v1/synth.metadata
Labels: cla: yes, context: none

#8639 [CHANGE ME] Re-generated google-cloud-build-v1 to pick up changes in the API or client library generator.
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/client.rb
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/operations.rb
  google-cloud-build-v1/synth.metadata
Labels: cla: yes, context: none

#8637 [CHANGE ME] Re-generated google-cloud-binary_authorization-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binary_authorization/v1beta1/binauthz_management_service/client.rb
  google-cloud-binary_authorization-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8635 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/client.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes, context: none

#8633 [CHANGE ME] Re-generated google-cloud-billing-budgets-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/budget_service/client.rb
  google-cloud-billing-budgets-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8631 [CHANGE ME] Re-generated google-cloud-bigquery-storage-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/big_query_read/client.rb
  google-cloud-bigquery-storage-v1/synth.metadata
Labels: cla: yes, context: none

#8629 [CHANGE ME] Re-generated google-cloud-bigquery-reservation-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-reservation-v1/lib/google/cloud/bigquery/reservation/v1/reservation_service/client.rb
  google-cloud-bigquery-reservation-v1/synth.metadata
Labels: cla: yes, context: none

#8627 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer-v1/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service/client.rb
  google-cloud-bigquery-data_transfer-v1/synth.metadata
Labels: cla: yes, context: none

#8625 [CHANGE ME] Re-generated google-cloud-bigquery-connection-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-connection-v1/lib/google/cloud/bigquery/connection/v1/connection_service/client.rb
  google-cloud-bigquery-connection-v1/synth.metadata
Labels: cla: yes, context: none

#8623 [CHANGE ME] Re-generated google-cloud-automl-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/automl/client.rb
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/automl/operations.rb
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/prediction_service/client.rb
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/prediction_service/operations.rb
  google-cloud-automl-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8622 [CHANGE ME] Re-generated google-cloud-automl-v1 to pick up changes in the API or client library generator.
  google-cloud-automl-v1/lib/google/cloud/automl/v1/automl/client.rb
  google-cloud-automl-v1/lib/google/cloud/automl/v1/automl/operations.rb
  google-cloud-automl-v1/lib/google/cloud/automl/v1/prediction_service/client.rb
  google-cloud-automl-v1/lib/google/cloud/automl/v1/prediction_service/operations.rb
  google-cloud-automl-v1/synth.metadata
Labels: cla: yes, context: none

#8620 [CHANGE ME] Re-generated google-cloud-assured_workloads-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/assured_workloads_service/client.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/assured_workloads_service/operations.rb
  google-cloud-assured_workloads-v1beta1/synth.metadata
Labels: cla: yes, context: none

#8618 [CHANGE ME] Re-generated google-cloud-asset-v1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/operations.rb
  google-cloud-asset-v1/synth.metadata
Labels: cla: yes, context: none

#8616 [CHANGE ME] Re-generated google-cloud-artifact_registry-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-artifact_registry-v1beta2/lib/google/cloud/artifact_registry/v1beta2/artifact_registry/client.rb
  google-cloud-artifact_registry-v1beta2/lib/google/cloud/artifact_registry/v1beta2/artifact_registry/operations.rb
  google-cloud-artifact_registry-v1beta2/synth.metadata
Labels: cla: yes, context: none

#8614 [CHANGE ME] Re-generated google-cloud-access_approval-v1 to pick up changes in the API or client library generator.
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/access_approval/client.rb
  google-cloud-access_approval-v1/synth.metadata
Labels: cla: yes, context: none

#8613 [CHANGE ME] Re-generated google-analytics-data-v1alpha to pick up changes in the API or client library generator.
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/client.rb
  google-analytics-data-v1alpha/synth.metadata
Labels: cla: yes, context: none

#8766 [CHANGE ME] Re-generated google-cloud-workflows to pick up changes in the API or client library generator.
  google-cloud-workflows/lib/google/cloud/workflows.rb
  google-cloud-workflows/lib/google/cloud/workflows/executions.rb
  google-cloud-workflows/synth.metadata
Labels: cla: yes, context: none

#8763 [CHANGE ME] Re-generated google-cloud-web_security_scanner to pick up changes in the API or client library generator.
  google-cloud-web_security_scanner/lib/google/cloud/web_security_scanner.rb
  google-cloud-web_security_scanner/synth.metadata
Labels: cla: yes, context: none

#8760 [CHANGE ME] Re-generated google-cloud-web_risk to pick up changes in the API or client library generator.
  google-cloud-web_risk/lib/google/cloud/web_risk.rb
  google-cloud-web_risk/synth.metadata
Labels: cla: yes, context: none

#8757 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/lib/google/cloud/vision.rb
  google-cloud-vision/synth.metadata
Labels: cla: yes, context: none

#8754 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/lib/google/cloud/video_intelligence.rb
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes, context: none

#8749 [CHANGE ME] Re-generated google-cloud-translate to pick up changes in the API or client library generator.
  google-cloud-translate/lib/google/cloud/translate.rb
  google-cloud-translate/synth.metadata
Labels: cla: yes, context: none

#8745 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/lib/google/cloud/text_to_speech.rb
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes, context: none

#8742 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/lib/google/cloud/tasks.rb
  google-cloud-tasks/synth.metadata
Labels: cla: yes, context: none

#8738 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/lib/google/cloud/talent.rb
  google-cloud-talent/synth.metadata
Labels: cla: yes, context: none

#8735 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/lib/google/cloud/speech.rb
  google-cloud-speech/synth.metadata
Labels: cla: yes, context: none

#8729 [CHANGE ME] Re-generated google-cloud-service_management to pick up changes in the API or client library generator.
  google-cloud-service_management/lib/google/cloud/service_management.rb
  google-cloud-service_management/synth.metadata
Labels: cla: yes, context: none

#8727 [CHANGE ME] Re-generated google-cloud-service_directory to pick up changes in the API or client library generator.
  google-cloud-service_directory/lib/google/cloud/service_directory.rb
  google-cloud-service_directory/synth.metadata
Labels: cla: yes, context: none

#8724 [CHANGE ME] Re-generated google-cloud-service_control to pick up changes in the API or client library generator.
  google-cloud-service_control/lib/google/cloud/service_control.rb
  google-cloud-service_control/synth.metadata
Labels: cla: yes, context: none

#8722 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/lib/google/cloud/security_center.rb
  google-cloud-security_center/synth.metadata
Labels: cla: yes, context: none

#8719 [CHANGE ME] Re-generated google-cloud-security-private_ca to pick up changes in the API or client library generator.
  google-cloud-security-private_ca/lib/google/cloud/security/private_ca.rb
  google-cloud-security-private_ca/synth.metadata
Labels: cla: yes, context: none

#8717 [CHANGE ME] Re-generated google-cloud-secret_manager to pick up changes in the API or client library generator.
  google-cloud-secret_manager/lib/google/cloud/secret_manager.rb
  google-cloud-secret_manager/synth.metadata
Labels: cla: yes, context: none

#8714 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/lib/google/cloud/scheduler.rb
  google-cloud-scheduler/synth.metadata
Labels: cla: yes, context: none

#8711 [CHANGE ME] Re-generated google-cloud-retail to pick up changes in the API or client library generator.
  google-cloud-retail/lib/google/cloud/retail.rb
  google-cloud-retail/synth.metadata
Labels: cla: yes, context: none

#8709 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/lib/google/cloud/redis.rb
  google-cloud-redis/synth.metadata
Labels: cla: yes, context: none

#8706 [CHANGE ME] Re-generated google-cloud-recommender to pick up changes in the API or client library generator.
  google-cloud-recommender/lib/google/cloud/recommender.rb
  google-cloud-recommender/synth.metadata
Labels: cla: yes, context: none

#8704 [CHANGE ME] Re-generated google-cloud-recommendation_engine to pick up changes in the API or client library generator.
  google-cloud-recommendation_engine/lib/google/cloud/recommendation_engine.rb
  google-cloud-recommendation_engine/synth.metadata
Labels: cla: yes, context: none

#8702 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/lib/google/cloud/recaptcha_enterprise.rb
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes, context: none
