Repository googleapis/google-cloud-ruby, pull requests merged in 2021-08, with the labels that each got.

#13284 chore: preformat cloudrad docs
  .toys/kokoro/release.rb
  Rakefile
  template/default/layout/yaml/_method.erb
  template/default/layout/yaml/_object.erb
  template/default/layout/yaml/format.rb
  template/default/layout/yaml/method.rb
  template/default/layout/yaml/setup.rb
Labels: cla: yes

#13287 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/validation_result.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes

#13286 [CHANGE ME] Re-generated google-cloud-binary_authorization-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-binary_authorization-v1beta1/proto_docs/google/cloud/binaryauthorization/v1beta1/resources.rb
  google-cloud-binary_authorization-v1beta1/synth.metadata
Labels: cla: yes

#13291 chore: Fix linkinator for new libraries
  .toys/ci.rb
Labels: cla: yes

#13288 [CHANGE ME] Re-generated google-cloud-retail-v2 to pick up changes in the API or client library generator.
  google-cloud-retail-v2/lib/google/cloud/retail/v2/search_service/client.rb
  google-cloud-retail-v2/proto_docs/google/cloud/retail/v2/search_service.rb
  google-cloud-retail-v2/synth.metadata
Labels: cla: yes

#13280 docs(vision-v1): Added code snippets illustrating how to call each rpc method
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search/operations.rb
  google-cloud-vision-v1/snippets/Gemfile
  google-cloud-vision-v1/snippets/image_annotator/async_batch_annotate_files.rb
  google-cloud-vision-v1/snippets/image_annotator/async_batch_annotate_images.rb
  google-cloud-vision-v1/snippets/image_annotator/batch_annotate_files.rb
  google-cloud-vision-v1/snippets/image_annotator/batch_annotate_images.rb
  google-cloud-vision-v1/snippets/product_search/add_product_to_product_set.rb
  google-cloud-vision-v1/snippets/product_search/create_product.rb
  google-cloud-vision-v1/snippets/product_search/create_product_set.rb
  google-cloud-vision-v1/snippets/product_search/create_reference_image.rb
  google-cloud-vision-v1/snippets/product_search/delete_product.rb
  google-cloud-vision-v1/snippets/product_search/delete_product_set.rb
  google-cloud-vision-v1/snippets/product_search/delete_reference_image.rb
  google-cloud-vision-v1/snippets/product_search/get_product.rb
  google-cloud-vision-v1/snippets/product_search/get_product_set.rb
  google-cloud-vision-v1/snippets/product_search/get_reference_image.rb
  google-cloud-vision-v1/snippets/product_search/import_product_sets.rb
  google-cloud-vision-v1/snippets/product_search/list_product_sets.rb
  google-cloud-vision-v1/snippets/product_search/list_products.rb
  google-cloud-vision-v1/snippets/product_search/list_products_in_product_set.rb
  google-cloud-vision-v1/snippets/product_search/list_reference_images.rb
  google-cloud-vision-v1/snippets/product_search/purge_products.rb
  google-cloud-vision-v1/snippets/product_search/remove_product_from_product_set.rb
  google-cloud-vision-v1/snippets/product_search/update_product.rb
  google-cloud-vision-v1/snippets/product_search/update_product_set.rb
  google-cloud-vision-v1/synth.metadata
Labels: cla: yes

#13300 [CHANGE ME] Re-generated google-cloud-retail-v2 to pick up changes in the API or client library generator.
  google-cloud-retail-v2/proto_docs/google/cloud/retail/v2/search_service.rb
  google-cloud-retail-v2/synth.metadata
Labels: cla: yes

#13299 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environment_services_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environments/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_pb.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/versions/client.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/environment.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/session.rb
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/version.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes

#13244 [CHANGE ME] Re-generated google-cloud-retail to pick up changes in the API or client library generator.
  google-cloud-retail/.rubocop.yml
  google-cloud-retail/google-cloud-retail.gemspec
  google-cloud-retail/lib/google/cloud/retail.rb
  google-cloud-retail/synth.metadata
  google-cloud-retail/synth.py
  google-cloud-retail/test/google/cloud/retail/client_test.rb
Labels: cla: yes, context: partial

#13310 [CHANGE ME] Re-generated google-cloud-kms-v1 to pick up changes in the API or client library generator.
  google-cloud-kms-v1/gapic_metadata.json
  google-cloud-kms-v1/lib/google/cloud/kms/v1/key_management_service/client.rb
  google-cloud-kms-v1/lib/google/cloud/kms/v1/resources_pb.rb
  google-cloud-kms-v1/lib/google/cloud/kms/v1/service_pb.rb
  google-cloud-kms-v1/lib/google/cloud/kms/v1/service_services_pb.rb
  google-cloud-kms-v1/proto_docs/google/cloud/kms/v1/resources.rb
  google-cloud-kms-v1/proto_docs/google/cloud/kms/v1/service.rb
  google-cloud-kms-v1/synth.metadata
  google-cloud-kms-v1/test/google/cloud/kms/v1/key_management_service_test.rb
Labels: cla: yes

#13311 [CHANGE ME] Re-generated google-cloud-video-transcoder-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-video-transcoder-v1beta1/lib/google/cloud/video/transcoder/v1beta1/resources_pb.rb
  google-cloud-video-transcoder-v1beta1/proto_docs/google/cloud/video/transcoder/v1beta1/resources.rb
  google-cloud-video-transcoder-v1beta1/synth.metadata
Labels: cla: yes

#13159 feat(bigquery): Add support for GEOGRAPHY type
  google-cloud-bigquery/acceptance/bigquery/advanced_test.rb
  google-cloud-bigquery/acceptance/bigquery/dataset_test.rb
  google-cloud-bigquery/acceptance/bigquery/named_params_test.rb
  google-cloud-bigquery/acceptance/bigquery/positional_params_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/convert.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/project.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema/field.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table/async_inserter.rb
  google-cloud-bigquery/test/google/cloud/bigquery/convert_to_query_param_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/data_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/external_csv_source_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/external_json_source_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/load_job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/query_job_data_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/schema_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_schema_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/table_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/view_attributes_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/view_test.rb
  google-cloud-bigquery/test/helper.rb
Labels: cla: yes, api: bigquery

#13448 [CHANGE ME] Re-generated grafeas-v1 to pick up changes in the API or client library generator.
  grafeas-v1/grafeas-v1.gemspec
  grafeas-v1/lib/grafeas/v1/grafeas/client.rb
  grafeas-v1/synth.metadata
Labels: cla: yes

#13447 [CHANGE ME] Re-generated google-iam-v1beta to pick up changes in the API or client library generator.
  google-iam-v1beta/google-iam-v1beta.gemspec
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/client.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/operations.rb
  google-iam-v1beta/synth.metadata
Labels: cla: yes

#13446 [CHANGE ME] Re-generated google-iam-credentials-v1 to pick up changes in the API or client library generator.
  google-iam-credentials-v1/google-iam-credentials-v1.gemspec
  google-iam-credentials-v1/lib/google/iam/credentials/v1/iam_credentials/client.rb
  google-iam-credentials-v1/synth.metadata
Labels: cla: yes

#13445 [CHANGE ME] Re-generated google-cloud-workflows-v1beta to pick up changes in the API or client library generator.
  google-cloud-workflows-v1beta/google-cloud-workflows-v1beta.gemspec
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows/client.rb
  google-cloud-workflows-v1beta/lib/google/cloud/workflows/v1beta/workflows/operations.rb
  google-cloud-workflows-v1beta/synth.metadata
Labels: cla: yes

#13444 [CHANGE ME] Re-generated google-cloud-workflows-v1 to pick up changes in the API or client library generator.
  google-cloud-workflows-v1/google-cloud-workflows-v1.gemspec
  google-cloud-workflows-v1/lib/google/cloud/workflows/v1/workflows/client.rb
  google-cloud-workflows-v1/lib/google/cloud/workflows/v1/workflows/operations.rb
  google-cloud-workflows-v1/synth.metadata
Labels: cla: yes

#13443 [CHANGE ME] Re-generated google-cloud-workflows-executions-v1beta to pick up changes in the API or client library generator.
  google-cloud-workflows-executions-v1beta/google-cloud-workflows-executions-v1beta.gemspec
  google-cloud-workflows-executions-v1beta/lib/google/cloud/workflows/executions/v1beta/executions/client.rb
  google-cloud-workflows-executions-v1beta/synth.metadata
Labels: cla: yes

#13442 [CHANGE ME] Re-generated google-cloud-web_security_scanner-v1beta to pick up changes in the API or client library generator.
  google-cloud-web_security_scanner-v1beta/google-cloud-web_security_scanner-v1beta.gemspec
  google-cloud-web_security_scanner-v1beta/lib/google/cloud/web_security_scanner/v1beta/web_security_scanner/client.rb
  google-cloud-web_security_scanner-v1beta/synth.metadata
Labels: cla: yes

#13441 [CHANGE ME] Re-generated google-cloud-web_security_scanner-v1 to pick up changes in the API or client library generator.
  google-cloud-web_security_scanner-v1/google-cloud-web_security_scanner-v1.gemspec
  google-cloud-web_security_scanner-v1/lib/google/cloud/web_security_scanner/v1/web_security_scanner/client.rb
  google-cloud-web_security_scanner-v1/synth.metadata
Labels: cla: yes

#13440 [CHANGE ME] Re-generated google-cloud-web_risk-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1beta1/google-cloud-web_risk-v1beta1.gemspec
  google-cloud-web_risk-v1beta1/lib/google/cloud/web_risk/v1beta1/web_risk_service/client.rb
  google-cloud-web_risk-v1beta1/synth.metadata
Labels: cla: yes

#13439 [CHANGE ME] Re-generated google-cloud-web_risk-v1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1/google-cloud-web_risk-v1.gemspec
  google-cloud-web_risk-v1/lib/google/cloud/web_risk/v1/web_risk_service/client.rb
  google-cloud-web_risk-v1/synth.metadata
Labels: cla: yes

#13438 [CHANGE ME] Re-generated google-cloud-vpc_access-v1 to pick up changes in the API or client library generator.
  google-cloud-vpc_access-v1/google-cloud-vpc_access-v1.gemspec
  google-cloud-vpc_access-v1/lib/google/cloud/vpc_access/v1/vpc_access_service/client.rb
  google-cloud-vpc_access-v1/lib/google/cloud/vpc_access/v1/vpc_access_service/operations.rb
  google-cloud-vpc_access-v1/synth.metadata
Labels: cla: yes

#13437 [CHANGE ME] Re-generated google-cloud-vision-v1p3beta1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1p3beta1/google-cloud-vision-v1p3beta1.gemspec
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/image_annotator/client.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/image_annotator/operations.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/product_search/client.rb
  google-cloud-vision-v1p3beta1/lib/google/cloud/vision/v1p3beta1/product_search/operations.rb
  google-cloud-vision-v1p3beta1/synth.metadata
Labels: cla: yes

#13436 [CHANGE ME] Re-generated google-cloud-vision-v1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1/google-cloud-vision-v1.gemspec
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/image_annotator/operations.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search/client.rb
  google-cloud-vision-v1/lib/google/cloud/vision/v1/product_search/operations.rb
  google-cloud-vision-v1/synth.metadata
Labels: cla: yes

#13435 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p2beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p2beta1/google-cloud-video_intelligence-v1p2beta1.gemspec
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1p2beta1/lib/google/cloud/video_intelligence/v1p2beta1/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1p2beta1/synth.metadata
Labels: cla: yes

#13434 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p1beta1/google-cloud-video_intelligence-v1p1beta1.gemspec
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1p1beta1/lib/google/cloud/video_intelligence/v1p1beta1/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1p1beta1/synth.metadata
Labels: cla: yes

#13433 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1beta2/google-cloud-video_intelligence-v1beta2.gemspec
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1beta2/lib/google/cloud/video_intelligence/v1beta2/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1beta2/synth.metadata
Labels: cla: yes

#13432 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1/google-cloud-video_intelligence-v1.gemspec
  google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/video_intelligence_service/client.rb
  google-cloud-video_intelligence-v1/lib/google/cloud/video_intelligence/v1/video_intelligence_service/operations.rb
  google-cloud-video_intelligence-v1/synth.metadata
Labels: cla: yes

#13431 [CHANGE ME] Re-generated google-cloud-video-transcoder-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-video-transcoder-v1beta1/google-cloud-video-transcoder-v1beta1.gemspec
  google-cloud-video-transcoder-v1beta1/lib/google/cloud/video/transcoder/v1beta1/transcoder_service/client.rb
  google-cloud-video-transcoder-v1beta1/synth.metadata
Labels: cla: yes

#13430 [CHANGE ME] Re-generated google-cloud-translate-v3 to pick up changes in the API or client library generator.
  google-cloud-translate-v3/google-cloud-translate-v3.gemspec
  google-cloud-translate-v3/lib/google/cloud/translate/v3/translation_service/client.rb
  google-cloud-translate-v3/lib/google/cloud/translate/v3/translation_service/operations.rb
  google-cloud-translate-v3/synth.metadata
Labels: cla: yes

#13429 [CHANGE ME] Re-generated google-cloud-trace-v2 to pick up changes in the API or client library generator.
  google-cloud-trace-v2/google-cloud-trace-v2.gemspec
  google-cloud-trace-v2/lib/google/cloud/trace/v2/trace_service/client.rb
  google-cloud-trace-v2/synth.metadata
Labels: cla: yes

#13428 [CHANGE ME] Re-generated google-cloud-trace-v1 to pick up changes in the API or client library generator.
  google-cloud-trace-v1/google-cloud-trace-v1.gemspec
  google-cloud-trace-v1/lib/google/cloud/trace/v1/trace_service/client.rb
  google-cloud-trace-v1/synth.metadata
Labels: cla: yes

#13427 [CHANGE ME] Re-generated google-cloud-tpu-v1 to pick up changes in the API or client library generator.
  google-cloud-tpu-v1/google-cloud-tpu-v1.gemspec
  google-cloud-tpu-v1/lib/google/cloud/tpu/v1/tpu/client.rb
  google-cloud-tpu-v1/lib/google/cloud/tpu/v1/tpu/operations.rb
  google-cloud-tpu-v1/synth.metadata
Labels: cla: yes

#13426 [CHANGE ME] Re-generated google-cloud-text_to_speech-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-text_to_speech-v1beta1/google-cloud-text_to_speech-v1beta1.gemspec
  google-cloud-text_to_speech-v1beta1/lib/google/cloud/text_to_speech/v1beta1/text_to_speech/client.rb
  google-cloud-text_to_speech-v1beta1/synth.metadata
Labels: cla: yes

#13425 [CHANGE ME] Re-generated google-cloud-text_to_speech-v1 to pick up changes in the API or client library generator.
  google-cloud-text_to_speech-v1/google-cloud-text_to_speech-v1.gemspec
  google-cloud-text_to_speech-v1/lib/google/cloud/text_to_speech/v1/text_to_speech/client.rb
  google-cloud-text_to_speech-v1/synth.metadata
Labels: cla: yes

#13424 [CHANGE ME] Re-generated google-cloud-tasks-v2beta3 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta3/google-cloud-tasks-v2beta3.gemspec
  google-cloud-tasks-v2beta3/lib/google/cloud/tasks/v2beta3/cloud_tasks/client.rb
  google-cloud-tasks-v2beta3/synth.metadata
Labels: cla: yes

#13423 [CHANGE ME] Re-generated google-cloud-tasks-v2beta2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta2/google-cloud-tasks-v2beta2.gemspec
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/cloud_tasks/client.rb
  google-cloud-tasks-v2beta2/synth.metadata
Labels: cla: yes

#13422 [CHANGE ME] Re-generated google-cloud-tasks-v2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2/google-cloud-tasks-v2.gemspec
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/cloud_tasks/client.rb
  google-cloud-tasks-v2/synth.metadata
Labels: cla: yes

#13421 [CHANGE ME] Re-generated google-cloud-talent-v4beta1 to pick up changes in the API or client library generator.
  google-cloud-talent-v4beta1/google-cloud-talent-v4beta1.gemspec
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/application_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/company_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/completion/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/event_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/job_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/job_service/operations.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/profile_service/client.rb
  google-cloud-talent-v4beta1/lib/google/cloud/talent/v4beta1/tenant_service/client.rb
  google-cloud-talent-v4beta1/synth.metadata
Labels: cla: yes

#13420 [CHANGE ME] Re-generated google-cloud-talent-v4 to pick up changes in the API or client library generator.
  google-cloud-talent-v4/google-cloud-talent-v4.gemspec
  google-cloud-talent-v4/lib/google/cloud/talent/v4/company_service/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/completion/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/event_service/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/job_service/client.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/job_service/operations.rb
  google-cloud-talent-v4/lib/google/cloud/talent/v4/tenant_service/client.rb
  google-cloud-talent-v4/synth.metadata
Labels: cla: yes

#13417 [CHANGE ME] Re-generated google-cloud-spanner-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-v1/google-cloud-spanner-v1.gemspec
  google-cloud-spanner-v1/lib/google/cloud/spanner/v1/spanner/client.rb
  google-cloud-spanner-v1/synth.metadata
Labels: cla: yes

#13416 [CHANGE ME] Re-generated google-cloud-spanner-admin-instance-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-admin-instance-v1/google-cloud-spanner-admin-instance-v1.gemspec
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/client.rb
  google-cloud-spanner-admin-instance-v1/lib/google/cloud/spanner/admin/instance/v1/instance_admin/operations.rb
  google-cloud-spanner-admin-instance-v1/synth.metadata
Labels: cla: yes

#13415 [CHANGE ME] Re-generated google-cloud-spanner-admin-database-v1 to pick up changes in the API or client library generator.
  google-cloud-spanner-admin-database-v1/google-cloud-spanner-admin-database-v1.gemspec
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/client.rb
  google-cloud-spanner-admin-database-v1/lib/google/cloud/spanner/admin/database/v1/database_admin/operations.rb
  google-cloud-spanner-admin-database-v1/synth.metadata
Labels: cla: yes

#13414 [CHANGE ME] Re-generated google-cloud-shell-v1 to pick up changes in the API or client library generator.
  google-cloud-shell-v1/google-cloud-shell-v1.gemspec
  google-cloud-shell-v1/lib/google/cloud/shell/v1/cloud_shell_service/client.rb
  google-cloud-shell-v1/lib/google/cloud/shell/v1/cloud_shell_service/operations.rb
  google-cloud-shell-v1/synth.metadata
Labels: cla: yes

#13413 [CHANGE ME] Re-generated google-cloud-service_usage-v1 to pick up changes in the API or client library generator.
  google-cloud-service_usage-v1/google-cloud-service_usage-v1.gemspec
  google-cloud-service_usage-v1/lib/google/cloud/service_usage/v1/service_usage/client.rb
  google-cloud-service_usage-v1/lib/google/cloud/service_usage/v1/service_usage/operations.rb
  google-cloud-service_usage-v1/synth.metadata
Labels: cla: yes

#13412 [CHANGE ME] Re-generated google-cloud-service_management-v1 to pick up changes in the API or client library generator.
  google-cloud-service_management-v1/google-cloud-service_management-v1.gemspec
  google-cloud-service_management-v1/lib/google/cloud/service_management/v1/service_manager/client.rb
  google-cloud-service_management-v1/lib/google/cloud/service_management/v1/service_manager/operations.rb
  google-cloud-service_management-v1/synth.metadata
Labels: cla: yes

#13411 [CHANGE ME] Re-generated google-cloud-service_directory-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1beta1/google-cloud-service_directory-v1beta1.gemspec
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/lookup_service/client.rb
  google-cloud-service_directory-v1beta1/lib/google/cloud/service_directory/v1beta1/registration_service/client.rb
  google-cloud-service_directory-v1beta1/synth.metadata
Labels: cla: yes

#13410 [CHANGE ME] Re-generated google-cloud-service_directory-v1 to pick up changes in the API or client library generator.
  google-cloud-service_directory-v1/google-cloud-service_directory-v1.gemspec
  google-cloud-service_directory-v1/lib/google/cloud/service_directory/v1/lookup_service/client.rb
  google-cloud-service_directory-v1/lib/google/cloud/service_directory/v1/registration_service/client.rb
  google-cloud-service_directory-v1/synth.metadata
Labels: cla: yes

#13409 [CHANGE ME] Re-generated google-cloud-service_control-v1 to pick up changes in the API or client library generator.
  google-cloud-service_control-v1/google-cloud-service_control-v1.gemspec
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/quota_controller/client.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/service_controller/client.rb
  google-cloud-service_control-v1/synth.metadata
Labels: cla: yes

#13408 [CHANGE ME] Re-generated google-cloud-security_center-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-security_center-v1p1beta1/google-cloud-security_center-v1p1beta1.gemspec
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/security_center/client.rb
  google-cloud-security_center-v1p1beta1/lib/google/cloud/security_center/v1p1beta1/security_center/operations.rb
  google-cloud-security_center-v1p1beta1/synth.metadata
Labels: cla: yes

#13407 [CHANGE ME] Re-generated google-cloud-security_center-v1 to pick up changes in the API or client library generator.
  google-cloud-security_center-v1/google-cloud-security_center-v1.gemspec
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/security_center/client.rb
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/security_center/operations.rb
  google-cloud-security_center-v1/synth.metadata
Labels: cla: yes

#13406 [CHANGE ME] Re-generated google-cloud-security-private_ca-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-security-private_ca-v1beta1/google-cloud-security-private_ca-v1beta1.gemspec
  google-cloud-security-private_ca-v1beta1/lib/google/cloud/security/private_ca/v1beta1/certificate_authority_service/client.rb
  google-cloud-security-private_ca-v1beta1/lib/google/cloud/security/private_ca/v1beta1/certificate_authority_service/operations.rb
  google-cloud-security-private_ca-v1beta1/synth.metadata
Labels: cla: yes

#13405 [CHANGE ME] Re-generated google-cloud-security-private_ca-v1 to pick up changes in the API or client library generator.
  google-cloud-security-private_ca-v1/google-cloud-security-private_ca-v1.gemspec
  google-cloud-security-private_ca-v1/lib/google/cloud/security/private_ca/v1/certificate_authority_service/client.rb
  google-cloud-security-private_ca-v1/lib/google/cloud/security/private_ca/v1/certificate_authority_service/operations.rb
  google-cloud-security-private_ca-v1/synth.metadata
Labels: cla: yes

#13404 [CHANGE ME] Re-generated google-cloud-secret_manager-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1beta1/google-cloud-secret_manager-v1beta1.gemspec
  google-cloud-secret_manager-v1beta1/lib/google/cloud/secret_manager/v1beta1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1beta1/synth.metadata
Labels: cla: yes

#13403 [CHANGE ME] Re-generated google-cloud-secret_manager-v1 to pick up changes in the API or client library generator.
  google-cloud-secret_manager-v1/google-cloud-secret_manager-v1.gemspec
  google-cloud-secret_manager-v1/lib/google/cloud/secret_manager/v1/secret_manager_service/client.rb
  google-cloud-secret_manager-v1/synth.metadata
Labels: cla: yes

#13402 [CHANGE ME] Re-generated google-cloud-scheduler-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1beta1/google-cloud-scheduler-v1beta1.gemspec
  google-cloud-scheduler-v1beta1/lib/google/cloud/scheduler/v1beta1/cloud_scheduler/client.rb
  google-cloud-scheduler-v1beta1/synth.metadata
Labels: cla: yes

#13401 [CHANGE ME] Re-generated google-cloud-scheduler-v1 to pick up changes in the API or client library generator.
  google-cloud-scheduler-v1/google-cloud-scheduler-v1.gemspec
  google-cloud-scheduler-v1/lib/google/cloud/scheduler/v1/cloud_scheduler/client.rb
  google-cloud-scheduler-v1/synth.metadata
Labels: cla: yes

#13400 [CHANGE ME] Re-generated google-cloud-retail-v2 to pick up changes in the API or client library generator.
  google-cloud-retail-v2/google-cloud-retail-v2.gemspec
  google-cloud-retail-v2/lib/google/cloud/retail/v2/catalog_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/completion_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/completion_service/operations.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/prediction_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/product_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/product_service/operations.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/search_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/user_event_service/client.rb
  google-cloud-retail-v2/lib/google/cloud/retail/v2/user_event_service/operations.rb
  google-cloud-retail-v2/synth.metadata
Labels: cla: yes

#13399 [CHANGE ME] Re-generated google-cloud-resource_settings-v1 to pick up changes in the API or client library generator.
  google-cloud-resource_settings-v1/google-cloud-resource_settings-v1.gemspec
  google-cloud-resource_settings-v1/lib/google/cloud/resource_settings/v1/resource_settings_service/client.rb
  google-cloud-resource_settings-v1/synth.metadata
Labels: cla: yes

#13398 [CHANGE ME] Re-generated google-cloud-redis-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-redis-v1beta1/google-cloud-redis-v1beta1.gemspec
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/client.rb
  google-cloud-redis-v1beta1/lib/google/cloud/redis/v1beta1/cloud_redis/operations.rb
  google-cloud-redis-v1beta1/synth.metadata
Labels: cla: yes

#13397 [CHANGE ME] Re-generated google-cloud-redis-v1 to pick up changes in the API or client library generator.
  google-cloud-redis-v1/google-cloud-redis-v1.gemspec
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/client.rb
  google-cloud-redis-v1/lib/google/cloud/redis/v1/cloud_redis/operations.rb
  google-cloud-redis-v1/synth.metadata
Labels: cla: yes

#13396 [CHANGE ME] Re-generated google-cloud-recommender-v1 to pick up changes in the API or client library generator.
  google-cloud-recommender-v1/google-cloud-recommender-v1.gemspec
  google-cloud-recommender-v1/lib/google/cloud/recommender/v1/recommender/client.rb
  google-cloud-recommender-v1/synth.metadata
Labels: cla: yes

#13395 [CHANGE ME] Re-generated google-cloud-recommendation_engine-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-recommendation_engine-v1beta1/google-cloud-recommendation_engine-v1beta1.gemspec
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/catalog_service/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/catalog_service/operations.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/prediction_api_key_registry/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/prediction_service/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/user_event_service/client.rb
  google-cloud-recommendation_engine-v1beta1/lib/google/cloud/recommendation_engine/v1beta1/user_event_service/operations.rb
  google-cloud-recommendation_engine-v1beta1/synth.metadata
Labels: cla: yes

#13393 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise-v1 to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise-v1/google-cloud-recaptcha_enterprise-v1.gemspec
  google-cloud-recaptcha_enterprise-v1/lib/google/cloud/recaptcha_enterprise/v1/recaptcha_enterprise_service/client.rb
  google-cloud-recaptcha_enterprise-v1/synth.metadata
Labels: cla: yes

#13392 [CHANGE ME] Re-generated google-cloud-pubsub-v1 to pick up changes in the API or client library generator.
  google-cloud-pubsub-v1/google-cloud-pubsub-v1.gemspec
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/iam_policy/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/schema_service/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber/client.rb
  google-cloud-pubsub-v1/synth.metadata
Labels: cla: yes

#13390 [CHANGE ME] Re-generated google-cloud-private_catalog-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-private_catalog-v1beta1/google-cloud-private_catalog-v1beta1.gemspec
  google-cloud-private_catalog-v1beta1/lib/google/cloud/private_catalog/v1beta1/private_catalog/client.rb
  google-cloud-private_catalog-v1beta1/synth.metadata
Labels: cla: yes

#13389 [CHANGE ME] Re-generated google-cloud-policy_troubleshooter-v1 to pick up changes in the API or client library generator.
  google-cloud-policy_troubleshooter-v1/google-cloud-policy_troubleshooter-v1.gemspec
  google-cloud-policy_troubleshooter-v1/lib/google/cloud/policy_troubleshooter/v1/iam_checker/client.rb
  google-cloud-policy_troubleshooter-v1/synth.metadata
Labels: cla: yes

#13388 [CHANGE ME] Re-generated google-cloud-phishing_protection-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-phishing_protection-v1beta1/google-cloud-phishing_protection-v1beta1.gemspec
  google-cloud-phishing_protection-v1beta1/lib/google/cloud/phishing_protection/v1beta1/phishing_protection_service/client.rb
  google-cloud-phishing_protection-v1beta1/synth.metadata
Labels: cla: yes

#13387 [CHANGE ME] Re-generated google-cloud-os_login-v1beta to pick up changes in the API or client library generator.
  google-cloud-os_login-v1beta/google-cloud-os_login-v1beta.gemspec
  google-cloud-os_login-v1beta/lib/google/cloud/os_login/v1beta/os_login_service/client.rb
  google-cloud-os_login-v1beta/synth.metadata
Labels: cla: yes

#13386 [CHANGE ME] Re-generated google-cloud-os_login-v1 to pick up changes in the API or client library generator.
  google-cloud-os_login-v1/google-cloud-os_login-v1.gemspec
  google-cloud-os_login-v1/lib/google/cloud/os_login/v1/os_login_service/client.rb
  google-cloud-os_login-v1/synth.metadata
Labels: cla: yes

#13385 [CHANGE ME] Re-generated google-cloud-os_config-v1alpha to pick up changes in the API or client library generator.
  google-cloud-os_config-v1alpha/google-cloud-os_config-v1alpha.gemspec
  google-cloud-os_config-v1alpha/lib/google/cloud/os_config/v1alpha/os_config_zonal_service/client.rb
  google-cloud-os_config-v1alpha/lib/google/cloud/os_config/v1alpha/os_config_zonal_service/operations.rb
  google-cloud-os_config-v1alpha/synth.metadata
Labels: cla: yes

#13384 [CHANGE ME] Re-generated google-cloud-os_config-v1 to pick up changes in the API or client library generator.
  google-cloud-os_config-v1/google-cloud-os_config-v1.gemspec
  google-cloud-os_config-v1/lib/google/cloud/os_config/v1/os_config_service/client.rb
  google-cloud-os_config-v1/synth.metadata
Labels: cla: yes

#13383 [CHANGE ME] Re-generated google-cloud-org_policy-v2 to pick up changes in the API or client library generator.
  google-cloud-org_policy-v2/google-cloud-org_policy-v2.gemspec
  google-cloud-org_policy-v2/lib/google/cloud/org_policy/v2/org_policy/client.rb
  google-cloud-org_policy-v2/synth.metadata
Labels: cla: yes

#13382 [CHANGE ME] Re-generated google-cloud-notebooks-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-notebooks-v1beta1/google-cloud-notebooks-v1beta1.gemspec
  google-cloud-notebooks-v1beta1/lib/google/cloud/notebooks/v1beta1/notebook_service/client.rb
  google-cloud-notebooks-v1beta1/lib/google/cloud/notebooks/v1beta1/notebook_service/operations.rb
  google-cloud-notebooks-v1beta1/synth.metadata
Labels: cla: yes

#13381 [CHANGE ME] Re-generated google-cloud-network_management-v1 to pick up changes in the API or client library generator.
  google-cloud-network_management-v1/google-cloud-network_management-v1.gemspec
  google-cloud-network_management-v1/lib/google/cloud/network_management/v1/reachability_service/client.rb
  google-cloud-network_management-v1/lib/google/cloud/network_management/v1/reachability_service/operations.rb
  google-cloud-network_management-v1/synth.metadata
Labels: cla: yes

#13380 [CHANGE ME] Re-generated google-cloud-network_connectivity-v1alpha1 to pick up changes in the API or client library generator.
  google-cloud-network_connectivity-v1alpha1/google-cloud-network_connectivity-v1alpha1.gemspec
  google-cloud-network_connectivity-v1alpha1/lib/google/cloud/network_connectivity/v1alpha1/hub_service/client.rb
  google-cloud-network_connectivity-v1alpha1/lib/google/cloud/network_connectivity/v1alpha1/hub_service/operations.rb
  google-cloud-network_connectivity-v1alpha1/synth.metadata
Labels: cla: yes

#13379 [CHANGE ME] Re-generated google-cloud-monitoring-v3 to pick up changes in the API or client library generator.
  google-cloud-monitoring-v3/google-cloud-monitoring-v3.gemspec
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/alert_policy_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/group_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/metric_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/notification_channel_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/query_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/service_monitoring_service/client.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/uptime_check_service/client.rb
  google-cloud-monitoring-v3/synth.metadata
Labels: cla: yes

#13378 [CHANGE ME] Re-generated google-cloud-monitoring-dashboard-v1 to pick up changes in the API or client library generator.
  google-cloud-monitoring-dashboard-v1/google-cloud-monitoring-dashboard-v1.gemspec
  google-cloud-monitoring-dashboard-v1/lib/google/cloud/monitoring/dashboard/v1/dashboards_service/client.rb
  google-cloud-monitoring-dashboard-v1/synth.metadata
Labels: cla: yes

#13377 [CHANGE ME] Re-generated google-cloud-metastore-v1beta to pick up changes in the API or client library generator.
  google-cloud-metastore-v1beta/google-cloud-metastore-v1beta.gemspec
  google-cloud-metastore-v1beta/lib/google/cloud/metastore/v1beta/dataproc_metastore/client.rb
  google-cloud-metastore-v1beta/lib/google/cloud/metastore/v1beta/dataproc_metastore/operations.rb
  google-cloud-metastore-v1beta/synth.metadata
Labels: cla: yes

#13376 [CHANGE ME] Re-generated google-cloud-metastore-v1 to pick up changes in the API or client library generator.
  google-cloud-metastore-v1/google-cloud-metastore-v1.gemspec
  google-cloud-metastore-v1/lib/google/cloud/metastore/v1/dataproc_metastore/client.rb
  google-cloud-metastore-v1/lib/google/cloud/metastore/v1/dataproc_metastore/operations.rb
  google-cloud-metastore-v1/synth.metadata
Labels: cla: yes

#13375 [CHANGE ME] Re-generated google-cloud-memcache-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-memcache-v1beta2/google-cloud-memcache-v1beta2.gemspec
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/cloud_memcache/client.rb
  google-cloud-memcache-v1beta2/lib/google/cloud/memcache/v1beta2/cloud_memcache/operations.rb
  google-cloud-memcache-v1beta2/synth.metadata
Labels: cla: yes

#13374 [CHANGE ME] Re-generated google-cloud-memcache-v1 to pick up changes in the API or client library generator.
  google-cloud-memcache-v1/google-cloud-memcache-v1.gemspec
  google-cloud-memcache-v1/lib/google/cloud/memcache/v1/cloud_memcache/client.rb
  google-cloud-memcache-v1/lib/google/cloud/memcache/v1/cloud_memcache/operations.rb
  google-cloud-memcache-v1/synth.metadata
Labels: cla: yes

#13373 [CHANGE ME] Re-generated google-cloud-media_translation-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-media_translation-v1beta1/google-cloud-media_translation-v1beta1.gemspec
  google-cloud-media_translation-v1beta1/lib/google/cloud/media_translation/v1beta1/speech_translation_service/client.rb
  google-cloud-media_translation-v1beta1/synth.metadata
Labels: cla: yes

#13372 [CHANGE ME] Re-generated google-cloud-managed_identities-v1 to pick up changes in the API or client library generator.
  google-cloud-managed_identities-v1/google-cloud-managed_identities-v1.gemspec
  google-cloud-managed_identities-v1/lib/google/cloud/managed_identities/v1/managed_identities_service/client.rb
  google-cloud-managed_identities-v1/lib/google/cloud/managed_identities/v1/managed_identities_service/operations.rb
  google-cloud-managed_identities-v1/synth.metadata
Labels: cla: yes

#13371 [CHANGE ME] Re-generated google-cloud-logging-v2 to pick up changes in the API or client library generator.
  google-cloud-logging-v2/google-cloud-logging-v2.gemspec
  google-cloud-logging-v2/lib/google/cloud/logging/v2/config_service/client.rb
  google-cloud-logging-v2/lib/google/cloud/logging/v2/logging_service/client.rb
  google-cloud-logging-v2/lib/google/cloud/logging/v2/metrics_service/client.rb
  google-cloud-logging-v2/synth.metadata
Labels: cla: yes

#13370 [CHANGE ME] Re-generated google-cloud-life_sciences-v2beta to pick up changes in the API or client library generator.
  google-cloud-life_sciences-v2beta/google-cloud-life_sciences-v2beta.gemspec
  google-cloud-life_sciences-v2beta/lib/google/cloud/life_sciences/v2beta/workflows_service/client.rb
  google-cloud-life_sciences-v2beta/lib/google/cloud/life_sciences/v2beta/workflows_service/operations.rb
  google-cloud-life_sciences-v2beta/synth.metadata
Labels: cla: yes

#13369 [CHANGE ME] Re-generated google-cloud-language-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-language-v1beta2/google-cloud-language-v1beta2.gemspec
  google-cloud-language-v1beta2/lib/google/cloud/language/v1beta2/language_service/client.rb
  google-cloud-language-v1beta2/synth.metadata
Labels: cla: yes

#13368 [CHANGE ME] Re-generated google-cloud-language-v1 to pick up changes in the API or client library generator.
  google-cloud-language-v1/google-cloud-language-v1.gemspec
  google-cloud-language-v1/lib/google/cloud/language/v1/language_service/client.rb
  google-cloud-language-v1/synth.metadata
Labels: cla: yes

#13367 [CHANGE ME] Re-generated google-cloud-kms-v1 to pick up changes in the API or client library generator.
  google-cloud-kms-v1/google-cloud-kms-v1.gemspec
  google-cloud-kms-v1/lib/google/cloud/kms/v1/iam_policy/client.rb
  google-cloud-kms-v1/lib/google/cloud/kms/v1/key_management_service/client.rb
  google-cloud-kms-v1/synth.metadata
Labels: cla: yes

#13366 [CHANGE ME] Re-generated google-cloud-iot-v1 to pick up changes in the API or client library generator.
  google-cloud-iot-v1/google-cloud-iot-v1.gemspec
  google-cloud-iot-v1/lib/google/cloud/iot/v1/device_manager/client.rb
  google-cloud-iot-v1/synth.metadata
Labels: cla: yes

#13365 [CHANGE ME] Re-generated google-cloud-iap-v1 to pick up changes in the API or client library generator.
  google-cloud-iap-v1/google-cloud-iap-v1.gemspec
  google-cloud-iap-v1/lib/google/cloud/iap/v1/identity_aware_proxy_admin_service/client.rb
  google-cloud-iap-v1/lib/google/cloud/iap/v1/identity_aware_proxy_o_auth_service/client.rb
  google-cloud-iap-v1/synth.metadata
Labels: cla: yes

#13364 [CHANGE ME] Re-generated google-cloud-gke_hub-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-gke_hub-v1beta1/google-cloud-gke_hub-v1beta1.gemspec
  google-cloud-gke_hub-v1beta1/lib/google/cloud/gke_hub/v1beta1/gke_hub_membership_service/client.rb
  google-cloud-gke_hub-v1beta1/lib/google/cloud/gke_hub/v1beta1/gke_hub_membership_service/operations.rb
  google-cloud-gke_hub-v1beta1/synth.metadata
Labels: cla: yes

#13363 [CHANGE ME] Re-generated google-cloud-gke_connect-gateway-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-gke_connect-gateway-v1beta1/google-cloud-gke_connect-gateway-v1beta1.gemspec
  google-cloud-gke_connect-gateway-v1beta1/lib/google/cloud/gke_connect/gateway/v1beta1/gateway_service/client.rb
  google-cloud-gke_connect-gateway-v1beta1/synth.metadata
Labels: cla: yes

#13362 [CHANGE ME] Re-generated google-cloud-gaming-v1 to pick up changes in the API or client library generator.
  google-cloud-gaming-v1/google-cloud-gaming-v1.gemspec
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_clusters_service/client.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_clusters_service/operations.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_configs_service/client.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_configs_service/operations.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_deployments_service/client.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/game_server_deployments_service/operations.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/realms_service/client.rb
  google-cloud-gaming-v1/lib/google/cloud/gaming/v1/realms_service/operations.rb
  google-cloud-gaming-v1/synth.metadata
Labels: cla: yes

#13361 [CHANGE ME] Re-generated google-cloud-firestore-v1 to pick up changes in the API or client library generator.
  google-cloud-firestore-v1/google-cloud-firestore-v1.gemspec
  google-cloud-firestore-v1/lib/google/cloud/firestore/v1/firestore/client.rb
  google-cloud-firestore-v1/synth.metadata
Labels: cla: yes

#13360 [CHANGE ME] Re-generated google-cloud-firestore-admin-v1 to pick up changes in the API or client library generator.
  google-cloud-firestore-admin-v1/google-cloud-firestore-admin-v1.gemspec
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin/client.rb
  google-cloud-firestore-admin-v1/lib/google/cloud/firestore/admin/v1/firestore_admin/operations.rb
  google-cloud-firestore-admin-v1/synth.metadata
Labels: cla: yes

#13359 [CHANGE ME] Re-generated google-cloud-eventarc-v1 to pick up changes in the API or client library generator.
  google-cloud-eventarc-v1/google-cloud-eventarc-v1.gemspec
  google-cloud-eventarc-v1/lib/google/cloud/eventarc/v1/eventarc/client.rb
  google-cloud-eventarc-v1/lib/google/cloud/eventarc/v1/eventarc/operations.rb
  google-cloud-eventarc-v1/synth.metadata
Labels: cla: yes

#13358 [CHANGE ME] Re-generated google-cloud-essential_contacts-v1 to pick up changes in the API or client library generator.
  google-cloud-essential_contacts-v1/google-cloud-essential_contacts-v1.gemspec
  google-cloud-essential_contacts-v1/lib/google/cloud/essential_contacts/v1/essential_contacts_service/client.rb
  google-cloud-essential_contacts-v1/synth.metadata
Labels: cla: yes

#13357 [CHANGE ME] Re-generated google-cloud-error_reporting-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-error_reporting-v1beta1/google-cloud-error_reporting-v1beta1.gemspec
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/error_group_service/client.rb
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/error_stats_service/client.rb
  google-cloud-error_reporting-v1beta1/lib/google/cloud/error_reporting/v1beta1/report_errors_service/client.rb
  google-cloud-error_reporting-v1beta1/synth.metadata
Labels: cla: yes

#13356 [CHANGE ME] Re-generated google-cloud-domains-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-domains-v1beta1/google-cloud-domains-v1beta1.gemspec
  google-cloud-domains-v1beta1/lib/google/cloud/domains/v1beta1/domains/client.rb
  google-cloud-domains-v1beta1/lib/google/cloud/domains/v1beta1/domains/operations.rb
  google-cloud-domains-v1beta1/synth.metadata
Labels: cla: yes

#13355 [CHANGE ME] Re-generated google-cloud-document_ai-v1beta3 to pick up changes in the API or client library generator.
  google-cloud-document_ai-v1beta3/google-cloud-document_ai-v1beta3.gemspec
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service/client.rb
  google-cloud-document_ai-v1beta3/lib/google/cloud/document_ai/v1beta3/document_processor_service/operations.rb
  google-cloud-document_ai-v1beta3/synth.metadata
Labels: cla: yes

#13354 [CHANGE ME] Re-generated google-cloud-document_ai-v1 to pick up changes in the API or client library generator.
  google-cloud-document_ai-v1/google-cloud-document_ai-v1.gemspec
  google-cloud-document_ai-v1/lib/google/cloud/document_ai/v1/document_processor_service/client.rb
  google-cloud-document_ai-v1/lib/google/cloud/document_ai/v1/document_processor_service/operations.rb
  google-cloud-document_ai-v1/synth.metadata
Labels: cla: yes

#13353 [CHANGE ME] Re-generated google-cloud-dlp-v2 to pick up changes in the API or client library generator.
  google-cloud-dlp-v2/google-cloud-dlp-v2.gemspec
  google-cloud-dlp-v2/lib/google/cloud/dlp/v2/dlp_service/client.rb
  google-cloud-dlp-v2/synth.metadata
Labels: cla: yes

#13352 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/google-cloud-dialogflow-v2.gemspec
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/agents/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/answer_records/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/contexts/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/conversation_profiles/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/conversations/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/documents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/documents/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/entity_types/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/environments/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/fulfillments/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/intents/operations.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/knowledge_bases/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/participants/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/session_entity_types/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/sessions/client.rb
  google-cloud-dialogflow-v2/lib/google/cloud/dialogflow/v2/versions/client.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes

#13351 [CHANGE ME] Re-generated google-cloud-debugger-v2 to pick up changes in the API or client library generator.
  google-cloud-debugger-v2/google-cloud-debugger-v2.gemspec
  google-cloud-debugger-v2/lib/google/cloud/debugger/v2/controller/client.rb
  google-cloud-debugger-v2/lib/google/cloud/debugger/v2/debugger/client.rb
  google-cloud-debugger-v2/synth.metadata
Labels: cla: yes

#13350 [CHANGE ME] Re-generated google-cloud-datastore-v1 to pick up changes in the API or client library generator.
  google-cloud-datastore-v1/google-cloud-datastore-v1.gemspec
  google-cloud-datastore-v1/lib/google/cloud/datastore/v1/datastore/client.rb
  google-cloud-datastore-v1/synth.metadata
Labels: cla: yes

#13349 [CHANGE ME] Re-generated google-cloud-datastore-admin-v1 to pick up changes in the API or client library generator.
  google-cloud-datastore-admin-v1/google-cloud-datastore-admin-v1.gemspec
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/datastore_admin/client.rb
  google-cloud-datastore-admin-v1/lib/google/cloud/datastore/admin/v1/datastore_admin/operations.rb
  google-cloud-datastore-admin-v1/synth.metadata
Labels: cla: yes

#13348 [CHANGE ME] Re-generated google-cloud-dataqna-v1alpha to pick up changes in the API or client library generator.
  google-cloud-dataqna-v1alpha/google-cloud-dataqna-v1alpha.gemspec
  google-cloud-dataqna-v1alpha/lib/google/cloud/dataqna/v1alpha/auto_suggestion_service/client.rb
  google-cloud-dataqna-v1alpha/lib/google/cloud/dataqna/v1alpha/question_service/client.rb
  google-cloud-dataqna-v1alpha/synth.metadata
Labels: cla: yes

#13347 [CHANGE ME] Re-generated google-cloud-dataproc-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1beta2/google-cloud-dataproc-v1beta2.gemspec
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/autoscaling_policy_service/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/cluster_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/cluster_controller/operations.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/clusters_services_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/job_controller/operations.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/jobs_services_pb.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_template_service/client.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_template_service/operations.rb
  google-cloud-dataproc-v1beta2/lib/google/cloud/dataproc/v1beta2/workflow_templates_services_pb.rb
  google-cloud-dataproc-v1beta2/synth.metadata
Labels: cla: yes

#13346 [CHANGE ME] Re-generated google-cloud-dataproc-v1 to pick up changes in the API or client library generator.
  google-cloud-dataproc-v1/google-cloud-dataproc-v1.gemspec
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/autoscaling_policy_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/cluster_controller/operations.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/job_controller/operations.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_template_service/client.rb
  google-cloud-dataproc-v1/lib/google/cloud/dataproc/v1/workflow_template_service/operations.rb
  google-cloud-dataproc-v1/synth.metadata
Labels: cla: yes

#13345 [CHANGE ME] Re-generated google-cloud-dataflow-v1beta3 to pick up changes in the API or client library generator.
  google-cloud-dataflow-v1beta3/google-cloud-dataflow-v1beta3.gemspec
  google-cloud-dataflow-v1beta3/lib/google/cloud/dataflow/v1beta3/flex_templates_service/client.rb
  google-cloud-dataflow-v1beta3/lib/google/cloud/dataflow/v1beta3/jobs/client.rb
  google-cloud-dataflow-v1beta3/lib/google/cloud/dataflow/v1beta3/messages/client.rb
  google-cloud-dataflow-v1beta3/lib/google/cloud/dataflow/v1beta3/metrics/client.rb
  google-cloud-dataflow-v1beta3/lib/google/cloud/dataflow/v1beta3/snapshots/client.rb
  google-cloud-dataflow-v1beta3/lib/google/cloud/dataflow/v1beta3/templates_service/client.rb
  google-cloud-dataflow-v1beta3/synth.metadata
Labels: cla: yes

#13344 [CHANGE ME] Re-generated google-cloud-data_labeling-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-data_labeling-v1beta1/google-cloud-data_labeling-v1beta1.gemspec
  google-cloud-data_labeling-v1beta1/lib/google/cloud/data_labeling/v1beta1/data_labeling_service/client.rb
  google-cloud-data_labeling-v1beta1/lib/google/cloud/data_labeling/v1beta1/data_labeling_service/operations.rb
  google-cloud-data_labeling-v1beta1/synth.metadata
Labels: cla: yes

#13343 [CHANGE ME] Re-generated google-cloud-data_fusion-v1 to pick up changes in the API or client library generator.
  google-cloud-data_fusion-v1/google-cloud-data_fusion-v1.gemspec
  google-cloud-data_fusion-v1/lib/google/cloud/data_fusion/v1/data_fusion/client.rb
  google-cloud-data_fusion-v1/lib/google/cloud/data_fusion/v1/data_fusion/operations.rb
  google-cloud-data_fusion-v1/synth.metadata
Labels: cla: yes

#13342 [CHANGE ME] Re-generated google-cloud-data_catalog-v1 to pick up changes in the API or client library generator.
  google-cloud-data_catalog-v1/google-cloud-data_catalog-v1.gemspec
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/data_catalog/client.rb
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/policy_tag_manager/client.rb
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/policy_tag_manager_serialization/client.rb
  google-cloud-data_catalog-v1/synth.metadata
Labels: cla: yes

#13341 [CHANGE ME] Re-generated google-cloud-container_analysis-v1 to pick up changes in the API or client library generator.
  google-cloud-container_analysis-v1/google-cloud-container_analysis-v1.gemspec
  google-cloud-container_analysis-v1/lib/google/cloud/container_analysis/v1/container_analysis/client.rb
  google-cloud-container_analysis-v1/synth.metadata
Labels: cla: yes

#13340 [CHANGE ME] Re-generated google-cloud-container-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-container-v1beta1/google-cloud-container-v1beta1.gemspec
  google-cloud-container-v1beta1/lib/google/cloud/container/v1beta1/cluster_manager/client.rb
  google-cloud-container-v1beta1/synth.metadata
Labels: cla: yes

#13339 [CHANGE ME] Re-generated google-cloud-container-v1 to pick up changes in the API or client library generator.
  google-cloud-container-v1/google-cloud-container-v1.gemspec
  google-cloud-container-v1/lib/google/cloud/container/v1/cluster_manager/client.rb
  google-cloud-container-v1/synth.metadata
Labels: cla: yes

#13338 [CHANGE ME] Re-generated google-cloud-asset-v1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1/google-cloud-asset-v1.gemspec
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/client.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/operations.rb
  google-cloud-asset-v1/synth.metadata
Labels: cla: yes, context: none

#13336 [CHANGE ME] Re-generated google-cloud-cloud_dms-v1 to pick up changes in the API or client library generator.
  google-cloud-cloud_dms-v1/google-cloud-cloud_dms-v1.gemspec
  google-cloud-cloud_dms-v1/lib/google/cloud/cloud_dms/v1/data_migration_service/client.rb
  google-cloud-cloud_dms-v1/lib/google/cloud/cloud_dms/v1/data_migration_service/operations.rb
  google-cloud-cloud_dms-v1/synth.metadata
Labels: cla: yes

#13335 [CHANGE ME] Re-generated google-cloud-channel-v1 to pick up changes in the API or client library generator.
  google-cloud-channel-v1/google-cloud-channel-v1.gemspec
  google-cloud-channel-v1/lib/google/cloud/channel/v1/cloud_channel_service/client.rb
  google-cloud-channel-v1/lib/google/cloud/channel/v1/cloud_channel_service/operations.rb
  google-cloud-channel-v1/synth.metadata
Labels: cla: yes

#13334 [CHANGE ME] Re-generated google-cloud-build-v1 to pick up changes in the API or client library generator.
  google-cloud-build-v1/google-cloud-build-v1.gemspec
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/client.rb
  google-cloud-build-v1/lib/google/cloud/build/v1/cloud_build/operations.rb
  google-cloud-build-v1/synth.metadata
Labels: cla: yes

#13333 [CHANGE ME] Re-generated google-cloud-binary_authorization-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-binary_authorization-v1beta1/google-cloud-binary_authorization-v1beta1.gemspec
  google-cloud-binary_authorization-v1beta1/lib/google/cloud/binary_authorization/v1beta1/binauthz_management_service/client.rb
  google-cloud-binary_authorization-v1beta1/synth.metadata
Labels: cla: yes

#13332 [CHANGE ME] Re-generated google-cloud-billing-v1 to pick up changes in the API or client library generator.
  google-cloud-billing-v1/google-cloud-billing-v1.gemspec
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_billing/client.rb
  google-cloud-billing-v1/lib/google/cloud/billing/v1/cloud_catalog/client.rb
  google-cloud-billing-v1/synth.metadata
Labels: cla: yes

#13331 [CHANGE ME] Re-generated google-cloud-billing-budgets-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-billing-budgets-v1beta1/google-cloud-billing-budgets-v1beta1.gemspec
  google-cloud-billing-budgets-v1beta1/lib/google/cloud/billing/budgets/v1beta1/budget_service/client.rb
  google-cloud-billing-budgets-v1beta1/synth.metadata
Labels: cla: yes

#13330 [CHANGE ME] Re-generated google-cloud-bigtable-v2 to pick up changes in the API or client library generator.
  google-cloud-bigtable-v2/google-cloud-bigtable-v2.gemspec
  google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/bigtable/client.rb
  google-cloud-bigtable-v2/synth.metadata
Labels: cla: yes

#13329 [CHANGE ME] Re-generated google-cloud-bigtable-admin-v2 to pick up changes in the API or client library generator.
  google-cloud-bigtable-admin-v2/google-cloud-bigtable-admin-v2.gemspec
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin/client.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_instance_admin/operations.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin/client.rb
  google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin/operations.rb
  google-cloud-bigtable-admin-v2/synth.metadata
Labels: cla: yes

#13328 [CHANGE ME] Re-generated google-cloud-bigquery-storage-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage-v1/google-cloud-bigquery-storage-v1.gemspec
  google-cloud-bigquery-storage-v1/lib/google/cloud/bigquery/storage/v1/big_query_read/client.rb
  google-cloud-bigquery-storage-v1/synth.metadata
Labels: cla: yes

#13327 [CHANGE ME] Re-generated google-cloud-bigquery-reservation-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-reservation-v1/google-cloud-bigquery-reservation-v1.gemspec
  google-cloud-bigquery-reservation-v1/lib/google/cloud/bigquery/reservation/v1/reservation_service/client.rb
  google-cloud-bigquery-reservation-v1/synth.metadata
Labels: cla: yes

#13326 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer-v1/google-cloud-bigquery-data_transfer-v1.gemspec
  google-cloud-bigquery-data_transfer-v1/lib/google/cloud/bigquery/data_transfer/v1/data_transfer_service/client.rb
  google-cloud-bigquery-data_transfer-v1/synth.metadata
Labels: cla: yes

#13325 [CHANGE ME] Re-generated google-cloud-bigquery-connection-v1 to pick up changes in the API or client library generator.
  google-cloud-bigquery-connection-v1/google-cloud-bigquery-connection-v1.gemspec
  google-cloud-bigquery-connection-v1/lib/google/cloud/bigquery/connection/v1/connection_service/client.rb
  google-cloud-bigquery-connection-v1/synth.metadata
Labels: cla: yes

#13324 [CHANGE ME] Re-generated google-cloud-automl-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-automl-v1beta1/google-cloud-automl-v1beta1.gemspec
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/automl/client.rb
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/automl/operations.rb
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/prediction_service/client.rb
  google-cloud-automl-v1beta1/lib/google/cloud/automl/v1beta1/prediction_service/operations.rb
  google-cloud-automl-v1beta1/synth.metadata
Labels: cla: yes

#13323 [CHANGE ME] Re-generated google-cloud-automl-v1 to pick up changes in the API or client library generator.
  google-cloud-automl-v1/google-cloud-automl-v1.gemspec
  google-cloud-automl-v1/lib/google/cloud/automl/v1/automl/client.rb
  google-cloud-automl-v1/lib/google/cloud/automl/v1/automl/operations.rb
  google-cloud-automl-v1/lib/google/cloud/automl/v1/prediction_service/client.rb
  google-cloud-automl-v1/lib/google/cloud/automl/v1/prediction_service/operations.rb
  google-cloud-automl-v1/synth.metadata
Labels: cla: yes

#13322 [CHANGE ME] Re-generated google-cloud-assured_workloads-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-assured_workloads-v1beta1/google-cloud-assured_workloads-v1beta1.gemspec
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/assured_workloads_service/client.rb
  google-cloud-assured_workloads-v1beta1/lib/google/cloud/assured_workloads/v1beta1/assured_workloads_service/operations.rb
  google-cloud-assured_workloads-v1beta1/synth.metadata
Labels: cla: yes

#13321 [CHANGE ME] Re-generated google-cloud-artifact_registry-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-artifact_registry-v1beta2/google-cloud-artifact_registry-v1beta2.gemspec
  google-cloud-artifact_registry-v1beta2/lib/google/cloud/artifact_registry/v1beta2/artifact_registry/client.rb
  google-cloud-artifact_registry-v1beta2/lib/google/cloud/artifact_registry/v1beta2/artifact_registry/operations.rb
  google-cloud-artifact_registry-v1beta2/synth.metadata
Labels: cla: yes

#13320 [CHANGE ME] Re-generated google-cloud-app_engine-v1 to pick up changes in the API or client library generator.
  google-cloud-app_engine-v1/google-cloud-app_engine-v1.gemspec
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/applications/client.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/applications/operations.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/authorized_certificates/client.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/authorized_domains/client.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/domain_mappings/client.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/domain_mappings/operations.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/firewall/client.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/instances/client.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/instances/operations.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/services/client.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/services/operations.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/versions/client.rb
  google-cloud-app_engine-v1/lib/google/cloud/app_engine/v1/versions/operations.rb
  google-cloud-app_engine-v1/synth.metadata
Labels: cla: yes

#13319 [CHANGE ME] Re-generated google-cloud-apigee_connect-v1 to pick up changes in the API or client library generator.
  google-cloud-apigee_connect-v1/google-cloud-apigee_connect-v1.gemspec
  google-cloud-apigee_connect-v1/lib/google/cloud/apigee_connect/v1/connection_service/client.rb
  google-cloud-apigee_connect-v1/lib/google/cloud/apigee_connect/v1/tether/client.rb
  google-cloud-apigee_connect-v1/synth.metadata
Labels: cla: yes

#13318 [CHANGE ME] Re-generated google-cloud-api_gateway-v1 to pick up changes in the API or client library generator.
  google-cloud-api_gateway-v1/google-cloud-api_gateway-v1.gemspec
  google-cloud-api_gateway-v1/lib/google/cloud/api_gateway/v1/api_gateway_service/client.rb
  google-cloud-api_gateway-v1/lib/google/cloud/api_gateway/v1/api_gateway_service/operations.rb
  google-cloud-api_gateway-v1/synth.metadata
Labels: cla: yes

#13317 [CHANGE ME] Re-generated google-cloud-access_approval-v1 to pick up changes in the API or client library generator.
  google-cloud-access_approval-v1/google-cloud-access_approval-v1.gemspec
  google-cloud-access_approval-v1/lib/google/cloud/access_approval/v1/access_approval/client.rb
  google-cloud-access_approval-v1/synth.metadata
Labels: cla: yes

#13316 [CHANGE ME] Re-generated google-area120-tables-v1alpha1 to pick up changes in the API or client library generator.
  google-area120-tables-v1alpha1/google-area120-tables-v1alpha1.gemspec
  google-area120-tables-v1alpha1/lib/google/area120/tables/v1alpha1/tables_service/client.rb
  google-area120-tables-v1alpha1/synth.metadata
Labels: cla: yes

#13314 [CHANGE ME] Re-generated google-analytics-data-v1alpha to pick up changes in the API or client library generator.
  google-analytics-data-v1alpha/google-analytics-data-v1alpha.gemspec
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/client.rb
  google-analytics-data-v1alpha/synth.metadata
Labels: cla: yes

#13313 [CHANGE ME] Re-generated google-analytics-admin-v1alpha to pick up changes in the API or client library generator.
  google-analytics-admin-v1alpha/google-analytics-admin-v1alpha.gemspec
  google-analytics-admin-v1alpha/lib/google/analytics/admin/v1alpha/analytics_admin_service/client.rb
  google-analytics-admin-v1alpha/synth.metadata
Labels: cla: yes

#13418 [CHANGE ME] Re-generated google-cloud-speech-v1 to pick up changes in the API or client library generator.
  google-cloud-speech-v1/google-cloud-speech-v1.gemspec
  google-cloud-speech-v1/lib/google/cloud/speech/v1/cloud_speech_pb.rb
  google-cloud-speech-v1/lib/google/cloud/speech/v1/cloud_speech_services_pb.rb
  google-cloud-speech-v1/lib/google/cloud/speech/v1/speech/client.rb
  google-cloud-speech-v1/lib/google/cloud/speech/v1/speech/operations.rb
  google-cloud-speech-v1/proto_docs/google/cloud/speech/v1/cloud_speech.rb
  google-cloud-speech-v1/proto_docs/google/protobuf/wrappers.rb
  google-cloud-speech-v1/synth.metadata
Labels: cla: yes

#13452 [CHANGE ME] Re-generated google-cloud-dialogflow-v2 to pick up changes in the API or client library generator.
  google-cloud-dialogflow-v2/proto_docs/google/cloud/dialogflow/v2/intent.rb
  google-cloud-dialogflow-v2/synth.metadata
Labels: cla: yes

#13453 [CHANGE ME] Re-generated google-cloud-pubsub-v1 to pick up changes in the API or client library generator.
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb
  google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/subscriber/client.rb
  google-cloud-pubsub-v1/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub-v1/proto_docs/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub-v1/proto_docs/google/pubsub/v1/schema.rb
  google-cloud-pubsub-v1/synth.metadata
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/publisher_test.rb
  google-cloud-pubsub-v1/test/google/cloud/pubsub/v1/subscriber_test.rb
Labels: cla: yes

#13301 feat(bigquery): Add support for multistatement transaction statistics in jobs
  google-cloud-bigquery/acceptance/bigquery/advanced_test.rb
  google-cloud-bigquery/acceptance/bigquery/bigquery_test.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/job.rb
  google-cloud-bigquery/test/google/cloud/bigquery/job_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/load_job_test.rb
  google-cloud-bigquery/test/helper.rb
Labels: cla: yes, api: bigquery

#13598 feat(bigquery): Add GEOGRAPHY schema helpers
  google-cloud-bigquery/lib/google/cloud/bigquery/load_job.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/schema/field.rb
  google-cloud-bigquery/lib/google/cloud/bigquery/table.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_load_job_schema_test.rb
  google-cloud-bigquery/test/google/cloud/bigquery/dataset_test.rb
Labels: cla: yes, api: bigquery

#13455 AnalyzeIamPolicyLongrunning is refactored to avoid direct reference the metadata.
  google-cloud-asset/samples/quickstart.rb
Labels: cla: yes

#13292 feat: Initial generation of google-cloud-filestore-v1
  google-cloud-filestore-v1/.gitignore
  google-cloud-filestore-v1/.repo-metadata.json
  google-cloud-filestore-v1/.rubocop.yml
  google-cloud-filestore-v1/.yardopts
  google-cloud-filestore-v1/.yardopts-cloudrad
  google-cloud-filestore-v1/AUTHENTICATION.md
  google-cloud-filestore-v1/CHANGELOG.md
  google-cloud-filestore-v1/Gemfile
  google-cloud-filestore-v1/LICENSE.md
  google-cloud-filestore-v1/README.md
  google-cloud-filestore-v1/Rakefile
  google-cloud-filestore-v1/gapic_metadata.json
  google-cloud-filestore-v1/google-cloud-filestore-v1.gemspec
  google-cloud-filestore-v1/lib/google-cloud-filestore-v1.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/cloud_filestore_manager.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/cloud_filestore_manager/client.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/cloud_filestore_manager/credentials.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/cloud_filestore_manager/operations.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/cloud_filestore_manager/paths.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/cloud_filestore_service_pb.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/cloud_filestore_service_services_pb.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/version.rb
  google-cloud-filestore-v1/proto_docs/README.md
  google-cloud-filestore-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-filestore-v1/proto_docs/google/api/resource.rb
  google-cloud-filestore-v1/proto_docs/google/cloud/common/operation_metadata.rb
  google-cloud-filestore-v1/proto_docs/google/cloud/filestore/v1/cloud_filestore_service.rb
  google-cloud-filestore-v1/proto_docs/google/longrunning/operations.rb
  google-cloud-filestore-v1/proto_docs/google/protobuf/any.rb
  google-cloud-filestore-v1/proto_docs/google/protobuf/duration.rb
  google-cloud-filestore-v1/proto_docs/google/protobuf/empty.rb
  google-cloud-filestore-v1/proto_docs/google/protobuf/field_mask.rb
  google-cloud-filestore-v1/proto_docs/google/protobuf/timestamp.rb
  google-cloud-filestore-v1/proto_docs/google/protobuf/wrappers.rb
  google-cloud-filestore-v1/proto_docs/google/rpc/status.rb
  google-cloud-filestore-v1/synth.metadata
  google-cloud-filestore-v1/synth.py
  google-cloud-filestore-v1/test/google/cloud/filestore/v1/cloud_filestore_manager_operations_test.rb
  google-cloud-filestore-v1/test/google/cloud/filestore/v1/cloud_filestore_manager_paths_test.rb
  google-cloud-filestore-v1/test/google/cloud/filestore/v1/cloud_filestore_manager_test.rb
  google-cloud-filestore-v1/test/helper.rb
Labels: cla: yes

#13600 [CHANGE ME] Re-generated google-cloud-filestore-v1 to pick up changes in the API or client library generator.
  google-cloud-filestore-v1/google-cloud-filestore-v1.gemspec
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/cloud_filestore_manager/client.rb
  google-cloud-filestore-v1/lib/google/cloud/filestore/v1/cloud_filestore_manager/operations.rb
  google-cloud-filestore-v1/synth.metadata
Labels: cla: yes
