Repository googleapis/google-cloud-ruby, pull requests merged in 2021-07, with the labels that each got.

#12520 [google-cloud-workflows-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-workflows-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-workflows-v1/synth.metadata
Labels: cla: yes, context: full

#12519 [google-cloud-vpc_access-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-vpc_access-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-vpc_access-v1/synth.metadata
Labels: cla: yes, context: full

#12518 [google-cloud-tpu-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-tpu-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-tpu-v1/synth.metadata
Labels: cla: yes, context: full

#12517 [google-cloud-shell-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-shell-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-shell-v1/synth.metadata
Labels: cla: yes, context: full

#12516 [google-cloud-security-private_ca-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-security-private_ca-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-security-private_ca-v1/synth.metadata
Labels: cla: yes, context: full

#12504 [google-analytics-data-v1beta] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-analytics-data-v1beta/proto_docs/google/api/field_behavior.rb
  google-analytics-data-v1beta/synth.metadata
Labels: cla: yes, context: full

#12515 [google-cloud-resource_settings-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-resource_settings-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-resource_settings-v1/synth.metadata
Labels: cla: yes, context: full

#12514 [google-cloud-private_catalog-v1beta1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-private_catalog-v1beta1/proto_docs/google/api/field_behavior.rb
  google-cloud-private_catalog-v1beta1/synth.metadata
Labels: cla: yes, context: full

#12513 [google-cloud-os_config-v1alpha] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-os_config-v1alpha/proto_docs/google/api/field_behavior.rb
  google-cloud-os_config-v1alpha/synth.metadata
Labels: cla: yes, context: full

#12512 [google-cloud-life_sciences-v2beta] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-life_sciences-v2beta/proto_docs/google/api/field_behavior.rb
  google-cloud-life_sciences-v2beta/synth.metadata
Labels: cla: yes, context: full

#12511 [google-cloud-eventarc-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-eventarc-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-eventarc-v1/synth.metadata
Labels: cla: yes, context: full

#12510 [google-cloud-essential_contacts-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-essential_contacts-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-essential_contacts-v1/synth.metadata
Labels: cla: yes, context: full

#12509 [google-cloud-document_ai-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-document_ai-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-document_ai-v1/synth.metadata
Labels: cla: yes, context: full

#12508 [google-cloud-dataflow-v1beta3] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-dataflow-v1beta3/proto_docs/google/api/field_behavior.rb
  google-cloud-dataflow-v1beta3/synth.metadata
Labels: cla: yes, context: full

#12507 [google-cloud-cloud_dms-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-cloud_dms-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-cloud_dms-v1/synth.metadata
Labels: cla: yes, context: full

#12506 [google-cloud-apigee_connect-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-apigee_connect-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-apigee_connect-v1/synth.metadata
Labels: cla: yes, context: full

#12505 [google-cloud-access_approval-v1] feat: add new FieldBehavior NON_EMPTY_DEFAULT
  google-cloud-access_approval-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-access_approval-v1/synth.metadata
Labels: cla: yes, context: full

#12521 [google-cloud-pubsub-v1] feat: Adding subscription properties to streaming pull response in third party pubsub.proto.
  google-cloud-pubsub-v1/lib/google/pubsub/v1/pubsub_pb.rb
  google-cloud-pubsub-v1/proto_docs/google/pubsub/v1/pubsub.rb
  google-cloud-pubsub-v1/synth.metadata
Labels: cla: yes, context: full

#12522 [google-cloud-spanner-admin-database-v1] feat(spanner): add leader_options to InstanceConfig and default_leader to Database
  google-cloud-spanner-admin-database-v1/lib/google/spanner/admin/database/v1/spanner_database_admin_pb.rb
  google-cloud-spanner-admin-database-v1/proto_docs/google/spanner/admin/database/v1/spanner_database_admin.rb
  google-cloud-spanner-admin-database-v1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#12523 [google-cloud-spanner-admin-instance-v1] feat(spanner): add leader_options to InstanceConfig and default_leader to Database
  google-cloud-spanner-admin-instance-v1/lib/google/spanner/admin/instance/v1/spanner_instance_admin_pb.rb
  google-cloud-spanner-admin-instance-v1/proto_docs/google/spanner/admin/instance/v1/spanner_instance_admin.rb
  google-cloud-spanner-admin-instance-v1/synth.metadata
Labels: api: spanner, cla: yes, context: full

#12532 docs: Update AUTHENTICATION.md in handwritten packages
  google-cloud-bigquery/AUTHENTICATION.md
  google-cloud-bigtable/AUTHENTICATION.md
  google-cloud-datastore/AUTHENTICATION.md
  google-cloud-debugger/AUTHENTICATION.md
  google-cloud-error_reporting/AUTHENTICATION.md
  google-cloud-firestore/AUTHENTICATION.md
  google-cloud-logging/AUTHENTICATION.md
  google-cloud-pubsub/AUTHENTICATION.md
  google-cloud-resource_manager/AUTHENTICATION.md
  google-cloud-spanner/AUTHENTICATION.md
  google-cloud-storage/AUTHENTICATION.md
  google-cloud-trace/AUTHENTICATION.md
  google-cloud-webrisk/AUTHENTICATION.md
Labels: cla: yes

#12528 fix(service_control-v1): Update timeout and retry policy
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/quota_controller_services_pb.rb
  google-cloud-service_control-v1/lib/google/api/servicecontrol/v1/service_controller_services_pb.rb
  google-cloud-service_control-v1/lib/google/cloud/service_control/v1/service_controller/client.rb
  google-cloud-service_control-v1/proto_docs/google/api/distribution.rb
  google-cloud-service_control-v1/proto_docs/google/api/servicecontrol/v1/log_entry.rb
  google-cloud-service_control-v1/proto_docs/google/logging/type/log_severity.rb
  google-cloud-service_control-v1/synth.py
Labels: cla: yes

#12529 fix!(analytics-data-v1alpha): Rename service-specific environment variable prefix to ANALYTICS_DATA
  google-analytics-data-v1alpha/.repo-metadata.json
  google-analytics-data-v1alpha/AUTHENTICATION.md
  google-analytics-data-v1alpha/Rakefile
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data/credentials.rb
  google-analytics-data-v1alpha/lib/google/analytics/data/v1alpha/analytics_data_api_services_pb.rb
  google-analytics-data-v1alpha/proto_docs/google/api/field_behavior.rb
  google-analytics-data-v1alpha/synth.py
Labels: cla: yes

#12530 fix(iam-v1beta): Add project_path helper
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pool_services_pb.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/operations.rb
  google-iam-v1beta/lib/google/iam/v1beta/workload_identity_pools/paths.rb
  google-iam-v1beta/proto_docs/google/api/field_behavior.rb
  google-iam-v1beta/synth.py
  google-iam-v1beta/test/google/iam/v1beta/workload_identity_pools_paths_test.rb
Labels: cla: yes

#12543 chore(asset-v1): Revert bazel migration for asset v1 because it is missing files
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service/operations.rb
  google-cloud-asset-v1/lib/google/cloud/asset/v1/asset_service_services_pb.rb
  google-cloud-asset-v1/proto_docs/google/api/field_behavior.rb
  google-cloud-asset-v1/proto_docs/google/type/expr.rb
  google-cloud-asset-v1/synth.py
Labels: cla: yes

#12540 [CHANGE ME] Re-generated google-cloud-container-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-container-v1beta1/lib/google/container/v1beta1/cluster_service_pb.rb
  google-cloud-container-v1beta1/proto_docs/google/container/v1beta1/cluster_service.rb
  google-cloud-container-v1beta1/synth.metadata
Labels: cla: yes, context: partial

#12541 [CHANGE ME] Re-generated google-cloud-datastore-admin-v1 to pick up changes in the API or client library generator.
  google-cloud-datastore-admin-v1/lib/google/datastore/admin/v1/migration_pb.rb
  google-cloud-datastore-admin-v1/proto_docs/google/datastore/admin/v1/migration.rb
  google-cloud-datastore-admin-v1/synth.metadata
Labels: cla: yes, context: full

#12542 [CHANGE ME] Re-generated google-cloud-kms-v1 to pick up changes in the API or client library generator.
  google-cloud-kms-v1/lib/google/iam/v1/iam_policy_services_pb.rb
  google-cloud-kms-v1/synth.metadata
Labels: cla: yes, context: partial

#12544 [CHANGE ME] Re-generated google-cloud-logging-v2 to pick up changes in the API or client library generator.
  google-cloud-logging-v2/lib/google/logging/type/http_request_pb.rb
  google-cloud-logging-v2/lib/google/logging/type/log_severity_pb.rb
  google-cloud-logging-v2/synth.metadata
Labels: cla: yes, context: full

#12545 [CHANGE ME] Re-generated google-cloud-monitoring-dashboard-v1 to pick up changes in the API or client library generator.
  google-cloud-monitoring-dashboard-v1/lib/google/cloud/monitoring/dashboard/v1/dashboards_service/client.rb
  google-cloud-monitoring-dashboard-v1/lib/google/cloud/monitoring/dashboard/v1/dashboards_service/paths.rb
  google-cloud-monitoring-dashboard-v1/lib/google/monitoring/dashboard/v1/alertchart_pb.rb
  google-cloud-monitoring-dashboard-v1/lib/google/monitoring/dashboard/v1/dashboards_service_pb.rb
  google-cloud-monitoring-dashboard-v1/lib/google/monitoring/dashboard/v1/dashboards_service_services_pb.rb
  google-cloud-monitoring-dashboard-v1/lib/google/monitoring/dashboard/v1/widget_pb.rb
  google-cloud-monitoring-dashboard-v1/proto_docs/google/monitoring/dashboard/v1/alertchart.rb
  google-cloud-monitoring-dashboard-v1/proto_docs/google/monitoring/dashboard/v1/dashboards_service.rb
  google-cloud-monitoring-dashboard-v1/proto_docs/google/monitoring/dashboard/v1/metrics.rb
  google-cloud-monitoring-dashboard-v1/proto_docs/google/monitoring/dashboard/v1/widget.rb
  google-cloud-monitoring-dashboard-v1/proto_docs/google/monitoring/dashboard/v1/xychart.rb
  google-cloud-monitoring-dashboard-v1/synth.metadata
  google-cloud-monitoring-dashboard-v1/test/google/cloud/monitoring/dashboard/v1/dashboards_service_paths_test.rb
  google-cloud-monitoring-dashboard-v1/test/google/cloud/monitoring/dashboard/v1/dashboards_service_test.rb
Labels: cla: yes, context: partial

#12546 [CHANGE ME] Re-generated google-cloud-pubsub-v1 to pick up changes in the API or client library generator.
  google-cloud-pubsub-v1/lib/google/iam/v1/iam_policy_services_pb.rb
  google-cloud-pubsub-v1/synth.metadata
Labels: cla: yes, context: partial

#12547 [CHANGE ME] Re-generated google-cloud-tasks-v2beta2 to pick up changes in the API or client library generator.
  google-cloud-tasks-v2beta2/lib/google/cloud/tasks/v2beta2/old_target_pb.rb
  google-cloud-tasks-v2beta2/synth.metadata
Labels: cla: yes, context: partial

#12654 [CHANGE ME] Re-generated google-iam-credentials to pick up changes in the API or client library generator.
  google-iam-credentials/AUTHENTICATION.md
  google-iam-credentials/synth.metadata
Labels: cla: yes, context: none

#12653 [CHANGE ME] Re-generated google-cloud-workflows to pick up changes in the API or client library generator.
  google-cloud-workflows/AUTHENTICATION.md
  google-cloud-workflows/synth.metadata
Labels: cla: yes, context: none

#12652 [CHANGE ME] Re-generated google-cloud-web_security_scanner to pick up changes in the API or client library generator.
  google-cloud-web_security_scanner/AUTHENTICATION.md
  google-cloud-web_security_scanner/synth.metadata
Labels: cla: yes, context: none

#12651 [CHANGE ME] Re-generated google-cloud-web_risk to pick up changes in the API or client library generator.
  google-cloud-web_risk/AUTHENTICATION.md
  google-cloud-web_risk/synth.metadata
Labels: cla: yes, context: none

#12650 [CHANGE ME] Re-generated google-cloud-vpc_access to pick up changes in the API or client library generator.
  google-cloud-vpc_access/AUTHENTICATION.md
  google-cloud-vpc_access/synth.metadata
Labels: cla: yes, context: none

#12649 [CHANGE ME] Re-generated google-cloud-vision to pick up changes in the API or client library generator.
  google-cloud-vision/AUTHENTICATION.md
  google-cloud-vision/synth.metadata
Labels: cla: yes, context: none

#12648 [CHANGE ME] Re-generated google-cloud-video_intelligence to pick up changes in the API or client library generator.
  google-cloud-video_intelligence/AUTHENTICATION.md
  google-cloud-video_intelligence/synth.metadata
Labels: cla: yes, context: none

#12647 [CHANGE ME] Re-generated google-cloud-video-transcoder to pick up changes in the API or client library generator.
  google-cloud-video-transcoder/AUTHENTICATION.md
  google-cloud-video-transcoder/synth.metadata
Labels: cla: yes, context: none

#12646 [CHANGE ME] Re-generated google-cloud-translate to pick up changes in the API or client library generator.
  google-cloud-translate/AUTHENTICATION.md
  google-cloud-translate/synth.metadata
Labels: cla: yes, context: none

#12645 [CHANGE ME] Re-generated google-cloud-tpu to pick up changes in the API or client library generator.
  google-cloud-tpu/AUTHENTICATION.md
  google-cloud-tpu/synth.metadata
Labels: cla: yes, context: none

#12644 [CHANGE ME] Re-generated google-cloud-text_to_speech to pick up changes in the API or client library generator.
  google-cloud-text_to_speech/AUTHENTICATION.md
  google-cloud-text_to_speech/synth.metadata
Labels: cla: yes, context: none

#12643 [CHANGE ME] Re-generated google-cloud-tasks to pick up changes in the API or client library generator.
  google-cloud-tasks/AUTHENTICATION.md
  google-cloud-tasks/synth.metadata
Labels: cla: yes, context: none

#12642 [CHANGE ME] Re-generated google-cloud-talent to pick up changes in the API or client library generator.
  google-cloud-talent/AUTHENTICATION.md
  google-cloud-talent/synth.metadata
Labels: cla: yes, context: none

#12641 [CHANGE ME] Re-generated google-cloud-speech to pick up changes in the API or client library generator.
  google-cloud-speech/AUTHENTICATION.md
  google-cloud-speech/synth.metadata
Labels: cla: yes, context: none

#12640 [CHANGE ME] Re-generated google-cloud-shell to pick up changes in the API or client library generator.
  google-cloud-shell/AUTHENTICATION.md
  google-cloud-shell/synth.metadata
Labels: cla: yes, context: none

#12639 [CHANGE ME] Re-generated google-cloud-service_usage to pick up changes in the API or client library generator.
  google-cloud-service_usage/AUTHENTICATION.md
  google-cloud-service_usage/synth.metadata
Labels: cla: yes, context: none

#12638 [CHANGE ME] Re-generated google-cloud-service_management to pick up changes in the API or client library generator.
  google-cloud-service_management/AUTHENTICATION.md
  google-cloud-service_management/synth.metadata
Labels: cla: yes, context: none

#12637 [CHANGE ME] Re-generated google-cloud-service_directory to pick up changes in the API or client library generator.
  google-cloud-service_directory/AUTHENTICATION.md
  google-cloud-service_directory/synth.metadata
Labels: cla: yes, context: none

#12636 [CHANGE ME] Re-generated google-cloud-service_control to pick up changes in the API or client library generator.
  google-cloud-service_control/AUTHENTICATION.md
  google-cloud-service_control/synth.metadata
Labels: cla: yes, context: none

#12635 [CHANGE ME] Re-generated google-cloud-security_center to pick up changes in the API or client library generator.
  google-cloud-security_center/AUTHENTICATION.md
  google-cloud-security_center/synth.metadata
Labels: cla: yes, context: none

#12634 [CHANGE ME] Re-generated google-cloud-security-private_ca to pick up changes in the API or client library generator.
  google-cloud-security-private_ca/AUTHENTICATION.md
  google-cloud-security-private_ca/synth.metadata
Labels: cla: yes, context: none

#12633 [CHANGE ME] Re-generated google-cloud-secret_manager to pick up changes in the API or client library generator.
  google-cloud-secret_manager/AUTHENTICATION.md
  google-cloud-secret_manager/synth.metadata
Labels: cla: yes, context: none

#12632 [CHANGE ME] Re-generated google-cloud-scheduler to pick up changes in the API or client library generator.
  google-cloud-scheduler/AUTHENTICATION.md
  google-cloud-scheduler/synth.metadata
Labels: cla: yes, context: none

#12631 [CHANGE ME] Re-generated google-cloud-retail to pick up changes in the API or client library generator.
  google-cloud-retail/AUTHENTICATION.md
  google-cloud-retail/synth.metadata
Labels: cla: yes, context: none

#12630 [CHANGE ME] Re-generated google-cloud-resource_settings to pick up changes in the API or client library generator.
  google-cloud-resource_settings/AUTHENTICATION.md
  google-cloud-resource_settings/synth.metadata
Labels: cla: yes, context: none

#12629 [CHANGE ME] Re-generated google-cloud-redis to pick up changes in the API or client library generator.
  google-cloud-redis/AUTHENTICATION.md
  google-cloud-redis/synth.metadata
Labels: cla: yes, context: none

#12628 [CHANGE ME] Re-generated google-cloud-recommender to pick up changes in the API or client library generator.
  google-cloud-recommender/AUTHENTICATION.md
  google-cloud-recommender/synth.metadata
Labels: cla: yes, context: none

#12627 [CHANGE ME] Re-generated google-cloud-recommendation_engine to pick up changes in the API or client library generator.
  google-cloud-recommendation_engine/AUTHENTICATION.md
  google-cloud-recommendation_engine/synth.metadata
Labels: cla: yes, context: none

#12626 [CHANGE ME] Re-generated google-cloud-recaptcha_enterprise to pick up changes in the API or client library generator.
  google-cloud-recaptcha_enterprise/AUTHENTICATION.md
  google-cloud-recaptcha_enterprise/synth.metadata
Labels: cla: yes, context: none

#12625 [CHANGE ME] Re-generated google-cloud-profiler to pick up changes in the API or client library generator.
  google-cloud-profiler/AUTHENTICATION.md
  google-cloud-profiler/synth.metadata
Labels: cla: yes, context: none

#12624 [CHANGE ME] Re-generated google-cloud-private_catalog to pick up changes in the API or client library generator.
  google-cloud-private_catalog/AUTHENTICATION.md
  google-cloud-private_catalog/synth.metadata
Labels: cla: yes, context: none

#12623 [CHANGE ME] Re-generated google-cloud-policy_troubleshooter to pick up changes in the API or client library generator.
  google-cloud-policy_troubleshooter/AUTHENTICATION.md
  google-cloud-policy_troubleshooter/synth.metadata
Labels: cla: yes, context: none

#12622 [CHANGE ME] Re-generated google-cloud-phishing_protection to pick up changes in the API or client library generator.
  google-cloud-phishing_protection/AUTHENTICATION.md
  google-cloud-phishing_protection/synth.metadata
Labels: cla: yes, context: none

#12621 [CHANGE ME] Re-generated google-cloud-os_login to pick up changes in the API or client library generator.
  google-cloud-os_login/AUTHENTICATION.md
  google-cloud-os_login/synth.metadata
Labels: cla: yes, context: none

#12620 [CHANGE ME] Re-generated google-cloud-os_config to pick up changes in the API or client library generator.
  google-cloud-os_config/AUTHENTICATION.md
  google-cloud-os_config/synth.metadata
Labels: cla: yes, context: none

#12619 [CHANGE ME] Re-generated google-cloud-org_policy to pick up changes in the API or client library generator.
  google-cloud-org_policy/AUTHENTICATION.md
  google-cloud-org_policy/synth.metadata
Labels: cla: yes, context: none

#12618 [CHANGE ME] Re-generated google-cloud-notebooks to pick up changes in the API or client library generator.
  google-cloud-notebooks/AUTHENTICATION.md
  google-cloud-notebooks/synth.metadata
Labels: cla: yes, context: none

#12617 [CHANGE ME] Re-generated google-cloud-network_connectivity to pick up changes in the API or client library generator.
  google-cloud-network_connectivity/AUTHENTICATION.md
  google-cloud-network_connectivity/synth.metadata
Labels: cla: yes, context: none

#12616 [CHANGE ME] Re-generated google-cloud-monitoring to pick up changes in the API or client library generator.
  google-cloud-monitoring/AUTHENTICATION.md
  google-cloud-monitoring/synth.metadata
Labels: cla: yes, context: none

#12614 [CHANGE ME] Re-generated google-cloud-metastore to pick up changes in the API or client library generator.
  google-cloud-metastore/AUTHENTICATION.md
  google-cloud-metastore/synth.metadata
Labels: cla: yes, context: none

#12613 [CHANGE ME] Re-generated google-cloud-memcache to pick up changes in the API or client library generator.
  google-cloud-memcache/AUTHENTICATION.md
  google-cloud-memcache/synth.metadata
Labels: cla: yes, context: none

#12612 [CHANGE ME] Re-generated google-cloud-media_translation to pick up changes in the API or client library generator.
  google-cloud-media_translation/AUTHENTICATION.md
  google-cloud-media_translation/synth.metadata
Labels: cla: yes, context: none

#12611 [CHANGE ME] Re-generated google-cloud-managed_identities to pick up changes in the API or client library generator.
  google-cloud-managed_identities/AUTHENTICATION.md
  google-cloud-managed_identities/synth.metadata
Labels: cla: yes, context: none

#12610 [CHANGE ME] Re-generated google-cloud-life_sciences to pick up changes in the API or client library generator.
  google-cloud-life_sciences/AUTHENTICATION.md
  google-cloud-life_sciences/synth.metadata
Labels: cla: yes, context: none

#12609 [CHANGE ME] Re-generated google-cloud-language to pick up changes in the API or client library generator.
  google-cloud-language/AUTHENTICATION.md
  google-cloud-language/synth.metadata
Labels: cla: yes, context: none

#12608 [CHANGE ME] Re-generated google-cloud-kms to pick up changes in the API or client library generator.
  google-cloud-kms/AUTHENTICATION.md
  google-cloud-kms/synth.metadata
Labels: cla: yes, context: none

#12607 [CHANGE ME] Re-generated google-cloud-iot to pick up changes in the API or client library generator.
  google-cloud-iot/AUTHENTICATION.md
  google-cloud-iot/synth.metadata
Labels: cla: yes, context: none

#12606 [CHANGE ME] Re-generated google-cloud-gke_hub to pick up changes in the API or client library generator.
  google-cloud-gke_hub/AUTHENTICATION.md
  google-cloud-gke_hub/synth.metadata
Labels: cla: yes, context: none

#12605 [CHANGE ME] Re-generated google-cloud-gke_connect-gateway to pick up changes in the API or client library generator.
  google-cloud-gke_connect-gateway/AUTHENTICATION.md
  google-cloud-gke_connect-gateway/synth.metadata
Labels: cla: yes, context: none

#12604 [CHANGE ME] Re-generated google-cloud-gaming to pick up changes in the API or client library generator.
  google-cloud-gaming/AUTHENTICATION.md
  google-cloud-gaming/synth.metadata
Labels: cla: yes, context: none

#12603 [CHANGE ME] Re-generated google-cloud-functions to pick up changes in the API or client library generator.
  google-cloud-functions/AUTHENTICATION.md
  google-cloud-functions/synth.metadata
Labels: cla: yes, context: none

#12602 [CHANGE ME] Re-generated google-cloud-eventarc to pick up changes in the API or client library generator.
  google-cloud-eventarc/AUTHENTICATION.md
  google-cloud-eventarc/synth.metadata
Labels: cla: yes, context: none

#12601 [CHANGE ME] Re-generated google-cloud-essential_contacts to pick up changes in the API or client library generator.
  google-cloud-essential_contacts/AUTHENTICATION.md
  google-cloud-essential_contacts/synth.metadata
Labels: cla: yes, context: none

#12600 [CHANGE ME] Re-generated google-cloud-domains to pick up changes in the API or client library generator.
  google-cloud-domains/AUTHENTICATION.md
  google-cloud-domains/synth.metadata
Labels: cla: yes, context: none

#12599 [CHANGE ME] Re-generated google-cloud-document_ai to pick up changes in the API or client library generator.
  google-cloud-document_ai/AUTHENTICATION.md
  google-cloud-document_ai/synth.metadata
Labels: cla: yes, context: none

#12598 [CHANGE ME] Re-generated google-cloud-dlp to pick up changes in the API or client library generator.
  google-cloud-dlp/AUTHENTICATION.md
  google-cloud-dlp/synth.metadata
Labels: cla: yes, context: none

#12597 [CHANGE ME] Re-generated google-cloud-dialogflow to pick up changes in the API or client library generator.
  google-cloud-dialogflow/AUTHENTICATION.md
  google-cloud-dialogflow/synth.metadata
Labels: cla: yes, context: none

#12596 [CHANGE ME] Re-generated google-cloud-dataqna to pick up changes in the API or client library generator.
  google-cloud-dataqna/AUTHENTICATION.md
  google-cloud-dataqna/synth.metadata
Labels: cla: yes, context: none

#12595 [CHANGE ME] Re-generated google-cloud-dataproc to pick up changes in the API or client library generator.
  google-cloud-dataproc/AUTHENTICATION.md
  google-cloud-dataproc/synth.metadata
Labels: cla: yes, context: none

#12594 [CHANGE ME] Re-generated google-cloud-dataflow to pick up changes in the API or client library generator.
  google-cloud-dataflow/AUTHENTICATION.md
  google-cloud-dataflow/synth.metadata
Labels: cla: yes, context: none

#12593 [CHANGE ME] Re-generated google-cloud-data_labeling to pick up changes in the API or client library generator.
  google-cloud-data_labeling/AUTHENTICATION.md
  google-cloud-data_labeling/synth.metadata
Labels: cla: yes, context: none

#12592 [CHANGE ME] Re-generated google-cloud-data_catalog to pick up changes in the API or client library generator.
  google-cloud-data_catalog/AUTHENTICATION.md
  google-cloud-data_catalog/synth.metadata
Labels: cla: yes, context: none

#12591 [CHANGE ME] Re-generated google-cloud-container_analysis to pick up changes in the API or client library generator.
  google-cloud-container_analysis/AUTHENTICATION.md
  google-cloud-container_analysis/synth.metadata
Labels: cla: yes, context: none

#12590 [CHANGE ME] Re-generated google-cloud-container to pick up changes in the API or client library generator.
  google-cloud-container/AUTHENTICATION.md
  google-cloud-container/synth.metadata
Labels: cla: yes, context: none

#12589 [CHANGE ME] Re-generated google-cloud-cloud_dms to pick up changes in the API or client library generator.
  google-cloud-cloud_dms/AUTHENTICATION.md
  google-cloud-cloud_dms/synth.metadata
Labels: cla: yes, context: none

#12588 [CHANGE ME] Re-generated google-cloud-channel to pick up changes in the API or client library generator.
  google-cloud-channel/AUTHENTICATION.md
  google-cloud-channel/synth.metadata
Labels: cla: yes, context: none

#12587 [CHANGE ME] Re-generated google-cloud-build to pick up changes in the API or client library generator.
  google-cloud-build/AUTHENTICATION.md
  google-cloud-build/synth.metadata
Labels: cla: yes, context: none

#12586 [CHANGE ME] Re-generated google-cloud-binary_authorization to pick up changes in the API or client library generator.
  google-cloud-binary_authorization/AUTHENTICATION.md
  google-cloud-binary_authorization/synth.metadata
Labels: cla: yes, context: none

#12585 [CHANGE ME] Re-generated google-cloud-billing to pick up changes in the API or client library generator.
  google-cloud-billing/AUTHENTICATION.md
  google-cloud-billing/synth.metadata
Labels: cla: yes, context: none

#12584 [CHANGE ME] Re-generated google-cloud-billing-budgets to pick up changes in the API or client library generator.
  google-cloud-billing-budgets/AUTHENTICATION.md
  google-cloud-billing-budgets/synth.metadata
Labels: cla: yes, context: none

#12583 [CHANGE ME] Re-generated google-cloud-bigquery-storage to pick up changes in the API or client library generator.
  google-cloud-bigquery-storage/AUTHENTICATION.md
  google-cloud-bigquery-storage/synth.metadata
Labels: cla: yes, context: none

#12582 [CHANGE ME] Re-generated google-cloud-bigquery-reservation to pick up changes in the API or client library generator.
  google-cloud-bigquery-reservation/AUTHENTICATION.md
  google-cloud-bigquery-reservation/synth.metadata
Labels: cla: yes, context: none

#12581 [CHANGE ME] Re-generated google-cloud-bigquery-data_transfer to pick up changes in the API or client library generator.
  google-cloud-bigquery-data_transfer/AUTHENTICATION.md
  google-cloud-bigquery-data_transfer/synth.metadata
Labels: cla: yes, context: none

#12580 [CHANGE ME] Re-generated google-cloud-bigquery-connection to pick up changes in the API or client library generator.
  google-cloud-bigquery-connection/AUTHENTICATION.md
  google-cloud-bigquery-connection/synth.metadata
Labels: cla: yes, context: none

#12579 [CHANGE ME] Re-generated google-cloud-automl to pick up changes in the API or client library generator.
  google-cloud-automl/AUTHENTICATION.md
  google-cloud-automl/synth.metadata
Labels: cla: yes, context: none

#12578 [CHANGE ME] Re-generated google-cloud-assured_workloads to pick up changes in the API or client library generator.
  google-cloud-assured_workloads/AUTHENTICATION.md
  google-cloud-assured_workloads/synth.metadata
Labels: cla: yes, context: none

#12577 [CHANGE ME] Re-generated google-cloud-asset to pick up changes in the API or client library generator.
  google-cloud-asset/AUTHENTICATION.md
  google-cloud-asset/synth.metadata
Labels: cla: yes, context: none

#12575 [CHANGE ME] Re-generated google-cloud-artifact_registry to pick up changes in the API or client library generator.
  google-cloud-artifact_registry/AUTHENTICATION.md
  google-cloud-artifact_registry/synth.metadata
Labels: cla: yes, context: none

#12574 [CHANGE ME] Re-generated google-cloud-app_engine to pick up changes in the API or client library generator.
  google-cloud-app_engine/AUTHENTICATION.md
  google-cloud-app_engine/synth.metadata
Labels: cla: yes, context: none

#12573 [CHANGE ME] Re-generated google-cloud-apigee_connect to pick up changes in the API or client library generator.
  google-cloud-apigee_connect/AUTHENTICATION.md
  google-cloud-apigee_connect/synth.metadata
Labels: cla: yes, context: none

#12572 [CHANGE ME] Re-generated google-cloud-api_gateway to pick up changes in the API or client library generator.
  google-cloud-api_gateway/AUTHENTICATION.md
  google-cloud-api_gateway/synth.metadata
Labels: cla: yes, context: none

#12571 [CHANGE ME] Re-generated google-cloud-access_approval to pick up changes in the API or client library generator.
  google-cloud-access_approval/AUTHENTICATION.md
  google-cloud-access_approval/synth.metadata
Labels: cla: yes, context: none

#12570 [CHANGE ME] Re-generated google-area120-tables to pick up changes in the API or client library generator.
  google-area120-tables/AUTHENTICATION.md
  google-area120-tables/synth.metadata
Labels: cla: yes, context: none

#12569 [CHANGE ME] Re-generated google-analytics-data to pick up changes in the API or client library generator.
  google-analytics-data/AUTHENTICATION.md
  google-analytics-data/synth.metadata
Labels: cla: yes, context: none

#12568 [CHANGE ME] Re-generated google-analytics-admin to pick up changes in the API or client library generator.
  google-analytics-admin/AUTHENTICATION.md
  google-analytics-admin/synth.metadata
Labels: cla: yes, context: none

#12615 [CHANGE ME] Re-generated google-cloud-monitoring-v3 to pick up changes in the API or client library generator.
  google-cloud-monitoring-v3/AUTHENTICATION.md
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/alert_policy_service/paths.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/group_service/paths.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/notification_channel_service/paths.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/service_monitoring_service/paths.rb
  google-cloud-monitoring-v3/lib/google/cloud/monitoring/v3/uptime_check_service/paths.rb
  google-cloud-monitoring-v3/synth.metadata
  google-cloud-monitoring-v3/test/google/cloud/monitoring/v3/alert_policy_service_paths_test.rb
  google-cloud-monitoring-v3/test/google/cloud/monitoring/v3/group_service_paths_test.rb
  google-cloud-monitoring-v3/test/google/cloud/monitoring/v3/notification_channel_service_paths_test.rb
  google-cloud-monitoring-v3/test/google/cloud/monitoring/v3/service_monitoring_service_paths_test.rb
  google-cloud-monitoring-v3/test/google/cloud/monitoring/v3/uptime_check_service_paths_test.rb
Labels: cla: yes, context: none

#12664 [CHANGE ME] Re-generated google-cloud-assured_workloads-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-assured_workloads-v1beta1/AUTHENTICATION.md
  google-cloud-assured_workloads-v1beta1/synth.metadata
Labels: cla: yes, context: full

#12663 [CHANGE ME] Re-generated google-cloud-artifact_registry-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-artifact_registry-v1beta2/AUTHENTICATION.md
  google-cloud-artifact_registry-v1beta2/synth.metadata
Labels: cla: yes, context: full

#12662 [CHANGE ME] Re-generated google-cloud-app_engine-v1 to pick up changes in the API or client library generator.
  google-cloud-app_engine-v1/AUTHENTICATION.md
  google-cloud-app_engine-v1/synth.metadata
Labels: cla: yes, context: full

#12660 [CHANGE ME] Re-generated google-cloud-api_gateway-v1 to pick up changes in the API or client library generator.
  google-cloud-api_gateway-v1/AUTHENTICATION.md
  google-cloud-api_gateway-v1/synth.metadata
Labels: cla: yes, context: partial

#12658 [CHANGE ME] Re-generated google-area120-tables-v1alpha1 to pick up changes in the API or client library generator.
  google-area120-tables-v1alpha1/AUTHENTICATION.md
  google-area120-tables-v1alpha1/synth.metadata
Labels: cla: yes, context: partial

#12656 [CHANGE ME] Re-generated google-analytics-data-v1alpha to pick up changes in the API or client library generator.
  google-analytics-data-v1alpha/AUTHENTICATION.md
  google-analytics-data-v1alpha/synth.metadata
Labels: cla: yes, context: full

#12655 [CHANGE ME] Re-generated google-analytics-admin-v1alpha to pick up changes in the API or client library generator.
  google-analytics-admin-v1alpha/AUTHENTICATION.md
  google-analytics-admin-v1alpha/synth.metadata
Labels: cla: yes, context: partial

#12576 [CHANGE ME] Re-generated google-cloud-asset-v1 to pick up changes in the API or client library generator.
  google-cloud-asset-v1/AUTHENTICATION.md
  google-cloud-asset-v1/synth.metadata
Labels: cla: yes, context: none

#12661 [google-cloud-apigee_connect-v1] chore(ruby): Switch Bazel jobs to use the Ruby gapic-generator 0.9.1
  google-cloud-apigee_connect-v1/AUTHENTICATION.md
  google-cloud-apigee_connect-v1/synth.metadata
Labels: cla: yes, context: full

#12659 [google-cloud-access_approval-v1] chore(ruby): Switch Bazel jobs to use the Ruby gapic-generator 0.9.1
  google-cloud-access_approval-v1/AUTHENTICATION.md
  google-cloud-access_approval-v1/synth.metadata
Labels: cla: yes, context: full

#12657 [google-analytics-data-v1beta] chore(ruby): Switch Bazel jobs to use the Ruby gapic-generator 0.9.1
  google-analytics-data-v1beta/AUTHENTICATION.md
  google-analytics-data-v1beta/synth.metadata
Labels: cla: yes, context: full

#12877 [CHANGE ME] Re-generated google-iam-v1beta to pick up changes in the API or client library generator.
  google-iam-v1beta/AUTHENTICATION.md
  google-iam-v1beta/synth.metadata
Labels: cla: yes

#12876 [CHANGE ME] Re-generated google-iam-credentials-v1 to pick up changes in the API or client library generator.
  google-iam-credentials-v1/AUTHENTICATION.md
  google-iam-credentials-v1/synth.metadata
Labels: cla: yes

#12875 [CHANGE ME] Re-generated google-cloud-workflows-v1beta to pick up changes in the API or client library generator.
  google-cloud-workflows-v1beta/AUTHENTICATION.md
  google-cloud-workflows-v1beta/synth.metadata
Labels: cla: yes

#12874 [CHANGE ME] Re-generated google-cloud-workflows-v1 to pick up changes in the API or client library generator.
  google-cloud-workflows-v1/AUTHENTICATION.md
  google-cloud-workflows-v1/synth.metadata
Labels: cla: yes

#12873 [CHANGE ME] Re-generated google-cloud-workflows-executions-v1beta to pick up changes in the API or client library generator.
  google-cloud-workflows-executions-v1beta/AUTHENTICATION.md
  google-cloud-workflows-executions-v1beta/synth.metadata
Labels: cla: yes

#12872 [CHANGE ME] Re-generated google-cloud-web_security_scanner-v1beta to pick up changes in the API or client library generator.
  google-cloud-web_security_scanner-v1beta/AUTHENTICATION.md
  google-cloud-web_security_scanner-v1beta/synth.metadata
Labels: cla: yes

#12871 [CHANGE ME] Re-generated google-cloud-web_security_scanner-v1 to pick up changes in the API or client library generator.
  google-cloud-web_security_scanner-v1/AUTHENTICATION.md
  google-cloud-web_security_scanner-v1/synth.metadata
Labels: cla: yes

#12870 [CHANGE ME] Re-generated google-cloud-web_risk-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1beta1/AUTHENTICATION.md
  google-cloud-web_risk-v1beta1/synth.metadata
Labels: cla: yes

#12869 [CHANGE ME] Re-generated google-cloud-web_risk-v1 to pick up changes in the API or client library generator.
  google-cloud-web_risk-v1/AUTHENTICATION.md
  google-cloud-web_risk-v1/synth.metadata
Labels: cla: yes

#12868 [CHANGE ME] Re-generated google-cloud-vpc_access-v1 to pick up changes in the API or client library generator.
  google-cloud-vpc_access-v1/AUTHENTICATION.md
  google-cloud-vpc_access-v1/synth.metadata
Labels: cla: yes

#12867 [CHANGE ME] Re-generated google-cloud-vision-v1p3beta1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1p3beta1/AUTHENTICATION.md
  google-cloud-vision-v1p3beta1/synth.metadata
Labels: cla: yes

#12866 [CHANGE ME] Re-generated google-cloud-vision-v1 to pick up changes in the API or client library generator.
  google-cloud-vision-v1/AUTHENTICATION.md
  google-cloud-vision-v1/synth.metadata
Labels: cla: yes

#12865 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p2beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p2beta1/AUTHENTICATION.md
  google-cloud-video_intelligence-v1p2beta1/synth.metadata
Labels: cla: yes

#12864 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1p1beta1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1p1beta1/AUTHENTICATION.md
  google-cloud-video_intelligence-v1p1beta1/synth.metadata
Labels: cla: yes

#12863 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1beta2 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1beta2/AUTHENTICATION.md
  google-cloud-video_intelligence-v1beta2/synth.metadata
Labels: cla: yes

#12862 [CHANGE ME] Re-generated google-cloud-video_intelligence-v1 to pick up changes in the API or client library generator.
  google-cloud-video_intelligence-v1/AUTHENTICATION.md
  google-cloud-video_intelligence-v1/synth.metadata
Labels: cla: yes

#12861 [CHANGE ME] Re-generated google-cloud-video-transcoder-v1beta1 to pick up changes in the API or client library generator.
  google-cloud-video-transcoder-v1beta1/AUTHENTICATION.md
  google-cloud-video-transcoder-v1beta1/synth.metadata
Labels: cla: yes

#12860 [CHANGE ME] Re-generated google-cloud-translate-v3 to pick up changes in the API or client library generator.
  google-cloud-translate-v3/AUTHENTICATION.md
  google-cloud-translate-v3/synth.metadata
Labels: cla: yes

#12859 [CHANGE ME] Re-generated google-cloud-trace-v2 to pick up changes in the API or client library generator.
  google-cloud-trace-v2/AUTHENTICATION.md
  google-cloud-trace-v2/synth.metadata
Labels: cla: yes

#12858 [CHANGE ME] Re-generated google-cloud-trace-v1 to pick up changes in the API or client library generator.
  google-cloud-trace-v1/AUTHENTICATION.md
  google-cloud-trace-v1/synth.metadata
Labels: cla: yes

#12857 [CHANGE ME] Re-generated google-cloud-tpu-v1 to pick up changes in the API or client library generator.
  google-cloud-tpu-v1/AUTHENTICATION.md
  google-cloud-tpu-v1/synth.metadata
Labels: cla: yes
