Repository googleapis/google-cloud-ruby, pull requests merged in 2022-04, with the labels that each got.

#17950 samples(storage): Add stream samples for Cloud Storage
  google-cloud-storage/samples/acceptance/files_test.rb
  google-cloud-storage/samples/storage_download_byte_range.rb
  google-cloud-storage/samples/storage_stream_file_download.rb
  google-cloud-storage/samples/storage_stream_file_upload.rb
Labels: api: storage, kokoro:force-run, samples

#18004 chore(main): release google-cloud-compute-v1 1.3.0
  .release-please-manifest.json
  google-cloud-compute-v1/CHANGELOG.md
  google-cloud-compute-v1/lib/google/cloud/compute/v1/version.rb
Labels: autorelease: pending

#18007 chore(main): release google-cloud-bigquery-reservation-v1 0.5.0
  .release-please-manifest.json
  google-cloud-bigquery-reservation-v1/CHANGELOG.md
  google-cloud-bigquery-reservation-v1/lib/google/cloud/bigquery/reservation/v1/version.rb
Labels: autorelease: pending

#18008 chore(main): release google-cloud-data_catalog-v1 0.11.0
  .release-please-manifest.json
  google-cloud-data_catalog-v1/CHANGELOG.md
  google-cloud-data_catalog-v1/lib/google/cloud/data_catalog/v1/version.rb
Labels: autorelease: pending

#18009 chore(main): release google-cloud-monitoring-dashboard-v1 0.7.0
  .release-please-manifest.json
  google-cloud-monitoring-dashboard-v1/CHANGELOG.md
  google-cloud-monitoring-dashboard-v1/lib/google/cloud/monitoring/dashboard/v1/version.rb
Labels: autorelease: pending

#18011 chore(main): release google-cloud-security_center-v1 0.14.0
  .release-please-manifest.json
  google-cloud-security_center-v1/CHANGELOG.md
  google-cloud-security_center-v1/lib/google/cloud/security_center/v1/version.rb
Labels: autorelease: pending

#18012 chore(main): release google-cloud-deploy-v1 0.2.0
  .release-please-manifest.json
  google-cloud-deploy-v1/CHANGELOG.md
  google-cloud-deploy-v1/lib/google/cloud/deploy/v1/version.rb
Labels: autorelease: pending

#18014 chore(main): release google-cloud-gke_hub-v1 0.2.0
  .release-please-manifest.json
  google-cloud-gke_hub-v1/CHANGELOG.md
  google-cloud-gke_hub-v1/lib/google/cloud/gke_hub/v1/version.rb
Labels: autorelease: pending

#18025 chore(main): release google-cloud-tasks-v2 0.5.0
  .release-please-manifest.json
  google-cloud-tasks-v2/CHANGELOG.md
  google-cloud-tasks-v2/lib/google/cloud/tasks/v2/version.rb
Labels: autorelease: pending

#18024 chore(main): release google-cloud-speech-v1 0.7.2
  .release-please-manifest.json
  google-cloud-speech-v1/CHANGELOG.md
  google-cloud-speech-v1/lib/google/cloud/speech/v1/version.rb
Labels: autorelease: pending

#18034 chore(main): release google-cloud-dialogflow-cx-v3 0.7.1
  .release-please-manifest.json
  google-cloud-dialogflow-cx-v3/CHANGELOG.md
  google-cloud-dialogflow-cx-v3/lib/google/cloud/dialogflow/cx/v3/version.rb
Labels: autorelease: pending

#18086 fix(pubsub): ignore grpc errors on ack/modack
  google-cloud-pubsub/lib/google/cloud/pubsub/service.rb
  google-cloud-pubsub/test/google/cloud/pubsub/service_test.rb
Labels: api: pubsub
