Repository googleapis/google-cloud-ruby, pull requests merged in 2022-05, with the labels that each got.

#18291 chore(asset): remove google-cloud-asset-v1beta1 from dependencies
  google-cloud-asset/samples/Gemfile
Labels: api: cloudasset

#18271 fix(google-cloud-bigtable): fix reads_prefix sample
  google-cloud-bigtable/samples/acceptance/read_samples_test.rb
  google-cloud-bigtable/samples/read_samples.rb
Labels: samples

#18319 fix(trace): wrap patched methods into class to ignore yard parsing
  google-cloud-trace/lib/google/cloud/trace/patches/active_call_with_trace.rb
  google-cloud-trace/lib/google/cloud/trace/patches/call_with_trace.rb
Labels: api: cloudtrace
